### ISSUE TITLE
Help with ExchangeError

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#1010]
Hello, 

Sometimes I get an ExchangeError that is retry'able because the exchange has problems. For example:

```
ccxt.base.errors.ExchangeError: kucoin 404
ccxt.base.errors.ExchangeError: kucoin 502 <html>
```
In other situations however, it's not retry'able because I just did something stupid. For example:
`ccxt.base.errors.ExchangeError: kucoin fetchOpenOrders requires a symbol param`

How can I differentiate between the two ? Now I'm retry'ing all ExchangeErrors, but in some cases this is not very useful.

Thanks!

**Comment by kroitor** [comment]
Hi!

> Sometimes I get an ExchangeError that is retry'able

In those cases you should get a NetworkError (another branch of errors, those you can recover from). The ExchangeError should stand for non-recoverable errors, like, when you missed a `symbol`. 

However, because we are under active development, the process of unification, including the unified error handling, is not finished yet, as you may know. So, in some cases, like that of Kucoin you can get an ExchangeError where in fact you should've get a NetworkError – that would indicate an inconsistency in the library. If you are sure that the error was recoverable (like `too many requests` or whatever network error) and the error type was not detected correctly, please report all such cases, and we will eventually be able to fix them all. But, please, note that in order to recognize the error properly we need to see the verbose output (what exactly is sent to in response from their API). We will be happy if you help us fix them.

> How can I differentiate between the two ?

Catch NetworkErrors and retry, catch ExchangeErrors and do not retry. Catch ExchangeError where it should be a NetworkError and report )

Does this answer your questions?

**Comment by kroitor** [comment]
P.S.You want to catch those cases specifically add this around your code:

```Python
try:
    YOUR_CODE
except ExchangeError as e:
    print('BAD ERROR CAUGHT')
    print(exchange.last_http_response)
    raise
```

**Comment by gaardiolor** [comment]
ok thanks! Of course I can get verbose output, but, isn't it better to handle it in a more generalized way and raise networkerror on all HTTP error codes (4xx, 5xx) ?

**Comment by kroitor** [comment]
@gaardiolor 

> isn't it better to handle it in a more generalized way and raise networkerror on all HTTP error codes (4xx, 5xx) ?

No, it isn't)

Exchanges report errors differently, and many of them report 429 for a NetworkError, for example... So, you can't distinguish by HTTP code, it will always be 4xx. We have to distinguish by their message/code. And for that we have to see it.

**Comment by kroitor** [comment]
I'm closing this for now. Feel free to reopen it or just ask questions here. Or add a new issue, if needed. Thx.
