### ISSUE TITLE
Question: best practice to fetch all transactions/ledgers

### ISSUE THREAD

**Issue by steebchen** [ccxt/ccxt#10110]
I just have a general question of whether there are any best practices for fetching all transactions/ledger items for a given account. Exchanges like Binance have a lot of currencies so going through all of those for an account seems overkill and slow. I was thinking about fetching the account's balances and then just fetching transactions/ledger entries for those returned currency codes, but that doesn't work if the user used to have a currency but does not anymore (except if there's dust left). Is there any other way to do this without having to go through all currency codes an exchange has?

**Comment by ttodua** [comment]
Well, I think there is no common way to get all transactions of all currencies universally over all exchanges. Part of exchanges might have a 'bulk' way but other exchanges may not. 
I advise to do a bit more research into the specific exchange API DOCS you are interested in, and find out there, if they support bulk/batch endpoint for getting all transactions, then it means it will be callable from CCXT (mostly with implicit API).

Another way you was mentioning, might be to iterate through your last X (i.e. 100) withdrawal/deposits and also trades, and from there, list-out all currencies, create an array, and iterate only through those array. This will much narrow-down your diapason (instead of iterating through all 700s currencies).  Or maybe you have a thought yourself, in what ways you have interacted with those currencies (other than deposit/withdrawal or trading) and try to get the list of 'those' coins that way, and after you have the desired list of coins, iterate through those currencies to fetch transactions for them.  

let us know if any issue there.
