### ISSUE TITLE
Binance: "Fee charged in different currencies" for SOL/BTC

### ISSUE THREAD

**Issue by Bomper** [ccxt/ccxt#10130]
I was running the example I submitted long time ago at #1079. For the SOL/BTC pair, it returned the following error:

```
throw new Error(`Fee charged in different currencies for order ${t.order}. Please file an issue.`);
```

I've seen Binance charge the fee in BNB for pairs such as SOL/BUSD.

But the error is not clear. Was the fee charged in more than one currency? "different currencies" from what? The base or the quote? Why not "in a different currency" (singular)?

- OS: Linux
- Programming Language version: Node 16.9.1
- CCXT version: 1.57.45

**Comment by kroitor** [comment]
@Bomper

> throw new Error(`Fee charged in different currencies for order ${t.order}. Please file an issue.`);
> Why not "in a different currency" (singular)?

That message is not from CCXT, though, it is from the example – some orders may have fees in varying currencies, since orders can be filled partially. It depends on your settings with Binance. If you have enabled paying fees in BNB, then, if you have BNB on your account, the fees will get paid in BNB (usually, at a discount). If you run out of BNB, the fees will be paid in the currency you get. Does that help?

**Comment by Bomper** [comment]
Duh, I should have checked my own code. Sorry for being an idiot :smile:

I've fixed the example to only roll up trades within the same order if the fee currency was the same. I could update it happily but I see there was not much interest in that example since 2018.
