### ISSUE TITLE
just my suggestion 

### ISSUE THREAD

**Issue by Taylorlewis374** [ccxt/ccxt#1032]
PASTE_YOUR_TEXT_DESCRIPTION_HERE

- OS: Windows 10
- Programming Language:python
- CCXT version:
- Exchange:kroitor/BTC
- Method:

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

MUST_READ_THIS https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

REPLACE_WITH_YOUR_CODE_TO_REPRODUCE_THE_BUG_HERE

example 1: ccxt.poloniex ({'verbose': True}).fetchTicker ('ETH/BTC')

example 2: exchange = ccxt.bittrex ()
           exchange.verbose = True
           exchange.fetchOrderBook ('ETH/BTC')

REPLACE_WITH_YOUR_VERBOSE_OUTPUT_HERE

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by kroitor** [comment]
?

**Comment by Taylorlewis374** [comment]
Can you teach me how to make some btc ?

**Comment by kroitor** [comment]
@Taylorlewis374 but why don't you want to learn it yourself like I did and like everybody else does? ) You don't live in an info-vacuum, or do you? ) I'm sorry, but I don't have enough time to teach everyone individually. I'm putting everything in public so that you can use it, but I'm not going to put it info in your brain and I'm not going to do the reading/thinking effort for you. Even if I wanted to, that would be physically impossible to do in a single lifetime. Moreover, I'm mostly learning myself. So, I guess, there is now shortcut, you have to start reading everything around here and elsewhere (links from here).

- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/network/dependents

I'm closing this for now if you don't mind. You can reopen it if needed, or just ask questions (if you have any specific problems with the library). I can't teach you how to make money. Sorry.

**Comment by Taylorlewis374** [comment]
*{
            -ms-text-size-adjust:100%;
            -webkit-text-size-adjust:none;
            -webkit-text-resize:100%;
            text-resize:100%;
        }
        a{outline:none;}
        @media only screen and (max-width:500px) {
            table[class="wrapper"]{min-width:320px !important;}
            table[class="flexible"]{width:100% !important;}
            td[class="hide"],
            td[class="hide"] img,
            span[class="hide"],
            br[class="hide"],
            td[class="fix-gmail"]{
                display:none !important;
                width:0 !important;
                height:0 !important;
                padding:0 !important;
                font-size:0 !important;
                line-height:0 !important;
            }
            td[class="img-flex"] img{
                width:100% !important;
                height:auto !important;
            }
            td[class="aligncenter"]{text-align:center !important;}
            td[class="indent-01"]{padding:10px !important;}
        }
    
    




    
        
            
                 
                
                    
                
                
                    Message from: taylorlewis374@gmail.com
                
                
                    I got tired of waiting on the bank to deposit my checks and standing in line to cash them, so I tried the Ingo Money App. Now I cash my checks right on my phone. My money is in my account in a couple of minutes and I can immediately make purchases, pay my bills or get cash at an ATM.They charge a fee to get your money fast, but it's worth the time and money I save.Give it a try and see what you think. Just click the image to register and then download the app. If you cash a check by 5/31/18, we'll both get $15!
                
                
                    9663 Santa Monica Blvd. Suite 184, Beverly Hills, CA 90210if you do not wish to receive promotions like this one, opt out here.
                
                
                    powered by: friendbuy
