### ISSUE TITLE
Question: Bitstamp placing limit orders

### ISSUE THREAD

**Issue by DanielMartini** [ccxt/ccxt#1036]
- Programming Language: PHP
- CCXT version: 1.10.513
- Exchange: Bitstamp
- Method: createLimitBuyOrder

Hello,

I've been trying to place limit orders in bitstamp without success, the point is that im receiving an error that I don't have enough funds to place the order.

My formula for calculate the amount of coins I can buy with certain balance and price is the next:

```(balance / price) - ((balance / price) * fee)```

I've been checking the javascript code of bitstamp tradeview and has the same as me, but the difference is that the API is asking me for more money when I submit the order.

ccxt is applying always the 0.25 for bitstamp at the moment (higher tier on bitstamp) so i don't think it's a fee problem.

I'm testing with this numbers (with 0.24%):

```(5.88 / 1.79729 ) - ((5.88 / 1.79729) * 0.0024) = 3.2637404```

and I'm getting this response:

```You need 5.88589 EUR to open that order. You have only 5.88334 EUR available. Check your account balance for details.```

I've been checking the [fee schedule](https://www.bitstamp.net/fee_schedule/) and I saw this:

``` Please note: All non-USD trading volumes are converted to USD using a spot exchange rate at the time of each trade. ```

Maybe this is affecting on the issue? I'm wondering if someone has achieved to place an order using all the funds or if bitstamp has an special fee for use the API or some idea what could be wrong

PS: sorry if the question is not applying directly to the library, don't hesitate to close it if you feel so

Thanks.

**Comment by kroitor** [comment]
> Maybe this is affecting on the issue? 

You should make and run the tests:
1. Calculate expected fees on both sides
2. Place sell order, assert expected vs actual fees on both sides with respect to USD rate at the time of the filling trades
3. Place buy order, assert expected vs actual fees on both sides with respect to USD rate at the time of the filling trades
4. From there you can deduce their exact fee schedule arithmetics to calculate the amount precisely.
5. Most often you can't use the entire amount because of floating conversion rates, so you need to have slightly more on your account anyways.

Sorry, but apart from that, I'm afraid, we can't help without actually having access to your account, balances, all that. I would close this for now, if you don't mind. Feel free to ask questions or to reopen it if needed.
