### ISSUE TITLE
Fetching more than 'limit' Klines

### ISSUE THREAD

**Issue by distantrainbow** [ccxt/ccxt#10396]
Hello,

It's not an issue in the meaning of a bug, but a feature request:
Binance enables to fetch ohlc data from start to end date. This approach enables in a loop to retrieve a '1m' candles data for the last week, for example, each iteration retrieving 'limit=1000' samples.
From the other hand, CCXT has only the 'since' argument, which enables using only the start_date until current time. With such an approach there's no way to make the loop for getting more than 1000 samples.

Please enable such an option by changing 'fetch_ohlcv' signature or by some other way.

Thanks.

**Comment by kroitor** [comment]
Hi!

> From the other hand, CCXT has only the 'since' argument, which enables using only the start_date until current time. With such an approach there's no way to make the loop for getting more than 1000 samples.

It is in fact very possible. You just shift the `since` argument going over time.

Please, check these links: 

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv-to-csv.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-ohlcv-sequentially.py
- https://github.com/ccxt/ccxt/tree/master/examples/py
- https://github.com/ccxt/ccxt/tree/master/examples/

Let us know if that does not answer your question.

**Comment by distantrainbow** [comment]
Hmm.. you totally right. Thanks.
