### ISSUE TITLE
Kucoin transfers to subaccount 

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#10418]
- OS: Windows 10
- Programming Language version: Python 3.8.10
- CCXT version: 1.58.25

I have a question rather than a problem, is it possible to transfer assets from my main account on Kucoin to one of my subaccounts by using CCXT? I looked at the transfer method but it only seems to work for internal transfers within your account. When I looked at the Kucoin API documentation they seem to have an endpoint for sub-account transfers. 

Thank you for the help.

**Comment by drsavant-pub** [comment]
Try the ccxt implicit method:  
```
privatePostAccountsSubTransfer(clientOid, currency, amount, direction, accountType, subAccountType, subUserId)
```
Parameters explained here: [Link](https://docs.kucoin.com/?lang=en_US#transfer-between-master-user-and-sub-user)

You should be able to get the subUserID by loggng into your account, otherwise use this ccxt implicit method:
```
privateGetSubUser()
```
See responses for privateGetSubUser() here: [Link](https://docs.kucoin.com/?lang=en_US#get-user-info-of-all-sub-accounts)

**Note**: I'm using nodejs therefore these implicit functions were derived from there.  If these don't work in python then use the ccxt manual link below to generate a list of implicit functions using a python example: print(dir(ccxt.kucoin()))

Implicit methods can be understood by going to the ccxt manual here: [Link](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods)

**Comment by kroitor** [comment]
Also, to add to the above, an example is available here: https://github.com/DoctorSlimm/ccxt/commit/1d52819bf940459c92e0af51db2861fbc1f7d7fc

Hope that helps.

**Comment by kroitor** [comment]
P.S. you can also use the unified `transfer` method from here: https://github.com/ccxt/ccxt/blob/master/python/ccxt/kucoin.py#L1994
