### ISSUE TITLE
Daily historic balance in BTC/USD

### ISSUE THREAD

**Issue by dorienh** [ccxt/ccxt#10600]
I know the fetchBalance method, but I was wondering if there is an easy way to fetch a history of the daily balance in usd/btc over a period of time without having to manually process the orderbook/historic prices?

**Comment by kroitor** [comment]
Hello! At this time most of the underlying exchanges' APIs don't provide the endpoints for balance histories. Some exchanges might have those endpoints with certain limitations (https://binance-docs.github.io/apidocs/spot/en/#daily-account-snapshot-user_data), and you could use those through implicit API methods with ccxt (https://github.com/ccxt/ccxt/wiki/Manual#implicit-api). Yet, there is no unified API method for that, cause this functionality is still very new and rare. 

The general approach to solving the problem is tracking your balances continuously and also tracking the prices at the time, synchronizing the two histories. Hope that answers your question, let us know if not. Feel free to reopen it or just ask further questions if any.
