### ISSUE TITLE
poloniex nonce error. override doesn't work. fresh api key and secret.

### ISSUE THREAD

**Issue by hippylover** [ccxt/ccxt#1063]
Hi im using python. Newest ccxt from pip install ccxt(how can i get the one from github if i want the latest-latest?)

```
exchanges = {}
exchanges['poloniex'] = ccxt.poloniex({'nonce': ccxt.Exchange.microseconds})
exchanges['poloniex'].apiKey = 'fakeapikey'
exchanges['poloniex'].secret = 'fakesecret'

exchanges['poloniex'].loadMarkets()
balances = exchanges['poloniex'].fetchBalance()

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 325, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kris/exchangescripts/ccex_examples/instantiate-all-at-once.py", line 39, in <module>
    balances = exchanges['poloniex'].fetchBalance()
  File "/usr/lib/python3.6/site-packages/ccxt/poloniex.py", line 213, in fetch_balance
    }, params))
  File "/usr/lib/python3.6/site-packages/ccxt/poloniex.py", line 685, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 283, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 341, in fetch
    self.handle_rest_errors(e, e.code, message if message else text, url, method)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 369, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 265, in raise_error
    details,
ccxt.base.errors.ExchangeNotAvailable: poloniex POST https://poloniex.com/tradingApi 422   {"error":"Nonce must be greater than 1515053336171833515. You provided 1515064679565070."}
```
Iv'e tried without overriding, with microseconds, milliseconds and seconds and it used fresh apikey and secret... It was strange because i seem to remember having gotten it working once after i switched api keys but i might be mistaken because i tried a lot of exchanges. What is clear is theres new api key and secret now but it still doesn't work.

**Comment by kroitor** [comment]
Hi!

> Iv'e tried without overriding, with microseconds, milliseconds and seconds

No need for that ) You basically screwed your nonce number because you actually tried various scales for values, whereas you should only redefine it if you have a nonce problem with a fresh key.

> and it used fresh apikey and secret... 

Here's a snippet of code with my fresh API key and secret, does it work for you?

```Python
# -*- coding: utf-8 -*-

import ccxt
from pprint import pprint

exchange = ccxt.poloniex({
    'apiKey': 'LB262URX-V3YPMSZI-1MS07316-V5W38QVK',
    'secret': '97f9abf2ee2a1672f7b66f4c233e77dc1b02d237a4bfe7d2a333d6cf66f17bf093615039d4010cb424e908dcafe7ebbf203bd619193319d6ad6f02598d08bb62',
    'enableRateLimit': True,  # this option enables the built-in rate limiter
})

currency = 'BTC'

for i in range(0, 10):
    datetime = exchange.iso8601 (exchange.milliseconds ())
    balance = exchange.fetch_total_balance()
    pprint('------------------------------------------------------------------')
    pprint(datetime + ' ' + currency + ' balance:')
    pprint(balance['BTC'])
```

If the above does work for you, then it means that you were not careful when choosing you keys and redefining nonce values for them. You don't need to redefine the nonce at all, unless you see a nonce error. You only need to redefine it, if you see a nonce error. But you should not see a nonce error in the first place, if you have the keys set up correctly and if you are not hitting the rate limiter. If you see a nonce error then you should read what it says and try to understand it. In case you don't understand it – you can ask a question here. The default nonce for Poloniex is in milliseconds.

> It was strange because i seem to remember having gotten it working once after i switched api keys but i might be mistaken because i tried a lot of exchanges. 

Right: there's no point in trying seconds-nonce after the milliseconds nonce. It won't work.

> What is clear is theres new api key and secret now but it still doesn't work.

It isn't clear ) You think this is a new key, but after you already used it with a milliseconds-nonce, it is *not new* anymore. A new key is a key that has not been used previously at all. If you tried a key, and it didn't work, then you tried to redefine a nonce, and it didn't work either – delete that key and create a new one.

Let me know if the above helps.

**Comment by kroitor** [comment]
@hippylover you can reopen it if needed. Thx!
