### ISSUE TITLE
CCXT Developer Wanted

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#10662]
Hi everyone!

We are having more and more requests for new features.
There's a backlog of issues and pull requests in the CCXT repository.
We are a very tiny team doing our best to keep CCXT free for the users.
We'd like to resolve the backlog, which is why we think it is time to expand the CCXT team.
We need more people to help us on our current tasks and beyond.
Since so many people rely on this software we need developers who are also rockstars and workhorses.
We don't have working hours or schedules, it will require the majority of your time.
Your compensation will be very good but it will depend on your activity (or how much you do).
Your age does not matter that much, but make sure it is legal for working.
This library is developed in three languages JavaScript, Python and PHP.
You need a decent experience with at least two of those three languages, though better know all three.
The more programming languages you have worked with – the better.
You must be an exceptionally skilled coder and a software architect with a lot of practice.
Your English must be fluent.
You must be a CS enthusiast in your heart (ideally, a CS graduate), to work on our team.
You need a portfolio of the work you did, on GitHub or elsewhere.
We are looking for people who have more answers than questions.

Things you must know very well or must have dealt with: 

- CCXT usage and documentation
- OOP (C++ experience would be very good)
- concurrency and parallelism in different languages
- software architectures
- patterns and algorithms
- version control
- networking
- cryptocurrencies
- general trading
- finance
 
This is what we do:

- writing unified methods and new exchange API integrations
- reviewing and directing the work on the existing PRs
- fixing bugs in the code, maintaining the repositories
- supporting users, answering questions, closing issues
- adding new examples and docs

This is a fully remote job.
You must be stress-resistant and be prepared to learn fast and bury into the work quickly.
Novice/beginner developers, please, don't waste your time.
Apart from the technical work it implies a lot of communication.
There will be a paid trial period of 1-2 months to see if we can work together.
We start from $100k/y to $200k+/y in crypto stablecoins on average.
It can go both ways depending on your qualification.

If you're interested, please, pm us on our discord chat (we will reply as soon as possible): 

[![Discord](https://img.shields.io/discord/690203284119617602?logo=discord&logoColor=white)](https://discord.gg/dhzSKYU)

**Comment by ttodua** [comment]
This is good news. Btw, just my 2 cents - you might consider hiring 2 person instead of one, for half-time. Might be better for replacing each-other and also, working parallelly on different tasks.

**Comment by frosty00** [comment]
> This is good news. Btw, just my 2 cents - you might consider hiring 2 person instead of one, for half-time. Might be better for replacing each-other and also, working parallelly on different tasks.

We have already hired 2 people, now we are looking for a third person to join us. We are looking for people who will work full time since it is a big time commitment.

**Comment by krychla1** [comment]
another 2 cents (you are getting rich : ), consider different search channels beside this one

**Comment by ttodua** [comment]
And another 2 cents - if the burden is too much, you might make the approved PR's rewardable (with cryptos) and incentivize users to fix & PR the github-listed issues, :) some people might get interested and ccxt might get more PR's & updates.

**Comment by kroitor** [comment]
@ttodua yeah, we're going to launch a developer reward program very soon!

**Comment by drsavant-pub** [comment]
@kroitor 

I love the idea of a community rewards program for coding solutions!  

Allow me to give you one or two observations that might have some bearing on this situation.  

A great majority of the new (and resolved) issues are questions rather than enhancements and bugs, and after looking through some of those questions it seems to me that a bunch of those were answered by reference to the manual.  The user could have found the answer in the manual by themselves and/or trial and error coding.   I also see a lot of issues improperly formatted.

I could be wrong, but it appears that a great deal of your time seems to be devoted to issues that can be found in the manual as well as improperly formatted issues and I've observed this getting larger over time.  I feel that enhancements and bugs should be the priority, but I also recognize that questions are important.  Questions develop interest, a larger audience, empower potential users and can sometimes lead to innovations.  So, they are very important, but not more important than actual bugs and enhancements.

My own pride prohibits me from asking a question if I believe there is a possibility I can answer it on my own, and this has forced me to dig into the ccxt manual again and again, create tons of trial and error code, and in some cases I've even discovered errors in the APIs of various exchanges and then dealt with those exchanges directly to get those errors fixed.   I believe this is what you want from your users, which is why I do as much as possible on my own to reduce the load on you and your team.  However, this does not seem to be the approach of everyone in the community.  

It is my opinion that the most valuable programmer (you) should not be answering mundane questions while the community of developers wait patiently for bugs and enhancements to come off the back burner.

In other words the CEO should not be doing the job of the receptionist.  (I do recognize that in many cases you are the only one who can answer these questions and therefore the contrast of CEO/receptionist many not be perfect, but it is apropos.)

There must be a way of handling this tidal wave of questions in such a way that it doesn't disperse your effort and energy,  but I don't have the answer because I haven't had the time to tabulate questions into categories to see where the bottlenecks really are.  If I had the time I could study the problem more closely and together we could arrive at a solution.

Those are my observations and I would be happy to be a part of the solution whatever it may be.

As always I thank you for your monumental effort with ccxt and your exceptional patience with everyone in this community.

**Comment by kroitor** [comment]
@drsavant-pub thx for your input! Totally agree with you! Btw, I've sent you an email, looking forward to hearing from you!
