### ISSUE TITLE
Significant delay on watchOrders and createOrder in prod

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#10785]
We are experiencing significant connection delay in `prod` using `watchOrder` and response delay using `createOrder`. 
For example, connection to Binance Futures can take up to 20 seconds for `watchOrder` and 10 sec. for `createOrder`.

In `staging` with few amount of profiles and orders, everything work instantly.

Does `ccx` have any request limit control that can influence the issue? Or it is some kind of DDoS protection from exchanges? 

- OS: Debian (Docker)
- Programming Language version: JavaScript
- CCXT version:  CCXT PRO: 0.9.35

**Comment by kroitor** [comment]
> We are experiencing significant connection delay in `prod` using `watchOrder` and response delay using `createOrder`. For example, connection to Binance Futures can take up to 20 seconds for `watchOrder` and 10 sec. for `createOrder`.
> 
> In `staging` with few amount of profiles and orders, everything work instantly.

How do you measure the latency?

I would suggest this:

```JavaScript
const ccxtpro = require('ccxt.pro')
async function main() {
    const exchange = new ccxt.binanceusdm()
    await exchange.loadMarkets()
    const start = exchange.milliseconds()
    const order = await exchange.createOrder('BTC/USDT', 'limit', 'buy', 1, 35000)
    const end = exchange.milliseconds()
    console.log (end - start, 'ms to place an order')
}

main()
```

If you are also measuring the loadMarkets() call – then you may be running into issues documented here: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

Could that be the case? If yes, then you can address that by sharing the loaded markets between the exchange instances:

- https://github.com/ccxt/ccxt/blob/master/examples/js/shared-load-markets.js

> Does `ccx` have any request limit control that can influence the issue? Or it is some kind of DDoS protection from exchanges?

Yes, it is described here: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit However, in order to tell the exact cause of the issue, we need a bit more details from you on the above. Ideally, please, post your code to reproduce the lengthy delay (remove all irrelevant bits from it as much as possible, leaving just the relevant essence of it).

**Comment by wunderb1t** [comment]
@kroitor Thank you for reply, we will check the links. Meanwhile here is code, to simulate the problem. In our app, we create new exchange instance for each new profile in async way, i.e. 'in parallel'. We think because of constant usage of such operation, exchange increase connecting time. As snippet output you should see connecting time increment approx. from 
3000 ms to 10000 ms. 

```
async function start() {
    // Imagine we have 100 different profiles.
    for (let profile = 0; profile < 100; profile++) {
        // Delay To Avoid Binance DDoS ban.
        await sleep(15);

        startSocketMonitor('binance', {
            apiKey: 'my api key',
            secret: 'my secret key'
        });
    }
}

async function startSocketMonitor(exchangeCode, profile) {
    const exchange = new ccxt[exchangeCode](profile);

    const start = new Date();
    exchange.onConnected = function (client, message) {
        console.log(`Connected in ${Math.floor(new Date() - start)} ms`);
    };

    while (true) {
        try {
            const orders = await exchange.watchOrders();
        }
        catch (e) {
            console.log(e);
            break;
        }
    }
}

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

start();
```

**Comment by kroitor** [comment]
@wunderb1t yeah, that is definitely caused by violating this rule: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter, if you apply shared markets as in the example i posted above – that will reduce your load times and resource usage significantly, and will not be aggressive on Binance servers either. I would highly recommend checking those links.

**Comment by ttodua** [comment]
Kroitor hinted you the correct way. You should create the exchange object once somewhere in global scope and use that initiated object inside your functions. That might solve the issue, otherwise you are probably creating numerous conenctions to binance API, causing clogging the limits.

 Feel free to reopen the issue anytime.
