### ISSUE TITLE
CCXT orderbook error

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#10793]
- OS:Windows 10
- Programming Language version: Python 3.7
- CCXT version: CCXT version: CCXT Pro Version: 0.8.13

I get this error 

```
File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxtpro\base\order_book_side.py", line 68, in __getitem__
    return super(OrderBookSide, self).__getitem__(item)
IndexError: list index out of range
```

what can i do?

**Comment by ttodua** [comment]
Please include the whole code you are using (you can replace sensitive information/part with dummy info) so we could see whole code how/what you did correctly or wrong. Without it impossible to answer, you didn't even mentioned exchange. Feel free to reopen the issue after you will be ready.

**Comment by kroitor** [comment]
@ShieldTrade we would be happy to give you a precise answer if you can provide a reduced snippet that reproduces the problem (if you can make one, remove all irrelevant bits to it leaving just the code that is essential for your use-case). Otherwise we're mostly guessing, hope for your understanding.
