### ISSUE TITLE
[KuCoin] Get kucoin Balance insufficient! when trying to create limit buy order

### ISSUE THREAD

**Issue by scovic** [ccxt/ccxt#10808]
- OS: Ubuntu 18.04
- Programming Language version: Node 16.11.1
- CCXT version: 1.55.50

```
const exchange = new ccxt.kucoin({
				password: password,
				apiKey: apiKey,
				secret: secret
			})
let trade_data = await exchange.createLimitBuyOrder("ANC/USDT",  2.5527858679816577, 3.917289,  { })
```

```
error: InsufficientFunds: kucoin Balance insufficient!
```
The problem is that i have usdt on my wallet, but on my main wallet. Is there a way to choose what wallet to use when creating a limit order? Or any params to set?

**Comment by ttodua** [comment]
There is no way to 'choose' it. It is how KuCoin works. You need to move funds from 'Main' account to 'Trading' account and there is not way otherwise. 
For 'moving' funds, you can do that manually, or use the programmatic approach. After that, you will have funds on you TRADING acc balance to trade.

**Comment by scovic** [comment]
Yes, thank you very much!
