### ISSUE TITLE
ftx.fetch_trades  return trades sorted by timestamp ccxt, but some trade's timestamp is same value, then the trade_id 's order is reversed.

### ISSUE THREAD

**Issue by feedss** [ccxt/ccxt#10838]
ftx.fetch_trades  return trades sorted by timestamp ccxt, but some trade's timestamp is same value, then the trade_id 's order is reversed.

**Comment by feedss** [comment]
sorted by trade_id seems better.

**Comment by ttodua** [comment]
@kroitor, I've experienced that too. maybe it is not only for FTX but for all other ex'es too, where there happen several trades on same MS. the solution should be generic (a method living in 'base') which sorts 'same-timestamped' arrays according to specific other 'key' instead of 'timestamp'. What do you think?

**Comment by kroitor** [comment]
> The solution should be generic (a method living in 'base') which sorts 'same-timestamped' arrays according to specific other 'key' instead of 'timestamp'. What do you think?

I agree, though, I think we should sort not by a single field, but by several fields, namely "by-timestamp-by-id-within-the-same-timestamp". It has to be added to this base method: 

https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L1265

We should at least define the priority of those fields, cause not all exchanges have ever-increasing ids, some of them use random uuid-strings for ids, which is why we can't always sort by id. But we can almost always sort by timestamp. Which is why i think the order of sorting must be "by timestamp, then by id within repeating timestamps".

**Comment by ttodua** [comment]
@kroitor , i've been thinking and maybe the issue might be a bit deeper. If exchange `fetchTrades` returns:
```
[
   {  id: "cdg-234-2fer-353-d45",  'time': 1600000001, 'price': 1.2 ... },
   {  id: "fet-633-fsg-423-e66",     'time': 1600000001, 'price': 1.4 ... },
   {  id: "geq-566-zxc-873-c12",   'time': 1600000001, 'price': 1.2 ... },
]
```

 CCXT shouldnt sort it with either timestamp or order ids. I think in implementation (`for loop`) the user should choose the correct direction of that specific exchange, and ccxt shouldn't change the sorting at all (neither timestamp nor id). Otherwise, sorting by CCXT will not be fail-safe and will lead to issues. What do you think?

**Comment by kroitor** [comment]
@ttodua 

> What do you think?

I would say we should keep sorting there, cause users rely on it for proper pagination throughout the lib: https://github.com/ccxt/ccxt/wiki/Manual#pagination

Check pagination examples here for reference (ctrl+f "pagination"): https://github.com/ccxt/ccxt/tree/master/examples/py

If we make the users figure the sorting order for each specific exchange by default – the next thing the users will ask is to unify that order. We have some thoughts on how we could improve pagination with iterators and more advanced stuff, but for now we might have higher priorities with the existing code. On the issue above, i would say that we should sort-by-timestamp-by-id at this point.
