### ISSUE TITLE
Flip XRP on The rock

### ISSUE THREAD

**Issue by marcobazzani** [ccxt/ccxt#1085]
How can I flip EUR/XRP to XRP/EUR on TheRock trading
- OS: any
- Programming Language: python
- CCXT version: latest master
- Exchange: Therock
- Method: fetch_l2_order_book

Could you suggest me a way to flip the order book to align it with other exchanges ?
actually therock publish data in EUR/XRP and BTC/XRP while the rest of the exchanges are in XRP/EUR do you have any strategy to flip the api ? (order_book would be the first but also the rest of the APIs)
I could then implement it and send you a PR.

**Comment by kroitor** [comment]
> How can I flip EUR/XRP to XRP/EUR on TheRock trading

You can't really do that, because EUR and XRP base/quote positions are not interchangeable, therefore the exchanges' policies for fees and tokens in general aren't "flippable" (can't reflect them, because this is not an ideal mirror, we have to account for conversion rates and liquidity, globally).

> Could you suggest me a way to flip the order book to align it with other exchanges ?

This is a way to flip the price quickly, without accounting for the above important aspects:

```
price = 1 / price
```

```JavaScript
mbp:ccxt igorkroitor$ node examples/js/cli therock fetchTicker EUR/XRP
{      symbol:   "EUR/XRP",
    timestamp:    1515202347379,
     datetime:   "2018-01-06T01:32:27.379Z",
         high:    0.55,
          low:    0.4,
          bid:    0.47,
          ask:    0.48,
         vwap:    undefined,
         open:    0.44,
        close:    0.48,
        first:    undefined,
         last:    0.48,
       change:    undefined,
   percentage:    undefined,
      average:    undefined,
   baseVolume:    230192.46,
  quoteVolume:    107757.9509,
         info: {          date: "2018-01-06T02:32:27.379+01:00",
                       fund_id: "EURXRP",
                           bid:  0.47,
                           ask:  0.48,
                          last:  0.48,
                          open:  0.44,
                         close:  0.48,
                           low:  0.4,
                          high:  0.55,
                        volume:  107757.9509,
                 volume_traded:  230192.46                       } }
```
```shell
mbp:ccxt igorkroitor$ echo "scale=8; 1/0.48" | bc
2.08333333
```

2.083 ~ XRP/EUR...

```
mbp:ccxt igorkroitor$ node examples/js/cli cex fetchTicker XRP/EUR
...
         last:    2.17,
...
```

> do you have any strategy to flip the api ?

Yes, the strategy is to touch the prices and amounts (volumes) as little as possible in the library and do as much as possible on top of it. Therefore we don't flip them in the base code.

> I could then implement it and send you a PR.

I think this affects some delicate aspects of estimating values for tokens (especially the fee schedules) and it is likely better to leave it in the userland. In other words, we let the user decide. We would be happy for all contributions from you, but we have concerns which aren't easily resolvable on this particular proposal (it would require a significant rework at the very least + all of the above).

Let me know if this answers your question. Thx!

**Comment by marcobazzani** [comment]
Yes I did the 1/price flip
Just wonder if could be convininent to flip the full API.
But I get your point

Can you just me explain a bit more in depth your statement:
"we have to account for conversion rates and liquidity, globally"

Thank you

**Comment by kroitor** [comment]
@marcobazzani what I wanted to say is that when you reverse the sides of the pair you can introduce some unwanted side-effects. For example, some exchanges have different fees on the buy and sell sides. Also, holding a value of M xrp worth of N euro is not the same as holding N euro in the first place – when flipping sides you have to account for added risks of holding this or that coin. Some exchanges freeze some pairs and funding occasionally. So, in general, it's not always a strict conversion ratio of 1/x, especially, if you are trading against multiple exchanges. Hope it helps.
