### ISSUE TITLE
ohlcvs.map is not a function (bybit)

### ISSUE THREAD

**Issue by flieks** [ccxt/ccxt#10972]
using latest version for JS

When i do this for bybit exchange

```
const since = new Date().getTime()
const ohlcv = await exchange.fetchOHLCV('BTCUSDT', '1h', since)
```

I get
`ohlcvs.map is not a function`

When i divide the date by 1000 it works but then it gives 200 price candles from march 2020.
const since = new Date().getTime() / 1000

**Comment by kroitor** [comment]
> using latest version for JS
> 
> When i do this for bybit exchange
> 
> ```
> const since = new Date().getTime()
> const ohlcv = await exchange.fetchOHLCV('BTCUSDT', '1h', since)
> ```

When you supply the current timestamp as the `since` timestamp, you're effectively asking for all candles from now into the future – and there's no future yet right now. Therefore you get an empty response.

> When i divide the date by 1000 it works but then it gives 200 price candles from march 2020.
const since = new Date().getTime() / 1000

Don't divide it by 1000. Subtract from it.
Instead, set it to the timestamp of the first historical candle you want to get.
This is explained in the Manual: https://docs.ccxt.com/en/latest/manual.html#pagination
The `since` argument is always in milliseconds and must be in the past to work.

This will work:

```JavaScript
const since = this.parse8601 ('2021-12-01T00:00:00Z');
const ohlcv = await exchange.fetchOHLCV('BTCUSDT', '1h', since)
```

This will also work:

```JavaScript
const hour = 60 * 60 * 1000
const since = new Date.getTime () - 50 * hour; // starting from -50 hours and newer
const ohlcv = await exchange.fetchOHLCV('BTCUSDT', '1h', since)
```
