### ISSUE TITLE
fetch_order_books function only works for exchange polionex

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#11028]
how come this code doesnt work for binance and kucoin?

# -*- coding: utf-8 -*-

import os
import sys
from pprint import pprint

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

id = 'poloniex'
#id='binance'
# instantiate the exchange by id
exchange = getattr(ccxt, id)({
    # 'proxy':'https://cors-anywhere.herokuapp.com/',
})

# load all markets from the exchange
markets = exchange.load_markets()

# this will work (a limited number of symbols)
#result = exchange.fetch_order_books(['ETH/BTC', 'LTC/BTC'])
#pprint(result)

# this will also work (a limited number of symbols)
#result = exchange.fetch_order_books(exchange.symbols[0:10])
#pprint(result)

# this will not work (too many symbols)
result = exchange.fetch_order_books(exchange.symbols)
pprint(result)

**Comment by kroitor** [comment]
> how come this code doesnt work for binance and kucoin?

Because Binance and KuCoin don't have a method for fetching multiple orderbooks at once, just one orderbook at a time, this is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata
- https://docs.ccxt.com/en/latest/manual.html#exchange-metadata

Binance and KuCoin don't have fetchOrderBooks, but they have fetchOrderBook.
Poloniex has fetchOrderBooks and fetchOrderBook.

Compare:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L71
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/kucoin.py#L68

To this:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/poloniex.py#L53
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/poloniex.py#L54

**Comment by adamrg73** [comment]
thanks
