### ISSUE TITLE
fetchOHLCV Limit on historical data

### ISSUE THREAD

**Issue by haythamabutair** [ccxt/ccxt#1112]
Is there a way to only get the past n data points? The current .get_historical_data retrievals all datapoints ( imagine the time complexity when running it against 250 coins)

- OS: Windows
- Programming Language: Python 2.7
- CCXT version: 1.10.521
- Exchange: Bittrex
- Method: get_historical_data

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

MUST_READ_THIS https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

```
  historical_data = self.exchange_interface.get_historical_data(
            market_pair=market_pair,
            period_count=period_count,
            time_unit=time_unit
        )
```

In order for me to just get the past 20 data points, I have to do this:

`        historical_data = []
        for exchange in self.exchanges:
            rev = exchange.fetch_ohlcv(
                market_pair,
                timeframe=time_unit
                #limit=period_count
                )
            historical_data.append(rev[-20:])
        return historical_data[0]`

example 1: ccxt.poloniex ({'verbose': True}).fetchTicker ('ETH/BTC')

example 2: exchange = ccxt.bittrex ()
           exchange.verbose = True
           exchange.fetchOrderBook ('ETH/BTC')

REPLACE_WITH_YOUR_VERBOSE_OUTPUT_HERE

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts
- https://github.com/ccxt/ccxt/issues/987

**Comment by haythamabutair** [comment]
@kroitor  - When following the candlestick logic, this still returns data from the beginning. It does not return the last N elements. Am I missing something? Like in the params, should we be passing something there?

**Comment by kroitor** [comment]
@haythamabutair 

I've linked to a [duplicate post](https://github.com/ccxt/ccxt/issues/987) regarding the problem with fetchOHLCV, I'd recomment to read it. This issue was closed because it's a duplicate to that issue.

> Am I missing something? 

Yes, you're missing the fact that this functionality is still under development. We will be happy for pull requests and contributions. Until we finish the unification process, there may be bugs here and there.

> Like in the params, should we be passing something there?

If you don't rely on the unified API, you can pass custom exchange params in the `params` argument, but you will have to consult exchanges' docs for exchange-specific parameter names. That can be a temporary workaround until we finish support for `since` everywhere.

Unfortunately for you, Bittrex does not support filtering OHLCV since date at all. So, they will always return the full set, and we can only filter OHLCV on client-side. But in your case, the timeouts will still be there. And if you don't want them, just set a higher timeout, like `.timeout = 30000` (milliseconds).

Hope it helps.

**Comment by haythamabutair** [comment]
@kroitor - Thanks for the explanation.
