### ISSUE TITLE
How to get all your trades on Binance fast

### ISSUE THREAD

**Issue by Bomper** [ccxt/ccxt#1120]
Does anyone know if there's a way to get all your trades on Binance, given that [their API forces you to get those trades *by symbol*](https://github.com/binance-exchange/binance-official-api-docs/pull/6)? What if you don't remember all the symbols you've traded? Do you have to do a for loop for all the symbols? That's what I'm doing in [my Binance fetchMyTrades](https://github.com/ccxt/ccxt/pull/1079) example, but it's painfully slow (5+ minutes), and I only have like 20 trades.

**Comment by kroitor** [comment]
> Does anyone know if there's a way to get all your trades on Binance, given that their API forces you to get those trades by symbol? 

Unfortunately, there isn't such a way... Binance is limiting "wide/big queries", because their goal is to reduce loads, of course. Most exchanges will sacrifice convenience for speed. We have to adjust to that.

> but it's painfully slow (5+ minutes), and I only have like 20 trades

You can filter by non-zero balances, or by changed/unchanged balances. But that requires keeping track of balances in the first place.

> Do you have to do a for loop for all the symbols?

If you don't keep track of them, then, yes, you have to. But if you have like 20 trades saving and reloading can be solved with a JSON-based cache/file in 5 minutes. This is affordable on first run. Then, when you have it cached, you can update it in background continuously or listen for streams...

Let me know if this answers your question.

**Comment by Bomper** [comment]
I have a few trades now and it's taking a long while, but for others who have many trades, it could take longer? Anyway, looks like the sample I wrote is the best that can be done with Binance, CC @blak3r

**Comment by rakodev** [comment]
+1
I'm agree with @Bomper 
It'll be easier if we can get all our trades in one request, I think it'll be more performing for each part, the client and Binance. Otherwise we will check all trades for all symbols... So many request for everybody...
