### ISSUE TITLE
What is expected latency for placing an order, other than network transfer latency?

### ISSUE THREAD

**Issue by cdcv** [ccxt/ccxt#11614]
Microseconds?  Milliseconds?  1 second? Few seconds? Often many seconds?
Example, if 100 orders are placed, what range of times should be expected between when ccxt createOrder is called and when the order is live on the exchange order book, after subtracting the network delay/transfer time from the server to the exchange?
Another way of asking the same thing: is expected latency to place an order significantly longer than the network delay (eg if using a server in the same geography as the exchange)?  Once an order arrives at an exchange via ccxt/exchange api, is there meaningful additional delay on the exchange side before the order is live on their order book?
How much does this vary between the exchanges, and during periods of high volume?
What is a reasonable maximum delay to anticipate between the time a create order is placed in ccxt and the time that the order is live on the exchange book or executes?
Has this latency been extensively tested?
I assume that there is microsecond latency within the ccxt code itself and no network traffic required before the order goes to the exchange via the api, assuming that loadMarkets had been called previously, correct?

Thank you

**Comment by ttodua** [comment]
This question will never have an exact answer. There are different things involved:
- exchange engine (we cant answer, every exchange has different engine and it's impossible to measure their timing, it also depends on their 'high-overload' or 'low-overload' status (only they can measure their averages themselves, but they will not share this stats in public). Even if someone tested and told the numbers, it will not be correct (because of many different factor). Order-matching and execution engine is not a fairly simple script, it has to interact with a database. It also depends on what strength of the servers are being used. However, in my opinion, any good exchange should do within several milliseconds (it's impossible to tell even an approximated number, but I dont think it would be more than 50ms even in regular-loaded scenario).
- ccxt doesn't have it's own speed. it depends on the hosted server/hardware/pc. If you execute 'createOrder' on _Pentium 1_, it might take X milliseconds, but if you run that on modern cpu, it will take Y times less. Neither this is possible to tell how many MS/MicroSecond it takes - it varies per hardware, and also per programming-language (JS, PHP, PY?).

The only way to answer that , is that you tested (google is your friend) with the specific tools. In simple way, you can measure (debug) the time-difference between you execute ccxt code and the moment before it send request. It might be a couple of MS i think ( lets say 1,2,3,4... depending hardware).

and even if someone tested these, that will be very very very broad approximations. However, in my personal opinion, that very broad numbers might be under what I named as example numbers in above lines.

@kroitor / @frosty00 let us know if you have more thoughts.

**Comment by cdcv** [comment]
Very helpful.  Thank you.  Sounds like all of the other delays are small relative to the network latency.

**Comment by cdcv** [comment]
Do any of the crypto exchanges offer colocalization of client servers on-site, to minimize data transmission latency?

**Comment by kroitor** [comment]
> Do any of the crypto exchanges offer colocalization of client servers on-site, to minimize data transmission latency?

Yes, some of them do, but you will have to reach out to the exchanges themselves with this question, cause we can't really respond on their behalf in this case. Some of them offer server colocation, other will offer CPU time on their servers or within their networks.

**Comment by kroitor** [comment]
Closing this for now, if you don't mind. Feel free to reopen it or just ask further questions if any.
