### ISSUE TITLE
Error fetching orders from Cryptopia

### ISSUE THREAD

**Issue by mohammadwillwin** [ccxt/ccxt#1172]
Tried to get my order history from Cryptopia on a symbol that existed on their website "XVG/BTC". Getting my available balance works, but fetching orders don't. It only works when I fetch orders on a market I never did eg. XRP/BTC.

I hid my API & secret key from the code,.

- OS: Windows 10
- Programming Language: PHP
- CCXT version: 1.10.621
- Exchange: Cryptopia
- Method: fetchOrders

```include "assets/import/ccxt/ccxt.php";
$cryptopia = new \ccxt\cryptopia (array ('apiKey' => 'X','secret' => 'X'));
$tradehistory = $cryptopia->fetchOrders ($symbol = 'XVG/BTC');
print_r($tradehistory);
```

```
Fatal error: Uncaught exception 'ccxt\ExchangeError' with message 'cryptopia null' in 
C:\xampp\htdocs\assets\import\ccxt\php\cryptopia.php:615 Stack trace: 
#0 [internal function]: ccxt\cryptopia->request('GetOpenOrders', 'private', 'POST', Array) 
#1 C:\xampp\htdocs\assets\import\ccxt\php\Exchange.php(644): call_user_func(Array, 'GetOpenOrders', 'private', 'POST', Array) 
#2 [internal function]: ccxt\Exchange->ccxt\{closure} (Array, Array)
#3 C:\xampp\htdocs\assets\import\ccxt\php\Exchange.php(1460): call_user_func_array(Object(Closure), Array) 
#4  C:\xampp\htdocs\assets\import\ccxt\php\cryptopia.php(486): ccxt\Exchange>__call('privatePostGetO...', Array)
#5 C:\xampp\htdocs\assets\import\ccxt\php\cryptopia.php(486): ccxt\cryptopia->privatePostGetOpenOrders(Array, Array) 
#6 C:\xampp\htdocs\assets\import\ccxt\php\Exchange.php(1198): ccxt\cryptopia->fetch_orders('XVG/BTC', NULL, NULL, Array)
#7 C:\xampp\htdocs\test.php(26): ccxt\Exchange->fetchOrders('XVG/BTC')
#8 {main} thrown in C:\xampp\htdocs\assets\import\ccxt\php\cryptopia.php on line 615
```

**Comment by mohammadwillwin** [comment]
Just tried again and this time the error didn't show, but it only showed an empty array.

Tried again then the same error came.

**Comment by mohammadwillwin** [comment]
Updated ccxt and it's still not working. Any reason?

**Comment by kroitor** [comment]
Hi!

This is a duplicate issue with the order cache. In short, cryptopia will only return open orders if you restarted your program after you created them. If they were closed and you restarted your program, we don't have any means for fetching those closed orders from Cryptopia, just the trades.

The inner workings of order cache are partially explained here:
- https://github.com/ccxt/ccxt/issues/660#issuecomment-355780769
- https://github.com/ccxt/ccxt/pull/102
- https://github.com/ccxt/ccxt/issues/304#issuecomment-335508927
- https://github.com/ccxt/ccxt/issues/569
- https://github.com/ccxt/ccxt/issues/660#issuecomment-355780769

This issue is common to Liqui, Cryptopia and several other exchanges.

Hope it helps. Closing this for now if you don't mind. Feel free to reopen it if needed or just ask questions.
