### ISSUE TITLE
fetch_order() order from Binance gives the limit price instead of the executed price

### ISSUE THREAD

**Issue by fredfortier** [ccxt/ccxt#1175]
I noticed this discrepancy in context of this issue: https://github.com/enigmampc/catalyst/issues/151.

Basically, I'm doing a fetch_order() on a filled order to determine the avg executed price. However, the `price` attribute corresponds to the limit price. I don't see this data in the `info` dict either. Let me know if you are already aware of this. If not, I'll do a PR to fix it.
![screenshot 2018-01-10 22 44 32](https://user-images.githubusercontent.com/1474114/34807993-df77e4da-f659-11e7-8898-bf05d19e212f.png)

Here is the output. 0.00000836 is my limit. It's missing my avg price which is 0.00000827. Dividing `cost` by `amount` also gives me 0.00000836.
```
{  
   'status':'closed',
   'timestamp':1515641853506,
   'price':8.36e-06,
   'datetime':'2018-01-11T03:37:33.506Z',
   'cost':0.0030346799999999997,
   'id':'17210371',
   'remaining':0.0,
   'info':{  
      u'orderId':17210371,
      u'clientOrderId':u'z8xl93tiQH5ZRTOGEtNI9D',
      u'origQty':u'363.00000000',
      u'icebergQty':u'0.00000000',
      u'symbol':u'TRXBTC',
      u'side':u'BUY',
      u'timeInForce':u'GTC',
      u'status':u'FILLED',
      u'stopPrice':u'0.00000000',
      u'time':1515641853506,
      u'isWorking':True,
      u'type':u'LIMIT',
      u'price':u'0.00000836',
      u'executedQty':u'363.00000000'
   },
   'fee':None,
   'side':u'buy',
   'amount':363.0,
   'type':u'limit',
   'symbol':u'TRX/BTC',
   'filled':363.0
}
```

**Comment by kroitor** [comment]
Hi! Thanks for opening this issue. Let me explain...

> Basically, I'm doing a fetch_order() on a filled order to determine the avg executed price. 

You can't really do it consistently. Approx 60% of exchanges will return the filling price or average price from order APIs, but the other exchanges, including some major ones like (Binance and HitBTC) won't return the filling info (cost and fee) for the order. Some of them (a significant count, like Cryptopia) don't have neither fetchOrder, nor fetchOrders, nor fetchClosedOrders at all. 

They will only return that info from their private trades API, and for that you need to call `fetchMyTrades()` and calculate the average price from actual trades. In other words, you're relying on info that might be missing, and that info is often missing. So, to get full consistent info, you have to fetch the trades as well. 

> However, the price attribute corresponds to the limit price. I don't see this data in the info dict either.

One way to fetch them would be to listen for Binance streams or to fetch trades via the REST API. We could do that in the same fetchOrder method, but there's a rule that is carried throughout the whole library – we don't do multiple network requests per method call. One call = one request. We can do 2 requests at max in very rare cases where it isn't time-critical nor mission-critical and where we can't wrap the implementation any other way. But in 99% of cases that rule works, and we only do one request per method call. This keeps the networking explicit (under the user's control). There are several reasons for that, namely, the order cache and rate-limiting. We let the user decide how many requests he wants to send.

The order cache is partially explained here:
- https://github.com/ccxt/ccxt/pull/102
- https://github.com/ccxt/ccxt/issues/304#issuecomment-335508927
- https://github.com/ccxt/ccxt/issues/569
- https://github.com/ccxt/ccxt/issues/660#issuecomment-355780769

The possible rate-limiter issues are partially explained here:
- https://github.com/ccxt/ccxt/issues/736

> Let me know if you are already aware of this.

Yep, we are.

> If not, I'll do a PR to fix it.

Because of the above, we think a better idea would be to let the user decide which calls to make. In other words, we'd like to stay as thin as possible. Let us know if you think differently, I might be missing something. Thank you!

**Comment by kroitor** [comment]
A snippet on the same issue: https://github.com/ccxt/ccxt/issues/1011#issuecomment-356917809

**Comment by fredfortier** [comment]
Yes, that makes sense. We'll work with `fetchMyTrades()` to get this info.

**Comment by benediamond** [comment]
@kroitor, do you know if there has been any movement from binance on this? it would be nice to pressure them a bit more.

**Comment by kroitor** [comment]
@benediamond you can obtain that info with `this.options['newOrderRespType']`. `'ACK'` for order id, `'RESULT'` for full order or `'FULL'` for order with fills. `'RESULT'` is their default.

**Comment by benediamond** [comment]
@kroitor I don't see anything about this in the docs. could you briefly explain how this works?

**Comment by kroitor** [comment]
@bendemott we're talking of a market order, so you can use an exchange-specific option of Binance:

```
let binance = new ccxt.binance ({
    // among other options ...
    
    'options': {
        'newOrderRespType': 'FULL',
    },
})
```

or like so:

```
binance.options['newOrderRespType'] = 'FULL'
await binance.createOrder (...
```

The above is also overrideable with createOrder, like so: 

```
binance.createOrder (symbol, type, side, amount, price, {
    'newOrderRespType': 'FULL',
})
```

So, having the full response and the fills info in it, from there you can get the actual average filling price of the order. If you could tweak parseOrder to detect for order response type and calculate filling info from it, it would be great ;)

**Comment by benediamond** [comment]
@kroitor ok, I'll get started. two questions:
1. is the presence of the `fills` key in the response the (only) cue that the order was created with type `'FULL'`?
2. even if `'FULL'` is used, `executedQty` is still calculated in the same (naive) way. correct?

**Comment by kroitor** [comment]
> 1. is the presence of the fills key in the response the (only) cue that the order was created with type 'FULL'?

Well, you don't actualy need to "detect it", sorry for confusing you, I mostly mean just doing a basic thing like:

```

let fills = this.safeValue (order, 'fills');
if (typeof fills !== 'undefined') {
    let trades = this.parseTrades (fills ...
    // calculate average price from trades
}
...
return {
    'info': order,
    'id': id,
    'timestamp': timestamp,
    ...
    'trades': trades, ←-- added
}

**Comment by benediamond** [comment]
i am not familiar with `parseTrades`, so I will need to look around a bit before doing this.

sorry, I edited my above question to fix a mistake.

**Comment by kroitor** [comment]
> even if 'FULL' is used, price (in the main response) is still the listed price, not the actual (i.e., average) price. correct?

Yep. Thus we can "override" it after calculating the true filling price inside that if-block...
