### ISSUE TITLE
Unified "active" attribute not documented

### ISSUE THREAD

**Issue by neuhaus** [ccxt/ccxt#1179]
Is loadMarkets() considered to be part of the unified API?

I noticed that there is no standard attribute for the status of a currency pair, there's only the information in the results' `info` property which varies (I've seen `status`, `disabled`, `active`, ...).

It would be handy to have a unified status attribute that shows if the currency pair can currently be traded.

**Comment by kroitor** [comment]
> Is loadMarkets() considered to be part of the unified API?

Yes: https://github.com/kroitor/ccxt/wiki/Manual#markets

> I noticed that there is no standard attribute for the status of a currency pair, there's only the information in the results' info property which varies (I've seen status, disabled, active, ...).

> It would be handy to have a unified status attribute that shows if the currency pair can currently be traded.

1. We have this standard:
  - `exchange.markets[symbol]['active'] = true/false`  // can or cannot trade
  - `exchange.currencies[code]['active'] = true/false`  // can or cannot deposit and withdraw

2. If you don't find any of these ↑ – that is because the library is a work in progress, some of that info might still be missing, we are working on it, your contributions are welcome and would be appreciated ;) I would recommend to read the entire Manual, then read the examples, most of questions will then become clear.

3. `anything['info']` – is the unparsed untouched raw non-unified reply from the exchange, as is. Therefore you see exchange-specific formats there. This is true for all data that is returned from ccxt, if it has `ticker['info'], order['info'], market['info']` - that field contains a raw response. You don't really need to look there unless you're trying to fix a bug or add something new. Most of the time you need to look at all other fields around info. Those fields are described in the Manual (for markets, as well as for other data structures returned from ccxt). 

Does this answer your question?

**Comment by neuhaus** [comment]
It does, thanks for the great response.
But it raises another issue: The "active" flag is not documented in the manual.
I'm changing the headline of this issue to the documentation issue.

**Comment by kroitor** [comment]
> But it raises another issue: The "active" flag is not documented in the manual.
> I'm changing the headline of this issue to the documentation issue.

The documentation is also under development. The source of all docs is in the wiki folder of this repo. Those are also editable, you can change them and add missing info where you think it is necessary. Your contributions to the docs (based on your experience using the library) are welcome as well ;) I would close this issue for now, if you don't mind.
