### ISSUE TITLE
Huobi PRO create_limit_sell_order return 'order amount precision error'

### ISSUE THREAD

**Issue by bypassfuture** [ccxt/ccxt#1192]
Hi sir, 

My ENV is MacOS python 2.7.10,

code
```
def exchange_auth(ex):
    assert type(ex)==str
    return exchange[ex]({
                'apiKey': api[ex]['api_key'],
                'secret': api[ex]['api_secret'],
                'verbose': True,
                'nonce': ccxt.Exchange.milliseconds,
        })

def limit_buy(exchange, product, amount, price):
    return exchange.create_limit_buy_order(product, amount, price)

def limit_sell(exchange, product, amount, price):
    return exchange.create_limit_sell_order(product, amount, price)

---------
limit_sell(exchange, product, 100, 0.00011428)

```
when i run limit_sell/limit_buy on huobipro , the following error message showed

> 
> ('GET', 'https://api.huobi.pro/v1/account/accounts?AccessKeyId=123456-123456-123456-1234&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2018-01-11T14%3A33%3A42&Signature=SO4xyPkoELky00pDc%2B2RNBIrceoytsumi6Ynn20jYY4%3D', '\nRequest:', {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36'}, None)
> ('GET', 'https://api.huobi.pro/v1/account/accounts?AccessKeyId=123456-123456-123456-1234&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2018-01-11T14%3A33%3A42&Signature=SO4xyPkoELky00pDc%2B2RNBIrceoytsumi6Ynn20jYY4%3D', '\nResponse:', "{'X-Request-ID': '69aba8a28e2bf489708746a115d72814', 'X-Application-Context': 'dawn-broker-pro:prd:8080', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Server': 'openresty', 'Connection': 'keep-alive', 'Date': 'Thu, 11 Jan 2018 14:33:45 GMT', 'Content-Type': 'application/json;charset=UTF-8'}", u'{"status":"ok","data":[{"id":365225,"type":"spot","subtype":"","state":"working"}]}')
> ('POST', 'https://api.huobi.pro/v1/order/orders/place?AccessKeyId=123456-123456-123456-1234&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2018-01-11T14%3A33%3A42&account-id=365225&amount=100.0&price=0.00011428&symbol=mdseth&type=sell-limit&Signature=Acbnji%2BNWGHnNkBPCXm6W9igPVgqDXJKSNKjUIYZevA%3D', '\nRequest:', {'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36'}, '{"amount":100.0,"symbol":"mdseth","account-id":365225,"type":"sell-limit","price":"0.00011428"}')
> ('POST', 'https://api.huobi.pro/v1/order/orders/place?AccessKeyId=123456-123456-123456-1234&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2018-01-11T14%3A33%3A42&account-id=365225&amount=100.0&price=0.00011428&symbol=mdseth&type=sell-limit&Signature=Acbnji%2BNWGHnNkBPCXm6W9igPVgqDXJKSNKjUIYZevA%3D', '\nResponse:', "{'X-Request-ID': 'bf428d0fc3bed7b60550aa724cf24a5e', 'X-Application-Context': 'dawn-broker-pro:prd:8080', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Server': 'openresty', 'Connection': 'keep-alive', 'Date': 'Thu, 11 Jan 2018 14:33:45 GMT', 'Content-Type': 'application/json;charset=UTF-8'}", u'{"status":"error","err-code":"order-orderamount-precision-error","err-msg":"order amount precision error, scale: `0`","data":null}')
> **ERROR:root:huobipro {"status":"error","err-code":"order-orderamount-precision-error","data":null,"err-msg":"order amount precision error, scale: `0`"}**
> 

I dont understand what "**order-orderamount-precision-error**" means ?
But the same code runs OK on binance and other exchange,  can you help me sir ?
Really thanks!

**Comment by xunixxx** [comment]
@kroitor @bypassfuture 
I have this error on the two exchanges I use (binance and gdax) and ran few tests (python 3):

ON BINANCE:

Let's say my program wants to BUY 190.24285165 BAT with BNB  (pair BAT/BNB), the order is correctly created with the amount rounded to 190.24 with the function amount_precision() as the precision of amount is 2 in the market dataset for the pair of symbols BAT/BNB.

No, if I execute this: SELL 190.24285165 BAT for BTC (pair BAT/BTC), the order return an error of precision.  The raw amount entered in the create_order function is the original one, and the result of amount_precision() is again 190.24285165 instead of 190 (indeed, the amount precision is 0 in the market dataset for the pair of symbol BAT/BTC)

The error resides in the truncate() function called by amount_precision() :
    ```
def truncate(num, precision=0):
        if precision > 0:
            decimal_precision = math.pow(10, precision)
            return math.trunc(num * decimal_precision) / decimal_precision
        return num
```

if precision = 0, then truncate() return the original value, hence the error.

We can fix this by using 
```
if precision == 0:
       return math.floor(num)
```

It might not fix the scenario where the fraction of quantity allowed is a positive power of 10 (I don't know if it is possible, for extremely low valued altcoin )


ON GDAX:

the create_order() function passes the amount as is, without calling the amount_precision() function, hence the error if the qty is not at the good precision. I guess this is not implemented in a bunch of other exchanges.


ALL MARKET:

I think it is better to use the lot 'min' information when it exists in the market dataset, and use the function amount_to_lots() that is implemented but not used for creating orders. Btw, this function by default is taking the lot information in a specific dictionary path, it should be removed and directly defined in each market structure.

**Comment by xunixxx** [comment]
@kroitor @bypassfuture 
I have this error on the two exchanges I use (binance and gdax) and ran few tests (python 3):

ON BINANCE:

Let's say my program wants to BUY 190.24285165 BAT with BNB  (pair BAT/BNB), the order is correctly created with the amount rounded to 190.24 with the function amount_precision() as the precision of amount is 2 in the market dataset for the pair of symbols BAT/BNB.

No, if I execute this: SELL 190.24285165 BAT for BTC (pair BAT/BTC), the order return an error of precision.  The raw amount entered in the create_order function is the original one, and the result of amount_precision() is again 190.24285165 instead of 190 (indeed, the amount precision is 0 in the market dataset for the pair of symbol BAT/BTC)

The error resides in the truncate() function called by amount_precision() :
 
```
def truncate(num, precision=0):
        if precision > 0:
            decimal_precision = math.pow(10, precision)
            return math.trunc(num * decimal_precision) / decimal_precision
        return num

```

if precision = 0, then truncate() return the original value, hence the error.

We can fix this by using 

```
if precision == 0:
       return math.floor(num)
```

It might not fix the scenario where the fraction of quantity allowed is a positive power of 10 (I don't know if it is possible, for extremely low valued altcoin )


ON GDAX:

the create_order() function passes the amount as is, without calling the amount_precision() function, hence the error if the qty is not at the good precision. I guess this is not implemented in a bunch of other exchanges.


ALL MARKET:

I think it is better to use the lot 'min' information when it exists in the market dataset, and use the function amount_to_lots() that is implemented but not used for creating orders. Btw, this function by default is taking the lot information in a specific dictionary path, it should be removed and directly defined in each market structure.
