### ISSUE TITLE
Liqui fetch_orders does not require a symbol

### ISSUE THREAD

**Issue by davidpodrebarac** [ccxt/ccxt#1193]
As the title says, liqui's method private_post_active_orders can be called without given symbol and in that case it would return all open orders.

I am using version ccxt-1.10.647, python async

**Comment by kroitor** [comment]
Works as of 1.10.651. Thx!

**Comment by davidpodrebarac** [comment]
Thanks, it does fetch all open orders now, but there is still one little bug.
Data is parse incorrectly, returned amount is None, while remaining amount is correct.

**Comment by davidpodrebarac** [comment]
For example:
```
{'amount': None,
  'cost': None,
  'datetime': ...
  'fee': None,
  'filled': None,
  'id': '...',
  'info': {...},
  'price': 0.1,
  'remaining': 0.1,
  'side': 'sell',
  'status': 'open',
  'symbol': 'ETH/BTC',
  'timestamp': ...,
  'type': 'limit'},
```

**Comment by kroitor** [comment]
@davidpodrebarac can you please post the same output but keep the info field and other fields there? Need to check on that.

**Comment by davidpodrebarac** [comment]
Updated above... I just left out order id and timestamp

**Comment by kroitor** [comment]
Ok, here's the explanation:

1. If you create the order ccxt will remember the order amount in the order cache, so if then call fetchOpenOrders **without restarting your program** – the amounts will be set correctly. However, the cache does not survive the restart unless you save it and restore it manually from a file or a database. The order cache is stored in the `.orders` property of the exchange. So, if you restarted your program and haven't saved+restored the order cache – the cache will be dropped and the remembered order amounts will be forgotten.

2. Now, when you fetchOrder from Liqui by order id, Liqui will return both the remaining amount to buy/sell **and** the initial ordered amount. Arithmetically, initial = remaining + filled.
Here's the info, as it comes from Liqui API:

![liqui-fetch-order](https://user-images.githubusercontent.com/1294454/34877771-7d706e96-f7b8-11e7-80b0-9b03b3ce07de.jpg)

3. However, when you **fetchOpenOrders** from Liqui, they will return **just the** `"amount"` and it will actually represent the **remaining** amount to buy or sell (not the total). This follows from their vague description:

![liqui-fetch-open-orders](https://user-images.githubusercontent.com/1294454/34877899-f7b7f386-f7b8-11e7-94d0-d1e07688ce20.jpg)

4. ↑ So, for open orders Liqui will not return all amounts, but will return the amount **to be bought/sold**, that is the **remaining** amount. This is also confirmed by their other method (the `createOrder`), which returns this:

![liqui-create-order](https://user-images.githubusercontent.com/1294454/34878011-8dae0c7c-f7b9-11e7-82d9-78e69df285e8.jpg)

5. ↑ As you see, when you create an order, Liqui can actually have a chance to fill it immediately depending on the order params, so it can be closed right away or partially, or not filled at all. If you combine the logic of 3+4 in your head, you will see that when the order is not filled at all, the total=remaining is returned from their active orders API. If the order was fully closed immediately upon creation, it does not get to open orders list at all. And if it was filled partially, the amount shows the remaining amount (that is left to be filled after the order is created and matched partially). The matched (filled) amount will be represented as a trade, and the open order will have just the remaining amount.

6. If you restarted your program, after the cash is dropped ccxt has no way to distinguish if the amount coming from Liqui active orders is the total=remaining, or is just the remaining amount. So, it takes the safest side here, because the value definitely designates the remaining part, but not obviously, the total part. Liqui does not show if the order was partially filled previously, so no total amount is known.

7. If you would not restart your program or you would restore the order cache upon restarting your program, you would not have the above issues at all, because ccxt would restore the amounts from memory.

We are not sure if we are going to change this specific behaviour for Liqui, but we will consider this again. These order caching aspect is still not documented, as this whole repository is a work in progress.

Hope it helps.
