### ISSUE TITLE
Margin trading

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#1207]
Hi, I would like to know how can I implement a simple "create_order" in margin trading platform of bitfinex. I tried with:

result = bitfinex.create_order(symbol="XRP/BTC", type = "market", side = "sell", amount = 100)

In the documentation of the API: https://docs.bitfinex.com/v1/reference#rest-auth-new-order
they say that if we choose order type: "market" "limit" or others are margin trading orders, and if we start with "exchange...", orders are exchange orders.
But when I try with the previous code, I get this error:

bitfinex Invalid order: not enough exchange balance for 100 XRPBTC

- OS: Linux
- Programming Language: python3
- CCXT version: last
- Exchange: bitfinex
- Method: create_order

**Comment by kroitor** [comment]
Hi!

1. Bitfinex has several types of accounts, including an *exchange* account and a *margin* account.

2. By default ccxt will create an `exchange market` or `exchange limit` type of orders, that involves the *exchange* account. The *exchange* prefix means that an order is not a margin order, but more like a spot order, immediate. Also, it will query the *exchange* balance with fetchBalance () by default.

3. If you want to override the order type that is sent towards Bitfinex and change it from default exchange order types to margin types, then you need to pass an extra params dictionary, like so: 

```Python
params = { 'type': 'market' }  # 'market' without the 'exchange ' prefix means a margin order type
result = bitfinex.create_order(symbol="XRP/BTC", type = "market", side = "sell", amount = 100, params)
```

↑ This will create a *margin* order. And it will use the funds on your *margin account*.

4. If you try to create an *exchange* order and all your funds are on your *margin* account, you will obviously see a "not enough exchange balance", because you are trying to create an *exchange* order and you don't have any *exchange* funds there. This explains the result that you were getting.

5. The same is true for the other side, if all your funds are on the *exchange* account, you can't make a *margin* order without having any *margin* funds.

6. If you want to fetch *margin* balance you have to pass the extra params there to override its default preference for *exchange* funds:

```Python
margin_balance = bitfinex.fetch_balance({'type': 'trading'})
```

Let me know if this answers your question or not.

**Comment by fedecaccia** [comment]
Your answer is very useful, thanks!

**Comment by masterkain** [comment]
is there a way to differentiate between margin and exchange trades via trade history? I always get `EXCHANGE LIMIT` even for margin trades

**Comment by kroitor** [comment]
@masterkain need to see your code and verbose output according to these instructions: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue in order to be able to help you ) Can you please share more info, or just follow those instructions literally? ) Thx!

**Comment by masterkain** [comment]
hello, thanks for the reply -- I didn't meant this to be a problem with the library itself, I tried to ask other bitfinex devs if they were ever able to tell a margin trade from an exchange one somehow. sorry to hijack the thread looking for tips, but not many other places to ask. 👍

**Comment by masterkain** [comment]
thanks -- I see, but via `v2/auth/r/trades/hist` I'm getting back margin trades as `EXCHANGE LIMIT`, does that happen to someone else? I'm trying to understand if there's some issue with my account because I'm not also able to list past trades with `start` and `end` ranges.

**Comment by kroitor** [comment]
@masterkain yes, they will return EXCHANGE LIMIT, because each separate trade is still an exchange trade, even if it's been opened as part of your margin position.

**Comment by masterkain** [comment]
ouch. that confirmation is really unfortunate, I have to sync trades but skip margin ones as they will mess with balances. ledger reading is not an option because it lacks a lof of data and reading description is not recommended. It was my understanding that if an order type begins with `EXCHANGE` it is from exchange wallet and without (such as `LIMIT`) it's a margin one, but I guess that's not the case. :( thanks for the help.

**Comment by bheff88** [comment]
just submit a different gid for margin and exchange orders respectively and then look off your records from that

**Comment by ChacoLv** [comment]
Hi, @kroitor , can I cancel a margin active position by a cancel function. for example: If have a margin buy order, and want to cancel, I should order a same position amount sell order. I want to know that whether have a function to cancel the active position. no matter what it is buy or sell

**Comment by kroitor** [comment]
@ChacoLv hi! Yes, you can:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://docs.bitfinex.com/v1/reference#close-position

```Python
from pprint import pprint

exchange = ccxt.bitfinex({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

positions = exchange.private_post_positions()
pprint(positions)

position_id = 123456789  # ←----------- replace with your position id

cancel_result = exchange.private_post_position_close({'position_id': position_id})
pprint(cancel_result)
```

**Comment by avolution** [comment]
The Problem is that there is a hardcoded

`
if (type == 'limit') or (type == 'market'):
  orderType = 'exchange ' + type
`

in the create_order function for Bitfinex.

**Why is it there?
In my opinon it should be removed.**

otherwise what @kroitor posted

`
params = { 'type': 'market' }  # 'market' without the 'exchange ' prefix means a margin order type
result = bitfinex.create_order(symbol="XRP/BTC", type = "market", side = "sell", amount = 100, params)
`

have no effect.

Without that two lines you are able to create a margin order.
For closing it you can just submit another order(open_pos_amount*-1)  to bring the amount to zero.
