### ISSUE TITLE
this error how to resolve?

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#12155]
It shows the error as follows:
  File "roboot2.py", line 41
SyntaxError: Non-ASCII character '\xef' in file roboot2.py on line 41, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

The code of line 41 as follows:
`print("usd_balance：", usd_balance, "    matic_balance：", matic_balance, "    matic_price：", matic_price)`

**Comment by samgermain** [comment]
Hi @qwe231cvb 

Without more detail it's hard to know what the problem is. I tried running `print("usd_balance：", " matic_balance：", " matic_price：")` within python3 and didn't receive that error.

Do you think you could provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

Thanks
