### ISSUE TITLE
HitBTC v2 fetchOrders not implemented

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#1218]
Hi, i am getting fetchOrders not implemented. Searched here if it was not done since my last update but doesnt look like that.

fetchClosedOrders works like fetchOrders should. It does return me list of closed and also open orders. Is it possible to do something about it ?

THanks

**Comment by kroitor** [comment]
Hi!

>  It does return me list of closed and also open orders. Is it possible to do something about it ?

Can you please show verbose output when fetchClosedOrders returns open orders mixed with closed orders? We would fix this particular aspect then and it will return just the closed orders for less confusion.

> fetchClosedOrders works like fetchOrders should.

fetchOrders should not work like fetchClosedOrders does now, because fetchClosedOrders uses the order history endpoint from HitBTC which lags behind their open orders list.

> fetchOrders not implemented. Searched here if it was not done since my last update but doesnt look like that.

fetchOrders for HitBTC v2 most likely won't be implemented at all for these reasons:
- they don't have a clearly designated endpoint for fetching all orders
- they only have an endpoint for active orders and an endpoint for historical orders
- he historical orders endpoint is updated much slower then the active endpoint, so you can't rely on it when you are trading
- the active orders endpoint returns just the active orders list, so there's no way to fetch them all at once, if you need them just in time (most often you do)

Does this answer your question?

**Comment by janeCMD** [comment]
Thanks for reply. According to what you say and saw on hitbtc, i think, if you merge active orders with orders history, it should contain complete list, no ? Do you have any idea of how much delayed is order history ?

**Comment by kroitor** [comment]
> if you merge active orders with orders history, it should contain complete list, no ?

That will require two requests and we don't do more than one request per call in the library. Otherwise it would be a complete mess, believe me ;)

> Do you have any idea of how much delayed is order history ?

Can't tell exactly, but the delay is significant enough. Seconds.
