### ISSUE TITLE
Bitstamp withdrawal

### ISSUE THREAD

**Issue by wannesdemaeght** [ccxt/ccxt#1231]
Hi,

in the exchange properties for Bitstamp, has.withdraw is set to false, for both v1 and v2.
according to bitstamp api docs, both v1 and v2 ARE supporting withdrawals though...
https://www.bitstamp.net/api/

Any chance of adding this?

**Comment by kroitor** [comment]
Hi!

> Any chance of adding this?

Already in the library (added recently), the `has.withdraw` property is still unchanged though, because the library is under active development. We will update the metainfo for bitstamp. You can call withdraw() right away (with current version). Let me know if answers your question or not. Thx!

**Comment by wannesdemaeght** [comment]
oh great, thanks!
