### ISSUE TITLE
Binance Long/Short contracts

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12423]
Im trying to do new python bot, I wanna create Long or short contract orders on binance till i close it.

exchange.create_order("Which parameters should i use except symbol amount etc. to create contract")

**Comment by samgermain** [comment]
> Im trying to do new python bot, I wanna create Long or short contract orders on binance till i close it.
> 
> exchange.create_order("Which parameters should i use except symbol amount etc. to create contract")

For closing orders, just make sure you add `reduceOnly: true` to `params`, other than that everything should be the same as spot orders

**Comment by flav1ooo** [comment]
Can you help me about how to open a default long order and close it as syntax ? One example maybe.

Thank you.

**Comment by flav1ooo** [comment]
> > Im trying to do new python bot, I wanna create Long or short contract orders on binance till i close it.
> > exchange.create_order("Which parameters should i use except symbol amount etc. to create contract")
> 
> For closing orders, just make sure you add `reduceOnly: true` to `params`, other than that everything should be the same as spot orders

Can you help me about how to open a default long order and close it as syntax ? Also can you explain why should i close it with reduceOnly parameter? One example maybe.

Thank you.

**Comment by samgermain** [comment]
[Binance has a webpage that explains reduceOnly](https://academy.binance.com/en/articles/the-ultimate-guide-to-trading-on-binance-futures#what-is-post-only-time-in-force-and-reduce-only)

> When you’re in One-Way Mode, ticking Reduce-Only will ensure that new orders you set will only decrease, and never increase your currently open positions.

Here's a few examples on how to create an order

https://github.com/ccxt/ccxt/blob/c060fd2ddb1b3d913f78a9e77bf9af4968f12e0c/examples/py/binance-market-order-quote-usdt.py#L30
https://github.com/ccxt/ccxt/blob/affef1d7524a88a5ca9a99a6931436ef2c2e345c/examples/py/bitmex-create-order.py#L1
https://github.com/ccxt/ccxt/blob/6f2c2d932d053f00e6380f016a76d346c9e8fab3/examples/py/latoken-create-order.py#L1

Just use the classes `binanceusdm` or `binancecoinm` for binance futures instead of the class `binance`

```
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt

exchange = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

symbol = 'ETH/USDT'  # bitcoin contract according to https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
type = 'limit'  # or 'market'
side = 'sell'  # or 'buy'
amount = 1.0
price = 2500.0  # or None for market orders

# extra params and overrides
params = {
    'reduceOnly': True,  # On exit orders
}

order = exchange.create_order(symbol, type, side, amount, price, params)
print(order)
```

**Comment by samgermain** [comment]
@flav1ooo I'm going to close this issue, feel free to reopen it if you have any questions
