### ISSUE TITLE
How to stop a JS Interval?

### ISSUE THREAD

**Issue by jhanstra** [ccxt/ccxt#1246]
- OS: Mac 10.13.1
- Programming Language version: Node 8.0
- CCXT version: 1.10.694
- Exchange: Binance
- Method: createMarketBuyOrder

Hello, really appreciate this library. I started implementing my own API for Binance, and was relieved to find this and use it instead.

I am attempting to write a bot that awaits certain events and trades once a thing occurs. I am using the [forever](https://github.com/foreverjs/forever) npm package but am new to it too. I have been testing out the following code:

```
#!/usr/bin/env node --harmony
'use strict'

import ccxt from 'ccxt'

let binance = new ccxt.binance({
  apiKey: process.env.BINANCE_API_KEY,
  secret: process.env.BINANCE_SECRET_KEY,
})

const placeOrder = () => {
  try {
    binance.createMarketBuyOrder('LTC/BTC', 0.05, { type: 'market', timestamp: Date.now(), side: 'buy'}).then((response) => {
      console.log('response', response)
    })
  } catch (e) {
    console.log('e', e)
  }
}

const main = () => {
  placeOrder()
}

setInterval(main, 10000)

```

The problem is, this order is being continuous run on an infinite loop somehow even when the forever process is not running. If I go to the Binance UI, any trade I make that adds bitcoin to my balance is immediately traded for Litecoin in 0.05 ltc increments until there is no btc remaining. I go to my open orders and there are none listed. How can I quit this loop or cancel the existing market orders?

Thanks.

**Comment by kroitor** [comment]
Hi!

> The problem is, this order is being continuous run on an infinite loop somehow even when the forever process is not running. 

I'm not getting what you want: you're launching an infinite loop by doing setInterval, and it's a problem for you? ) Well, if it is, maybe, you should not launch the infinite loop in the first place? )

> How can I quit this loop or cancel the existing market orders?

1. You can't cancel a market order, because it is executed immediately, therefore the *market* type. You can only cancel limit orders that weren't closed previously.

2. This will run the loop until you have no more BTC:
```
#!/usr/bin/env node --harmony
'use strict';

const ccxt = require ('./ccxt.js')

let binance = new ccxt.binance({
  enableRateLimit: true, // ←-------------------------------- add these
  rateLimit: 10000, // ←-------------------------------- add these
  apiKey: process.env.BINANCE_API_KEY,
  secret: process.env.BINANCE_SECRET_KEY,
})

// rewrite here:

;(async () => {
    while (true) {
        try {
            const order = await binance.createMarketBuyOrder('LTC/BTC', 0.05)
            console.log (order)
        } catch (e) {
            console.log (e.constructor.name + ' ' + e.message)
            throw e
        }
    }
}) ()
```

3. Read this: https://github.com/kroitor/ccxt/wiki/Manual

Sorry, your question is not related to the library itself, but is more about doing proper JavaScript programming with timers + exception handling + rate-limiting with respect to previous result. For JavaScript timers you should google a tutorial. For exception handling, here's a link to the Manual on which exceptions should be handled: https://github.com/ccxt/ccxt/wiki/Manual#error-handling. Also check the Manual and the examples on how to do proper rate-limiting. I'm closing this if you don't mind.

**Comment by jhanstra** [comment]
Hey @kroitor, thanks for the quick response. It seems to be an issue (or a misunderstanding) with using the forever package. I know how setInterval works, but that's not what was causing the continuous market orders. The setInterval was set for 10 seconds, but it was placing orders multiple times per second. There must have been a forever process still spinning, even though listing the processes showed nothing. I restarted my computer and it stopped. Your first point is the main thing I was wondering - whether market orders are only executed right when they are submitted, or whether multiple orders could be queued in a backlog to execute once they were able to (i.e. once you have more bitcoin available to spend).

Thanks again!

**Comment by kroitor** [comment]
> whether market orders are only executed right when they are submitted, or whether multiple orders could be queued in a backlog

Well, yes, they are executed immediately or canceled (dropped), that is the usual pattern of a market order. No backlogging. We want a market price – it means now, not later.
