### ISSUE TITLE
Finding one step below of stop price question

### ISSUE THREAD

**Issue by kursadaydin** [ccxt/ccxt#12466]
- OS: Windows 10
- Programming Language version: Python 3.9.6
- CCXT version: 1.75.74

**I have the OCO function, it works fine, but how can I find 1 step below the stop price?**
**eg: stop price: 0.0047 stop_limit_price should : 0.0046
eg: stop price: 1.0 stop_limit_price should : 0.99**

````
async def createLimitSellOrderOCO (exchange, _symbol, _amount, _limit_price, _stop_price): #test edildi çalışıyor
    market = exchange.market(_symbol)
    print('___________________________________________________________')
    try:
        order = await exchange.private_post_order_oco({
            "symbol": market['id'], 
            "side": 'sell',
            "quantity":  exchange.amount_to_precision(_symbol,_amount), 
            "price": exchange.price_to_precision(_symbol,_limit_price), 
            "stopPrice": exchange.price_to_precision(_symbol,_stop_price),
            'stopLimitPrice':exchange.price_to_precision(_symbol,_stop_Price),
            'stopLimitTimeInForce':'GTC',
            
            })   
    except Exception as e:
        print('Failed to place', _symbol, 'order')
        print(type(e).__name__, str(e))
        print('___________________________________________________________')
    return order`
```

**Comment by ttodua** [comment]
If I correctly understand your question (correct me if your question is different) you want to find out what is the minimum ticksize for a symbol. It's `market['precision']['price']` for exchanges where `exchange.precisionMode` is set to `TICK_SIZE` . i.e. here instead of `mexc.js` , check any exchange you refer: https://github.com/ccxt/ccxt/blob/master/js/mexc.js#L225  (at this moment, there are still few exchanges which use `DECIMAL_PLACES or SIGNIFICANT_DIGITS`, and in that case you can `1/Math.pow(market['precision']['price'])` to get the minimum price movement value.

Let us know if you have any further issue.
