### ISSUE TITLE
Why 'create_time_ms' is not used in gateio?

### ISSUE THREAD

**Issue by SmartManoj** [ccxt/ccxt#12478]
https://github.com/ccxt/ccxt/blob/7359c23cfc938323ea3b4c6c72119e5a6feacba8/js/gateio.js#L2924

Seems `ctime` is removed. [Docs](https://www.gate.io/docs/apiv4/en/#get-a-single-order)

**Comment by carlosmiei** [comment]
Hello @SmartManoj 

We're not using create_time_ms because this field is not present in every type of order message (fetch, create, cancel,...) so we choose to use create_time instead (it's the same but in seconds and we convert it afterward) because it's generally more available than create_time_ms. Regarding ctime, we're using it as an alternative because sometimes it is what's in the order message instead of create_time/create_time_ms:

Example: https://www.gate.io/docs/developers/apiv4/en/#cancel-a-single-order-2
![image](https://user-images.githubusercontent.com/43336371/160106561-139c2c9e-65cd-4459-be01-0ef33d810fd9.png)
