### ISSUE TITLE
The orderId in takeprofit Id is different to the orderId I see in the trades' orderId when take profit order is triggered (FTX exchange)

### ISSUE THREAD

**Issue by jamezun** [ccxt/ccxt#12523]
- OS: Win 10
- CCXT Version: 1.76.58
- Python Version: 3.9.7
in FTX using CCXT, I notice that whenever a take profit order/stop loss triggered, when I retrieve the triggered order trades using fetch_my_trades(), the `orderId` of that trade is different from the `orderId` of the take profit order/stop loss order, why is that? shouldnt the trade should be referencing the take profit `orderId` or stop loss `orderId` instead? Is that a bug or when the take profit or stop loss is triggered, FTX will place a market order instead, so the` orderId` will be the market `orderId` instead of the take profit `orderId`/stop loss `orderId`?

**Comment by micant** [comment]
I'm currently tackling the same issue. This isn't a CCXT issue or a bug, but rather looks to be by-design from FTX. 
Fetching trigger orders used to return an `orderId` property referencing the `market` or `limit` order that gets executed on trigger - great 👍 
But now, for some reason, this is deprecated and this property returns `null` - not great 👎 
https://docs.ftx.com/#get-open-trigger-orders

As you said, when a trigger order is triggered, FTX will create a trigger order with a unique `id` - that has all the trigger order properties plus additional properties about the order executed. Then another `market` or `limit` order will be created with another unique `id` but without any trigger information.

So now it is not possible to link a trigger order to the market or limit order it executes using the data that FTX provides. This really doesn't make sense to me. Perhaps FTX is moving towards delineating trigger order from standard orders, but then why do they create a second order record with a unique id? It's inconsistent with other exchanges and logic - really.  

I don't know what the solution is other than programatically matching timestamps and order amounts between trigger orders and market/limit orders, but that feels really janky and becomes highly problematic when you're trading frequently.

I hope we're missing something obvious here.

**Comment by ttodua** [comment]
I've been trying to figure out this and turns out it is possible (though, not a standard approach by exchange API, unlike other exchanges, but still possible).
At first, when you have a position (i.e. already bought 0.1234 BTC-PERP) and then create take-profit order, either UI or from ccxt i.e.:
```
let order= await e.createOrder('BTC-PERP','takeProfit', 'sell', 0.1234, undefined, {stopPrice:47680});
```
then the order-id (only identifier) will be like `172902172`. (the same will be if you  do `fetchOpenOrders` or `fetchOrders` ) for that order. No other identifier will be available for that order. 
However, there is another endpoint, specifically for 'trigger' orders (yeah, I agree - this is not ideal scheme, as 'trigger' order is just an order with 'stop' (trigger/activation) price, which could have been handled with 'regular orders' endpoint) , at this moment it seems not to be unified in ccxt, but set as implicit:
```
let myOrder = await  e.privateGetConditionalOrdersConditionalOrderIdTriggers({'conditional_order_id':'172902172'});
```
where id is the same which was retrieved from `createOrder/fetchOrders`. Then, that endpoint (if that trigger order was executed) returns response like:
```
{
	"success": true,
	"result": [
		{
			"time": "2022-03-29T04:54:04.390665+00:00",
			"orderId": 132144259673,
			"error": null,
			"orderSize": 0.0001,
			"filledSize": 0.0001
		}
	]
}
```
where now you see the 'real' order-id (i.e. `132144259673`). That is the id which you can use later (i.e. `fetchOrderTrades('132144259673', ...)` to get the trades-list for it ..).

Hope this clarifies

**Comment by micant** [comment]
You absolute legend, I'll test this tonight. Thanks heaps for your help!
