### ISSUE TITLE
In kucoin fetch_order_book gets fully aggregated orderbook always when authenticated

### ISSUE THREAD

**Issue by SmartManoj** [ccxt/ccxt#12658]
- OS:
- Programming Language version:
- CCXT version: 1.78.18

https://docs.kucoin.com/#get-part-order-book-aggregated | v1
> You are recommended to request via this endpoint as the system response would be faster and consume less traffic

v3 also recommended. But the above statement makes sense and also due to their API performance.
And for v3, they have strict access frequency control.  Got 429 too.

So isn't it best to use v1 when limit is <=100?

**Comment by dmh1974** [comment]
I'm having the same issue, when i provide an api key, i get depth of 10's of thousands returned for fetchOrderBook with kucoin

I would like to be able to force v1 for these requests for 100 depth, it appears v3 has no limit

**Comment by dmh1974** [comment]
in the JS code for kucoin, it looks like once you are authenticated there is no option to specify depth, only when !authenticated

**Comment by dmh1974** [comment]
also, in case they dont get around to changing the authenticated override... here is a work around i am using.. calling the implicit method directly...

console.log(await kucoin.public_get_market_orderbook_level2_100({ symbol: 'BTC-USDT' }))

**note the syntax change for symbol requires a - instead of /

**Comment by DoctorSlimm** [comment]
Hi, this issue was fixed in: ccxt#13290
