### ISSUE TITLE
Is there a method by which I can check the permissions of my keys?

### ISSUE THREAD

**Issue by kuropatochka666** [ccxt/ccxt#12723]
For example like this 
```
        $exchange = new $exchange_class (array (
            'apiKey' => 'apiKey',
            'secret' => 'secret',
        ));
        $exchange->get_permissions()
```

```
      { 
        fetchBalance: true,
        fetchOpenOrders: true,
        fetchClosedOrders: true,
        fetchMyTrades: true,
        createOrder: false,
        cancelOrder: false,
      }
```

**Comment by ShieldTrade** [comment]
I am also interested in this issue. 

As far as I know most of the exchanges do not have an endpoint to check the permission associated with the private keys.

**Comment by ttodua** [comment]
We tried to look into this several years ago, but it turned out extensively complex and seems not viable or priority at this moment.
Best and easier thing would be that users did specific functionality detection on their own, like try/catch for `PermissionsDenied` (etc) exceptions to determine whether any desired method works for api-key or not.

**Comment by Gentleman-James** [comment]
For our ccxt use we need to gather read only exchange API keys from our users. We need to check that the keys they give us are read only for everyone security. This should be done the moment they give us the key, before we save the keys they give us in our database.
