### ISSUE TITLE
Identifying whether 2 different sets of API keys belong to the same account

### ISSUE THREAD

**Issue by serteikas** [ccxt/ccxt#12899]
Hello

Basically title. 

I have 2 sets of API keys and would like to know if they belong to the same account (mainly to prevent duplicates). Is there some kind of identification data of account that you can retrieve via exchange(-s) API?

Thanks.

**Comment by samgermain** [comment]
One way would be to use the [fetchDepositAddress](https://docs.ccxt.com/en/latest/manual.html#deposit-addresses) method. Your deposit addresses will be unique to your account. This method won't work on coinbase because they create new deposit addresses everytime

**Comment by samgermain** [comment]
I'm going to close this issue because using [fetchDepositAddress](https://docs.ccxt.com/en/latest/manual.html#deposit-addresses) should work. Feel free to reopen this issue if you have any more questions

Some exchanges also provide something like `userId` or `uid` within `info`, but those solutions would all be specific to that exchange
