### ISSUE TITLE
Question about ASYNC orders.

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#13073]
I just checked online but i couldnt find any certain answer. I wonder which of the two examples given below works faster and more accurately to generate orders?

Ex1:

```
Async x():
  await order1
  await order2
.
.
.
```

Ex2:

```
Async x():
  await asyncio.gather(order1,order2)
.
.
.

```
Thank you !

**Comment by carlosmiei** [comment]
Hello @flav1ooo , 
`asyncio.gather` will be more performant because all tasks will be scheduled concurrently so for instance while waiting for the I/O (server response for instance) of task A can start running the B and vice-versa. However, you have to bear in mind that `asyncio.gather` does not guarantee the execution order so you don't know which order will be placed first. If that is not a problem for you then you can use it and benefit from the performance improvement, otherwise, you should stick with the regular `await taskA, await taskB`

Please feel free to reopen it if this does not answer your question!
Thank you.
