### ISSUE TITLE
New Exchange: Waves

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1312]
api doc: https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API
url: https://wavesplatform.com/product
volume: N/A
address: Suite 1, 5 Percy Street, Fitzrovia, London, United Kingdom, W1T 1DG
company info: Radar Relay, LLC, https://www.linkedin.com/company/waves-platform-ltd/, https://en.wikipedia.org/wiki/Waves_platform, https://beta.companieshouse.gov.uk/company/10348537, https://wavesplatform.com/files/docs/Waves_terms_and_conditions.pdf
based country: LONDON
demo: 
priority: low
type: decentralised ex

**Comment by trgpwild** [comment]
@kroitor Waves DEX Rocks!!! I'm anxious for this!!!

**Comment by acamarata** [comment]
They recently re-branded and put a new focus of their whole team on promoting it as "Waves Exchange" instead of the whole platform with the DEX just being a part of it.  The new URL for them is https://waves.exchange and they have a roadmap for more exchange centric features and integrations - some of which should make linking up CCXT easier I think.

**Comment by acamarata** [comment]
Docs are here - https://docs.waves.exchange/en/waves-matcher/matcher-api
Also see - https://docs.waves.exchange/en/waves-exchange/waves-exchange-protocol

**Comment by rmcxm** [comment]
any update on this ???

**Comment by kroitor** [comment]
@acamarata @rmcxm we will address this asap, hope to get it merged soon.
