### ISSUE TITLE
Too much request weight used; current limit is 1200 request weight per 1 MINUTE

### ISSUE THREAD

**Issue by euphrates85** [ccxt/ccxt#13165]
OS: Windows
Programming Language version: Python 3.10
CCXT version: 1.77.62

```
exchange = ccxt.binance({
    "apiKey": 'xxx',
    "secret": 'yyy',
    'options': {
        'adjustForTimeDifference': True
    },
    'enableRateLimit': True
})

exchange.load_markets()
while 1:
    try:
        bars = exchange.fetch_ohlcv(ETH/USDT, timeframe='5m', limit=5)                                          
        df = pd.DataFrame(bars[:], columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')

    except ccxt.BaseError as Error:
        print("[ERROR] ", Error)
        continue

```
Hello,
I am running above code and i am not getting any error message regarding to request usage. However, after i am running 2nd trade bot in same IP with same code i am getting "more than 1200 request usage" error.
How can i calculate how many request i am creating in a minute? If i can calculate it, i will schedule to download ohlvc data in 2 or 3 seconds, or how many seconds it needs.

I have seen this link [weight on multiple Rest API endpoints](https://www.binance.com/en/support/announcement/f3d75a44fc7b4610b080b9c3499ed075)
But i couldnt find which endpoind i am calling. Is it GET /api/v3/exchangeInfo?

Edit: I am reading the documents. I am not an expert in coding but I am trying to understand as much as I can. The point I couldn't understand is, in my personnel computer I am running 5 bots at the same time and I am not receiving this error. However, when I run 2 bots in Aws server (EC2 t3.medium) I receive this error. I just couldn't figure it out

Thank you.

**Comment by DoctorSlimm** [comment]
@euphrates85  you do not need to calculate the amount of requests you send per minute yourself, this is done inside each `exchange ( )` instance which you create. You are likely getting issues because those two bots inside your EC2 instance both share the same IP address, and your IP address is therefore getting ratelimited. For best usage for calling market-data endpoints such as `fetch_ohlcv ()` in your case, run different bots on different IP addresses, perhaps . If you are calling private methods such as `fetchBalance ()` or `createOrder ()` then you cannot in most cases run more than one bot because the exchange will apply rate limits to your account itself rather than your IP address.

**Comment by kroitor** [comment]
More info on rate limiting here:

- https://docs.ccxt.com/en/latest/manual.html#rate-limit
- https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter
- https://docs.ccxt.com/en/latest/manual.html#error-handling

Let us know if that does not answer your question.

**Comment by seeyoul8r** [comment]
@kroitor Igor, hello! Where is it better to take a look about weights of queris? Your links above are not working. I'm looking for fetching single order information and how often I can call this method.
