### ISSUE TITLE
where is the example of using websocket?

### ISSUE THREAD

**Issue by xyq-c-cpp** [ccxt/ccxt#13318]
hi, i wanna find the example of using websocket, but i can not find it. so, Do ccxt has been impled it? if it has been impled, tell me where is it, thank you!

**Comment by samgermain** [comment]
There's lot of examples inside https://github.com/ccxt/ccxt/blob/2053c8771b6ac7094e409b4b99c2802c59642e31/examples

It depends on the language your using though

There's also examples inside the [ccxtpro manual](https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual), because the web socket is for ccxtpro

**Comment by xyq-c-cpp** [comment]
okay, i got it. i had been saw the website of https://ccxt.pro/pricing. where is the worker of ccxtpro, i wanna ask some questions about this.

**Comment by kroitor** [comment]
CCXT Pro Examples:

- https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/
- https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/py
- https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/js
- https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/php

Also docs and manuals:

- https://github.com/ccxt/ccxt/wiki/ccxt.pro.install
- https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual

CCXT Manual:

- https://docs.ccxt.com
