### ISSUE TITLE
Poloniex giving 403 error not accessible from this location

### ISSUE THREAD

**Issue by rohitkhatri** [ccxt/ccxt#1332]
poloniex GET https://poloniex.com/public?command=returnTicker 403 not accessible from this location at the moment

- OS: Mac OS High Sierra
- Programming Language version: Python
- CCXT version: 1.10.738
- Exchange: Poloniex
- Method: fetch_tickers

**Comment by kroitor** [comment]
You should handle these errors like described here:
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/kroitor/ccxt/wiki/Manual#error-handling
- https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting
- 

You can also try setting an arbitrary `.userAgent` that property is described here:
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

Alternatively, you can check if it works when you access it through a public CORS proxy (also in the Manual).

Without seeing your [code and verbose output](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) it's hard to tell he exact reason.

Closing this for now if you don't mind. Feel free to reopen it if needed, or just ask questions, but please paste code and verbose output, otherwise we won't be able to help you significantly.

**Comment by rohitkhatri** [comment]
@kroitor In verbose, It's printing html code and when I execute that code, It shows the captcha screen on poloniex

**Comment by kroitor** [comment]
@rohitkhatri have you tried setting a userAgent or a CORS-proxy? If you are polling all their tickers too frequenty, they can ban you temporarily.

**Comment by rohitkhatri** [comment]
@kroitor I just tried a CORS-proxy, and It worked, but is it a good solution?

**Comment by kroitor** [comment]
@rohitkhatri no, it's a bad one. Try it without a proxy, but with a userAgent first. If it works, then you have to randomize it to avoid their bans.

**Comment by rohitkhatri** [comment]
@kroitor Tried many user agents, but not working. :-(

**Comment by kroitor** [comment]
@rohitkhatri ok, then you need to use a cloudflare scraper, like described here: 
- https://github.com/ccxt/ccxt/issues/1001
Let me know if it helps you or not. If not, please paste your code.

**Comment by danoctavian** [comment]
@rohitkhatri what country are you connecting from? I noticed that connecting from certain countries prompts me with the captcha but as soon as I change to a US IP using a VPN it goes away specifically in the case of poloniex.

**Comment by kroitor** [comment]
Also this might help:
- https://github.com/ccxt/ccxt/blob/master/examples/js/bypass-cloudflare.js
- https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare.py
