### ISSUE TITLE
WS, WebSocket

### ISSUE THREAD

**Issue by 1nussebedernipes** [ccxt/ccxt#1333]
Hello, good Sir!

I try to found a solution to use ccxt and WebSocket. I have found this https://github.com/ccxt/ccxt/issues/762 and want to ask: maybe you can provide some "in-development/experimental" feature to us? It has more important for us because we need to try WebSocket API in our current project. Maybe you can provide some advice for me?

Best regards,
Iskandar

**Comment by kroitor** [comment]
Hi! 

The **main difficulty in this task** is to provide an *in-development* feature. When we have it in an experimental state, that would mean we have it all (the other work from there is trivial). Having it in experimental state is our topmost priority now. Basically, you're asking, if it is possible to do 90% of the job now, so that users could do the rest of 10%. Well, yes, that is possible, and that is what we are occupied with exactly.

I'd suggest to move this discussion here: https://github.com/ccxt/ccxt/issues/56 as these issues are duplicate somewhat.

Closing this for now, if you don't mind.

**Comment by 1nussebedernipes** [comment]
Many thanks for your answer!
