### ISSUE TITLE
Big issue with Huobi Futures

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13351]
Placing order on Huobi requires amount position, But on Huobi it represents in two ways (look on screens): as contracts, and as current coin. In my code amount is in current coin, but this brings error of Insuffient margin time to time. So is there any way to place orders not using contracts number, but using current cryptocurrensie value?

THIS one brings error, because my amount of buying DOGE with 5x is 300 in DOGE. This number goes to create_order amount.
```
balance = exchange.fetch_balance()["USDT"]["free"]
                offset = 'open'
                leverage = math.floor(exchange.fetch_leverage_tiers(coin+self.usdt)[coin+self.usdt+":USDT"][0]["maxLeverage"]*self.huobi_leverage)
                if leverage==1 or leverage==2 or leverage==3:
                    pass
                elif leverage>=5 and leverage<10:
                    leverage = 5
                elif leverage>=10 and leverage<20:
                    leverage = 10
                elif leverage>=20 and leverage<30:
                    leverage = 20
                elif leverage>=30 and leverage<40:
                    leverage=30
                elif leverage>=40 and leverage<50:
                    leverage=40
                else:
                    leverage=exchange.fetch_leverage_tiers(coin+self.usdt)[coin+self.usdt+":USDT"][0]["maxLeverage"]
                price = exchange.fetch_ticker(coin+self.usdt)["last"]
                amount = ((balance / price)*(leverage))
                result = "1"
                if (amount<1):
                    for elem in str(amount).split("0"):
                        if elem == "" or elem == ".":
                            result += "0"
                        else:
                            am = int(result)
                            amount=math.floor(amount*am)
                            break
                else:
                    amount = math.floor(amount*0.95)
                params = {'offset': offset, 'lever_rate': leverage}
                exchange.create_order(coin + self.usdt + ':USDT', 'limit', 'buy', amount, price, params)
```
It brings `huobipro {"status":"error","err_code":1047,"err_msg":"Insufficient margin available.","ts":1653035927343}`
But if in code i change amount just to 3, it works perfectly, because 3 is contract size on Huobi (look at screens). So how i can calculate amount for creating order in contracts?

**Comment by kroitor** [comment]
@KindSpidey the exchange APIs will usually represent the `amount` in contracts for derivatives, CCXT will not recalculate the value in whatever currency, it is up to the user. I mean, since it's not even an issue with CCXT, it's just the way contracts are traded, each contract has a contractSize, that is documented in the Manual:

- https://docs.ccxt.com/en/latest/manual.html#market-structure

So you can calculate the value of your position as you like.
You cannot buy a half or a quarter of a contract though, cause contracts are only traded in whole integer quantities. So if you're trading derivatives you will have to calculate the values of your positions in the userland with a few basic multiplications.

**Comment by ttodua** [comment]
Above answer by @ kroitor covered the topic , so, marking this issue as closed. Let us know if you have any further issue with CCXT.
