### ISSUE TITLE
Lbank2 - issues

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#13381]
_[ based on report : #1271 ]_
>  i was checking the create market order, and it seems that in the price i have to put the cost (price * amount) so it is shown properly on the trade list but i'm not sure if the mapping is ok or even following other exchanges, because the amount when i create the order is in "quote currency" and it should be in base currency right?
> ...
> The issue I see is with lbank2, I'm using lbank2 for almost everything, but, there are some calls I still do with lbank because with lbank2 are not working (as far as i have seen):  fetchOrderBook & fetchClosedOrders
> ...
> and when fetch the order, the amount is on quote currency, which misleads also the "filled" calculation

**Comment by garciapd** [comment]
I attach a screenshoot comparing the results of fetching the orders after placing them, mind that for Market ordrers, both buy and sell, I have to use a price -> (price * amount), so the cost, instead of the price, otherwise it doesn't work

![WhatsApp Image 2022-05-22 at 10 48 30 AM](https://user-images.githubusercontent.com/7051701/169687024-765ed22a-e313-4f9d-a3c7-cbf41eca01ec.jpeg)

You can see the different results, the order on the picture is:
- Buy Limit Order
- Sell Market Order
- Sell Limit Order
- Buy Market Order

the cost, amount and filled for Buy Limit, Sell Limit, Sell Market are ok, the difference is with Buy Market

**Comment by DoctorSlimm** [comment]
@garciapd thanks, am looking into it now

**Comment by DoctorSlimm** [comment]
@garciapd `fetchClosedOrders` is not a method on `lbank2`, you can use `fetchOrders`, and specify the exchange specific `status` you wish in the params for example:

```Python3
cancelled_orders = lbank2.fetchOrders('DOGE/USDT', None, None, {'status': -1})
```

the available options are: `-1: Cancelled 0: Unfilled 1: Partially filled 2: Completely filled 3: Partially filled has been cancelled 4: Cancellation is being processed`

does that help?

**Comment by garciapd** [comment]
@DoctorSlimm does the fetchOrderBook call work for you? it was not giving me all the orders with mine included

**Comment by kroitor** [comment]
@garciapd do you have this issue with the most recent version (1.83.57+) ?

**Comment by garciapd** [comment]
the market order has been fixed thanks!

Although, when fetching the orderbook with lbank and lbank2, there are many differences, it looks like almost another exchange

**Comment by garciapd** [comment]
thanks! really appreciate your effort :D

**Comment by ryanreed357** [comment]
I don't understand I was thinking all that was fuckery to me . I don't know
how to read it.. I'm down to make big money and I'll share but
