### ISSUE TITLE
order fields - average, filled, cost

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#13486]
Is the following expression correct for the orders fields  ->  cost = average * filled  ?

**Comment by YuriyTigiev** [comment]
What difference between price and average, amount and filled? 
I found that for kucoin (spot) fields average and filled, cost is empty, but for binance they are filled.
Is amount (response) equal the parameter amount from function createOrder?

**Comment by ttodua** [comment]
Late reply here. As you refer to returned `order` object's fields:
- `amount` is whatever user sets
- `filled` as it reads, is the amount that was filled from whole `amount`
- `price` is whatever user sets (if it's market order, then this field is empty)
- `average` is the median (average) filled price of order (as it may have multiple trades at different price).
You are almost right, theoretically, the returned cost from order is `average * filled` , however, on top of that, exchanges might  include fees, so, you have to consider them too.
On the other hand, the `cost` (as a part of user-request, instead of response from exchange) can be used to determine the whole `price * amount` (as opposed to `average * filled`).

Hope that helps. let us know if you have any further question/issue with ccxt.

**Comment by YuriyTigiev** [comment]
Hi, 

Thank you for you attention. 
What I found for FTX sport market -  average, filled and cost set None and status = 'open' for a market order.  
A fetch_order method returns real values for average, filled and cost for orders with a status = 'closed'

**Comment by ttodua** [comment]
You might be right - some exchanges doesn't provide complete information back to order-submitting requests. However, full infos are mostly available from `fetchOrder(s)` endpoint(s).
