### ISSUE TITLE
Check whether the last transaction is completed huobi.pro

### ISSUE THREAD

**Issue by rohitkhatri** [ccxt/ccxt#1355]
I am trying to fetch the recent transaction or deposit, and see if whether the transaction is completed.

- OS: Mac OS High Sierra
- Programming Language version: PHP 7
- CCXT version: 1.10
- Exchange: huobi.pro
- Method: need to figure out which method to use for fetching the last transaction

**Comment by kroitor** [comment]
@rohitkhatri 

The method is `private_post_dw_balance_transfer()`, we don't have the transaction history unified yet. 

To get all methods supported: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```
import ccxt
from pprint import pprint
exchange = ccxt.huobipro()
pprint(dir(exchange))
```

Hope it answers your question.

**Comment by rohitkhatri** [comment]
@kroitor I'm getting this error

huobipro {"status":"error","err-code":"bad-argument","err-msg":"Argument is invalid. to","data":null}

    $api = new \ccxt\huobipro([
        'apiKey' => 'api key',
        'secret' => 'secret'
    ]);

    var_dump($api->privatePostDwBalanceTransfer());

**Comment by kroitor** [comment]
@rohitkhatri then you need to check their docs, because that method is their custom (non-unified) API from ccxt.
Their docs are here: 
- https://github.com/huobiapi/API_Docs/wiki/REST_api_reference

However, that method is actually incorrect, my bad. In fact, I don't see any method in their API that would return that info. Sorry for misleading you.

**Comment by rohitkhatri** [comment]
@kroitor thanks
