### ISSUE TITLE
remove need to supply cost param in OKEX createOrder

### ISSUE THREAD

**Issue by michnovka** [ccxt/ccxt#1390]
- OS: Linux
- Programming Language version: JS
- CCXT version: 1.10.780
- Exchange:OKEX
- Method:createOrder

I do not understand why I have to supply additional costs param:

```
                if (side === 'buy') {
                    order['price'] = this.safeFloat (params, 'cost');
                    if (!order['price'])
                        throw new ExchangeError (this.id + ' market buy orders require an additional cost parameter, cost = price * amount');
                }
```

Since the method signature is

    async createOrder (symbol, type, side, amount, price = undefined, params = {})

why not just use amount and fetch ticker for latest ask price for given symbol? would be much more elegant, even though it requires one API call more.

If you agree, I will work on this change @kroitor

**Comment by kroitor** [comment]
> would be much more elegant, even though it requires one API call more

Unfortunately, can't do that. Can't decide for the user which request should be next and how much time should be spent waiting for those requests to be executed. Therefore the policy throughout the library is to make one HTTP request per one call to keep it explicit (and let the user decide). This boils down to rate-limiter reasons, explained here: #1175.

> why not just use amount and fetch ticker for latest ask price for given symbol?

That is exactly what the user is required to do by means of the library, but the library won't do it for you. It offers methods, but doesn't solve any possible user-level use-case. You will have to code the business logic in userland, because the library can't decide that for you (the desired behaviour may be all too different for other users).

Hope it answers your question. Let me know, if not. Thx!
