### ISSUE TITLE
Cannot get deposits and withdrawals data from Coinbase 

### ISSUE THREAD

**Issue by miranska** [ccxt/ccxt#14001]
I failed to get a list of deposits and withdrawals from Coinbase. 

- OS: MacOS
- Programming Language version: Python 3.9.7
- CCXT version: 1.88.26

I've tested the following code on several currencies:
```python
test_currency = 'USDT'
exchange = ccxt.coinbase({'apiKey': 'KEY', 'secret': 'SECRET'})
print(exchange.fetch_withdrawals(code=test_code))  # results in []
print(exchange.fetch_deposits(code=test_code))  # results in []
```

From what I can see, the `account id` is obtained correctly, but the deposit and withdrawal endpoints return empty payloads:

`fetch_withdrawals` response:
```
fetch Response: coinbase GET https://api.coinbase.com/v2/accounts/8[CUT]6/withdrawals 200 ResponseHeaders: {[CUT]} ResponseBody: {"pagination":{"ending_before":null,"starting_after":null,"previous_ending_before":null,"next_starting_after":null,"limit":25,"order":"desc","previous_uri":null,"next_uri":null},"data":[]}
```

`fetch_deposits` response:
```
fetch Response: coinbase GET https://api.coinbase.com/v2/accounts/8[CUT]6/deposits 200 ResponseHeaders: {[CUT]} ResponseBody: {"pagination":{"ending_before":null,"starting_after":null,"previous_ending_before":null,"next_starting_after":null,"limit":25,"order":"desc","previous_uri":null,"next_uri":null},"data":[]}
```

**Comment by carlosmiei** [comment]
Hello @miranska,

After some tests, I believe this is a problem with Coinbase's API engine and not CCXT since, as you can see in the image attached, even using their python SDK I'm getting an empty array for accounts that have had recent deposits/withdrawals. Nonetheless, I've reached support and am waiting for a response from them. I'll let you know as soon as I have more information.

![image](https://user-images.githubusercontent.com/43336371/175355318-0cb981f2-11da-4f1b-8702-2bd5b4888d66.png)

**Comment by ttodua** [comment]
@carlosmiei can you share what follow-ups have you got (if any)?

**Comment by dakkusingh** [comment]
any update on this?

**Comment by carlosmiei** [comment]
@dakkusingh Are you still facing this issue? What's your ccxt version?

**Comment by ttodua** [comment]
> @dakkusingh Are you still facing this issue? What's your ccxt version?

that was still an issue and i've pushed fixes
