### ISSUE TITLE
bitfinex in ccxt.async_support. More than 10 sec waiting for the response of load_markets() and fetch_balance

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#14018]
When bitfinex.load_markets() and bitfinex.fetch_balance() are being run in **async** mode,  **waiting time for the response is more than 10 sec**

When bitfinex.load_markets() and bitfinex.fetch_balance() are being run in **synchronous** mode, waiting time is about 1 sec

- OS: Windows 11, ubuntu 20,04
- Programming Language version: python 3.7, python 3.9
- CCXT version: 1.88.39

```
async def main():
    bitfinex = ccxt.bitfinex()
    bitfinex.apiKey, bitfinex.secret = ......., ..........

    start = time()
    result_gather = await asyncio.gather(
        asyncio.create_task(bitfinex.load_markets())
    )
    duration_load_markets = time() - start      # 12 sec

    # fetch_balance
    start = time()
    wait_done, wait_pended = await asyncio.wait([
        asyncio.create_task(bitfinex.fetch_balance())
    ])
    duration_wait_fetch_balance = time() - start        # 12 sec

    wait_result = list()
    for res in list(wait_done):
        wait_result.append(res.result())

if __name__ == "__main__":
    print(asyncio.get_event_loop().run_until_complete(main()))
```

**Comment by DoctorSlimm** [comment]
@DmitryVil also there is no need to use asynchronous code in your situation, because `fetch_balance` loads the markets when you are calling it. And you also dont need to use gather in this case either because `load_balance` actually only calls a single endpoint. `asyncio.gather()` is mostly useful for making multiple http calls concurrently and awaiting their result.

**Comment by DmitryVil** [comment]
@DoctorSlimm, I prepared this example only to show the problem with bitfinex.
Of course, async mode is dedicated to multiple requests.

Could you please explain difference between bitfinex and bitfinex2?

**Comment by Serpens66** [comment]
"5 times per minute which translates to 12 seconds between requests" ?
Why not maintaining a list of the latest timestamps? This way the user could do 5 calls within one second if he wants and then needs to wait 1 minute to do more. It is more flexible and just better for professional traders (maybe offer different ratelimit-modes, so the user can choose simple or advanced method)

**Comment by kroitor** [comment]
> maybe offer different ratelimit-modes, so the user can choose simple or advanced method

Actually, we're working on that and will have a number of rate limiting policies exactly for that purpose. Hope to get that done soon!

**Comment by DoctorSlimm** [comment]
@DmitryVil `bitfinex` is am implementation of the old and soon to be deprecated v1 API  https://docs.bitfinex.com/docs#api-v1-or-api-v2 and `bitfinex2` is the more recent v2 API with lower ratelimits, and increased performance.

**Comment by ttodua** [comment]
@DmitryVil I've been testing this issue, and it turns out that you only missed one small detail, which had messed up whole things (and they were seen as bug).
As you want to use asynchronous functionality (asyncio) then you should use the related ccxt import:
```
# import ccxt
import ccxt.async_support as ccxt
```

and your above code will work as you expect (in around few seconds the script will finish its job). 
Just in the end, add `await bitfinex.close()`.
Additionally, you might use `asyncio.run` instead of `asyncio.get_event_loop().run_until_complete(..`

Hope that helps, let us know if you experience other issues.
