### ISSUE TITLE
Exchange typescript definition incorrect for loadMarkets, missing for fetchMarkets

### ISSUE THREAD

**Issue by ajsharp** [ccxt/ccxt#1413]
- OS: OS X High Sierra
- Programming Language version: Node 8.9.3
- CCXT version: 1.10.802
- Exchange: bittrex, gdax
- Method: exchange.loadMarkets, exchange.fetchMarkets

The incorrect code is here: https://github.com/ccxt/ccxt/blob/675d74e5eb02dc87216a4a9897af86427c8a19b2/ccxt.d.ts#L114

`ccxt.Exchange.loadMarkets()` returns an Object of markets, keyed by the market symbol. The `fetchMarkets()` method is seemingly the same method, but returns the data in an array. However, the typescript definition file only includes `loadMarkets()` right now. I'd be happy to submit a PR that adds `loadMarkets()` to the typescript definition and fixes the issue with the `loadMarkets()` definition.

It's not clear to me what the difference `fetchMarkets()` and `loadMarkets()` is, though it seems that the subclasses are expected to implement `fetchMarkets()` while the exchange base class defines `loadMarkets()`. Either way, the `loadMarkets()` definition in the typescript file is incorrect.

**Comment by kroitor** [comment]
> I'd be happy to submit a PR that adds loadMarkets() to the typescript definition and fixes the issue with the loadMarkets() definition.

We will be happy as well and we are open to all proposals and welcome all contributions! ) However, you might want to take a look here, for example: https://github.com/ccxt/ccxt/pull/785

We are currently merging that PR (with a few edits on the way), so this problem might well be covered by an existing commit already. We would be thankful for a review from you anyway.

> It's not clear to me what the difference fetchMarkets() and loadMarkets() is

The loadMarkets is to be called by a user, and the fetchMarkets is to be called by internal code (also available to the user). So, the base method is the preferred way of loading, because it calls fetchMarkets + fetchCurrencies (where available). Also, the loadMarkets call is responsible for populating the initial state of the markets and currencies within the exchange (including their properties). So, most of the time you are **required** to call loadMarkets (not fetchMarkets) before accessing the `.markets` of an exchange.

Let me know if it doesn't answer your question.

Thank you!

**Comment by ajsharp** [comment]
> We will be happy as well and we are open to all proposals and welcome all contributions! ) However, you might want to take a look here, for example: #785

Great yea, it looks like it's fixed here: https://github.com/ccxt/ccxt/pull/785/files#diff-b21562953bcf119502df497717acef06R262. 

> The loadMarkets is to be called by a user, and the fetchMarkets is to be called by internal code (also available to the user).

Awesome, thanks for this explanation. You might consider marking this method semi-private in some way (maybe renaming to `_fetchMarkets()`). But I totally understand if there's more of a drive to power forward and not worry about deprecations and backwards compatibility and such. 

Thanks for the speedy support. Very much appreciated. Will track #785 going forward. Closing.

**Comment by kroitor** [comment]
Ok, cool ) 

Let us know if you have any other questions! 

One more thing I would add: having no other means of accessing market info, the ccxt library has to preload it implicitly in order to work correctly, and it will loadMarkets upon your first call to any method of the unified API. It is done once, then cached, and can then be force-reloaded by the user on demand. More about it here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Cheers!
