### ISSUE TITLE
Create github labels for new exchanges

### ISSUE THREAD

**Issue by thijstriemstra** [ccxt/ccxt#1414]
that can be applied to issues and pull requests.

**Comment by mkutny** [comment]
I'd actually move all of them to a single issue. There are really clogging the workspace )

**Comment by kroitor** [comment]
@mkutny we will think of a way to close them, but keep a list of what is "in progress" somewhere accessible. Will also merge many of them little by little as well.

**Comment by wannesdemaeght** [comment]
I agree with OP

**Comment by thijstriemstra** [comment]
ping @kroitor (if you can give appropriate permissions, i'll do it myself and keep an eye on it in the future).

**Comment by kroitor** [comment]
@thijstriemstra I probably misunderstood your proposal at first, but you used the word *new*, and I thought of adding some types of labels to the builds that are introducing support for new exchanges. But now it seems to me that you actually wanted to create labels for each exchange to label the issues, is that right? Because, if this is the case, we can create them, of course, however, I'm still not sure about the permissions (whether this is possible or not within GitHub rights).

**Comment by thijstriemstra** [comment]
> I thought of adding some types of labels to the builds that are introducing support for new exchanges.

Yep, that's what I meant as well. That way you can filter on label/new exchange.

**Comment by kroitor** [comment]
Related: 

- https://github.com/isaacs/github/issues/311
- https://github.com/dear-github/dear-github/issues/113#issuecomment-232428812

From above it follows, that GitHub's permission system does not have a fine-grained permission system. They just have read / write / admin. Which isn't enough, obviously, and it's a big pain for most of teams. We are going to work around this limitation via their API, but, maybe not right now, after adding WS support and all that... We will probably write a bot hooked up to their webhooks. The bot will have necessary write permissions, and we will give it a brain to put labels on issues that have matching words, and it will be able to read some commands from developers listed on our contributors page.

**Comment by jorijnsmit** [comment]
So unrelated to OP but related to sub thread: yes they are clogging the issue list. Maybe a start would be to label all new exchange requests with a "new exchange" label instead of "enhancement"? This would make filtering them out (or in) a lot easier already.

**Comment by jorijnsmit** [comment]
To solve the actual issue @thijstriemstra brought up: I think with so many exchanges it would be overkill to create 80+ labels. Maybe tags in the issue's title using the exchange's id would render a similar result? For example prefixing the issue's title with [gatecoin] or [binance] if the issue is related to that specific exchange?

**Comment by thijstriemstra** [comment]
I  see the labels now, I think this can be closed @kroitor.
