### ISSUE TITLE
Canceling an order by `clientOrderId` in TypeScript

### ISSUE THREAD

**Issue by nl** [ccxt/ccxt#14201]
Hi 👋🏻

This is a typing question. Several past, closed issues like [this one](https://github.com/ccxt/ccxt/issues/7086) and [this one](https://github.com/ccxt/ccxt/issues/10112) indicate that it is possible, in Python, to cancel an order simply providing the instrument and the `clientOrderId`. In this case, one is instructed to pass `None` to the main order `id`.

However using the TypeScript client, one can see [in the typing file](https://github.com/ccxt/ccxt/blob/e801cb2564e3f6464a5b986a982461c43749cac2/ccxt.d.ts#L376) that the `id` parameter is *not* optional, and will not accept, say, `undefined`.
Is this a small mistake in the types or am I overlooking something?

- Programming Language version: Node.js 16 w/ TypeScript 4.x
- CCXT version: 1.89.92

**Comment by carlosmiei** [comment]
Hello @nl,

This is tricky technically the **id** is not an optional parameter but as you noticed sometimes the user wants to use the **clientOrderId** instead so in Python they set `id = None` and pass it in params. If you want to do the same thing in typescript, I would suggest passing any string in the id parameter (empty string for instance) and then specifying the **clientOrderId** in params.  I'm not sure this will work for every exchange because each implementation is different but let us know if you find any trouble with it

**Comment by ttodua** [comment]
I think the above answer renders the topic ready for close. Let us know if you have any further issues with CCXT.
