### ISSUE TITLE
create_market_order in exchange.py

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#14249]
- Programming language version: Python
- CCXT version: 1.90.29

Why did you modify the create_market_order function in exchange.py?
The documentation is not up to date.
https://docs.ccxt.com/en/latest/manual.html?highlight=create_market_order#market-orders

Now we have to add the price argument when we call it.
```
def create_market_order(self, symbol, side, amount, price, params={}):
        return self.create_order(symbol, 'market', side, amount, price, params)
```

What should we specify as the price for a market order?

the function should not be like this::
```
def create_market_order(self, symbol, side, amount, params={}):
        return self.create_order(symbol, 'market', side, amount, None, params)
```

Thanks

**Comment by ttodua** [comment]
yes, seems a mistake in one of the recent updates. submitting fix shortly.

**Comment by ttodua** [comment]
Thanks for report.
Your statement is partially true, but not fully. The reason is that:
1) in most cases, market-order for buying something, doesn't need to have a price.
2) in other cases, some exchanges require that even market-order had price to calculate the maximum permitted spent of funds. (you can search for keyword `createMarketBuyOrderRequiresPrice` to find out such exchanges across ccxt library). so, that's why , CCXT's unified method `createMarketOrder` needs to have `price` in supported arguments, whenever user/exchange needs to make use of it. 

However, the bug is that, by default, it should be undefined/None/null. So, i've submitted the [PR](https://github.com/ccxt/ccxt/pull/14255) which only sets that default value.

**Comment by Hadevmin** [comment]
Thanks ttodua for the commit and the explanations. 
I didn't submit a PR because I don't have the overview of the project. But with your and kroitor's exhaustive explanations, it is getting easier to take control of the project.

Thanks a lot!

**Comment by ttodua** [comment]
> Thanks ttodua for the commit and the explanations. I didn't submit a PR because I don't have the overview of the project. But with your and kroitor's exhaustive explanations, it is getting easier to take control of the project.
> 
> Thanks a lot!

good luck, that is the correct direction, as ccxt and it's functionality is intended to be eventually understood by user very well, to know how things work. that's why there is a big manual, and users have frustrations without reading it. However, what you have found was a bug, and whenever you find other issues, let us know again. thanks
