### ISSUE TITLE
Can I create market maker with ccxt?

### ISSUE THREAD

**Issue by copyNdpaste** [ccxt/ccxt#14297]
There are some services that support creating market maker such as humming bot...

Can I create market maker with ccxt without those services?
I mean ccxt is enough to make market maker? I think I have to implements some AMM strategies manually and I seems too hard.

What is the better solution?

**Comment by carlosmiei** [comment]
Hello @copyNdpaste,

Of course, you can be a market maker using ccxt, everytime you place an order that lands in the orderbook you're market-making, you just need to set the option that flags it (usually `postOnly`) upon creating your orders (or else won't be guaranteed even if it is a limit-order). 

You can read more about it here:
- https://www.binance.com/en/support/faq/360007720071
- https://support.kraken.com/hc/en-us/articles/360000526126-What-are-Maker-and-Taker-fees-
- ...

Regarding the second question, everything is possible because ccxt is only a middleware/ unified API so you have full flexibility to do the implementations you want but some programming/trading knowledge is required to implement trading bots. 

If don't want to implement it from scratch you can take a look at freqTrade, a python framework that uses ccxt under the hood and allows you to set up different types of trading bots in a very easy way: https://www.freqtrade.io/en/stable/
