### ISSUE TITLE
Get realised pnl from trades

### ISSUE THREAD

**Issue by StartingProgramming** [ccxt/ccxt#14294]
- OS: Microsoft
- Programming Language version: Python
- CCXT version: 1.72.98

```
phemex = ccxt.phemex({
    'apiKey': API_KEY,
    'secret': API_SECRET,
    "adjustForTimeDifference": False,
    'enableRateLimit': False,
    'verbose': False
})
response = phemex.fetchClosedOrders(symbol = "BTCUSD")
pprint(response)
```

```
  {
      'id':                '12345-67890:09876/54321', // string
      'clientOrderId':     'abcdef-ghijklmnop-qrstuvwxyz', // a user-defined clientOrderId, if any
      'datetime':          '2017-08-17 12:42:48.000', // ISO8601 datetime of 'timestamp' with milliseconds
      'timestamp':          1502962946216, // order placing/opening Unix timestamp in milliseconds
      'lastTradeTimestamp': 1502962956216, // Unix timestamp of the most recent trade on this order
      'status':      'open',        // 'open', 'closed', 'canceled', 'expired', 'rejected'
      'symbol':      'ETH/BTC',     // symbol
      'type':        'limit',       // 'market', 'limit'
      'timeInForce': 'GTC',         // 'GTC', 'IOC', 'FOK', 'PO'
      'side':        'buy',         // 'buy', 'sell'
      'price':        0.06917684,   // float price in quote currency (may be empty for market orders)
      'average':      0.06917684,   // float average filling price
      'amount':       1.5,          // ordered amount of base currency
      'filled':       1.1,          // filled amount of base currency
      'remaining':    0.4,          // remaining amount to fill
      'cost':         0.076094524,  // 'filled' * 'price' (filling price used where available)
      'trades':     [ ... ],        // a list of order trades/executions
      'fee': {                      // fee info, if available
          'currency': 'BTC',        // which currency the fee is (usually quote)
          'cost': 0.0009,           // the fee amount in that currency
          'rate': 0.002,            // the fee rate (if available)
      },
      'info': { ... },              // the original unparsed order structure as is
  }
```
I try to get realised pnl using ccxt for my trades, but I don't get it. Can someone help me?
Thanks

**Comment by carlosmiei** [comment]
Hello @StartingProgramming,

PNL is not a **trade** concept, a trade is only a record of buying/selling an asset that does not have the profit/loss concept. 

Assuming that you intend to check the PNL of a derivative position, I would suggest looking into **fetchPosition(s)** because positions keep track of the unrealized profit/loss by comparing the current contract price with the entry price used for opening the position. 

You can read more about it here: https://docs.ccxt.com/en/latest/manual.html?highlight=position#positions

**Comment by ttodua** [comment]
I would add a note:
- firstly, you should ensure in the terms what you want to get - realized Pnl is different from Unrealized Pnl.
- we are in the process of unification of fetchPosition/fetchPositions. It also entails accustoming the `realizedPnl` field.
- in the meanwhile, before we add field that in native unified structure, as @carlosmiei suggested you should use `fetchPosition(s)` and check `info` key in the response to find out, whether it contains any information (from your target exchange) about realized Pnl, because some exchanges might not provide any information at all.  if they dont provide that information, then you should do the homework to find out the specific was for that specific exchange to calculate your realized pnl (like @carlosmiei  suggested, maybe check unrealized pnl and remaining position amount, and compare that to initial position amount and order-price that happened last time, which could have closed the position partially).

**Comment by StartingProgramming** [comment]
I saw unrealised pnl from `fetchPosition(s)`, but unrealised pnl is the pnl while the trade is open, isn't? I want to check the pnl (or the roi) right after the trade is closed. So I want to see the profit of the trade minus fees, which is the overall pnl (absolute or in percentage)  from one complete contract trade. Is tis available? (I am using phemex)

**Comment by dorienh** [comment]
I find it strange that this object does not give us the info needed to calculate PnL. 

Is price the closing price or opening price? Since it is the one used to calculate cost, I assume opening price. So how do we see at which cost or closing price the position was closed given that we only have this object. Do we need to do a second call?
