### ISSUE TITLE
Phemex ID not found for edit_order, (Market =market) 

### ISSUE THREAD

**Issue by sfaezi** [ccxt/ccxt#14407]
Is there any way to edit perpetual trades in Phemex? I see that limit trades can be edited but I cannot edit/cancel when the trade type is market. I am not sure what to use as ID.  I keep receiving ID not found error.

- OS: Mac 
- Programming Language version: Python
- CCXT version: 1.66.32

```
import ccxt 
exchange = ccxt.phemex({
        'apiKey': testnet_key0,  # testnet keys if using the testnet sandbox
        'secret': testnet_secret0,  # testnet keys if using the testnet sandbox
})

exchange.set_sandbox_mode(True)  # uncomment to use the testnet sandbox

markets = exchange.load_markets()

amount = 10
symbol = 'BTC/USD:USD'

# Opening and Canceling a pending contract (limit) order
order =  exchange.create_order(symbol, 'market', 'buy', amount, None, {})

response = exchange.edit_order(order['id'],symbol, params={'stopLossPrice': 20000, 'takeProfitPrice': 40000})
pprint(response)
```

```
Error:
ccxt.base.errors.OrderNotFound: phemex {"code":10002,"msg":"OM_ORDER_NOT_FOUND","data":null}
```

**Comment by carlosmiei** [comment]
Hello @sfaezi,

Trades cannot be edited because they're only "execution reports" you don't control how and when they will be executed. You can't also edit "market" orders since they're executed immediately. 

I would suggest reading the entire manual carefully so that you can clear up these trading concepts a bit.

More information regarding this question:
- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades
- https://github.com/ccxt/ccxt/wiki/Manual#order-structure
- https://github.com/ccxt/ccxt/wiki/Manual#trade-structure

**Comment by sfaezi** [comment]
Thanks for your suggestions. I read the manuals thoroughly and I understood the concept of market trades. However, I was not able to solve my problem.
The Phemex website lets you set a new stop-loss price and take-profit price values after placing a perpetual order with leverage. How can I recreate that throw APIs?

The following command creates a perpetual (contract) order on the website

leverageResponse =  exchange.set_leverage(leverage, symbol)
order =  exchange.create_order(symbol, 'market', 'buy', amount, None, {})
