### ISSUE TITLE
Unable to create market buy order on Huobi Global

### ISSUE THREAD

**Issue by SergeySypalo** [ccxt/ccxt#14412]
Thanks for fixing placing sell orders on Huobi Global ([14387](https://github.com/ccxt/ccxt/issues/14387)), but looks like there is a problem with automatically calculating order price for buy orders on spot market

- OS: Windows 11
- Programming Language version: Python 3.10.5
- CCXT version: 1.90.89

```
exchange.create_market_buy_order('SOL/USDT', 5)
```

```
ccxt.base.errors.InvalidOrder: huobi market buy order requires price argument to calculate cost(total amount of quote currency to spend for buying, amount * price). To switch off self warning exception and specify cost in the amount argument, set .options['createMarketBuyOrderRequiresPrice'] = False. Make sure you know what you're doing.
```

On other exchanges such as Binance, code works as expected.

**Comment by carlosmiei** [comment]
Hello @SergeySypalo,

This time is not a bug but an implementation quirk, Huobi and some other exchanges for market buy orders require the user to provide the "cost" of the order instead of the "base amount". So even though it's a market order that should not require a "price" argument we're requiring it so that we can calculate the "cost" (amount * price) and send it to Huobi.

Practical example:

If you want to buy 0.1 BTC using USDT, usually you would do:
```Python
exchange.create_market_buy_order("BTC/USDT", 0.1)
```

That is not possible in Huobi since we have to provide the "cost", so here instead of saying I want to buy 0.1 BTC, we have to say " I want to spend X USDT".

Assuming that the BTC price is 10 000 USDT and you want to buy 0.1 BTC the cost would be 1000 USDT. so you would have to place the order like this:

```Python
exchange.create_order("BTC/USDT", "market", "buy", 0.1, 10000) # cost will be 0.1*10000 = 100, price will only be used to calculate it
```

Alternatively, you can disable this warning and supply the cost directly in the amount parameter:

```Python
exchange['options']['createMarketBuyOrderRequiresPrice'] = False
exchange.create_market_order("BTC/USDT", 100) # meaning you want to buy 100 USDT worth of BTC
```

Please let us know if that does not answer your question!

**Comment by ldkklj** [comment]
Same problem :
If I use 'exchange['options']['createMarketBuyOrderRequiresPrice'] = False',will raise an error :TypeError: 'huobi' object is not subscriptable,So I changed to::
huobiN.optiosn['createMarketBuyOrderRequiresPrice'] = False
huobiN.create_market_order("BTC/USDT", 10)
Then will also raise an error::
TypeError: create_market_order() missing 2 required positional arguments: 'amount' and 'price'

**Comment by SergeySypalo** [comment]
Hello @carlosmiei 
Thanks for the reply, yeah I worked it around using the following code:
```
prices = exchange.fetch_tickers()
ask = float(prices['SOL/USDT']['ask'])
usdtamount = 10
amount = round(usdtamount/ask,4)
exchange.create_market_order('SOL/USDT', 'buy', amount, price=ask)
```
But thought as this is a market order, I don't care about execution price, so this calculation can be implemented on ccxt side for exchanges requiring that.

**Comment by carlosmiei** [comment]
Hello @ldkklj, in this case you should be using `create_market_buy_order('BTC/USDT', 10)` or specify the side `create_market_order('BTC/USDT', 'buy' ,10, None)`

**Comment by ldkklj** [comment]
Thanks @carlosmiei
It works,but can you show me how to create a future market order in huobi,
I use this code :
huobiN.create_market_order('BTC/USDT:USDT', 'buy' ,10, None,params = {'offset': 'open', 'lever_rate': 1,'marginType': 'cross'})
it always raise an exception:
"err_code":1049,"err_msg":"Open a position with market price is not available.contracts","ts":1658305448673}

**Comment by carlosmiei** [comment]
@ldkklj, as you can see, in the error, unfortunately, Huobi does not support market orders for contracts (you can easily confirm this on their website) so you must stick to limit orders.
