### ISSUE TITLE
Using CCXT in JS or python? [Performance Question]

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#14470]
Assuming we're making any crypto coin  software that pulls data and creates orders, is javascript or faster python? Why ?

**Comment by carlosmiei** [comment]
Hello @flav1ooo, not an easy answer but I'll try 

If we're talking about raw performance, python will be comparatively slower than Javascript/Node.js in most cases, because Node uses the V8 Javascript engine and is capable of advanced multithreaded operations under the hood. Actually, JS is one of the fastest scripting languages out there.

Let's consider these samples:

Python sample 1:
``Python
start_time = time.time()
sum = 0
for i in range(0, 200000000):
    sum+=i
duration = time.time() - start_time
print("Duration (seconds)", duration)
```

Javascript sample 1:
Javascript
```
const start = Date.now();
let sum = 0;
for (let i = 0; i < 200000000; i++) {
    sum+=i
}
const duration = Date.now() - start;
console.log("Duration:::", duration)
```
If we measure the execution time of both, we will see that Node.js is approximately 80 times faster than python which is impressive, but this is when things get tricky, on those samples we're only measuring "pure computational performance" without any IO/ or external libraries.  In a real-world trading bot you will have to handle at least a lot of IO to load markets/ fetch prices/ place orders, so let's simulate that.

Python sample 2:
```Python
async def symbol_loop(exchange, symbol):
    await exchange.loadMarkets()
    if symbol in exchange.markets:
        for i in range(0, 20):
            try:
                ticker = await exchange.fetch_ticker(symbol)
            except Exception as e:
                print(str(e))
    await exchange.close()

async def main():
    start_time = time.time()
    symbol = 'BTC/USDT'
    exchanges = ['binance', 'kraken', 'bybit', 'huobi', 'kucoin', 'hollaex', 'coinbase', 'okx', 'phemex', 'zb', 'cryptocom']
    loops = [symbol_loop(getattr(ccxt, exchange_id)({"defaultType":"spot"}), symbol) for exchange_id in exchanges]
    await gather(*loops)
    duration = time.time() - start_time
    print("Duration (seconds)", duration)

run(main())
```
Javascript sample 2:
```Javascript
let test = async function (exchange, symbol) {
    await exchange.loadMarkets ()
    if (symbol in exchange.markets) {
        for (let i = 0; i < 20; i++) {
            try {
                let ticker = await exchange.fetchTicker (symbol)
                tickers.push(ticker)
            } catch (e) {
                console.log(e)
            }
        }
    }
}

const symbol = 'BTC/USDT'
async function main () {
    const start = Date.now();
    let exchanges = ['binance', 'kraken', 'bybit', 'huobi', 'kucoin', 'hollaex', 'coinbase', 'okx', 'phemex', 'zb', 'cryptocom']
    await Promise.all (exchanges.map (async id => {
        let exchange = new (ccxt)[id] ({"defaultType": "spot"})
        await test (exchange, symbol)
    }))
    const duration = Date.now() - start;
    console.log("Duration:::", duration)
}
main ()
```

Surprisingly, by measuring it now we will see that the execution time is almost the same for both scripts, due to the high IO handling happening and less "pure instructions execution". 


Additionally, you have also to take into consideration the usage of external libraries. Let's say you need to handle huge datasets with billions of rows, will be much faster if you use c/c++ libraries in Python such as Pandas/Numpy than pure Javascript structures.

To conclude, as you can see, we can't say go with Python or Javascript because it will depend a lot on what you're going to do and how you're doing it. 

I would probably suggest:
- A lot of IO and not much pure computational logic -> Python and JS will be similar
- A lot of IO and raw computation -> JS will probably have an edge here
- A lot of IO and heavy data handling using external libraries -> Python is very rich in high-performance data libraries, so probably fits better here

Please let us know if this was enlightened for you or not and if you need more clarification on this matter.

**Comment by flav1ooo** [comment]
> @flav1ooo One thing that I forgot to mention is that we also have plans to support statically typed languages in the future that will allow another level of performance compared to JS and Python

GO would be great i guess lots of people suggest this language for speed

**Comment by ttodua** [comment]
@carlosmiei's answer was thorough and I think for now, I'll close the issue.
If any further questions/issues, let us know
