### ISSUE TITLE
how can i get a position with its corresponding orders ?

### ISSUE THREAD

**Issue by 23dontcry** [ccxt/ccxt#14558]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:Ubuntu 
- Programming Language version:PHP

```
how can i get a position with its corresponding orders ?
```

**Comment by carlosmiei** [comment]
Hello @23dontcry, as far as I know, you can't get it all at once, and there is no direct link between orders <-> positions because a position might result from different orders with different sizes, directions, timelines, etc. You can however fetch that information separately by using `fetchOrders` and `fetchPositions`

**Comment by 23dontcry** [comment]
thanks!!

**Comment by carlosmiei** [comment]
@23dontcry Unfortunately, you can't.

Let's say we're talking about the current "long BTC/USDT:USDT" position you have opened. You might have placed 10 BTC/USD:USDT orders that opened/closed a previous "long BTC/USDT:USDT" position and only the last one being responsible for the current position. 

 You can, however, keep track of the orders on your side upon opening positions by storing their ids in mapping/db/cache/file/...

**Comment by 23dontcry** [comment]
oh thanks a lot :)
