### ISSUE TITLE
How to download python3.6-environment-windows.yml file?

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#14573]
In this page, why can't I find the download option for the python3.6-environment-windows.yml file?
https://github.com/scrtlabs/catalyst/blob/master/etc/python3.6-environment-windows.yml
How to download python3.6-environment-windows.yml file?

**Comment by samgermain** [comment]
> In this page, why can't I find the download option for the python3.6-environment-windows.yml file? https://github.com/scrtlabs/catalyst/blob/master/etc/python3.6-environment-windows.yml How to download python3.6-environment-windows.yml file?

The https://github.com/scrtlabs/catalyst repository is deprecated, since 2018, meaning updates and support are no longer provided for it, so I would suggest trying to use something else to do what you want. 

Since this question is not related to CCXT, I would suggest asking it on 
- [Stack Overflow](https://stackoverflow.com/help/how-to-ask)
- some subreddits
    - https://www.reddit.com/r/learnprogramming/
    - https://www.reddit.com/r/learnpython/
- the [python discord server](https://discord.gg/python)
