### ISSUE TITLE
Avoid partial execution of a sell order.

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#14879]
How to avoid partial execution for a sell market order for FTX exchange ? I would like to cancel the order if the order amount is not enough for selling.

**Comment by sc0Vu** [comment]
Hi @YuriyTigiev 

I think you're asking for Fill-or-Kill order (FOK) order, but I didn't see this kind of order in FTX.

**Comment by YuriyTigiev** [comment]
Any idea for workaround ?

**Comment by ttodua** [comment]
> Any idea for a workaround ?

If exchange doesn't support it natively (which is the only guaranteed way) then there is no workaround we might offer. all what I can say is to check orderbook before submitting the order, and if you see your amount is fillable without your price diapason, then you should submit `ioc` (immediate-or-cancel) order. however, it still doesn't guarantee that your full amount will be executed, because in the second before your order reaches the exchange, the orderbook might have changed more than you expect. What I can advise is to reach out to FTX api support and bother them to add the needed functionality. maybe they listen to customers ever (low chances from my experience, but try).
