### ISSUE TITLE
Formula for manually calculation of a parameter "since" for selected a timeframe and candels

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#14942]
Can you share the formula of calculation of a parameter "since" for  selected a timeframe and candels?
For example how to calculate the parameter "since" for  timeframe "3w" and and candels 10?

**Comment by pcriadoperez** [comment]
Hi @YuriyTigiev ,

There is no formula to calculate `since` and it does not depend on `timeframe` or `limit`
`since` is a timestamp to specify the timerange at which to get the candles.
So for example for `fetchOHLCV (BTC/USDT, '1w', 1656637200000, 2)` you will receive two candles. One for timestamp `1657242000000` and one for a week after.

More information can be found here: https://docs.ccxt.com/en/latest/manual.html#ohlcv-candlestick-charts

I'll close this issue for now but feel free to reach out on discord or here if you have any other questions.
