### ISSUE TITLE
help installing and maybe partnership 

### ISSUE THREAD

**Issue by silverbuyer** [ccxt/ccxt#1507]
can you help install to load test
you got my attention...i have seen so much junk out there

is this yet another? can it be used in production?

do you have a demo hosted somewhere?

any whatsapp number or direct number in north america?

**Comment by silverbuyer** [comment]
i am looking to start my own exchange
can you help with client accounts..fiat and crypto deposits and matching algo..order book etc..there is open source called txbits and connectors on github..take a look

**Comment by giorgionetg** [comment]
I think you get wrong library... 

> It is intended to be used by coders, developers, technically-skilled traders, data-scientists and financial analysts for building trading algorithms on top of it.

I suppose it's not the best way to make an exchange... The goals are different... You need to create an e-commerce and market on your fiat/crypto combo...

**Comment by silverbuyer** [comment]
can you dev new software?

**Comment by kroitor** [comment]
> can you help install to load test

Sorry, but this is not an executable program for end-users. Our product is a programming toolkit for developers who want to create their own software. Setting it up for development requires programming skills (this is documented on the front page of this library). It won't make money for you out of the box. Instead you have to program it for making money, depending on your strategies.

In other words, you cannot play with a LEGO kit right away, but you can play with a toy built from a LEGO kit. This library is a LEGO construction kit for building toys, but we are not a toy in itself.

> is this yet another?

Hopefully, not. We are a group of developers, not a software company.

> can it be used in production?

Yes, if you can write code, you can use it in production as well.

> do you have a demo hosted somewhere?

No, but we have more than 100+ products based on our library, here: https://github.com/ccxt/ccxt/network/dependents

We are also integrated into other cool development environments, like the GDAX Trading Toolkit and The Enigma Catalyst, here: https://github.com/ccxt/ccxt/tree/master/examples

> any whatsapp number or direct number in north america?

Whatsapp number – yes.
North American number – no, but we can arrange one.

We have all means of contact, but we don't really need anything of that (not necessary for what we and our users do). We do not offer voice support.

> i am looking to start my own exchange
> can you help with client accounts..fiat and crypto deposits and matching algo..order book etc..there is open source called txbits and connectors on github..take a look

Starting your own exchange means funding. In order to hook up other traders, you will have to burn volumes, like other exchanges do. Software development aspects and connectors are not primary objectives at all and are usually much less significant than funding aspects.

> can you dev new software?

We did develop software for other clients earlier, but we are not offering our services at the moment. We are currently occupied with our own projects including support and development of this library.

Let us know if it doesn't answer your questions.

**Comment by kroitor** [comment]
Let us know if we can help with anything here. Closing this for now.
