### ISSUE TITLE
Binance WebSocket watchOrderBook reporting out-of-order nonce errors sporadically

### ISSUE THREAD

**Issue by ryanmccoy** [ccxt/ccxt#15130]
- OS: Ubuntu 20.04
- Programming Language version: Python 3.7.12
- CCXT version: ccxt-1.93.108, ccxtpro-1.2.35

Full disclosure: I am aware that the issue here is very possibly in userland, and possibly has to do with the greater parts of our application perhaps blocking / interrupting the websocket's ability to handle messages. I can't provide the full application's architecture, but hopefully there is enough below to illustrate where the issue is happening and possibly get some help on what might be going wrong.

DESCRIPTION: As of a few months ago our websocket watchOrderBook streamer started throwing a ton of out-of-order nonce errors (stack trace provided at the bottom). Nothing changed for the streamer's model prior to the error starting to be thrown. There are also functioning streamers for FTX, ByBit, and BitMex that function without issue, even when Binance starts throwing these errors. The current workaround is to not run our binance streamers in websocket mode, and just fetch the OB on-demand via REST. Any insight into why this might be happening for binance only would be greatly appreciated, as my understanding on python's concurrency (async specifically) is a bit limited.

```
import asyncio
from threading import Thread
import time
import ccxt
import ccxtpro
from collections import deque

class Stream:
    def __init__(self, acct):
        for k,v in acct.items(): setattr(self, k, v)
        self.exch_pro = getattr(ccxtpro, self.name)({
                'enableRateLimit': True,
                'options': {'defaultType': self.market},
            })
        self.prices_websocket = deque(maxlen=100)

    @asyncio.coroutine
    async def watchOrderBook_loop(self, loop):
        self.exch_pro.asyncio_loop = loop
        while True:
            try:
                response     = await getattr(self.exch_pro, 'watchOrderBook')(self.symbol)
                bid          = response['bids'][0][0] if len (response['bids']) > 0 else None
                ask          = response['asks'][0][0] if len (response['asks']) > 0 else None
                price_market = None

                if bid is not None and ask is not None:
                    price_market = float((bid + ask) / 2.0)

                timestamp = response['timestamp'] if response['timestamp']!=None else self.exch_pro.milliseconds()
                element = [bid, ask, price_market, timestamp]

                self.prices_websocket.append(element)
                print(f"{self.symbol}: {element}")
            except ccxt.NetworkError as e:
                print(f"{self.name} websocket network error: {e}")
                time.sleep(0.5)
            except ccxt.ExchangeError as e:
                print(f"{self.name} websocket exchange error: {e}")
                time.sleep(0.5)
            except Exception as e:
                print(f"{self.name} websocket stopped for unknown reasons: {e}")
                time.sleep(0.5)

class Command:
    def _init_datafeeds(self, feed_accounts):
            asyncio_loop = self._get_or_create_eventloop()
            loops = []
            for acct in feed_accounts:
                s = Stream(acct)
                loops.append(s.watchOrderBook_loop(asyncio_loop))
            t = Thread(target=self.start_websocket, args=(asyncio_loop,loops,))
            t.start()
            t.join()

    def _get_or_create_eventloop(self):
        try:
            return asyncio.get_event_loop()
        except RuntimeError as e:
            if "There is no current event loop in thread" in str(e):
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
                return asyncio.get_event_loop()

    def start_websocket(self, asyncio_loop, loops):
        asyncio.set_event_loop(asyncio_loop)
        asyncio_loop.run_until_complete(asyncio.gather(*loops))
        asyncio_loop.close()

if __name__ == "__main__":
    commander =  Command()
    feed_accounts = [
        {
            'name': 'binance',
            'market': 'delivery',
            'symbol': 'BTC/USD'
        },
        {
            'name': 'binance',
            'market': 'delivery',
            'symbol': 'ETH/USD'
        },
        {
            'name': 'binance',
            'market': 'future',
            'symbol': 'LINK/USDT'
        },
        {
            'name': 'binance',
            'market': 'future',
            'symbol': 'BTC/USDT'
        },
        {
            'name': 'binance',
            'market': 'future',
            'symbol': 'ETH/USDT'
        }
    ]
    commander._init_datafeeds(feed_accounts)
```

```
2022-09-28T08:47:12.260 DEBUG: binance handleOrderBook received an out-of-order nonce
Traceback (most recent call last):
  File "/home/ubuntu/triggerman/triggerman/streamer.py", line 128, in watchOrderBook_loop
    response = await getattr(self.exch_pro, 'watchOrderBook')(self.symbol)
  File "/home/ubuntu/triggerman/tman-venv/lib/python3.7/site-packages/ccxtpro/binance.py", line 151, in watch_order_book
    orderbook = await self.watch(url, messageHash, message, messageHash, subscription)
  File "/home/ubuntu/triggerman/triggerman/streamer.py", line 128, in watchOrderBook_loop
    response = await getattr(self.exch_pro, 'watchOrderBook')(self.symbol)
  File "/home/ubuntu/triggerman/tman-venv/lib/python3.7/site-packages/ccxtpro/binance.py", line 151, in watch_order_book
    orderbook = await self.watch(url, messageHash, message, messageHash, subscription)
  File "/home/ubuntu/triggerman/tman-venv/lib/python3.7/site-packages/ccxtpro/binance.py", line 288, in handle_order_book
    raise ExchangeError(self.id + ' handleOrderBook received an out-of-order nonce')
ccxt.base.errors.ExchangeError: binance handleOrderBook received an out-of-order nonce
```

**Comment by ryanmccoy** [comment]
Hi @pcriadoperez Unfortunately I also don't have a conistent way of reproducing this issue. There were times it ran for days without the error ever manifesting. There was a time when it would manifest in our UAT environment after a few hours or days, but went weeks never occurring in our Production environment. Then there are times it happens the moment we initialize our streamers into the greater application. 

I have started it in our UAT environment with verbose on, hopefully it does not take forever this time to manifest itself - will report here the moment I see it (with the verbose output around the error)

**Comment by pcriadoperez** [comment]
Sounds good, I'll keep this open till then.

In any case, if the error happens because a message is skipped due to network issues for example. On the the next call to `binance.watchOrderBook` the code should reconnect, and grab a new snapshot. So your downtime would be only the amount of time it would take to disconnect, reconnect and fetch the latest snapshot.

**Comment by ryanmccoy** [comment]
@pcriadoperez When it does happen, it does not recover from the issue unfortunately. It requires a full restart of the streamer at the point. And the error seems to build up strangely. Meaning the error rapidly starts to stack the longer it goes. I will be able to better illustrate this when it repeats itself (hopefully soon)

**Comment by ryanmccoy** [comment]
@pcriadoperez I was able to effectively reproduce the issue by adding the time.sleep(0.5) at the end of every loop - I am assuming because this is a blocking sleep inside of an async loop (that is shared by multiple streamers inside the same thread). I have removed the sleep entirely since at best it seems like it is functionally pointless (since ccxt handles rate limiting behind the scenes) and at worst may be disruptive. Thoughts?

**Comment by krychla1** [comment]
Hi fellows! I have this same problem.
Recently I upgraded to newest version of ccxt as a result of the pro merge. Since then I face the out-of-order issue for binance very often. Looking at the logs I experienced the error very rarely before (once in a few months running on 200-300 subscriptions). Now I receive it every time I create subscriptions for about 3% of subscriptions. Some of the pairs (its random) takes multiple retries (5-10) to subscribe successfully.

Ccxt version before upgrade:
+-- ccxt.pro@1.2.6
| `-- ccxt@1.91.57

Ccxt ver after upgrade:
1.95.12

**Comment by pcriadoperez** [comment]
@ryanmccoy, glad to hear removing the sleep helped!

@krychla1, I compared the two versions and there shouldn't be any changes on the binance file. Can you provide a verbose output to take a further look or a way you have been able to reproduce?

**Comment by krychla1** [comment]
@pcriadoperez I will take a look next week more deeply.

**Comment by kroitor** [comment]
From my understanding, since adding time.sleep helps reproduce this issue, then it boils down to blocking in an async context, indeed. My advice is to make sure you exclude blocking calls from within async-calls or replace your blocking I/O with non-blocking I/O.

Among the most common points of blocking could be:

- writing to a disk/file in sync-blocking mode (logs, dumps, etc)
- using the sync API for your DB operations (most DBMs also provide a non-blocking async API nowadays)
- time-consuming calculations that could “eat” your async loops

Please, make sure you exclude the above three possible reasons. To debug this issue and to track it down, I’d recommend stripping out parts of business logic, leaving just the async WS calls and reactions, and then adding various parts of your system (logs, db, calculations) one by one until it starts to manifest itself again. That should theoretically help narrow down the search for the cause of trouble at the very least.

Just my 2 cents. We will try to post more non-blocking examples for the use/cases mentioned above, and will keep investigating of course.
