### ISSUE TITLE
gateio fetch_orders() is not implemented yet

### ISSUE THREAD

**Issue by Turtlesfr** [ccxt/ccxt#1531]
- OS: Ubuntu
- Programming Language version: Python 3.5
- CCXT version: current
- Exchange: gateio
- Method: ?

I'm getting "gateio fetch_orders() is not implemented yet" while trying to retrieve my orders (passed or current).
This works on Poloniex and Binance.
Any workaround ?

Thank you

**Comment by kroitor** [comment]
@Turtlesfr until it is implemented as a unified fetchOrders method you can call any of the exchanges' endpoints by using exchange-specific implicit methods, described here:
https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
The ccxt library supports all of them out of the box, it's just that not all of them are unified yet (that's the hardest part, because of their multiple differences).

Let us know if it doesn't answer your question. Thx!

**Comment by kroitor** [comment]
P.S. your contributions are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
