### ISSUE TITLE
Why some exchanges asks for USDT while others asks for number of token in buy methods?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15577]
Hey guys. I have a question.
When I try to buy any coin on Huobi or Bybit, in command `exchange.create_market_buy_order(coin, amount)` amount parametr is USDT. Other words, these exchanges asks for number of USDTs I'm gonna pay for any token.

But others exchanges like MEXC. Binance, Kucoin and etc in the same command `exchange.create_market_buy_order(coin, amount)` in amount parametr asks not for number of USDTs I'm gonna spend, but the number of coin I'm gonna buy. 

Why exchanges asks for different things? And can I buy coins by the first method (sending number of USDTs, but not coin)? I don't want to spend time on getting my balance, coin last_price and calculation.

**Comment by pcriadoperez** [comment]
Hi @KindSpidey,

So we try to always unify `createOrder` so the amount is always in the base currency whenever it is possible. However this changes sometimes for certain exchanges and also different symbols. (For example futures can be the number of contracts).

In the case of bybit order quantity (for market orders: when side is Buy, this is in the quote currency. Otherwise, qty is in the base currency. For example, on BTCUSDT a Buy order is in USDT, otherwise it's in BTC. For limit orders, the qty is always in the base currency.)
Reference:  (https://bybit-exchange.github.io/docs/spot/v3/#t-placeactive)

For now I'll close this issue but feel free to post any more questions or open another issue
