### ISSUE TITLE
Best Source For Perpetual Futures Funding Rate Post FTX Blow Up

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#15734]
This is more of a question than an issue but I feel that this community is best qualified to help me address what is a crucial issue for my business.

My entire infrastructure related to a trading system I developed my clients was dependent on futures funding rate (FFR) data from FTX. All my backtests, tools, scanners, and live systems were dependent on that. The FTX blow up has created a gaping hole in our infrastructure that I aim to fill.

Q: What is the best source for pulling hourly FFR data at the current time? When looking at coinglass (https://www.coinglass.com/FundingRate) I see that many of them are quoted as 8-hour rates, but that relates to the payout not the actual quotes as they constantly seem to change. Either way what exchange is currently offering the most up to date and reliable FFR data?

Thanks in advance for any pointers.

**Comment by Dan-krm** [comment]
If you'd like to ask the broader community a question I think a better place would be in the CCXT general discord channel because more people will likely see it.

I'd recommend using Binance through CCXT since they have the most volume and all of the funding rate methods defined. Some other decent options would be Bitget, Bybit and Okx
