### ISSUE TITLE
CCXT x Hotbit

### ISSUE THREAD

**Issue by ProStrike-hub** [ccxt/ccxt#15739]
Hello, 

I'd like to know if Hotbit is in the process, or planned, of being integrated into CCXT ?

Thanks.

**Comment by samgermain** [comment]
> Hello,
> 
> I'd like to know if Hotbit is in the process, or planned, of being integrated into CCXT ?
> 
> Thanks.

[It doesn't look like hotbit has an api](https://www.hotbit.io/support?page=api), so no

**Comment by samgermain** [comment]
> Hello,
> 
> I'd like to know if Hotbit is in the process, or planned, of being integrated into CCXT ?
> 
> Thanks.

It looks like someone [created a PR](https://github.com/ccxt/ccxt/pull/4135) at one time, but it was closed because the hotbit website doesn't link to the api docs, it looks like their docs are on Github though

That PR would need to be updated, but even after that there are a lot of completed **new exchange** PRs that are unmerged, so it might not be merged for a while unless hotbit opted to become a certified exchange or something

**Comment by samgermain** [comment]
> Hello,
> 
> I'd like to know if Hotbit is in the process, or planned, of being integrated into CCXT ?
> 
> Thanks.

It looks like you can't get api keys to use the api documented on github, so hotbit has no api then
