### ISSUE TITLE
unify proxies

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#15902]
we should unify and document how to use ccxt with proxies

**Comment by goznauk** [comment]
I'm not sure this is the best practice, but I tested this for `huobi` and this works.

```typescript
const agent: SocksProxyAgent = new SocksProxyAgent(runningArgs.socksProxyUrl);
```
```javascript
{
    fetchImplementation: nFetch,
    agent: agent,
    httpAgent: agent,
    httpsAgent: agent,
    options: { ws: { options: { agent: agent } } },
}
```

Due to [undici](https://undici.nodejs.org/) `fetch` implementation does not worked with  `SocksProxyAgent`, I should have use another `fetchImplementation`. I'm not sure but `agent` might be - must be tested again - redundant. However the websocket needed `agent` for `ccxt.pro` functions.

Because I've written this relying on memory, please feel free to point out wrong things.

Thanks!

**Comment by frosty00** [comment]
> I'm not sure this is the best practice, but I tested this for `huobi` and this works.
> 
> ```ts
> const agent: SocksProxyAgent = new SocksProxyAgent(runningArgs.socksProxyUrl);
> ```
> 
> ```js
> {
>     fetchImplementation: nFetch,
>     agent: agent,
>     httpAgent: agent,
>     httpsAgent: agent,
>     options: { ws: { options: { agent: agent } } },
> }
> ```
> 
> Due to [undici](https://undici.nodejs.org/) `fetch` implementation does not worked with `SocksProxyAgent`, I should have use another `fetchImplementation`. I'm not sure but `agent` might be - must be tested again - redundant. However the websocket needed `agent` for `ccxt.pro` functions.
> 
> Because I've written this relying on memory, please feel free to point out wrong things.
> 
> Thanks!

We've made node-fetch the default fetchImplementation in the latest ccxt. I'm more talking about having a unified way to declare a proxy across langs - js, py and php. Maybe something like:

```
exchange ({
    'httpProxy': 'ip:port',
    'httpsProxy': 'ip:port',
    'socksProxy': 'ip:port',
})
```
