### ISSUE TITLE
Does exchanges expose USDT over API when buying?

### ISSUE THREAD

**Issue by hippylover** [ccxt/ccxt#1598]
Hi i'm trying to buy USDT over API on bittrex and binance but i can't find it in .symbols -- that is, USDT/BTC, USDT/ETH etc -- BTC/USDT exists and ETH/USDT exists however. Is this an exchange limitation or bug?

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

**Comment by hippylover** [comment]
Hmm, ok i read that and i don't think it answers the question. My point is if im buying USDT(on the BTC market) the correct ticker should read USDT/BTC, yes?

**Comment by kroitor** [comment]
> Hmm, ok i read that and i don't think it answers the question. My point is if im buying USDT(on the BTC market) the correct ticker should read USDT/BTC, yes?

Nope ) The correct ticker should be `BTC/USDT`. Because you cannot buy USDT on BTC markets with Binance and Bittrex as they only have BTC-for-USDT markets. Thus the **base** currency is BTC (before the slash) and the **quote** is USDT (after the slash) and the correct symbol is `BTC/USDT`.

```
// you can't
buy USDT for BTC
// you can
sell BTC for USDT
```

↑ These are equivalent.

Does this make sense now?

**Comment by hippylover** [comment]
This is not correct. I just tested for bittrex now and you can buy and sell USDT.

**Comment by hippylover** [comment]
And im not american. European.

**Comment by kroitor** [comment]
> I just tested for bittrex now and you can buy and sell USDT.

You are confused with their market naming, their markets are named USDT-BTC, and you think that because USDT is the leftmost, you kinda sell and buy USDT, but this is not the case and this is a very common pitfall. You are in fact trading BTC for USDT there, please don't confuse it.

The easiest way to prove it is to look at the price.

```
>>> import ccxt
>>> ccxt.bittrex().fetch_ticker('BTC/USDT')['last']
10911.20000001
>>> ```

↑ Obviously the price is BTC/USDT, not USDT/BTC. So you're buying and selling BTC for your USDT, and not vice versa. You just need to pay attention to all details, literally, every symbol, as this is documented in the Manual.

**Comment by hippylover** [comment]
Ok. This is some confusing shit. I think i get your argument now, technically you are correct.

Eg you say: "you can't buy USDT for BTC" and this is not true from a *practical* sense, eg: i can click on the sell button on bittrex and then i will effectively be buying USDT for BTC just as much as i am selling BTC for USDT. However from a *technical* perspective i'm clicking the sell button. Hmm.

**Comment by kroitor** [comment]
I would add, that when you click sell, your are actually selling BTC for USDT. That is correct from both *technical* and *financial* perspective. Their buttons literally tell you the same:

<img width="1122" alt="screen shot 2018-01-30 at 15 18 51" src="https://user-images.githubusercontent.com/1294454/35566063-14a89862-05d1-11e8-8b66-c5321d57d295.png">

Buy bitcoin, sell bitcoin. For tether dollars. Not vice versa.
