### ISSUE TITLE
EXMO requests load_markets() and fetchTickers() responds symbols that are not on the spot

### ISSUE THREAD

**Issue by petrkl** [ccxt/ccxt#16046]
Hi!

EXMO responds to requests load_markets() and fetchTickers() symbols that are not on the spot.
Moreover, these symbols are marked as active (when requested load_markets()).

For example: PLCU/BTC

How filter on EXMO only symbols that are only on the spot?

Thanks in advance!

**Comment by samgermain** [comment]
Unfortunately there's not a lot that we can do about this, the endpoint on exmo's API returns these markets with no indicator of whether the market is active or not, even though an error is thrown when you try to create an order on these markets. 

I've [updated the active key within `load_markets` to be undefined instead of true](https://github.com/ccxt/ccxt/pull/16065). Other than this, you'll need to do some error handling for markets that are not active.
