### ISSUE TITLE
Asyncio workflow

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#16040]
- Programming Language version: Python 3.10.5
- CCXT version: 2.2.91

If I understand the asyncio functionality correctly , the workflow for this code is as following:
```
import asyncio
import ccxt.pro


async def loop(exchange, symbol):
    while True:
        orderbook = await exchange.fetch_order_book(symbol)
        # code without call exchange method
        if condition:
            await exchange.create_order(symbol, ...)


async def main():
    exchange = ccxt.pro.binance()
    symbols = ['symbol1', 'symbol2', 'symbolN']
    await asyncio.gather(*[loop(exchange, symbol) for symbol in symbols])


asyncio.run(main())
```
1. All loop functions execute code until 'fetch_order_book' call.
2. Execute 'fetch_order_book' and execute code until 'fetch_order_book' if condition not True else until 'create_order'
3. From symbol1 to symbolN in the order, execute 'fetch_order_book' or 'create_order'

Is it right? 
So my question is how can I execute the 'create_order' function immediately after 'fetch_order_book' if condition is True.

The purpose of my question is in case of you have lot of symbol in symbols list. If only the last symbol has condition True, you need to wait all symbol to fetch him orderbook before post your order. I would like to minimize the time between the execution of 'fetch_order_book_ and the execution of the trade.

Thanks you very much for your help.

**Comment by pcriadoperez** [comment]
Hi @Hadevmin ,

Not exactly. So asyncio will run all the loop functions in parallel and independently.
Each loop function will first wait for `fetch_order_book`, check the condition and if true immediately call create_order. And continuously do so.

So this code should meet your needs of executing the 'create_order' function immediately after 'fetch_order_book' if condition is True.

Also for this case I'd recommend using `watch_order_book` which will provide order book updates, instead of having to fetch the full order book.

Please let me know if you have any further questions, if not feel free to close the issue

**Comment by Hadevmin** [comment]
Hi @pcriadoperez,

I probably made some mistakes in my tests because I was not observing this scenario....
Thanks for your help! And for the method, it is the case! ;)
I use this condition before calling the order book or the account balance.
```
if exchange.has['watchOrderBook']:
   exchange.watch_order_book
   ...
elif exchange.has['fetchOrderBook']:
   exchange.fetch_order_book
   ...
```
