### ISSUE TITLE
bibox stopped withdrawals

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#16041]
Hello.
I think it is better to delete bibox exchange for preventing user from loosing money. 
They do not process withdrawals. First they didnt' withdraw 38k USDT since 
20 Nov. After that they decreased withdrawal limit to 0.01 BTC and even with this limit they do not process withdrawals with such a small amounts.
I am KYC verified, account was not blocked or violate anything.
I would suggess to remove it from ccxt.

<img width="1792" alt="Screenshot 2022-12-10 at 14 09 32" src="https://user-images.githubusercontent.com/34489099/206857068-94d0be40-ce31-464a-a9d5-b058eabf3754.png">

**Comment by samgermain** [comment]
> First they didnt' withdraw 38k USDT since

Could you elaborate on that a bit more and explain what happened exactly?

**Comment by alexsith** [comment]
> > First they didnt' withdraw 38k USDT since
> 
> Could you elaborate on that a bit more and explain what happened exactly?

Explain how? They silently did not withdraw big amount of USDT. I violate nothing, account is not frozen or something. KYC-verified. Support keep telling 'Technicians working on situation'. Withdrawal limit decreased to 0.01BTC per day - which makes exchange useless.

**Comment by samgermain** [comment]
> 

Give some details, I'm assuming you mean that you tried to withdraw 38K of USDT, and now the withdrawal is pending? Or was it cancelled, or the money was lost?

**Comment by frosty00** [comment]
@alexsith i'm also verified and cannot withdraw, we will likely delist within a few days

**Comment by ndubel** [comment]
same problems with bibox

**Comment by JovianMoon** [comment]
After I saw this issue here I tried to withdraw 0.01 BTC on 11th (I haven't completed KYC). The withdrawal did get stuck to "Withdrawing" limbo for two days, but got completed on 13th, some hours ago. So you might still be able to save some of your funds by BTC withdrawals. Not very useful if you have a lot of funds but still something. I will try to do a couple of more withdrawals to see if they will go a permanents limbo.

If you can't withdraw more than that with KYC it makes the exchange sound pretty suspicious...

**Comment by ttodua** [comment]
Guys, did anyone had any update? was the problem eventually fixed or it stayed as it was (or even worse)?

**Comment by JovianMoon** [comment]
@ttodua Just few days ago received ETH that I withdrew from Bibox in the middle of December. I have successfully withdrawn 0.01 BTC about 10 times since the problems started. The latest BTC withdrawal has been in "Withdrawing" state about 10 days. From my (no KYC done) point of view Bibox withdrawal problems have maybe gotten slightly worse since December as it seems to take longer and longer for withdrawals to complete.

**Comment by ttodua** [comment]
@JovianMoon thanks for insights! so, it means everything is clear. the problem (if such exists on exchange) should have been solved within those days (week) whenever started, but as it wasn't solved so long time, it says much.
