### ISSUE TITLE
The fetchOpenInterest method does not seem to exist

### ISSUE THREAD

**Issue by Mehdi-Verfaillie** [ccxt/ccxt#16142]
Good morning,

While looking at the documentation I was interested in the function: `fetchOpenInterest` - https://docs.ccxt.com/en/latest/manual.html#open-interest
But it seems that it has not been implemented. It is also not mentioned in the `'has':` object. 
Only `fetchOpenInterestHistory` seems to be available.

- Programming Language: **JS**
- CCXT version: **2.4.33**

Any information about this ?

Special thank for contributors.

**Comment by carlosmiei** [comment]
Hello @Mehdi-Verfaillie,

Currently, `fetchOpenInterest` is implemented only for a few exchanges (bitget, bybit, huobi, okx).

If you happen to know some exchange that does not have it but provides an endpoint with that information please let us know and we will update it as soon as possible.

**Comment by Mehdi-Verfaillie** [comment]
Should we add `'fetchOpenInterest': false` in the meta-info interface for exchanges that do not provide the endpoint ? @carlosmiei

**Comment by samgermain** [comment]
> Should we add `'fetchOpenInterest': false` in the meta-info interface for exchanges that do not provide the endpoint ? @carlosmiei

sorry about this, I've added `fetchOpenInterest` and `fetchOpenInterestHistory` to has of Exchange in #16146

**Comment by Mehdi-Verfaillie** [comment]
Let's take the opportunity to make it available for Binance. The endpoint seems to be available on v1.
https://binance-docs.github.io/apidocs/futures/en/#open-interest

**Comment by samgermain** [comment]
> Let's take the opportunity to make it available for Binance. The endpoint seems to be available on v1. https://binance-docs.github.io/apidocs/futures/en/#open-interest

If you would like to submit a PR, I'll happily review it, you'll need to create a fork

![](https://i.imgur.com/MraW6JM.png)

then you can copy the method from the method from another exchange

![](https://i.imgur.com/l32WHvA.png)

and change some of it some that the method works with the binance api endpoint, you'll for sure need to change the 

- request arguments
- api path
- api response

![](https://i.imgur.com/poDYLqU.png)

and then you'll need to adjust the `parseOpenInterest` method so that the correct values are obtained from the binance response

![](https://i.imgur.com/qlTnX1H.png)

you only need to write the JavaScript method, the python and php methods will be transpiled from the JavaScript
