### ISSUE TITLE
The fetchBalance method with params is missing documentation exemple.

### ISSUE THREAD

**Issue by Mehdi-Verfaillie** [ccxt/ccxt#16350]
Programming Language: JS
CCXT version: 2.4.33

Hello everyone,

Do we have more information on how the `fetchBalance` method works?
I read the [documentation](https://docs.ccxt.com/en/latest/manual.html?#account-balance) saying `Extra parameters specific to the exchange API endpoint` but it's not 100% clear to me.

Let's take an exemple from[ huobi documentation](https://huobiapi.github.io/docs/spot/v1/en/#get-account-balance-of-a-sub-user). They say: `'sub-uid': The specified sub user id to get balance for.`
```
'private': {
    'get': {
        'account/accounts/{sub-uid}': 1
    }
}
```
So far, the only thing I can do is suppose that I have to write it this way but it have no effect.
```
await exchange.fetchBalance({ 'sub-uid': '1234' }))
```

Maybe someone can provide a working exemple ? It would be great.

Thank you

**Comment by pcriadoperez** [comment]
Hi @Mehdi-Verfaillie , You are using params correctly, however the issue is that in huobi `fetchBalance` uses the following endpoints, depending on the market type, subtype and margin:
- `spotPrivateGetV1MarginAccountsBalance`
- `spotPrivateGetV1CrossMarginAccountsBalance`
- `spotPrivateGetV1AccountAccountsAccountIdBalance`
- `spotPrivateGetV1MarginAccountsBalance`
- `spotPrivateGetV1CrossMarginAccountsBalance`
- `contractPrivatePostLinearSwapApiV1SwapAccountInfo`
- `contractPrivatePostLinearSwapApiV1SwapCrossAccountInfo`
- `contractPrivatePostApiV1ContractAccountInfo`
- `contractPrivatePostSwapApiV1SwapAccountInfo`

If you want to use the endpoint  you mentioned you can use the ccxt implicit api and call `huobi.privateGetAccountAccountsSubUid({sub-uid:'1234'})`

However if you are just looking to use fetch Balance. I would just call `huobi.fetchBalance()` and make sure you set the defaultType to the market type you want to use.

**Comment by Mehdi-Verfaillie** [comment]
Thanks for help @pcriadoperez !
