### ISSUE TITLE
invalid symbols in huobi pro

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#1666]
The symbols: 'bt1btc' and 'bt2btc'

are both listed under markets by Huobi Pro, but arent supported in any other of their api requests.
https://api.huobi.pro/market/detail/merged?symbol=bt1btc
Im sure this is an error on their side, but it would perhaps be better if those 2 symbols are filtered out by ccxt until they either remove those symbols or fix their api.

**Comment by kroitor** [comment]
https://medium.com/huobi-global/regarding-bitcoin-segwit2x-hard-fork-huobi-pros-position-bad5937de1aa

Unfortunately, we can't turn them off and we can't be selective on what should be excluded or not, we give you everything from the exchange, as their API endpoints report, and you (the user) decide what to do with it. The reasoning is this: because they haven't switched those two fork-symbols off yet and because they still serve them from their API, some users may still hold those tokens on their account balances, or have trades in history that should be associated with that symbol.

The proper way to fix it would be to ask them to add some indication whether a market symbol is still active or not. However, they don't even serve a list of markets from their API and we have to scrape it from their web interface...

Let us know if this does not answer your question.

**Comment by asagynbaev** [comment]
I have the same problem with "venusdt" marker. Does anybody knows, how to fix it?

**Comment by kroitor** [comment]
@asagynbaev see the answer here: https://github.com/ccxt/ccxt/issues/3472#issuecomment-407350142 (`VEN` is rebranded to `VET`)

**Comment by asagynbaev** [comment]
> @asagynbaev see the answer here: [#3472 (comment)](https://github.com/ccxt/ccxt/issues/3472#issuecomment-407350142) (`VEN` is rebranded to `VET`) and the manual on symbols vs market ids here: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

Thanks a lot!))

**Comment by JNYH** [comment]
The symbol 'lunausdt' is not working also 
I tried to place buy-limit and sell-limit orders via API for 'lunausdt', and got the following response:
{'status': 'error',
 'err-code': 'base-symbol-error',
 'err-msg': 'The symbol is invalid',
 'data': None}
(The same code works for 'xrphusd')

**Comment by kroitor** [comment]
@JNYH please, paste your versions, your code and your request+response in verbose mode: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
