### ISSUE TITLE
[binance][pro] in watchOrderBook resulted book grows linear

### ISSUE THREAD

**Issue by aleksraiden** [ccxt/ccxt#16718]
### Operating System

Debian

### Programming Languages

JS

### CCXT Version

2.7.31

### Description

I have subscriptions to orderbook from binance futures. As I understand, in each iteration (updates) in resulted book we have store at limit (or default) price level. But if I check book Ask or Bid, an array length only grows. 

### Code

```
let binance  = new ccxt.pro.binanceusdm({ verbose: false, enableRateLimit: true, newUpdates: true});

await binance.watchOrderBook('BTC/USDT:USDT', 10); //I want only top-10 of bid/ask

setInterval( async function(){
		
	let book = binance.orderbooks['BTC/USDT:USDT'];
					
	console.log( 'bids: ' + book.bids.length + ', asks: ' + book.asks.length ); 
	//And in console we have output: 
	//bids: 110, asks: 108
	//bids: 122, asks: 117
	//bids: 133, asks: 125
	//bids: 144, asks: 132
	//bids: 149, asks: 139
	//bids: 169, asks: 164
				
}, 250 );
```
Is this correct?

**Comment by pcriadoperez** [comment]
Hi @aleksraiden, many times ccxt caches all the bids and asks, and then only displays the limit in the returned orderbook. In this case you are accessing the cache bids and asks and that's why you see the number growing. We usually recommend using the orderbook returned by `watchOrderBook`, that shows the bids/asks with it's limit.

If you want the last ten I'd recommend either looking at the orderbook returned by `watchOrderBook` or checking the last 10 bids/asks in the cache.

### Using returned orderbook (recommended)
```
while (true) {
   const orderbook = await binance.watchOrderBook('BTC/USDT:USDT', 10);
   console.log (orderbook.bids);
   console.log (orderbook.asks);
}
```
### Using stored orderbook
`binanceusdm.orderbooks['BTC/USDT:USDT'].bids.slice (0,10)`

I'll close this issue for now but feel free to reach out with any more questions
