### ISSUE TITLE
CCXT supports new Bybit API v5 accounts as of version 2.8.61

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#17013]
Hello, dear CCXT users!

We would like to announce that the Bybit v5 integration has been merged in CCXT as of version 2.8.61.

Users with all types of accounts including unified v5 accounts, unified margin accounts, and regular accounts can use Bybit from CCXT out of the box as CCXT can now detect the types of Bybit accounts automatically, so, it should just work. 

As always, feel free to report any difficulties and/or issues you might find after the upgrade.

Thank you for using CCXT!

Yours, the CCXT Dev Team

**Comment by furryboffin** [comment]
Do we still need to set "enableUnifiedMargin" to "true" ?

**Comment by carlosmiei** [comment]
> Do we still need to set "enableUnifiedMargin" to "true" ?

@furryboffin By default CCXT will make one request to figure out your account type.

**Comment by furryboffin** [comment]
I've noticed that not all markets listed in bybit.markets are available as tickers for the websocket. Is this expected?

**Comment by carlosmiei** [comment]
> I've noticed that not all markets listed in bybit.markets are available as tickers for the websocket. Is this expected?

@furryboffin Which ones are not available? (we didn't update the WS yet so yes we might have some discrepancies)

**Comment by furryboffin** [comment]
There are a lot... to many to list here easily/quickly. Also, I just tried to place my first trade using this new version and a unified account. I want to trade on BTCUSDT perp... how do I inform CCXT to place the order on futures market and not on spot? It's try to place it on spot with the amount specified in BTC... and fails because the amount is blow the minimum, which I imagine is minimum USDT value. E.G. I used to place futures USDT trades using the base currency amount, in this case BTC. So I want to go long 0.01BTC, I set the amount to 0.01 and it tries to place that on spot and fails due to min amount requirement.

**Comment by furryboffin** [comment]
I tried the following:
```
 bybit = new ccxt.bybit({defaultType: 'future', defaultSubType: 'linear', enableRateLimit:true})
 ```
 to no avail.

**Comment by furryboffin** [comment]
After a little more digging, I see that the list of markets that I'm getting is always that of spot. Not one market is future or swap.

**Comment by furryboffin** [comment]
After even more digging I discovered that you can get a full list of markets by calling fetchMarkets() then filter out those that are linear swap. and now I'm able to subscribe to all markets. I still have not yet figured out how to place a trade on linear swap instead of spot yet though.

**Comment by furryboffin** [comment]
I think I figured it out. Correct me if I'm wrong, but it seems to just depend on the symbol that is used. So, one can trade on spot or swap(linear/inverse) all with the same ccxt object, just passing the correct ticker i.e. "BTC/USDT:USDT" for linear swap, "BTC/USDT" would be spot and "BTC/USD" would be inverse swap.

**Comment by kroitor** [comment]
> I think I figured it out. Correct me if I'm wrong, but it seems to just depend on the symbol that is used. So, one can trade on spot or swap(linear/inverse) all with the same ccxt object, just passing the correct ticker i.e. "BTC/USDT:USDT" for linear swap, "BTC/USDT" would be spot and "BTC/USD" would be inverse swap.

Yes, you're almost entirely correct, except that the inverse swap would be "BTC/USD:BTC", please, check these contract naming conventions:

- https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions

**Comment by wunderb1t** [comment]
Hi,
Is there any possible way to load only `linear swap` markets via `loadMarkets` method?
Because right now `loadMarkets` method loads all markets (spot and derivatives) and in result we got redundant requests.
Will be handy if in `bybit` class options parameters can be provided 'fetchMarkets' option like in `binance`.

**Comment by kjnh10** [comment]
How can I create_order for margin trading?
When I specify "BTC/USDT", it leads to trading spot pair.

**Comment by frosty00** [comment]
@kjnh10 you can use `bybit.borrowMargin` and `bybit.repayMargin` and then make spot orders as normal using the borrowed margin

**Comment by kjnh10** [comment]
@frosty00 

With unified accout, I got this error message.
ccxt.base.errors.ExchangeError: bybit {"retCode":12634,"retMsg":"Account has been upgraded (upgrading) to UTA","result":{},"retExtInfo":{},"time":1681209532437}
