### ISSUE TITLE
What's different in 3.0?

### ISSUE THREAD

**Issue by goznauk** [ccxt/ccxt#17203]
Hello CCXT Team!

I understand that maintaining comprehensive [changelogs](https://github.com/ccxt/ccxt/blob/master/CHANGELOG.md) can be challenging due to the frequency of updates (https://github.com/ccxt/ccxt/issues/9925) and the difficulty in categorizing them as major/minor/patch (https://github.com/ccxt/ccxt/issues/9391). However, I'm eager to learn about the rationale behind the recent major version upgrade.

Could you please provide some insight into the key factors that led to the transition from major version 2 to 3? Detailed changelogs for major and minor versions would be greatly appreciated. (I concur that maintaining patch changelogs in detail might be unfeasible XD)

**Comment by carlosmiei** [comment]
Hello @goznauk,

As announced on Sunday, CCXT migrated its development codebase from Javascript with CJS modules to Typescript with ESM modules and refactored its structure slightly to reduce circular imports and custom inheritance solutions specific to each language, now every language has the same structure. You can read more about the migration and refactor here: https://github.com/ccxt/ccxt/pull/14282

Nonetheless, we tried to make this change backward compatible with all users from all languages (Typescript, Javascript, Python, PHP). Still, since it was a massive update, we decided to make a major bump to avoid surprising the users upon updating.

Regarding the changelog, I agree with you, and we're working towards that, but right now, we don't have a stable solution yet, however, I generated a changelog manually so it could help track the changes, and will attach it to this comment. (it's not perfect though).

If you're reticent about updating your ccxt version I would highly advise doing it because typescript will give us an extra safety compile-time from now on, and we expect to see an improvement in the shipped code.  Also feel free to reach out if you hit any issue after updating it, we will do our best to help you out as soon as possible.


Thank you!

[NewChangelog.md](https://github.com/ccxt/ccxt/files/10989386/NewChangelog.md)
