### ISSUE TITLE
How to correctly get tokens that have the same short names, but which are different in essence?

### ISSUE THREAD

**Issue by AlwxDavydov** [ccxt/ccxt#17263]
### Operating System

Windows 10 

### Programming Languages

python

### CCXT Version

2.8.31

### Description

For a concrete example, I want to get information about the GAS token on two exchanges, mexc and gate. However, what is called GAS(but GAS here is only the example, there are a lot of same tokens with such names) in Mex is actually GAS_DAO, on the gate the full name of the GAS token is also GAS. This is a different coin with a different price and with a different contract. How can I separate these concepts and get information about GAS(GAS), and not about GAS_DAO. I tried using load_market, fetch_markets and fetch_tickers. I noticed that it's not a bad idea to compare coins by code. But I don't understand how to get a coin by code.(2 part of code). Sorry if this is a dumb question, I'm just really stuck

### Code

```
import ccxt

exchange1 = ccxt.mexc3()
exchange2 = ccxt.gate()

exchange1.load_markets()
exchange2.load_markets()
markets1 = exchange1.currencies
markets2 = exchange1.currencies

print(markets1['GAS'])
print(markets2['GAS'])  

Using codes

import ccxt

exchange1 = ccxt.gate()
exchange2 = ccxt.mexc()

symbols1 = exchange1.load_markets()
symbols2 = exchange2.load_markets()

print(exchange1.currency('GASDAO')['code']) #GASDAO
print(exchange2.currency('GAS')['code'])  # GASDAO
```

**Comment by pcriadoperez** [comment]
Hi @AlwxDavydov , So ccxt unifies the codes so it's the same across all exchanges. In the case of GASDAO, we use GASDAO.
Also for most functions we accept both the unified ccxt code and also the exchange code. So in the example of mexc, mexc uses the code GAS for GASDAO, this is why you can call both `mexc.currency('GAS')` and `mexc.currency('GASDAO') and both will return GASDAO. As the first will reference the mexc's code for GASDAO and the second case it will recognize ccxt's unified code GASDAO.

This is a bit of a unique case because the exchange code mexc uses is the same as the code ccxt uses for a different currency(GAS).

In the case of gate, it does support both currencies GAS and GASDAO. So `gate.currency('GAS')` will return the GAS currency and `gate.currency('GASDAO')` will return the GASDAO currency.

I hope this answers your question. I'll close the issue for now but feel free to reach out with any other questions!
