### ISSUE TITLE
3.0 exchange.parsePrecision not handle '0' correctly

### ISSUE THREAD

**Issue by lovepocky** [ccxt/ccxt#17284]
### Operating System

linxu

### CCXT Version

3.0.25

### Description

```ts
 const bitget = new ccxt.pro.bitget()
 console.log(bitget.parsePrecision('0'))
> 0.1
```
previous versions expect output is `1e0`

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @lovepocky 
Yes we decided to get rid of the scientific notation but it should not impact any calculations with it because both formats are equivalents. 

You can read more about the rationale behind this change here:
https://github.com/ccxt/ccxt/pull/17115
https://github.com/ccxt/ccxt/issues/15238
https://github.com/ccxt/ccxt/issues/16167

**Comment by lovepocky** [comment]
@carlosmiei sorry I didn’t describe it clearly. 
the new method is expected to return 1, not 0.1

**Comment by carlosmiei** [comment]
> @carlosmiei sorry I didn’t describe it clearly. the new method is expected to return 1, not 0.1

@lovepocky sorry my bad, we will take a look asap
