### ISSUE TITLE
OKX Ether options missing in okx.markets, after loaded the market

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#17351]
### Programming Languages

JS

### CCXT Version

latest

### Description

Only Bitcoin options are shown in the okx.markets.

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @x1i4b1x2 

Since the default uly is `BTC-USD`, you won't find ether option in okx (https://www.okx.com/docs-v5/en/#rest-api-public-data-get-instruments). However, you can change underlying by setting `defaultUnderlying` in options, or `uly, marketId` in params when `loadMarkets` or `fetchMarkets`. Let me know if you have other questions.
