### ISSUE TITLE
Cannot retrieve Poloniex/Cryptopia CLOSED orders

### ISSUE THREAD

**Issue by kerbe6** [ccxt/ccxt#1740]
- OS: Linux
- Programming Language version: Python 2.7.14+
- CCXT version: 1.10.978
- Exchange: Poloniex, Cryptopia
- Method: fetchClosedOrders(), fetchOrders()

CCXT seems to be unable to get closed orders from Poloniex or Cryptopia. fetchOpenOrders(symbol) works fine. fetchOrders(symbol) only returns open orders. fetchClosedOrders(symbol) returns an empty list. I don't know if there's a built in lookback limit for the method, but I have closed orders that are only hours old which are not being returned by the method. Both of these exchanges have 'fetchClosedOrders': 'emulated' listed as a property.

I'm pretty sure I'm calling these methods properly -- they work fine when I try them on Binance.

Thanks!

**Comment by kroitor** [comment]
Hi!

This issue was addressed here:

- https://github.com/ccxt/ccxt/issues/1172#issuecomment-357423540
- https://github.com/ccxt/ccxt/issues/1172#issuecomment-357423540
- https://github.com/ccxt/ccxt/pull/102
- https://github.com/ccxt/ccxt/issues/96

Let us know if it doesn't answer your question. Thx!

**Comment by kerbe6** [comment]
Thanks! Your library is amazing, by the way. You guys did an awesome job. Thanks for all the time you've put into this.
