### ISSUE TITLE
[help] How can I fetch orders at May 19, 2021 from 15:30 PM to 16:30 from binanceusdm?

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#17469]
How can I fetch orders for ICPUSDTPERP pair at `May 19, 2021 from 15:30 PM to 16:30 PM` from binance-futures (`ccxt.binanceusdm()`)? Any guide would be appreciated.

---------

The Bitcoin futures price diﬀerence between Binance and other exchanges was seven times larger during the crash period compared to a prior reference period. Hence [this paper -- Bitcoin Flash Crash on May 19, 2021: What did really happen on Binance?](https://acfr.aut.ac.nz/__data/assets/pdf_file/0009/686754/6b-Tim-Baumgartner-May19.pdf) argues that: "A part of the data has been (partly) back-ﬁlled by Binance later on during the outage period: May 19, 2021 from 15:30 PM to 16:30".

I just want to close investigate the orders at the exact time duration I get liquadated when there was outrage. I have been liquated in `ICPUSDTPERP` pair at Crash on May 19, 2021 on Binance where original price of the pair shown 50% lower value than its original price.

**Comment by cryptoCCY** [comment]
You can adapt the following example to suit your purposes: https://github.com/ccxt/ccxt/blob/master/examples/py/binance-futures-positions.py

With something like the following:

`import os
import sys
from pprint import pprint

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binanceusdm({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
})

markets = exchange.load_markets()

symbol = 'ICP/USDT:USDT'
since   = DATE_TIME_OF_INTEREST # use datetime.timestamp()*1000 for the start time you need
limit     = 100 #or however many orders you are interested in fetching

order_history = exchange.fetch_orders(symbol, since, limit, {})
pprint(order_history)`

**Comment by avatar-lavventura** [comment]
@cryptoCCY Thanks!
