### ISSUE TITLE
StopLoss/ Take Profit 

### ISSUE THREAD

**Issue by alphatrade1** [ccxt/ccxt#17628]
### Operating System

MAC

### Programming Languages

python

### CCXT Version

3.0.61

### Description

If I send a limit order, how can I also send a stop loss and take profit order attached to that position such that if my position closes the additional take profit and stop loss orders are also killed? I sent a create_orders as such 

self.exchange.create_order(instrument, 'TAKE_PROFIT_MARKET', 'sell', size, price,{'stopPrice': 30000,"reduceOnly": True})

But If I manually close the order still have an issue

### Code

self.exchange.create_order(instrument, 'TAKE_PROFIT_MARKET', 'sell', size, price,{'stopPrice': 30000,"reduceOnly": True}))

**Comment by Dan-krm** [comment]
Which exchange are you using? Stop-loss and take-profit orders aren't fully unified yet so it can depend on the exchange and this specific functionality that you're asking for isn't always available.

The schema in this issue is what we are currently following: https://github.com/ccxt/ccxt/issues/13822

**Comment by Dan-krm** [comment]
CCXT's `stopLoss` and `takeProfit` functionality is unified and supported on most exchanges now, you can check the documentation for more information: https://docs.ccxt.com/#/README?id=stoploss-and-takeprofit-orders-attached-to-a-position
