### ISSUE TITLE
Is it possible to accelerate the transfer between exchanges

### ISSUE THREAD

**Issue by AntonDe** [ccxt/ccxt#17670]
### ؜

Hi all,

I write a script which sends USD form Binance over the BNB Network to another exchange, where the USDT are used to trade and finally the purchased amount of coins transfers back to Binance.

Is there a way to accelerate the transfer, or can I not influence the network speed at all. I understand that it probably depends on the load of the network, but maybe? :)

Thanks

**Comment by carlosmiei** [comment]
Hello @AntonDe,
If you're transferring from exchange A to exchange B I don't think so because, besides the time it takes to broadcast and accept the transaction, you also have to wait for the approval of the exchange (actually, that takes most of the time). If you're withdrawing from a self-hosted wallet you can try to increase the gas price/fee a bit so your tx has a higher priority on the mem pool.
