### ISSUE TITLE
load_markets v/s fetch_markets (pairs dict differences)

### ISSUE THREAD

**Issue by avmarko** [ccxt/ccxt#17718]
### ؜

CCXT ver 2.2.36 / Win-10 / python 3.7

Getting available trading-pairs via load_markets may bring less results compared to fetch_markets for some exchanges.
So far I noticed two types of differences:

A) Duplicate-pairs (totally identical records) are brought by fetch_market (while load_market doesn't). Example: For bitFlier exchange BTC_JPY and ETH_BTC pairs, occuring 3 times each in fetch_market result.

B) Multiple pairs of the same symbol with different id are all brought by fetch_markets (while load_market brings only one of them). Example: For Binance exchange fetch_markets brings symbol BCH/BTC with 2 different ids (BCHBTC and BCHABCBTC), while load_markets brings only one id (BCHBTC).

**Comment by carlosmiei** [comment]
Hello @avmarko,

`fetchMarkets` returns an array of parsed markets whereas `loadMarkets` returns a dictionary indexed by the unified symbol, which is why you don't see repeated entries. For instance, binance has conflicting ids between spot and linear swap markets, so it is expected to see `id: BTCUSDT` twice on the array returned by `fetchMarkets` . The same does not happen with `loadMarkets` because our unified symbols do not have this ambiguity so you will get one entry with `key = 'BTC/USDT` referring to the spot market and another with `key = 'BTC/USDT:USDT` referring to the linear swap market.

**Comment by avmarko** [comment]
Understood :-) 
Thank you @carlosmiei
