### ISSUE TITLE
KucoinFutures add set_leverage_tiers method

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17897]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

As KucoinFutures does not have a set_leverage endpoint, is it possible to add an endpoint to adjust the risk limit tiers which uses this endpoint: https://docs.kucoin.com/futures/#adjust-risk-limit-level

### Describe the solution you'd like

Add an set_leverage or set_risk_limit_level method to ccxt. 

### Describe alternatives you've considered

Using the "leverage" argument when placing orders, unfortunately then you use isolated margin where I prefer to use cross margin (for kucoin this is auto deposit margin).

**Comment by Dan-krm** [comment]
@Tomas-MP We usually don't create new unified methods unless they can be supported on multiple exchanges. We already have a setLeverage method but it looks like it's a bit different than what the endpoint you're referring to is used for. I opened a PR that will add this missing endpoint, and you can use the Implicit API with it: https://docs.ccxt.com/#/?id=implicit-api
```
kucoinfutures futuresPrivatePostPositionRiskLimitLevelChange '{"symbol":"XBTUSDTM","level":2}'

kucoinfutures.futuresPrivatePostPositionRiskLimitLevelChange ([object Object])
2023-05-13T06:26:07.034Z iteration 0 passed in 595 ms

{ code: '200000', data: true }
```

**Comment by Tomas-MP** [comment]
@Dan-krm when I try the client.set_leverage("XRP/USDT:USDT", params={'leverage': 10}) it does throw the NotSupported error, is this correct? The other implicit API method is working, thank you.

**Comment by Dan-krm** [comment]
Yeah that's correct. Sorry my last message was a bit unclear, what I meant was setLeverage is a unified method but it's not supported on kucoinfutures because there's no endpoint for it, you can see which methods are supported for each exchange under `'has'` in the specific exchange class. For a list of exchanges and their supported methods you can also refer to this js example: https://github.com/ccxt/ccxt/blob/master/examples/js/exchange-capabilities.js
