### ISSUE TITLE
Please Help Me

### ISSUE THREAD

**Issue by aliriahy** [ccxt/ccxt#18049]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

please help
How can I send the candle data I received to another exchange?

**Comment by kroitor** [comment]
> How can I send the candle data I received to another exchange?

I don't think the other exchange will accept external data from you. It's not how cryptocurrency exchanges work, so your question does not make much sense in terms of practical use or what you're trying to do. I'm going to close this issue, please, read more about CCXT to practice with code and understand it:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/FAQ

Feel free to comment on this issue or explain your question better so that we could help.

**Comment by aliriahy** [comment]
Hi Igor
I have set up an example of an exchange using opendex, now I have a problem
to display the initial data on the trade page, can you help me

regards
alireza
