### ISSUE TITLE
CCXT Bybit fetchFundingRate not working

### ISSUE THREAD

**Issue by hyunr01** [ccxt/ccxt#18073]
### ؜

OS: Windows
Programming Language version: Python 3.9.13
CCXT version: 3.1.15

```
bybit = ccxt.bybit()
bybit.options['defaultType'] = 'future'
print(bybit.fetchFundingRate('BTC/USDT'))
```

I'm not sure why, but I keep getting the following error when I try to run the above code:
BadSymbol: bybit fetchFundingRate() supports contract markets only

The above code works for the ccxt binance library, so I'm not too sure why it's saying that the future market isn't a contract market.

**Comment by carlosmiei** [comment]
Hello @hyunr01,

In our unified terms, `BTC/USDT' represents a spot market, not a linear swap contract. Binance supports that notation due to historical reasons, but we recommend the unified symbols adoption, in this case, you should be using `BTC/USDT:USDT`.

I would recommend checking this out: https://docs.ccxt.com/#/README?id=symbols-and-market-ids

**Comment by hyunr01** [comment]
Thanks!
