### ISSUE TITLE
Make calculate_fee async

### ISSUE THREAD

**Issue by jsecchiero** [ccxt/ccxt#1860]
I'm actually using python and the calculate_fee method with ccxt.async but it return a dict not a coro.

example:
```
import ccxt.async as ccxt
import asyncio

async def fee():
    bittrex = ccxt.bittrex()
    await bittrex.load_markets()
    fee = \
    await bittrex.calculate_fee('RCN/ETH','limit','sell',8004.00412983,0.00021422)
    print(fee)

loop = asyncio.get_event_loop()
asyncio.ensure_future(fee())
loop.run_forever()
```

error
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 8, in fee
    await bittrex.calculate_fee('RCN/ETH','limit','sell',8004.00412983,0.00021422)
TypeError: object dict can't be used in 'await' expression
```

**Comment by kroitor** [comment]
> but it return a dict not a coro

This is by design. That function does all the calculation locally and does not send any requests, so it does not have to be async at all. It's a plain linear method. So you should not *await* for it, just call it and save the result into a variable.

Let us know if this does not answer your question.
