### ISSUE TITLE
Create a market buy order on binance

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#18621]
### ؜

Hello, 

Please share a worked code on python how to create a buy marked order on a binance.  How to pass parameter a params?

2023-07-22 08:00:06 :: WARNING  :: Exchange.create_order() takes 6 positional arguments but 7 were given          

```
                    quoteOrderQtyMarketAllowed = market_info.get('quoteOrderQtyMarketAllowed', False)
                    priceIsRequired = market_info.get('priceIsRequired', False)

                    params = {}
                    if quoteOrderQtyMarketAllowed:
                        params = {'quoteOrderQty': order_amount} 
                        order_amount = None

                    if not priceIsRequired:
                        current_price = None

                    order = await self.exchange.create_order(self.symbol, 'market', self.side, order_amount, current_price)

```

**Comment by kroitor** [comment]
On the code itself, you're missing the 6th argument (`params`) for `exchange.create_order()`:

```
                   quoteOrderQtyMarketAllowed = market_info.get('quoteOrderQtyMarketAllowed', False)
                    priceIsRequired = market_info.get('priceIsRequired', False)

                    params = {}
                    if quoteOrderQtyMarketAllowed:
                        params = {'quoteOrderQty': order_amount} 
                        order_amount = None

                    if not priceIsRequired:
                        current_price = None

                    order = await self.exchange.create_order(self.symbol, 'market', self.side, order_amount, current_price, params)
```

As for the error you're posting, that's coming from another file, or a different line:

```
2023-07-22 08:00:06 :: WARNING :: Exchange.create_order() takes 6 positional arguments but 7 were given
```

In your code above you're only passing 5 params, but not 7. That just means there's a mismatch of the error with the actual line of code. It could be explained by some confusion or misconfiguration of your scripts, like, launching one file instead of another, not saving your files after edits and so on. Or there's more code in the file that is now shown in your snippet.

**Comment by YuriyTigiev** [comment]
Hello, 

I have tried three different approaches to pass the parameter "params." Unfortunately, in all three cases, I encountered an error: "Exchange.create_order() takes 6 positional arguments but 7 were given" in the TypeScript code (Deno) for the latest library for the Binance exchange. It appears that I accidentally forgot to include the "params" parameter in my previous post.


```
#1
params = {}
params['quoteOrderQty'] = order_amount
order = await self.exchange.create_order(self.symbol, 'market', self.side, order_amount, current_price, params)
```



```
#2
params = {'quoteOrderQty': order_amount} 
order = await self.exchange.create_order(self.symbol, 'market', self.side, order_amount, current_price, params)
```


```
#3
params = {'quoteOrderQty': order_amount} 
order = await self.exchange.create_order(self.symbol, 'market', self.side, order_amount, current_price, params=params )
```

**Comment by ttodua** [comment]
@YuriyTigiev please post your ccxt version number

**Comment by AdolfoVillalobos** [comment]
Hi,

Whenever I have experienced similar issues in the past, in which the signature of the function seems to be correctly being satisfied, it often relates to one of: (1) A missing reference to "self", self being a class created by you, or (2) A redundant reference to "self".  

In any case, can you should provide a more complete example in order to assess in which section of the code is the reference failing to satisfy expectations? 

---

If the previous fails, the most simple explanation might be that you installed a version of ccxt that does not support the number of parameters given. 

---

Finally: Did you tried using keyworded values for all the parameters, and not just for params?. it is posible that there is a conflict with an optional parameter

**Comment by ttodua** [comment]
@YuriyTigiev sorry, I kicked in here in incorrect moment while looking at your last comment and I forgot that you used python, not js. but still, the code that you share does not seem to be broken with regard to what you say. you might changing name of your local variable name `params` into smth other and try again, if still fails, repost here a complete snippet (minimal reproducible example) so we could test the whole script on our side.

**Comment by YuriyTigiev** [comment]
Sorry. My bad. I forgot about this part of code.

```
    @ async_retry()
    async def create_order(self, symbol: str, order_type: str,
                           side: str, amount: float, price: float) -> dict:
        return await self.exchange.create_order(symbol=symbol, type=order_type,
                                                side=side, amount=amount, price=price)
```
