### ISSUE TITLE
Bitmex fetch_funding_rates not working

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#19069]
### Operating System

windows 10

### Programming Languages

Python

### CCXT Version

4.0.80

### Description

`fetch_funding_rates` returns the same data as in exchange.markets

CCXT
`def fetch_funding_rates(self, symbols: Optional[List[str]] = None, params={}):`

`[List[str]]` is a type alias.  Do you expect a list of symbol like ['BTC/USD:BTC'','BTC/USDT:USDT'' ] and, if None is passed, return all symbols current funding rate ?

### Code

```
async def start_bot():
    bitmex = ccxt.pro.bitmex()
    markets = await bitmex.load_markets()
    rates = await bitmex.fetch_funding_rates(['BTC/USD:BTC'])
    print (rates)

asyncio.run(start_bot())

```

**Comment by carlosmiei** [comment]
Hello @ShieldTrade,

> fetch_funding_rates returns the same data as in exchange.markets

That is because the same endpoint that returns the available instruments also has the information about the funding rate, so per se I don't think it is a problem.


> [List[str]] is a type alias. Do you expect a list of symbol like ['BTC/USD:BTC'','BTC/USDT:USDT'' ] and, if None is passed, return all symbols current funding rate ?

Yes I think so, are you suggesting it is something wrong with it?

We have indeed a problem with the filtering but I'm going to fix it asap.

**Comment by ShieldTrade** [comment]
No problem.
While waiting for your fix I  can filter the info I need from `exchange.markets.`
