### ISSUE TITLE
Bybit v5 not supporting normal accounts correctly

### ISSUE THREAD

**Issue by germangar** [ccxt/ccxt#19311]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.0.99

### Description

Hey guys,

I just updated ccxt to the latest version and I'm finding out I have troubles using setMarginMode in Bybit with a standard account.
<br>
If try to addapt to the new names like this:

```
            newMarginMode = MARGIN_MODE
            if( cls.exchange.id == 'bybit' ):
                newMarginMode = 'ISOLATED_MARGIN' if( MARGIN_MODE == 'isolated' ) else 'REGULAR_MARGIN'

            try:
                response = cls.exchange.set_margin_mode( newMarginMode, symbol, params )
```
I get this:
`Unhandled Exception bybit setMarginMode() Normal Account not support ISOLATED_MARGIN`

If I simply keep the old names ('isolated' and 'cross'), I get this:
`set_margin_mode: Unhandled Exception bybit setMarginMode() marginMode must be either ISOLATED_MARGIN or REGULAR_MARGIN or PORTFOLIO_MARGIN`

Is there any way to keep the standard accounts working with v5? I'm not a big fan of the concept of unified accounts.

Thanks.
<br>
Edit: Also. Is there a way to know the type of account I'm communicating with?

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @germangar 

You can check whether the account is uta by `isUnifiedEnabled()` or `this.options['enableUnifiedMargin'], this.options['enableUnifiedAccount']`.

We used this api in `setMarginMode` https://bybit-exchange.github.io/docs/v5/account/set-margin-mode, it only support `REGULAR_MARGIN (i.e. Cross margin), PORTFOLIO_MARGIN` for normal and usdc perp / option.

I found another api https://bybit-exchange.github.io/docs/v5/position/cross-isolate for normal account, would test and see how it works for normal account.

**Comment by germangar** [comment]
Looks like that could be it. That's great. I'm reverting to the ccxt version I had before by now, and I'll try again when it's implemented. Thanks a lot.

**Comment by sc0Vu** [comment]
Hi @germangar 

You can try setMarginMode with symbol after update ccxt (https://github.com/ccxt/ccxt/pull/19313).

Let me know if you have other issues.

**Comment by germangar** [comment]
That was fast. Thank you. I'll try it tonight.

**Comment by xmatthias** [comment]
unfortunate that the merge for this fix seems to have missed 4.0.100 by about an hour (based on push times on pypi) - and considering that previously working code is still not working on 4.0.100.

testing this on master seems to (somewhat) work - though the call is raising an odd (in my opinion inappropriate) error in "InvalidOrder".

```

fetch Request: bybit POST https://api.bybit.com/v5/position/switch-isolated RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'asdfasdf, 'X-BAPI-TIMESTAMP': '1695057731272', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': 'asdfasdf', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} 
RequestBody: {"category":"linear","symbol":"ETHUSDT","tradeMode":1,"buyLeverage":"3.0","sellLeverage":"3.0"}


fetch Response: bybit POST https://api.bybit.com/v5/position/switch-isolated 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '121', 'Connection': 'keep-alive', 'Date': 'Mon, 18 Sep 2023 17:22:11 GMT', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1695057731385', 'Ret_code': '110026', 'Cache-Control': 'no-store', 'Traceid': '', 'Timenow': '1695057731387', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 9336c14434e205e440418213079c6074.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA60-P1', 'X-Amz-Cf-Id': '=='} 
ResponseBody: {"retCode":110026,"retMsg":"Cross/isolated margin mode is not modified","result":{},"retExtInfo":{},"time":1695057731387}


InvalidOrder('bybit {"retCode":110026,"retMsg":"Cross/isolated margin mode is not modified","result":{},"retExtInfo":{},"time":1695057792195}')
```

I understand (somewhat) why the placement doesn't work - but `InvalidOrder` seems highly inappropriate (something around `BadRequest` would sound better to me - which would align it to `110043` ... https://github.com/ccxt/ccxt/blob/282cddb7fd7756067f9f302afee589c4ebfe4daf/ts/src/bybit.ts#L748C22-L748C28

**Comment by germangar** [comment]
I'm waiting for 101 to test it. I'll report back since I guess I'm the one who has the standard account here.

**Comment by carlosmiei** [comment]
@xmatthias Thanks, you're 100% right we will update it asap

**Comment by germangar** [comment]
I can confirm 101 is back to succesfully changing margin mode with the normal account. Thanks again!

**Comment by sc0Vu** [comment]
@carlosmiei is there any possibility bybit use the same error code (I remember they did before)?

**Comment by xmatthias** [comment]
@carlosmiei i find your PR a bit picky if i'm honest

what makes 110026 different from 110025 - so one is a invalid order, while the other is not? (i did not directly encounter this this error - i just noticed the "next to this" mappings as slightly odd).

```
                    '110025': InvalidOrder, // Position mode is not modified
                    '110026': BadRequest, // Cross/isolated margin mode is not modified
                    '110027': InvalidOrder, // Margin is not modified
```

**Comment by carlosmiei** [comment]
@xmatthias you're right, I will check the contiguous errors as well.

**Comment by xmatthias** [comment]
@carlosmiei another question one i THINK changed with this update (though i'm not sure if it's been present in prior versions ...).

from the [order structure](https://docs.ccxt.com/#/README?id=orders) documentation it seems like the order object defines 5 states ... 
```
    'status':      'open',        // 'open', 'closed', 'canceled', 'expired', 'rejected'
```
though in reality, i do receive `'status': None` (or undefined in js) ... 
i do understand that some exchanges don't provide this info when creating an order (for example, bybit) - but then an order should be assumed to be open, no? or is undefined/None a valid response for this field, too?

**Comment by carlosmiei** [comment]
> @carlosmiei another question one i THINK might have changed with this update (though i'm not sure if it's been present in prior versions ...).
> 
> from the [order structure](https://docs.ccxt.com/#/README?id=orders) documentation it seems like the order object defines 5 states ...
> 
> ```
>     'status':      'open',        // 'open', 'closed', 'canceled', 'expired', 'rejected'
> ```
> 
> though in reality, i do receive `'status': None` (or undefined in js) ... i do understand that some exchanges don't provide this info when creating an order (for example, bybit) - but then an order should be assumed to be open, no? or is undefined/None a valid response for this field, too?

@xmatthias We don't assume a state by default if not provided (or at least if is not inferable from other fields), since the order parser is shared among different methods (fetchOrders, fetchOrder, fetchClosedOrders, watchOrders, createOrder, etc etc) it usually leads to some bugs.

**Comment by xmatthias** [comment]
@carlosmiei unfortunately, i found the last version unstable (buggy) for bybit (#19362). I assume it's mostly due to v5 - even though not everything is explicitly linked to the v5 introduction PR.

**Comment by anonFacePalm** [comment]
@carlosmiei
Bybit is not supporting classic Spot in a consistent way in v5 API.  Ok, fine.  Is there a simple way to downgrade CCXT to just use the v3 API?  Or maybe to use the v3 API when using a non-unified spot account?

### Exchange property .version?
The manual says that the exchange property .version seems to be an upper limiter, not a specifier for the api version.  And looking in bybit files and Exchange files, it appears that Exchange.version is never checked.  The only checking for 'version' is checking the CCXT version. 

### What about downgrading the websocket?

In /ts/src/pro/bybit.ts:31-68  the urls have a subcategory for unified and nonUnified in private spot.  However, even after setting defaultType and manually checking isUnifiedEnabled(), the raw response data my tests are getting is in V5api format, not v3api format.

getUrlByMarketType() :
/ts/src/pro/bybit.ts:143 does NOT check for unified/nonUnified.  Also, /ts/src/pro/bybit.ts:127 assumes 'api', without checking for if 'test' should be used.

In /ts/src/bybit.ts, isUnifiedEnabled() is called by most if not all of the fetchXxxxx() functions.  However, for pro, watchBalance() is the only one that calls isUnifiedEnabled() (/ts/src/pro/bybit.ts:1286) 

When messages are received, it appears that the parsing is based off of the topic of the websocket.  Which would be fine, if the websocket topic had been set correctly.  But it looksas though because the topic was not set correctly, the wrong endpoint was used, and the messages come in without the data for classic spot.

**Comment by carlosmiei** [comment]
Hello @anonFacePalm,

> Bybit is not supporting classic Spot in a consistent way in v5 API. Ok, fine. Is there a simple way to downgrade CCXT to just use the v3 API? Or maybe to use the v3 API when using a non-unified spot account?

The only way is to downgrade the ccxt version. Nonetheless, we were recommended by bybit to migrate to v5 because it would work properly with all account types (normal, unified margin, uta).

Can you please elaborate a bit more on what is not working properly after the v5 upgrade?

**Comment by anonFacePalm** [comment]
@carlosmiei  Thanks for your response. I saw you made some updates to bybit, so I updated to 4.1.12 and checked again.

The main issue is that Bybit is providing inconsistent trading fee data to classic spot on V5API.

- The private trade structure from watchMyTrades does not return the trading fee.
- The order structure from watchOrders does not properly set fee['currency'] from 'feeCurrency'.
- The order structure update from watchOrders that DOES have the fee does not have the tradeId and has cumulative amounts everywhere except for the fee, which is for a single trade.
- The order structure from watchOrders does not accumulate fees and trades in the order structure.
- The order structure from fetchClosedOrders does not include fee info.

watchMyTrades doesn't return the trading fee because Bybit doesn't provide 'execFee' for classic spot in v5API Private Execution websocket ( https://bybit-exchange.github.io/docs/v5/websocket/private/execution ).  Sure, classic spot is not supported in many of the fields, but some of them are kinda redundant.  Like, orderPrice and orderQty can be ignored and use 'execPrice' and 'execQty' instead.

fetchMyTrades does return the amount of the trading fee under 'execFee', but in order to determine the currency, you have to follow the procedure at https://bybit-exchange.github.io/docs/v5/enum#spot-fee-currency-instruction  Plus, for every update, now you have to fetchMyTrades.

watchOrders does not set fee['currency'] from 'feeCurrency' and only includes the fee on a single update, and does not add it to 'fees' to include it on subsequent updates from that order id.

I can provide examples of the data feed if you would like, but would rather not make everyone scroll through all that.

**Comment by anonFacePalm** [comment]
@carlosmiei 

Example:
https://github.com/anonFacePalm/ccxt/blob/data-feed/bybit%20v5api%20data.log

**Comment by carlosmiei** [comment]
@anonFacePalm Thanks, we will check it and revert.
