### ISSUE TITLE
Unable to watch_trades() with some markets

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#19469]
Hello,

I'm wondering why it's possible to `watch_trades` Bitget's markets like `BTC/USDT` and `BTC/USDT:USDT` with `ccxt.pro`, but not `BTC/USD:BTC`. A similar issue happens with Bitmart, market `BTC/USDT` can be monitored but not `BTC/USDT:USDT`. 

What could be the reason ? I'm not sure if it's CCXT Po limitation or if the class instance needs to be configured somehow.

Thank you,
Kinzowa

**Comment by Kinzowa** [comment]
This is the error I got for Bitget : 

`An error occurred with bitget BTC/USD:BTC: bitget {"event":"error","arg":{"instType":"mc","channel":"trade","instId":"BTCUSD_DMCBL"},"code":30001,"msg":"instType:mc,channel:trade,instId:BTCUSD_DMCBL doesn't exist","op":"subscribe"}, <class 'ccxt.base.errors.BadRequest'>`

**Comment by samgermain** [comment]
Thank you for letting us know. This was a bug related incorrect parsing of the websocket market ids for coin-margined and usdc-margined contracts. 

I pushed a [PR](https://github.com/ccxt/ccxt/pull/19472) that will fix this for all perpertual contracts. Delivery future contracts will still not be able to be watched however because bitget has not written implementation on their api yet.
