### ISSUE TITLE
How to handle GDAX create_market_sell_order:ExchangeError : gdax size too precise

### ISSUE THREAD

**Issue by LaurentIsRunning** [ccxt/ccxt#1964]
Hello, 

I've read many comments regarding the precision issue, and the usage of string vs number is pretty clear for me.
What is not soo clear is who has the responsibility to set the correct precision, ccxt or its user.
For instance with gdax I had the following error:
`GDAX - create_market_sell_order:ExchangeError : gdax size too precise (0.015119505)`

Shoul I call _amount_to_precision_ myself? Do I have to double check _self.markets[symbol]['precision']['amount']_?

I'm quite certain that this question is a duplicate, sorry for that, but I can't find a clear answer.

Thank you very cmuch in advance, 

Laurent
 

- OS: WIndows 10
- Programming Language version: Python
- CCXT version: 1.10.991
- Exchange: gdax
- Method: create_market_sell_order

**Comment by kroitor** [comment]
> What is not soo clear is who has the responsibility to set the correct precision, ccxt or its user.

It's ccxt. However, because this is still a work in progress, some things may be still missing here and there, in this particular case, the user is responsible to workaround it by:
1. calling `amount_to_string` on client side for the amount to prepare it for posting in an order
2. calling `price_to_presicion` on client side for the price...

This is going to be reworked very soon with much more convenience in mind:
- https://github.com/ccxt/ccxt/issues/522
- https://github.com/ccxt/ccxt/pull/1162

The work on this is going full on! )

Let us know if this does not answer your question. Thx!

**Comment by LaurentIsRunning** [comment]
Thank you very much for your answer!
Yes it is clear for me now !
