### ISSUE TITLE
Bitmex fetch positions doesn't show information anymore

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#19666]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.1.20

### Description

Hello,

suddenly, probably after ccxt update I get no Information from 

Bitmex.fetch.positions anymore. 

Output is --> []  None

Was there any change on ccxt for Bitmex or is it a bug? 

My account was liquidated because of this problem. Luckily it was just play money :-)... 

### Code

```
bitmex = ccxt.bitmex({'enableRateLimit': True,
                       'apiKey': bitmexconfig.api_key,
                       'secret': bitmexconfig.api_secret,})


symbol = 'XBTUSD'
params={"type":"swap","code":"XBT"}

bitmex_pos = bitmex.fetch_positions([symbol], params)
print(bitmex_pos)

```

**Comment by carlosmiei** [comment]
Hello @Nitrix321,

Recently we just improved the filtering because if you called `fetch_positions([A,B,C])` it would return all the positions regardless of the symbols provided. The filtering might not be working correctly with exchange-specific ids and I will fix it ASAP but in the meantime, you can either not provide any symbol or provide the unified one (BTC/USD:BTC)

Example:
```Python
pos = bitmex.fetch_positions(params = params)
# or
pos = bitmex.fetch_positions(['BTC/USD:BTC'] ,params = params)
```

**Comment by carlosmiei** [comment]
@Nitrix321 Sorry I think what I said is wrong, exchange-specific symbols are also working,  but due to the filtering it will only return positions from the symbols in the symbols array, so I would suggest calling `fetch_positions` without any argument.

**Comment by Nitrix321** [comment]
hi @carlosmiei thanks, its working now without any argument as you said. I already tried without symbol or only symbol and no param but without any argument I was not thinking about that...
