### ISSUE TITLE
How to determine the right currency to size order amount when dealing with perp ?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#19775]
Hello,

I noticed that MEXC has a `BTC/USDT:USDT` market which need to be sized in `USDT` when creating a new order, and the same `BTC/USDT:USDT` market at Binance must be sized in `BTC`. 

My question is how is it possible to know if the `amount` should be in the `base` or `quote` currency ?

I could make the assumption that if the min amount is 0.001, then it's `BTC`, but I would like a more elegant method to determine the right currency. 

Contracts specs : 

**Binance**

```
Symbol: BTC/USDT:USDT
Contract size: 1.0
Limits:
{"cost": {"max": null, "min": 5.0}, "price": {"max": 4529764.0, "min": 556.8}, "amount": {"max": 1000.0, "min": 0.001}, "market": {"max": 120.0, "min": 0.001}, "leverage": {"max": null, "min": null}}
```

**MEXC**

```
Symbol: BTC/USDT:USDT
Contract size: 0.0001
Limits:
{"cost": {"max": null, "min": null}, "price": {"max": null, "min": null}, "amount": {"max": 2625000.0, "min": 1.0}, "leverage": {"max": 200.0, "min": 1.0}}
```

Regards,

**Comment by Dan-krm** [comment]
Hi @Kinzowa the standard approach is that the amount should be in units of the base currency, some exchanges however require the number of contracts so you'd enter the number of contracts in the amount argument and how much you pay in the base currency would be the number of contracts * the contract size. I think it's pretty uncommon that an exchange would use the quote value for the amount argument.

I think at the very least we could adjust the createOrder docstring for each exchange to say whether the amount should be in units of the base currency, quote currency or number of contracts.

We could also add a `contractAmount` key to the market structure and set it to base, quote or contracts, or we could convert the exchanges that use contracts to use the base amount and maybe set an option to switch between the two. I'll discuss this with the CCXT team and see if they agree with any of these ideas

**Comment by Kinzowa** [comment]
> I think it's pretty uncommon that an exchange would use the quote value for the amount argument.

Hi @Dan-krm, thanks for you answer. I think it's more related to the market types than the exchanges. `amount` of `inverse` markets are usually denominated in the quote currency but `amount` of `linear` and `spot` markets are usually/always denominated in the base currency. The linear market at MEXC pointed above is unusual. Some exchanges also have `quanto` market type, for example ETH/USD:BTC, in which case it's also the `quote` currency.

> We could also add a `contractAmount` key to the market structure and set it to base, quote or contracts, or we could convert the exchanges that use contracts to use the base amount and maybe set an option to switch between the two. I'll discuss this with the CCXT team and see if they agree with any of these ideas

That would be great.

**Comment by Dan-krm** [comment]
@Kinzowa I'm not able to fully test MEXC at the moment because it looks like their futures trading API is under maintenance, but I'll keep checking and test it once the maintenance is finished.

I don't think I'll be adding contractAmount to the market structure or setting an option to switch between base amount and number of contracts anytime soon. Currently the best approach is to just check the contractSize and limits and make your order based off of that. Also sometimes the API documentation or the methods docstring will have some more information regarding the amount argument.

If the contractSize is 1.0 and the minimum amount is in the decimals that means you can treat the amount argument like it's the base currency. If the contractSize is in the decimals and the minimum amount is 1.0 that means you need to enter the number of contracts in the amount argument. (number of contracts * contractSize = base amount)

There is some exceptions where the quote amount is expected generally for market buy orders. We have an option that you can set to true or false called `createMarketBuyOrderRequiresPrice`. If set to true we automatically calculate the quote amount for you by multiplying the base amount by the price, alternatively you can set it to false and provide the quote amount in the amount argument without filling the price argument.

I don't think createMarketBuyOrderRequiresPrice is active for any swap implementations yet but feel free to let us know if you think it's missing somewhere and I think that might be what's missing here, unfortunately I'm unable to test it and add it to MEXC until their maintenance is finished
