### ISSUE TITLE
fetchBalance() - How to get all symbols i.e. Bittrex, Bibox

### ISSUE THREAD

**Issue by ljianyih** [ccxt/ccxt#1991]
Hi, sorry if question sounded too newbie, but how do I get the balances for all symbols? For i.e. Bittrex, and Bibox, I can get only around 5 symbol balances caling this function, but I need to get all symbols for the balance, how do I do this (Binance, hitbtc, returns all balance by calling this)?

Also, if this additional question can be answered then it will be very much appreciated. I couldn't get the authorization for Bit-Z after inserting the API key and secret key. And for Cobinhood, they only provides signature which is secret, what to input in the API key?

Thanks for all these especially this great ccxt library, and sorry for being new to this and trying to learn. Thanks.

**Comment by mkutny** [comment]
There is no such thing as "symbol balance" so it's hard to tell what do you mean by that. I'd suggest reading the Manual first so we could speak the same language.

You also seem skipped "How to submit issues" guide, you need to familiarize yourself with it too. Basically, code snippets, verbose outputs etc are required.

In other words you need to do some homework if you want someone to help you here.

**Comment by kroitor** [comment]
> but how do I get the balances for all symbols?

- https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance

> I couldn't get the authorization for Bit-Z after inserting the API key and secret key.

Then we need you to read this very carefully:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

If you don't provide enough info, we can't really help. We can even make it worse by stupid guessing. Without all your code and verbose output it's really hard to tell anything. We need you to help us to help you, this is how it goes )

> And for Cobinhood, they only provides signature which is secret, what to input in the API key?

Cobinhood is broken now, soon to be fixed, the work on the fix is almost complete here: 

- https://github.com/ccxt/ccxt/pull/1957
- https://github.com/ccxt/ccxt/issues/1980

Let us know if the above doesn't answer your questions.
