### ISSUE TITLE
CoinbasePro to Coinbase Advanced Trade API

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#20070]
### Operating System

Linux Ubuntu 22LTS

### CCXT Version

4.1.56

### Description

Hi, I noticed CoinbasePro APIs are very recently migrating to Coinbase Advanced Trade APIs: 
https://docs.cloud.coinbase.com/advanced-trade-api/docs/rest-api-pro-mapping

Do you know, by any chance if there's backward support for CoinbasePro Apis?
If not, any plans on introducing coinbaseadvancedtrade exchange integration as well?

Thank you for the awesome work,
Florian.

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @fl0wo the coinbase pro API is supported through the `coinbasepro` exchange class in ccxt, the advanced trade API is supported through the `coinbase` exchange class. Let us know if you have any other questions, issues or notice any missing functionality, thanks

**Comment by MrDenfish** [comment]
Migrating from coinbase pro to coinbase advanced trade. I am using a yubyikey for 2factor, because of this, coinbase support says that I need to use a JWT. Not much out there and was wondering if I can implement JWT with ccxt? If so where might I find relevant docs? I have been working with coinbase support and they have been helpful to extent of getting things to work on their end, but I am at a point where I need to test ccxt and can't find anything helpful.

**Comment by Dan-krm** [comment]
@MrDenfish our coinbase classes handle different sections of the Coinbase Cloud API, I'm not sure if there is any special handling that is required on CCXT's end for working with a JWT, you could try connecting just using the recommended approach with the coinbase exchange class and open a separate issue following this guide: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue if you run into any issues
