### ISSUE TITLE
OKEX 

### ISSUE THREAD

**Issue by artbred** [ccxt/ccxt#2008]
There is a problem with okex or ccxt library. language js
When i make request okex.fetchTicker('1ST/USD') i get an error however okex has pair 1st/usd
Maybe problems are in the method?What i can use to get buy/sell prices instead of ticker thanks

**Comment by kroitor** [comment]
> When i make request okex.fetchTicker('1ST/USD') i get an error

```
mbp:ccxt igorkroitor$ node examples/js/cli okex fetchTicker 1ST/BTC
okex.fetchTicker (1ST/BTC)
{      symbol:   "1ST/BTC",
    timestamp:    1519246858000,
     datetime:   "2018-02-21T21:00:58.000Z",
         high:    0.00004654,
          low:    0.00004056,
          bid:    0.00004135,
          ask:    0.00004198,
         vwap:    undefined,
         open:    undefined,
        close:    undefined,
        first:    undefined,
         last:    0.00004199,
       change:    undefined,
   percentage:    undefined,
      average:    undefined,
   baseVolume:    187815.13052326,
  quoteVolume:    undefined,
         info: {      high: "0.00004654",
                       vol: "187815.13052326",
                      last: "0.00004199",
                       low: "0.00004056",
                       buy: "0.00004135",
                      sell: "0.00004198",
                 timestamp:  1519246858000     } }
mbp:ccxt igorkroitor$
```

I don't get any errors with it. Can you please be more specific and follow these steps precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ? Need your language, your language version number, your ccxt version number, your code and verbose output.

**Comment by kroitor** [comment]
Sorry, please ignore my previous message, will look into it and will get back to you asap.

**Comment by artbred** [comment]
Why did yo close it?

**Comment by kroitor** [comment]
Ok, this is fixed in ccxt 1.10.1175 (the build will be available in 4-5 minutes). OKEX does not have a `1ST/USD` future market, just the `1ST/USDT` spot token trading market. This was a symbol inconsistency within ccxt and if you wait a little and then update your ccxt version, the issue will be fixed. Thx for reporting!

**Comment by kroitor** [comment]
> Why did yo close it?

![screen shot 2018-02-22 at 00 24 34](https://user-images.githubusercontent.com/1294454/36506159-cd6c1364-1766-11e8-854f-fc84bb3076e2.png)

If you click that number up there ↑↑↑ you'll see the exact reason )) Because the fix is on the way ) GitHub just closes them automatically when I upload a fix with a tag.

**Comment by artbred** [comment]
Thanks!

**Comment by kroitor** [comment]
@artbred thx to you for your feedback!

**Comment by artbred** [comment]
Очень хорошо когда есть единомышленники!Спасибо за проделанную Вами работу)
