### ISSUE TITLE
GateIO Swap Funding Rate

### ISSUE THREAD

**Issue by acodemics** [ccxt/ccxt#20128]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.1.64

### Description

When trying to get funding rate for GateIO perpetual swaps it loads the spot markets as well which means we can't use the GateIO symbol to retrieve funding rate.

I found that the `load_markets` method also loads spot markets if `sandboxMode` is set to False.

To fix the swap funding rate issue I had to set `sandboxMode` to True to skip the spot market loading.

### Code

```
gate = ccxt.gateio(
          {
              "options": {
                  "defaultType": "swap",
                  "sandboxMode": True
              }
          }
      )
data = gate.fetch_funding_rate('BTC_USDT')
```

**Comment by carlosmiei** [comment]
Hello @acodemics,

Yes it is tricky because gate has conflicting ids between spot and swap markets, but CCXT usually always loads up every market type available (spot, swap, future, etc) to have the exchange ready to perform any operation over any market. 

We also advise the use of the unified symbol because those are not ambiguous but  I will apply a fix to take into consideration the default type you select to resolve the conflict and your code should work after the patch.
