### ISSUE TITLE
Coinbase fetch_currencies throws ccxt\ExchangeError: extend method not found

### ISSUE THREAD

**Issue by madelmann** [ccxt/ccxt#20134]
### Operating System

Ubuntu

### Programming Languages

PHP

### CCXT Version

4.1.66

### Description

Since one of the last updates the Coinbase PHP implementation is broken so that it's not possible to 

PHP Fatal error:  Uncaught ccxt\ExchangeError: extend method not found, try underscore_notation instead of camelCase for the method being called in /.../ccxt/php/Exchange.php:1609
Stack trace:
#0 /.../ccxt/php/Exchange.php(1384): ccxt\Exchange->__call()
#1 /.../ccxt/php/Exchange.php(4102): ccxt\Exchange->fetch()
#2 /.../ccxt/php/Exchange.php(4106): ccxt\Exchange->fetch2()
#3 /.../ccxt/php/abstract/coinbase.php(191): ccxt\Exchange->request()
#4 /.../ccxt/php/coinbase.php(1136): ccxt\abstract\coinbase->v2PublicGetCurrencies()
#5 /.../ccxt/php/coinbase.php(1155): ccxt\coinbase->fetch_currencies_from_cache()
#6 [internal function]: ccxt\coinbase->fetch_currencies()
#7 /.../ccxt/php/Exchange.php(1605): call_user_func_array()
#8 /.../api/coinbase/internal/fetchCurrencies.php(21): ccxt\Exchange->__call()
#9 /.../api/coinbase/scripts/Launcher-Currencies.php(15): FetchCurrencies()
#10 {main}
  thrown in /.../ccxt/php/Exchange.php on line 1609

### Code

```
      // execute request
    $result = $exchange->fetchCurrencies();

```

**Comment by pcriadoperez** [comment]
Hi @madelmann , for me it does seem to be working. Have you tried instead `fetch_currencies` ?

**Comment by pottertech** [comment]
Getting something similar.  Not sure why this is happening on Coinbase.

Operating System

Ubuntu 20.04

Programming Languages

PHP v8.2.23

CCXT Version

4.1.74

Description:

PHP v8.2.13
CCXT v4.1.74
PHP Fatal error:  Uncaught ccxt\ExchangeError: extend method not found, try underscore_notation instead of camelCase for the method being called in /root/ccxt/php/Exchange.php:1608
Stack trace:
#0 /root/ccxt/php/Exchange.php(1383): ccxt\Exchange->__call()
#1 /root/ccxt/php/Exchange.php(4109): ccxt\Exchange->fetch()
#2 /root/ccxt/php/Exchange.php(4113): ccxt\Exchange->fetch2()
#3 /root/ccxt/php/abstract/coinbase.php(200): ccxt\Exchange->request()
#4 /root/ccxt/php/coinbase.php(1139): ccxt\abstract\coinbase->v2PublicGetCurrencies()
#5 /root/ccxt/php/coinbase.php(1158): ccxt\coinbase->fetch_currencies_from_cache()
#6 /root/ccxt/php/Exchange.php(1558): ccxt\coinbase->fetch_currencies()
#7 /root/ccxt/php/coinbase.php(2100): ccxt\Exchange->load_markets()
#8 /root/testsell.php(27): ccxt\coinbase->create_order()
#9 {main}
  thrown in /root/ccxt/php/Exchange.php on line 1608

TEST Program:

<?php
chdir('/root');
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/ccxt/ccxt.php';
date_default_timezone_set('UTC');

echo 'PHP v' . PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION . '.' . PHP_RELEASE_VERSION . "\n";
echo 'CCXT v' . \ccxt\Exchange::VERSION . "\n";

$exchangeId = 'coinbase';
$exchangeName = '\\ccxt\\' . trim(strtolower(trim($exchangeId)));

$exchange = new $exchangeName (array (
    'apiKey' => 'ADD API KEY',
    'secret' => 'ADD SECRET KEY',
    'timeout' => 10000,
    'enableRateLimit' => true,
    'verbose' => true,
));

$type = 'market';
$side = 'sell';
$amount = 1.0;
$symbol = 'DOGE/USD';

$result = $exchange->create_order($symbol, $type, $side, $amount);
var_dump($result);

**Comment by pottertech** [comment]
I have reverted to version 4.1.30 and it is working well.

**Comment by carlosmiei** [comment]
@jayburston What's your exact PHP version?

**Comment by pottertech** [comment]
For me I only see it on Coinbase but I am also using Kraken and BinanceUS.

**Comment by madelmann** [comment]
I've just checked out an older version of CCXT (4.1.43) and everything is working again for me, so I'
m quite sure that it's not an error on my side. Actually the issue is not only related to Coinbase but also the Bybit implementation is affected (all functions, not only fetching currencies). I will now gradually update to newer versions and update this entry when I've tracked down the version where the bug has been introduced.

**Comment by pottertech** [comment]
> I've just checked out an older version of CCXT (4.1.43) and everything is working again for me, so I' m quite sure that it's not an error on my side. Actually the issue is not only related to Coinbase but also the Bybit implementation is affected (all functions, not only fetching currencies). I will now gradually update to newer versions and update this entry when I've tracked down the version where the bug has been introduced.

What command did you submit to pull CCXT (4.1.43) ?  I would like to test it as well to see if my issue goes away.

**Comment by madelmann** [comment]
> > I've just checked out an older version of CCXT (4.1.43) and everything is working again for me, so I' m quite sure that it's not an error on my side. Actually the issue is not only related to Coinbase but also the Bybit implementation is affected (all functions, not only fetching currencies). I will now gradually update to newer versions and update this entry when I've tracked down the version where the bug has been introduced.
> 
> 
> 
> What command did you submit to pull CCXT (4.1.43) ?  I would like to test it as well to see if my issue goes away.

Just do a git checkout with an old commit id. You may need to try some versions, or you could just pull the newest version which has it already fixed.
