### ISSUE TITLE
woo fetch_ohlcv not using since

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#20179]
### Operating System

Ubuntu 22.04

### Programming Languages

Python

### CCXT Version

4.1.71

### Description

Hi ! 
Here for a new issue :)
On woo, afaik, ccxt is not using the https://docs.woo.org/#kline-historical-data-public api point, but is using https://docs.woo.org/#kline-public

Which means that start time is not used, and so, since is not used.

Could this be changed please? Or am I doing something wrong?

Also, in woo.py ImplicitApi, I see that you have `v1PubGetHistKline` not used, but `v1PublicGetKline` is

Thanks a lot !

### Code

```
  

```

**Comment by samgermain** [comment]
> ### Operating System
> 
> Ubuntu 22.04
> ### Programming Languages
> 
> Python
> ### CCXT Version
> 
> 4.1.71
> ### Description
> 
> Hi ! Here for a new issue :) On woo, afaik, ccxt is not using the https://docs.woo.org/#kline-historical-data-public api point, but is using https://docs.woo.org/#kline-public
> 
> Which means that start time is not used, and so, since is not used.
> 
> Could this be changed please? Or am I doing something wrong?
> 
> Also, in woo.py ImplicitApi, I see that you have `v1PubGetHistKline` not used, but `v1PublicGetKline` is
> 
> Thanks a lot !
> ### Code
> 
> ```
>   
> ```

This is done intentially, because the one endpoint provides more up to date kline date, while the other provides data from old candlesticks

Ideally, they should still be included but there will need to be a conditional to check when the start date of the kline data is. if the start date is new enough, we should be using `https://docs.woo.org/#kline-public` if the start date is old (historical), then we should use this endpoint `https://docs.woo.org/#kline-public`

This of course becomes more complicated when we need both old (historical) data and more current ohlcv data (would require 2 calls properly)

If you think it's a good addition, I encourage you to take a look at implementing it though
