### ISSUE TITLE
mexc future

### ISSUE THREAD

**Issue by kiaxseventh** [ccxt/ccxt#20175]
Hello, I greatly appreciate your efforts.

I noticed that the future section for the mexc exchange has not yet been added.
[Mexc: set future and option to false](https://github.com/ccxt/ccxt/pull/19711)
Do you have any plans for this and is there a specific time?

**Comment by Dan-krm** [comment]
Hi @kiaxseventh future is set to false because mexc doesn't have delivery futures (what CCXT calls future).

Mexc does have perpetual futures (what CCXT calls swap) and since it's set to true you can expect it to be fully supported by CCXT.
```
delivery futures -> 'future': false
perpetual futures -> 'swap': true
```
As Sam mentioned mexc is undergoing maintenance for their perpetual futures API so some trading pairs and functionality might not be working as expected until their maintenance is finished

**Comment by arussellbishop** [comment]
MeXC spot - working for execution buy/sell ? Or NOT working ?

**Comment by carlosmiei** [comment]
@seeyoul8r still disabled on the exchange side.

**Comment by siamak** [comment]
any update?
