### ISSUE TITLE
Clarification stopLoss and takeProfit in createOrder SPOT markets

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#20233]
### Operating System

Linux 22.04LTS

### Programming Languages

JavaScript

### CCXT Version

4.1.65

### Description

Hello,

I'm seeking guidance on the optimal approach to integrate "stopLoss" and "takeProfit" functionalities when placing orders on SPOT markets. I primarily use the following exchanges: kraken, binance, bitget, coinbasepro, kucoin, and okx.

I found examples in the ccxt repository that seem to cater to okx and bitget specifically: [Link](https://github.com/ccxt/ccxt/blob/master/examples/js/create-order-position-with-takeprofit-stoploss.js)

My question is whether there is a universal approach that can be applied across all the mentioned exchanges. I'm considering the following option:

Place a buy order (limit).
Place two sell orders (limit) specifying the "takeProfitPrice" and "stopLossPrice".
Example (Not OCO orders):
```
symbol = 'ADA/USDT'
main_order = await binance.create_order(symbol, 'market', 'buy', 50) // Open position
tp_order = await binance.create_order(symbol, 'limit', 'sell', 50, 1.5, {"takeProfitPrice": 1.6}) // Take profit order
sl_order = await binance.create_order(symbol, 'limit', 'sell', 50, 0.24, {"stopLossPrice": 0.25}) // Stop loss order
```

Although I'm open to this approach, I have a couple of concerns:

Do I need to wait for the first order to be executed before placing the two sell orders?
Will the two sell orders "lock the amount of ADA" available, or is it possible to place a third limit sell (overriding the stoploss and takeprofit ones)?

Final clarification:
What's the relationship between "price" and "stopLossPrice" when placing a "limit sell order" (e.g., the 0.24 and the 0.25)? It's not clear to me how should I set the "price" field when creating an order with "stopLossPrice".

Your insights and examples would be highly appreciated.

Thank you!

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @fl0wo there is a unified approach for stop, stop loss and take profit orders using CCXT, you can read about it in the `Placing Orders` section of the manual. There can be some subtle differences between exchanges and these types of orders tend to be more focused on futures and swap trading, although there is spot implementations when the exchange supports it.

### 1. Do I need to wait for the first order to be executed before placing the two sell orders?
For spot you generally need to be holding the asset if you want to create a sell order, so you'd need the first order to be executed before placing the sell orders. Exchanges might vary in how they handle this and some might be more flexible, so you could always try and do some testing by creating a limit order then trying to create a stop order that triggers if the price drops even lower than your limit, and see what happens (you'd either create another open order or get an error message)

### 2. Will the two sell orders "lock the amount of ADA" available, or is it possible to place a third limit sell (overriding the stoploss and takeprofit ones)?
This sounds like it would be exchange specific and you could find the answer by testing creating orders on the exchange in question. I doubt a new order would automatically cancel your other stopLossTrigger and takeProfitTrigger orders if that's what you mean by override. But it might allow you to place the order and whichever order is triggered first it goes with. Although this might leave your other orders open unless you cancel them which could cause some problems. This might vary by exchange and you could test it by creating and canceling orders on the exchange you're curious about. You can also check your `total`, `free` and `used` balance by using the `fetch_balance` method on CCXT to see if there is any locked amounts after creating orders

### 3. What's the relationship between "price" and "stopLossPrice" when placing a "limit sell order" (e.g., the 0.24 and the 0.25)?
`stopLossPrice`, `takeProfitPrice`, `stopPrice` and `triggerPrice` are all trigger prices that trigger opening the order, and the `price` is the execution price of the order. So in your example when the market price drops to 0.25 (the trigger price) a new limit sell order will be created on the orderbook with a price of 0.24 (the order price)

I'd recommend reviewing the `Placing Orders` section of the CCXT manual:
https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

For working with spot markets, I'd probably stick to using trigger orders using the `triggerPrice` param if you want the order to be hidden from the orderbook until it's triggered. For spot markets using the triggerPrice is essentially the same as using the stopLossPrice or takeProfitPrice because there's no reduceOnly param and it might be supported in more places. If you don't care about the order being hidden until it's triggered you could just use limit orders since it will be supported everywhere and the easiest approach.
