### ISSUE TITLE
Problem with docs

### ISSUE THREAD

**Issue by markbell2410** [ccxt/ccxt#2054]
In OHLV Candlestick charts section. It seems some JS code has been mixed into the PHP example

// PHP
if ($exchange->has['fetchOHLCV'])
    foreach ($exchange->markets as $symbol => $market) {
        usleep ($exchange.rateLimit * 1000); // usleep wants microseconds
        var_dump ($exchange->fetch_ohlcv ($symbol, '1M')); // one month
    }

Should be

// PHP

if ($exchange->has['fetchOHLCV'])
    foreach ($exchange->load_markets() as $symbol => $market) {
        usleep ($exchange->rateLimit * 1000); // usleep wants microseconds
        var_dump ($exchange->fetch_ohlcv ($symbol, '1M')); // one month
    }

And also, the symbol in the fetch_ohlcv call works if you enter 1m (lower case M) as an argument. But is this 1 minute? I haven't managed to find any information on the functions in this library up to now

**Comment by kroitor** [comment]
> Should be
> foreach ($exchange->load_markets() as $symbol => $market) {

No, it shouldn't ) Because the section on loading markets is covering that much earlier.
The user is required to load markets before accessing them, so, in the following examples we do not add `load_markets` everywhere, because it should be clear from the Loading Markets section.

https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Instead the code in that snippet should be:

```PHP
$exchange->load_markets(); // this line is not duplicated everywhere in each snippet, it is omitted

// the code below is what remains as the most relevant part in that particular example (and it's correct):
if ($exchange->has['fetchOHLCV'])
    foreach ($exchange->markets as $symbol => $market) {
        usleep ($exchange->rateLimit * 1000); // usleep wants microseconds
        var_dump ($exchange->fetch_ohlcv ($symbol, '1M')); // one month
    }
```

> And also, the symbol in the fetch_ohlcv call works if you enter 1m (lower case M) as an argument. But is this 1 minute? I haven't managed to find any information on the functions in this library up to now

This is the standard commonplace designations for OHLCV timeframes. Lowercase `m` stands for *minutes*, uppercase `M` means *months*:

- `1m` – 1 minute
- `5m` – 5 minutes
- `1h` – 1 hour (60 minutes)
- `1d` – 1 day (24 hours)
- `1w` – 1 week (7 days)
- `1M` – 1 month (30 days)

Let us know if it does not answer your questions. Thx!
