### ISSUE TITLE
Bitget - create one-way mode orders with API V2

### ISSUE THREAD

**Issue by krasnyd** [ccxt/ccxt#20729]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.2.3

### Description

I want to create a market order with a one-way mode. When I try to use the standard `createOrder` function, the API is giving me an error:
`{"code":"40774","msg":"The order type for unilateral position must also be the unilateral position type."}`

The same error was already discussed in issue #19140 and the suggestion was to use the function `create_market_order` that calls the Bitget API V1 (https://bitgetlimited.github.io/apidoc/en/mix/#place-order). 
Is there some option for creating the same order with API V2? (https://www.bitget.com/api-doc/contract/trade/Place-Order)

### Code

```python
import os
import sys
import time
from asyncio import run
import logging
import ccxt

exchange = ccxt.bitget({
        'apiKey': '..',
        'secret': '...',
        'password': '...',
        'options': {
            'defaultType': 'swap',
        }
})

exchange.fetch_markets()
exchange.load_markets()

symbol = "IMX/USDT:USDT"
type = "market"
side = "buy" 
amount = 5

exchange.set_position_mode(False, symbol)
exchange.set_margin_mode('isolated', symbol)
exchange.set_leverage(10, symbol)

order = exchange.createOrder(symbol, type, side, amount, params={"marginMode": "isolated"})

```

**Comment by samgermain** [comment]
Could you share the result of `fetchPositions` please?

**Comment by Dan-krm** [comment]
Hey @krasnyd it looks like one-way mode orders don't work on bitget v2 if the `tradeSide` parameter is filled which is required for hedge mode orders. I opened a pull request that will allow you to set `"oneWayMode": true` in the createOrder params so that you can create one way mode orders without getting the unilateral error.

**Comment by jazzygit** [comment]
Hello, just want to say, that I have been struggeling for days to get the basic buy/sell working on bitget futures perpetual. **I gave up with ccxt as bitget** configuration requirements (margin, one way/ dual, ticket multiple names etc..) is so weird and because nothing worked for me. :/
Finally I could make it thanks to this projet:
https://github.com/BitgetLimited/v3-bitget-api-sdk/tree/master/bitget-python-sdk-api/bitget
Everyone can just understand the basic api call based on request for a simple version of buy/sell !

It turn out that I had to implement bybit, then kucoin, kraken and now bit get and for EVERY brooker I had problems and long hours of searchin/debugging !! 85% ~of API REST tested sample code on internet does not work :/
Why minimal example are not maintained by brookers.. that would make crypto trader life easier !

**Comment by roberlin** [comment]
Hi i have the same issue, but figured out it works from my gitpod dev but not worked from google func cloud. Possible the they have different servers with different versions and schemantic and messages are absoloet. Or they deactivated the google func servers not banned but the same errors. i get the same error if i want to place something without params like a limit order. the same code works in gitpod dev.

**Comment by Vasco0x4** [comment]
my code is from 4 months ago but is on my github in public. I am also available if you have any questions.

**Comment by mefplusx** [comment]
> Hello, just want to say, that I have been struggeling for days to get the basic buy/sell working on bitget futures perpetual. **I gave up with ccxt as bitget** configuration requirements (margin, one way/ dual, ticket multiple names etc..) is so weird and because nothing worked for me. :/ Finally I could make it thanks to this projet: https://github.com/BitgetLimited/v3-bitget-api-sdk/tree/master/bitget-python-sdk-api/bitget Everyone, from this great project, can just understand the basic api cals, based on request for a simple version of buy/sell !
> 
> It turn out that I had to implement bybit, then kucoin, kraken and now bit get and for EVERY brooker I had problems and long hours of searchin/debugging !! 85% ~of API REST tested sample code on internet does not work :/ Why minimal example are not maintained by brookers.. that would make crypto trader life easier !

100%!!! with private apis ccxt have so big troubles :(

**Comment by mefplusx** [comment]
> @mefplusx We're here to help, if you have any questions or are facing any issues with ccxt, please open a new github issue and we will take a look as soon as possible.

what about currenct issue?)

**Comment by carlosmiei** [comment]
@mefplusx By default, CCXT assumes you're in `one-way` mode, if you're in `hedged` mode (where you can hold both longs+shorts simultaneously for the same symbol) you just need to provide `hedged: true` in `params` upon creating an order and that's it.

**Comment by okay456okay** [comment]
> If anyone has the same problem, you can also simply go to the trading preferences of your Bitget app or website and change the position mode in your trading preferences to 'One-way mode'.

this works.  change preferences guideline: https://www.bitget.com/support/articles/12560603811572
