### ISSUE TITLE
PHP Notice:  Undefined index: WRC/BTC in /home/{user}/ccxt/php/liqui.php on line 317

### ISSUE THREAD

**Issue by forexhill** [ccxt/ccxt#2085]
PHP Notice:  Undefined index: WRC/BTC in /home/{user}/ccxt/php/liqui.php on line 317

Interestingly, the values for WRC/BTC still came through. Note this is Yobit retrieval.

    OS: Linux Ubuntu 17.10
    Programming Language version: PHP 7.1.11-0ubuntu0.17.10.1
    CCXT version: Version 1.10.1253 (trunk)
    Exchange: **YoBit**
    Method: standard retrieval of ask, bid, basevol, quotevol

**Comment by kroitor** [comment]
@forexhill can you please show your full verbose output according to this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ? That would be very helpful, I would be able to solve it quickly then. Don't edit it, if possible, just remove your keys from there, if any. Thx!

**Comment by kroitor** [comment]
@forexhill also, you really-really-really want to update your version of ccxt, as 1.10.1 is very old ;)

**Comment by forexhill** [comment]
@kroitor thanks. I just did git clone - I assume trunk is latest version? CHANGELOG shows this 1.10.1 - what is a better method for seeing latest revision ?

**Comment by forexhill** [comment]
I'll see if I can reduce the testcase

**Comment by kroitor** [comment]
> I just did git clone - I assume trunk is latest version?

If you did `git pull` after that – you can check your current version in `package.json` file in the root of the repo. The CHANGELOG is a little outdated, honestly.

**Comment by forexhill** [comment]
Git clone was of today, after the fixes made, so no `git pull` required.

package.json - 1.10.1253

**Comment by kroitor** [comment]
@forexhill got it, should be ok then. Still need your code and verbose output to get further. Standing by for more info from you.

**Comment by forexhill** [comment]
@kroitor btw just made $50 donation for you. Thank you again. Perhaps more later.

**Comment by forexhill** [comment]
Going to try and get testcase now

**Comment by forexhill** [comment]
Ok, I have established that the issue is sporadic. It happens on different pairs at different times.

`PHP Notice:  Undefined index: BLAZR/BTC in /home/{user}/ccxt/php/liqui.php on line 317`

It must be a particular situation that is not caught yet by ccxt.

**Comment by kroitor** [comment]
Looks like you're hitting a rate-limit, really.

First, you're not using any rate-limiting at all, which is very risky and may produce side-effects like those you see. To enable rate-limiting, you need to follow the Manual and examples:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/blob/master/examples/php/built-in-rate-limiting-poller.php

Add `array('enableRateLimit' => true)` to you constructor params:

```PHP
$exchange = new $exchange (array('enableRateLimit' => true));
```

↑ This will add the necessary delays between your requests, otherwise exchanges won't like it, when you're sending to much requests.

Second, this is absolutely not the way to go:

```PHP
        printf("%s%s%F%F%f%f\n",
         $exchange->id,
         $arbsymb,
         $exchange->fetch_ticker($arbsymb)["ask"],
         $exchange->fetch_ticker($arbsymb)["bid"],
         $exchange->fetch_ticker($arbsymb)["baseVolume"],
         $exchange->fetch_ticker($arbsymb)["quoteVolume"]
        );
```

Here ↑ you're fetching the same ticker four (!!!) times, to access its values, instead of fetching it just once... This will definitely hit the rate-limit of an exchange. In other words, you're accessing the exchange too frequently too soon.

Instead, it should be:

```PHP
        $ticker = $exchange->fetch_ticker($arbsymbol); // ←---- fetch it just once and save into $ticker
        printf("%s%s%F%F%f%f\n",
         $exchange->id,
         $arbsymb,
         $ticker["ask"], // ←---- access field of $ticker here without unnecessary fetching multiple times
         $ticker["bid"],
         $ticker["baseVolume"],
         $ticker["quoteVolume"]
        );
```

Third, you don't have any error handling around the fetch_ticker, so you need to surround it in try-catch as well...

```
    try {
        $ticker = $exchange->fetch_ticker($arbsymbol); // ←---- fetch it just once and save into $ticker
        printf("%s%s%F%F%f%f\n",
         $exchange->id,
         $arbsymb,
         $ticker["ask"], // ←---- access field of $ticker here without unnecessary fetching multiple times
         $ticker["bid"],
         $ticker["baseVolume"],
         $ticker["quoteVolume"]
        );    
    } catch (Exception $e) {
        print_r ($e);
    }
```

And so on... Basically, most of the errors in that code snippet are tied to your skills in PHP. You need to learn more about variables, sending http requests from php, how cURL works, etc...

Let me know if it does not help.

**Comment by forexhill** [comment]
Wow, what a detailed reply. Thank you and understood. 

Btw, as most of the code (but not the one you highlighted) is from the arbitrage php example in examples/php, it may be good to add the `enableRateLimit` to that one too.

**Comment by forexhill** [comment]
@kroitor side question - is it possible to get the details for several coins at the same time? Yobit v3 API allows this - up to 61 pairs per combined call.

**Comment by kroitor** [comment]
@forexhill yes, you need to use another method of the unified family: fetchTickers instead of fetchTicker (note the difference in plural "s" ending). The fetchTickers method accepts an array of symbols you want to fetch from Yobit and it will return an array of requested tickers by symbol.

```PHP
// do not forget to add the necessary error handling
$exchange = new $exchange (array('enableRateLimit' => true));
$exchange->load_markets();
$symbols = array ('ETH/BTC', 'BCH/BTC', 'BTC/USD'); 
$exchange->fetchTickers ($symbols);
```

More about it:

- https://github.com/ccxt/ccxt/wiki/Manual#all-at-once
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Let me know if you have difficulties with it.
