### ISSUE TITLE
totalAvailableBalance returns empty string even if accountType is UNIFIED

### ISSUE THREAD

**Issue by pastanorm** [ccxt/ccxt#20948]
### Operating System

Ubuntu

### Programming Languages

JavaScript

### CCXT Version

4.2.15

### Description

I'm fetching result using fetchBalance but totalAvailableBalance returns empty string even if accountType is UNIFIED.
I upgraded accountType from CONTRACT to UNIFIED.
Here's fetch result.

### Code

```
{
    "totalEquity": "56.91663832",
    "accountIMRate": "",
    "totalMarginBalance": "",
    "totalInitialMargin": "",
    "accountType": "UNIFIED",
    "totalAvailableBalance": "",
    "accountMMRate": "",
    "totalPerpUPL": "5.9584504",
    "totalWalletBalance": "50.95818792",
    "accountLTV": "",
    "totalMaintenanceMargin": "",
    "coin": [
        {
            "availableToBorrow": "",
            "bonus": "0",
            "accruedInterest": "0",
            "availableToWithdraw": "39.4074047",
            "totalOrderIM": "0",
            "equity": "56.9314405",
            "totalPositionMM": "0.4702608",
            "usdValue": "56.91663832",
            "unrealisedPnl": "5.96",
            "collateralSwitch": true,
            "spotHedgingQty": "0",
            "borrowAmount": "0",
            "totalPositionIM": "11.5640358",
            "walletBalance": "50.9714405",
            "cumRealisedPnl": "0.114117",
            "locked": "0",
            "marginCollateral": true,
            "coin": "USDT"
        }
    ]
}
```

**Comment by Dan-krm** [comment]
Hi @pastanorm those are exchange specific values that are returned that we can't really control. That's why it's generally recommended to work with the unified response if possible that shows the free, used, total and debt balances for all of the currencies you hold. If you look at the bybit documentation https://bybit-exchange.github.io/docs/v5/account/wallet-balance the totalAvailableBalance equals: `totalMarginBalance - totalInitialMargin` both of those values are also empty for you so that could be why totalAvailableBalance is empty.

I'd recommend transferring funds between your funding and unified trading account on the bybit website, maybe making some orders and recreating your API keys ensuring you have all the correct permissions selected and see if any of those actions help populate the totalAvailableBalance for you. Other than that there's not much we can do because that's an exchange specific value returned by bybit not a unified response that we can control. I'd recommend reading the linked documentation for more information on this specific endpoint and maybe reaching out to bybit if you need more clarification.

I feel like depending on what you're using the value for the totalEquity value might be more useful for you than the totalAvailableBalance, you can read the documentation to see if that's the case

**Comment by Dan-krm** [comment]
Closing this issue now, feel free to reopen it if you have any other related questions or issues.
