### ISSUE TITLE
CCXT filters out some Binance non-pm positions

### ISSUE THREAD

**Issue by VadymPoliak** [ccxt/ccxt#21115]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.1.58

### Description

When I fetched positions for Binance non-pm accounts, some positions were missing. I used fetch_account_positions(params={"type": "future"}) to get positions and it returned partial positions. I tried with fapiprivatev2_get_account method and the exchanged returned the full positions.

### Code

```
  fetch_account_positions(params={"type": "future"})

```

**Comment by samgermain** [comment]
What do you mean by non-pm accounts?

**Comment by VadymPoliak** [comment]
non portfolio margin accounts

**Comment by carlosmiei** [comment]
@VadymPoliak Right now, portfolio margin support is a work in progress. We expect to finish it soon

**Comment by Dan-krm** [comment]
@VadymPoliak could you share your partial response calling `fetch_Account_positions` and the complete response calling the endpoint directly? It might also help if you could share the verbose output `exchange.verbose = true`

The params should be the second argument in that method, the first argument is a list of symbols or None:
```python
fetch_account_positions(None, params={"type": "future"})
```
Also it would be worth it to update your version of CCXT and seeing if that helps resolve the issue for you since you're using a fairly old version.

**Comment by VadymPoliak** [comment]
[fapiprivatev2_get_account.txt](https://github.com/ccxt/ccxt/files/14189971/fapiprivatev2_get_account.txt)
[fetch_account_positions.txt](https://github.com/ccxt/ccxt/files/14189972/fetch_account_positions.txt)

I attached example data.

fapiprivatev2_get_account always returns full positions (13 non-zero initial margin positions) but fetch_account_positions sometimes returns partial positions (2, 8, 9, 11, etc). I think there's an issue in filtering positions according to market symbols ccxt fetched prior to fetch_account_positions.

**Comment by VadymPoliak** [comment]
And I upgraded CCXT to 4.2.36 but it didn't solve this issue.

**Comment by VadymPoliak** [comment]
@Dan-krm , @carlosmiei @samgermain  any suggestions?

**Comment by Dan-krm** [comment]
@VadymPoliak it looks like binance returns quite a few empty positions where all of the values are zeroed out in the exchange response, there is probably an issue with the `parseAccountPositions` helper method filtering out some of the positions that you want to see. I'm going to open a pull request soon adding portfolio margin support to the fetch positions methods, I'll see if I can resolve this issue at the same time.

**Comment by VadymPoliak** [comment]
@Dan-krm . It's not a portfolio margin account. And binance returns about 275 positions but we have 13 positions with non-zero initial margin. But CCXT removes some of them.

**Comment by Dan-krm** [comment]
@VadymPoliak could you share the entire verbose ResponseBody of your call to `fapiPrivateV2GetAccount`? In the text file you shared it looks like you only have the positions array but in CCXT's parser there is a comparison with the assets array that might be the reason for some of the positions being removed. I plan on testing and seeing if I can fix the parser using your data if possible.

**Comment by VadymPoliak** [comment]
@Dan-krm . I am having trouble to get whole verbose response because I can only run it on the server. I think I can get fapiPrivateV2GetAccount response. Is it enough for you?

**Comment by Dan-krm** [comment]
@VadymPoliak yeah I think so I'm just looking for your entire response from this endpoint if possible:
https://binance-docs.github.io/apidocs/futures/en/#account-information-v2-user_data
including both the assets and positions arrays

**Comment by VadymPoliak** [comment]
[fapiPrivateV2GetAccount.txt](https://github.com/ccxt/ccxt/files/14204781/fapiPrivateV2GetAccount.txt)

**Comment by VadymPoliak** [comment]
@Dan-krm . Please check it is what you want

**Comment by Dan-krm** [comment]
@VadymPoliak yeah that should work thanks. It might take me a bit of time to work through this since our fetch position related method implementations on binance are a bit complicated but I'll let you know within the next day or two of any progress

**Comment by VadymPoliak** [comment]
Thx. @Dan-krm

**Comment by VadymPoliak** [comment]
any updates? @Dan-krm

**Comment by Dan-krm** [comment]
Hi @VadymPoliak I parsed your exchange response into a json file and did some testing in javascript and python:
[fapiPrivateV2GetAccount.json](https://github.com/ccxt/ccxt/files/14226283/fapiPrivateV2GetAccount.json)

The fetchAccountPositions method is working as expected for me and returning all of the positions.
A pull request was merged so that the empty positions aren't returned in the CCXT response for fetchAccountPositions.
There is a few notes on fetchAccountPositions:
- When calling swap or future related methods it's currently recommended to use the binanceusdm or binancecoinm classes instead of the binance class
- In fetchAccountPositions the different endpoints that are used are split between `"subType":"linear"` and `"subType":"inverse"`
- According to the CCXT unification `"type":"future"` is for delivery futures and `"type":"swap"` is for perpetual futures

You can call the fetchPositions method and set the `"method"` param to `"method":"positionRisk"`, `"method":"account"` or `"method":"option"`, positionRisk is the default, if you set it to account it will call fetchAccountPositions:
```
node examples/js/cli binanceusdm fetchPositions undefined '{"method":"account","subType":"linear"}'
```
```
python3 examples/py/cli.py binanceusdm fetchPositions None '{"method":"account","subType":"inverse"}'
```

I did some extensive testing and everything seems to be working properly and I wasn't able to recreate your issue, if you want some more help you can share your verbose output and I can take a closer look:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by VadymPoliak** [comment]
![image](https://github.com/ccxt/ccxt/assets/132665145/3a701c14-f98e-4f35-8fb1-80985b9428ec)
partial positions happens often, not always as you can see in the screenshot. I have called the method as soon as the server returns partial positions but ccxt returned normal positions. Hard to reproduce that issue.

**Comment by VadymPoliak** [comment]
@Dan-krm . FYI

**Comment by Dan-krm** [comment]
@VadymPoliak thanks for the information, this seems like a bug on the exchange API side of things and the best we can do is report the inconsistency to binance
