### ISSUE TITLE
EXMO - create_market_buy_order() parameters problem

### ISSUE THREAD

**Issue by vvinni** [ccxt/ccxt#2132]
OS: Windows 7
Programming Language version: Python 3.6
CCXT version: 1..11.10
Exchange: EXMO
Method: create_market_buy_order()

@kroitor Unfortunately I was too tired to understand what happened.

In my bot, if the last price is below some point, I open a market order if it is above that point and below another reference I use a limit order...

Yesterday, I copied the wrong method when I created this post even though I was doing the right thing.

The errors described above was happening on this line of code:

`compra = self.conn.create_market_buy_order(PAR, volume)`

the error:

`exmo {"result":false,"error":"Error 50049: Parameter is not a number 'price'"}
`
Can you help?

**Comment by kroitor** [comment]
@vvinni unfortunately, Exmo requires a price argument for all orders, even for market orders. So, it should be `compra = self.conn.create_market_buy_order(PAR, volume, price)`
I've added a warning message stating that. Please, don't forget to update ccxt to version 1.11.24 (in 5-10 minutes). 
Hope it helps. Thx!

**Comment by kroitor** [comment]
@vvinni sorry, my previous answer is a mistake, after doing some testing, i turns out that they will accept market orders without a price, thus, you need to update to 1.11.25 (in 5-10 minutes, again), and use your old code, it should work now. Let us know if you have difficulties with it. Thank you!

**Comment by vvinni** [comment]
@kroitor no man... my mistake... I asked the wrong question with the wrong method.

Thank you very much for the rapid reply! 

Today when I got home I will update the lib and try again... I let you know...

Thank you! 

Awesome work!

**Comment by kroitor** [comment]
@vvinni you would make it a little easier for me to help you, if you copied the entire verbose output as described here https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue (without your keys, of course)

**Comment by kroitor** [comment]
Add this line just before the call to self.conn.create_limit_buy_order:

```Python
self.conn.verbose = True  # ←---- this one
compra = self.conn.create_limit_buy_order(PAR, volume, preco)
```

Then post the output here without your keys )

**Comment by vvinni** [comment]
@kroitor sorry man! 

Here we go:

> Request: POST https://api.exmo.com/v1/order_create {'Content-Type': 'application/x-www-form-urlencoded', 'Key': '******', 'Sign': '******', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} nonce=1520467508051&pair=USDT_USD&quantity=46.1744&type=limitbuy&price=1.021

> Response: POST https://api.exmo.com/v1/order_create 200 {'Server': 'nginx', 'Date': 'Thu, 08 Mar 2018 00:05:12 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Key, Sign', 'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT, DELETE', 'Strict-Transport-Security': 'max-age=604800', 'Content-Encoding': 'gzip'} {"result":false,"error":"Error 50302: Wrong order type"}

**Comment by vvinni** [comment]
@kroitor thank you very much!

Things are working properly here!

Excelent work!

Thank you!

**Comment by Akhtem** [comment]
Can someone help me? I Use C# apiExmo . And there are methods with Dictionary<string,string> .
But when I try to create order  I get error ""{\"result\":false,\"error\":\"Error 50049: Parameter is not a number 'price'\"}"" . As i understood it's because of <string,string> .     I must put number , not "number".

**Comment by kroitor** [comment]
@Akhtem unfortunately, we can't help on C# apiExmo. We can help with the CCXT though. In your case, I think, you should address your question to the creators of the C# apiExmo. Most likely, the signature of the method wants you to put a numeric string into the params –  use `"123"` (in quotes) instead of `123`.

**Comment by Akhtem** [comment]
Yes , you are right . I tried to put.  
decimal price = 5.555;
<string , price.ToString()>   
And after this i got an error. But when i wrote 
Convert.ToString(price, CultureInfo.InvariantCulture); instead of price.ToString(); . It's okey.
