### ISSUE TITLE
Bittrex error handling

### ISSUE THREAD

**Issue by rdbr** [ccxt/ccxt#2137]
When calling an API function and there is an error, `throwExceptionOnError` gets called in the `request` function. If the error is unknown, no exception is thrown and the `request` function returns nothing, so response will be undefined.

I suggest to throw `ExchangeError` after the `throwExceptionOnError` returns, just like in `handleErrors`.

**Comment by kroitor** [comment]
> I suggest to throw ExchangeError after the throwExceptionOnError returns, just like in handleErrors.

We can't do that unfortunately, because most often it's a recoverable ExchangeNotAvailable error... In order to fix it somehow, we need to see your verbose output and the code to reproduce it. We might add some handling for a yet-unknown error, if you could show it to us, Bittrex docs are very poor.

Hope it answers your question.

**Comment by rdbr** [comment]
The problem is that nothing is returned on unknown errors, I can only check if the return value is undefined.

My error is not really that important, because it is about the future unknown errors, but here is such an error when nothing is returned or thrown, while status is 200:
`{"success":false,"message":"INVALID_CURRENCY","result":null}`

I think it is better to at least throw some kind of error, so the error can be handled by the client.
