### ISSUE TITLE
Function similar to bybit

### ISSUE THREAD

**Issue by kartun83** [ccxt/ccxt#21423]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

There is a function at bybit own implementation set_trading_stop. 
https://bybit-exchange.github.io/docs/v5/position/trading-stop
It looks very helpfull

### Describe the solution you'd like

Similar function in ccxt

### Describe alternatives you've considered

Manually create orders using create_stop_loss_order / create_take_profit_order
This function require side definition, but bybit doesn't

**Comment by Dan-krm** [comment]
Hi @kartun83 I've opened a pull request that once merged will allow you to set the createOrder method option to `'privatePostV5PositionTradingStop'` when instantiating the bybit exchange class, so that you can use `create_stop_loss_order / create_take_profit_order` with the endpoint that you specified
