### ISSUE TITLE
Invalid nonce (has already been used)

### ISSUE THREAD

**Issue by forexhill** [ccxt/ccxt#2153]
Hi @kroitor! Any reason I would get an invalid nonce (already used) error? The php program is single threaded, and just does a few trades ($exchange->create_order) in close succession, then pauses for a while to ratelimit. Also, any way to set the nonce manually before a transaction?

- OS: Ubuntu 17
- Programming Language version: PHP 7.1
- CCXT version: very latest (fresh trunk pull from few hours ago)
- Exchange: Yobit
- Method: Few $exchange->create_order trading calls close together

ccxt\ExchangeError: yobit unknown "error" value => {"success":0,"error":"invalid nonce (has already been used)"} in /home/{user}/ccxt/php/liqui.php:736
Stack trace:
#0 /home/{user}/ccxt/php/Exchange.php(894): ccxt\liqui->handle_errors(200, '', 'https://yobit.n...', 'POST', Array, '{"success":0,"e...')
#1 /home/{user}/ccxt/php/Exchange.php(751): ccxt\Exchange->fetch('https://yobit.n...', 'POST', Array, 'nonce=152041512...')

**Comment by kroitor** [comment]
@forexhill hi! Can you please post a minimal snippet of code to reproduce the problem and your verbose output of it? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
Need a small, but a complete snippet from you, so that I could copy it and run in my environment... I mean, the entire program, not a line or two of it, but, please, remove everything that isn't absolutely necessary for repeating the problematic case. Most often these problems arise due to disabled rate limiting.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

**Comment by forexhill** [comment]
Hmm. Just had it again 
PHP Fatal error:  Uncaught ccxt\ExchangeError: yobit unknown "error" value => {"success":0,"error":"invalid nonce (has already been used)"} in /home/{user}/ccxt/php/liqui.php:736

Is the nonce build on unix timestamp and as such if two trx are in one second it can fail?

**Comment by forexhill** [comment]
I cannot sent code for this one sorry.

**Comment by forexhill** [comment]
It also seems to happen with the $exchange->create_order (a few directly in a row) only whereas it have not seen it happen yet with $exchange->fetchTicker (also a few directly in a row)

**Comment by forexhill** [comment]
Think it is this; when there are multiple calls in the same second (is second resolution used for nonce?). If so, then perhaps we can add a suffix from a nanosecond timer or something?

**Comment by forexhill** [comment]
Another idea is to read it from a file or variable

**Comment by kroitor** [comment]
@forexhill 

> Is the nonce build on unix timestamp and as such if two trx are in one second it can fail?

Yes, by default, however...
 
> If so, then perhaps we can add a suffix from a nanosecond timer or something?

First, we already have a way of overriding the nonce: https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce. Second, the nonce for yobit is defined in milliseconds by default. So, you should just enable the rate limiting (add `array('enableRateLimit' => true)` as shown in this example: https://github.com/ccxt/ccxt/blob/master/examples/php/built-in-rate-limiting-poller.php

Without the code it's really hard to guess, unfortunately.

Let us know if the above does not help. Thx!

**Comment by forexhill** [comment]
@kroitor so I already had the ratelimiter enabled, had set the ratelimit to 605ms (which should stay just under the 100 requests/min max for Yobit) AND was inserting another usleep($exchange->rateLimit*1000); after each exchange call. So, 1) from the example it would seem there is no need to do the usleep? 2) so how can we possibly have these nonce failures at all?

**Comment by forexhill** [comment]
Also, https://github.com/ccxt/ccxt/wiki/Manual still has usleep as well in example code, FYI

**Comment by kroitor** [comment]
> So, 1) from the example it would seem there is no need to do the usleep? 

Yep, no need for usleep.

> 2) so how can we possibly have these nonce failures at all?

It's very hard to tell without seeing your actual code, I mean, it is obviously due to an error in the logic of the script you're running, but I can't guess what it might be, without actually seeing it... If you could do some homework and reduce the error case to the small sample, you will most likely find the error yourself (think: I wouldn't ask otherwise).

> Also, https://github.com/ccxt/ccxt/wiki/Manual still has usleep as well in example code, FYI

Yes, it does. You either enable the built-in rate limiter or you call `usleep` or `sleep` by hand – whatever you choose, but you **don't want to use both at the same time**.

**Comment by forexhill** [comment]
Oh I trust that you would not ask unless it was needed, sorry. It's just that it would be very hard to reduce this to a simple script and even more so because it involves actual trading functions (the rest works fine). It would seem it is a regression. I think I can prove that too by running with an older version of ccxt and seeing if it happens again.

**Comment by kroitor** [comment]
> It's just that it would be very hard to reduce this to a simple script and even more so because it involves actual trading functions (the rest works fine).

This is the key – you just stated it yourself. Yes, it will be hard, and **that's the whole point of doing it!** I mean, if it would be easy, I would answer right away. So, debugging is what makes programming hard. But you have to get used to to do it willingly and frequently, otherwise you'll spend months solving problems, which is not something you want, obviously. So, whenever you need to debug anything, it will always boils down to some hard unwanted work that **has to be done** to isolate the problem and fix it. It never happens the other way )

**Comment by forexhill** [comment]
Thank you :)

**Comment by kroitor** [comment]
@forexhill i'm really sorry for not being able to help you more with this... hope for your understanding, without seeing at least some code from you and being able to tweak it myself, I'm practically blind and I don't have any option better than... uhm... a blind guess.

**Comment by forexhill** [comment]
It is I who should have done more :)

**Comment by forexhill** [comment]
Also see #2163
