### ISSUE TITLE
Kraken conflicting symbol 'REP/USD'

### ISSUE THREAD

**Issue by Rickkert00** [ccxt/ccxt#22056]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.2.89

### Description

On kraken, there exist two versions of the REP token: REP and REPV2. In older ccxt versions (4.2.47), the symbol REP/USD would map to REPV2/USD on kraken, and symbol REPV1/USD would map to REP/USD on kraken. However after updating, it seems that REPV1/USD symbol is no longer supported in ccxt, as both kraken markets REPV2/USD and REP/USD are now linked to ccxt symbol REP/USD. 

I am not sure how to access each market seperately now. 

### Code

```
import ccxt
kr = ccxt.kraken()
mkts = kr.load_markets()
# in mkts, only REP/USD is present. How do i access both REP/USD and REPV2/USD?

```

**Comment by sc0Vu** [comment]
@Rickkert00 the issue is related to ccxt/ccxt#21112, with the patch merged the currency code would be changed if it's in the reverse order. Will fix this.

**Comment by ttodua** [comment]
Recently there was merged a PR that fixed the issue for commonCurrencies. with regard to kraken, i am not fully sure where the problem lies at this moment, because when I looked into  currencies ( https://api.kraken.com/0/public/Assets ) or markets ( https://api.kraken.com/0/public/AssetPairs ), I nowhere see `REP` currency anymore, there are `REPV2` and `XREP` (which has 'altname' `REP` but altnames are not read &used in ccxt). So, there should not be a problem, as ccxt has such mapping in `commonCurrencies`:
```
'REPV2': 'REP',
```
so, when you'll want to interact with `REPV2/USD` market on kraken, with ccxt you'll be able to refer it with `REP/USD`.

and as mentioned above, there is also `XREP/USD` market. if you want to change that currency code, you can add smth like:
```
'XREP': 'REPV1'
```
so, you can then refer with `REPV1/USD` instead of `XREP/USD`

**Comment by ttodua** [comment]
The only issue that is present now in kraken, is that it has now-obsolete `'REP': 'REPV1',` which I'll push to be removed

**Comment by ttodua** [comment]
after the PR is merged and this issue autoclosed, you can update ccxt and it would have solved the problem. 
so, as seen in upcoming PR: https://github.com/ccxt/ccxt/pull/22067/files#diff-d577c74f7dbeddac30dac13c4097bf0aa9338629f0e3ae3a43677d980f80a24cR224

We will use this mapping:
```
                'REPV2': 'REP',
                'XREP': 'REPV1',
```

**Comment by ttodua** [comment]
wait, the problem seems deeper, this needs a while to fix the architecture.

**Comment by sc0Vu** [comment]
@ttodua I used that but it didn't work. With 'REPV2': 'REP' setting, REPV2 would change to REP, but REPV1 wold change (because the code of REPV1 is REP). That's why I remove 'REPV2': 'REP', it would change symbol to REPV1/USD and REPV2/USD.

**Comment by ttodua** [comment]
@sc0Vu i have made a PR on top of your PR, please take a look in: https://discord.com/channels/690203284119617602/1226127078823428106 it would fix everything

**Comment by ttodua** [comment]
ok, problem was detected and fix is on the way. when new ccxt package is published (probably within 5-8 hours from now) you should update and retest. the problem should be gone and you can use:
```
'REPV2': 'REP',
'REP': 'REPV1'
```
or whatever you like

**Comment by carlosmiei** [comment]
@Rickkert00 Can you update your ccxt version and check if the issue is resolved now, please?

**Comment by Rickkert00** [comment]
Thanks for the quick fix guys! After updating, the issue is fixed :)
