### ISSUE TITLE
[BITMART] No actual networks information for "fetch_deposit_withdraw_fee()"

### ISSUE THREAD

**Issue by alekseyiovchev** [ccxt/ccxt#22124]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

ccxt-4.2.94

### Description

Hello. I am trying to fetch network + fee from BitMart, using `bitmart.currencies` got me null values in dict, and `bitmart.fetch_deposti_withdraw_fee('ETH')` for example got me empty networks dict. I am using apikey,etc. I was asking BitMart support for help,but they told me to ask you,cause I am using your lib(ccxt)

### Code

```
bitmart = ccxt.bitmart(apiKey,secret,uid)
bitmart.fetch_deposit_withdraw_fee('ETH')

OUTPUT:
{"info": {"today_available_withdraw_BTC": "100.0000", "min_withdraw": "0.01", "withdraw_precision": "8", "withdraw_Precision_GeTen": null, "withdraw_fee": "0.002"}, "withdraw": {"fee": 0.002, "percentage": null}, "deposit": {"fee": null, "percentage": null}, "networks": {}}

```

**Comment by carlosmiei** [comment]
Hello @alekseyiovchev,

The problem is that bitmart does not seem to provide the networks information in the API, these are the endpoints we use for fetchCurrencies/fetchDepositWithdrawFee and as you can't see, the information is not there, 

https://developer-pro.bitmart.com/en/spot/#get-currency-list-v1
https://developer-pro.bitmart.com/en/spot/#get-deposit-and-withdraw-history-keyed

**Comment by carlosmiei** [comment]
@alekseyiovchev In this case, I think you can assume that if the exchange only returns 1 fee that represents the native chain fee, in this case ETH

**Comment by alekseyiovchev** [comment]
@carlosmiei thanks for fast response, have a good day!

**Comment by sench93** [comment]
for fetchCurrencies isn't this endpoint better ?

https://developer-pro.bitmart.com/en/spot/#get-currencies
