### ISSUE TITLE
fetchTrades params argument

### ISSUE THREAD

**Issue by akel94** [ccxt/ccxt#2218]
Is the params argument in fetchTrades still under experimental stage?

I'm quite having a hard time in fetching trades for a specific exchange but only getting the sell or buy side.

I'm currently using 

exhange.fetchTrades(symbol,params={'side':'sell'})

but it always says
 {"msg":"Not all sent parameters were read; read '1' parameter(s) but was sent '2'.","code":-1104}

**Comment by kroitor** [comment]
> Is the params argument in fetchTrades still under experimental stage?

No, it isn't. It is supported and should be working and should be used for overriding exchange-specific params of a http request.

> I'm quite having a hard time in fetching trades for a specific exchange but only getting the sell or buy side.

This is because you are misunderstanding the purpose of `params`. It is for **exchange-specific** params, unique for each specific exchange, and you can't just make up any param you want, like `{'side':'sell'}`, because there's no such exchange-specific parameter as `side` at all. To find which params are supported by this or that exchange, you need to consult the docs for your specific exchange. CCXT users will normally not use the exchange-specific `params` in calls to `fetchTrades()` method at all. If you want to find more details on the unified API in ccxt, the arguments and parameters, and their meaning, please consult the Manual, here: https://github.com/kroitor/ccxt/wiki/Manual

If you want to filter the trades by `'side' = 'sell'`, you fetch them and then *filter by side on your side*, lol ))

Unfortunately, you've missed to specify your programming language and the exchange in question. So, here's a brief example on how you would do that:

```Python
# Python
trades = exchange.fetch_trades(symbol)
sells = [trade for trade in trades if trade['side'] == 'sell']
```

```JavaScript
// JavaScript
const trades = await exchange.fetchTrades (symbol)
const sells = trades.filter (trade => trade.side === 'sell')
```

Let us know if it does not answer your question. Thx!

**Comment by akel94** [comment]
My apologies. Python is the language. 

That's what I'm actually doing right now. I'm fetching all the trades and I let my program filter the buy and sell. I just wondered if it is possible to obtain a specific side per fetchTrade query, to save computing times. Because that would save me half of the computing time. Anyways, you've answered my question. Thanks a bunch!
