### ISSUE TITLE
Gemini exchange lacking features

### ISSUE THREAD

**Issue by wmturner** [ccxt/ccxt#2220]
I was wondering if there is a reason the Gemini exchange is so lacking in features in comparison to most others in CCXT?

https://github.com/ccxt/ccxt/blob/master/python/ccxt/gemini.py

Reviewing the API documentation shows much more is supported than what is currently present.

**Comment by kroitor** [comment]
> I was wondering if there is a reason the Gemini exchange is so lacking in features in comparison to most others in CCXT?

Yes, there is ) Most of my time goes answering this type of questions instead of actually adding the missing features. I mean, c'mon, you could've thought about it a little more and could've come up with an answer yourself, as it is obvious: the only possible reason for any such thing is not our unwillingness, but a simple lack of time, of course. It's that simple ))) No offence )

Now, having said that, we will be happy for any help and we appreciate all contributions! ;) Your pull-requests are welcome )

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#pending-tasks

Also, for the same reason as explained above, there's no point in reporting what's missing, as we're well aware. The task is big, and apart from a few active contributors, most activity is about questioning like "when will this or that be ready?" or "why isn't it there yet?". Unfortunately, these questions don't really help solving the task.

Hope it answers your question and for your understanding. Thx! )

**Comment by wmturner** [comment]
Thanks for the feedback, I did not intend for my request to come off that way, just wanted to make sure.  I believe there was a period of time where Gemini's API was impacted and certain functionality disabled, and was wondering if this was related was all. 

I need this functionality and will be adding.  I'm not the best JS programmer, but will do my best to add per docs and contribute back via PR.

Thanks!
-Will

**Comment by kroitor** [comment]
@wmturner I didn't mean to scare you away ) Sorry if it was a little too straight )) We're still friendly and open to all suggestions and proposals. Thx again! We will be happy to see a PR from you.

**Comment by wmturner** [comment]
No worries, I understand how it goes.  I have my fork plugged into Travis,
and will be working on adding a few methods.  I've been looking a bit into
various WebSocket API's for a few exchanges and can give that a shot as
well.

Thanks for all the hard work!

**Comment by kroitor** [comment]
@wmturner 

> I've been looking a bit into
various WebSocket API's for a few exchanges and can give that a shot as
well.

You might want to check these two links on WS then:

- #56 
- https://gist.github.com/kroitor/aabecc346a5bded6ead7a82205d8ffc1

Let us know if you have any questions with it! Thx!

**Comment by wmturner** [comment]
Good read, I think I agree with most of your points.  Will be in touch.
Thnx!
