### ISSUE TITLE
Internal errors are not visible in my code. C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22297]
### Operating System

Windows 10

### CCXT Version

4.3.6

### Description

When something happens inside ccxt threads I never see it.
I can only catch by using the debug version of ccxt from the source code.
I think I should be able to be notified about internal errors.

Public error delegate is good thing for pushing such messages.

For example this issue https://github.com/ccxt/ccxt/issues/22037 show nothing, but has important information inside.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @skuvv, thanks once again for bringing our attention to this.

Our current approach is to bubble up internal exceptions to the user (that's how we do in the other languages) but since c# is a bit different we might still have some unexpected behaviors. I will let you know if I find something.

Just to make it clear, basically, you're saying that on the WS side, when there's an issue, you never see it explicitly, right?

**Comment by skuvv** [comment]
@carlosmiei yes, correct.
But this also actual for all internal errors not only for WS

**Comment by ttodua** [comment]
late reply here, I'll post an update within 24 hours

**Comment by ttodua** [comment]
@skuvv I had a delay, I am still looking into this problem, hard to intercept but i would have some thoughts on this

**Comment by skuvv** [comment]
@ttodua thanks

**Comment by Santas** [comment]
Does this still cause issues?

**Comment by ttodua** [comment]
@skuvv I am sorry for missing to comment here.
What I remember, is that the https://github.com/ccxt/ccxt/pull/23250 should have fixed this, and thus you can read .InnerException to find the cause.
feel free to re-open the topic if you experience any further issue, your examples are helpful as always.
