### ISSUE TITLE
Inconsistent Ticker API

### ISSUE THREAD

**Issue by micahschaefer** [ccxt/ccxt#2230]
I am using the Python library and am not a very good programmer ... 

I have noticed that the ticker returns inconsistent results for different exchanges, such as one exchange will return a askVolume while another does not. This may hold true for other methods as well. 

In order to write programs based off this library, I recommend implementing a normalized data structure where ALL API methods return the same response independent of the fact that there is data or not. 

The documentation implies that the API will return a normalized data structure but this is not the case. 

To implement a normalized data structure, all methods should include a default data structure with null values that is overridden with data from the result of the method and then returned. 

Example: 

```
default_ticker = {
  'symbol': null,
  'info' : {},
  'timestamp' : null
  ........
}

function fetch_ticker(...):
  ticker = default_ticker 
  ... // do actual function
  ticker.info = results
{ normalize functions per exchange
  if results.bid:
    ticker.bid = format(clean(results.bid))
} 
```

I appreciate any feedback, I will be looking deeper into the library to see if building this in and creating a pull request is an option on my end.

**Comment by kroitor** [comment]
> I have noticed that the ticker returns inconsistent results for different exchanges, such as one exchange will return a askVolume while another does not. This may hold true for other methods as well.

This library is a work in progress. The `bidVolume`/`askVolume` were added by request from our users recently, and the docs may not be very clear, but the two fields are both optional (may be missing in the ticker). Apart from those two, other fields should be pretty much consistent with the Manual. 

> The documentation implies that the API will return a normalized data structure but this is not the case.

I'll update the Manual on that for less confusion, as it is somewhat behind the code.

> To implement a normalized data structure, all methods should include a default data structure with null values that is overridden with data from the result of the method and then returned.

You are getting forward in the race for our 2018 Captain Obvious Award ) You need to get acquainted with the code a little, namely, check out the purpose of `fetchTicker` and `parseTicker`... Also, read this doc https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md about the structuring of this repo and how code is generated... 

In short, consistency is what we've been working on for past several months. This library probably offers the most cross-exchange-consistent view of crypto markets right now. However, this work is not finished yet. It is done by approx 90% in the public API and approx 60% in the private part. Consistency is what actually makes it a hard task, otherwise this library would have been finished already.

<img width="1505" alt="screen shot 2018-03-13 at 00 11 25" src="https://user-images.githubusercontent.com/1294454/37309811-1c9876bc-2653-11e8-9597-4ec9bd4b7ca2.png">

So, if you think there's something missing in docs or in the code, feel free to submit your edits, just make sure to look around a little first. 

Your contributions and pull-requests are welcome ) We will be happy for all help.

Let us know if we can help with anything else here ) Thx!

**Comment by micahschaefer** [comment]
Thanks for the response ! I look forward to the future of this project.
