### ISSUE TITLE
How to observe RateLimit across threads

### ISSUE THREAD

**Issue by stabilus** [ccxt/ccxt#2252]
- OS: Win 7
- Programming Language version: Python 3.6
- CCXT version: 1.11.84
- Exchange: binance
- Method: any

This is a question:

I would like to run several threads involving various symbols within the same exchange and various symbols on different exchanges. I would like to run each unique combination of exchange and symbol in one separate thread (python 3.6: _thread). 

In the case where I run several threads on the same exchange (i.e. on Binance for the symbols: 'BTC/USDT', 'AION/BTC' and 'IOTA/BTC') I still need to observe the exchange RateLimit (3 threads hitting Binance).  

Can the exchange.enableRateLimit=True setting somehow be made transparent across all threads involving the same exchange?

**Comment by kroitor** [comment]
> Can the exchange.enableRateLimit=True setting somehow be made transparent across all threads involving the same exchange?

Currently, not, it isn't thread-safe. If you created the exchange instance before the threads, the exchange instance is shared across all thread automatically, including the nonce (which is mostly localtime-dependent). In other words, if you want to use the same keypair across multiple thread, you will have to add thread synchronization and will have to override the `nonce()` to use a common synced source. That is, until we find a better way of laying it out... 

Does this answer your question?

**Comment by stabilus** [comment]
This is probably a bit much for my understanding as a hobby programmer...  I'll try and find out how to synch threads and override the nonce(). 
In principle, instantiating the exchange once and then spawning threads for individual symbols would make sense. So far, I spawned a thread for each exchange-symbol combo, (i.e. 3 symbols on binance: I created 3 threads each of which created a separate instances of the exchange). I understand that this will not share the rateLimit, 
But if I instantiate the exchange first and then spawn 3 threads using this exchange instance, would that not take advantage of the exchange.RateLimit?

**Comment by kroitor** [comment]
> But if I instantiate the exchange first and then spawn 3 threads using this exchange instance, would that not take advantage of the exchange.RateLimit?

Not really, because you have to rate-limit your requests accordingly... In general you don't want to issue multiple requests for a single API key in parallel at all, exchanges will do their best to not let you share the key. So, a better approach may be to have a single thread responsible for communication with the exchange, and multiple "worker" threads that would use the communicator-thread as a middleware to talk to the exchange... You will have to set up some messaging queues between threads and use some thread synchronization primitives anyways.

Well, it's explained here:

- http://effbot.org/zone/thread-synchronization.htm
\+
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Or google for "python atomic increment", "python multithreading", "python thread synchronization"

There's a ton of info on this out there. Unfortunately the entire topic of multithreading is too wide to learn from just one issue on github, you obviously need to get more practice with multithreading, so that you feel yourself confident in what can be done and how it should be done with threads.

Hope it answers your question. Let us know if we can help with anything else here. Closing it for now, if you don't mind. Feel free to reopen it if needed. Thx!

**Comment by stabilus** [comment]
appreciate your help and guidance. Thank you!

**Comment by cowboyjj** [comment]
> So far, I spawned a thread for each exchange-symbol combo, (i.e. 3 symbols on binance: I created 3 threads each of which created a separate instances of the exchange). I understand that this will not share the rateLimit,

Hi Stabilus, I am trying to do what you said above but not having much luck. Would you mind kindly sharing a skeleton code to just show how things are put together? thanks a lot
