### ISSUE TITLE
tidex fetch_currency issue

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2259]
Tidex has changed key' names 
    
await self.load_markets()
  File "/Users/user/ccxt/async/base/exchange.py", line 159, in load_markets
    currencies = await self.fetch_currencies()
  File "/Users/user/ccxt/async/tidex.py", line 86, in fetch_currencies
    id = currency['Symbol']
KeyError: 'Symbol'

**Comment by alexsith** [comment]
{'id': 2, 'symbol': 'BTC', 'type': 2, 'name': 'Bitcoin', 'order': 1, 'amountPoint': 8, 'depositEnable': True, 'depositMinAmount': 0.0005, 'withdrawEnable': True, 'withdrawFee': 0.001, 'withdrawMinAmout': 0.001, 'settings': {'Blockchain': 'https://blockchain.info/', 'TxUrl': 'https://blockchain.info/tx/{0}', 'AddrUrl': None, 'ConfirmationCount': 3, 'NeedMemo': False}, 'visible': True}

**Comment by kroitor** [comment]
They switched their web API keys to camelCase... Unfortunately this isn't an official part of their API, but we have no other means of fetching currencies info from them, thus it's better than nothing. But because it isn't official, they won't bother warning or notifying anyone, of course. 

Anyway, this is now fixed in ccxt 1.11.96, please update your version, it should work normally now. Let us know if you still have difficulties with it. Thank you!
