### ISSUE TITLE
Temporarily Disabled Withdraw and Deposit From exchange

### ISSUE THREAD

**Issue by tackpartners** [ccxt/ccxt#2270]
Hello,

It seems that more and more exchange disable temporarily withdraw and deposit for some currency.
Is there a way to check if deposit and withdraw has been deactivated by the exchange for a specific currency?

For example, currently the 'BTS' currency has been deactivated by Poloniex, but strangely, using the create_deposit_address() function, I am able to get a deposit address with status 'ok' which is not normal.

Many thanks for this amazing library and the great work you've done!

- Programming Language version: Python
- CCXT version: 1.11.103
- Exchange: Poloniex

**Comment by kroitor** [comment]
@tackpartners Hi! Sorry for the long wait...

> Is there a way to check if deposit and withdraw has been deactivated by the exchange for a specific currency?

We are working on the unification of this aspect, and the general rule will be:
- to find if the market is tradeable check `if (exchange.markets['ETH/BTC']['active'])`
- to find if the currency is fundable (can deposit/withdraw) check `if (exchange.currencies['ETH/BTC']['active'])`.

↑ This is a work in progress and it these flags may be missing here and there, we will be happy for all help and contributions:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

> For example, currently the 'BTS' currency has been deactivated by Poloniex, but strangely, using the create_deposit_address() function, I am able to get a deposit address with status 'ok' which is not normal.

Because this library is still under development and due to the lack of docs from the exchanges themselves, some aspects may not work ideally yet, but we are going to fix all of them anyway. Thanks for reporting this.

Hope this answers your questions, let us know if not.

**Comment by Poldarn** [comment]
Hi Kroitor, 

First of all congratulations for this amazing library! Unavailable work done!

I have a question reg. this thread (not sure if it's ok to post something here since it's close, so apologies beforehand if I shouldn't).

To get if a currency is available (can be withdrawn and deposit) you mentioned this would be needed: if (exchange.currencies['ETH']['active']).

but this is loading the currencies everytime and then filtering for ETH and displaying its active attribute? if you have it in a loop wouldn't would be very costy?

Wouldn't be easier to implement it somehow somewhere here? fetchTicker(symbol)?

Perhaps I'm missing something. 

Thanks!

**Comment by Poldarn** [comment]
@kroitor

**Comment by kroitor** [comment]
> but this is loading the currencies everytime and then filtering for ETH and displaying its active attribute?

Nope, when you reference  .currencies – you're not loading anything. You're accessing a preloaded and cached value. And there's no networking going on in that particular piece `exchange.currencies['ETH']['active']`. As it is explained in the Manual, if you don't load them by hand, markets (and currencies) are loaded and stored in the cache (`exchange.markets` and `exchange.currencies`) automatically for you upon your **first call to the unified API**. So, if you don't load them by hand, markets will be preloaded in `fetchBalance` or in `createOrder` or in `fetchOrderBook`, whatever happens first in your code. In that particular piece, there's no calls to unified methods, so `.currencies` is a basic object property.

More about it here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
