### ISSUE TITLE
InvalidNonce bitfinex2 invalid checksum

### ISSUE THREAD

**Issue by ssemeniuta** [ccxt/ccxt#22758]
### Operating System

Ubuntu 20.04

### Programming Languages

Python

### CCXT Version

4.3.42

### Description

I get `InvalidNonce bitfinex2 invalid checksum` error when running the below snippet. It takes about 10 seconds for the error to appear. 

[This issue](https://github.com/ccxt/ccxt/issues/19479) reports similar issue, but with `BTC/USD` symbol and `{'prec': 'R0'}`

### Code

```
import ccxt.pro
from asyncio import run

print('CCXT Pro version', ccxt.pro.__version__)

params = {"prec": "P0"}
limit = 100

async def main():
    exchange = ccxt.pro.bitfinex2()
    await exchange.load_markets()
    exchange.verbose = False
    symbol = 'AZERO/USDT'
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol, limit=limit, params=params)
            print(orderbook)
        except Exception as e:
            print(type(e).__name__, str(e))
            break

    await exchange.close()

run(main())


```

**Comment by carlosmiei** [comment]
Hello @ssemeniuta,
Thanks for letting us know, we will take a look.

**Comment by ttodua** [comment]
@carlosmiei this issue might not be directly solvable , because of the frequency of incoming OB updates could be faster than the loop of await  .watchOrderBook. so, the solution could be:
A) ED subscriptions
or
B) handling exceptions in userland to ignore that message
or
C) saving incoming updates in cache (even if there are no clients in `this.futures` at the given moment) and once the await loopo returns back and re-subscribes into `this.futures`, then return the new data with respecting cached data

**Comment by carlosmiei** [comment]
@ttodua I'm not sure exactly how the frequency of incoming updates is related to the checksum validation.

**Comment by carlosmiei** [comment]
@ttodua the orderbook is always updated regardless of the "user subscription", you can even call `watch_order_book()` only once and the orderbook will be updated in the background

**Comment by ttodua** [comment]
yes, you're right, what I wanted to interpret is that during frequent updates in bitfinex (if i correctly recall it was bitfinex) on same millisecond I have seen multiple incoming updates, thus when calculating the checksum of current orderbook, it might be still missing the first delta (because the whole `handleMessage>handleOrderbook` whole cycle can take more than 1 MS) thus, if on same MS there incomes two delta:
- A
- B

if B is followed by checksum validation, then A update might not be yet handled (thus missing during checksum). 
I just theoretically assume this might be case, can't prove atm..

**Comment by ssemeniuta** [comment]
@ttodua Thanks for the feedback. Do I understand correctly that your hypothesis is that book updates are too frequent to be fully processed by the script?

Atm I essentially do `B) handling exceptions in userland to ignore that message` from your suggestion - I let one script finish, wait for 2-3 minutes, then start the script again. There are periods when my app works for ~2-3 hours without this exception which is fine for now.

**Comment by carlosmiei** [comment]
@ssemeniuta I don't think that's the root cause for this issue, in the meantime while we debug it can you please try to disable the checksum validation by doing `exchange.options['checksum'] = False` ?

**Comment by ssemeniuta** [comment]
I've modified the above code to

```
import ccxt.pro
from asyncio import run

print('CCXT Pro version', ccxt.pro.__version__)

params = {"prec": "P0"}
limit = 100

async def main():
    exchange = ccxt.pro.bitfinex2()
    await exchange.load_markets()
    exchange.verbose = False
    symbol = 'AZERO/USDT'
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol, limit=limit, params=params)
            print(orderbook)
        except Exception as e:
            print(type(e).__name__, str(e))
            break

    await exchange.close()

run(main())
```

And the exception did not appear after ~24 hours of runtime. Thank you.

**Comment by AdolfoVillalobos** [comment]
This is still an issue.

Setting the checksum parameter to false prevents errors from rising, but I think there is still something wrong when parsing the Oderbook updates. Is anyone still facing this issue?
