### ISSUE TITLE
Woo fetch_ohlcv credentials requirements

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#22838]
### Operating System

Ubuntu 22.04.1 LTS

### Programming Languages

Python

### CCXT Version

4.2.64

### Description

Hey

While using `woo.fetch_ohlcv` I'm facing an issue depending on if I use `since` or not
v1PubGetHistKline => this do need to sign, hence an apiKey
v1PublicGetKline => this does not 

Is this intended?

Thanks a lot

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @KevinBaudin,

Yes, if `since` is provided we use this (https://docs.woo.org/#kline-historical-data-public) endpoint, and that is private unfortunately.


https://docs.ccxt.com/#/exchanges/woo?id=fetchohlcv
![image](https://github.com/ccxt/ccxt/assets/43336371/bccd6dce-b6b6-46f4-a9ca-24f9fa2aad32)

**Comment by KevinBaudin** [comment]
Are we sure it's private? this really looks like a public endpoint from naming etc.

Also from Postman I managed to get this:

![image](https://github.com/ccxt/ccxt/assets/20791331/975f1c09-5b88-4ada-91d9-25bfac704368)

without being logged at all

**Comment by carlosmiei** [comment]
@KevinBaudin yes you're right 🤦 , will check it asap, sorry

**Comment by carlosmiei** [comment]
@KevinBaudin can you update your ccxt version and try again? should be working now

**Comment by KevinBaudin** [comment]
Seems to work, thanks a lot !
