### ISSUE TITLE
Add URL to get pair details

### ISSUE THREAD

**Issue by siedi** [ccxt/ccxt#2289]
Feature Request:

Can we add the URL to retrieve the pair details (the trading view) on the exchange, please?

E.g. here:
```
            'urls': {
                'logo': 'https://user-images.githubusercontent.com/1294454/27766244-e328a50c-5ed2-11e7-947b-041416579bb3.jpg',
                'api': 'https://api.bitfinex.com',
                'www': 'https://www.bitfinex.com',
                'doc': [
                    'https://bitfinex.readme.io/v1/docs',
                    'https://github.com/bitfinexcom/bitfinex-api-node',
                ],
            },
```

we would add `https://www.bitfinex.com/t/%pair%` or so.

Would help in the apps to link directly to these views.

**Comment by kroitor** [comment]
There was an attempt on this earlier, but we decided not to add web URLs, because unifying their web schema is beyond the scope of this library, moreover, they change their web interfaces too frequently without a prior warning to anyone.

More about it here: 

- https://github.com/ccxt/ccxt/issues/108
- https://github.com/ccxt/ccxt/pull/112

Hope it answers your question. Thx!
