### ISSUE TITLE
HitBTC2 not finding order id

### ISSUE THREAD

**Issue by ballaj2001** [ccxt/ccxt#2301]
Windows
Python
version: 1.10.738
Exchange: HitBTC
Method: fetch_order_status

Hi,

When I try to get the order status utilizing the order id (clientorderid/id) I get an error saying the order isn't found. In the text below you will see that I created a buy order and then used the id from the response to look at the status of the ID. I checked the API reference on HitBTC and it says it uses the clientOrderId (same as 'id' in the response).

```
{'id': '1435ed0141304cee82aa111630c20a07', 'timestamp': 1521411268174, 'datetime': '2018-03-18T22:14:28.174Z', 'created': 1521411268174, 'updated': 1521411268174, 'status': 'closed', 'symbol': 'ANT/BTC', 'type': 'limit', 'side': 'buy', 'price': 0.000314, 'amount': 77.833, 'cost': 0.024439561999999998, 'filled': 77.833, 'remaining': 0.0, 'fee': None, 'info': {'id': '21964996205', 'clientOrderId': '1435ed0141304cee82aa111630c20a07', 'symbol': 'ANTBTC', 'side': 'buy', 'status': 'filled', 'type': 'limit', 'timeInForce': 'GTC', 'quantity': '77.833', 'price': '0.000314', 'cumQuantity': '77.833', 'createdAt': '2018-03-18T22:14:28.174Z', 'updatedAt': '2018-03-18T22:14:28.174Z', 'tradesReport': [{'id': 232843626, 'quantity': '77.833', 'price': '0.000314', 'fee': '0.000024440', 'timestamp': '2018-03-18T22:14:28.174Z'}]}}
Traceback (most recent call last):
  File "c:\Python\Learning\Hello\multiple_exchange_Bit_Hit V2.py", line 117, in <module>
    order_status=check_order_status(my_exchange_buy,order_id)
  File "c:\Python\Learning\Hello\multiple_exchange_Bit_Hit V2.py", line 28, in check_order_status
    order_status=my_exchange.fetch_order_status(order_id)
  File "C:\Users\Ballaj2001\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 846, in fetch_order_status
    order = self.fetch_order(id)
  File "C:\Users\Ballaj2001\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\hitbtc2.py", line 877, in fetch_order
    raise OrderNotFound(self.id + ' order ' + id + ' not found')
ccxt.base.errors.OrderNotFound: hitbtc2 order 1435ed0141304cee82aa111630c20a07 not found
```

You can see the id from the response (1435ed0141304cee82aa111630c20a07) is the same as the one placed in the 'fetch_order_status' method. Although this one says 'closed', the same error happens even if it's partially filled.

Thanks in advance,

**Comment by kroitor** [comment]
Hi!

The `fetchOrderStatus` will call `fetchOrder` and will return the status of the order from there, if the exchange does not have a specific endpoint for just the status (most exchanges don't have such an endpoint, neither does HitBTC, so the fetchOrderStatus call is mostly emulated via fetchOrder).

The problem with HitBTC v2 API is that they don't have a method to fetch an order without knowing its status... They have two methods:
- `fetchOrder` – fetches the order from history (if it is in history, for example, closed)
- `fetchOpenOrder` – fetches the order from the open orders.

So, you should do `fetchOpenOrder()` first and [catch OrderNotFound](https://github.com/ccxt/ccxt/wiki/Manual#error-handling) if the order is not found among the open orders. That would mean that the order is closed, so you should then do a second call to `fetchOrder()` to get the details of a closed order...

The above setup is less convenient because you never know whether your order will be closed quickly or will hang for a while, thus, you never know beforehand if it is open or not, making the fetchOrderStatus for HitBTC somewhat unnecessary... However, this is just how their API works.

Hope it answers your question, let us know if not. Thx!

**Comment by ballaj2001** [comment]
Thanks this works. Also if you put in a delay and wait at least 20 seconds (Just the time I chose, may be shorter can be used) the fetch order will work. It just seems that you can't check the order immediately after placing it.
