### ISSUE TITLE
About balances values

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2358]
So. What we have now is 'total', 'used', 'free'. In 80%(or maybe more) of exchanges 'total' is 'available balance' + held in orders. BUT! There are some exchanges (cryptopia, bx.in.th, southxchange and maybe others) where 'total' = available + held_in_orders + pending_deposit + withdraw_pending.

I think in concept of ccxt we should exclude pending_deposit and pending_withdraw, because you can't do anything with that values - you can't change it to 'available' by yourself, like a canceling order.

If you think it is good idea, I will post my code which change this incorrect(in my opinion) behavior.

in my case: I use only 'total' value for checking deposits and it gives me wrong sign about balance before I can use it.

Thank you.

**Comment by kroitor** [comment]
> I think in concept of ccxt we should exclude pending_deposit and pending_withdraw, because you can't do anything with that values - you can't change it to 'available' by yourself, like a canceling order.

The general idea is:
- `free` = how much you can use for trading
- `used` = how much is used for whatever needs (in orders, pending, etc)
- `total` = `free` + `used`

> If you think it is good idea, I will post my code which change this incorrect(in my opinion) behavior.

Depends on how you would solve it, but, please, keep in mind that we don't do more than one HTTP request per unified call.

The above behaviour is within our expectations. I don't think that this should be changed immediately because other users may rely on existing behaviour... Let us know if you think differently or, maybe have more arguments for it... 

Hope it answers your question. Thx!
