### ISSUE TITLE
How to check whether new candle formed?

### ISSUE THREAD

**Issue by aav80** [ccxt/ccxt#2365]
- OS: Windows 10
- Programming Language version: Node JS 9.0
- CCXT version: 
- Exchange: binance
- Method: fetchOHLCV

on init of my script I going to fetch some quantity of candles,
later i will call another method periodically

how can I check - is new candle now forming, so I need to do something with already formed data. how to check it ?
For instance, I will use 1-hour timeframe, execute function every minute, how han I check that new candle starts?

**Comment by kroitor** [comment]
> For instance, I will use 1-hour timeframe, execute function every minute, how han I check that new candle starts?

The new hourly candle starts when the new UTC hour starts...

```
15:00-16:00 candle 123
16:00-17:00 candle 124
17:00-18:00 candle 125..
...
```

So, each new hourly candle starts on the edge of two consecutive clock hours.

All timestamps in ccxt are **UTC epoch in milliseconds**. Does this answer your question?

**Comment by aav80** [comment]
Yes, you answered completely.

I have another candle-related question, is there any method which is called when new candle is formed, which I can inherite, or some way to run function only 1 time and right the moment, when candle starts?

**Comment by kroitor** [comment]
> I have another candle-related question, is there any method which is called when new candle is formed, which I can inherite, or some way to run function only 1 time and right the moment, when candle starts?

There's no such method in the library, because it isn't related to the library itself, but mostly related on setting up proper timing for events in your program. This is usually done in userland. Think differently: no two events in the word are simultaneous. When you set a timer for 16:00, and it is triggered, it does not necessarily mean that the actual time is 16:00. May be +/- microsecond offset there... And if you request a candle then, the server may have it's own clock which is not in sync with yours, so the server clock may show 15:59 at that moment. I guess, Einstein and Heisenberg in their theories claim that no two events can be measured precisely in time-space... So you should not rely on the clocks, you should instead think of a solution that would work either way. Thus, instead of waiting an hour for the next candle to arrive and then checking, you check every **half an hour** (or as frequently as you need) if the new candle has arrived or not and base all your further behaviour on that.
