### ISSUE TITLE
Reduce API Requests for calculating total balance

### ISSUE THREAD

**Issue by borghoffd** [ccxt/ccxt#2370]
Hey guys,

i'm currently working on a Binance bot with your Trading Library and it's making the development really easy!
But i'm having some struggle with the amount of API requests my bot does. My exchange is Binance and i developed the bot in Javascript/ Node.js, CCXT version is 1.11.117.

The most amount of API calls i'm making to calculate the total balance of my Account, which is then used to calculate the amount of coins i'm buying. This method is called every minute. 

I use exchange.fetchTotalBalance() and filter out every coin where the amout is over 0. Then for every coin i call exchange.fetchTicker() to get the current BTC value and calculate the amount times that value. 
The problem is that i use one bot per coin and flood the Binance API with multiple bots, which of course is not a great idea. 

Is there i way to get the direct BTC value of coins other than BTC itself? My way to calculate is kinda tricky but i see no other way to do it right now.

Any help would be appreciated!

Thanks,
Dennis

**Comment by ardabeyazoglu** [comment]
You should call `fetchTickers` to get latest prices of all coins at once, then or before call fetchBalance. This way you call 2 methods and do the rest in your code.

**Comment by kroitor** [comment]
@borghoffd, the answer of @ardabeyazoglu is correct, however, you should use rate limiting and call fetchBalance first, then fetchTickers to get them all at once. Now, because fetchTickers is a "heavy" request, you should not call fetchTickers more frequently than approx once a minute, otherwise they will ban you. More about rate-limiting in the Manual: https://github.com/ccxt/ccxt/wiki
Let us know if it does not answer your question. Thx!

**Comment by nabtron** [comment]
Isn't there any "total balance" in usd or btc option available in binance api? like it shows on the website itself?

**Comment by kroitor** [comment]
@nabtron https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance

**Comment by kroitor** [comment]
@nabtron https://github.com/ccxt/ccxt/issues/1986
