### ISSUE TITLE
Gate.io Ignores startTime / endTime parameters when fetching orders.

### ISSUE THREAD

**Issue by ywallis** [ccxt/ccxt#23843]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.4.6

### Description

When calling closed orders on gate.io with startTime / endTime parameters, these are ignored, and the latest closed orders are retrieve, regardless of their creation / fill time.
The same behavior can be observed when using the "since" parameter.

### Code

```

orders = gate.fetch_closed_orders(symbol=pair, limit=1000, params={'startTime': 1727308800000, 'endTime': 1727316000000})
  

```

**Comment by carlosmiei** [comment]
Hello @ywallis,
At `fetchClosedOrders` we're using these endpoints and most of them don't support a `since/until` timestamp so ccxt can only filter the data afterward using those timestamps:

https://www.gate.io/docs/developers/apiv4/en/#list-orders
https://www.gate.io/docs/developers/apiv4/en/#retrieve-running-auto-order-list
https://www.gate.io/docs/developers/apiv4/en/#list-futures-orders
https://www.gate.io/docs/developers/apiv4/en/#list-all-auto-orders
https://www.gate.io/docs/developers/apiv4/en/#list-futures-orders-2
https://www.gate.io/docs/developers/apiv4/en/#list-all-auto-orders-2
https://www.gate.io/docs/developers/apiv4/en/#list-options-orders

Nonetheless, I found a different endpoint that can probably be supported as well and it does accept `since/until` in the request: https://www.gate.io/docs/developers/apiv4/en/#list-futures-orders-by-time-range

Will be added shortly!

**Comment by carlosmiei** [comment]
@ywallis Can you update your ccxt version and try again pls? it should be working now, but please bear in mind that you should be providing `startTime` as `since` as an argument, and `endTime` as `until` inside `params`

**Comment by ywallis** [comment]
> @ywallis Can you update your ccxt version and try again pls? it should be working now, but please bear in mind that you should be providing `startTime` as `since` as an argument, and `endTime` as `until` inside `params`

Sorry for not looking into this earlier! I've updated, and the behavior hasn't changed using any of the code below:

`orders = gate.fetch_closed_orders(symbol=pair, limit=1000, params={'startTime': 1727308800000, 'endTime': 1727316000000})`
`orders = gate.fetch_closed_orders(symbol=pair, limit=1000, params={'since': 1727308800000, 'until': 1727316000000})`

However, I am able to simulate using the implicit method as below:

`orders = gate.privateSpotGetOrders(params={'currency_pair': 'BTC_USDT', 'status': 'finished', 'from': 1727308800, 'to': 1727316000})
`


My understanding of the inner workings of the library are probably not good enough, but could this endpoint not be used by the unified API?

**Comment by carlosmiei** [comment]
@ywallis Can you please try to follow the method's signature? 

You should be providing since like this: `gate.fetch_closed_orders(symbol=pair, since =1727308800000, limit=1000, params={ 'until': 1727316000000})`

**Comment by carlosmiei** [comment]
@ywallis Sorry, that was missing but I updated in the meantime. Can you please update your ccxt version to the latest and try again? `until` should be working now as well.

**Comment by ywallis** [comment]
> @ywallis Sorry, that was missing but I updated in the meantime. Can you please update your ccxt version to the latest and try again? `until` should be working now as well.

That did it! Seems fixed! Thanks a ton

**Comment by carlosmiei** [comment]
@ywallis Thanks for confirming it!

Will close this issue but please let me know if anything!
