### ISSUE TITLE
KuCoin: fetchDepositWithdrawFee() 'networks' field empty

### ISSUE THREAD

**Issue by XKonnoRX** [ccxt/ccxt#24038]
### Operating System

Windows 11

### CCXT Version

4.4.20

### Description

Language C#

It seems that the field 'networks' is wrong for fetchDepositWithdrawFee:

var res = kucoin.fetchDepositWithdrawFee("USDT").Result;

--> Is returning empty 'networks' field

### Code

```
  {
  "info": {
    "currency": "USDT",
    "limitBTCAmount": "14.56983254",
    "usedBTCAmount": "0.00000000",
    "quotaCurrency": "USDT",
    "limitQuotaCurrencyAmount": "999999.00000000",
    "usedQuotaCurrencyAmount": "0",
    "remainAmount": "999999.000000",
    "availableAmount": "0",
    "withdrawMinFee": "5.5",
    "innerWithdrawMinFee": "0",
    "withdrawMinSize": "30",
    "isWithdrawEnabled": true,
    "precision": 6,
    "chain": "ERC20",
    "reason": null,
    "lockedAmount": "0"
  },
  "withdraw": {
    "fee": null,
    "percentage": false
  },
  "deposit": {
    "fee": null,
    "percentage": null
  },
  "networks": {}
}

```

**Comment by carlosmiei** [comment]
Hello @XKonnoRX, Yeah, at least one currency should be present, but unfortunately, not more than one because Kucoin only returns one per request. If you want to get information about a different network, you have to provide it in `params` upon calling the method.

We will fix the reported issue, thanks for reporting it.

**Comment by carlosmiei** [comment]
@XKonnoRX If you update your ccxt version it should be working now.
