### ISSUE TITLE
Where to find ccxt knowledgable coders?

### ISSUE THREAD

**Issue by forexhill** [ccxt/ccxt#2412]
Hi all! I have a question. Where do I find good developers knowledgeable in ccxt? I have a few functions which I urgently need coded. I will pay for the time.

**Comment by kroitor** [comment]
> I have a few functions which I urgently need coded.

Which particular functions? Are those in unified CCXT API? Or are those user-specific or application-specific?

**Comment by forexhill** [comment]
Functions for particular tradeflow operations (application-specific, but generally written so they can be used elsewhere) - in PHP.

**Comment by igladun** [comment]
I found on Upwork. But you must always re-check the work because sometimes coders on Upwork do some mistakes, which could produce money lose.

**Comment by cryptodawn1** [comment]
Hi forexhill,
I am using ccxt for quite a long time in my php/node projects;  have 30+ years of programming experience.  Contact me with your requirement. cryptodawn@YAHOO.com

**Comment by yangdevt** [comment]
Hi, cryptodawn1
I am building the site using CCXT library now and I met a problem with Api rate Limit.
I am going to display the trading info 2 times per second, but since for the rate Limit, the requests is pending after few minutes.
Is there any solution to reduce the rate Limit?
Should I request from the each exchange Api developers?

**Comment by cryptodawn1** [comment]
yangdevt,
exchange will start rejecting once flooded with out-of-range of rate-limit., use proxies as a simple solution, but a smart code with proxies either!!

**Comment by yangdevt** [comment]
cryptodwan1
Thanks for your answer in advance.
What I am doing is to display the transaction history for all exchanges in the CCXT library.
And I am calling the api request 2 times per second.
This is view side code:
**************************
$.post('/request_info',{'exchangeID_array':exchangeID_array}, function(result){
   $.each(result, function(index, value){
	.....................					
   },'json');
},1000);
*************************
And this is part for calling the api:
*************************
router.post('/request_info', function(req, res, next){
  exID = req.body.exchangeID_array; //exchange ID array 
  ;(async () =>  {
		for(var i=0;i< exID.length;i++){
			var exID_item = exID[i];
			var symbol = 'BTC/USD';
			try{
				const enableRateLimit = true;
				const each_selectexchange = new ccxt[exID_item] ({ enableRateLimit })
				let each_markets = await each_selectexchange.loadMarkets ();
				const each_order = await each_selectexchange.fetchOrderBook (symbol);

                                .............................

*************************
But few minutes later(about 1~2 minutes), the requests are pending.
I think that the reason is since the rateLimit of every exchanges api is different.
How can I fix that?

**Comment by kroitor** [comment]
@yangdevt https://github.com/ccxt/ccxt/issues/2458#issuecomment-378753998

**Comment by kroitor** [comment]
@forexhill I'd close this for now if you don't mind. Feel free to reopen it if needed. Thx!

**Comment by kroitor** [comment]
@forexhill 
- https://www.freelancer.in/projects/php/cryptopia-trading-script-using-ccxt/
- https://www.upwork.com/job/cryptocurrency-data-collection-system-using-ccxt-library_~012e1e20ff47c65983/
- https://www.freelancer.com/projects/php/crypto-arbitrage-trading-bot-multiple/
- https://www.upwork.com/job/Create-cryptocurrency-arbitrage-trading-bot-Python-Java-with-the-help-ccxt-library_~01712fd6b89c78833b/
- https://www.freelancer.co.uk/projects/graphic-design/create-exchange-based-with-ccxt/
- http://ke.jobrapido.com/jobpreview/6559382
- https://www.workana.com/en/job/query-via-api-e-analise-de-dados-sort
- https://www.work.ua/jobs/3053691/
- https://freelance.ru/projects/?cat=4&spec=446
- http://za.jobrapido.com/jobpreview/24063764
- https://www.agencies.io/job/10293121/f/freelancer/php-python-django-developer-hours-week
- https://www.fl.ru/projects/3537246/integratsiya-api-kriptobirj-dlya-analiza-tsen-i-arbitraja.html
- google for *"ccxt job"*, *"ccxt freelance"*, ...

**Comment by kroitor** [comment]
@forexhill 

Also: 
- https://github.com/ccxt/ccxt/network/dependents
- https://github.com/ccxt/ccxt/graphs/contributors

**Comment by hollylh** [comment]
> Would anyone from the community be interested in paid work?

Hello, I realize this thread is a year old..but who did you wind up hiring?  I'm having the same issue!  Thanks.

**Comment by hollylh** [comment]
> I found on Upwork. But you must always re-check the work because sometimes coders on Upwork do some mistakes, which could produce money lose.

I know this thread is very old, but is there anyone in particular you could recommend?  I'm having problems finding people..  Thank you
