### ISSUE TITLE
[cex.io] Missing 'fetchOrder' after rework

### ISSUE THREAD

**Issue by varanauskas** [ccxt/ccxt#24126]
### Operating System

macOS

### Programming Languages

JavaScript

### CCXT Version

4.4.25

### Description

In #23942 `exchange.fetchOrders` was removed from the CEX.IO exchange
https://github.com/ccxt/ccxt/commit/47358fe21c7b36d59bfe0c8871947bd66b7525c5#diff-8c5121be79cf98ed8260adfe6101267fccffee0c4216b3c552d1b1495f69b262R43-R44

If I understand correctly it was done reworking API to new version

I think new version has an ability to fetch a single order using this call:
https://trade.cex.io/docs/#rest-private-api-calls-orders
POST /get_my_orders { orderId }

### Code

```ts
import ccxt from "ccxt";
const exchange = new ccxt.cex({ ... });
console.log(exchange.has.fetchOrder); // false
```

**Comment by carlosmiei** [comment]
Hello @varanauskas, thanks for reporting it.

Yes we upgraded cex recently, but we will double-check if `fetchOrder` can be implemented using this new API.

**Comment by carlosmiei** [comment]
@varanauskas Ok, I checked, and the problem is that this endpoint only returns open or closed orders depending on the values inside the request and can't return both simultaneously. 

`fetchOrder/fetchOrders` can only be implemented when the exchange provides an endpoint that returns orders regardless of their status.

We can however implement `fetchOpenOrder` and `fetchClosedOrder` (singular)

**Comment by carlosmiei** [comment]
@varanauskas We added fetchOpenOrder/fetchClosedOrder to cex.io let us know if anything
