### ISSUE TITLE
QRYPTOS fetchOHLCV doesn't work when I set the since param

### ISSUE THREAD

**Issue by jeffryhartanto** [ccxt/ccxt#2413]
- OS: Windows 10
- Programming Language version: Javascript
- CCXT version: 1.12.50
- Exchange: QRYPTOS
- Method: fetchOHLCV

Hi, I execute this method `let tickers = await exchange.fetchOHLCV(symbol, '1m');` and it returns 14 items, which is fine. However, when I set the `since` param, e.g. `let tickers = await exchange.fetchOHLCV(symbol, '1D', '2018-03-30 00:00:00');`, it always returns 0. Do I do something incorrect? Also, can I change the limit to say 100? I cannot find the info regarding the limit in their website.

**Comment by mkutny** [comment]
1. `since` is a `number` (milliseconds), not a `string`. But that's for your future consideration, in this particular case it's irrelevant (see below why).

2. `has.fetchOHLCV === 'emulated'` on this exchange. It means that the exchange does not provide this method as a part of their native API. Instead, the candles are built on the library side using this fewliner:
https://github.com/ccxt/ccxt/blob/ef83a289768fb5f09d6e3bfa03596496b5af7874/js/base/Exchange.js#L583-L590

3. As you can see it first fetches trades by `fetchTrades` and then feeds them into `buildOHLCVC` function. But as it relies on `fetchTrades` it can go as far in terms of params as this method allows.

4. [The documentation](https://developers.quoine.com/#executions) says that their `fetchTrades` do not support `since` and that by default only 20 trades are returned. The latter basically means that your 14 candles are built on the very limited set of data.

5. If I needed candles on this exchange I would fetch as much trades as I needed myself (by looping `fetchTrades` method) and fed them into `buildOHLCVC` myself.

Hopefully, with the help of ccxt it's much easier to do than without.

**Comment by jeffryhartanto** [comment]
Thankss... forgot to check the type..
