### ISSUE TITLE
Fetching historical bid-ask spread for a trading pair

### ISSUE THREAD

**Issue by arklumichael** [ccxt/ccxt#2442]
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: master
- Exchange: any
- Method:fetch_order_book

I am a newbie to Python programming so please excuse me if I make very stupid mistake. I also heavily borrow from the examples from the ccxt example library

I try to fetch historical order book (to calculate bid-ask spread from cryptopia for this specific pair LTC/BTC every 12 hours from 2018-03-20 00:00:00 till now, for example. Here is the code I merge from several examples hoping to do the work, but it does seem to give me the correct times series of bid-ask spread or bid, ask individually. Any idea why? Thanks a lot!

# Code

```Python
import os
import sys
import time

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402



msec = 1000
minute = 60 * msec
hold = 30




id = 'cryptopia'


exchange = getattr(ccxt, id)({
       'rateLimit': 3000,
    'enableRateLimit': True,
    # 'verbose': True,
    # 'proxy':'https://cors-anywhere.herokuapp.com/',
})



from_datetime = '2018-03-20 00:00:00'
from_timestamp = exchange.parse8601(from_datetime)



now = exchange.milliseconds()



data1=[]
data2=[]
data3=[]
while from_timestamp < now:

     try:
          markets = exchange.load_markets()
          orderbook = exchange.fetch_order_book ('LTC/BTC',from_timestamp)
          bid = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
          ask = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None
          spread = (ask - bid)  if (bid and ask) else None
          from_timestamp += 12* 60 * minute
          data1.append(bid)
          data2.append(ask)
          data3.append(spread)

     except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:
          print('Got an error', type(error).__name__, error.args, ', retrying in', hold, 'seconds...')
          time.sleep(hold)
```

**Comment by kroitor** [comment]
Hi!

First, let me explain: the exchanges will not keep all historical data available, very few of them actually do that, and most of them will restrict the amount of data in the past you can query at any specific moment. So, you can't just say "hey, give me the spread that was there on the 5th of October 2016" – the exchanges won't like it. On the other hand, you can query current spread any time you want. So, if you think further, in order to build a fault-tolerant system you will have to keep your program running, and fetching current spread and storing it (in a file or a database or in memory, or whatever) for later use in your program. This is the general pattern of aggregating data.

Secondly, there's a mistake in the code: the second argument of fetch_order_book is not a *"from time"*, but a `limit` of orders you want to fetch. More about it: 
- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual#order-book

Hope it answers your questions. Feel free to reopen this issue if needed or just ask if you have more )

**Comment by arklumichael** [comment]
thank you so much Kroitor!

**Comment by kroitor** [comment]
@arklumichael you might also want to read through other chapters in the Manual, as there's still some historical data available (OHLCV, trades) – that might be needed as well in your code.

**Comment by arklumichael** [comment]
@kroitor Thank you so much! You think there is absolutely no way, say, if I want to get the bid ask spread anywhere? I am a researcher at MIT studying finance so that I need long time series across multiple exchanges in order to do some statistical analysis for a research paper

**Comment by kroitor** [comment]
@arklumichael if you want actual orderbook data (the most detailed state of the order stack at each particular moment) – then you will have to aggregate it. Storing each state of the orderbook along with ongoing trades is called "tick history". Existing commercial aggregators will charge several hundred $ for a monthly tick history for one exchange and one pair. That is gigabytes of data. Now, imagine, if you want to collect data from 100 exchanges each having 100 pairs – you will have to build a highly-scalable system just to be able to handle terabytes of data... This is the primary reason why the exchanges themselves don't serve historical orderbooks – too heavy.

**Comment by Ross-Li** [comment]
> @kroitor Thank you so much! You think there is absolutely no way, say, if I want to get the bid ask spread anywhere? I am a researcher at MIT studying finance so that I need long time series across multiple exchanges in order to do some statistical analysis for a research paper

Check out Shrimpy, maybe they have what you need.
