### ISSUE TITLE
Timeout and rateLimit

### ISSUE THREAD

**Issue by yangdevt** [ccxt/ccxt#2458]
When I checked the manual, it says like this:
**************************************************************************************************
timeout: A timeout in milliseconds for a request-response roundtrip (default timeout is 10000 ms = 10 seconds). You should always set it to a reasonable value, hanging forever with no timeout is not your option, for sure.

rateLimit: A request rate limit in milliseconds. Specifies the required minimal delay between two consequent HTTP requests to the same exchange. This parameter is not used for now (reserved for future).
**************************************************************************************************
so if I set the timeout as 500ms, then I can call the api 2 times per second?
And rateLimit is still not used for now?

**Comment by kroitor** [comment]
> so if I set the timeout as 500ms, then I can call the api 2 times per second?

No, the timeout controls the maximum duration of a single request, and has nothing to do with the rate limit.

> And rateLimit is still not used for now?

It is used and it is the actual delay in milliseconds between two consecutive requests. However, in order to use it, you should enable the built-in rate limiter (disabled by default):

```
exchange = ccxt.bittrex ({'enableRateLimit': true})
exchange.fetch_balance ()
exchange.create_order (...)
...
```

Hope it answers your question.

**Comment by yangdevt** [comment]
Thanks for your answer.

This is my server side code

******************************************
........


;(async () =>  {
for(var i = 1; i< single_exchange_info.length; i++){
var symbol = single_exchange_info[i];
try{
const single_selectexchange = new ccxt[single_exchangeID] ({
'verbose': process.argv.includes ('--verbose'),
'timeout': 500,
})
let single_markets = await single_selectexchange.loadMarkets ()

.........
**********************************************
so I set the timeout as 500ms and set the setinterval time 500ms too.

$.post('/start_single_exchange',{'single_exchange_info':single_exchange_info}, function(result){


    }, 'json');
}, 500);


________________________________

**Comment by yangdevt** [comment]
Thanks for your answer.

This is my server side code for call the apis 2 times per second.
******************************************
........

;(async () =>  {
for(var i = 1; i< single_exchange_info.length; i++){
var symbol = single_exchange_info[i];
try{
const single_selectexchange = new ccxt[single_exchangeID] ({
'verbose': process.argv.includes ('--verbose'),
'timeout': 500,

})
let single_markets = await single_selectexchange.loadMarkets ()

.........
**********************************************

so I set the timeout as 500ms and set the setinterval time 500ms too.

**********************************
............

$.post('/start_single_exchange',{'single_exchange_info':single_exchange_info}, function(result){

        ...................

    }, 'json');
}, 500);

..............
***********************************************

But after few minutes later, the requests are still pending.
How can I fix that?

Best


<http://aka.ms/weboutlook>
________________________________

**Comment by kroitor** [comment]
@yangdevt 

> so I set the timeout as 500ms and set the setinterval time 500ms too.

You should read and do literally what is written in my above post, because I just told you to do the opposite: 
1. do not touch the `timeout` at all, don't change it, don't set it, remove that line
2. add `{enableRateLimit:true}` to your constructor.

```
<!DOCTYPE HTML>
<html>
<head>
    <title>CCXT Basic example for the browser</title>
    <script type="text/javascript" src="https://unpkg.com/ccxt"></script>
    <script>

        document.addEventListener ("DOMContentLoaded", async function () {

            alert ('ccxt version ' + ccxt.version + ' supporting '+ ccxt.exchanges.length.toString () + ' exchanges');

            const enableRateLimit = true
            const exchange = new ccxt.poloniex ({ enableRateLimit })
            const symbol = 'ETH/BTC'

            while (true) {

                let text = []

                try {

                    const ticker = await exchange.fetchTicker (symbol)

                    text = [
                        exchange.id,
                        symbol,
                        JSON.stringify (exchange.omit (ticker, 'info'), undefined, '\t')
                    ]

                } catch (e) {

                    text = [
                        e.constructor.name,
                        e.message,
                    ]
                }

                document.getElementById ('content').innerHTML = text.join (' ')

            }

        })
    </script>
</head>
<body>
<h1>Hello, CCXT!</h1>
<pre id="content"></pre>
</body>
</html>
```

Examples: https://github.com/ccxt/ccxt/tree/master/examples

I'd recommend to read the entire Manual and browse through all the JS and HTML examples and make sure you understand them, then try creating your code based on that.

**Comment by yangdevt** [comment]
I am going to call all the apis at one time every 2 times per second.
But request for some exchanges will be pending few mins later.
So I asked again

**Comment by munny-lcx** [comment]
my ccxt version: 1.30.20, updated version
language used: Node.js
Exchange id: hitbtc2
function used: fetchOHLCV  of ccxt exchange

what I am trying: to store ohlcv from Jan 2021
for my algo is: to run  a script in every 4 min though setInterval or corn package.

i store get last store ohlcv from hitbtc ohlcv db

then call fetchOHLCV with since and also with limit 1000.

my code is:
under for loop of all pair list

![image](https://user-images.githubusercontent.com/66307095/85127649-7ac24780-b24d-11ea-8ace-0a588a77f3c4.png)

and under fetchAndStore function: 

create exchange class:
![image](https://user-images.githubusercontent.com/66307095/85127384-f2dc3d80-b24c-11ea-82e6-9874552c1684.png)

call class method fetchOHLCV:

![image](https://user-images.githubusercontent.com/66307095/85127463-169f8380-b24d-11ea-94bd-5fcfa817c91e.png)

Thank you ccxt for your great support
