### ISSUE TITLE
Kucoin, Cobinhood and Qryptos: fetch_open_orders() throws error

### ISSUE THREAD

**Issue by wntsang4** [ccxt/ccxt#2475]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.12.87
- Exchange: Kucoin, Cobinhood, Qryptos
- Method: fetch_open_orders()

After calling fetch_open_orders(), it throws below error
array = [entry for entry in array if entry['timestamp'] >= since]
TypeError ("'>=' not supported between instances of 'int' and 'dict'",)

Kucoin:
Request: GET https://api.kucoin.com/v1/order/active-map?symbol=SPHTX-BTC {'KC-API-KEY': '5aa04d', 'KC-API-NONCE': '1523004773684', 'KC-API-SIGNATURE': 'fc6b', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.kucoin.com/v1/order/active-map?symbol=SPHTX-BTC 200 {'Date': 'Fri, 06 Apr 2018 08:52:56 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost'} {"success":true,"code":"OK","msg":"Operation succeeded.","timestamp":1523004776037,"data":{"SELL":[{"oid":"5ac735641501194f5097fbbb","userOid":null,"coinType":"SPHTX","coinTypePair":"BTC","direction":"SELL","price":5.0E-5,"dealAmount":0.0,"pendingAmount":5.0,"createdAt":1523004773000,"updatedAt":1523004773000}],"BUY":[]}}

Cobinhood:
Request: GET https://api.cobinhood.com/v1/trading/orders {'nonce': '1523005785', 'Authorization': 'eyJhbGciOiJIywZc2d39b3e03cf846eedab26e56c19512d23c9', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.cobinhood.com/v1/trading/orders 200 {'Date': 'Fri, 06 Apr 2018 09:09:48 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d52210a19061523005788; expires=Sat, 06-Apr-19 09:09:48 GMT; path=/; domain=.cobinhood.com; HttpOnly; Secure', 'Access-Control-Allow-Origin': 'https://cobinhood.com', 'Via': '1.1 google', 'Alt-Svc': 'clear', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '40731e20588932b3-HKG', 'Content-Encoding': 'gzip'} {"success":true,"result":{"limit":50,"page":1,"total_page":1,"orders":[{"id":"01f88a23-b970-4868-a935-19fc857e6c24","trading_pair_id":"TBAR-BTC","side":"bid","type":"limit","price":"0.0000006","size":"100000","filled":"0","state":"open","timestamp":1520958587719,"eq_price":"0","completed_at":null,"source":"exchange"}]}}

Qryptos:
Request: GET https://api.qryptos.com/orders?product_id=48&status=live {'X-Quoine-API-Version': '2', 'Content-Type': 'application/json', 'X-Quoine-Auth': 'eyJhJ4', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.qryptos.com/orders?product_id=48&status=live 200 {'Date': 'Fri, 06 Apr 2018 09:18:02 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '366', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dcc7aa0d8df5420cc38d680e969ca29ab1523006282; expires=Sat, 06-Apr-19 09:18:02 GMT; path=/; domain=.qryptos.com; HttpOnly, _vax_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJWY4NTYxOTFhYTAyMTc3ZWJjNGZlN2NhZTY5Njg1NDgwBjsAVEkiCWxhbmcGOwBGOgdlbkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsHWwZpA40oAUkiIiQyYSQxMCRHRjdyTFhlaEgwV2QxZVJpMHpqWmJPBjsAVA%3D%3D--aea89fc441e90bc05badf418ebec08e86b4d4d46; path=/; secure; HttpOnly', 'Cache-Control': 'max-age=0, private, must-revalidate', 'Content-Encoding': 'gzip', 'Etag': '"30dc9a8690cf3eee68ceb3f4e4694a8e"', 'Status': '200 OK', 'Strict-Transport-Security': 'max-age=631152000; includeSubdomains', 'Vary': 'Accept-Encoding', 'Via': '1.1 spaces-router (4d6b14feab68)', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Powered-By': 'Phusion Passenger 5.1.2', 'X-Rack-Cache': 'miss', 'X-Request-Id': 'c43ce147-e548-8332-09d9-3b0f85946f92', 'X-Runtime': '0.037007', 'X-Ua-Compatible': 'IE=Edge,chrome=1', 'X-Xss-Protection': '1; mode=block', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '40732a30beb23355-HKG'} {"models":[{"id":36093476,"order_type":"limit","quantity":"100.0","disc_quantity":"0.0","iceberg_total_quantity":"0.0","side":"sell","filled_quantity":"0.0","price":0.00005,"created_at":1523006279,"updated_at":1523006279,"status":"live","leverage_level":1,"source_exchange":null,"product_id":48,"product_code":"CASH","funding_currency":"BTC","crypto_account_id":null,"currency_pair_code":"SPHTXBTC","average_price":"0.0","target":"spot","order_fee":"0.0","source_action":"manual","unwound_trade_id":null,"trade_id":null},{"id":29806733,"order_type":"limit","quantity":"500.0","disc_quantity":"0.0","iceberg_total_quantity":"0.0","side":"sell","filled_quantity":"0.0","price":0.000064,"created_at":1521381881,"updated_at":1521381881,"status":"live","leverage_level":1,"source_exchange":null,"product_id":48,"product_code":"CASH","funding_currency":"BTC","crypto_account_id":null,"currency_pair_code":"SPHTXBTC","average_price":"0.0","target":"spot","order_fee":"0.0","source_action":"manual","unwound_trade_id":null,"trade_id":null}],"total_pages":1,"current_page":1}

Code:
orders = kucoin.fetch_open_orders('SPHTX/BTC')
orders = cobinhood.fetch_open_orders('TBAR/BTC')
orders = qryptos.fetch_open_orders('SPHTX/BTC')

**Comment by kroitor** [comment]
First of all, when you are reporting your verbose output, please follow these rules exactly (literally) and use backticks for readability: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. For some reason you keep reformatting the output and changing places in text when you copypaste it here. 

In fact, when you issue a fetch* call in verbose mode, it will output:

1. the request (5-15 lines)
2. then the response (whatever the length)
3. then the error stack trace (5-10) lines... you've copied just the last line of the error stack trace... instead you should've copied the entire output, and just remove your keys from it (if necessary).

Anyway, never mind, that is mostly for future reporting, please mind the above next time.

As for this issue, it seems that you're actually passing the `since` parameter (a dictionary) to the fetch_open_orders call, where it should be an integer instead.

What does this snippet output? (copy-paste all output as is, remove your keys, but please don't cut out anything else)

```Python
import ccxt
kucoin = ccxt.kucoin({
    'enableRateLimit': True,
    'verbose': True,
    'apiKey': 'YOUR_API_KEY',  #  ←--------------
    'secret': 'YOUR_SECRET',  #  ←--------------
})
orders = kucoin.fetch_open_orders('SPHTX/BTC') # ←---- is there anything else here in your code?
```

Are you sure that your last line containing the function call does not have any other params, except the `'SPHTX/BTC'` pair?

**Comment by wntsang4** [comment]
it should be
kucoin.fetch_open_orders('SPHTX/BTC', {'id' : order['id'], 'type' : order['side'].upper()})

There are too many open orders, so I cut some of them.

**Comment by kroitor** [comment]
> it should be
> kucoin.fetch_open_orders('SPHTX/BTC', {'id' : order['id'], 'type' : order['side'].upper()})

No it shouldn't. From the Manual (read it): https://github.com/ccxt/ccxt/wiki/Manual#open-orders

It says:

> ```exchange.fetchOpenOrders (symbol = undefined, since = undefined, limit = undefined, params = {})```

The `params` should be the fourth (!) argument, not the second.
Also, that last `params` dictionary is used for exchange-specific params, and Kucoin does not have such a parameter as `id` to their fetch_open_orders method anywhere in their docs: https://kucoinapidocs.docs.apiary.io/#

You can't really choose whatever property name you like and pass it in `params`, those are for very specific values only.

You should really read the Manual on how to work with orders, because you obviously don't completely understand how it works: https://github.com/ccxt/ccxt/wiki/Manual#orders

The correct call should be:

```Python
symbol = 'SPHTX/BTC'
since = None
limit = None
params = {'type' : order['side'].upper()}
orders = kucoin.fetch_open_orders(symbol, since, limit, params)
print('Got ' + str(len(orders)) + ' orders')
```

I'd recommend to read the entire Manual from the beginning to the end. It will save you weeks of debugging, trust me. ;)

Hope the above answers your question.
