### ISSUE TITLE
Loop through all markets and all exchanges for bid-ask spread in python

### ISSUE THREAD

**Issue by arklumichael** [ccxt/ccxt#2511]
OS: Mac
- Programming Language version: Python

For the following code to get bid-ask for a specific exchange (bxinth) for a specific market 'XPM/BTC', is it possible that loop through all markets for a exchange or all markets across all exchanges on python? I don't know if a similar issue has been issued before but I don't seem to have seen it for python.

Thanks a lot!

# Code

import os
import sys
import time

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

id = 'bxinth'

exchange = getattr(ccxt, id)({
       
    # 'proxy':'https://cors-anywhere.herokuapp.com/',
})

orderbook = exchange.fetch_order_book ('XPM/BTC')
bid = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
ask = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None
spread = (ask - bid) if (bid and ask) else None
print (exchange.id, 'market price', { 'bid': bid, 'ask': ask, 'spread': spread })

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/tree/master/examples/py

Does this answer your question?

**Comment by arklumichael** [comment]
I don't think so I guess?

**Comment by arklumichael** [comment]
Let me have another look

**Comment by arklumichael** [comment]
Thank you kroitor, as I understand it correctly, instantiate-all at once code allow me to instantiate all exchanges, but I have to type in each market for each exchange by hand? like this?

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

exchanges = {}  # a placeholder for your instances

for id in ccxt.exchanges:
    exchange = getattr(ccxt, id)
    exchanges[id] = exchange()

# now exchanges dictionary contains all exchange instances...
orderbook=exchanges['bittrex'].fetch_order_book('ETH/BTC')
bid = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
ask = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None
spread = (ask - bid) if (bid and ask) else None
print ('market price', { 'bid': bid, 'ask': ask, 'spread': spread })

orderbook=exchanges['binance'].fetch_order_book('ETH/BTC')
bid = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
ask = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None
spread = (ask - bid) if (bid and ask) else None
print ('market price', { 'bid': bid, 'ask': ask, 'spread': spread })

**Comment by arklumichael** [comment]
@kroitor Sorry I am absolutely beginner, you may already tell me the answer, but I can't tell..

**Comment by jorijnsmit** [comment]
I vote to close, this is not an issue with ccxt but rather an ask for help... 

@arklumichael I suggest doing some tutorials, taking some programming classes or hacking some more by yourself. Your issue here is not specific enough but rather has a gest of "please code this and that for me". That's not what GitHub is for :-)

**Comment by kroitor** [comment]
@arklumichael 

> Sorry I am absolutely beginner, you may already tell me the answer, but I can't tell..

I'd agree with @jorijnsmit , you need to get along with fundamental python first, then move on to algorithmic trading. In general you don't want all exchanges and all markets, because not all of them will even be available from your location. Many of them have thousands of symbols, some of them are not even exchanges at all (like CoinMarketCap). If you run a sequential loop over all of them, fetching will take hours and by that time the first responses will be outdated. Start by going through examples and making sure you understand each one of them – that's the necessary minimum of python skillz you need to have to work with the library effectively.  You will also have to read the entire Manual in order to understand how to communicate with crypto exchanges: https://github.com/ccxt/ccxt/wiki. Closing it for now.
