### ISSUE TITLE
Kucoin: Inconsistent result of create_limit_order()

### ISSUE THREAD

**Issue by HynekBlaha** [ccxt/ccxt#2539]
- OS: MacOs
- Programming Language version: Python 3.6
- CCXT version: 1.12.122
- Exchange: Kucoin
- Method: self.create_limit_order()

<img width="665" alt="screen shot 2018-04-10 at 21 44 26" src="https://user-images.githubusercontent.com/26007903/38579889-aa66b168-3d08-11e8-8278-8dde7e0a867a.png">

Thee is timestamp in result['info']['timestamp'], but not set in result['timestamp']
Also result['symbol'] should be in format "NEO/BTC", not "NEO-BTC".
And probably result['side'] in lowercase (not sure).

**Comment by kroitor** [comment]
> Thee is timestamp in result['info']['timestamp'], but not set in result['timestamp']

Fixed this.

> Also result['symbol'] should be in format "NEO/BTC", not "NEO-BTC".

Fixed this.

> And probably result['side'] in lowercase (not sure).

You're passing an uppercase `'BUY'` string to createOrder, which is against the Manual:
- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

> `side`, a string literal for the direction of your order, buy or sell. When you place a buy order you give quote currency and receive base currency. For example, buying BTC/USD means that you will receive bitcoins for your dollars. When you are selling BTC/USD the outcome is the opposite and you receive dollars for your bitcoins.

You should have submitted lowercase `'buy'` or `'sell'` instead. This is left as is in ccxt, should be fixed in your code.

Thanks!
