### ISSUE TITLE
privatePostDepositNew not a function

### ISSUE THREAD

**Issue by jaybutera** [ccxt/ccxt#2566]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: mac osx
- Programming Language version: js
- CCXT version: 1.12.159
- Exchange: bitfinex2
- Method: fetchDepositAddress

privatePostDepositNew is not a function according to the node compiler. grep search in root only found results with it (pPDN) being called as a function, no function definitions were found.

**Comment by kroitor** [comment]
> grep search in root only found results with it (pPDN) being called as a function, no function definitions were found.

You won't find function definitions by doing grep because most of those methods are defined implicitly, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods. In other words, those functions don't exist in code and they are added dynamically and only begin existing in runtime.

Implicit methods are also explained here: https://github.com/ccxt/ccxt/issues/237#issuecomment-332354313.

I've added a warning and fixed the `.has['fetchDepositAddress'] = false`  property for bitfinex2, as it does not have fetchDepositAddress implemented yet, and the one that is inherited comes from bitfinex v1. I've added an override for it as well with a more explicit message. 

Let us know if the above does not resolve this issue. We hope to implement Bitfinex2 fetchDepositAddress asap. Thanks!
