### ISSUE TITLE
createMarketBuyOrder() accepts 0 as an amount

### ISSUE THREAD

**Issue by jorijnsmit** [ccxt/ccxt#2573]
`createMarketBuyOrder()` does not come back with an error when trying to buy something with amount of `0`, but instead tries to communicate this to the exchange. Why?

(macOS, Python, v1.12.162, `binance`, `createMarketBuyOrder()`)

**Comment by jorijnsmit** [comment]
Note I am not parsing it `0` but an amount close to it which, if I understand it correctly, is then deducted to 0 by its internal calling of `amountToLots()`.

**Comment by mkutny** [comment]
Some exchanges do accept `0` as a parameter, so why would ccxt reject that?

I mean, if binance does not allow `0` then it'll reject and ccxt throw `InvalidOrder`. Does this behavior hurt in some way?

**Comment by jorijnsmit** [comment]
It feels unnecessary and a waste of resources to actually communicate it to the exchange. I did not however realise some exchanges do accept `0` as a parameter, even though this makes me wonder what use that would have!

**Comment by kroitor** [comment]
> createMarketBuyOrder() does not come back with an error when trying to buy something with amount of 0, but instead tries to communicate this to the exchange. Why?

Mostly because we are a thin wrapper. We do not want to mask exchange functionality – in other words, if you submit those params – we won't decide if they are worthy to send or not. If you don't want your args passed to the exchange – just don't call that method with zero ) We will consider adding optional layers of client-side protection later.

> this makes me wonder what use that would have!

Many exchanges do not distinguish market orders from other orders. They accept zero for a price of an order to designate that it's a market order – that is common among the exchanges themselves. Also, many exchanges mimic market orders with limit orders, and most often a limit sell order with price 0 will be closed for best market prices from the orderbook.

Hope this answers your question, let us know if not. Thx!
