### ISSUE TITLE
Is there any way to set the price to 'ask' using bittrex exchange?

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#2579]
- OS: ubuntu
- Programming Language version: python
- CCXT version: last
- Exchange: bittrex
- Method: execute_order

Since bittrex only has limit order types there is not way to set a market order. 
But, if I want to be sure that the order is executed, is there any way to set the price to the 'ask' amount in the order_book, without requesting the full order_book previously?

**Comment by kroitor** [comment]
@fedecaccia if I get you correctly, you actually want a market order (*"Ask"* means buy for best available price, that is market price and up). 

Despite that Bittrex does not support market orders directly, there's still a way to simulate them, you just need to place the order at a price close to zero or at a very high price, depending on the direction of your trade. 

Think what would the exchange do, if you sell 1 BTC for a price of $1. A normal exchange will not sell your bitcoin for a dollar, because there exist bidders in the orderbook that are willing to pay you more ($8000 or more) for your bitcoin. 

So, a normal exchange will start closing your order for best price for you starting from the top of the opposite orderbook stack, if you are doing it far worse than current market price. 

If you wanted to buy 1 BTC for a market price, you would then put your bid at a price of $1million for one bitcoin, and a normal exchange will then sell a bitcoin to you from a seller that is willing to take less than $1million from you  and will sell for the market price at $8000. So, if you are selling, sell for a very low price, if you are buying, then buy for a very high price – in both cases you will get the actual market price from a normal exchange.

**Whenever I say "normal exchange" I'd suggest you to test if the exchange in question is "normal" with a very small amount than is not significant to lose, for testing. Not all exchanges work normally, but most of the major ones are ok. Anyway, use this method at your own risk and do the testing.**

Hope this answers your question.

**Comment by fedecaccia** [comment]
Thanks kroitor!
