### ISSUE TITLE
Expose method to retrieve default limit/count for fetch_trades

### ISSUE THREAD

**Issue by JoshVarty** [ccxt/ccxt#2590]
I am trying to log all of the trades across various exchanges. Every few minutes I use `fetch_trades()` to query and log their recent trades. When calling this method I see that different exchanges use different default limits. 

For example, `fetch_trades()` on Bithumb calls: 
`https://api.bithumb.com/public/recent_transactions/BCH?count=100`

While Bitfinex calls:
`https://api.bitfinex.com/v1/trades/BCHBTC?limit_trades=50&timestamp=1523817293`

Bithumb uses a default limit of `100` while Bitfinex uses a defaul limit of `50`. It would be helpful to have these values exposed somewhere. Ideally we would be able to see both:
 - Default limit
 - Max limit

Currently some of the max/default limits are documented in comments:
https://github.com/ccxt/ccxt/blob/eb995c0ff42620877c85a98de2026d2ca7a54e51/python/ccxt/async/bithumb.py#L224-L231

**Comment by mkutny** [comment]
In addition, some of them report first trades (starting from Y2014, so you need to move ahead to fetch all trades) while some recent ones (so you need to go backwards in time).

Some of them allow tying trades by trade id, some of them return paginated output, some of them ignore `since` parameter altogether.

So the task of "fetching trades for a period" becomes quite cumbersome, much easier said than done.

**Comment by kroitor** [comment]
Yeah, for now we still have to deal with the exchanges' differences in an exchange-specific manner, but I hope to add more unification to it, after adding the notorious WS support...

**Comment by ttodua** [comment]
Just a note for closing of this issue - this will be addressed after [`Features`](https://github.com/ccxt/ccxt/issues/6772) functionality is implemented.
