### ISSUE TITLE
ingest old data from market

### ISSUE THREAD

**Issue by SiHyeong** [ccxt/ccxt#2596]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10 64-bit
- Programming Language version: Python 2.7 and 3.5
- CCXT version: 1.12
- Exchange: Bithumb(BTC/KRW), Coinone(BTC/KRW)
- Method:

Hello, when I use this function,

"exchange.fetch_ohlcv("ETH/KRW", '1h', from_timestamp)

other markets provide about more than 1 month. But coinone and bithumb only provide one day data when I give from_timestamp like

"from_datetime = '2017-09-01 00:00:00'
from_timestamp = exchange.parse8601(from_datetime)"

Is it problem of ccxt ohlcv or currency market?

**Comment by kroitor** [comment]
Hi!

This is documented here: 

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-emulation

When the method is emulated, the OHLCV is built from a log of trades, which usually has something like 100-1000 last trades... This is a limitation of the exchange, that does not have a method for OHLCV in the API.

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

> There's a limit on how far back in time your requests can go. Most of exchanges will not allow to query detailed candlestick history (like those for 1-minute and 5-minute timeframes) too far in the past. They usually keep a reasonable amount of most recent candles, like 1000 last candles for any timeframe is more than enough for most of needs. You can work around that limitation by continuously fetching (aka REST polling) latest OHLCVs and storing them in a CSV file or in a database.

> Is it problem of ccxt ohlcv or currency market?

Most often it is a limitation of the exchange, however, this my also be due to a missing implementation unified in ccxt (you can still do that with implicit methods until this is unified completely), or this may also be due to a bug.

We hope to enhance the workings of fetchOHLCV by using their website charting endpoints for some exchanges where possible.

Let us know if it does not answer question. Thx!

**Comment by SiHyeong** [comment]
Thank you for the kind answer! 
I will try figure out more detail about endpoints.

**Comment by kroitor** [comment]
@SiHyeong i'd recommend to read the entire Manual, it will save you a lot of time, really!
