### ISSUE TITLE
Question: Is there any library/script to analyse price pattern? 

### ISSUE THREAD

**Issue by microSoftware** [ccxt/ccxt#2638]
Hello, 

First I would like to say thank you for this amazing library. This is really a useful and amazing project. 

This is not CCXT directly related but I know there are lot of coders/traders and it's probably something that can be useful for other people as well.

My question: **Is there any library/script to analyse price pattern (bullish/bearish/candlestick...)?**

There is lot of stock screener that analyse bullish/bearish/candlestick pattern. I wonder if they all develop their in-house algo or there is a library out-there I didn't find? 

CCXT is perfect to get price in real-time but then you need to analyse this data. Did you develop your own algo?

Thank you,

**Comment by j0e1in** [comment]
https://www.tradingview.com/chart/ is a good place to start. You can write your own strategy by using its pine script to quickly experiment your ideas. Since it has built-in backtest system, you can immediately see the performance of your algorithm. Plus, the platform has a large community that people share their scripts openly. 
Once you have come up with something decent, you can convert your pine script into python using numpy and pandas (I also use ta-lib https://github.com/mrjbq7/ta-lib) with very few changes (and/or -> &/|  etc.), and you can start trading. Personally, I wrote my own backtest system to test these algorithms again and find optimal parameters before start trading.

Disclaimer: I have no association with Tradingview, I just love the platform, and I only use free version, since it's enough for me.

**Comment by microSoftware** [comment]
Thank you for your complete answer. I looked into TA-lib and it exactly what I was looking for. There is so much pattern recognition and indicator. It's more than I could dream of ;)
