### ISSUE TITLE
Missing BItfinex /position/close private method

### ISSUE THREAD

**Issue by j0e1in** [ccxt/ccxt#2640]
- OS: Ubuntu
- Programming Language version: Python
- CCXT version: 1.13.26
- Exchange: Bitfinex

Bitfinex should have a method called `private_post_position_close` / `PrivatePostPositionClose` to request this endpoint: https://bitfinex.readme.io/v1/reference#close-position

**Comment by kroitor** [comment]
> Can you give an example? pls

```Python
mbp:python igorkroitor$ python3
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> bitfinex = ccxt.bitfinex({'apiKey':'YOUR_API_KEY', 'secret':'YOUR_SECRET', 'enableRateLimit': True})
>>> from pprint import pprint
>>> pprint(dir(bitfinex))
['__class__',
 ...
 'privatePostPositionClose',
 ...
 'private_post_position_close',
 ...
 'ymdhms']
>>> bitfinex.private_post_position_close({'position_id': 12345})
```

https://docs.bitfinex.com/v1/reference#close-position

<img width="1176" alt="screen shot 2018-10-08 at 14 44 00" src="https://user-images.githubusercontent.com/1294454/46607176-a7c9d780-cb08-11e8-9b92-25bb7b3ddbf7.png">

**Comment by terrorizers** [comment]
I have tried exactly that https://github.com/ccxt/ccxt/issues/2764#issuecomment-427583232 but doesn't works, even if I do `params = { 'type': 'market' }` and `bitfinex.private_post_position_close({'position_id': 1779}, params` or even `bitfinex.private_post_position_close({'position_id': 17798, 'type': 'market'})` since it is a margin order...

**Comment by kroitor** [comment]
@terrorizers do you have an open position for closing in the first place?

**Comment by terrorizers** [comment]
is this a new kind way of insulting? 

```
order = bitfinex.create_order('BTC/USDT', 'market', 'buy', 0.002, None, { 'type': 'market' })

In [214]: bitfinex.private_post_position_close({'position_id': int(order['id'])})
---------------------------------------------------------------------------
ExchangeNotAvailable                      Traceback (most recent call last)
<ipython-input-214-92d21a05d9ea> in <module>()
----> 1 bitfinex.private_post_position_close({'position_id': int(order['id'])})

/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py in request(self, path, api, method, params, headers, body)
    360 
    361     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
--> 362         return self.fetch2(path, api, method, params, headers, body)
    363 
    364     @staticmethod

/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py in fetch2(self, path, api, method, params, headers, body)
    357         self.lastRestRequestTimestamp = self.milliseconds()
    358         request = self.sign(path, api, method, params, headers, body)
--> 359         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    360 
    361     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    445         except HTTPError as e:
    446             self.handle_errors(response.status_code, response.reason, url, method, headers, http_response)
--> 447             self.handle_rest_errors(e, response.status_code, http_response, url, method)
    448             self.raise_error(ExchangeError, url, method, e, http_response)
    449 

/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py in handle_rest_errors(self, exception, http_status_code, response, url, method)
    467                     error = DDoSProtection
    468         if error:
--> 469             self.raise_error(error, url, method, exception if exception else http_status_code, response)
    470 
    471     def handle_rest_response(self, response, url, method='GET', headers=None, body=None):

/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py in raise_error(self, exception_type, url, method, error, details)
    342             error = str(error)
    343         output = ' '.join([self.id] + [var for var in (url, method, error, details) if var is not None])
--> 344         raise exception_type(output)
    345 
    346     def throttle(self):

ExchangeNotAvailable: bitfinex https://api.bitfinex.com/v1/position/close POST 404 Client Error: Not Found for url: https://api.bitfinex.com/v1/position/close 
```

**Comment by kroitor** [comment]
> is this a new kind way of insulting?

Not really, it's a way of solving issues quickly saving time for everyone. That's mostly your time, by the way, but mine as well.

Having your code and verbose output, it's clear that what you're trying to do is not in line with how exchanges actually work. You can't open a market order and close it. Market orders cannot be closed in the first place, because they don't stay open. They are closed immediately. Only limit orders can be closed afterwards (and, only if they are still open). But that's just a half of the story.

The second half is that you seem to be confusing positions with orders. You can't take an id of an order (returned from create_order) and pass it to a method for closing positions by position id. This is what you're actually trying to do. Instead, you should rather open a margin position, and then close it, when you feel necessary. You should open a position with a method for opening positions (not with a method for opening orders). And you should get a list of your positions with a certain method for listing your positions. You will quickly find the actual names of methods for managing your positions, if you read the docs for the exchange in question and then do this:

```Python
>>> import ccxt
>>> bitfinex = ccxt.bitfinex({'apiKey':'YOUR_API_KEY', 'secret':'YOUR_SECRET', 'enableRateLimit': True})
>>> from pprint import pprint
>>> pprint(dir(bitfinex))
```

Does this answer your question?

**Comment by terrorizers** [comment]
ok yes i confuse badly, but I don't see a close_open_positions there, nor a fetch_open_positions to get id, my problem is that I try to close an open position doing a new one with the opposite side and same amount but that doesn't works because the amount is less cause fee, so I'm looking for the right way to close a position, and I don't find it there.

yes, sorry you are not insulting, is that that I feel I'm loosing a lot of time to do a so basic thing, and this get me mad to the least

**Comment by kroitor** [comment]
> but I don't see a close_open_positions there, nor a fetch_open_positions to get id

Have you tried actually doing this?

```Python
>>> import ccxt
>>> bitfinex = ccxt.bitfinex({'apiKey':'YOUR_API_KEY', 'secret':'YOUR_SECRET', 'enableRateLimit': True})
>>> from pprint import pprint
>>> pprint(dir(bitfinex))
```

Because, it's there:

```
 'private_post_position_claim', // to claim your position
 'private_post_position_close', // to close your position
 'private_post_positions', // to get a list of your positions with their ids
```

There's just three methods that have the word "position" in them, and all of them are listed there. So, to get an id of an open position, you need to use `private_post_positions`:

```
>>> import ccxt
>>> bitfinex = ccxt.bitfinex({'apiKey':'YOUR_API_KEY', 'secret':'YOUR_SECRET', 'enableRateLimit': True})
>>> positions = bitfinex.private_post_positions()
```

That will return your active (open) margin positions, if any.

**Comment by terrorizers** [comment]
ok, seems I need to sleep way more! :/ thanks XD
