### ISSUE TITLE
MacOS install ccxt report an error

### ISSUE THREAD

**Issue by Kenmmm** [ccxt/ccxt#2654]
- OS: MacOS
- Programming Language version: Python3
sudo pip3 install ccxt
error
Requirement already satisfied: ccxt in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ccxt-1.13.36-py3.5.egg
Collecting setuptools>=38.5.1 (from ccxt)
  Could not fetch URL https://pypi.python.org/simple/setuptools/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement setuptools>=38.5.1 (from ccxt) (from versions: )
No matching distribution found for setuptools>=38.5.1 (from ccxt)

**Comment by kroitor** [comment]
Whats your `python3 --version` ? It requires 3.5.3+ for asyncio. Also it seems that you have a problem accessing https://pypi.python.org/simple/setuptools/ with pip from your machine (most likely due to old certificates or pyopenssl overriding your certificates). Can you post `pip3 show pyopenssl`. If it's there, then deinstall it and then retry again. You can then reinstall it again later.
