### ISSUE TITLE
bittrex ohlcv bugfix

### ISSUE THREAD

**Issue by marcoracer** [ccxt/ccxt#2667]
CCXT: 1.13.42     EXCHANGE: Bittrex
The Bittrex v2 api answer returns a list with ascending timestamps, but as the main exchange expects the list of ohlcv with descending order, the final result doesn't agreed with the expected result.
To fix this one must only reorder the reorder the request answer before call the parse_ohlcvs!

**Comment by kroitor** [comment]
> but as the main exchange expects the list of ohlcv with descending order, the final result doesn't agreed with the expected result.

Not sure why would you expect descending order, we return all lists sorted in ascending order from CCXT. This is logical with historical charting data, you never draw it backwards. I've added this to the Manual, here: https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-structure

Because this library is still a work in progress, there still may be inconsistencies with the ordering, as described here:
- https://github.com/ccxt/ccxt/issues/987
- https://github.com/ccxt/ccxt/issues/2416

We hope to resolve all inconsistencies asap and we will be thankful for your reports.

Let us know if this does not answer your question.
