### ISSUE TITLE
How to get the order id when RequestTimeout received and the order closes immediately 

### ISSUE THREAD

**Issue by AvishaiW** [ccxt/ccxt#2698]
Hi,

The environment we are using:
- Programming Language version: Python 
- CCXT version: 1.12.131
- Method: create_order

We are trying to figure out what is the best way to handle `RequestTimeout` during the call to `create_order`.
We've read the docs [describing this](https://github.com/ccxt/ccxt/wiki/Manual#requesttimeout) 
but there are still some un-clarities.
In the case in which a `RequestTimeout` occurs and the order closes immediately, how can the order-id be received? The `fetch_balance` call, as proposed on the docs, does not include the entire required info of course.

**Comment by kroitor** [comment]
> In the case in which a RequestTimeout occurs and the order closes immediately, how can the order-id be received?

This can be done in a few ways:

1. If `has['fetchOrders']` is true, it should return a full list of orders, including the closed one.
2. If `has['fetchOrders']` is false, but `has['fetchOpenOrders']` is true and `has['fetchClosedOrders']` is true, you fetch open orders and if there are no open orders, then you can fetch closed orders to find it there.
3. You can use the balance as a hint: if it has changed, some trade within your order happened, so the order might already be closed fully or partially.
4. In absence of the above, or, alternatively, you can fetchMyTrades and get the order id from there.

Let us know if it does not answer your question. Thx!

**Comment by AvishaiW** [comment]
Thanks for the quick reply.
We have the following questions:
1. When calling `fetch_orders` for the following case, the command didn't include the immediately closed order. Same for calling `fetch_closed_orders`.
2. We wanted to use `fetch_my_trades` however this in not supported for all exchanges (is there any workaround?)

**Comment by kroitor** [comment]
> When calling fetch_orders for the following case, the command didn't include the immediately closed order. Same for calling fetch_closed_orders.

This will only work if `has['fetchOrders']` or `has['fetchClosedOrders']` are `true` and not `'emulated'`. See https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties for details.

The truth is: many exchanges **have no means** of restoring a timed-out order due to their poor API (most of them will provide an endpoint for open orders and that's it).

> We wanted to use fetch_my_trades however this in not supported for all exchanges (is there any workaround?)

We are adding the missing implementations as soon as we can, and, in the absence of a unified method you can use an implicit method for exchange-specific jobs: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- #71 
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#pending-tasks

> however this in not supported for all exchanges

Your contributions are welcome, btw! ) We appreciate all help. Thx!

**Comment by AvishaiW** [comment]
Thanks a lot!
