### ISSUE TITLE
Speed of API Calls

### ISSUE THREAD

**Issue by Domebone** [ccxt/ccxt#2731]
My rate limit is disabled, but when fetching the bid prices of all the pairs on binance I am maybe only printing one pair per second. 
- OS: Windows 10
- Programming Language version: Python 2.7.10
- CCXT version: 1.13.67
- Exchange: Binance
- Method: fetch_ticker

Here is my code:

binance=ccxt.binance()
binance_markets=binance.loadMarkets()
print("Loading Binance Pairs...")
binance_symbols=binance.symbols

for binance_symbols in binance_markets:
    print(binance_symbols)
    binance_bids=(binance.fetch_ticker(binance_symbols)['info'])

**Comment by kroitor** [comment]
> maybe only printing one pair per second.

You're doing it synchronously. Because you're doing the requests sequentially, and the exchange response takes some time to be sent back to you (approx 1 sec of total roundtrip), you won't be able to get them quickly. Use the async version of ccxt if you want more than one simultaneously (quickly):

- https://github.com/ccxt/ccxt/tree/master/examples/
- https://github.com/ccxt/ccxt/tree/master/examples/py
- https://github.com/ccxt/ccxt/blob/master/examples/py/async-tickers.py

**WARNING: Exchanges will not like it if you're hitting them too often and may ban you if you're not rate-limiting your requests.**

Hope this helps.

**Comment by Domebone** [comment]
Perfect, thank you
