### ISSUE TITLE
Binance order status question

### ISSUE THREAD

**Issue by rcolombo** [ccxt/ccxt#2750]
My question concerns Binance's `GET /api/v3/order` endpoint.

If you have an order that partially fills and then you cancel it, does Binance return that order as PARTIALLY_FILLED or CANCELED? In other words, is there a hierarchy of statuses when an order falls under multiple statuses? I'm finding this near-impossible to test since I don't know how to guarantee a partially filled order.

Apologies if this isn't the right medium for a question like this. If any of the repo owners feel this should be removed, please don't hesitate.

**Comment by mkutny** [comment]
> If you have an order that partially fills and then you cancel it, does Binance return that order as PARTIALLY_FILLED or CANCELED?

I would go through my trades and check on that but... it's not documented. It means that it could be either.

Even if my logs say that it's one or the other the next day it might turn around. So even if you figure out the right answer now I wouldn't suggest relying on it as it's too unpredictable.

>  I'm finding this near-impossible to test since I don't know how to guarantee a partially filled order.

One idea is to find a low volume market and place a taker order which exceeds the amount of resting order.

Let's say you have some BTC there and top orderbook entries for 'ICN/BTC' are: `[0.00016091, 8] / [0.00016157, 90]`. If you place a limit buy order for 100 ICN at 0.00016157 you'll get a partially filled order. Just cancel it immediately and check its status.

**Comment by mkutny** [comment]
BTW, logically I'd expect such an order to have `PARTIALLY_FILLED` status.

The reason is that exchanges tend to purge canceled orders frequently as they have almost no value but occupy space. On the other hand, partially filled orders are linked to trades.

To be on a safe side you may want to check `filled` property to ensure that order's been filled.

**Comment by kroitor** [comment]
I think @mkutny answered this question completely, unfortunately, I don't see canceled orders or partially filled orders in my Binance history to say which one it is. This is subject to testing in userland. Sorry for not being more helpful here.

**Comment by crossx4real** [comment]
when i cancelled a partially filled order programatically a few days ago, in binance the trade showed as 'partially', but my order status check on ccxt showed still returned "open"

Q: is ccxt able to return a partially filled order as "partial"? because i have not seen it till date.

**Comment by kroitor** [comment]
@crossx4real in most cases "partially" means a partially filled order that might still be open. Can you show your verbose output for the order in question? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by crossx4real** [comment]
@kroitor unfortunately i can't show the output, this was days ago.

**Comment by crossx4real** [comment]
so is the unified status for a partially filled order in ccxt "partially"?

**Comment by kroitor** [comment]
> @kroitor unfortunately i can't show the output, this was days ago.

Can you fetchOrder by order id in verbose mode?

> so is the unified status for a partially filled order in ccxt "partially"?

No, the unified status is either "open" (if not canceled and filled < amount), or "closed" (if closed, or filled == amount). 

The open that is a newly open order will have status === 'open' and filled = 0.
The partially filled but still open order will have status === 'open' and filled > 0 and filled < amount
The partially canceled order will have status === 'canceled' and filled > 0 and filled < amount
The fully closed order should have status === 'closed' and filled === amount.

There is no point in unifying the "partial" status – because it's ambiguous – can be either "partially filled" or "partially canceled". More about this nonsense here: https://github.com/ccxt/ccxt/pull/6741#issuecomment-609909341

**Comment by crossx4real** [comment]
lol, ok thanks, got it.
