### ISSUE TITLE
Can we add Cryptohub, Openledger?

### ISSUE THREAD

**Issue by kankando** [ccxt/ccxt#2793]
is it possible to add the following exchanges please?

**1. Cryptohub**
Website : https://cryptohub.online
Api : https://cryptohub.online/api/

**2. Openledger**
Website : https://openledger.io

**Comment by kankando** [comment]
@kroitor Thanks for looking into and Graviex seem there is a separate issue on it (#2538). Cryptohub and Openledger are new but there are lot of people who want to trade on those. That will also help to boost ccxt further if that being integrated.

**Comment by kankando** [comment]
hello, there is another npm package for graviex already.

https://www.npmjs.com/package/graviex

**Comment by An-Net** [comment]
**1. Cryptohub**

Trading floor is inactive since 21 September 2018:
- https://twitter.com/CryptoHubONLINE/status/1043163502628798464
- https://www.reddit.com/r/CryptoCurrency/comments/9i1wro/cryptohub_exchange_hacked_and_closing_down/ 

**2. Openledger**

Duplicate:
- https://github.com/ccxt/ccxt/issues/2377
