### ISSUE TITLE
Best PHP Practices on ccxt

### ISSUE THREAD

**Issue by IvoPereira** [ccxt/ccxt#2809]
Hello.

Thanks a lot for this awesome library. I've been reading a lot through the docs and examples these last days and I've started to mess with it. I've came up with a few questions that I hope you perhaps could help me to point in the right direction:

1. The PHP examples (https://github.com/ccxt/ccxt/tree/master/examples/php) should have their purpose documented somewhere. In last resort, it should be in the code. I may help with this with a PR if you are interested.

2. Which of the two available examples is the best practice when dealing with rate limiting?
- **Built-in Rate Limiting Poller** (https://github.com/ccxt/ccxt/blob/master/examples/php/built-in-rate-limiting-poller.php) - and why this one enables rate limit
- **React EventLoop with Rate Limiting** (https://github.com/ccxt/ccxt/blob/master/examples/php/react-eventloop-with-rate-limiting.php) - and this one doesn't?

Regarding the first option, I am curious too on why does a while loop is used on that approach. What is the logic behind it on dealing with rate limiting? What happens behind the scenes for it not to end in an infinite loop?

3. Still, in terms of rate limiting, how should we use it with a group of functions that should be executed sequentially? I am going to take one of the previous mentioned examples:

```php
$loop = React\EventLoop\Factory::create ();
// instantiate the exchange by id
$exchange = '\\ccxt\\poloniex';
$exchange = new $exchange ();
$tick_function = function () use ($exchange, $loop, &$tick_function) {
    global $exchange, $loop;

    // get balance
    // fetch ticker for market
    // place buy order
    // while order is not complete keep fetching order status
    // place sell order

    $loop->futureTick ($tick_function);
};
$loop->futureTick ($tick_function);
$loop->run ();
```

Would the listed sequence work in a single call of the rate limiter and a rate limit be applied between each call? Or should I separate each method into its own separate call of the EventLoop?

4. As seen in the previous question, would that be the best way to correctly handle a successfull order completion?

I need to be able to set a sell order, right after having my buy order filled. I am aware this is responsability of the developer, but in your opinion what are the best practices here?

How would I be able to keep querying if the order has already been filled so I could set up a sell order?

5. Suggestion out of issue scope: Have you ever wondered on a Discord server for ccxt? Might be worth checking.

Thanks a lot for all your hardwork. Hope to contribute soon.

**Comment by kroitor** [comment]
> The PHP examples should have their purpose documented somewhere.
> I may help with this with a PR if you are interested.

Your help will be really appreciated! 👍 

> Which of the two available examples is the best practice when dealing with rate limiting?

Depends on the application framework that you're using. It may be such that in some cases you better stick to the first, and in other cases you would want to use the second.

> Regarding the first option, I am curious too on why does a while loop is used on that approach. What is the logic behind it on dealing with rate limiting? What happens behind the scenes for it not to end in an infinite loop?

> Still, in terms of rate limiting, how should we use it with a group of functions that should be executed sequentially? I am going to take one of the previous mentioned examples:

> As seen in the previous question, would that be the best way to correctly handle a successfull order completion?

There's no generic way of doing it, it depends on your trading strategy, the order types, mostly. The library won't track the orders, so you have to poll `fetchOpenOrders`, `fetchClosedOrders` and `fetchMyTrades` to get the fill info.

You may want to read this about built-in rate limiting and "sequential vs async" requests: https://github.com/ccxt/ccxt/issues/1399.

> How would I be able to keep querying if the order has already been filled so I could set up a sell order?

The exchange won't like it due to nonce conflicts, in general they will not tolerate more than one private API request at a time. You can also use multithreading and synchronize/share the nonce with mutexes or atomic increments.

```PHP
while (true) {
   if ($ready_to_poll)
      poll();
   if ($ready_to_sell)
      sell();
}
```

Let me know if this does not answer your questions. Thx!

**Comment by IvoPereira** [comment]
Hello @kroitor! Thanks for replying so fast.

I am in mobile so I won't be quoting, just enumerating the points.

1. Regarding the first point I will surely contribute once I am able to correctly identify the examples and the specific usecases for each one.

2. Currently I am not using a framework at all, but I might use one if it does bring me some advantages. Which would be the best approach for a vanilla PHP usage?

3. To be honest I would prefer to do it sequentially. My trading strategy will only be executed 5 or 6 times a day, much probably in different hourly timeframes.

For each time I execute it, I would do what I have mentioned:

- get balance
- fetch ticker for market
- place buy order
- while order is not complete keep fetching order status
- place sell order

4. Regarding nonce conflicts and more than one private API request at the same time: well, as PHP is synchronous and I will not have (the chance is very low) the same trading strategy occurring at the same time, wrapping all my code in a unique rate limiting solution would work?

From what I have understood, the biggest bottleneck with this solution is when you expect to have simultaneous requests going in and the authentication is not able to correctly get the latest nonce to be changed?

5. Regarding discord, do you completely discard the idea or might check it later? I have seen it to work very well in these types of repos where community try to help each other overcoming daily challenges when using the repo.

Thanks once again.

**Comment by kroitor** [comment]
> Regarding nonce conflicts and more than one private API request at the same time: well, as PHP is synchronous and I will not have (the chance is very low) the same trading strategy occurring at the same time, wrapping all my code in a unique rate limiting solution would work?

Sure!

> From what I have understood, the biggest bottleneck with this solution is when you expect to have simultaneous requests going in and the authentication is not able to correctly get the latest nonce to be changed?

The problem is that the exchanges themselves will require a nonce number to be sent with each request, and that number has to increase continuously for each new request, so you have to synch that nonce number before sending your requests, if you're sending them simultaneously. In fact, there's no simultaneity in the requests, because the nonce in each request is unique, and the exchange 
won't accept the nonce if it goes backwards. This is documented here: https://github.com/ccxt/ccxt/wiki/Manual#authentication

Also, many exchanges will require a nonce number to be equal to current timestamp in seconds – and because each nonce number should be unique and growing – you usually use system clock to generate nonce numbers, but generating unique timestamp-nonces means, that you won't be able to send requests more frequently than once per second. Thus, no simultaneity from the very start. All requests are sequential, it just so happens that some of them may be executed quickly (from aside it looks like they were simultanous, but they weren't).

> Regarding discord, do you completely discard the idea or might check it later? I have seen it to work very well in these types of repos where community try to help each other overcoming daily challenges when using the repo.

Sorry, forgot to reply to this as well – we already have a gitter chatroom:

[![Gitter](https://badges.gitter.im/ccxt-dev/ccxt.svg)](https://gitter.im/ccxt-dev/ccxt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Welcome )
