### ISSUE TITLE
HTTP proxy not working in async mode

### ISSUE THREAD

**Issue by whchen8** [ccxt/ccxt#2826]
- OS: macOS 10.13.3
- Programming Language version: Python 3.6.5
- CCXT version: 1.13.133
- Exchange: okex, binance, ...
- Method: `fetch_ticker()`, ...

I'm hosting my own CORS server with an HTTP protocol. It does work in sync mode, but when I'm using **async** mode, it fails.

```python
import asyncio
import ccxt.async as ccxt

exchange = ccxt.binance({
    'enableRateLimit': True,
    'verbose': True,
    'proxy': 'http://myproxy/'
})

async def poll():
    while True:
        yield await exchange.fetch_tickers()

async def fetch_tickers():
    await exchange.load_markets()
    async for tickers in poll():
        # some output here

asyncio.get_event_loop().run_until_complete(fetch_tickers())
```

It raises `ccxt.base.errors.ExchangeNotAvailable` error and says:

```bash
ccxt.base.errors.ExchangeNotAvailable: binance http://myproxy/https://api.binance.com/api/v1/exchangeInfo GET [Errno 54] Connection reset by peer
```

It seems like an SSL issue. So, do I have to host my CORS with HTTPS protocol? But why it works in sync mode with the same proxy I set for the exchange?

**Comment by kroitor** [comment]
> It seems like an SSL issue. 

Most often, it is. See if you have pyopenssl, also Anaconda Python is known to have issues with OpenSSL compatibility...

> So, do I have to host my CORS with HTTPS protocol? 

This can help.

> But why it works in sync mode with the same proxy I set for the exchange?

Those are different HTTP implementations (async is using the `aiohttp`, sync is using `requests`), so the problem is most likely related to the differences in the setup (see `pip list`, `pip3 list`, and versions of modules in your virtualenvs).

Hope this answers your question. Let us know if not.
