### ISSUE TITLE
Bitmex create_order nonce exception

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#2854]
- OS:ubuntu 16.04
- Programming Language version:PHP
- CCXT version:1.14.4
- Exchange:bitmex
- Method:create_order
Some times it shows up, nonce not increace compare with last request nonce.

**Comment by kroitor** [comment]
Do you use any rate-limiting? Can you post your code?

**Comment by jackyxie** [comment]
`            $options = [
                'apiKey' => $api_info['accessKey'],
                'secret' => $api_info['secretKey'],

                //debug
                'verbose' => false,
                'enableRateLimit' => true,
                'timeout' => '1000',

                //curl proxy setting
                'curl_options' => [
                    CURLOPT_SSL_VERIFYPEER => false,
                    CURLOPT_SSL_VERIFYHOST => false,
                ],
            ];`

**Comment by kroitor** [comment]
> I have enableRateLimit on, when make a create_order request.

Can you please make it a snippet of code that I can copypaste and launch to reproduce your problem (a short, but a complete program) ? Otherwise it will be really hard to tell exactly.

Also, note, that `timeout` should be a number in milliseconds, not a string, so `'timeout' => '1000'`  is not a proper value for that option (one second is too short, and it should not be a string).

**Comment by jackyxie** [comment]
Thanks for point out the type of timeout, as the snippet of code as I have change already. If it show up again, I'll open the issue again.

**Comment by kroitor** [comment]
@jackyxie ok, feel free to reopen it if needed, just make sure to follow these recommendations very carefully https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue otherwise it will be really hard to help.
