### ISSUE TITLE
Websocket Code Contributions

### ISSUE THREAD

**Issue by TensorTom** [ccxt/ccxt#2899]
The websocket features have been on the roadmap since last year. In the interest of getting it done, I'd like to raise this issue for myself and others like me. I work with these exchange APIs constantly in my daily engineering. Though I'm historically not much for public Git repos (I don't tend to share), I'd be willing to contribute websockets code and work hours for this one. I can help you with the PHP and Python implements. Probably JavaScript as well but I'd rather stick to those two.

I'm relatively certain that many others share my sentiment. There is a possible caveat (On my part). I see in the [contrib file](https://github.com/ccxt/ccxt/blob/b2599376a74f0e622f35ddd19da89552b628ae4b/CONTRIBUTING.md) that you're transpiling some JS to PHP and Python. I'll need to look into this further but first things first. Can you point us to what websocket code there is currently?

**Comment by jdieks** [comment]
I'm also following this on a regular basis lately. There seems to be a lot of work going on on this fromt. Check out this thread: https://github.com/ccxt/ccxt/issues/56

**Comment by kroitor** [comment]
> I see in the contrib file that you're transpiling some JS to PHP and Python. I'll need to look into this further but first things first.

The [CONTRIBUTING](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md) is the most important doc in all this, as it explains how and why we organize the code the way it is in the repository. You should really read it very carefully from the very beginning to the end to understand how this library works internally. Reading the entire CONTRIB doc should be your first thing of all first things, if you're going to contribute ;)
 
The first real technical task is two write unified websocket code in three languages (JS, PHP, Python) for two exchanges (or, better, more than two exchanges of your choice). Once we have it – we can move on from there.

Key points:

- A websocket implementation in three languages for just one favourite exchange – isn't going to help us (GitHub has had enough of them for years already).
- A websocket implementation in one favourite language for two or more exchanges – isn't going to help us (also available on GitHub in all flavours).
- There's a ton of separate custom implementations on GitHub for each exchange in every language. Because they are separate in their design – they don't fit into this library. They won't work seamlessly in a language-agnostic or exchange-agnostic manner – neither of those "examples" really help.
- There's very little point in submitting "hey, here's my websocket code for Binance in Python, let's use it as the baseline in the library" – custom examples don't really help (we've got dozens of submissions of separate non-standardized implementations – that code is not reusable – it either breaks on another exchange or it is not capable of working in the same way with the same callflow in a different language).

> Can you point us to what websocket code there is currently?

All here: 
- #56 (the main WS thread)
- https://gist.github.com/kroitor/aabecc346a5bded6ead7a82205d8ffc1 (design considerations on WS in CCXT)

Let me explain:

The WS implementation is not yet ready in this library, because people think it's "easy" to just publish an example implementation in their favourite language for the favourite exchange and build from there. In fact, it isn't easy at all, you just have to comprehend the task in it's entirety first – we are writing *exchange-agnostic portable cross-platform cross-language unified code*, this is what makes this task hard and this is what makes up this library. 

We used to reply in this manner: just try unifying websocket code for any two exchanges in three languages taking into account the rules from the CONTRIBUTING doc (without having exchange-specific code in the base classes and without having language-specific code in the derived classes). Try implementing it in a portable way and let us know if you have any questions down the road. Nobody has returned alive since then yet ))

Hope this answers your question. Let us know if not.

I'd move this discussion to #56 if you don't mind (that post is worth reading in full, most of the above is explained there + some links to some code).
