### ISSUE TITLE
HADAX - Withdraw "Paramemter currency is invalid."

### ISSUE THREAD

**Issue by rsparrow** [ccxt/ccxt#2904]
- OS: OSX
- Programming Language version: JS
- CCXT version: 1.14.25
- Exchange: HADAX
- Method: withdraw

Getting the following error, I haven't had time to dig into it yet:

{ Error: hadax {"status":"error","err-code":"invalid-currency","err-msg":"Paramemter `currency` is invalid.","data":null}
    at hadax.handleErrors (.../node_modules/ccxt/js/huobipro.js:774:27)
    at response.text.then (.../node_modules/ccxt/js/base/Exchange.js:513:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeError] }

Note, the currency object on line 694 of huobipro.js the currency object's value is the following before the call:

{ id: 'BTC', numericId: undefined, code: 'BTC', precision: 10 }

**Comment by kroitor** [comment]
@rsparrow can you show verbose request info? Or tell which particular values you're using for the withdraw () call? Please, always submit your code with values visible (but without the keys), and verbose request and response as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. Otherwise it will be really hard to help.

**Comment by kroitor** [comment]
"paramemter"... Oh, Huobi...

**Comment by kroitor** [comment]
Fixed in #2646 https://github.com/ccxt/ccxt/commit/c9221d00ef4260386246267b94c2134f1f40e069
Thank yoU!
