### ISSUE TITLE
Found Errors on exchanges for method loadMarket and FetchOHLCV

### ISSUE THREAD

**Issue by davemg3** [ccxt/ccxt#2937]
Hello
Below some tests achieved on cctx exchanges . Done with 'since', 'timeframe'='1h', but without 'limit' as this parameter creates in some cases different other inconsistencies.
The exchange data seems to be accessible at least for current and previous candles , just it seems the output of CCTX dont follow the same guidelines for each. 

-Is there a reason?and are some alignment scheduled?
-Is there also a probability that data with their timestamp could be mixed ? (for ex with exchange BX.in.th, some candles are timestamped with future date)...

Tested around 09h30 with since=06:00:00, since=07:00:00, since=08:00:00, with **hasfetch=true**

**ACX**       : no candles 
**Binance**   : ok 
**bitbank**   : Exception publicGetPairCandlestickCandleTypeYYYYMMDD not found

**Bitfinex v2**: NOK, various behaviour at 2018-05-23 09:44:30 :
	since = 08:00:00 only received candle of current uncomplete hour 09:00:00
	since = 07:00:00 -> received array 07:00:00, 09:00:00 (missing intermediary candle)
	since = 06:00:00 -> received array 06:00:00 (only the 'since' candle)
   
**Bitlish**   : ohlcv is always array size =1 and ohlcv [0] is an array instead of a string causing exception Array to string conversion
**BitMarket** : Exception Undefined index: 1h (OK as this timeframe not provided)
**Bittrex** : ok

**Bit-Z**    : at 2018-05-23 09:45:44 with 
	since = 08:00:00, received date array  08:00:00 
	since = 07:00:00 => expected array  07:00:00, 08:00:00, received array  08:00:00 
	since = 06:00:00 => expected array  09:00:00, 10:00:00, 11:00:00 ,received date array  10:00:00, 11:00:00 

**Bleutrade**       : Exception {"success":false,"message":"INVALID_MARKET","result":null}
**BTCExchange** : Exceptionbtcexchange GET https://www.btcexchange.ph/api/ohlcdata 6 Could not resolve host: www.btcexchange.ph

**BTC Markets **     : nok, sometimes no candles
**BTCTurk** : no candles 
**CEX.IO**  : Exception Undefined variable: response

**COBINHOOD** : at 2018-05-23 09:45:34, ****
	since = previous hour 08:00:00 NOK no candles
	since =  07:00:00 ,received array 07:00:00, 08:00:00, 09:00:00 OK
	since =  06:00:00 NOK, no candles received

**CoinEx** :  no candles
**Ethfinex**: 
	since = hour before 08:00:00, NOK only received candle of current uncomplete hour 09:00:00 
	since = 07:00:00, NOK expected array  07:00:00, 08:00:00,received date array is  07:00:00, 09:00:00 (missing intermediary candle)
	since =  06:00:00 NOK,Expected array  06:00:00, 07:00:00, 08:00:00 ,  received array  08:00:00 

**Gatecoin** : ok 
**GDAX** : ok
**HitBTC v2** : ok

**Huobi** exception GET http://api.huobi.com/staticmarket/btc_kline_060_json.js 403 Forbidden, nginx

**Kraken** ok
**Kucoin** ok 
**Kuna** no candles
**OKCoin** ok
**OKEX** ok
**Poloniex** OK Exception Undefined index: 1h (not having timeframe 1h)
**TideBit** NOK : no candles(with timeframe '1h'), undefined ofset (with timeframe '60')

For now i guesss we need from client side to alternate params in fetching+add a filter to grap the candle data when sput out.

**Comment by DaveMG3** [comment]
Tested around 12h30 with since=11:00:00, since=10:00:00, since=09:00:00, with hasfetch='emulated'

**1BTCXE**  : Exception _1btcxe markets not loaded
**Bit2C**   : no candles
**BitBay**  : no candles
**Bithumb** : only candle of current uncomplete hour
**bitkk**   :  no candles

**Bitso**   : OK since=11:00:00, Expected date array  11:00:00 , received date array  11:00:00, 12:00:00 (uncomplete candle is present) .
OK for since=10:00:00, since=09:00:00 but uncomplete current candle is not present this time

**Bitstamp**: OK since 11:00:00 Expected date array  11:00:00 , received date array  11:00:00, 12:00:00
 NOK for since 10:00:00, , since=09:00:00 as always only receive previous hour candle and uncomplete current hour candle
 
**BL3P**    : OK  for since=11:00:00,10:00:00, since=09:00:00 (all previous and current candle present)
**BtcBox**  : Only candle of current uncomplete hour
**BTCChina** : NOK Exception GET https://plus-api.btcchina.com/market/trade?symbol=bcccny&start_time=1526992441176&end_time=1527078841176 503 
**BtcTrade.im,**: OK depending of since, not more than 2 candles before + current one

**BTC Trade UA**: NOK, various behavior  since=10:00:00, Expected date array  11:00:00 ,Received date array  11:00:00 
	 since=10:00:00, Expected date array  10:00:00, 11:00:00 , received date array  10:00:00 (only the 'since'  candle) 
	 since=09:00:00, Expected date array  09:00:00, 10:00:00, 11:00:00 , Received date array  09:00:00, 11:00:00, 12:00:00 (missing  intermediary candle)
	 
**BTCX** : Exception GET https://btc-x.is/api/v1/trade/btc/eur/1000 6 Could not resolve host: btc-x.is

**BX.in.th**  : NOK expected date array  11:00:00 , received date array  18:00:00, 19:00:00 (wrong hours sent. fetching was done around 12h30)
**C-CEX**     : Exception ccex null

**CHBTC**     : Exception{"result":false,"message":"\u670d\u52a1\u7aef\u5fd9\u788c"}
**ChileBit**  : no candles

**coincheck** : only candle of current uncomplete hour

**coinfloor** : OK for since = 11:00:00, Expected date array  11:00:00 , received date array  11:00:00, 
NOK for since 10:00:00 as received date array  10:00:00 (only send the candle at 'since' hour)

**Coingi**    : no candles
**CoinMate**  : only candle of current uncomplete hour
**coinnest**  : OK Send more than 2 previous candle+current one. 

**CoinOne**    : OK only current and previous candle whatever since
**Coinsecure** : Exception GET https://api.coinsecure.in/v1/exchange/trades 6 Could not resolve host: api.coinsecure.in
**CoinSpot** OK: Exception requires apiKey for all requests
**Cryptopia**  :no candles

**DSX NOK**    : For the 3cases, Only the send the 'since' candle and current uncomplete candle, not the ones between.
**EXMO**       : depending of fetching time, it can be only current uncomplete candle or current and previous candle

**EXX**        : no candles
**flowBTC**    : no candles
**FoxBit**     : no candles
**FYB-SE**     : no candles

**Comment by kroitor** [comment]
<img width="1505" alt="screen shot 2018-05-24 at 09 04 33" src="https://user-images.githubusercontent.com/1294454/40467208-9784e07e-5f31-11e8-95ca-9ec315862953.png">

**Comment by DaveMG3** [comment]
Hi  @kroitor ,
Instead of opening overwhelming issues, i put here some finding on new tested version in Python and PHP, so i can update the table when solved


Updated on : |   | 21/06/2018 |  
-- | -- | -- | --
**ccxt_id** | **Method** | **issue (45/119Exch), tested on   Python & PHP version** | **Comments** | **ccxt version**
bitlish | fetchOHLCV | Ccxt exception : array to string   conversion |   | 1.14.242
cex | fetchOHLCV | Ccxt exception : array to string   conversion |   | 1.14.242
cryptopia | fetchOHLCV | Cryptopia exposed '1h' candle   can start at any minute depending of fetching time | https://github.com/ccxt/ccxt/issues/3034 | 1.14.242
chbtc | fetchOHLCV | Emulated :   Exception{"result":false,"message":"\u670d\u52a1\u7aef\u5fd9\u788c"} |   | 1.14.242
bitmex | fetchOHLCV | Error on BTC/USD, Bitcoin   quantities are returned in Satoshis: 1 XBt (Satoshi) = 0.00000001 XBT   (Bitcoin). |   | 1.14.242
bleutrade | fetchOHLCV | Exception bleutrade   {"success":false,"message":"INVALID_MARKET","result":null} |   | 1.14.242
bithumb | fetchOHLCV | Issue with exploded volume | https://github.com/ccxt/ccxt/issues/3178 | 1.14.242
coinex | fetchOHLCV | No candles while   fetchOHLCV=1  timeframe exist |   | 1.14.242
bitfinex2 | fetchOHLCV | Ok, but some pairs doesn’t send   candles |   | 1.14.242
allcoin | load_markets | Exception when trying to load exchange:   count(): Parameter must be an array or an object that implements Countable | API updated on their  website, so the support for AllCoin is   currently broken in CCXT. https://github.com/ccxt/ccxt/issues/2880 | 1.14.242
yunbi | load_markets | Exception when trying to load exchange:   yunbi GET https://yunbi.com/api/v2/markets.json 47 Maximum (20) redirects   followed |   | 1.14.242
btcturk | load_markets | BTC Turk on 1h timeframe for its   listed pairs dont send any data except every day at 00:00:00 where it   provides a bunch of false data. https://github.com/ccxt/ccxt/issues/3141 |   | 1.14.242
coinegg | load_markets | Exception when trying to load   exchange: coinegg GET   https://www.coinegg.com/coin/btc/allcoin?t=1529541495768 503 not accessible   from this location at the moment | To  be tested with cloudflare   https://github.com/ccxt/ccxt/issues/2880 | 1.14.242
coingi | load_markets | Exception when trying to load   exchange: coingi GET https://coingi.com 503 not accessible from this location   at the moment | To  be tested with cloudflare | 1.14.242
livecoin | load_markets | Exception when trying to load   exchange: Undefined index: |   | 1.14.242
jubi | load_markets | ExchangeError :   {"result": false, "code":"405"} |   | 1.14.242
tidebit | fetchOHLCV | Type OHLCV = 1 but No candles   1h, 1d |   | 1.14.242
acx | fetchOHLCV | Type OHLCV = 1 but No candles   1h, 1d |   | 1.14.242
kuna | fetchOHLCV | Type OHLCV = 1 but No candles   1h, 1d |   | 1.14.242
anxpro | fetchOHLCV | No Type OHLCV implemented |   | 1.14.242
coinbase | fetchOHLCV | No Type OHLCV implemented |   | 1.14.242
coinexchange | fetchOHLCV | No Type OHLCV implemented |   | 1.14.242
getbtc | fetchOHLCV | No Type OHLCV implemented |   | 1.14.242
lykke | fetchOHLCV | No Type OHLCV implemented |   | 1.14.242
coincheck | fetchOHLCV | Emulated : only candle of   current uncomplete hour |   | 1.14.242
_1btcxe | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
bitbay | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
chilebit | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
flowbtc | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
foxbit | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
fybse | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
fybsg | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
lakebtc | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
surbitcoin | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
urdubit | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
vbtc | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
virwox | fetchOHLCV | Emulated and no candles (tested   for 1h, 1d) |   | 1.14.242
coinsecure | fetchOHLCV | Emulated : Exception GET   https://api.coinsecure.in/v1/exchange/trades 6 Could not resolve host:   api.coinsecure.in | Exchange seems to be down due to   hacking and loss fund | 1.14.242
huobicny | load_markets | Exception : huobicny GET   https://be.huobi.com/v1/common/symbols 28 Operation timed out after 10000   milliseconds with 0 bytes received | HuobiCNY down and replaced by   HuobiPro? (which has itself all pairs of CMCap) | 1.14.242
huobi | fetchOHLCV | ExchangeNotAvailable : GET   http://api/huobi.com/staticmarket/btc_kline_060_json.js 404 not accessible   from this location at the moment | Huobi down and replaced by HuobiPro ?(which   has itself all pairs of CMCap)(2 symbols sent by load exchange : BTC/CNY,   ETC/CNY) | 1.14.242
okcoincny | fetchOHLCV | Ccxt RequestTimeout :get   https://www.okcoin.cn/api/v1/kline.do?sybol=bcc_cny&type=1hour&since=1529589599000   28 Connection timed out after 1000 millisecondes with 0 bytes received | OkCoinCNY down and replaced by   OkCoinUSD ?(which has itself all pairs of CMCap) | 1.14.242
btcchina | load_markets | Exchange not available : get   https://data.btcchina.com/data/trades?market=ltcbtc 503 | BTCChina shutdown on September   30th, 2017 | 1.14.242
coolcoin | load_markets | Exception when trying to load   exchange: coolcoin GET   https://www.coolcoin.com/coin/eth/allcoin?t=1529541498470 500 not accessible   from this location at the moment | Exchange down | 1.14.242
btcexchange | fetchOHLCV | Exception GET   https://www.btcexchange.ph/api/ohlcdata 6 Could not resolve host:   www.btcexchange.ph | Exchange is down | 1.14.242
btcx | fetchOHLCV | Exchange not available get   https://btcx.is/api/v1/trade/btc/eur/1000 6 could not resolve host: btc-x.is | Exchange is down | 1.14.242

**Comment by jorijnsmit** [comment]
Bleutrade returns the same error for all of its markets when using `fetchOHLCV()`: `bleutrade {"success":false,"message":"INVALID_MARKET","result":null,"explanation":null}`

**Comment by kroitor** [comment]
@mw130 there's been some progress and some exchanges from the above list are already fixed, however, it's hard to resolve this entire issue at once, sorry, this is the reason why we keep them separate... I'll take a look into Bleutrade as soon as I can...

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/4406.
Closing this for now until we have a followup. We suggest to keep issues separate per exchange in the future.
