### ISSUE TITLE
Failed to load markets for allcoin – they changed their API

### ISSUE THREAD

**Issue by whchen8** [ccxt/ccxt#2962]
- OS: macOS 10.13.3
- Programming Language version: Python 3.6.5
- CCXT version: 1.14.71
- Exchange: allcoin
- Method: `load_markets()`

Failed to load markets for allcoin. Guess the original endpoint is no longer in force.

```bash
ccxt.base.errors.ExchangeNotAvailable: allcoin
  https://www.allcoin.com/Home/MarketOverViewDetail/
GET 500 Server Error: Internal Server Error for url:
  https://www.allcoin.com/Home/MarketOverViewDetail/
```

**Comment by DaveMG3** [comment]
Hi,
https://github.com/ccxt/ccxt/issues/2880

**Comment by hroff-1902** [comment]
Okay (moving discussion here) -- Allcoin is still broken. Liqui has terminated operation, for example. There are some more broken... Would not it be nice to mark such exchanges somehow... I see, you have the Exchange status dict returned by fetch_status, so those exchanges may be hardcoded as 'broken' in the status field so that the users of the ccxt lib could check the list of all exchanges and exclude those of them that are known to be broken or defunct.

**Comment by kroitor** [comment]
> Would not it be nice to mark such exchanges somehow...

)) https://github.com/ccxt/ccxt/issues/5285 

Your help is welcome )

Liqui is about to be delisted. And we have delisted many non-working exchanges the previous week.
