### ISSUE TITLE
Javascript syntax error when running from the browser

### ISSUE THREAD

**Issue by tomastelensky** [ccxt/ccxt#2963]
I just tried a simple example that you presented here https://github.com/ccxt/ccxt/issues/880 :

```html
<!DOCTYPE HTML>
<html>
<head>
    <title>CCXT Basic example for the browser</title>
    <script type="text/javascript" src="https://unpkg.com/ccxt"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function(){
                alert ('ccxt version ' + ccxt.version + ' supporting '+ ccxt.exchanges.length.toString () + ' exchanges');
        });
    </script>
</head>
<body>
<p>Hello, CCXT!</p>
</body>
</html>
```

On the console, I got these errors:

```
Uncaught SyntaxError: Unexpected identifier   _1broker.js:71 
ccxt-basic-example.html:8 Uncaught ReferenceError: ccxt is not defined(anonymous function) @ ccxt-basic-example.html:8
```

In the link above (along with the example), you wrote "CCXT is designed to work from the browser (where CORS is supported, or via a CORS-proxy)", so I wonder where is the problem.

Thanks a lot!

- OS: Windows XP SP3, Google Chrome
- Programming Language version: ?
- CCXT version: pulled 2018-05-25
- Exchange: NA
- Method: NA

**Comment by kroitor** [comment]
When you say *"I just tried a simple example"* can you please tell exactly what you did to try it?

Because I've opened the `basic.html` file with my Chrome Version 66.0.3359.139 (Official Build) (64-bit) on Mac (`File → Open`, then picked the file from a cloned ccxt repository on my local drive), and here it is working:

<img width="1088" alt="screen shot 2018-05-27 at 14 12 51" src="https://user-images.githubusercontent.com/1294454/40585252-25610624-61b8-11e8-825f-fcfcd86b8299.png">

<img width="1088" alt="screen shot 2018-05-27 at 14 13 08" src="https://user-images.githubusercontent.com/1294454/40585254-2988f18a-61b8-11e8-9ec6-0f4fbd6ed88e.png">

**Comment by tomastelensky** [comment]
I just openned it in Chrome.

**Comment by kroitor** [comment]
@tomastelensky Looking at your OS version, I'm really afraid of asking this, but... which version of Chrome is it?

**Comment by tomastelensky** [comment]
49.0.2623.112 m :-) It doesn't update any more :-)

**Comment by kroitor** [comment]
I'm afraid, chrome 49 does not support the needed feature subset of ES6... You will either have to find a way to run it in a newer browser or to repack it in ES5-only mode with Babel. Unfortunately, I can't really help beyond this at the moment. Closing this for now, let me know if you still have difficulties with it even with newer browsers. Thx!
