### ISSUE TITLE
New Exchange: Crex24

### ISSUE THREAD

**Issue by minidantebtc** [ccxt/ccxt#2968]
Please add https://crex24.com to CCXT.

Thanks for the awesome work.

**Comment by retroporno** [comment]
You could use their new API 2.0. 
Works fine: https://docs.crex24.com/trade-api/v2/

**Comment by josemejiasji** [comment]
+1

**Comment by is0initial** [comment]
I really need support Crex24 in CCXT.

**Comment by is0initial** [comment]
+0.24 ltc  * 2   - it's me.
Thanks for the awesome work. [2]

**Comment by is0initial** [comment]
+0.24 ltc - it's me.
Thanks for the awesome work. [3]

**Comment by is0initial** [comment]
+0.24 ltc - it's me.

**Comment by is0initial** [comment]
+0.24 ltc - it's me.

**Comment by is0initial** [comment]
@kroitor, Thanks for the awesome work. [4]

**Comment by is0initial** [comment]
+0.24 ltc - it's me.

**Comment by is0initial** [comment]
+0.24 ltc - it's me.

**Comment by kroitor** [comment]
@is0initial my apologies for the long wait for this one, I was again a bit overloaded with maintenance tasks, but I'm going to launch the work on Crex24 very soon, hopefully.

**Comment by scottie** [comment]
would be great to see

**Comment by garik-code** [comment]
> It is added in CCXT 1.17.442. Don't forget to update your version of the library. We will be happy if you help us test it and report bugs if any )
> 
> @is0initial thanks so much again for your contributions, we appreciate your support!
> 
> Cheers!

У меня проблема, при добавлении ключей ошибка: "{ Error: crex24 {"errorDescription":"Failed to verify request signature."}"

TRANSLATE: I have a problem when adding keys error: "{Error: crex24 {" errorDescription ":" Failed to verify request signature. "}" 

HELP!))

**Comment by kroitor** [comment]
@garik-code I can't reproduce it on my side (works in JS, PHP and Python)... need to see the code to be able to repeat it (without your keys of course)... Unfortunately, you didn't follow the guides on submitting an issue:
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

... so we don't know which version of the library it is, which language you're using, etc... So, we can't really help you, unless you provide the missing details (and, please, follow the guides as precisely as you possibly can – to a word, literally).

You might want to check your keys against the https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting section as well.

This works on my side:

```Python
# Python
import ccxt
exchange = ccxt.crex24({
    'apiKey': 'YOUR_API_KEY',  # 36 hexadecimal characters with dashes
    'secret': 'YOUR_SECRET',  # base64 secret with '=' and '/' inside, 88 chars in my case
    'enableRateLimit': True,  # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
print(exchange.fetch_balance())
```

The most common pitfall for authorization is double-clicking to copy-paste the base64 secret. Because double-clicking selects text up to a word boundary, you often miss the characters after the slash (`/`) or the base64-ending (`==` at the end of the string isn't selected by a double-click). So the user might think that it has been copied, but in fact, it wasn't copied properly. You have to try a fresh new keypair (make sure you haven't used it with another software before) and you have to check for you credentials (make sure each symbol is there).

The other frequent cause of errors is not respecting the rate-limit or overriding the nonce in an incompatible way, but, I think this isn't your particular case.

Let me know if you have a follow up on this or if the above does not answer your question.

**Comment by garik-code** [comment]
> @garik-code I can't reproduce it on my side (works in JS, PHP and Python)... need to see the code to be able to repeat it (without your keys of course)... Unfortunately, you didn't follow the guides on submitting an issue:
> 
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
> * https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
> 
> ... so we don't know which version of the library it is, which language you're using, etc... So, we can't really help you, unless you provide the missing details (and, please, follow the guides as precisely as you possibly can – to a word, literally).
> 
> You might want to check your keys against the https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting section as well.
> 
> This works on my side:
> 
> ```python
> # Python
> import ccxt
> exchange = ccxt.crex24({
>     'apiKey': 'YOUR_API_KEY',  # 36 hexadecimal characters with dashes
>     'secret': 'YOUR_SECRET',  # base64 secret with '=' and '/' inside, 88 chars in my case
>     'enableRateLimit': True,  # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
> })
> print(exchange.fetch_balance())
> ```
> 
> The most common pitfall for authorization is double-clicking to copy-paste the base64 secret. Because double-clicking selects text up to a word boundary, you often miss the characters after the slash (`/`) or the base64-ending (`==` at the end of the string isn't selected by a double-click). So the user might think that it has been copied, but in fact, it wasn't copied properly. You have to try a fresh new keypair (make sure you haven't used it with another software before) and you have to check for you credentials (make sure each symbol is there).
> 
> The other frequent cause of errors is not respecting the rate-limit or overriding the nonce in an incompatible way, but, I think this isn't your particular case.
> 
> Let me know if you have a follow up on this or if the above does not answer your question.

I am using the "ccxt" version: "^ 1.17.568" java script

`  app.put('/keys', urlencodedParser, (req, res) => {
    let data = req.body
    let bot = data.id
    let access = []
    if(typeof data.key === 'undefined' || typeof data.secret === 'undefined' || typeof data.title === 'undefined'){
      res.json({success: 'false', err: 102})
    }else{
      access['title'] = data.title
      access['key'] = data.key
      access['secret'] = data.secret
      base.query('SELECT exchange FROM bots WHERE id = $1', [bot]).then(exchange => {
        exchange = exchange.rows[0]
        if(typeof exchange === 'undefined'){
          res.json({success: 'false', err: 105})
        }else{
          access['exchange'] = exchange.exchange
          let connect = new ccxt[access['exchange'].toLowerCase()] ({
              'apiKey': access['key'],
              'secret': access['secret'],
              'timeout': 30000,
              'enableRateLimit': true,
              'agent' :  new HttpsProxyAgent (`http://${getProxy()}/`)
          })
          connect.fetchBalance().then(fetchBalance => {
            console.log(fetchBalance);
            base.query('INSERT INTO accesses (bot, title, key, secret, exchange) VALUES ($1, $2, $3, $4, $5) RETURNING *', [bot, access['title'], access['key'], access['secret'], access['exchange']]).then(insert => {
              insert = insert.rows[0]
              insert = {'id': insert.id, 'title': insert.title, 'key': insert.key}
              res.json({success: 'true', return: insert})
            }, err => {
              res.json({success: 'false', err: 101})
              console.log(`err[101]: ${err}`)
            })
          }, err => {
            res.json({success: 'false', err: 104})
            console.log(err)
          })
        }
      }, err => {
        res.json({success: 'false', err: 105})
        console.log(`err[101]: ${err}`)
      })
    }
  })`

**Comment by garik-code** [comment]
Sorry, I'm stupid! :) I send the keys to get with a request from the interface .. Without urlencode. And the secret contains a "+", which is replaced by a space .. Thank you, you are the best!
