### ISSUE TITLE
Proposal: unify cancelOrder return value

### ISSUE THREAD

**Issue by egorFiNE** [ccxt/ccxt#2983]
As @kroitor properly pointed out, after a "successful" (*) `cancelOrder()` call we do not really know if that order has been canceled or not. The responses from all exchanges differ and some of them do indeed return proper order structure on cancel request which can be fed to `parseOrder()` and then returned to the application. 

Perhaps the logic that would determine if `cancelOrder()` has been successful, could be implemented in ccxt? 

Proposal for the `cancelOrder()` result structure: 

1. always return `status` field;
1. return `status: 'queued'` if it is possible to deduct from the exchange response that  the cancel order request has been accepted;
1. return `parseOrder()` result if the exchange returned the order structure;
1. return `status: 'unknown'` otherwise;
1. always return the original response in `info`. 

Migration path for this change seems clear: a script calling `cancelOrder()` can check if `info` is present in return value and if so, it can rely on the `status` field. If `info` is not present, that means we are dealing with the raw exchange response, i.e. it's `cancelOrder()` implementation has not been migrated yet.

What do you think? 

(*) sometimes it's hard to tell what exactly is a successful `cancelOrder()` call; some exchanges cancel immediately while others might just delete the order like it was never there. Go figure.

**Comment by kroitor** [comment]
First of, thanks for your participation! Really appreciate your involvement!

Regarding your proposal, let's examine each of the proposed steps carefully:

> Proposal for the cancelOrder() result structure:

> - always return status field;

I would change this item for *always return order structure with known fields having proper values, unknown fields having undefined values*, including the `status`. To me it looks like you and other users would like to know as much as possible about the order in question, not just the `status`, but, probably, other fields as well. And their values should be either defined (known) or undefined (unknown). The equivalent of `undefined` from JS is `None` in Python and `null` in PHP.

> - return status: 'queued' if it is possible to deduct from the exchange response that the cancel order request has been accepted;

This particular point seems redundant, let me explain: when the cancel request fails we throw an exception. So, if there was no exception thrown, then it means that the `cancelOrder` was accepted. So, if you don't catch an exception from `cancelOrder`, then the request for cancelation was accepted. And if the `status` is unknown as this point, then there's no difference in whether its value is `'queued'` or `undefined` – both mean *"cancelOrder was successful, but status is undefined or unknown yet"* – so I'd stick with the latter one (`undefined`, as it reflects the truth).

> - return parseOrder() result if the exchange returned the order structure;

I'd change it for *"always return parseOrder results with as many fields defined as possible"*.

> - return status: 'unknown' otherwise;

To me both `'unknown'` and `'queued'`mean `undefined`, when cancelOrder succeeded. When the exception was thrown, the status is still `'unknown'` or `undefined`. So, I'd stick to `undefined`.

> - always return the original response in info.

Yep.

> What do you think?

I would agree with the general part – we should unify the cancelOrder response to return the order structure with all known fields defined, all unknown fields undefined. Let me know your opinion on the above )

Thx again!

**Comment by kroitor** [comment]
> See, but what if there's more than just two paths: exception and no exception? Like for instance an exchange returning something along the lines or "I cannot cancel right now" or "Cancel is pending" or "something fucked up but not quite". 

To me this is aligned with what I posted above, meaning that if any field has a definitely-known value, then we can put it in the response. If the exchange does specify the status of the order, then we just use it to full extent.

> Like for instance an exchange returning something along the lines or "I cannot cancel right now"
> or "something fucked up but not quite".

Both of the above cases should probably throw an exception.

> or "Cancel is pending"

We actually have a CancelPending exception, which is thrown when you're trying to cancel the order that is already being canceled. So the exception here is thrown on the second attempt. That means, that if there was no exception on the first call to `cancelOrder`, the order is definitely in "cancel pending" state now. But because we don't know if it is still open or canceled already, we can't set the status to anything except `undefined` until the next call to `fetchOrder`...

> I've seen one return simply {} on cancel, while it's other API calls had a status/success field (nope, I don't remember which braindamaged creature did this).

Yep, some exchanges return the status. Some of them (like HitBTC) return the entire order. So it's exchange-dependent. We should, however, unify the cancelOrder response to return the entire order structure with as many fields having defined values as possible.

> (thinking aloud) okay so what if we clarify the documentation by suggesting to always perform fetchOrder() after cancelOrder() in case status === undefined (which would be the majority of cases)?

Yep, this is actually already in the error handling section, but we should add it to the description of `cancelOrder` as well. Totally agree on this.

> Another way of thinking about it: what is there are really two statuses: the status of order and the status of HTTP request? Do we need to differentiate?

No, I don't really think we should differentiate this particular aspect. We're hiding everything HTTP-related behind our calls, so we don't want the user to go down to the low-level HTTP layer at all (we have exception classes for that). 

In terms of this library, your call is either successful (no exception) or not successful (an exception). If it is successful, then, in most cases you don't know the `status`, because it is undefined. This is just how most exchanges work – they will provide as little info as possible from their endpoints and we will have to deduce what's possible from there.

Let me know if you're comfortable with the above.

**Comment by kroitor** [comment]
Dupe: https://github.com/ccxt/ccxt/issues/1445

**Comment by egorFiNE** [comment]
> Let me know if you're comfortable with the above.

Yep. All agreed upon, so we're going forward.  

We will implement this in the coming days for binance, bittrex, cobinhood, cryptopia, gatecoin, gateio, hitbtc, kucoin and perhaps livecoin. 

Regarding gateio, we really need #2850 merged. What's blocking, how can we help you to further this PR? We're willing to contribute. 

Also, #2932, #2934, #2956, #2958 are blockers as we are standing on this parts being done, but these are relatively small and simple PRs, hope you can merge them soon.

**Comment by frosty00** [comment]
I agree with trying to unify `cancelOrder`, however relying on an exchange response is not the best idea for a couple of reasons. 

Rather than attempting to guess the status of a `cancelOrder` call, subsequent calls to `fetchOpenOrders` should be made to deduce the status of the order **at any given moment**. Most exchanges will have implemented some sort of queue logic so the cancel is likely to be delay. By constantly polling the exchange we don't need to know the status of `cancelOrder` and can assume nothing. I have wrapped my `cancelOrder` and `createOrder` calls with some exception handling because they are not reliable due to the very nature of exchange responses. 

Also agree that #2850 should be merged now so I can build / edit it.

**Comment by egorFiNE** [comment]
@frosty00 in fact, in our code we do exactly this: we `cancelOrder()`, then we *almost* disregard the answer and then we cycle thru `fetchOrder()`. 

And by *almost* I mean that we try to deduce the current state of fill amount, avg price, etc *in between* the `cancelOrder()` and `fetchOrder()`. Why? Simply because this a little bit update info might be available from the exchange and it doesn't hurt to update the numbers one more time in case we do have them. 

So in general we are all aligned that we either catch() or not catch and that's about it for `cancelOrder()`. 

But we shouldn't disregard exchange reply if we have one.

**Comment by kroitor** [comment]
The solution to this issue is to always return the unified order structures https://github.com/ccxt/ccxt/wiki/Manual#order-structure from all methods that have `Orders` in their name, including `fetchOrder`, `createOrder`, `cancelOrder` and so on. We're making a transition towards that, there may still be places where `cancelOrder` return is not unified yet, but we are happy to merge PRs on that matter and we will keep adding the necessary edits to all implementations of `cancelOrder` along the way. Closing this at this point. Feel free to reopen it if needed or just ask further questions, if any.
