### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by alexigonkin** [ccxt/ccxt#3013]
when I try to place order with price "0.0000042" I get order with price "0.0000041". 
This problem is common for all exchanges.
Demo code: [TestTrunc.txt](https://github.com/ccxt/ccxt/files/2063945/TestTrunc.txt)

- OS: MacOS/Ubuntu
- Programming Language version: python 3.6
- CCXT version: 1.14.118 
- Exchange:  exchange.py
- Method: truncate

**Comment by frosty00** [comment]
truncate is depreciated, use `decimal_to_precision`

**Comment by kroitor** [comment]
@frosty00 thx!

@alexigonkin the answer of @frosty00 is correct, you should now use `decimal_to_precision` instead of truncate. Let us know if changing it for `decimal_to_precision` does not help. Thx!

**Comment by omidkrad** [comment]
I noticed sometimes I get numbers with rounding errors from CCXT API. As you know, any arithmetic operation using native JS operators is prone to rounding errors. I also see that you have a bunch of helper functions for fixing up these issues, nonetheless they still happen. Here are some places in the code base that are using arithmetic operations that may need to be protected for rounding errors.

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/binance.js#L361

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/binance.js#L605

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/binance.js#L709

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/binance.js#L719

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/binance.js#L749

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/binance.js#L1050

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/base/Exchange.js#L974

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/base/Exchange.js#L976

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/base/Exchange.js#L1280

https://github.com/ccxt/ccxt/blob/bfbcfbe71d7ace5440b160b7aaf7907eaeff7247/js/base/Exchange.js#L1285

My suggestion is use a math library for all arithmetic operations. I use the excellent [decimal.js-light](https://github.com/MikeMcl/decimal.js-light) that I recommend. You don't have to pass around the `Decimal` object, just do the calculation and convert to number in place.

```
// cost = price * filled
cost = new Decimal(price).mul(filled).toNumber();
```

Of course it looks uglier than when using the native operator, so I would keep the original operation in the comments.

**Comment by omidkrad** [comment]
Here's an example:
```js
let cost = 0.228114
let filled = 1.38
let price = cost / filled // 0.16530000000000003
```

**Comment by kroitor** [comment]
@omidkrad you're right, however, this issue is a bit tricky to solve:

1. It will significantly hit the performance, especially when dealing with thousands of numbers in a single reply, and many replies in a row.
2. We already have BN and BigNumber (two bn libs) as deps for the web3-related code and signing, adding a third lib for big numbers is probably not the way to go – we should instead reduce the number of bn deps to a single codepoint responsible for all arithmetics on big numbers, this is easier said than done.
3. In many cases users don't want floats formatted to precision – because the float can be rounded to the desired precision in the userland, where necessary. Instead, those users either want "fast floats for speed" or "slow decimal strings for precision".
4. It will require porting to other languages and it will make the code less maintainable by newcoming contributors who are less familiar with our rules for decimals.

Ideally, we want to have a "decimal number mode" as the controlling property of the exchange instance, so that a user could specify which type of numeric output he wants. However, adding that property to the exchange implementation without hitting the performance is difficult. We will look into possible quickfixes for this.

**Comment by omidkrad** [comment]
Makes sense, thanks for the detailed response @kroitor.

**Comment by kroitor** [comment]
@omidkrad thx for your feedback as well, appreciate your involvement!
