### ISSUE TITLE
Bitmex error when placing trailing-stop order: "Invalid price"

### ISSUE THREAD

**Issue by aasche** [ccxt/ccxt#3017]
- OS: macOS Sierra 10.12.5
- Programming Language version: Python 3.6.4
- CCXT version: 1.11.69
- Exchange: Bitmex
- Method: `create_order(self, symbol, type, side, amount, price=None, params={})`

Hi!

I'm having troubles posting a TRAILING-STOP order on BITMEX.
I use:

`bitmex.create_order(symbol = 'BTC/USD', type = 'trailing-stop', side = 'sell', amount = 1, price = -300.0)`

and get error:

`ccxt.base.errors.ExchangeError: bitmex {"error":{"message":"Invalid price","name":"HTTPError"}}`

I tried a few different prices such as e.g. -7200.0 when current BTC price is at 7500.0, I also tried both prices with and without the minus symbol. Also, I tried these four different price combinations while having an actual open position.
As I understand I would need to set the price as the distance where the trailing-stop should be set absolute to the current BTC price.
E.g. the current BTC price is at 7500.0 (having a long position) and I would like to place the trailing-stop (sell) at 300.0 (at 7200.0) below that price I would set price = 300.0.

Help is much appreciated!

**Comment by kroitor** [comment]
Hi! Sorry for the long wait. In order to use BitMEX trailing stops you will have to override a few extra params and make sure that they correspond to BitMEX docs from here: 

- https://www.bitmex.com/api/explorer/#!/Order/Order_new

![bitmex-trailing-stop](https://user-images.githubusercontent.com/1294454/41656190-d08f0270-7497-11e8-89ab-7a75bd60b324.jpg)

```Python
bitmex.create_order(symbol, type, side, amount, price, {
    'ordType': 'Stop',
    'stopPx': 
    # ... other params, 
})
```

All of the above is documented in the Manual:

https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
Let us know if this does not answer your question.

**Comment by aasche** [comment]
Great! Thank you very much!

To place a trailing-stop on BitMEX the following snippets work for me:
(ccxt version 1.11.69)
(python 3.6.4)

create trailing-stop sell order:
```
bitmex.create_order(symbol = 'BTC/USD', type = 'stop', side = 'sell', amount = 1, params = {
    'ordType': 'Stop',
    'pegPriceType': 'TrailingStopPeg',
    'pegOffsetValue': -50.0 # distance in USD
    })
```

create trailing-stop buy order:
```
bitmex.create_order(symbol = 'BTC/USD', type = 'stop', side = 'buy', amount = 1, params = {
    'ordType': 'Stop',
    'pegPriceType': 'TrailingStopPeg',
    'pegOffsetValue': 50.0 # distance in USD
    })
```

**Comment by kroitor** [comment]
@aasche thx for reporting back!
