### ISSUE TITLE
Qryptos: Wrong price precision on ETH, USD, JPY markets

### ISSUE THREAD

**Issue by xogoc** [ccxt/ccxt#3030]
- OS: Ubuntu 16.04.3
- Programming Language version: Node.js v8.11.1
- CCXT version: 1.14.119
- Exchange: Qryptos

This code in qryptos.js:
```
if (quote === 'BTC') {
                minPrice = 0.00000001;
            } else if (quote === 'ETH' || quote === 'USD' || quote === 'JPY') {
                minPrice = 0.00001;
            }
...
if (typeof minPrice !== 'undefined')
                precision['price'] = -Math.log10 (minPrice);
```
makes price precision on all ETH, USD, JPY markets = 5. When it is actually 8 in most markets. Even CCXT Manual states that minPrice and pricePrecision is totally different things.
Sorry, I don't know how to submit fixes, only issues :)

**Comment by mkutny** [comment]
The issue is that they just don't provide an endpoint to fetch market info, therefore, it's a subject for manual introspection.

So to determine precisions one needs to check trades/orderbooks and then confirm them by submitting relevant (and irrelevant) orders to see if they pass or throw an exception.

Similarly, in order to guess min limits one needs to create orders and see which prices/amounts trigger `InvalidOrder` or `InsufficientBalance` exceptions.

Eventually, we'll need to end up with the structure similar to the following: https://github.com/ccxt/ccxt/blob/ef810d615e10bfc143f4eb7d38e2918d5354330e/js/getbtc.js#L33-L35

So if you could help to create such a matrix it then could be incorporated in the library.

**Comment by kroitor** [comment]
Qryptos is now Liquid: https://github.com/ccxt/ccxt/issues/3809
