### ISSUE TITLE
Query market price

### ISSUE THREAD

**Issue by joshhopkins** [ccxt/ccxt#3037]
- OS: MacOS 10.13.4
- Programming Language version: Node 10.0.0
- CCXT version: 1.13.94
- Exchange: All
- Method: fetchOrderBook / fetchTicker

Prior to reading [this](https://github.com/ccxt/ccxt/wiki/Manual#market-price) I have been referring to `bid` returned from `fetchTicker` method to find current market price. According to the manual `fetchOrderBook` is the preferred method for this, though it seems to be returning the same number. Am I right to assume both approaches are interchangeable?

**Comment by kroitor** [comment]
> Am I right to assume both approaches are interchangeable?

For the market price – yes, those are interchangeable. However, sometimes fetchTicker can be a more *"lightweight"* approach, if the exchange in question does not allow to limit the orderbook to just one bid/ask with `fetchOrderBook ('FOO/BAR', 1)`. Otherwise, `fetchOrderBook` with a limit of 1 will probably be faster due to less traffic. But you're right, in general, you can interchange them safely. Ultimately, you can measure which one works better for your particular set of exchanges and pairs. Hope this answers your question.

**Comment by joshhopkins** [comment]
Got it. Thanks for the clarification!
