### ISSUE TITLE
How to bypass Yobit/Cloudflare DDoSProtection in PHP?

### ISSUE THREAD

**Issue by wybitnygracz** [ccxt/ccxt#3047]
I get the error " Uncaught ccxt\DDoSProtection: yobit GET https://yobit.net/api/3/ticker/007_btc-007_doge-007_eth-007_rur-007_usd-007 ... "
I saw example how bypass cloudflare in js, do you have example for php ?

**Comment by kroitor** [comment]
> do you have example for php ?

Yep, but is still requires python, because it uses the cfscrape from cli, so, I don't have a pure PHP example right away (will look for solutions of the issue), but I can write a PHP example for you, if you are ok with installing Python in parallel (you might actually have it in your system already).

**Comment by wybitnygracz** [comment]
I can't install phyton now on my server, thanks for answer.

**Comment by dmig** [comment]
Another way -- use proxies to connect. You can even search the web for free proxies, but they're pretty unstable -- not for production use.

**Comment by DaveMG3** [comment]
@kroitor , would be interested to see you PHP example using Python and cfscrape from cli.
Is it published somewhere?
Thks

**Comment by kroitor** [comment]
@DaveMG3 sorry for the delay, will upload it asap
