### ISSUE TITLE
How can I custom error response from market

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#3053]
- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.14.140
- Exchange: all exchange market
- Method: private method

As ccxt implement the api of exchanges, how can I get the origin failed json result from ccxt method.

I get exception like this below. How can I get the json result in ccxt?
```
bitfinex {"message":"Could not find a key matching the given X-BFX-APIKEY."}
```

How to get like this.
```
{"message":"Could not find a key matching the given X-BFX-APIKEY."}
```

**Comment by kroitor** [comment]
First of all, you should not rely on those messages in the application logic. Those are more for debugging purposes, you should not show that to a user nor should you use those strings in you GUI. Basically, you should instead do the proper differentiated error handling, as shown in the [examples](https://github.com/ccxt/ccxt/tree/master/examples/php) and in the [Manual](https://github.com/ccxt/ccxt/wiki/Manual#error-handling). 

If, for some reason, you still want to parse those messages – that might indicate a design error in your application. So, instead of using those error messages we'd highly recommend to do proper exception type catching and handling.

However, if you don't care and you require access to that message after reading the above, then you can do this like so:

- https://github.com/ccxt/ccxt/tree/master/examples/php/error-handling-message.php

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

$exchange = new \ccxt\bittrex (array (
    'apiKey' => 'foo',
    'secret' => 'bar',
));

$message = null;

try {

    $result = $exchange->fetch_balance ();
    var_dump ($result);

// these catch-clauses are showing the proper way of handling the errors

} catch (\ccxt\AuthenticationError $e) {

    // handle authentication error here

} catch (\ccxt\NetworkError $e) {

    // your code to handle the network code and retries here

} catch (\ccxt\ExchangeError $e) {

    // your code to handle an exchange error

} catch (Exception $e) {

    // This is an example of how NOT TO DO error handling
    // One should not rely on the message string contained in the exception
    // If you want to access it, that might indicate a design error in your code.

    $message = $e->getMessage ();

    if (preg_match ('/[a-z]+\s+(\{.+\})$/iu', $e->getMessage (), $matches)) {
        $message = $matches[1];
    }

    echo print_r ($message, true) . "\n";

}

?>
```

Don't say we didn't warn you. Hope this answers you questions.

**Comment by Umbralith** [comment]
Thank you so much again
