### ISSUE TITLE
OkEx Exchange CNY conversion error

### ISSUE THREAD

**Issue by davemg3** [ccxt/ccxt#3142]
Hello Kroitor,
Wondering if it comes from CCXt or OkEx API but data provided for pairs in CNY as ETH/CNY are provided in USD value instead of CNY value, as per image below : 
![image](https://user-images.githubusercontent.com/32598581/41463322-52b4e2de-7096-11e8-8eea-498762647efb.png)

    Programming Language version:
    CCXT version: Java
    Exchange: 1.14.179
    Method: OHLCV

**Comment by kroitor** [comment]
<img width="279" alt="screen shot 2018-06-15 at 17 57 27" src="https://user-images.githubusercontent.com/1294454/41474786-9e7c12d0-70c5-11e8-839c-d825966cc342.png">

> Wondering if it comes from CCXt or OkEx API but data provided for pairs in CNY as ETH/CNY are provided in USD value instead of CNY value, as per image below :

Will check for that and will get back to you soon.

**Comment by DaveMG3** [comment]
After checking these are all pairs crypto/CNY which have same value as crypto/USD

![image](https://user-images.githubusercontent.com/32598581/41499642-a0593c40-7183-11e8-91d7-357d85f75c57.png)

**Comment by DaveMG3** [comment]
New infos :
 You cannot trade in USD on OkEx, only in CNY so might be than OKEX trying to provide equivalent in USD did an error on CNY but the weirdest is the value received from API hourly since this WE:

36 millions volume on pair EOS/USD hourly which cumulated on 24h gives around 800 millions!!
![image](https://user-images.githubusercontent.com/32598581/41865373-1ce16a96-78ad-11e8-9fd1-cf12aa43cdd7.png)

For OKEx (1.3billions volume) , Kraken only provides volume with USDT, BTC, ETH, so might be they also rejected pair in USD or CNY cause of volume error...or these pairs have a special meaning

![image](https://user-images.githubusercontent.com/32598581/41866687-31476504-78b1-11e8-991b-e89b81d6f049.png)
![image](https://user-images.githubusercontent.com/32598581/41866691-33693f60-78b1-11e8-8146-020730e3a25c.png)
