### ISSUE TITLE
Bilance shows me held, but for what?

### ISSUE THREAD

**Issue by Elmit2015** [ccxt/ccxt#3170]
The balance shows me free / used / total    (available / pending / total)
How can I find out for what trades some coins have been "used" (prepared)?

**Comment by kroitor** [comment]
> How can I find out for what trades some coins have been "used" (prepared)?

- https://github.com/ccxt-dev/ccxt/wiki/Manual#personal-trades
- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

Let us know if this does not answer your question.

**Comment by Elmit2015** [comment]
It's all a trial and error method, ... for me more an error method.

I tried:
try {
//	$mytrades = $exchange->fetchMyTrades (symbol = undefined, since = undefined, limit = undefined, params = {});
//	$mytrades = $exchange->fetchMyTrades (BTC,,,{});
	$mytrades = $exchange->fetchMyTrades (BTC);
	
	print_r ($mytrades);

Can you please give me the next hint?

**Comment by kroitor** [comment]
@Elmit2015 you earlier said that you read a lot and now you're asking a question that is explained in a pretty detailed way in the Manual... you can't fetch trades for a currency code like `'BTC'` or `'USDT'` or whatever it is. Because trades are dealing with two currencies, that is, a trading pair, or *a symbol*, like we call it, `'BTC/USD'` or `'ETH/USDT'`, for example. This is explained here: https://github.com/ccxt/ccxt/wiki/Manual#markets

So, the exchanges will not give you a trade log per currency code, instead they will give you a trade log per symbol (currency pair).

```PHP
$exchange->load_markets ();
// print_r ($exchange->symbols); // uncomment if you want to see all of them
$symbol = 'BTC/USD'; // set to whatever symbol you want your trade history for...

if (!array_key_exists ($symbol, $exchange->markets)) {
    throw new Exception($exchange->id . ' does not have a symbol ' . $symbol);
}

if ($exchange->has['fetchMyTrades']) {
    $trades = $exchange->fetch_my_trades ($symbol);
    // build your logic from trades history, if available from the exchange
} else if ($exchange->has['fetchClosedOrders']) {
    $orders = $exchange->fetch_closed_orders ($symbol);
    // alternatively, build your logic from closed orders history, if available from the exchange
} else {
    // read the manual and add this codepath depending on the needs of your application
    // because we are not going to write all the code for you, lol )
}
```

I'd really recommend to read the entire Manual very carefully from the very beginning to the very end – this might save you a lot of time, trust me ;)
