### ISSUE TITLE
Bitmex - Bitflyer : symbols not following ccxt format

### ISSUE THREAD

**Issue by DaveMG3** [ccxt/ccxt#3180]
In PHP version, with $ccxt_exchange->load_markets(),we got the following results, breaking other methods call : 

Bitflyer : 
![image](https://user-images.githubusercontent.com/32598581/41570259-4f8ac5f8-736e-11e8-9ee4-77f55257d613.png)

Bitmex : 
![image](https://user-images.githubusercontent.com/32598581/41570296-75ba34e8-736e-11e8-874c-374a268423b5.png)

Sorry for opening various isssues (I got some time to test)

- Programming Language version: PHP
- CCXT version: 1.14.211
- Exchange:
- Method: LoadMarket

**Comment by kroitor** [comment]
Symbols can have any format. Usual spot trading symbols are pairs of currencies like `'ETH/BTC'`, `'BTC/USD'` and so on, however, there are also futures markets which are coded with a month in their symbolic name, and, also, there are other cases as well, so there is no universal "CCXT format" for symbols – it's just a string and the content of that string should not be parsed on user side. Instead of parsing it, you should just access market properties and let us know if you find some of them missing.

Hope this answers your question.
