### ISSUE TITLE
Bittrex bug in OHLCV without specifying since argument

### ISSUE THREAD

**Issue by Stas-Buzunko** [ccxt/ccxt#3207]
OS: ubuntu
Programming Language version: js
CCXT version: 1.14.231
Exchange: bittrex
Method: OHLCV => timeframe 1h

If I don't specify since but specify limit, then it fetches random period. Approximately 2 months ago when it should fetch last week only.

Here is the code I use

```
exchangeCCXT.fetchOHLCV('ADX/BTC', '1h', undefined, limit = 168)
     .then( async hours => {
       console.log('hours', hours)
```

Here is response I get.
![image 20](https://user-images.githubusercontent.com/12331100/41720537-09825706-756c-11e8-8b64-74b1c2543389.png)
![image 19](https://user-images.githubusercontent.com/12331100/41720538-09afc7cc-756c-11e8-82ac-406e85ab28cb.png)

The same method with 1d timeframe and limit 7 returned data for December 2015.

Works correctly when specifying since param.

**Comment by kroitor** [comment]
Hi! If `since` is not specified the `fetchOHLCV` method will return the time range as is the default from the exchange itself.  This is not a bug. Some exchanges will return candles from the beginning of time, others will return most recent candles only, the exchanges' default behaviour is expected. Thus, without specifying `since` the range of returned candles will be exchange-specific. One should pass  the `since` argument to ensure getting precisely the history range needed.

Added the above info to the Manual. Hope this answers your question. Thx!

**Comment by Stas-Buzunko** [comment]
thanks for clarifying this, because I read docs and it said 
```
"You can call the unified fetchOHLCV / fetch_ohlcv method to get the list of most recent OHLCV candles for a particular symbol like so:"
```
"Most recent" part is confusing. Thanks for updating docs.

**Comment by kroitor** [comment]
> "Most recent" part is confusing.

Removed those two words from there as well. Thx for pointing that out!
