### ISSUE TITLE
Cannot connect to bx.in.th even by using bypass-cloudflare.js

### ISSUE THREAD

**Issue by sathwik77** [ccxt/ccxt#3215]
- OS: Windows
- Programming Language version: Node 8.9.4
- CCXT version: latest
- Exchange: bx.in.th
- Method: bypass-cloudflare.js
Cannot access bx.in.th from any of the js examples. It shows error as 

`(node:9300) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): #<Object>
(node:9300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.`

![image](https://user-images.githubusercontent.com/26072324/41762459-78316db6-7618-11e8-96bb-6f9b2547ea7b.png)

**Comment by kroitor** [comment]
Unfortunately, bx.in.th's captcha is too hard to bypass – they will make the life of a coder as hard as they possibly can. You should try using a Thai proxy to see if it helps. It isn't accessible from my location either (when i'm using my browser to access their website, they will return a 403 cloudflare captcha page).

```
mbp:ccxt igorkroitor$ node examples/js/bypass-cloudflare.js
{ errorType: 1 }
```

<img width="1046" alt="screen shot 2018-06-22 at 10 28 53" src="https://user-images.githubusercontent.com/1294454/41763504-176b4b70-7607-11e8-901a-d400ae128632.png">

You should contact their support on this issue and ask them to whitelist your IP with their Cloudflare settings. Unfortunately, the issue is not in the library itself. It's on their API side. Nobody restricts the API access with Cloudflare like they do. Hope this answers your question.

**Comment by kroitor** [comment]
More on proxies here:

- https://github.com/ccxt/ccxt/wiki/Install#proxy
- https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

**Comment by kroitor** [comment]
@sathwik77 Yep this is frustrating sometimes... At this point, I guess, you should reach out for their tech support... We will be thankful if you report your findings.

**Comment by sathwik77** [comment]
We will try to reach out them and update you on this if we ever get any reply from them..

**Comment by kroitor** [comment]
@sathwik77 you can also try the following:

- https://github.com/thammarongg/bxthai/blob/master/src/bxthai.js

... and other js implementations from here: https://github.com/search?l=JavaScript&q=bx+in+th&type=Repositories

However, not sure if you'll have any luck. But, hey, we'll be happy if you let us know in case you find some code that does solve this somehow.

**Comment by sathwik77** [comment]
Only work around is to use a VPN of Thailand/Singapore or buy a VPS in region Thailand/Singapore.
