### ISSUE TITLE
Error when try to get balance: "invailed sign"

### ISSUE THREAD

**Issue by srkgpy** [ccxt/ccxt#3228]
It works when I do this:
`import ccxt`
`hitbtc = ccxt.hitbtc({
    'apiKey': '18339694544745d9357f9e7c0f7c41bb',
    'secret': '8340a60fb4e9fc73a169c26c7a7926f5',
})`
`print(hitbtc.fetch_balance())`

But its now working when I do this (I have a lot of balances that I nee to read their api from csv):

````
import time
import csv
import ccxt
import os
import sys
from collections import namedtuple
```

TaskConfig = namedtuple('TaskConfig', 'exchanges,name,public,secretk')

def handle_task(tc):
    ex = getattr(ccxt, tc.exchanges)({'apiKey': tc.public, 'secret': tc.secretk})
    ex_ba = ex.fetch_balance()
    print(ex_ba)    

def main():
    with open("arbexchanges.csv", 'r') as arbexchanges:
        reader = csv.reader(arbexchanges)
        for i in arbexchanges:
            tc = TaskConfig(*i.split(','))
            handle_task(tc)
            time.sleep(2)
        
if __name__ == '__main__':
    main()
`

**Comment by kroitor** [comment]
If it works like shown in your first snippet and doesn't work with the second snippet, then you should check your values...

```Python
def handle_task(tc):

    print("I'm now trying to instantiate exchange: ", tc.exchanges)  # do your python-homework first!
    print("I'm using apiKey: ", tc.public)
    print("I'm using secret: ", tc.secretk)

    ex = getattr(ccxt, tc.exchanges)({'apiKey': tc.public, 'secret': tc.secretk})
    ex_ba = ex.fetch_balance()
    print(ex_ba)  
```

Nobody here is going to teach you how to debug your own basic python code, sorry. This is for issues with the library, not with any code that does not work. Also, you're not helping to help you, because "it's not working" isn't a proper description of what is happening exactly. You should be much more specific than that, when you're describing a technical problem. 

At least, read this doc very carefully https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue and copy the verbose request/response output of a method that is failing. 

Without knowing all the details of the error including the contents of your CSV it will be really hard to tell anything specific, however, I'm afraid, there's very little chance that anyone will be interested into looking into that CSV, except you, my friend ) Because this is your job, not ours )

**Comment by kroitor** [comment]
I'd close this for now, feel free to ask further questions, if any.
