### ISSUE TITLE
Is there a fetch_ticker cache?

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#3255]
I'm trying to update about 100 coin prices across a dozen exchanges. Going one-by-one is obviously inefficient if the exchange API doesn't support individual coin calls.

I was thinking I could either cache the results (I'm fine with 3 minutes) or I'll have to rewrite my script to call the all-at-once exchanges only once, update all the prices, and then call the one-at-a-time exchanges.

I can't find anything in the docs; does such a cache feature exist? How simple would it be to implement?

**Comment by kroitor** [comment]
> I can't find anything in the docs; does such a cache feature exist?

Nope, we don't cache them in the library, because caching them in userland is trivial.

> How simple would it be to implement?

Very simple, if you know your programming language well. If you're doing this in PHP, that would just require creating a shared assoc array of tickers by symbol, protecting it with mutexes and writing from your threads to that assoc array directly.

One thing to note here: caching real-time data is ok for analysis purposes, however, you don't really want to trade tickers that are several minutes old, for obvious reasons.

Let us know if it does not answer your question.
