### ISSUE TITLE
calculate_fee  for kucoin not working yet

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#3261]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: ccxt-1.14.230
- Exchange: kucoin
- Method: calculate_fee

Great you implemented calculate_fee, however for kucoin so far it is returning wrong results (guess it is the base exchange method still for kucoin). Example:

````
import ccxt
ex = ccxt.kucoin()
ex.calculateFee('KCS/BTC','limit','buy', 10, 0.1, 'taker')
````

returns as currency of the fee 'BTC', however kucoin always subtracts the fee from the currency you GET, in this case 'KCS'. Would be great if someone could do the method implementation for kucoin :-)

**Comment by miracle2k** [comment]
Ran into this as well.

I notice that all the implementations of `calculate_fee` are essentially copies, duplicating the same logic. Either they have a fixed currency to deduct the fee from (say always the quote currency), or they decide the currency based on whether it is a sell or a buy. The rest seems to be the same. Some of them call ``self.fee_to_precision``, while others do not (an oversight maybe?).

My suggestion then would be to move the information as to how the fees work on an exchange to the static data. For example:

```
fees: {
    'trading': {
        'maker': 0.001,
        'taker': 0.001,
        'applyOn': 'receive'   // This is new
    },
}
```

``applyOn`` could be one of:

- 'receive': The default behavior on most exchanges, it's the base currency for buys, quote currency for sells.
- 'spend': The opposite of the default (not sure if any exchange uses this).
- 'quote': The fee is always the quote currency (this is currently the default logic in the base class).
- 'base': The fee is always the base currency  (not sure if any exchange uses this).
- 'custom'/missing/null: The exchange has a custom logic, in case that is ever necessary.

Using this approach, we can probably remove all the `calculate_fee` methods, and just have a single method in the base class. 

What do you think?

**Comment by miracle2k** [comment]
I'd be interested in working on this, because I need it myself. 

In addition to not duplicating code, storing a `feeSystem` option in the exchange data has another advantage: It allows people to do fee calculations not covered by `calculate_fee`. 

For example, if I want to buy to sell 7000 EUR on bitstamp:BTC/EUR at a rate of 7000 EUR, I cannot just submit an order for 1 BTC - I need to submit 7000 EUR + Fee.  `calculate_fee` only allows me to calculate the fee if I already know my order size.

If cxxt stores the information about the fee system in a readable way, people can write their own logic if required.

**Comment by kroitor** [comment]
Hi! Sorry for a long wait.

@MarcelBeining 

> Would be great if someone could do the method implementation for kucoin :-)

Added that duplicated override temporarily until we have a better solution. Thx for reporting!

@miracle2k 

> I notice that all the implementations of calculate_fee are essentially copies, duplicating the same logic. Either they have a fixed currency to deduct the fee from (say always the quote currency), or they decide the currency based on whether it is a sell or a buy. The rest seems to be the same.

100% true!

> Some of them call self.fee_to_precision, while others do not (an oversight maybe?).

In some cases this may be an oversight, however, in some other cases, like that of Kraken, you have to add more stages of rounding, otherwise your trade won't balance. This is related to how the exchange engine computes the fee values internally and how it does rounding upon reporting them to the outer world. And this, of course, is not documented well among exchanges.

> I'd be interested in working on this, because I need it myself.

That would be great! However, we have to be careful with this and make sure we don't break anything ) Also, other methods for those other use cases you mentioned are really welcome in the base class ) Thx for your involvement!

**Comment by kroitor** [comment]
@miracle2k also, forgot to mention, you might also want to read #1835 and posts linked from there to get a wider overview of the overall picture with fees.

**Comment by primski** [comment]
what's going on here, because fees broke for me on kucoin this morning ... i guess they've been wrong all along ... so is there a fix being made?

also is there a support group/chat for the like minded people ?
