### ISSUE TITLE
kucoin order data has inline trade list, and those have the wrong fee

### ISSUE THREAD

**Issue by miracle2k** [ccxt/ccxt#3284]
A order data response from kucoin:

```javascript
{  
   'info':{  
      'coinType':'EOS',
      'dealValueTotal':70.61051071,
      'feeTotal':0.07061051,
      'userOid':'5a7ae81903d6440e9981c7b4',
      'dealAmount':8.6787,
      'coinTypePair':'USDT',
      'type':'SELL',
      'orderOid':'5b2e620b9ffd372eb6287008',
      'createdAt':1529766412000,
      'dealOrders':{  
         'total':1,
         'firstPage':True,
         'lastPage':False,
         'datas':[  
            {  
               'createdAt':1529766414000,
               'amount':8.6787,
               'dealValue':70.61051071,
               'fee':0.07061051,
               'dealPrice':8.13607,
               'feeRate':0.001
            }
         ],
         'currPageNo':1,
         'limit':20,
         'pageNos':1
      },
      'dealPriceAverage':8.13607,
      'orderPrice':8.13607,
      'pendingAmount':0.0
   },
   'id':'5b2e620b9ffd372eb6287008',
   'timestamp':1529766412000,
   'datetime':'2018-06-23T15:06:52.000Z',
   'lastTradeTimestamp':None,
   'symbol':'EOS/USDT',
   'type':'limit',
   'side':'sell',
   'price':8.13607,
   'amount':8.6787,
   'cost':70.61051071,
   'filled':8.6787,
   'remaining':0.0,
   'status':'closed',
   'fee':{  
      'cost':0.07061051,
      'rate':None,
      'currency':'USDT'   // Correct fee currency is USDT
   },
   'trades':[  
      {  
         'id':None,
         'order':'5b2e620b9ffd372eb6287008',
         'info':{  
            'createdAt':1529766414000,
            'amount':8.6787,
            'dealValue':70.61051071,
            'fee':0.07061051,
            'dealPrice':8.13607,
            'feeRate':0.001
         },
         'timestamp':1529766414000,
         'datetime':'2018-06-23T15:06:54.000Z',
         'symbol':'EOS/USDT',
         'type':None,
         'side':'sell',
         'price':8.13607,
         'cost':70.61051071,
         'amount':8.6787,
         'fee':{  
            'cost':0.07061051,
            'currency':'EOS'   // Fee currency here is EOS
         }
      }
   ]
}
```

Note the inline comments. The reason this happens is as follows:

1. kucoin does not tell the fee currency, ccxt has to "guess" what it is based on the side (buy or sell). For the order itself, it does so here as part of `parseOrder`: https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L611

2. For the trade, it want to use the same logic, in `parseTrade`: https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L968

3. The problem is that the data structure for a single trade only contains very basic information:

```
{  
            'createdAt':1529766414000,
            'amount':8.6787,
            'dealValue':70.61051071,
            'fee':0.07061051,
            'dealPrice':8.13607,
            'feeRate':0.001
         }
```

It does not tell which side the order is on. As a result, those lines in ``parseTrade`` both fail:

```
feeCurrency = (side === 'sell') ? market['quote'] : market['base'];
```
```
let feeCurrencyField = (side === 'sell') ? 'coinTypePair' : 'coinType';
```

Because `side` is really `undefined`, which means that it always selects the same currency, and sometimes gets it wrong.

I wanted to fix this with a pull request, but I couldn't quite decide how to best pass along the required data to `parseTrade`. Also, there are some comments within `kucoin` about how `parseMyTrades` will be removed - those confused me further. Any suggestions?

**Comment by kroitor** [comment]
Hey! Thx for a comprehensive report!

> Also, there are some comments within kucoin about how parseMyTrades will be removed - those confused me further.

First of, the comments are true – it is indeed improper to call a method that is fetching closed orders – fetchMyTrades. Kucoin does not have an endpoint for fetchMyTrades at all. So it just has to be renamed to fetchClosedOrders. Secondly, there is a fetchClosedOrders method for Kucoin already, so these two have to be joined together. The difference between them is that one will call the `orders-dealt` endpoint, the other will call `deal-orders` endpoint. Now, the Kucoin naming / docs are really confusing, but the actual difference between the two endpoints is that one will return all closed orders (will accept a request that isn't specifying a symbol), the other will only fetch orders by a symbol. Thus, we can do something like `let method = (typeof symbol === 'undefined') ? 'first' : 'second'` in fetchClosedOrders... The inevitable consequence of this is, of course, to rewrite parseOrder and parseTrade a little bit...

Going back to the initial issue – if we do the above sequence of changes and edit both parseOrder and parseTrade – this will automatically resolve the side + fee problem, because no trades will be parsed via the current callchain, and in general personal trades for Kucoin (if any) will be parsed within parseOrder, like we do it in other exchanges. I doubt, however, that Kucoin has a personal trades log available in their API, so, this should auto-resolve much earlier than we reach the implementation of `parseTrade`.

Let me know if this makes sense.

**Comment by primski** [comment]
today, my app broke, i am no longer receiving fee from kucoin

fee_asset works
but not fee and feeRate

returns None


not sure why, been debugging all morning
