### ISSUE TITLE
create order in okex: cost is deprecated?

### ISSUE THREAD

**Issue by fonzmeister** [ccxt/ccxt#3316]
- OS:
- Programming Language version:
- CCXT version: 1.15.4
- Exchange: okex
- Method: createorder

as shown in this issue https://github.com/ccxt/ccxt/issues/3060 it is needed to give an extra parameter to the create order function. I believe this is deprecated, allthough I might misunderstand things.

Reffering to the api guide of okex (https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Spot-EN/REST%20API%20for%20SPOT.md) there is no parameter that is costs

The privatePostTrade method works if you enter the amount you would like to spend for the price variable e.g.
```
privatePostTrade({'symbol':btc_ltc,'type':'buy_market','price':0.01}
```

**Comment by kroitor** [comment]
> as shown in this issue #3060 it is needed to give an extra parameter to the create order function. 

That's right.

> I believe this is deprecated, allthough I might misunderstand things.

It is not deprecated.

> Reffering to the api guide of okex (https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Spot-EN/REST%20API%20for%20SPOT.md) there is no parameter that is costs

That's correct, OKEX does not require it. However, for market buys OKEX **requires the cost of the order to be passed in the price parameter**, which is even more confusing than just having a separate cost parameter, because their users will now have to add all sorts of special cases to their code.

> The privatePostTrade method works if you enter the amount you would like to spend for the price variable e.g.

First of, let's clarify: *"the amount you would like to spend"* = cost. This is just the same thing, called differently. Then...

> The privatePostTrade method works if you enter the amount you would like to spend for the price variable e.g.

Yep. However, CCXT does this in a different way. In order to avoid confusion, we do not ask for cost in the price parameter for market orders. Actually, asking for price for market orders is a complete nonsense in itself. Just think about it... 99% of exchanges will require just the amount + extra params (if any) for market orders (which is logical and straighforward), and for OKEX you would need to have a special case where you would pass the **cost** in the **price** param? This sounds like absurd. 

That's why we use the standard set of arguments for market orders (amount + extra params, if any). And the OKEX implementation will require an additional extra parameter in a standard way, like other exchanges do require extra params sometimes. Those parameters can be easily uhm... "parameterized", automated and configured in a unified way for all exchanges.

Hope this answers your question.
