### ISSUE TITLE
OHLCV volume in exchanges

### ISSUE THREAD

**Issue by EmbarAlmog** [ccxt/ccxt#3318]
- OS: Mac
- Programming Language version: Python
- CCXT version: latest
- Exchange: Poloniex
- Method: parse_ohlcv

Hi, 
which volume should be returned when fetching the ohlcv data from the exchanges? base volume or quote volume?
I have noticed that in `parse_ohlcv` in Poloniex, the return volume is the `quoteVolume` instead the `baseVolume` (reversed in 1.10 version) and also in Bittrex, the return volume is ohlcv['V'] instead ohlcv['BV'], while in Bitfinex the base volume is returned.

thanks

**Comment by kroitor** [comment]
Hi!

> which volume should be returned when fetching the ohlcv data from the exchanges? base volume or quote volume?

Base volume, according to the Manual: https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-structure

> I have noticed that in parse_ohlcv in Poloniex, the return volume is the quoteVolume instead the baseVolume (reversed in 1.10 version) and also in Bittrex, the return volume is ohlcv['V'] instead ohlcv['BV'], while in Bitfinex the base volume is returned.

Let's first make sure that you're not confused by words "base" and "quote". The Manual has a separate section on this: https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

In CCXT we call the `base` the currency before the slash, the `quote` is the currency after the slash. Now, Bittrex does call them the opposite. So when Bittrex returns its "base volume" in bittrex-terms, that is a quote volume in ccxt terms and vice-versa.

For example, in ETH/BTC pair, according to CCXT

```
base currency ↓
             ETH / BTC
                    ↑ quote currency
```

Now for this pair, contrary to CCXT, Bittrex will call ETH the "quote" (which isn't true), so they will return V = ETH volume, BV = BTC volume.

So, if by our spec we are to return base volumes for Bittrex, we should return V. Because ETH is the base, not quote.

You can easily verify this with their raw OHLCV, here's one random ETH/BTC raw candle from their ohlcv endpoint:

```
{"O":0.02007731,"H":0.02105000,"L":0.02000946,"C":0.02077383,"V":24315.69209022,"T":"2016-05-10T00:00:00","BV":502.74292032}
```

```
V = 24315.69209022 in ETH (this is base volume in CCXT)
BV = 502.74292032 in BTC (this is quote volume in CCXT, despite that Bittrex calls it BaseVolume)
```

BV / V = ETH/BTC price.

This should make it clear... It's actually base volume (ETH) everywhere in CCXT, if you look at the overall unified picture. Hope this answers your question.

**Comment by EmbarAlmog** [comment]
Thanks for the detailed answer!
What is the reason for the change in Poloniex? does Poloniex call them the opposite also?

**Comment by kroitor** [comment]
> does Poloniex call them the opposite also?

Yep! Here it is, an ETH candle for Poloniex:

```
{"date":1530748800,"high":0.0715192,"low":0.07065441,"open":0.07084501,"close":0.07136499,"volume":107.91147068,"quoteVolume":1516.33633534,"weightedAverage":0.07116592}
```

So:

```
volume = 107.91147068
quoteVolume = 1516.33633534
```

Obviously, with ETH/BTC, their quoteVolume (ETH) is our base volume in CCXT. So, Poloniex is the same as Bittrex.

**Comment by EmbarAlmog** [comment]
Thanks a lot!

**Comment by EmbarAlmog** [comment]
Hi @kroitor, I have a follow up question on this subject: could you please elaborate on the reasons behinds the decision to quote the OHLCV volume in base currency and not in the quote currency (which is more intuitive and the one being used in stock market). Thanks

**Comment by kroitor** [comment]
@EmbarAlmog hi! 

Despite that volumes of stocks may be denoted in quote currency, most crypto exchanges will output OHLCV candles with volumes in base currency, so we just use what the majority of exchanges offers. I think, this is due to the nature of the base assets themselves. 

If you think of it, when you see `"a volume of 50 AAPL"` that doesn't really tell you much about the actual value of that volume, right? And if you convert that number to USD (something used for everyday calculations) that will tell you the value of that volume immediately. So, maybe, with stocks it is more comfortable for humans to estimate the values of those volumes in quote currency. Wikipedia disagrees, however: https://en.wikipedia.org/wiki/Volume_(finance)

Crypto and Forex, is the opposite case – when you trade currency-for-currency (compared to stock-for-currency) you usually want to see the volumes in the base currency. It kinda tells you how much that is. 

Examples: 

- Quite confusing: "buy BTC for a total value (cost) of $10000 for a price of 0.0001BTC/USD"
- Much cleaner: "buy 1 BTC for a price of 0.0001BTC/USD"

The deeper reasoning behind that is most likely related to the way these assets are emitted, emission rules with currencies, crypto and stocks are often all very different.
