### ISSUE TITLE
CCXT structure for meteor applications

### ISSUE THREAD

**Issue by DanMan259** [ccxt/ccxt#3341]
- OS: Ubuntu 16.04
- Programming Language version: Meteor.js 1.7.03
- CCXT version: Latest 1.15 or whatever
- Exchange: Most of them
- Method: Pulling Transaction Data, and most public pricing endpoints

It's not exactly an issue and you recommend to read the manual for these things, but I could find any help for this.

I wanted to know how would you structure this library in a meteor application. I wanted to know how to structure the server side code so that I could pull transaction history from the private endpoints at the user's request. The user would be able to choose their desired exchange and it will allow them to put in their API key and secret.

I also wanted to know how to structure to pull pricing data from public endpoints. I intend to make a live feed for this data.

Do I separate the files based off the exchange or methods and call the files required dependant on the action. 

Is there an example or guide that I could base it off of or any recommendations.

**Comment by mkutny** [comment]
> I wanted to know how would you structure this library in a meteor application.

Actually, you don't structure this library, you structure your app.

And this leads to the question... do you have meteor issue or ccxt issue? I mean, do you have experience of writing Meteor apps? Because, if you don't then you'll probably need to seek an advice elsewhere.

> Is there an example or guide that I could base it off of or any recommendations.

As for ccxt there are plenty of examples in `/examples/js/` folder. They are neat and it's wise to take a look at them.

I believe that if:
1) you can write a Meteor app that makes use of a DB (or any other async resource)
2) you can write a minimalistic ccxt script that queries an exchange
then replacing DB calls with ccxt calls should not be an issue.

**Comment by pcriadoperez** [comment]
@DanMan259  Is this ok close?
