### ISSUE TITLE
A question about new exchanges

### ISSUE THREAD

**Issue by Cleric334** [ccxt/ccxt#3387]
Hello.

Sorry if I ask in the wrong place, but is it possible to speed up the addition of certain exchanges for some crypto donation? If yes, how much could it be?

I really enjoy ccxt, but it's lacking some exchanges i would love to test now, so please take my question as a sincere one.

Thanks in advance.

**Comment by frosty00** [comment]
Difficulty here is trust, most people work on ccxt for free or for their own projects, how can they be sure that you will pay them if they write this exchange class. 

Perhaps something like https://gitcoin.co/ could help to solve this problem.

**Comment by Cleric334** [comment]
Well, it's no problem. I have a list of exchanges I am interested in, I post the list, ccxt contributers take a look and tell for how much they are going to implement each of those, they name the price, i consider it, and if it's ok with me, i pay them and wait for task completion.

ccxt is truly an awesome library and I have trust in people contributing to it, so payment in advance is not a problem for me.

**Comment by kroitor** [comment]
@frosty00 

> how can they be sure that you will pay them if they write this exchange class?

![e482148e6d82af3c2282437b43fdbe79650b9a7a_128](https://user-images.githubusercontent.com/1294454/42715178-748ecebe-86fe-11e8-975a-a0111ecf400e.jpg)

))

@Cleric334 

>  I post the list, ccxt contributers take a look and tell for how much they are going to implement each of those, they name the price, i consider it, and if it's ok with me, i pay them and wait for task completion.

I'd suggest to start by posting the list here, and we could use this issue to synchronize and distribute the workload among developers. Many of them, including myself, are currently working to integrate this or that exchange. So, it all depends on the list, of course. Also, I'd suggest to put your own price tag on at least one exchange from your list (how much you are willing to pay), you need to initiate it somehow by example.

The CCXT Dev Team can also be an intermediary in the settlement and could force the contract or  guarantee job quality / payment.

> ccxt is truly an awesome library and I have trust in people contributing to it, so payment in advance is not a problem for me.

Beware of the scammers, don't send any money to anyone claiming to do the job unless you're absolutely sure in what you're doing.

**Comment by valentinbora** [comment]
@kroitor would you be okay as a general approach to implement fetchTicker(s)/loadMarkets methods for new exchanges first, and then improve their capabilities afterwards?

Self-serving disclaimer: I personally need as many exchanges integrated as possible, with just the basics, and am willing to submit pull requests for them.

**Comment by kroitor** [comment]
@valentinbora we usually implement the following methods as the base set:
- fetchMarkets
- fetchTicker(s)
- fetchOrderBook(s)
- fetchOHLCV
- fetchTrades
- createOrder
- cancelOrder
- fetchOrder(s)
- sign ()

We also often add these to the base set:

- fetchOpenOrders
- fetchClosedOrders
- fetchOrderTrades
- fetchMyTrades
- fetchDepositAddress
- withdraw

Basically, it's very easy to implement fetchMarkets + fetchTickers in most cases, but I'm not sure if we can integrate just those two methods, as most people would expect at least some trading functionality, orderbooks, trades... We can, however, start implementing those and submit them in Pull Requests (branches), so that other people could fork them and add more methods to them. How does that sound to you?

**Comment by valentinbora** [comment]
@kroitor thanks! As far as I am concerned, any progress is good progress.
