### ISSUE TITLE
Bitfinex FetchOHLCV since error when use BTC symbol

### ISSUE THREAD

**Issue by cristianm** [ccxt/ccxt#3393]
- OS: Windows/Linux
- Programming Language version: v10.6.0
- CCXT version: 1.16.18
- Exchange: bitfinex
- Method: FetchOHLCV 

I try to get candles. All work fine with anothers exchanges and FIAT symbols, but when try to get for example candles for BTC/CBT, last 100 candles based on perior, or last 5 doesn´t work, get empty result. 

example for period 15m:

var momentSince = moment().utc();
momentSince.subtract(100 * 15, 'minutes');
var since = momentSince.format('x')

await exchange.fetchOHLCV('CBT/BTC', '15m', since)

**Comment by kroitor** [comment]
Check this out:

- https://api.bitfinex.com/v2/candles/trade:15m:tCBTBTC/hist?sort=1&limit=100&start=1531487715948 (returns an empty response `[]`)
- https://api.bitfinex.com/v2/candles/trade:15m:tCBTBTC/hist?sort=1&limit=100&start=1530403200000 (returns a non-empty response)
- https://api.bitfinex.com/v2/candles/trade:15m:tCBTBTC/hist?sort=1&limit=100&start=1530404100000 (returns a non-empty response)

Looks like Bitfinex requires your timestamp to be a multiple of the timeframe, 15m (900000 milliseconds) in this particular case. 

- 1531487715948 % 900000 = 15948
- 1530404100000 % 900000 = 0
- 1530403200000 % 900000 = 0

I'll add a fix for this shortly.

P.S. Also, make sure that your since value is UTC **in milliseconds**.

**Comment by kroitor** [comment]
Hm... this is evenly divisible by 15 minutes, but does not work, however: https://api.bitfinex.com/v2/candles/trade:15m:tCBTBTC/hist?sort=1&limit=100&start=1531487700000

Something is wrong here...

**Comment by kroitor** [comment]
@cristianm is it displayed correctly on their website for you? It is all empty on my side:

<img width="1000" alt="screen shot 2018-07-14 at 17 36 28" src="https://user-images.githubusercontent.com/1294454/42725468-7d37d9be-878c-11e8-9802-79952889df1a.png">

Other timeframes look weird as well...

**Comment by kroitor** [comment]
Ok, they don't really seem to have any trading history for the past week for that symbol.
