### ISSUE TITLE
Bittrex methods  XToPrecision return float instead of string

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#3428]
- Programming Language version: Python
- CCXT version: ccxt-1.16.57
- Exchange: bittrex, bitfinex
- Method: XToPrecision

Hi,
I just found that, while all other exchanges I used so far return a string on the method XToPrecision (fee,cost,amount etc), the **bittrex** exchange returns a float!

```
ct = ccxt.bittrex()
ct.loadMarkets()
ct.costToPrecision('ETH/BTC',0.00100000)
```
--> float
```
ct = ccxt.binance()
ct.loadMarkets()
ct.costToPrecision('ETH/BTC',0.00100000)
```
--> string (also for other exchanges such as kraken, kucoin and bitfined

Also it seems that the **bitfinex** feeToPrecision is not working, as it always returns a key error for any symbol.

**Comment by kroitor** [comment]
> I just found that, while all other exchanges I used so far return a string on the method XToPrecision (fee,cost,amount etc), the bittrex exchange returns a float!

That's right, but you should not rely on the type of the output of that method, really, because it will generate an exchange-specific return-type anyway. Some exchanges will require floats, others will require strings. 

> Also it seems that the bitfinex feeToPrecision is not working, as it always returns a key error for any symbol.

You should loadMarkets for it first.

Let us know if this does not answer your question.

**Comment by MarcelBeining** [comment]
Hi, ok thanks.
However concerning bitfinex, I actually **did** load the market:
```
ct = ccxt.bitfinex()
ct.loadMarkets()
ct.feeToPrecision('ETH/BTC',0.00100000)
```
--> error

**Comment by kroitor** [comment]
> ```ct.feeToPrecision('ETH/BTC',0.00100000)```
↑ That's an error, bitfinex uses currency precision for fees instead of pair-precision...

`ct.feeToPrecision('ETH',0.00100000)` or `ct.feeToPrecision('BTC',0.00100000)` will work.

In other words, I'm telling you: you should not rely on any non-documented methods, as most of them are there for internal exchange-specific needs, instead of using `feeToPrecision`, you should rather calculate the fee with `calculateFee`, for example. This particular aspect is very hard to unify and the work on it is still in progress.

**Comment by kroitor** [comment]
We are thinking of redesigning this a bit, namely, remove amountToPrecision and priceToPrecision and use a generic toPrecision method, that would accept a currency code and a value and would work in a unified way for amounts, prices, costs and fees. We would document the new set and you could build upon it then. Hope to do it soon. And will let you know, of course.
