### ISSUE TITLE
New Exchange: bitasiaex.com

### ISSUE THREAD

**Issue by toorq** [ccxt/ccxt#3442]
website: https://www.bitasiaex.com/
api doc: https://www.bitasiaex.com/about/about.html?id=115

**Comment by toorq** [comment]
I have completed the code.
The code is in here:

https://github.com/toorq/ccxt/blob/master/js/bitasiaex.js

Thanks.

**Comment by toorq** [comment]
Hello, kroitor.
Have you read my code ?

**Comment by kroitor** [comment]
Hi, @toorq ! Yep, I've seen the code. It will require some cleanup before we can merge it, because it doesn't pass the tests and is not yet transpileable according to principles described here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes. 

I'll do my best to merge it asap in a portable way.

**Comment by kroitor** [comment]
The exchange is inaccessible.
