### ISSUE TITLE
Bittrex api endpoint question 

### ISSUE THREAD

**Issue by AlessandroSpallina** [ccxt/ccxt#3456]
Hello, 
Ccxt uses v1.1 api version, other libraries uses instead v2.0

Are there some kind of differences about speed or what?

**Comment by kroitor** [comment]
Hi!

> Ccxt uses v1.1 api version, other libraries uses instead v2.0

That's not true! ) 

CCXT uses both 1.1 and 2.0: 
- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L45
- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L58

We just don't use v2 for private APIs in CCXT (yet?).

The v2.0 API isn't actually an API. It is a reverse-engineered list of their website endpoints. I guess, at this point many coders have reverse-engineered it already. The docs posted as result of that job are unofficial: https://github.com/thebotguys/golang-bittrex-api/wiki/Bittrex-API-Reference-(Unofficial). So, in fact, v2.0 can change if Bittrex does a redesign of their website, because, well, it's unofficial. Hope this answers your question. Let us know if not.

**Comment by Showgofar** [comment]
create order api v2 contains TimeInEffect parameter 
that why i had asked about implementation of TradeBuy and TradeSell 
=)
