### ISSUE TITLE
'timestamp' in parse_orders should be descending

### ISSUE THREAD

**Issue by ouyangtianzuo** [ccxt/ccxt#3461]
in exchange.py

    def parse_orders(self, orders, market=None, since=None, limit=None):
        array = self.to_array(orders)
        array = [self.parse_order(order, market) for order in array]
        **array = self.sort_by(array, 'timestamp')**
        symbol = market['symbol'] if market else None
        return self.filter_by_symbol_since_limit(array, symbol, since, limit)

the array is better  descending sort by timestamp

because if you use 'limit' params to fetch_closed_orders, the order of orders will be chaos

**Comment by kroitor** [comment]
Sorry, but we don't agree. The logic behind it is to fetch `limit` rows starting from `since` timestamp into the future (not backwards). We've switched from what you proposed to ascending sorting order in all methods returning trades, orders, candles and other arrays. Hope this answers your question. Let us know if not.
