### ISSUE TITLE
dup coin: HOT is Holo in liqui and binance

### ISSUE THREAD

**Issue by arielorvits** [ccxt/ccxt#3470]
https://twitter.com/Liqui_Exchange/status/1021401132579672067

**Comment by kroitor** [comment]
@arielorvits why did you close it? )

**Comment by arielorvits** [comment]
by mistake

**Comment by arielorvits** [comment]
@kroitor , if you choose Holo as the default - you should add
'HOT': 'Hydro Protocol'
to: okex, hadax, bitfinex
https://coinmarketcap.com/currencies/hydro-protocol/#markets
thank you

**Comment by kroitor** [comment]
@arielorvits sure, will do that shortly, thx for pointing that out!

**Comment by kroitor** [comment]
@arielorvits by the way, we've been fixing these inconsistencies with your help for some while now and  I'm sure you see that most of my edits are very basic one-liner re-mappings of symbolic codes. 

So, I thought, maybe you'd want to try pull-request mode so that the very important and helpful thing that you do would be properly shown in our contributors section? ) If you will, we'd very thankful ) I mean, we can optimize the procedure. That, however, would require you to submit those edits. We will moderate that in our turn.

You can easily edit them right here in the web-editor on GitHub by just navigating to a file and clicking the `edit` pencil <img width="18" alt="screen shot 2018-07-27 at 08 19 27" src="https://user-images.githubusercontent.com/1294454/43302877-d2cb606a-9175-11e8-8a2b-bf14c8247a31.png"> + a couple of clicks.


Anyways, your help is very much appreciated and thx for your involvement in this!

**Comment by arielorvits** [comment]
@kroitor 

of course, good idea, I'll try this next time I'll have a fix.

thank you
