### ISSUE TITLE
ccxt.base.errors.AuthenticationError: kucoin

### ISSUE THREAD

**Issue by Mantas779** [ccxt/ccxt#3473]
ccxt.base.errors.AuthenticationError: kucoin {"code":"UNAUTH","msg":"System error, please retry later.","success":false,"timestamp":1532428426997}

Worked fine, till now?  Just retry later ?
Is this my coding, ccxt, or KUCOIN side ?

Thx for the good work on CCXT

**Comment by kroitor** [comment]
You see, this thing: `{"code":"UNAUTH","msg":"System error, please retry later.","success":false,"timestamp":1532428426997}` including the phrasing in the `msg` is coming from the exchange itself, thus these questions: `Worked fine, till now? Just retry later ?` should most likely be redirected to Kucoin ) 

But hey, nothing happens without a reason, so if it did work fine and stopped working now, you can:
- wait and retry as they say
- try to understand what might have changed since "then" and what's different "now"

This might be something related to the timezone, for example. Or to current load on their system. So the reason behind it might be very different and without knowing much more details from you it would be really hard to actually help you. For example, have you performed our troubleshooting sequence already? You didn't write about it and it's hard to guess from your post ;)

**Comment by Mantas779** [comment]
Yes, i did a troubleshooting sequence.
Used a 1 line code example to see if i get the same error.
I use this code always to check if my Key and secret. nonce enz are working fine, and use the right code to lets say get my BTC balance 

btc = Exchange.fetchBalance()['BTC']['free']
print(btc)

if this works i go further in my project. 
Thought it was on KuCoin sight, but feels so useless now, just to wait and try later.

Thx for reply.

**Comment by Mantas779** [comment]
Pffffffff, looks like they fixed it!!!

Process finished with exit code 0

**Comment by kroitor** [comment]
Yeah, these errors may be intermittent. Thx for reporting anyways! Looks like their `msg` was telling the truth.
