### ISSUE TITLE
1.17.* Requirements

### ISSUE THREAD

**Issue by ccasselman** [ccxt/ccxt#3490]
- OS: MacOS High Sierra
- Programming Language version: PHP 7.1 & 7.2
- CCXT version: 1.17.*
- Exchange: None
- Method: None

In version 1.17.* you made ext-gmp required by composer.  Is this absolutely required.  

I develop locally on a Mac and that extension is no longer stand alone.  I can't find a way to get this thing to run on my box anymore - I've tried about 6 methods and wasted over 12 hours on this.  I'm no systems guy so maybe I am missing something.  All existing docs no longer work because the repo has been deprecated/archived.

If at all possible, is there a way to use an active package?

If this is my problem not yours, just delete this issue.

**Comment by kornrunner** [comment]
I'll just chime in:

Requirement is propagated through 3rd party packages required for elliptic curve cryptographic functions for signing orders. If you need this feature in ccxt - then you'll need to find a way to install / compile php with GMP extension (sorry, can't help much with that, I'm not MacOS user). 

In case you don't need it - then you can pass a flag `--ignore-platform-reqs` to composer and then it will ignore such requirements. I can't say that's advised or a good way to go (since it will ignore all requirements, not just gmp one) - but it should "solve" the problem.
