### ISSUE TITLE
Gdax Missing fetchDepositAddress 

### ISSUE THREAD

**Issue by itsmemittal** [ccxt/ccxt#3505]
Hi, I need to get deposit address through API in Gdax but in code what I found that library does not have the depositAddress function in it.

Is there any alternative to get DepositAddress in gdax?

**Comment by kroitor** [comment]
Hi!

Yes, see here: https://github.com/ccxt/ccxt/pull/2610 (will merge it to master soon) or here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if it does not answer your question.

**Comment by itsmemittal** [comment]
Would you help me in an example how would I do DepositAddress for gdax

**Comment by kroitor** [comment]
I've added the implementation for it, however, it will only work with coinbase accounts. Let me know if you have difficulties with it, however, make sure to report any issues precisely like shown here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. In order to help you with it will need your code and a complete log of your verbose requests and responses (without the keys). We would be happy if you report back whether it works for you or not.

**Comment by itsmemittal** [comment]
Hi,
Problem is I am trying with Gdax, not Coinbase. so do we have such methods which will get us to deposit address on gdax not on coinbase.

**Comment by kroitor** [comment]
@itsmemittal GDAX is Coinbase basically... Most people deposit crypto to GDAX via Coinbase like so:

```
User → Coinbase → GDAX 
```

and withdraw crypto from GDAX via Coinbase like so:

```
GDAX → Coinbase → User
```

I'm not sure if you have any other way of actually getting a deposit address other than that associated with your Coinbase account. Hope this answers your question.

**Comment by itsmemittal** [comment]
Thanks, I understood.
