### ISSUE TITLE
binance.fetch_ohlcv since argument

### ISSUE THREAD

**Issue by eloiup** [ccxt/ccxt#3507]
- OS: ubuntu 16.04
- Programming Language version: python 2.7
- CCXT version: 1.17.29
- Exchange: binance
- Method: fetch_ohlcv 

Since argument seems to be broke

`binance.fetch_ohlcv('BTC/USDT', timeframe='1d', limit=3)`

retrieves ohlcv from the last 3 days just fine.

if we add the since argument:

`binance.fetch_ohlcv('BTC/USDT', timeframe='1d', limit=3, since=int(time.time()-60*60*24*10))`

retrieves data from 2017

**Comment by kroitor** [comment]
The `since` argument as well as other timestamps returned from this library are all integer UTC timestamps **in milliseconds** everywhere throughout the code. Your `since` value is a float in seconds. I've added a clarification on that to the Manual on fetchOHLCV as it wasn't mentioned there in particular. Thx for pointing that out!

I'd rather recommend to use `iso8601/parse8601` methods btw:

```Python
since = binance.parse8601('2018-07-24T00:00:00Z')
binance.fetch_ohlcv('BTC/USDT', '1d', since, 3)
```

**Comment by rexovas** [comment]
I myself am using the ciso8601 module, I've written a simple function to convert date strings to UNIX timestamp format in milliseconds:

```
import ciso8601
import datetime
import time

def getUNIX(input_date):
    UNIX = int(time.mktime(ciso8601.parse_datetime(input_date).timetuple()) * 1000)
    return UNIX
```
```since = getUNIX('2017-01-01')``` or ```since = getUNIX('2017-01-01T00:00:00Z')```
