### ISSUE TITLE
Kucoin: Can not get rid of "Signature verification failed" error on private API

### ISSUE THREAD

**Issue by dmittal3** [ccxt/ccxt#3517]
Hi @kroitor ,
I am trying to simply fetch account balances and formed below unix commands to do that:

!/Bin/Sh
kcAPIkey=5b5cxxxxxxxxx
kcSecretKey=xxxx-xxx-xxxxxxx-xxx-xxxx
nonce=$(($(date +%s%N)/1000000))
secret=$(echo -n "/v1/account/balances/$nonce" | base64 | openssl dgst -sha256 -hmac "$kcSecretKey" | sed 's/.*= //')
curl -s -H "KC-API-KEY: $kcAPIkey" -H "KC-API-NONCE: $nonce" -H "KC-API-SIGNATURE: $secret" -X GET 'https://api.kucoin.com/v1/account/balances'

Error message of the file at my path: {"code":"UNAUTH","msg":"Signature verification failed","success":false,"timestamp":1532805181671}

Can you please help as documentation doesn't seems alright and all the places I search over internet many people reporting this issue.

OS:Ubuntu
Programming Language: Unix
Exchange: Kucoin

**Comment by kroitor** [comment]
1. It's `/v1/account/balance`, not balance**s**
2. Your nonce is not calculated correctly, the %N flag doesn't work everywhere, and you should rather use a seconds timestamp multiplied by a thousand.
3. The base64 payload for signing should be output with `printf` instead of `echo`, otherwise it will produce weird encoded results (google `base64 shell different`)

A working script:

```sh
#!/bin/sh

kcAPIkey="5b5cxxxxxxxxx"
kcSecretKey="xxxx-xxx-xxxxxxx-xxx-xxxx"

nonce=$(($(date +%s)*1000))
endpoint="/v1/account/balance"
query=""
payload64=$(printf "$endpoint/$nonce/$query" | base64)
secret=$(printf "$payload64" | openssl dgst -sha256 -hmac "$kcSecretKey" | sed 's/.*= //')

curl -s -H "KC-API-KEY: $kcAPIkey" -H "KC-API-NONCE: $nonce" -H "KC-API-SIGNATURE: $secret" -X GET 'https://api.kucoin.com/v1/account/balance'
```

Sorry, but this is beyond the scope of CCXT and we can't really offer support for that in future, hope for your understanding. The general rule of thumb is: whenever your signing procedure doesn't work, break it into smallest possible parts/pieces and compare each piece at each step against a working example (code from CCXT). Hope this helps.

**Comment by dmittal3** [comment]
Thanks a lot @kroitor 
I checked as per your working code and it seems the code mistake was in base64 payload as I was not breaking it to the level you provided and it was not producing correct input for hmac encoding.

Writing below my findings, so that it can help others (including noobs like me) with similar questions and landing to this post:

1. It's /v1/account/balance (without s), not balances
:: With balance**s** you get paged output, default is only page 1 (here I see that Kucoin documentation is not enough detailed)

2. Your nonce is not calculated correctly, the %N flag doesn't work everywhere, and you should rather use a seconds timestamp multiplied by a thousand (however, this will effectively rate-limit your requests to one per second, otherwise they will start interfering with each other's nonces)
:: my output with %N flag also coming same, so no issues here

3. The base64 payload for signing should be output with printf instead of echo, otherwise it will produce weird encoded results (google base64 shell different)
:: This is the life saver to break down the code and calculating payload separately. I hoped that unix should take it properly even in single line code, but somehow its not producing desired results. 
However, I found that printf is equivalent to echo -n and it worked well for me.

This much support was big enough for me!!
Thanks again for your kind help.
