### ISSUE TITLE
fetchOrderHistory fail on symbol='' ; used to work

### ISSUE THREAD

**Issue by creslinux** [ccxt/ccxt#3614]
Hi!

Im not sure if this is a defect, its a change in behaviour.

Against sandbox api on GDAX the following used to work to fetch all OpenOrders
`all_open_orders = exchange.fetchOpenOrders(symbol='', since="", limit="", params={})`

Now the following error is returned. 
`ccxt/base/exchange.py", line 312, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: gdax No market symbol`

Requesting without symbol passed empty works as prior behaviour 
`all_open_orders = exchange.fetchOpenOrders(since="", limit="", params={})`

- OS: Ubuntu 18:04
- Programming Language version: 3.6 Python
- CCXT version: 1.17.85
- Exchange: gdax sandbox
- Method: fetchOpenOrders

**Comment by kroitor** [comment]
@creslinux we don't accept empty strings in the args anywhere, so, if you want to pass an empty symbol, it should be None: `exchange.fetchOpenOrders(symbol=None, since=None, limit=None, params={})`. You're right, it did work with some exchanges earlier, but the fact that it used to work with an empty string is more like a bug. It should not accept empty strings, really. None-values are used to indicate the absence of the value instead.

Let us know if it does not answer the question. Thx!)
