### ISSUE TITLE
Gemini market order discrepancy

### ISSUE THREAD

**Issue by frankhucek** [ccxt/ccxt#3621]
- OS: High Sierra v10.13.6
- Programming Language version: Node v8.11.3
- CCXT version: 1.17.101
- Exchange: Gemini
- Method: createOrder

Issue:
After confirming market orders are supported on Gemini through the ``hasMarketOrder`` property, I attempt to place a market order. The returned response is an error stating that Gemini supports limit orders only, so there is a discrepancy between the ``hasMarketOrder`` property and the ability to place a market order.

In the output below, I confirm the ccxt version is current.

Code:
```
console.log(require ('ccxt').version);
let exchange = new ccxt.gemini({
    apiKey: gemApiKey.key,
    secret: gemApiKey.secret
});
console.log(exchange.hasCreateMarketOrder);
let res = await exchange.createOrder ('ZEC/ETH', 'market', 'buy', '.005', '167.00', {});
console.log(res);
```
Output:
```
1.17.101
true
{ Error: gemini allows limit orders only
    at gemini.createOrder (/Users/user/Code/project/node_modules/ccxt/js/gemini.js:293:19)
```

Thanks for the help!

**Comment by kroitor** [comment]
@frankhucek indeed, there was an inconsistency with the `has` flag, I've added it, so this should be fixed in next version (arriving in 5-10 minutes). One note on the above: the `hasCreateMarketOrder` as well as other properties starting with `hasBlaBla` are deprecated, and I highly recommend switching to the new metainfo property – `exchange.has['createMarketOrder']`. All those properties are collected under the `exchange.has` associative array, in a single property of the exchange.

**Comment by frankhucek** [comment]
@kroitor Awesome, thanks for the update.
