### ISSUE TITLE
fetch_transactions issue currency['code']

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#3636]
Hi @kroitor , I tested the unified fetch transactions new feature after you merged it.

I'm testing with python and I tested cobinhood fetch_deposits.

I get this error:

```
  File "/home/paul/env/crypto-accounting/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1266, in parse_transactions
    code = currency['code'] if currency else None
```

I was tempted to fix this in Exchange.js, as follows:

in `parseTransactions `instead of:
```
        let code = (typeof currency !== 'undefined') ? currency['code'] : undefined;
```

push a PR:
```
        let code = (typeof currency !== 'undefined') ? currency : undefined;
```

But then I saw that `parseTrades` and `parseOrders` have the same issue (with `market['symbol']`). Why are they like this?
What kind of object do you expect from `currency` (or `market`)? I was thinking that currency would be a string e.g BTC, EUR etc. and should not be a dictionary containing code (and what else besides code?)?

If the object is correct, then the fix would be as follows?
```
        let code = (typeof currency !== 'undefined' && typeof currency['code']  !== 'undefined') ? currency['code'] : undefined;
```

**Comment by kroitor** [comment]
> Why are they like this? What kind of object do you expect from currency (or market)?

Check out the `.currencies` property and the `.currencies_by_id` property as well:

<img width="692" alt="screen shot 2018-08-12 at 23 48 05" src="https://user-images.githubusercontent.com/1294454/44006269-2e520742-9e8a-11e8-8ff3-3e1a02d06ec0.png">

- `markets` by pair `symbol` (unified)
- `markets_by_id` by pair `id` (exchange-specific)
- `currencies` by currency `code` (unified)
- `currencies_by_id` by currency `id` (exchange-specific)

The second argument of the parseOrder, parseTicker, parseTrade is a `market` object. The argument for parseTransaction is the `currency` object.

> If the object is correct, then the fix would be as follows?

Nope, because you can't dereference keys to check for their existence in Python, like you're used to do in JS, thus this construct will throw an exception in Python:

```
typeof currency['code']  !== 'undefined'  // no 'code' key in Python = Exception
```

So the "proper fix" is there already a few lines below: https://github.com/ccxt/ccxt/blob/master/js/cobinhood.js#L651

```JavaScript
        if (typeof currency !== 'undefined') {
            code = currency['code'];
        }
```

However, if that leaves the `code` undefined in your particular case, then please show your verbose output, this might be due to inconsistencies in lowercase/uppercase currency ids and we have a workaround for that as well. Can you post your verbose response from the exchange, plz?

**Comment by kroitor** [comment]
I'll add a fix for the above issue with line 1266 in a few minutes.

**Comment by kroitor** [comment]
I've uploaded it and it should be there in 5-10 minutes, version 1.17.117+. Thx for reporting!
