### ISSUE TITLE
What is the expected cancelOrders behavior

### ISSUE THREAD

**Issue by ahmohamed** [ccxt/ccxt#3638]
I am asking about cancelOrders([order_ids) should behave when one or more of the orders throw an error. I am investigating this function in BTCMarkets.

Consider this example:

```js
let valid_id = '1234';
let invalid_id = '4567';

some_exchange.cancelOrders([valid_id, invalid_id])
```

At least in BTCMarkets, the response is as follows:

```js
responses:[
  {success: true, errorCode: null, errorMessage: null, id: 1234},
  {success: false, errorCode: 3, errorMessage: "order does not exist.", id: 4567}
]
```

Should the method behave as `Promise.all` and throw an `OrderNotFound `, or return an array `[ {success: true, id:1234}, OrderNotFound ]`?

**Comment by ahmohamed** [comment]
I ended up with iterating through `responses` and throwing `InvalidOrder` if any had `success=false`. I thought it should behave similar to `fetchOrderBooks`, supplying a mix of valid and invalid symbols. 

The only caveat is that the info about the successfully cancelled order is lost, but I think this is not critical. It will just cost the user an extra `cancelOrder` request.

Let me know what you think.

**Comment by kroitor** [comment]
> I ended up with iterating through responses and throwing InvalidOrder if any had success=false. I thought it should behave similar to fetchOrderBooks, supplying a mix of valid and invalid symbols.
> Let me know what you think.

Yep, I would do the same as a temporary solution, until we come up with a better design for exception handling.

> The only caveat is that the info about the successfully cancelled order is lost, 

Yep, this is what bugs me very much, the user would rather not lose it, of course, if possible.

> but I think this is not critical. It will just cost the user an extra cancelOrder request.

In fact, for a real trading operation, the extra request itself is critical, so it looks like we will have to redesign our exceptions a bit. We have been planning for this, and we think exceptions should unify the following:
- unified method name
- endpoint name
- unified exception type(s)
- exchange-specific error code(s)
- exchange-specific error string(s)
- unified error string(s)
- other flags and exchange-specific options
- HTTP:
  - URL
  - method name
  - request query params
  - request body params
  - error code
  - request headers
  - response headers
  - response body

All of the above can become quite tricky ti implement in a portable way, especially with very few specific cases where there's no other way to fetch the data, except by issuing more than one http request.

But yeah, in general, this is still an open question, and we have to approach it carefully, but will have to unify this, sooner or later. It's not unified yet, because there were (and still are) a few more critical aspects, namely these: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#pending-tasks

**Comment by kroitor** [comment]
> I ended up with iterating through responses and throwing InvalidOrder if any had success=false.

One thing to clarify here: I'd rather throw OrderNotFound if any of them was not found, and would throw InvalidOrder, if any of them was invalid, depending on the answer from the exchange. In this particular case with HitBTC, I'd throw OrderNotFound, because: `{success: false, errorCode: 3, errorMessage: "order does not exist.", id: 4567}`. Though, it depends on how you look at it, you might consider `"not exists" == Invalid`, `"not exists" != NotFound` for your specific use case.

**Comment by ahmohamed** [comment]
Sure. I am not quite sure how to do partial string matching (for error message) in a portable way. Didn't find any examples outside the base `Exchange` class. Ideally, I would do `if (errorMessage.match(/not exist/)){...}` or `.search`, but that is not portable. I couldn't find a suitable core function also.

**Comment by ttodua** [comment]
@carlosmiei please mention two words here and we can probably close this too

**Comment by ttodua** [comment]
unified approach is to return an array of orders, where the failed orders would have .status = failed/rejected etc.
however, if some exchange throws exception directly, ccxt might also directly throw an exception in some cases instead of returning an array.
