### ISSUE TITLE
[possible bug] hitbtc2.fetch_my_trades omits all "CL/BTC" transactions

### ISSUE THREAD

**Issue by pjboro** [ccxt/ccxt#3639]
- OS: Ubuntu Bionic (as host and client) in docker
- Programming Language version: Python 3.7.0 (default, Jul 17 2018, 11:04:33) \n[GCC 6.3.0 20170516]
- CCXT version: ccxt-1.17.60.dist installed by pip3
- Exchange: hitbtc using hitbtc2 module
- Method: fetch_my_trades()

Hi!

I found something strange while trying to download my transactions history: the ccxt omits all the transactions from market "CL/BTC". We're talking both buy and sell trades. "CL/BTC" is not available to trade on hitbtc anymore, and so is not listed in hitbtc2.markets. When we try to explicitly download history of trades done on this market, we get an exception. We should be able to download all the history, not only the history of pairs that are available now, and many apis make that possible.
I don't know if the (possible) bug is only present in hitbtc2 module; I suppose it is an architectural problem concerning all available modules. I looked at some with fetch_my_trades already implemented, and all of them use self.market function as shown below.

Had anyone had a similar problem? What would be the best way to correct this? I'm new to your library, and I don't want to write ugly hacks if there is a nice way you would recommend.

Thanks for this library: the idea is great, and the amount of work you already did is huge. I like it.

```
# This is the way I download the trades history. Nothings fancy, not much to talk about.
hitbtc = ccxt.hitbtc2(hitbtc_keys)
my_trades = hitbtc.fetch_my_trades()

# Trying to get history of a pair that is not traded anymore, we get an exception.
hitbtc.fetch_my_trades("CL/BTC")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/hitbtc2.py", line 1007, in fetch_my_trades
    market = self.market(symbol)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1336, in market
    self.raise_error(ExchangeError, details='No market symbol ' + str(symbol))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 312, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: hitbtc2 No market symbol CL/BTC
```

We can see possible problems if we take a look at this snippet:

```
# [...]
    def market(self, symbol):
        if not self.markets:
            self.raise_error(ExchangeError, details='Markets not loaded')
        if isinstance(symbol, basestring) and (symbol in self.markets):
            return self.markets[symbol]
        self.raise_error(ExchangeError, details='No market symbol ' + str(symbol))
# [...]
 def fetch_my_trades(self, symbol=None, since=None, limit=None, params={}):
        self.load_markets()
        request = {
            # 'symbol': 'BTC/USD',  # optional
            # 'sort':   'DESC',  # or 'ASC'
            # 'by':     'timestamp',  # or 'id' String timestamp by default, or id
            # 'from':   'Datetime or Number',  # ISO 8601
            # 'till':   'Datetime or Number',
            # 'limit':  100,
            # 'offset': 0,
        }
        market = None
        if symbol is not None:
            market = self.market(symbol)
            request['symbol'] = market['id']
        if since is not None:
            request['from'] = self.iso8601(since)
        if limit is not None:
            request['limit'] = limit
        response = self.privateGetHistoryTrades(self.extend(request, params))
        return self.parse_trades(response, market, since, limit)
```

**Comment by kroitor** [comment]
Hi!

> I found something strange while trying to download my transactions history: the ccxt omits all the transactions from market "CL/BTC".

It *does not omit* them, actually...

> We should be able to download all the history, not only the history of pairs that are available now, and many apis make that possible.

You can download it with CCXT, however, you gotta understand the inner workings of the library, as described in the Manual, here:

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

When you start an exchange instance – it will load all markets from the exchange. It will take all exchange-specific market ids, like CLBTC, for example. (as described in the Manual) and will unify them to exchange-agnostic symbols, like CL/BTC.

<img width="1302" alt="screen shot 2018-08-13 at 17 40 14" src="https://user-images.githubusercontent.com/1294454/44038674-f80e0618-9f1f-11e8-9116-618b1a85779a.png">

As you can see from the above table, hitbtc market ids don't have a slash in them (`ETHBTC`, `DASHBTC`). On the other hand, unified symbols do have a slash (`ETH/BTC`, `DASH/BTC`). The mapping of non-unified ids to unified symbols is covered in the Manual.

> Had anyone had a similar problem? What would be the best way to correct this? I'm new to your library, and I don't want to write ugly hacks if there is a nice way you would recommend.

When CCXT loads the markets from HitBTC, the exchange does not send the CLBTC market id anymore, because it is delisted. So, CCXT cannot take nothing and convert it to CL/BTC (there's no place where the library could find about this particular delisted market, except from HitBTC themselves). So, when the market gets delisted – it loses it's unified symbol automatically, you can't query it **by a unified symbol** from an exchange, if the exchange has delisted that symbol. This is because the library doesn't know the market id that corresponds to that symbol.

However, you can still query those trades by the exchange-specific market ids, for CLBTC, in particular. And this is, again, documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#unified-api
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Thus, you can fetch your CL/BTC trades like so:

```Python
# This is the way I download the trades history. Nothings fancy, not much to talk about.
hitbtc = ccxt.hitbtc2(hitbtc_keys)
symbol = None
since = None
limit = None
params = {  # exchange-specific non-unified parameter names!
    'symbol': 'CLBTC',  # exchange-specific non-unified delisted market id 
}
my_trades = hitbtc.fetch_my_trades(symbol, since, limit, params)
```

I'd really recommend to read the entire Manual from the very beginning to the very end, it will save you a ton of time. Let us know if the above does not answer your question.

**Comment by pjboro** [comment]
I read the manual, but not carefully enough, as I see now. Sorry about that and thank for your very informative response. 

I've tried running the code you provided, but there is something I'm missing. The output looks as follows:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 388, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.hitbtc.com/api/2/history/trades?symbol=CLBTC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/hitbtc2.py", line 1013, in fetch_my_trades
    response = self.privateGetHistoryTrades(self.extend(request, params))
  File "/usr/local/lib/python3.7/site-packages/ccxt/hitbtc.py", line 913, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 327, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 400, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "/usr/local/lib/python3.7/site-packages/ccxt/hitbtc2.py", line 1125, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: hitbtc2 {"error":{"code":2001,"message":"Symbol not found","description":"Try get /api/2/public/symbol, to get list of all available symbols."}}
```
On the webpage they refer to (https://api.hitbtc.com/api/2/public/symbol) I found no mention about CLBTC. Any thoughts?

I appreciate your time. Thanks.

**Comment by kroitor** [comment]
> On the webpage they refer to (https://api.hitbtc.com/api/2/public/symbol) I found no mention about CLBTC. Any thoughts?

Looks like the exchange engine itself will forbid you from fetching the trades for a market id that has been delisted. In that case you can try fetching them all at once with fetchTrades [pagination](https://github.com/ccxt/ccxt/wiki/Manual#pagination), and see if it will report those delisted trades there (there's a 50/50 chance that they will either list them in history, or will omit them within their engine). Hope this helps.

**Comment by pjboro** [comment]
I'll try to do that, and if that wont work, I will contact the exchange itself asking for help with this problem. I'm going to post here when I learn something new. Thanks!

**Comment by kroitor** [comment]
@pjboro we will be happy if you report back whether you managed to solve it or not! Thx to you as well!

**Comment by pjboro** [comment]
Well, it's been a long time.
I tried to do it in several ways, also using other hitbtc modules available on github and pure exchange market API itself, all that to no avail. It is the problem with hitbtc.com API, not with CCXT library. It's great news for CCXT users and not so well for hitbtc users in general ;)
https://github.com/hitbtc-com/hitbtc-api/issues/210
