### ISSUE TITLE
Unified argument checks for createOrder

### ISSUE THREAD

**Issue by ahmohamed** [ccxt/ccxt#3641]
Arguably, createOrder is one of the most important functions where a careful check of passed arguments is critical. Currently, this is done separately for each exchange. I would propose a unified `checkCreateOrderArgs` function, that can be called in `createOrder` to make sure the arguments are correct, and throw `InvalidOrder` if not. 

Of course, sophisticated exchanges can override `checkCreateOrderArgs` (as in Binance).

**Comment by ahmohamed** [comment]
The following checks are true for most exchanges:

```
symbol in this.markets // This is currently checked, however ExchangeError is thrown instead of InvalidOrder
type in ['market', 'limit']  
//other order types can be added through a dedicated property, or by overrriding
side in ['buy', 'sell']

price !== undefined // unless type === 'market'
price >= market['limits']['price']['min'] // where limits are defined
price < market['limits']['price']['max']

amount !== undefined
amount >= market['limits']['amount']['min']
amount < market['limits']['amount]['max']

precise_price = this.priceToPrecision(symbol, price)
precise_amount = this.amountToPrecision(symbol, price)
return (precise_price, precise_amount)
```

There is already redundant code for most of these checks in a lot of exchanges. Others, just omit these checks altogether. If these checks can be grouped in one function, it can be added to as a first line in `createOrder` where applicable.

**Comment by kroitor** [comment]
@ahmohamed 

> type in ['market', 'limit']

These cases conflict with the above:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L701
- https://github.com/ccxt/ccxt/blob/master/js/hitbtc2.js#L846

↑ We don't really force the type anywhere, we only check for it, but it can be overrided with extra params. 

> price !== undefined // unless type === 'market'
> price >= market['limits']['price']['min'] // where limits are defined

There's approximately 10 exchanges that want order cost instead of order amount for market buys which is also a conflict with the above rules:

- https://github.com/ccxt/ccxt/blob/master/js/fcoin.js#L328
- https://github.com/ccxt/ccxt/blob/master/js/cex.js#L327
- https://github.com/ccxt/ccxt/blob/master/js/huobipro.js#L662
- ...

> precise_price = this.priceToPrecision(symbol, price)
> precise_amount = this.amountToPrecision(symbol, price)

With Kucoin, for example, these methods take currency precision, instead of market precision:

- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L811
- there's also a few other examples similar to the above

If you combine all of the above tony details, the `checkCreateOrderArgs` will become the longest of all methods. Alternatively, we could make overrides, but we already do those overrides in createOrder, so adding one more overrideable method won't make a significant difference to me. Does the above make sense? Or do you still think it's worth trying to unify that aspect?

**Comment by ahmohamed** [comment]
I will have a thorough look and get back to you. 

Just a quick thought: I am not suggesting to replace all the currently implemented checks. Instead, the `checkCreateOrderArgs` can be added first to exchanges with no checks implemented. Even if we exclude all the exceptions above for the time being, there will still be a good number of exchanges where we can apply the generic checks.

**Comment by kroitor** [comment]
As for me, I simply suggest to implement missing but needed functionality first, like that listed here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#pending-tasks , because from my own experience users care less of the internal design of this or that base method, yet they do care more about having or not having this or that method, and they would be happy to have it even despite a non-ideal implementation. 

But anyways, we welcome all contributions, whatever the purpose, we merge enhancements to the base code regularly, as well as other things. Thx for your involvement!

**Comment by ttodua** [comment]
this is partially being implemented (per exchange checks) and partially impossible with current design (because user can ignore args at all and pass values in `params`)
