### ISSUE TITLE
precision mechanism

### ISSUE THREAD

**Issue by orikalinski** [ccxt/ccxt#3653]
Hi, 

Right now the precision mechanism works with num of digits after the floating point.
There are cases that is not enough.
For example in ccxt BitMEX precision is 0.1 (1 digit after the floating point) for XBTUSD which means 6400.87 turns into 6400.9 although BitMEX tickSize in this case is 0.5 which means 6400.87 should turn into 6401.0 if we use round or 6400.5 if we use floor

**Comment by kroitor** [comment]
> There are cases that is not enough.
> For example in ccxt BitMEX precision is 0.1 (1 digit after the floating point) for XBTUSD which means 6400.87 turns into 6400.9 although BitMEX tickSize in this case is 0.5

Yep, you're absolutely right. You see, BitMEX is a very specific case, I'd say a unique case, because no other exchange has lots   or precision/limits different from a power of ten. BitMEX has minimal lots of 0.5, 0.2 and so on. So this is still a yet unsolved issue. Check out my answer here as well: https://github.com/ccxt/ccxt/issues/3652#issuecomment-413106673. 

So, as a very rough temporary solution we're using the "1 decimal digit", though this will erroneously allow values like 0.2 or 0.3 to be sent out, not-force-rounded to 0.5. In other words, currently, precision is correct, one decimal digit, but the rounding is done incorrectly, so you have to round it in userland to +/- 0.5 first to workaround this. Yes, we do know that this is a very ugly solution, but it will work at the very least. In the meantime we are working on a better one )

We'll do our best to fix it soon with a much better `decimal_to_precision` implementation. Hope this answers your question. Your contributions are welcome, btw )

**Comment by orikalinski** [comment]
Thanks for the answer!

**Comment by iquirino** [comment]
Hi guys!

I am here because i'm searching on google for "How to floor numbers by precision digits count".

My solution is:

```
var precisionCount = 4; //market.precision.amount or market.precision.price
var valueToUse = 0.000168374;

var newValue =Math.floor(valueToUse  * Math.pow(10, precisionCount )) / Math.pow(10, precisionCount )
```

I think this information can help someone, so we can add this on the wiki?
Ccxt already has a function to do this?

Thank you!

**Comment by kroitor** [comment]
@iquirino hi! 

> I think this information can help someone, so we can add this on the wiki?
> Ccxt already has a function to do this?

Yep, this has been generalized and described here:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- JS: https://github.com/ccxt/ccxt/blob/master/js/test/base/functions/test.number.js
- Python: https://github.com/ccxt/ccxt/blob/master/python/test/test_decimal_to_precision.py
- PHP: https://github.com/ccxt/ccxt/blob/master/php/test/decimal_to_precision.php
- https://github.com/ccxt/ccxt/pull/3663
- https://github.com/ccxt/ccxt/pull/2408
- https://github.com/ccxt/ccxt/issues/522

We will add more info to the Wiki on how to work with those methods as soon we can. Your contributions are welcome! ;)

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by iquirino** [comment]
Hi!

Thank you by your answer!

The article did not explain how to do this precision using "decimalToPrecision" or "decimal_to_precision".
https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Thank you!
