### ISSUE TITLE
take orders

### ISSUE THREAD

**Issue by borgr** [ccxt/ccxt#3659]
- OS:Linox and windows
- Programming Language version: python
- CCXT version: latest (cloned now)
- Exchange:btcbox
- Method:create_order

I was wondering about take orders in btcbox.
1. what happens when I pass this function None (it failed for me, but should it be a take order? what url does it send)
2. if not is there another way of using take orders instead of make?
3. can I expect a take order to exist in every exchange? it seems some exchanges don't haave it in their API.

**Comment by kroitor** [comment]
@borgr please read here on which orders can be placed with exchanges and how to place them:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

The meanings of "maker" and "taker" as well as the difference between them is explained here:
- https://support.binance.com/hc/en-us/articles/360007720071-What-Do-Maker-and-Taker-Mean-
- https://blog.kraken.com/post/242/kraken-fee-change-important-updates/
- https://bitbay.net/en/helpdesk/exchange/what-is-maker-and-taker-fee
- https://support.bitfinex.com/hc/en-us/articles/213919589-What-fees-do-you-charge-
- https://www.luno.com/help/en/articles/1000168409-how-does-a-limit-order-work-and-what-are-maker-and-taker-orders
- https://money.stackexchange.com/questions/63044/maker-taker-fees-can-somebody-explain-in-plain-english
- https://globitex.com/knowledge-base/trading/2-what-is-the-difference-between-a-market-maker-and-a-market-taker/
- http://webcache.googleusercontent.com/search?q=cache:l5kNNs7QfEIJ:cryptocurrencyfacts.com/maker-vs-taker-cryptocurrency/&num=1&hl=en&gl=ru&strip=1&vwsrc=0
- https://desk.zoho.com/portal/coindelta/kb/articles/how-is-a-maker-and-a-taker-decided

I'd really recommend to read the entire Manual from the very beginning to the very end it will save you a ton of time. The above questions seem to be caused by a lack of theoretical knowledge of how markets work and of the difference between a maker and a taker. CCXT will allow you to place both maker and taker orders, however, you have to understand what they are first, to work with it efficiently.

Hope this answers your questions.
