### ISSUE TITLE
Propose to replace for with map

### ISSUE THREAD

**Issue by Piterden** [ccxt/ccxt#3665]
```js
    const libraries = []

    for (let library in pythonStandardLibraries) {
      const regex = new RegExp ("[^\\']" + library + "[^\\'a-zA-Z]")
      if (bodyAsString.match (regex))
        libraries.push ('import ' + pythonStandardLibraries[library])
    }
```
The same will be
```js
    const libraries = pythonStandardLibraries.map((library) => bodyAsString
      .test(new RegExp (`"[^\\']${library}[^\\'a-zA-Z]`)) ? `import ${library}` : false
    }).filter(Boolean)
```
Maybe replace it everywher?

**Comment by Piterden** [comment]
Hm...

![image](https://user-images.githubusercontent.com/5930429/44232258-1fceed80-a1a9-11e8-884c-8bba0150521d.png)

**Comment by kroitor** [comment]
> Maybe replace it everywher?

Well, we could, of course, however, I don't see a practical reason to do so ) I mean, for me that particular edit wouldn't really make a significant difference, or, in other words, it works for me either way. So, I'd rather focus on yet unsolved problems ) I don't have any technical objections and I do agree that it would make the code shorter and a tiny bit cleaner for a price of making the transpiler run a bit slower due to the added functions calls. However, at this point I don't find the above case critical enough, therefore I usually don't spend too much time thinking on that aspect. 

So, if you want to give it a try, why not, we welcome your contributions, let's just make sure we don't break anything. The best approach is to submit small edits or *atomic PRs*, not *all-in-one* nor *replaced-everywhere*, but more like one PR *here*, another PR *there*, and so on. That way we'd merge them quicker.

Thanks anyways! Appreciate your involvement! Hope you don't mind me closing this for now. We'll be happy for any proposals and commits. Cheers!
