### ISSUE TITLE
How to properly get/calculate current price for trading bot to buy or sell at.

### ISSUE THREAD

**Issue by proeng** [ccxt/ccxt#3671]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.17.73
- Exchange: BitMex
- Method: fetch_ticker

I am not sure if this is proper place to ask, but it is related to a closed issue, that i did not feel answered the question to my problem.
https://github.com/ccxt/ccxt/issues/3337
I am building a trading bot and i have a problem with bitmex returning None on bid+ask, as you answered above, but i am confused how to solve the issue.
Problem is if i use fetch_markets, or order_books, i will run out of my allowed data to fetch per minute real quickly, i need to be able to fetch specific data about 1 coin at a time. I am limiting myself to fetching 5 coin tickers per exchange at a single  #time.

Is there a way to calculate bid and ask from OHLCV, or how should i approach this?
I want the price that is displayed on the actual exchange, when you trade there, or the price that is displayed in tradeview on that exchange. Is there something i misunderstand, is there a better way to get this data without getting to much data per second so i get banned?

This is my current implementation, but it is temporary cause i want the current price that is displayed on the exchange. I realize it just show the lowest price you can buy, but as volume runs out you buy the next one etc. 

`val = self.model.price_info[exchange][symbol]['bid']`
`    if val is None:`
`      val = self.model.price_info[exchange][symbol]['close']
`

**Comment by Mandelbr0t** [comment]
1. You cant calculate the current price out of OHLCV data, because the current price reflects the market at a specific moment and OHLCV is applied to a range in time.
2. However, you can catch the orderbook and use limit orders at the bid/ask prices, but you have to look at the volume that is available at the current bid/ask price. 
3. If you run out of allowed requests for that exchange, you could implement a webscraper yourself that reads the webpage you normally view if you visit the exchange.

**Comment by kroitor** [comment]
Thx, @Mandelbr0t!

@proeng hope it answers your questions, let us know if not. I'd also recommend to read the entire Manual from the very beginning to the very end, this can save you a ton of time, really: https://github.com/ccxt/ccxt/wiki. Closing this for now if you don't mind. Feel free to reopen it if needed.
