### ISSUE TITLE
In Python, truncate_to_string() rounds up, truncate() does not

### ISSUE THREAD

**Issue by miracle2k** [ccxt/ccxt#3699]
In Python the behaviour of those two methods is different:

```python
In [32]: b.truncate_to_string(1.4973, 2)
Out[32]: '1.5'

In [33]: b.truncate(1.4973, 2)
Out[33]: 1.49
```

This is regularly a problem for me with binance, which has these very large lot sizes. I want to sell my whole balance, which might be `1.4973`. But when I call `create_limit_sell_order` with that amount, binance calls `amount_to_string -> truncate_to_string`, and then actually submits an order for `1.5`, which binance sensibly rejects - I don't have that much.

I believe ccxt should instead submit an order for `1.49`, that is, round down.

I know that this subject (rounding, floating point) has come up numerous times in the past, and some work was planned to possible change certain things. I can see a lot of tickets, though not the current state.

However, I am wondering if we might not make `truncate_to_string` do this:

```
@staticmethod
def truncate_to_string(num, precision=0):
        return str(self.truncate(num, precision))
```

or, if that is necessary:

```
@staticmethod
    def truncate_to_string(num, precision=0):
        if precision > 0:
            # Instead of:
            # parts = ('{0:.%df}' % precision).format(Decimal(num)).split('.')
            # do this:
            parts = str(self.truncate(num, precision)).split('.')

            decimal_digits = parts[1][:precision].rstrip('0')
            decimal_digits = decimal_digits if len(decimal_digits) else '0'
            return parts[0] + '.' + decimal_digits
        return ('%d' % num)
```

To ensure that they both return the same result - a round down, which I think makes the most sense for order submission.

The JS version behaves this way:

```js
api = new (require('./js/base/Exchange.js'))
> api.truncate_to_string(1.4973, 2)
'1.49'
> api.truncate(1.4973, 2)
1.49
>
```

As does PHP:

```php
php > echo $x->truncate(1.4973, 2);
1.49
php > echo $x->truncate_to_string(1.4973, 2);
1.49
php >
```

**Comment by kroitor** [comment]
@miracle2k both `truncate` and `truncate_to_string` are deprecated due to the bugs you described (those are known), we are aware of them and we now migrate to `decimal_to_precision` everywhere. 

BTW, `amount_to_lots` was deprecated for the same reason and has been removed a couple of weeks ago. 

See this PR: https://github.com/ccxt/ccxt/pull/3663 by @frosty00 

Basically, you shouldn't rely on those undocumented methods – if you encounter such a method then it isn't in the docs most likely because it still has bugs and is not fit for the docs / for public usage yet.

Let us know if that does not answer your question. Thx!

**Comment by miracle2k** [comment]
Thanks. So I'll just be waiting for #3663 to be merged - then my particular problem with binance would be fixed as well, it seems.
