### ISSUE TITLE
Poloniex min amount

### ISSUE THREAD

**Issue by JeanChai** [ccxt/ccxt#3706]
- OS:Win10
- Programming Language version: python 3.6
- CCXT version: 1.17.164
- Exchange: Poloniex ETH/USDT
- Method: create_order

Amount is equal to minimun limit of ETH/USDT : 0.00000001
Price is 296.71716899303
Total = amount * price = 2.96e-06
But I get the following error: {"error":"Amount must be at least 0.000001."}. Obviously my total is larger than 1e-6.

I asked this question in #3688 , using 1.16.89. I updated to the most recent version and this problem still exists.

**Comment by kroitor** [comment]
Hi!

This is the issue with Polo limits, as described here:

- https://github.com/ccxt/ccxt/issues/2706#issuecomment-390529874

Duplicate:

This is the issue with Polo limits, as described here:

- https://github.com/ccxt/ccxt/issues/2706#issuecomment-390529874

Duplicates:

- https://github.com/ccxt/ccxt/issues/3786
- https://github.com/ccxt/ccxt/issues/3688
- https://github.com/ccxt/ccxt/pull/3029

We're going to have to add a map of their limits as a workaround until their API starts to serve complete data from their side... Hope, to add the fix for it soon.
