### ISSUE TITLE
Bitfinex DDOS protection using client.rateLimit

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#3738]
- OS: Linux
- Programming Language version: Python
- CCXT version: last
- Exchange: Bitfinex
- Method: rateLimit

I always pause my algorithm for client.rateLimit before fetch orderbooks.
Using that with bitfnex is not working, since I get Error by DDOS Protection.

**Comment by kroitor** [comment]
> Using that with bitfnex is not working, since I get Error by DDOS Protection.

Bitfinex has varying rate limits that depend on the endpoints in question. Which particular methods do you use? Any code to reproduce the issue?

Also, have you read this?

- https://github.com/ccxt/ccxt/issues/3175
- https://github.com/ccxt/ccxt/issues/3175#issuecomment-398205651

**Comment by fedecaccia** [comment]
The method I'm using is fetchOrderBook("XXX/YYY"). Thanks!

**Comment by kroitor** [comment]
@fedecaccia have you seen their docs on that?

![bitfinex-orderbook-ratelimit](https://user-images.githubusercontent.com/1294454/44622946-82239e80-a8cb-11e8-9541-dfe316531396.jpg)

Can you post a short but a complete snippet of code to reproduce the issue?

**Comment by fedecaccia** [comment]
I'm also having this error (with the same code):

ccxt.base.errors.RequestTimeout: bitfinex GET https://api.bitfinex.com/v1/book/BATBTC HTTPSConnectionPool(host='api.bitfinex.com', port=443): Read timed out. (read timeout=10)

**Comment by kroitor** [comment]
> yes I have seen that recently.

You have seen that recently... and...? ) Ok, let's clarify this ) When I ask "have you read that?" I actually mean "you should go and read that link carefully and try what's written there", so what I really expect from you is "yes, I have tried that and here are my results: ...". 

Once again, actual Bitfinex rate limits don't correspond to their documented rate limits. Most often their actual rate limits are significantly lower than documented, for example, an actual limit of 20 requests per second of orderbooks instead of the documented 60 requests per second.

That is described in the post linked above, which has code for experimentation that was meant to be tried by you ) This entire issue: https://github.com/ccxt/ccxt/issues/3175

But, apparently, you haven't tried that. So, I've uploaded an example that should clarify it for you:
https://github.com/ccxt/ccxt/blob/master/examples/py/bitfinex-rate-limiting.py

Let us know if that does not help )

**Comment by fedecaccia** [comment]
Sorry, I haven't explained myself. Yes, I searched that documentation and I tested the rate limits they published for two or three different methods. I haven't put all in the example code above to the sake of simplicity (I just used the rateLimit property of the client). The thing is that, after a while, I always get a DDOS Protection error. I'm going to try with a rateLimit = 3000 ms. Thanks!
