### ISSUE TITLE
bitflyer markets are missing baseId and quoteId fields

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3746]
For example:

```
"BCH/BTC": {
    "precision": {
      "price": 8,
      "amount": 8,
      "cost": 8
    },
    "taker": 0.0025,
    "maker": 0.0025,
    "id": "BCH_BTC",
    "symbol": "BCH/BTC",
    "base": "BCH",
    "quote": "BTC",
    "type": "spot",
    "spot": true,
    "future": false,
    "info": {
      "product_code": "BCH_BTC"
    }
  }
```

[EDIT] ... I now see that they are missing missing from most implementations.  Is that expected?

**Comment by kroitor** [comment]
>  I now see that they are missing missing from most implementations. Is that expected?

Mostly, yes, because we've started adding baseId and quoteId not very long ago. You should not rely on the fields that aren't documented in the Manual, really. We hope to add them throughout the entire library, everywhere, if possible. Added them to bitflyer as well. Let us know if that does not answer the question.

**Comment by npomfret** [comment]
Thank you
