### ISSUE TITLE
 How to get all orders for huobipro one day?

### ISSUE THREAD

**Issue by Labradors** [ccxt/ccxt#3750]
```python
orders = huobi.fetch_orders(since=current_time-86400)
```
but the order num only 100.

**Comment by kroitor** [comment]
All timestamps are in **milliseconds**! Please read the Manual from the very beginning to the very end carefully, all of that is written there: 

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#working-with-datetimes-and-timestamps
- https://github.com/ccxt/ccxt/wiki/Manual#date-based-pagination

```Python

from pprint import pprint

symbol = None
since = huobi.milliseconds() - 86400 * 1000  # in milliseconds!
limit = None
params = {}

huobi.enableRateLimit = True

all_orders = []

orders = huobi.fetch_orders(symbol, since, limit, params):
while orders 
    all_orders += orders
    last_order = orders[-1]
    since = last_order['timestamp'] + 1  # fetch from last order on next cycle
    orders = huobi.fetch_orders(symbol, since, limit, params):

pprint(all_orders)
print('Fetched all', len(all_orders), 'orders')
```

↑ this is pseudocode, it might require some editing + it does not include error handling (which you will need), but we won't do the homework for you ;) It should answer your question and give you the idea. The concept of pagination is, again, already documented in the Manual which you should really read in order to be able to use this library efficiently ;)

**Comment by Labradors** [comment]
thank
