### ISSUE TITLE
Implement Ethfinex dEx API

### ISSUE THREAD

**Issue by hems** [ccxt/ccxt#3761]
Hello Guys,
I noticed EthFinex is listed among the supported exchanges but unfortunately CCXT isn't 100% compatible with the current implementation.

Some of the functionalities such as fetching OHLCV indeed should come from Bitfinex, but some of the functionality / concepts are new and must still be implemented on CCXT, I would like to provide some information and help implementing such functionality into CCXT, but first i would like to explain in details what must be done so we can get clear direction on how we should solve that in the neatest way possible.

One of the main difference between EthFinex implementation and the standard Bitfinex implementation is that the authentication is done signing requests with user's private key instead of providing a KEY and SECRET string upfront.

Taking the "getOrders" method as an example ( [check the source here](https://github.com/ethfinex/efx-api-node/blob/master/src/api/get_orders.js) ) you will notice that a "nonce" is generated and then signed with user's private key.

You can see the implementation for the [signature function here](https://github.com/ethfinex/efx-api-node/blob/master/src/api/sign/sign.js), it currently supports users using MetaMask or a running a local ethereum node.

It's important to notice though that some users won't be using MetaMask or a local node and that's why the getOrders method [receives nonce and signature as optional last parameters](https://github.com/ethfinex/efx-api-node/blob/master/src/api/get_orders.js#L4), this way you would be able to generate fetch the orders with a pre-signed nonce instead of relying on the library's sign function some other functions in the library behaves the same way.

Currently the available methods are:

  - [submitOrder](https://github.com/ethfinex/efx-api-node/blob/master/src/api/submit_order.js)
    - It creates [an 0x Order](https://github.com/hems/efx-api-node/blob/master/src/api/contract/create_order.js)
    - Then [signs it and post to the HTTP API](https://github.com/hems/efx-api-node/blob/master/src/api/submit_order.js)
  - [cancelOrder](https://github.com/ethfinex/efx-api-node/blob/master/src/api/cancel_order.js)
  - [getOrders](https://github.com/ethfinex/efx-api-node/blob/master/src/api/get_orders.js)
    - Will return currently open orders 
    - Can be filtered by id or array of ids
    - Can be filtered by symbol or array of symbols
  - [getOrdersHist](https://github.com/ethfinex/efx-api-node/blob/master/src/api/get_orders_hist.js)
    - Will return historical orders
    - Can be filtered by id or array of ids
    - Can be filtered by symbol or array of symbols

The second main difference is that in order to put an Order on the Order Book you have to first "lock" your tokens, locking tokens basically means you will put those tokens aside to be used in your dEx orders.

This call won't be issued against the HTTP API but instead it will be issued against a Web3 contract, you can see the [implementation for locking tokens here](https://github.com/ethfinex/efx-api-node/blob/master/src/api/contract/lock.js) and here is the function which actually [estimates the gas needed to do the transaction and sends it to the node to be broadcasted](https://github.com/ethfinex/efx-api-node/blob/master/src/api/eth/send.js), there is also a "[releaseTokens](https://github.com/hems/efx-api-node/blob/master/src/api/release_tokens.js)" function if the user decides to unlock the funds.

The questions so far are:

 - Do you currently support Web3 calls from within the library? If not, shall we send a "web3" object on the constructor?
 - Would we also provide a custom web3 "send" function on the constructor while keeping MetaMask and "local node" integration implemented by default?
 - How to add the extra "lockTokens" and "releaseTokens" method as extra methods on the API?
 - Am i missing something ?

PS: I saw there are two contributors to the [ethfinex.js](https://github.com/ccxt/ccxt/blob/master/js/ethfinex.js) file: @kroitor and @frosty00 so i'm tagging them here to check if they would be able to help updating the library.

**Comment by kroitor** [comment]
Hi! And welcome )

> I noticed EthFinex is listed among the supported exchanges but unfortunately CCXT isn't 100% compatible with the current implementation.

You're absolutely correct, it requires a rewrite.

Thx for explaining the differences. We're aware of them, because the reservation sequence you described is common to most DEXes.

See, for example, the implementation of The Ocean, we do the signing with privateKey for it:

- https://github.com/ccxt/ccxt/blob/master/js/theocean.js
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/theocean.py
- https://github.com/ccxt/ccxt/blob/master/php/theocean.php

> Do you currently support Web3 calls from within the library? 

Yep: 

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L1222
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1421
- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L2103

However, the support for web3 is not complete yet, it lacks a lot of functionality, and not all methods are available in all our languages yet – we need to mirror them in js/python/php, and php isn't very well supported by the ETH community. 

> If not, shall we send a "web3" object on the constructor?

Only if you need to override the default one.

> Would we also provide a custom web3 "send" function on the constructor while keeping MetaMask and "local node" integration implemented by default?

We currently support the signing, but not the sending yet, this is still a thing that has to be designed and implemented properly in CCXT.

> How to add the extra "lockTokens" and "releaseTokens" method as extra methods on the API?

See the implementation of unified `createOrder` in The Ocean, and read this announcement as well: https://github.com/ccxt/ccxt/issues/3476

> Am i missing something ?

Apart from what is mentioned above, probably not )

Let me know if that answers your questions or not)

**Comment by hems** [comment]
@kroitor thanks for such fast reply.

I'm having a look at the "createOrder' function which receives `walletAddress` and `privateKey`, I think some users would be okay with providing their private key but other users would likely prefer to simply sign the payloads themselves ( for instance provided pre-signed payloads or a custom sign function), is that something you guys considered?

Regarding the Ethfinex implementation, if I would go ahead and start implementing a PR I would like to ask a couple more things:

 - Do you have a link to some code showing how the call to the Smart Contract fro within an "exchange" file?

 - Where should I add a basic "map" of tokens and "decimals", like the one we [have here](https://github.com/hems/efx-api-node/blob/master/src/currencies.js) ? 

 - How would we go about some of the calls being done to the Bitfinex HTTP API ( for instance OHLCV ) and some being done to the ETHFINEX HTTP API, can we specify two URLs on the exchange config?

 - Would you be able to provide a starting point based on the description / issues we have highlighted here and the experience you already have with CCXT so I could help with the code and testing out the new implementation?

**Comment by kroitor** [comment]
> sign the payloads themselves ( for instance provided pre-signed payloads or a custom sign function), is that something you guys considered?

Yes, we have considered this. However, we haven't unified it yet, because most often the library will be used within an algotrading environment, where you would still keep the keys on the trading system. Of course, you may want to do deferred or delegated signing, if you don't possess the private key – in that case a remote side would sign the request for you and you'd then send it towards the DEX or DEX contract. We will add the support for deferred `async sign()` hopefully soon.

> Do you have a link to some code showing how the call to the Smart Contract fro within an "exchange" file?

We currently don't have it in CCXT yet (under heavy development right now), but we're going to support for both JSONRPC and external `sign()` providers (be it a local full node, a lite node, MetaMask or a remote infura node, whatever it is).

> Where should I add a basic "map" of tokens and "decimals", like the one we have here ?

Most of them (`decimals`), we believe, should not be hardcoded. Basically, if the token in question is standardized (an ERC20 or ERC721 token), then we'll read the `decimals` from it. However, with some exchanges, the token contract `decimals` may be different from min limits allowed by the exchange, thus we will need an endpoint from Ethfinex to serve its limits and pairings. Otherwise we will have to reinvent the wheel and will add a workaround that will fetch that metadata either from ethfinex website or directly from the above github doc you linked.

> How would we go about some of the calls being done to the Bitfinex HTTP API ( for instance OHLCV ) and some being done to the ETHFINEX HTTP API, can we specify two URLs on the exchange config?

Sure! We often have multiple base URLs for various endpoints, see this, for example:

- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L42
- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L714

The implementation in `sign()` or `request()`, however, will depend on the data in question.

> Would you be able to provide a starting point based on the description / issues we have highlighted here and the experience you already have with CCXT so I could help with the code and testing out the new implementation?

Yep, this is something we're going to do soon – we'll start adding those missing base methods for deferred signing, and will start adding more support for web3 with contract calls, including `read` and  `write` (send) operations with contracts and more. We don't have an ETA yet, there's quite a lot of work going on around this library, on various aspects of it, but I hope to get it all sorted and resolved in the coming weeks.

Let me know if you have more )

**Comment by kroitor** [comment]
> Indeed we will be providing an HTTP endpoint to fetch the list of contracts/tokens and it's likely we will also have the decimals cached in that response as well.

Great! )

> is there an exchange implementation we could look at to see how this works on ccxt?

Yep, see here:

- https://github.com/ccxt/ccxt/blob/master/js/bitmex.js#L36
- https://github.com/ccxt/ccxt/blob/master/js/gdax.js#L39
- https://github.com/ccxt/ccxt/blob/master/js/test/test.js#L213

Basically, we can define as many base URLs as we want and we can combine them how we want, so I don't expect any problems wrapping Ethfinex as well )

**Comment by hems** [comment]
how does it knows if it should use a "test net" url or a "production" url? is there some sort of "NODE_ENV" variable that is "standard" on ccxt or shall we just pass an "network-id" as parameter on the constructor ?

I have copy and pasted and modified a bit a very very dirty "createOrder" and "submitOrder" method on my fork: https://github.com/hems/ccxt/commit/de8a99bbe375f371df86356cd92cbb34a56bb8a0 i'm sure this is far from "good enough", but it's something we can look at and keep improving and soon enough we will have it working.

One thing I had to do is to add the 0x.js library as a dependency, but I guess this was expected, right?

**Comment by hems** [comment]
@kroitor i can see on test/test.js that if "urls['test']" is defined it replaces the 'api' value, but how do we defined if we will be running CCXT in 'test' mode? Is there a flag/option somewhere?

I'm guessing we would have urls specified in this way....?

````javascript

urls: {
  'test': {
    'test.bitfinex...'
    'test.ethfinex...'
  },

  api: {
    'bitfinex...',
    'ethfinex...'
  }

}
````
?

**Comment by kroitor** [comment]
> how does it knows if it should use a "test net" url or a "production" url? 
> but how do we defined if we will be running CCXT in 'test' mode?

There's two possible scenarios:
- The user wants to switch to the testnet url – that is done via constructor params or afterwards with exchange properties, documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties. In this case the user sets the properties when and how he wants, in runtime, in userland logic.
- The exchange implementation has to decide which URL to send the request to – that is usually implemented in the `sign()` logic for the exchange and may depend on request params, on exchange specifics, etc, etc... In this case it is implemented in compile-time in the corresponding exchange file.

> is there some sort of "NODE_ENV" variable that is "standard" on ccxt or shall we just pass an "network-id" as parameter on the constructor ?

Constructor params and exchange properties (can be changed in runtime) – are the two standards on ccxt ) Regardless of NODE_ENV, or PY_ENV (surprise), or PHP_ENV... ;) In other words, working with env variables is beyond the scope of the library, it is the app-level configuration issue that should be dealt with in userland and should not be reduplicated/reinvented or propagated from one library to another, we believe.

> One thing I had to do is to add the 0x.js library as a dependency, but I guess this was expected, right?

Actually, wrong ) Unless you have 0x.py and 0x.php in your sleeve ;) Please, follow here for a detailed explanation: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

Portability requirements are the key reason for not having 0x.js linked, we do very scrupulous cherry-picking of what and how should be imported and reused as base class methods, for example:

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L1274
- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L1257
- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L1237

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1498
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1467
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1433

- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L2169
- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L2118

**Comment by kroitor** [comment]
> I'm guessing we would have urls specified in this way....?
> 
> ````javascript
> 
> urls: {
>   'test': {
>     'test.bitfinex...'
>     'test.ethfinex...'
>   },
> 
>   api: {
>     'bitfinex...',
>     'ethfinex...'
>   }
> 
> }
> ````
> ?

We always have URLs specified as documented in the Manual, namely, the `exchange.urls['api']` property will be in one of the following formats:

- Easy: `urls: { api: "http://foo.bar" }`

- Complex: 

    ```
    'urls': {
        'api': {
            'bitfinex': 'https://bitfinex...',
            'ethfinex': 'https://ethfinex...',
            'bitfinextest': 'https://test.bitfinex...',
            'ethfinextest': 'https://test.ethfinex...',
            'label': 'https://base.url/foo/bar',
            ....
        },
        ...
    }
    ```

**Comment by hems** [comment]
@kroitor so the strategy would be to "copy" part of the source of the 0x.js library and if needed port that part of the code to Python and PHP ?

Can an exchange implementation make to ccxt's master in case there is only one implementation working, for instance the node.js one?

**Comment by kroitor** [comment]
> so the strategy would be to "copy" part of the source of the 0x.js library and if needed port that part of the code to Python and PHP ?

Well, yes, however, "copying" just "a part of" 0x.js sounds easier said than done ;) As for porting – that may be even harder that stripping some code from js only. Also, most likely, we will have to get an `async sign()` declaration in ccxt base code as well. But we will do that sooner or later anyways (hopefully. sooner).

> Can an exchange implementation make to ccxt's master in case there is only one implementation working, for instance the node.js one?

In most cases we prefer to have portability throughout the lib, but in rare cases and with some experimental code we can merge parts of it. We would rather ask you to open a PR with JS edits and other contributors and devs from the community could then help port it to other languages quickly. If you do your edits with portability in mind, that would be easier for us to port and merge, rather than js-specific code and syntax.

**Comment by hems** [comment]
@kroitor thanks for the info.

i'll start a PR soon and we can take it from there. Regarding importing 0x.js i believe the trade-off might be worthy as probably more and more exchanges will rely on 0x in the future.

In case you guys decide against adding 0x.js to package.json ( seems like the ideal situation from ccxt point of view ) we would need to port a few things which doesn't seem to be so straight forward:

  - ZeroEx.generatePseudoRandomSalt
    - [Seems easy to port](https://github.com/0xProject/0x-monorepo/blob/development/packages/order-utils/src/salt.ts)

  - ZeroEx.getOrderHashHex
    - [Not so easy to port](https://github.com/0xProject/0x-monorepo/blob/development/packages/order-utils/src/order_hash.ts#L50-L75) becaues it relies on [eip712utils](https://github.com/0xProject/0x-monorepo/blob/development/packages/order-utils/src/eip712_utils.ts)

 - ZeroEx.isValidSignature
    - [Not so easy to port](https://github.com/0xProject/0x-monorepo/blob/development/packages/order-utils/src/signature_utils.ts#L25-L83)

 - zeroEx.signOrderHashAsync
    - [Not so easy to port](https://github.com/0xProject/0x-monorepo/blob/development/packages/order-utils/src/signature_utils.ts#L202-L263)...


Considering 0x repo has good tests and good code coverage it seems to me that it would be very risky to port that code and write tests and then always be "catching up" in case they update it.

Fingers crossed you guys can weight in favor of 0x.js as a dependency otherwise i  believe it would take a lot of time to "import" and test all the function from ZeroEx library.

**Comment by kroitor** [comment]
> ZeroEx.generatePseudoRandomSalt

Not ported yet, but should be pretty easy to port.

> ZeroEx.getOrderHashHex

Ported already, in CCXT codebase.

> ZeroEx.isValidSignature

Also ported already, in CCXT codebase.

> zeroEx.signOrderHashAsync

We have a sync version of it that uses privateKey, but will add the async version as well, so, yes, almost ported already, as well.

;)

**Comment by hems** [comment]
@kroitor that's amazing to hear! you guys are really ahead on this game!

Will prepare a PR without 0x.js as dependency and we can start using those

**Comment by hems** [comment]
We are deploying `/r/get/conf` pretty soon, here is the current output, it will be slightly adjusted but should give a good idea of what's going to happen:

````javascript
{
  "0x": {
    "minOrderTime": 300,
    "tokenRegistry": {
      "ETH": {
        "decimals": 18,
        "wrapperAddress": "0x965808e7f815cfffd4c018ef2ba4c5a65eba087e",
        "minOrderSize": 0.02
      },
      "USD": {
        "decimals": 6,
        "wrapperAddress": "0x83e42e6d1ac009285376340ef64bac1c7d106c89",
        "minOrderSize": 10
      }
    },
    "ethfinexAddress": "0x9faf5515f177f3a8a845d48c19032b33cc54c09c",
    "exchangeAddress": "0x67799a5e640bc64ca24d3e6813842754e546d7b1",
    "exchangeSymbols": [
      "tETHUSD"
    ]
  }
}
````

**Comment by hems** [comment]
We have implemented a POST request to `https://api.ethfinex.com/trustless/v1/r/get/conf` which now returns the aforementioned json.

**Comment by hems** [comment]
Any news/progress on this? Is there anything i could help with or code to accelerate this proccess?

**Comment by hems** [comment]
I'm not user what is the status on this but we have moved to ZeroEx v2 so things are a little different and perhaps a little bit simpler now...

**Comment by frosty00** [comment]
ethfinex no longer exists
