### ISSUE TITLE
Why not make parse_order_book return also the number of orders when available?

### ISSUE THREAD

**Issue by oppure** [ccxt/ccxt#3783]
Hi
coinbasepro api call [GET /products/\<product-id\>/book](https://docs.pro.coinbase.com/#get-product-order-book) returns also the number of orders for each bid/ask price, this information can be useful, wouldn't it be worth considering to modify the parse_order_book and fetch_order_book functions to return also the number of orders when it's available?

**Comment by kroitor** [comment]
Hi!

Please, read this: https://github.com/ccxt/ccxt/issues/36

> coinbasepro api call GET /products/<product-id>/book returns also the number of orders for each bid/ask price

Other exchanges may return a timestamp as the third argument. Some others also return an order id instead of count, depending on the aggregation level. The order count, for example, is only relevant to aggregated orderbooks. Thus, having an order count as third argument (blindly) would yield a conflict with different exchanges, if not treated carefully. Therefore we have specific methods for aggregated results, read here about it: https://github.com/ccxt/ccxt/wiki/Manual#market-depth. L1/L2/L3 methods are designed to handle this. However, the aspect is not unified yet, this is still a work in progress.

Hope this answers your question.
