### ISSUE TITLE
How do the values in the `has` meta property get set?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3827]
Does the `has` array for the supported features of the unified API get filled in _magically_ in some way?  Or is it just typed in?  I ask because I noticed in `bitbay.js` there is almost nothing there:

            'has': {
                'CORS': true,
                'withdraw': true,
            }
... but reading down the code a little I can see `async fetchTicker`, `async fetchOrderBook` etc, which are a part of the unified API.

Conversely in `bitfinex2.js` I see:

            'has': {
                'CORS': true,
                'createLimitOrder': false,
                'createMarketOrder': false,
                'createOrder': false,
                'deposit': false,
                'editOrder': false,
                'fetchDepositAddress': false,
                'fetchClosedOrders': false,
                'fetchFundingFees': false,
                'fetchMyTrades': false,
                'fetchOHLCV': true,
                'fetchOpenOrders': false,
                'fetchOrder': true,
                'fetchTickers': true,
                'fetchTradingFees': false,
                'withdraw': true,
            },

**Comment by firepol** [comment]
No it's not filled magically. I think you just found a bug. I guess if you have time you could submit a PR for this. You just have to copy/paste the snipped you used above, from bitfinex, and set to true/false each feature. Easy one.

**Comment by kroitor** [comment]
@npomfret the `has` property is *deep-extended* by the default `has` values from the base class:

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L84
- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L794
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L160

So: `{ 'a': true, 'b': false }` + `{ 'b': true, 'c': false }` = `{ 'a': true, 'b': true, 'c': false }`.

Next, if you think more on **what is an exchange**, you'll notice that to be an exchange in full-sense, their system has to have the very minimum of common data endpoints – tickers, orderbooks, trades, markets. So, most of related `has` properties are true by default for public market data. The exchange also has to have `cancelOrder` and `createOrder`, otherwise it's useless, therefore those two methods are also always true. On the other hand, the rest of their private APIs can differ a lot, this is where the values of `has` properties differ from exchange to exchange. So, we don't have to set all of them in each file, we just add the overrides.

There still be some values missing here and there, and some of them may be inconsistent, and we'd be thankful, as always, if you report the conflicts or inconsistencies you may find with those properties. Let me know if that does not answer the question. Thank you!
