### ISSUE TITLE
'import ccxt' takes over 2 seconds with python 3.6

### ISSUE THREAD

**Issue by ngugc** [ccxt/ccxt#3845]
- OS: Ubuntu 16.04.4
- Programming Language version: Python 3.6
- CCXT version: 1.17.283
- Exchange:
- Method:

time python3.6 -c 'import ccxt'

real	0m2.716s
user	0m1.340s
sys	0m0.076s

time python2.7 -c 'import ccxt'

real	0m0.243s
user	0m0.112s
sys	0m0.020s

**Comment by kroitor** [comment]
The version for Python3 has to import web3 imports and eth*.py imports in order to provide 0x functionality, whereas in Python2 that functionality is not available. Therefore the number of deps it has to load for py3 is far greater than that of v2. We will soon drop the support for python2, as shown here: 

- https://pythonclock.org
- http://python3statement.org

Hope this answers your post. Let us know if not.

**Comment by ngugc** [comment]
@kroitor , is there any way to improve the import time? 2.7 secs are toooo long.

**Comment by kroitor** [comment]
@ngugc you can try a custom build: https://github.com/ccxt/ccxt/blob/master/exchanges.cfg
