### ISSUE TITLE
Why trades/orders are sorted by timestamp ascending?

### ISSUE THREAD

**Issue by ngugc** [ccxt/ccxt#3859]
- OS:
- Programming Language version: js
- CCXT version:
- Exchange:
- Method:

![image](https://user-images.githubusercontent.com/2368031/45605189-90e61700-ba6d-11e8-9f80-04e24cc407e9.png)

From my experience, most of the exchanges return trades/orders sorted by timestamp descending.  It's convenient for the apps to traverse the data from latest to older.
Why does ccxt sort trades/orders by timestamp ascending?

**Comment by kroitor** [comment]
> From my experience, most of the exchanges return trades/orders sorted by timestamp descending. It's convenient for the apps to traverse the data from latest to older.

In fact, there's no dominating majority in this, even topmost exchanges differ in the ordering, and this is covered in the Manual. 

- https://github.com/ccxt/ccxt/wiki/Manual#pagination

You can always redefine `parseTrades` and sort them how you want, thus it isn't really an issue at all for most users. 

In short, the ascending sorting is aligned with the date-based pagination and `since`+`limit` arguments, otherwise those would be `before`+`limit`.

Let us know if that does not answer your question.

**Comment by ngugc** [comment]
OK, thanks! Then I am worrying about, are there any exchanges which return pages ascending? I mean, page2 is newer than page 1.
