### ISSUE TITLE
return error when decimal_to_precision args n is float

### ISSUE THREAD

**Issue by Iliker** [ccxt/ccxt#3860]
```
>>> from base.decimal_to_precision import decimal_to_precision
>>> decimal_to_precision(10000.0, 0, 5, 3, 4)
'1'
>>> decimal_to_precision("10000.0", 0, 5, 3, 4)
'10000'
```

error is call create_order in python/ccxt/binfinex.py

**Comment by kroitor** [comment]
@Iliker what's your version of CCXT ?

**Comment by Iliker** [comment]
1.16.89 @kroitor

**Comment by kroitor** [comment]
@Iliker you should update to at least 1.17.239 (better to most recent version of it), as this issue has already been reported by @beniloew here: https://github.com/ccxt/ccxt/issues/3800 and fixed by @frosty00 here: https://github.com/ccxt/ccxt/pull/3663. Let us know if that does not answer your question.
