### ISSUE TITLE
symbol/market and precision checks

### ISSUE THREAD

**Issue by ngugc** [ccxt/ccxt#3863]
- OS:
- Programming Language version: all
- CCXT version:
- Exchange:
- Method:

I notice that most of the exchange functions check if 'symbol' is in the market list, and when placing orders, the amount/price precision is checked.

In some cases, I would like to handle the above checks in user land or just skip the checks.
I wonder if there is solution for this requirement, or is it possible to add a switch to the above checks?

Thanks!

**Comment by kroitor** [comment]
> I notice that most of the exchange functions check if 'symbol' is in the market list

Exchanges have very strict rules on the values of `amount` and `price`, as explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Because `precision` and `limits` are both properties of a market, a symbol is required to identify the market and retrieve the info on market precision and limits from markets that are preloaded in prior.

> and when placing orders, the amount/price precision is checked.

Nope, the amount and price are not checked, instead they are forced to be of certain precisions + within limits, as described in the Manual.

Exchanges won't accept your values if the values don't conform to requirements on precision/limits. Therefore there's no "switch off" for that. However, you can still override any of params you want, as explained in https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

I'd recommend to read the entire Manual from the very beginning to the very end, this will save you a lot of time, really. It has tons of useful details, answers and explanations of various concepts – all that should help building a solid understanding of how it all works. 

But anyways, let us know if the above does not answer your question.

**Comment by ngugc** [comment]
@kroitor , as the market list cannot be updated in real time, a running app won't be able to handle the symbols that are newly listed in the exchanges.

**Comment by kroitor** [comment]
> as the market list cannot be updated in real time

Why? As described here: https://github.com/ccxt/ccxt/wiki/Manual#market-cache-force-reload you can load the list of markets and update it in real time in your running app whenever you want/need, as many times as you want throughout the lifetime of your app.

**Comment by ngugc** [comment]
@kroitor , the reason is that usually we don't know the exact time the symbols will be listed. We may only know “xxx symbol will be listed in yyy days” from the exchange announcements. We have to poll the market list.

**Comment by kroitor** [comment]
> We have to poll the market list.

Right, there's no shortcuts, you have to poll it if you want the an up-to-date view of their markets.

**Comment by ngugc** [comment]
@kroitor, that's why I ask for an option to fire bare requests without the whitelist check.

**Comment by kroitor** [comment]
> @kroitor, that's why I ask for an option to fire bare requests without the whitelist check.

@ngugc you can do that with implicit methods, as documented here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
