### ISSUE TITLE
warning: 'couldn't find .netrc file'

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#3867]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version:  python 3.7
- CCXT version: 1.17.309
- Exchange: all exchanges
- Method: fetch2OrderBook(), fetchBalance()

Igor, Good morning,

I am using asynchronous ccxt access to exchanges. From yesterday ( I suppose after ccxt was upgraded) after each request to exchange I have got the warning: "couldn't find .netrc file".

Today I upgraded ccxt to the latest version but nothing changed, I am still getting such message.

What it may mean? If it possible to fix?

Thank you in advance,

Dmitry

**Comment by kroitor** [comment]
> What it may mean? If it possible to fix?

This is related to the following issue: https://github.com/ccxt/ccxt/issues/3854

The fix for it was to add `trust_env=True` flag to `aiohttp.ClientSession`. That option enables env variables for proxy support as described here: https://docs.aiohttp.org/en/stable/client_advanced.html?highlight=trust_env#proxy-support. It will then load proxy settings from env variables or from a `.netrc` file, if any. 

However, in your case that file is missing, and you probably have debug logging enabled, which is too verbose. So, this isn't really an error, more like a warning. But to suppress it, I've added a `self.aiohttp_trust_env` flag to the base exchange class, it's set to false by default, so you won't see the warning as of 1.17.311.
