### ISSUE TITLE
poloniex withdraw id

### ISSUE THREAD

**Issue by anik-jagtap** [ccxt/ccxt#3880]
- OS: Windows 7
- Programming Language version: JavaScript
- CCXT version: 1.17.240
- Exchange: Poloniex
- Method: withdraw()

Hi,
I am working with Poloniex withdraw method. Since withdraw method of other exchanges such as Bitfinex, Binance, etc provides us the response with the withdraw id or id; but poloniex just returns this,
`{
  "response": "Withdrew 2398 NXT."
}`
It does not include withdraw id or id. How can i get withdraw id for my withdraw request? Can you please help me in this ?

**Comment by kroitor** [comment]
> How can i get withdraw id for my withdraw request?

You can't, it's a limitation of the exchange. They won't return the id in response to your withdraw request.

> Can you please help me in this ?

We'd love to, but this isn't something that we can workaround on our side, the issue is with the Poloniex API itself. Therefore you can't really get that id in one call. However, you can fetch the history of your deposits and withdrawals, and find the id of your withdrawal from there (match it by the amount or by date – both are known to you upon making a withdraw request). We haven't unified the funding history method for poloniex yet, so you will have to use implicit methods to fetch your withdrawal history: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```
mbp:ccxt igorkroitor$ node
> const ccxt = require ('./ccxt')
undefined
> const poloniex = new ccxt.poloniex ();
undefined
> console.log (poloniex)
poloniex {
  ...
  privatePostReturnDepositsWithdrawals: [AsyncFunction: partial],
  private_post_returndepositswithdrawals: [AsyncFunction: partial],
  ...
```

Hope this answers your question, let us know if not.
