### ISSUE TITLE
fetchTicker returning undefined values

### ISSUE THREAD

**Issue by AdvaithD** [ccxt/ccxt#3890]
I have a simple function that fetches tickers of certain exchanges, and logs them

`async function ccxtPrices() {
  let prices = { btc: 0.0, usd: 0.0, eur: 0.0, gbp: 0.0, cny: 0.0 }
  let usd = coinbase.fetchTicker("BCH/USD")
  let eur = coinbase.fetchTicker("BCH/EUR")
  let gbp = coinbase.fetchTicker("BCH/GBP")
  let cny = okex.fetchTicker("BCH/CNY")

  Promise.all([usd, eur, gbp, cny]).then(function(values) {
    const [usd, eur, gbp, cny] = values
    console.log(usd)
  })
}

ccxtPrices()`

However, the USD ticker output contains several undefined values.

![](https://i.gyazo.com/1035d0bdf66a79bcd7475e75ca15d33d.png)

- OS: MacOS
- Programming Language version: Node V8
- CCXT version: v1.17.141
- Exchange: Coinbase pro and okex
- Method: fetchTicker

**Comment by kroitor** [comment]
> However, the USD ticker output contains several undefined values.

Hi! This is the expected behaviour as not all exchanges will return all fields, most of them will only return just a subset of them. CCXT unifies them to common names and types, but it cannot create a value out of thin air. We only have what we have from the exchange in question. Let us know if that does now answer your question.

**Comment by AdvaithD** [comment]
@kroitor thanks for clearing things out!
