### ISSUE TITLE
Bittrex fetch_ohlcv not working

### ISSUE THREAD

**Issue by thomas-leeee** [ccxt/ccxt#3896]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: MacOS
- Programming Language version: python3.6
- CCXT version:  1.7.212
- Exchange: bittrex
- Method: fetch_ohlcv

Tried with or without limit=3, both return empty dict.

```
import ccxt
import datetime


ex = ccxt.bittrex({'enableRateLimit': True, 'timeout': 5000})
ex.load_markets()
# print(dir(ex))
candles = ex.fetch_ohlcv('ETH/BTC', '1m', since=ex.milliseconds() - 2 * 60 * 1000, limit=3)
print(candles)
print(max([c[2] for c in candles]))
```

**Comment by kroitor** [comment]
```Python
import ccxt
ex = ccxt.bittrex({'enableRateLimit': True})
markets = ex.load_markets()
since = ex.milliseconds() - 2 * 60 * 1000
print("I'm trying to fetch candles since " + ex.iso8601(since))
candles = ex.fetch_ohlcv('ETH/BTC', '1m')
print("... while the last available bittrex candle is on " + ex.iso8601(candles[-1][0]))
```

```
mbp:ccxt igorkroitor$ python3
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> ex = ccxt.bittrex({'enableRateLimit': True})
>>> markets = ex.load_markets()
>>> since = ex.milliseconds() - 2 * 60 * 1000
>>> print("I'm trying to fetch candles since " + ex.iso8601(since))
I'm trying to fetch candles since 2018-09-23T19:50:23.645Z
>>> candles = ex.fetch_ohlcv('ETH/BTC', '1m')
>>> print("... while the last available bittrex candle is on " + ex.iso8601(candles[-1][0]))
... while the last available bittrex candle is on 2018-09-23T19:49:00.000Z
>>>
```

Let us know if the above does not answer your question.

**Comment by thomas-leeee** [comment]
Thanks @kroitor , I was not aware that the bittrex api is this *much* laggy. Do you have any suggestion for faster workaround using ccxt available functions for bittrex?

**Comment by kroitor** [comment]
> Do you have any suggestion for faster workaround using ccxt available functions for bittrex? I only need a few 1m candles from now=ex.milliseconds().

Yes: because OHLCV candles are built from trades in general, you can fetch most recent public trades and build OHLCV candles from there with `build_ohlcv` method:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1332

    \+

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1291

> and look at the gap of these candles!

That's expected – it means that within the missing periods there were no trades with the pair in question (BNT/BTC). Symbols that are not traded actively can have **natural** gaps.

**Comment by kroitor** [comment]
> I was not aware that the bittrex api is this much laggy.

It isn't actually laggy, if you take an actively traded pair like 'ETH/BTC' and look at previous answer carefully, then you'll see that current time is 19:50:23, and bittrex has the last candle from 49:00 - 50:00. It doesn't have a candle from 50:00 - 51:00 yet. Because the fifty first minute is not over yet. You will have the 50-51 candle as soon as time passed beyond 51:00. This should make it clear now, let me know if not.

**Comment by thomas-leeee** [comment]
That clarifies a lot actually. If possible you can update the manual with these information @kroitor . Specifically the code snippet we exchanged, as these are good template for new users. By digging this forum I know how to use .milliseconds() and .iso8601() which is quite useful.
