### ISSUE TITLE
data missing in minutes candle?

### ISSUE THREAD

**Issue by rg687** [ccxt/ccxt#3918]
- OS: Linux debian
- Programming Language version: pyhton
- CCXT version: 1.17.359
- Exchange: binance
- Method:

import ccxt
timestamp_ms_start = 1504713600000
''' datetime.datetime.fromtimestamp(1504713600)
 datetime.datetime(2017, 9, 6, 12, 0) '''

binance = ccxt.binance()
data = binance.fetch_ohlcv('LTC/BTC', '1m', since=timestamp_start)

data[0][0]-timestamp_start 
25200000

seems like some data are missing?
im trying to get minute by minute candle for binance from the opening of this market but i believe 24844 data points are missing

thanks

**Comment by kroitor** [comment]
1. Exchanges go offline, for maintenance and for other reasons from time to time, so you should not expect that you will have **continuous** fine-grained (1m) history – it will have gaps whether they want it or not and you have to be prepared for it. In other words, treat missing candles as if there were no trades during that period or as if the history is unknown. Missing candles are absolutely legitimate info, because a missing info is an info in itself – it tells you that there were gaps in the trade. There's no way we can "reconstruct" those gaps from thin air.

2. From your code it's not clear which values you have passed, because you don't report the issue with verbose request/response (your actually-sent values would be obvious from there), as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. You did show a value of `timestamp_ms_start`,  but you didn't show the value of `timestamp_start` so I have to guess it or to fix your program snippet first to make it work. If, instead, you could just follow those issue-posting guides precisely, that would help reproduce it and answer more precisely.

Let us know if that does not help.

**Comment by rg687** [comment]
oops i had rewrite the code on the fly and timestamp_start is timestamp_ms_start but you're right its probably just binance which had close his trading engine at the time.
thanks
