### ISSUE TITLE
Invalid Nonce on Bitstamp

### ISSUE THREAD

**Issue by sanyam199** [ccxt/ccxt#3939]
- OS: Ubuntu 14.04.5 LTS
- Programming Language version: Python 2.7
- CCXT version: 1.17.327
- Exchange: Bitstamp
- Method: fetch_balance, create_order, fetch_order

I have integrated ccxt in my system, and although everything works fine mostly, I encounter the "Invalid Nonce" error frequently on the above-mentioned methods.

**Comment by kroitor** [comment]
Are you using the built-in rate limiting?

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#invalidnonce

I highly recommend to read the entire Manual from top to bottom first in order to be able to work with this library efficiently. Let us know if that does not answer your question.
