### ISSUE TITLE
help understanding fetchBalance logic

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3948]
Hi

I'm trying to use ccxt for private account operation for the first time.  My chosen exchange is Liquid and I've had a couple of problems, the latest of which is understanding the how balances are handled.

I know that Liquid does not return the _free_ v's _used_ balance information in it's API, it only gives the total.  When I call the `fetchBalance` method, my `used` fields have a value of _0.0_, which is incorrect (I have open orders).  I would have expected it to be _undefined_ at least.

I took a look at the code and found what I consider to be the bug [here](https://github.com/ccxt/ccxt/blob/master/js/liquid.js#L179).   

I then noticed just below a method to the super class called `parseBalance`.  I think I understand what this method is trying to do but I couldn't get it to work. I have the following issues / questions:

It looks like the purpose of the method is to assign a value to the _used_ balance (if it is _undefined_) by using the `orders` cache via `getCurrencyUsedOnOpenOrders`.  Correct?

 * the name seems wrong to me - it doesn't parse anything.  Could it be renamed for clarity?
 * there is some code in there which (according to the comments) is specific to the _Liqui_ exchange - why is this code in the base class and not in the _Liqui_ implementation?  
 * after patching the _Liquid_ implementation to use the value `undefined` instead of `0.0` I still didn't have a correct _used_ balance.  

Looking at the base _Exchange_ class I can't see anywhere that the `orders` field is written to, which I imagine in the source of the 2nd bug?  How does the orders cache work?   The manual says:

> The ccxt library will try to emulate the order history for the user by keeping the cached .orders property containing all orders issued within a particular exchange class instance

This doesn't appear to be working for me, at least not for the Liquid exchange. I can see that a few exchanges write to `this.orders` explicitly in their implementations.  Is the orders cache something that each exchange must implement?  if so, how do you ensure consistency in it's use/implementation?

Thanks in advance for any info...

**Comment by kroitor** [comment]
Hi! Sorry for a long wait for the answer.

> It looks like the purpose of the method is to assign a value to the used balance (if it is undefined) by using the orders cache via getCurrencyUsedOnOpenOrders. Correct?

Yes, that's correct, however, orders cache is only used with a few particular exchanges (Liqui (not Liquid), Poloniex and some others).

> the name seems wrong to me - it doesn't parse anything. Could it be renamed for clarity?

Will review that and, hopefully, bring it back to order

> there is some code in there which (according to the comments) is specific to the Liqui exchange - why is this code in the base class and not in the Liqui implementation?

This is for historical reasons mostly, but yes, that code does not belong there for now, and we're going to move it to Liqui.

> Looking at the base Exchange class I can't see anywhere that the orders field is written to, which I imagine in the source of the 2nd bug? How does the orders cache work? The manual says:

> The ccxt library will try to emulate the order history for the user by keeping the cached .orders property containing all orders issued within a particular exchange class instance

> This doesn't appear to be working for me, at least not for the Liquid exchange. I can see that a few exchanges write to this.orders explicitly in their implementations. Is the orders cache something that each exchange must implement? if so, how do you ensure consistency in it's use/implementation?

I guess, the Manual isn't very clear on this, but yeah, that's because orders cache is only applied to certain exchanges, therefore the deduction of balances from orders doesn't (and shouldn't) work across all exchanges.

Hope this answers your questions, feel free to reopen it or just ask further questions, if not.

**Comment by npomfret** [comment]
@kroitor 

Can we remove the [liqui specific code](https://github.com/ccxt/ccxt/blob/bbf41e3066cf848d5d089d325a816ae60ead7683/js/base/Exchange.js#L1067) from the base exchange class?

> This is for historical reasons mostly, but yes, that code does not belong there for now, and we're going to move it to Liqui.

**Comment by kroitor** [comment]
@npomfret we will be able to tell in approximately 8 days ) Can't do that as long as their API responds. Also, some users may be using some parsers from the liqui class to process their history, so we will have to keep it for a while after the complete shutdown. One more thing – we have to make sure we don't break anything, because liqui is the base class for a few other derived exchanges, like, for example, yobit and others. Basically all ex-BTCe clones.
