### ISSUE TITLE
Can't pass optional parameter on Kraken

### ISSUE THREAD

**Issue by brucetus** [ccxt/ccxt#3954]
- OS: Debian 9 Stretch
- Programming Language version: Javascript
- CCXT version: Latest
- Exchange: Kraken
- Method: createOrder

Hi, I'm getting this error when trying to enter in the optional parameter 'leverage' when creating an order on Kraken. 

This is the code I use:
```
client.createOrder('BTC-USD', opts.type, opts.side, this.roundToNearest(opts.size, opts), opts.price, { 'leverage': args.leverage })
```
And I get this error here:
<img width="836" alt="screen shot 2018-10-05 at 5 11 58 pm" src="https://user-images.githubusercontent.com/31704711/46565365-6eecf100-c8c3-11e8-9e47-02e1b6abc9e0.png">

Without the leverage parameter it works perfectly fine and I'm able to place and complete orders.

**Comment by kroitor** [comment]
1. Kraken does not have a BTC-USD symbol: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
2. Your screenshot shows XMR-USD, which kinda makes me think you're not posting the code that corresponds to your screenshot (don't report text bugs in screenshots)
3. Because you don't post your verbose request/response it's hard to help you, we need you to follow this precisely:

  - https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

  ```JavaScript
  await client.loadMarkets ();

  client.verbose = true;  // ←-- add this and post your verbose request/response without your keys here

  client.createOrder('BTC/USD', opts.type, opts.side, this.roundToNearest(opts.size, opts), opts.price, { 'leverage': args.leverage })

  ```

**Comment by brucetus** [comment]
My apologizes, I didn't realize XMR didn't offer a leverage of 5 and that was what was causing this issue. I can confirm it is working now. Thank you.
