### ISSUE TITLE
Bitmex (Javascript for browser) Error [Invalid stopPx for ordType]

### ISSUE THREAD

**Issue by SavosRU** [ccxt/ccxt#3959]
- OS: Mac OS 10.13.6 High Sierra
- Programming Language version: Javascript, Google Chrome 69.0.3497.100 (64-bit)
- CCXT version: '1.17.369' (ccxt.browser.js)
- Exchange: Bitmex
- Method: create_order (for Stop and StopLimit)

Можно по-русски? Вроде тут кто-то писал...
Проблемы с созданием СТОП-ордеров. С маркетными и лимитными нет.
Суть такова.
1)
Имеем код для создания Стоп-Маркет-Ордера:
```
async function newStopMarketOrder(symbol, size, stop_price, side) {
   var stopType = 'Stop';	
   var params = new Array({'stopPx': stop_price});
    try {
        var result = exchange.createOrder(symbol, stopType, side, size, undefined, params);
        return result;        
    } catch (e) {
		var msg = "Exception at newStopMarketOrder(): " + e;
		console.log(msg);
		alert(msg)
    }	
}
```

Вызываем вот так:
```
var symbol = "BTC/USD";
var size = 20;
var side = "Sell";
var limit_price = 6500;
var stop_price = 6510;

newStopMarketOrder(symbol, size, stop_price, side).then(result => {
	alert(result);
});
```
Судя по отладчику в Хроме - видим, что формируется запрос вида:
https://testnet.bitmex.com/api/v1/order?0%5BstopPx%5D=6510&symbol=XBTUSD&side=Buy&orderQty=20&ordType=Stop
И на него приходит ошибка:
Unhandled Promise Rejection: Error: bitmex {"error":{"message":"Invalid stopPx for ordType","name":"HTTPError"}}

При этом, когда через Bitmex API Explorer проводим ту же операцию по созданию стоп-маркета с теми же параметрами - все ок. Response Body нам показывает (лишнее пустое убрал):
```
{
  "symbol": "XBTUSD",
  "side": "Sell",
  "orderQty": 20,
  "price": null,
  "stopPx": 6510,
  "ordType": "Stop",
  "ordStatus": "New",
}
```
Вроде бы все те же самые параметры stopPX и ordType - но что-то не так... Почему?

2) Со Стоп-Лимитными-Ордерами то же самое. 
Код:
```
async function newStopLimitOrder(symbol, size, stop_price, limit_price, side) {    
    var stopType = 'StopLimit';
    var params = new Array({'price': limit_price,  'stopPx': stop_price, 'ordType': stopType} );
    try {
        var result = exchange.create_order(symbol, stopType, side, size, limit_price, params);
        return result;        
    } catch (e) {
		var msg = "Exception at newStopLimitOrder(): " + e;
		console.log(msg);
		alert(msg)
    }	
}
```
Вызываем вот так:
```
var symbol = "BTC/USD";
var size = 20;
var side = "Sell";
var limit_price = 6500;
var stop_price = 6510;

newStopLimitOrder(symbol, size, stop_price, limit_price, side).then(result => {
	alert(result);
});
```
По отладчику видим запрос вида:
https://testnet.bitmex.com/api/v1/order?0%5Bprice%5D=6500&1%5BstopPx%5D=6510&2%5BordType%5D=StopLimit&symbol=XBTUSD&side=Buy&orderQty=20&ordType=StopLimit&price=6500
И на него приходит ТА ЖЕ ошибка:
Unhandled Promise Rejection: Error: bitmex {"error":{"message":"Invalid stopPx for ordType","name":"HTTPError"}}
Хотя по API Explorer как Вы понимаете - тоже все работает...

Что я делаю не так? Пробовал менять create_order на createOrder - ничего не меняется.
Маркет ордера через ту же create_order создаются без проблем. Лимитники тоже...
А вот стопы никак не хотят
Заранее благодарен!

P.S. на PHP, кстати, тоже столкнулся с проблемой СтопМаркетов, но там хоть Стоп-Лимиты ставит... Надо будет по стоп-маркетам на PHP создать отдельный запрос тут?

**Comment by SavosRU** [comment]
Похоже, разница между API Expolrer и CCXT кроется именно в генерируемом URL для запроса.

Вижу на эксплорере такой адрес:
`curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-With: XMLHttpRequest' -d 'symbol=XBTUSD&side=Sell&orderQty=20&stopPx=6510&ordType=Stop' 'https://testnet.bitmex.com/api/v1/order'`

И тут тот самый злосчастный stopPx=6510 присутствует явно. А в приведенном мною выше коде видно, что этой переменной в явном виде нет, она есть только в закодированной его части. Может в этом и проблема?

![image](https://user-images.githubusercontent.com/6779356/46587478-af03cd80-ca95-11e8-9b1b-58d41ee3ff37.png)

![image](https://user-images.githubusercontent.com/6779356/46587486-cc389c00-ca95-11e8-989e-48f65686623d.png)

**Comment by SavosRU** [comment]
Сам спросил - сам же и отвечаю!

меняем
`var params = new Array({'stopPx': stop_price});
`
на
`var params = JSON.parse('{"stopPx": '+ stop_price + '}');
`
И ВСЁ ЗАРАБОТАЛО!!!

С стоп-лимитами аналогично

**Comment by kroitor** [comment]
Your initial problem was not in the way the library works, but in the way you understand JavaScript arrays. And this is most likely due to the fact that you're coming from PHP world and you kinda extrapolate your expectations to other languages from your previous PHP experience. In PHP indexed arrays and associative arrays are the same, so in PHP this syntax is absolutely ok:

```PHP
// PHP
$array1 = array ('foo', 'bar'); // this will be a array[0] = 'foo', array[1] = 'bar'
$array2 = array ('a' => 'foo', 'b' => 'bar'); // this will be a array['a'] = 'foo', array['b'] = 'bar'
// the syntax for assoc arrays is the same as for indexed arrays ↑
```

In JavaScript and other languages you can't mix the two like that. Indexed arrays (also known as lists) can only be created and used in a certain way. The way of working with associative arrays (also known as dictionaries or objects) – is different. The following JS snippet shows it:

```JavaScript
// JavaScript
array1 = new Array ('foo', 'bar') // equal to your first line from PHP
array2 = {'a': 'foo', 'b': 'bar' } // NOT AN ARRAY !!! it's an object equal to your second line in PHP
// in JS you create indexed arrays vs assoc dicts differently ↑
```

So, I'm pretty much convinced that your trouble were caused by the way you're wrapping the params into an array:

```
var params = new Array({'stopPx': stop_price}); // may be ok in PHP, but totally wrong in JS
```

You don't want to convert the object to an array. Because `params` should be an assoc object. 
So, you need more JS training with basic syntax, code constructs and built-in types to understand it and to work with it efficiently.

Also, you **don't want** to parse your object from a string representation with `JSON.parse`, because in JS you can specify the result of that operation in code syntax. **Objects are JSON in JS. ** But that's a whole other story, get more reading about that...

Therefore **the correct syntax is not**:

```JavaScript
var params = JSON.parse('{"stopPx": '+ stop_price + '}'); // wrong
var params = new Array({'stopPx': stop_price}); // wrong
```

**The correct syntax is:**

```JavaScript
var params = {"stopPx": stop_price} // correct
```

Make sure that your previous conclusion does not hide the actual true cause of the issue and make sure you really do understand it to the end.

**Comment by SavosRU** [comment]
Big thanks for your answer to my request!

You are right - my previous experience on PHP make me bad service in JS-development.
But I'm learning and getting some results ;-)

Nice job, perfect project!
Good luck!
