### ISSUE TITLE
Wrong datetime for exchanges for hitbtc2 & coinbase

### ISSUE THREAD

**Issue by 4knahs** [ccxt/ccxt#3984]
- OS: Ubuntu 17.04
- Programming Language version: Py
- CCXT version: 1.17.113
- Exchange: hitbtc2 and coinbase
- Method: fetch_tickers

Basically the datetime field for these two exchanges is incorrect. For coinbase the timestamp is seconds and thus its miscalculated as the conversion assumes milliseconds. In the case of hitbtc2, the timestamp is 0 and thus the date time gets reported as 1970.

Examples:

 exchange |         datetime         
----------+--------------------------
 coinbase | 1970-01-18T18:40:08.868Z
 coinbase | 1970-01-18T18:40:09.168Z
 hitbtc2  | 1970-01-01T00:00:00.000Z
 hitbtc2  | 1970-01-01T00:00:00.000Z

**Comment by 4knahs** [comment]
Actually the hitbtc2 has its timestamp set to 0.

**Comment by kroitor** [comment]
@4knahs can you post your verbose output for the above call?

```
hitbtc2 = ccxt.hitbtc2 ()
hitbtc2.load_markets ()
hitbtc2.verbose = True
tickers = hitbtc2.fetch_tickers ()
```

? Because I'm not seeing the above symptoms with the most recent version 1.17.378 when I do this:

```
mbp:ccxt igorkroitor$ python examples/py/cli.py hitbtc2 fetch_tickers
```

All datetimes are within 2018:

<img width="461" alt="screen shot 2018-10-13 at 16 13 42" src="https://user-images.githubusercontent.com/1294454/46905902-02957180-cf03-11e8-9943-c7b829608771.png">
