### ISSUE TITLE
Wallet withdrawal fee

### ISSUE THREAD

**Issue by marinsokol5** [ccxt/ccxt#40]
Is there any chance of adding the wallet withdrawal fee.
https://hitbtc.com/fees-and-limits 
https://support.kraken.com/hc/en-us/articles/201893608-What-are-the-withdrawal-fees-
they are not that hard to find but it looks that a lot of them require hardcoding.
Maybe not for everyone but for like 20 of them?

**Comment by kroitor** [comment]
Yeah, thanks for writing us! We're working on it right now! We call that a **Unified API**, and it is being developed right as I write this to you ) Currently, we have unified tickers and order books, but balances, orders and fees are not unified yet. There's also [a similar issue here](https://github.com/kroitor/ccxt/issues/36) about balance unification. We're going to finish balance unification in a few days and then we will unify the fees, that would take a few days as well. So, keep in touch for updates, your request will soon be satisfied. )

**Comment by kroitor** [comment]
We have just unified the balance API, as written in #36, and now we're coming up for orders and fees! )

**Comment by munrocket** [comment]
What about withdrawl fee? Are JS library more fresh than python?
I not digged deep, but as I understand only binance have withdrawal fees in python.

**Comment by kroitor** [comment]
@munrocket this is currently under heavy development, namely trading and funding fees + orders API, deposits and withdrawals. Hope to deliver soon. Your PRs are welcome!

**Comment by munrocket** [comment]
@kroitor Can I just PR in python project or I need to change JS file?

**Comment by kroitor** [comment]
@munrocket please, make sure to read this first: https://github.com/ccxt-dev/ccxt/blob/master/CONTRIBUTING.md. Thx!

**Comment by toothlessG22** [comment]
Are you still working on this issue? If so, how are you tackling it? Hardcoding? Scraping? I’d like to to try to help. 

Thanks.

**Comment by kroitor** [comment]
@toothlessG22 most of the work on it is now going on here: https://github.com/ccxt/ccxt/pull/553
We're now unifying fetchCurrencies() because we believe the withdrawal fee should be a property of the currency. So, we're adding a special entity for currency, and the `.currencies` property on the Exchange is now an assoc array of such entities.

The plan is: I'm going to merge the above PR in a couple of days and will also rework/unify the structure of the currency entity, and from there we will need to add implementations of fetchCurrencies to as many exchanges as possible (where supported, of course). 

So, your contributions are welcome, we appreciate all help, I will notify you as soon as that PR is merged. There's also a lot of room for contributions to other aspects of the library as wll, more about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Because currencies and their properties are involved in many places of the library, this is also related to the recently started rework of the deposit API by @Deathamns , here:
- https://github.com/ccxt/ccxt/search?q=fetchDepositAddress&type=Commits&utf8=%E2%9C%93
- https://github.com/ccxt/ccxt/search?q=fetchDepositAddress&type=Issues&utf8=%E2%9C%93

So, this is the current status. We are going to make a breakthrough on this in the coming few days. Let us know if you have any questions.

**Comment by kroitor** [comment]
@toothlessG22 this is also an important part of the whole story: https://github.com/ccxt/ccxt/pull/473

**Comment by toothlessG22** [comment]
@kroitor Thanks for the info! Looking forward to the merge.

**Comment by kroitor** [comment]
Now that a lot of work has been done to target this issue and many exchanges already have withdrawal fees defined, I think we can close it for now and start adding exchange-specific issues and pull-requests, if any. Feel free to reopen it if need, `fees` will also be documented in the Manual very soon. Cheers!

**Comment by devsi** [comment]
Necro thread!

@kroitor I see many exchanges have implemented their custom endpoints to return withdrawal fees, but there is no unified way to retrieve these fees (from what I can see?)

I have had to write overriding classes for 9 exchanges in my project as each exchange handles retrieving the withdrawal fee differently. (trade fees are hardcoded so I can use them as most exchanges supply that).

**Comment by devsi** [comment]
Meep. Looks like SOME of the exchanges have `fetchFundingFee` implemented, but only half the ones I use do so I still have to write it myself for most.

`fetchFundingFee` confused me as I assumed it was purely a fee for crediting your account with a balance.

**Comment by kroitor** [comment]
> Meep. Looks like SOME of the exchanges have `fetchFundingFee` implemented, but only half the ones I use do so I still have to write it myself for most.

@devsi yep, this is a long story, and if you want to understand it to its full extent, please, go through these posts:

- https://github.com/ccxt/ccxt/pull/1793
- https://github.com/ccxt/ccxt/pull/1814#issuecomment-363827160
- https://github.com/ccxt/ccxt/pull/1669
- https://github.com/ccxt/ccxt/issues/4128

Let me know if you have questions after that.

In short, you're right, and funding fees are not unified yet. We are making progress towards the following generalization:

- tradings fees:
  - fetchTradingFee (symbol)
  - fetchTradingFees (symbols = undefined)
  - loadTradingFees
  - loadFees
- funding fees (include both withdrawal and deposit fees, as some exchange have deposit fees)
  - fetchFundingFee (code)
  - fetchFundingFees (codes = undefined)
  - loadFundingFees 
  - loadFees

↑ The above should be tied with loadMarkets (which also requires resolving the calls for `fetchMarkets` and `fetchCurrencies` in proper order) and `loadMarketsAndCurrencies` + `loadFees` + `loadLimits` = `load()`...
