### ISSUE TITLE
Btcturk Return Html Content

### ISSUE THREAD

**Issue by semihyesilyurt** [ccxt/ccxt#4007]
Btcturk giving 403

- OS: Win10
- Programming Language version: 3.7
- CCXT version: last
- Exchange: btcturk
- Method: get_balance()

**Comment by kroitor** [comment]
Can you please follow [these guides]() and post your verbose request/response?

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Also, what exactly from the Manual have you tried already to workaround this issue? CORS ? Proxies? VPN? Basically, in order to help you we need much more detail.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki#troubleshooting
