### ISSUE TITLE
fetch_tickers use inactive markets 

### ISSUE THREAD

**Issue by Matoran** [ccxt/ccxt#4011]
Hi, 

when we use fetch_tickers we have some inactive markets (like HSRBTC in binance). Is it wanted ? Otherwise i could fix it by using self.markets to filter each ticker.

**Comment by kroitor** [comment]
Hi!

> Is it wanted ? 

Yes, this is by design, because the library should not decide what they user might or might not need. Therefore we don't filter those results, unless this is absolutely necessary. In other words, we tend to return as much as possible from the exchange. We believe whatever filtering is necessary – should be applied in userland after receiving the result. Hope this answers your question. But still, thx anyways for your participation, your help is very much appreciated, there's plenty of room for enhancements: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md, your pull requests are welcome!
