### ISSUE TITLE
How to get funding rate data on bitmex

### ISSUE THREAD

**Issue by czonghui** [ccxt/ccxt#4021]
- OS: win10
- Programming Language version: py 2.7 on anaconda 5.2 32bit
- CCXT version: 1.17.371
- Exchange: bitmex
- Method: fetch_fees()

Code

import ccxt
mktBitmex = ccxt.bitmex()
ww=mktBitmex.fetch_fees()
dfww=pd.DataFrame(ww)
dfww.to_csv('mktBitmex_fee_CCXT.csv', sep=',', encoding='utf-8')

Result

I run the above code and get empty csv file.  After debugging I find the code runs to  the following function

    def fetch_fees(self):
        trading = {}
        funding = {}
        try:
            trading = self.fetch_trading_fees()
        except AuthenticationError:
            pass
        except AttributeError:
            pass

        try:
            funding = self.fetch_funding_fees()
        except AuthenticationError:
            pass
        except AttributeError:
            pass  <------------------------ code jumps to here 

        return {
            'trading': trading,
            'funding': funding,
        }

how can I change code to get the funding fee of Bitmex?

**Comment by kroitor** [comment]
> how can I change code to get the funding fee of Bitmex?

You cannot – they don't serve that info from their API and don't have those limits documented anywhere in their docs, so you will have to hardcode those limits by trying manually on their website for currencies you need and use minimal values from there. Hope this answers your question.

**Comment by xorq** [comment]
GET /instrument does the job
https://www.bitmex.com/api/explorer/#!/Instrument/Instrument_get

**Comment by kroitor** [comment]
@xorq this is exactly what we're doing in fetchMarkets for bitmex:

- https://github.com/ccxt/ccxt/blob/master/js/bitmex.js#L151
- https://github.com/ccxt/ccxt/wiki/Manual#markets

However, I think the author's question was about withdrawal fees.

If you really try to open https://www.bitmex.com/api/v1/instrument?count=100&reverse=false
all `fundingRate`s are `null`:

<img width="965" alt="screen shot 2018-12-01 at 12 43 30" src="https://user-images.githubusercontent.com/1294454/49326668-d1323d00-f566-11e8-992d-0516ea4e7874.png">

It's also interesting to note that the withdrawal fee rate is not a property of an instrument (aka *trading pair*, *market*, *symbol*) – because, obviously, you can't deposit or withdraw a pair of currencies, the withdrawal fee is a property of each particular currency, because you can only deposit or withdraw one currency at a time.

**Comment by sweihub** [comment]
> GET /instrument does the job https://www.bitmex.com/api/explorer/#!/Instrument/Instrument_get

This works
```sh
curl https://www.bitmex.com/api/v1/funding 
```

Output
```json
[
 {
    "timestamp": "2016-06-02T12:00:00.000Z",
    "symbol": "XBTUSD",
    "fundingInterval": "2000-01-02T00:00:00.000Z",
    "fundingRate": 0.0009739999999999999,
    "fundingRateDaily": 0.0009739999999999999
  },
]
```
