### ISSUE TITLE
fetch_ohlcv has varying responses for OHLCV when called with a fixed time that coinpair/market may not be listed for

### ISSUE THREAD

**Issue by michaelwaldman** [ccxt/ccxt#4038]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: OS X Mojave
- Programming Language version: Python 3
- CCXT version: 1.17.405
- Exchange:  ACX and Binance, but generally all
- Method: fetch_ohlcv

I've reviewed all similar posted issues and did not find any that matched, but my apologies if I missed anything.
Essentially, I'm trying to pull data from a fixed point in time for various exchanges/coin pairs on the exchanges, and the issue I run into is that some exchanges, like acx, will return an empty list '[]', whereas binance will fast forward until the point in time where they do have data and return that as the "since" value.  My script will get stuck on the ones that return an empty list as it appends the length of the fetched OHLCV * 60 * 1000 (I know @kroitor mentioned  [here](https://github.com/ccxt/ccxt/issues/4035#issuecomment-432326496) that `from_timestamp = ohlcv[-1][0] + minute` is a better way to iterate, but I'm not sure this how this would apply to me as I make multiple separate calls since I need data at min. granularity) Essentially, I wanted to know if there's a way to get the oldest supported time for each coinpair on an exchange, and if not how I could get around that since I want to start at the oldest time. 
For replication purposes, the call that generates an empty list is:
```
curr_exchange = 'acx'
client = getattr(ccxt, curr_exchange)({
    'enableRateLimit': True,
})

print(client.fetch_ohlcv(symbol="BTC/AUD",timeframe="5m", since=1414091252000))
```

**Comment by ttodua** [comment]
old topic, but still relevant issue. so, i'll post a comment: even though that would be good to be fixed,  unfortunately, I think this might be wontfix, because different exchanges behave differently and might be impossible to reliable tell the answer. for example, fetching ohlcv data from 2017 (on exchange which was opened at 2018), might return `[]` response, but other exchanges might throw an exception. so, in the first case, ccxt does now know the listing time, ccxt cant determine whether provided `[]` should be translated into exception.

however, i might return to this issue in future.
