### ISSUE TITLE
Making loadMarkets/fetchMarkets accept a marketid as a parameter, to speed things up

### ISSUE THREAD

**Issue by ShoresOfNowhere** [ccxt/ccxt#4039]
Can the loadmarkets/fetchmarkets function be modified as to accept a parameter indicating what market are we interested in? It could even be left as an optional parameter, which if omitted would simply make the functions behave as they do now and get all the markets.

This is an efficiency feature, as there are big exchanges which do have HUNDREDS of markets, and reading all of them when you just need a single market is time consuming without any reason. I don't know if other coders are doing like me, but I rarely need these infos for more than two markets in a specific moment, and loading 600+ markets (for example on livecoin there are 666 markets) when you need one of them is slow...

**Comment by kroitor** [comment]
@ShoresOfNowhere in most cases loading 600 markets takes exactly the same amount of https requests as loading just one market. That is because all of them are reported from the endpoint responsible for the list of markets, and you can't really choose or specify that in a cross-compatible. You can only load them first, then filter them to just one, which makes very little sense if you're trying to avoid loading all of them in the first place. So, in general, the answer to your question is "no", unfortunately. Some exchanges execute more than one request, but they don't really fetch markets one by one.
