### ISSUE TITLE
bittrex fetchDeposits returns no timestamp and datetime

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#4050]
- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.17.421
- Exchange: bittrex
- Method: fetchDeposit

The only timestamp returned from the exchnage for withdrawals is in the 'LastUpdated' field. This should probably be used for the timestamp and datetime. The 'Opened' field that is used for Withdrawals is not available when fetching deposits

**Comment by kroitor** [comment]
> The only timestamp returned from the exchnage for withdrawals is in the 'LastUpdated' field. This should probably be used for the timestamp and datetime. 

Nope, unfortunately, we can't set that timestamp there, because it literally means the last updated timestamp, therefore it is in the transaction structure, in the `updated` field. We don't invent values where the exchange in question does not provide them. You can add that logic to your code in userland on client-side, namely, *"consider updated timestamp for Bittrex deposits a timestamp"*. But, unfortunately, this may not play well for all users equally. The other signifcant reason behind it is that the LastUpdated field can change, which should not happen to a unified `timestamp` (it should always be fixed, unchanging, if set).

> The 'Opened' field that is used for Withdrawals is not available when fetching deposits

Right, this is by design again, same reasoning basically. They don't support any date-based pagination for deposits and withdrawals whatsoever.

Does the above answer your question? )

**Comment by WoK-E** [comment]
Yes, it does answer the question, and I understand the reasoning. I will; be closing the issue.

The reason I use 'LastUpdated' is because this is when the exchange gets enough confirmations, in order to consider the deposit valid, and stops updating the record. The other (selfish) reason is because I want to minimize the ccxt classes I extend in order to provide such extra logic and functionality :)

Thanks for the prompt response, and thanks for this great library!
