### ISSUE TITLE
Kucoin - withdraw command ignore tag input

### ISSUE THREAD

**Issue by lampardlb** [ccxt/ccxt#4062]
- OS: Windows
- Programming Language version: python
- CCXT version: 1.17.419
- Exchange: Kucoin
- Method: withdraw

I've used kucoin.withdraw to withdraw a small amount of XLM with tag input, but found that the input ignores the tag and leave it blank. I then looked into the source code and found that the withdraw function in kucoin.py does not have 'if tag' command. This could potentially cause delay or even missing of fund for other users so perhaps worth a simple fix.

**Comment by kroitor** [comment]
@lampardlb the problem is that they don't document the usage of tag or memo anywhere in their docs:

https://kucoinapidocs.docs.apiary.io/#reference/0/assets-operation/create-withdrawal-apply

We've found this reddit post: https://www.reddit.com/r/kucoin/comments/93o92b/withdraw_of_xlm_through_api/ and added the support for `tag` by gluing it with a `@` sign to the address, however, we're not sure if it is a correct solution or not. Would be very thankful if you could help us test it and report back, whether it works for you now or not. Please, update to version 1.17.435 (it will be available for downloading in 5-10 minutes), and then retry.

**Comment by lampardlb** [comment]
I've now tested and can confirm it works perfectly, thank you very much!

**Comment by kroitor** [comment]
@lampardlb thanks for reporting and for your feedback! Appreciate it!

**Comment by lampardlb** [comment]
> @lampardlb thanks for reporting and for your feedback! Appreciate it!

I really appreciate all the work you and your fellow admins of the ccxt project have done, you're absolutely amazing!
