### ISSUE TITLE
when symbol haven't active property, they are active ?

### ISSUE THREAD

**Issue by Matoran** [ccxt/ccxt#4075]
Hi,

some exchanges do not have active property for each symbol. It's mean that all symbols return by the API are active ? Or we don't know :D ? Sorry if the answer is somewhere (wiki or code) but i don't find it :X.

Thanks in advance for the help.

**Comment by kroitor** [comment]
> It's mean that all symbols return by the API are active ? Or we don't know :D ?

It means, we don't know, because either the exchange in question does not report that, or we don't have proper parsing for that particular field, as it was added later along the way, so, some implementation may be missing that flag even in cases when exchanges do provide it. This is still under development, and if you can list those exchanges that miss that flag, we will add fixes, where necessary. Hope this answers your question, let us know if not )
