### ISSUE TITLE
Error: binance GET request timed out (10000 ms)

### ISSUE THREAD

**Issue by kobej1** [ccxt/ccxt#4104]
Hello,

I sync my local time every minute with the software "Dimension 4" but after an hour of 2 I have still the error "binance GET request timed out (10000 ms)". This time it got this error when calling after my KEY balance. Do anyone know how to fix this problem? This was my output:

![image](https://user-images.githubusercontent.com/42657049/47956973-46cddc00-dfae-11e8-9f2c-f7dbd3047835.png)

- OS: Windows 10 
- Programming Language version: Node.js
- CCXT version: 1.17.458
- Exchange: Binance
- Method: Getting KEY balance

**Comment by kroitor** [comment]
From your screenshot it looks like you're fetching the ticker (not the balance). Anyways, that's a common pitfall if you forget to apply rate limiting as required by the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/issues/1855
- https://github.com/ccxt/ccxt/issues/1027
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#limits
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#24hr-ticker-price-change-statistics

Hope this answers your question.

**Comment by kobej1** [comment]
Yeah sorry I apologize, I meant fetching the ticker of the coin KEY. But I get the "binance GET request timed out (10000 ms)" error after an hour of two for a random method I want to execute. I sync my local time every minute and added **'enableRateLimit': true** when adding my api keys. But is there a way to solve this issue?

**Comment by kroitor** [comment]
>  I meant fetching the ticker of the coin KEY.

Ok, however, note, that you can't really fetch a ticker for a *coin*, you can fetch a ticker for a pair of traded coins, that is a *symbol*, as decribed in the Manual (market *symbols* are not the same as coin or token *codes*). 

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

That doesn't really make a significant difference to your main question, just make sure that you use the same terminology as in the Manual, otherwise it can be confusing. Binance has at least two symbols involving the `KEY` currency code:

- `KEY/BTC`
- `KEY/ETH`

↑ To understand this properly, I'd recommend to read the entire Manual from top to bottom, it will save you a lot of time, seriously.

> But I get the "binance GET request timed out (10000 ms)" error after an hour of two for a random method I want to execute.

> is there a way to solve this issue?

For random occasional timeouts – the solution is to just repeat the call again later (in a second or a few seconds). In other words, you have to add some very basic error handling:

```JavaScript
while (true) {
    try {
        let symbol = 'ETH/BTC' // your symbol
        let ticker = await exchange.fetchTicker (symbol)
    } catch (e) {
        console.log (e)
        console.log (e.constructor.name)
        console.log (e.message)
        if (e instanceOf ccxt.RequestTimeout) {    
            // do nothing and retry upon your next iteration
        } else if (e instanceOf ccxt.ExchangeNotAvailable) {
            // do nothing and retry upon your next iteration
        } else if (e instanceOf ccxt.ExchangeError) {
            // stop the execution, or add your handling
            // according to the needs of your application
            process.exit ();            
        }
        await exchange.sleep (exchange.rateLimit); // add a delay before retrying
    }
}
```

Described here: https://github.com/ccxt/ccxt/wiki/Manual#error-handling
