### ISSUE TITLE
no trades attribute despite order fills

### ISSUE THREAD

**Issue by 7013145** [ccxt/ccxt#4125]
- OS: Ubuntu Linux 32-bit
- Programming Language version: Python3
- CCXT version: 
- Exchange: Yobit
- Method: order_info

A fill has occurred but there is no `trades` attribute when i query order_info. The `remaining` and `filled` attributes does reflect the fill, but I was hoping I could rely only on the `trades` attribute to monitor progress since using the filled/remaining might result in inaccurate execution prices, for taker orders at least.

Should i make sure to also check for fills even if no `trades` attribute is present? Or is this unwanted behaviour particular to yobit? I have not encountered this problem on other exchanges.

**Comment by kroitor** [comment]
> when i query order_info

If you query for their private `OrderInfo` endpoint with implicit methods, then you get the response from the exchange as is, and it's missing the fills – we won't make them up out of thin air, if the exchange does not provide that information. If, on the other hand, you do the call to `fetchOrder` then and the missing bits are there, but not parsed correctly in CCXT, it's a different story, and some fixes to the parsing code may be required. In any case, we need you to read this carefully:

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Thus, in order to proceed, we need your **code** and your **verbose request/response** to be able to tell the exact reason for missing fills there.

**Comment by 7013145** [comment]
I see that you are correct, I am using the `fetch_order` call from `ccxt.yobit`.

The thing is, usually the `trades` attribute works correctly. I could hope it's a one-off, or turn verbose on until the scenario occurs again.

My code is simple, I just make the above call and then handle the resulting `order` object, which probably have been working correctly 299/300 times.

I thought maybe if the executed order was at exact same rate as `order` object, it might forego using `trades` attribute.

Will read your resources, and if it occurs again i'll turn verbose on and hopefully give you all the information you need.

**Comment by kroitor** [comment]
Closing this if you don't mind, feel free to reopen it if needed or simply ask questions if any.
