### ISSUE TITLE
Gate.io has now API to withdraw

### ISSUE THREAD

**Issue by Newar417** [ccxt/ccxt#413]
_(Thanks to https://github.com/ccxt/ccxt/issues/412)_

Gate.io API has now API capabilities. 

API URL: https://api.gate.io/api2/1/private/withdraw

**Comment by kroitor** [comment]
Thx for the info, though, we know that is has an API to withdraw, because it is inherited from Bter. The unified withdraw for bter/gate is not implemented in ccxt yet, we will be happy for your contributions. In the meantime, I'm closing this, if you don't mind, we will update you upon implementing the unified withdraw for Gate.io.

**Comment by kroitor** [comment]
It has been unified in ccxt v.1.9.282+. Don't forget to update.
