### ISSUE TITLE
load_markets/fetch_markets optional parameters

### ISSUE THREAD

**Issue by maayank** [ccxt/ccxt#4132]
Some exchanges have optional parameters that may be of interest to their load_markets counterpart (e.g. 'expired' get parameter for 'getinstruments' at Deribit). Is there a way to pass the parameter to the request?

Assuming not (I'm not seeing a way thru the ccxt source code):
1. Is it possible to open a feature request? :)
2. I **may** implement it myself and send a patch (python) - what would be the ccxt-architecture way to do it?

Cheers

Edit: as other functions depend on the resultset from fetch_markets, this seems like "extra" important, as one couldn't simply get the market name by other means (outside of fetch_markets) and use it with ccxt.

**Comment by kroitor** [comment]
>  Is there a way to pass the parameter to the request?

As you know from the Manual, practically all methods have a way to pass those extra params/overrides, as described here: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params. However, load_markets/fetch_markets is currently the only method that does not conform to that rule – that is mostly due to historical reasons. But we can add `params = {}` to its arguments as we do for most other unified methods.

> Is it possible to open a feature request? :)

Yes, sure ) You've opened it already by posting this issue.

> I may implement it myself and send a patch (python) - what would be the ccxt-architecture way to do it?

The CCXT-way to do that would be to follow these steps:
1. Read **very carefully**:
  - https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
  - https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
  - https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes
2. Because `load_markets()` is a base class method, we will have to change its implementation in the base class for each of JS/Py/PHP, but the edits required are trivial.
3. Change declarations of `fetch_markets()` in all derived classes by adding an argument to it and make sure it is propagated through the `load_markets` → `fetch_markets` → `implicit method` chain... https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if that does not answer your questions, we'll be happy if you submit a PR for the above request. If not, no worries, we'll add it, hopefully, soon.

**Comment by ShoresOfNowhere** [comment]
I think kroitor has merged this in v. 1.17.533, so that fetch_markets and load_markets now accept the custom params parameter, but work should be done on individual drivers to react to this new parameter in their fetch_markets functions; until this happens the parameter is accepted but ignored.

I'll be posting a patch to livecoin driver ASAP, but since I'm now working on a small set of exchanges, I will not patch soon other exchange direvers...

**Comment by maayank** [comment]
Many thanks 👍 ❤️

**Comment by xyc0562** [comment]
@kroitor Many existing adapters' fetch_markets haven't been modified to reflect this optional parameter and in the Python build (functions cannot be called with more than accepted number of arguments) these will simply fail.

**Comment by kroitor** [comment]
> Many existing adapters' fetch_markets haven't been modified to reflect this optional parameter

Which particular adapters you mean? o.O We thought, we modified all `fetchMarkets` to acceps `params`... Let us know if we missed some.

**Comment by xyc0562** [comment]
> > Many existing adapters' fetch_markets haven't been modified to reflect this optional parameter
> 
> Which particular adapters you mean? o.O We thought, we modified `fetchMarkets` to accept extra `params`... Let us know if we missed some exchanges.

My mistake, I think I messed up with the source code on my side of the repo. Just checked and all adapters have the `params` optional argument in `fetch_markets` method.

**Comment by kroitor** [comment]
@xyc0562 no worries, don't hesitate to ask if you find something suspicious )

**Comment by kroitor** [comment]
We're now passing the params through the `loadMarkets` → `fetchMarkets` chain everywhere.
