### ISSUE TITLE
New Exchange: coinsuper

### ISSUE THREAD

**Issue by coinsuperapi** [ccxt/ccxt#4151]
Note: We submited a same create issue before: https://github.com/ccxt/ccxt/issues/2975 

Exchange Properties:

id: coinsuper
exchange name: Coinsuper
exchange url: https://www.coinsuper.com/
version: 2
API doc: https://github.com/coinsuperapi/API_docs_en/wiki
countries: Hong Kong

**Comment by kroitor** [comment]
Sorry for a long wait, we didn't have enough time to cover it yet. Because the other issue #2975 is still open, I suggest to move the discussion there. We don't lose track of open issues, so, it's in the line for being integrated and we will integrate it, hopefully soon. Your contributions are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
