### ISSUE TITLE
The ocean tradeId holds the transaction hash instead of the tradeId

### ISSUE THREAD

**Issue by ilesar** [ccxt/ccxt#4155]
- OS:
- Programming Language version:
- CCXT version: 1.17.491
- Exchange: The Ocean
- Method:

The current Ocean exchange implementation maps the transaction hash received from the API to the tradeId. The API response includes a unique trade id property which should be used.

The mapping change is trivial and I will change it if you agree.

https://github.com/ccxt/ccxt/blob/master/js/theocean.js#L479

https://docs.theocean.trade/#trade-history

**Comment by ilesar** [comment]
@kroitor Is there a reason for for the txHash fallback? I think it would be better to expose a separate txHash property and let the users implement the fallback in their application. With the current implementation users cannot rely on the id to be of consistent format.

**Comment by kroitor** [comment]
> @kroitor Is there a reason for for the txHash fallback?

Yep, it's there due to the fact that parseTrade is also used to parse in-order trades which have to be distinguished somehow, thus, txHash ends up as in-order trade ids.

> I think it would be better to expose a separate txHash property and let the users implement the fallback in their application.

Unfortunately, no. We can't add txHash because one exchange of 130+ exchanges has it. It will be empty in most other cases. So, we usually don't add new fields to unified structures unless it's absolutely necessary: 

- https://github.com/ccxt/ccxt/wiki/Manual#trade-structure
- https://github.com/ccxt/ccxt/wiki/Manual#transaction-structure

> With the current implementation users cannot rely on the id to be of consistent format.

You should not rely on the format of any string id coming inside unified structures, basically, users should treat it as an arbitrary string.

**Comment by ilesar** [comment]
@kroitor Thank you for the explanation. It makes sense.
