### ISSUE TITLE
Bitfinex fetchMyTrades get margin trades

### ISSUE THREAD

**Issue by milesalex** [ccxt/ccxt#4157]
Hello,

I'm having trouble finding a way to use `fetchMyTrades()` with bitfinex to fetch margin trades from their api. I know this isn't really a ccxt question, but their docs are unclear and I don't know what to add to the params object to get these trades. ANy help would be appreciated.

**Comment by kroitor** [comment]
Hi, @milesalex !

Have you tried the `fetchMyTrades`? From their docs it follows that you should be able to fetch your margin trades with that call. Let us know if that is not the case.

**Comment by milesalex** [comment]
Yes. I tried fetch my trades but it doesn't show any margin trades as poloniex does. Nothing that says margin. I also am not sure how to specify wallet type if that is needed

**Comment by kroitor** [comment]
Ok, looks like we already had the same question in #1207 (all about bitfinex margin trading):

- https://github.com/ccxt/ccxt/issues/1207#issuecomment-357154252
- https://github.com/ccxt/ccxt/issues/1207#issuecomment-367181012

Let us know if that does not answer your questions.

**Comment by milesalex** [comment]
I looked at both of those and they are in reference to `fetchBalances`, `createOrder`, but not `fetchMyTrades`. I cant seem to add the `type: 'margin'` to the params object

**Comment by kroitor** [comment]
@milesalex it turns out, you can't really fetch margin trades with Bitfinex as you do with other exchanges. 

> You don't get a list of trades, instead, you get a list of margin positions, and track your margin account info with your positions, profits and losses. Unfortunately, they don't serve a separate history of margin trades per each margin deal, afaik. Thus, the trades it makes when opening and closing your margin positions aren't distinguished and not associated with a margin or a non-margin account.

So, they don't have an endpoint for margin trades specifically, but you can probably restore that info from their v2 ledgers endpoint and order trades endpoint (for a margin order) combined together with active orders and orders history. That's easier said, than done, of course... Basically, I think their logic is: if you create a margin-type order, then, if you fetch trades for that margin order you should get a list of your margin trades (per order). This makes Bitfinex different from other exchanges that have distinguished endpoints for margin and spot trading.

**Comment by milesalex** [comment]
Ok thank you for the reply. I'll try to think of a solution.

**Comment by kroitor** [comment]
@milesalex ok, feel free to reopen it if needed or just ask further questions, if any, will be happy to help.
