### ISSUE TITLE
trades date based pagination

### ISSUE THREAD

**Issue by vsmelov** [ccxt/ccxt#4193]
I want to fetch new trades according to https://github.com/ccxt/ccxt/wiki/Manual#date-based-pagination

I specify last trade timestamp from last trade fetch, but get this last trade again.

In the example below, it looks like CCXT return trades by condition

`t >= 1542633960000`
not
`t > 1542633960000`

this is not what I need for pagination

```
2018-11-19 14:26:04,420 - run.py:97 - INFO - get 2 new trades for bitstamp fetch_trades(**{'since': 1542633960000, 'limit': 500})
2018-11-19 14:26:04,421 - run.py:98 - INFO - raw trades:
[{'amount': 0.34,
  'cost': 1749.4394,
  'datetime': '2018-11-19T13:26:00.000Z',
  'fee': {'cost': None, 'currency': 'USD'},
  'id': '77603365',
  'info': {'amount': '0.34000000',
           'date': '1542633960',
           'price': '5145.41',
           'tid': '77603365',
           'type': '1'},
  'order': None,
  'price': 5145.41,
  'side': 'sell',
  'symbol': 'BTC/USD',
  'timestamp': 1542633960000,
  'type': None},
 {'amount': 0.5302,
  'cost': 2729.686982,
  'datetime': '2018-11-19T13:26:02.000Z',
  'fee': {'cost': None, 'currency': 'USD'},
  'id': '77603369',
  'info': {'amount': '0.53020000',
           'date': '1542633962',
           'price': '5148.41',
           'tid': '77603369',
           'type': '0'},
  'order': None,
  'price': 5148.41,
  'side': 'buy',
  'symbol': 'BTC/USD',
  'timestamp': 1542633962000,
  'type': None}]
```

- OS:
vsmelov@blocktech-008:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bioni

- Programming Language version:
Python 3.6.6 (default, Sep 12 2018, 18:26:19)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux

- CCXT version:
ccxt==1.17.86

- Exchange:
any

- Method:
fetch_trades

**Comment by kroitor** [comment]
> I specify last trade timestamp from last trade fetch, but get this last trade again.

> In the example below, it looks like CCXT return trades by condition

> t >= 1542633960000
> not
> t > 1542633960000

> this is not what I need for pagination

This is exchange-specific for now, so you can just add 1 to the last trade timestamp to avoid the duplicate and fetch the *next* page of trades. Does this solve the issue for you?

**Comment by kroitor** [comment]
To clarify: the semantics meaning of `since` vs `after` is the following:
- `since` means `>=`
- `after` means `>`

Therefore the `>=` behaviour is pretty much expected and you have to adjust the timestamp upon traversing. 

Let us know if that does not answer your question or does not help. Closing it for now, if you don't mind, feel free to reopen it if needed or just ask further questions, if any.

**Comment by vsmelov** [comment]
can I specify this argument `after` instead of `since`?

**Comment by kroitor** [comment]
> can I specify this argument after instead of since?

Yes, if you think of it, it's just a basic arithmetic fact: `after = since + 1`. So you just pass `lastTradeTimestamp + 1` to `fetchTrades`. That would be the same as passing `after` instead of `since`.

**Comment by vsmelov** [comment]
Ok, i think it will work nice if this behavior is the same for all exchanges.

BTW, why in documentation  https://github.com/ccxt/ccxt/wiki/Manual#date-based-pagination
you did not mention it? It recommends to use just since=objects[-1].timestamp

**Comment by kroitor** [comment]
@vsmelov 

> Ok, i think it will work nice if this behavior is the same for all exchanges.

It should be that way, however, this aspect isn't fully unified yet, so, with some exchanges there may be some nuances. As you know, we're still under development, so, if you find any bugs, issues or inconsistencies out there – let us know, plz (just make sure to check for duplicates first, hehe).

> BTW, why in documentation https://github.com/ccxt/ccxt/wiki/Manual#date-based-pagination
you did not mention it? It recommends to use just since=objects[-1].timestamp

This is something that is currently in progress. We hope to unify this aspect soon and will add those missing details to the Manual. Basically, we didn't yet have a chance to document it to a full extent, mostly because exchanges themselves rarely bother to document it in their own docs. So, we are going to code for some auto-detection in our testing framework that would indicate the type of pagination and paging rules applied by each exchange, effectively unifying this thing completely. Tests have to be properly automated, that requires working hours... Your help is welcome, btw: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md ;)
