### ISSUE TITLE
got stuck on build

### ISSUE THREAD

**Issue by obsidianart** [ccxt/ccxt#4195]
I'm trying to build, I think I installed all the dependencies but I got stuck here

```
> ccxt@1.17.515 update-badges /Users/obsidianart/Documents/GitHub/ccxt
> node update-badges

Preparing for PyPI → ./python/README.rst (<anonymous> @ update-badges.js:12)
/Users/obsidianart/Documents/GitHub/ccxt/update-badges.js:24
let rstExchangeTableLines = match[2].split ("\n")
                                 ^

TypeError: Cannot read property '2' of null
    at Object.<anonymous> (/Users/obsidianart/Documents/GitHub/ccxt/update-badges.js:24:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

Also, I'm unclear how you can test your code (except from automated test), I assume example works if you build every time, is there something else I'm missing?

**Comment by kroitor** [comment]
> I'm trying to build, I think I installed all the dependencies but I got stuck here

This error may be related to the output format of pandoc, which depends on pandoc version. What is the version of you installation of pandoc?

```
mbp:ccxt igorkroitor$ pandoc --version
pandoc 1.19.2.1
```

With 1.19 it works fine, however, with later versions, they could have changed the output for .rst, so, in order to fix it we need to check the version of your pandoc first.

**Comment by obsidianart** [comment]
```
pandoc 2.4
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1.2, skylighting 0.7.4
```
I never heard of pandadoc before so I guess it's the latest. should I try to find and install an older version?

**Comment by kroitor** [comment]
> I never heard of pandadoc before so I guess it's the latest. should I try to find and install an older version?

Yep, this is definitely the case... It did break my builds when I updated to version 2+, so, yes, if you can, please downgrade to version 1.19. This will solve the issue with the build command. In the meantime, we will find ways of fixing the root cause, and making it work with any version of Pandoc.

Let me know if that does not help. Feel free to reopen it or just ask further questions if any. Thx!

**Comment by gthedifferentone** [comment]
Has this been fixed  ?

**Comment by kroitor** [comment]
@gthedifferentone do you have an issue with it?

**Comment by 0xsaika** [comment]
I had the same problem in macOS high sierra and solve it with downgrade pandoc to 1.19.

1. edit `"$(brew --repo homebrew/core)/Formula/pandoc.rb"` (backup if you want)
2. fix `url` column to `https://hackage.haskell.org/package/pandoc-1.19.2.4/pandoc-1.19.2.4.tar.gz`
3. fix 'sha256' hash to `5a4e56b970e59984fda8cf03c3d89ce6a100f28aa7defaf2da28f68498419902` or sha256sum of your pandoc package which suitable with your OS
4. `brew install pandoc`

There are many not working solution of "downgrade pandoc in macOS" on google search. so I want to share my way although it's not a solution of root cause. thx!

**Comment by kroitor** [comment]
@0xsaika thanks for the hints! This is very helpful! We will do our best to make it version-agnostic asap!

**Comment by abhishekr700** [comment]
Hi, this pandoc issue still persists in the latest docker image. By default, the version is 2.5

**Comment by kroitor** [comment]
@abhishekr700 we will get the docker image fixed asap, thanks!

**Comment by abhishekr700** [comment]
Is there a way to downgrade the version in the docker image ?

**Comment by kroitor** [comment]
> Is there a way to downgrade the version in the docker image ?

Yes, however, you will have to deinstall pandoc 2.5 and reinstall pandoc 1.19 manually. We will resolve this as soon as we can.

**Comment by abhishekr700** [comment]
Would it be okay if I address this in a PR?

**Comment by kroitor** [comment]
@abhishekr700 that would be awesome! Thx again!

**Comment by kroitor** [comment]
@abhishekr700 actually, the proper way to address it is to remove all rst entirely – we need to migrate to md-only. The support for RST has been added to work with https://readthedocs.org/ and to support old PyPI. The new versions of PyPI and RTD support markdown (`.md`), which is the default format that we use to generate .rst from it. So, in order to fix it we need to fix RTD and python packages to work with .md directly. Removing the `.rst` from the repo and migrating to `.md` is tricky, though. I hope to resolve this as soon as possible.

**Comment by abhishekr700** [comment]
@kroitor Got your point. But since for the time being this would allow other developers to not fall for this repeated error. I'll soon send a PR
