### ISSUE TITLE
*ToPrecision methods return strings

### ISSUE THREAD

**Issue by ErickMarlo** [ccxt/ccxt#4199]
Need add parseFloat() before return.
Thanks!

OS: OS X
Programming Language version:
CCXT version: 1.17.488
Exchange: JavaScript
Method: priceToPrecision, amountToPrecision, costToPrecision, feeToPrecision

**Comment by ErickMarlo** [comment]
Code for check it.

`
//'use strict';
const ccxt = require ('ccxt');
const l = console.log;
var exchanges = ['binance', 'bittrex', 'kucoin', 'hitbtc', 'bitfinex','poloniex','kraken','huobipro'];
e = [];

setTimeout(()=>{
	exchanges.forEach (async (x)=>{
		e[x] = new ccxt[x] () 
		await e[x].loadMarkets ()
	})
},1000)

var ss = 'ETH/USDT'

setTimeout(()=>{
	exchanges.forEach (async (x)=>{
		if(!!e[x].markets[ss]) {
			l("#",x,ss)
			let n; 
			
			n = e[x].amountToPrecision(ss,1.2345678901234567890111) 
			l('amountToPrecision', typeof n,n)

			n = e[x].costToPrecision(ss,1.2345678901234567890111)
			l('priceToPrecision',  typeof n,n)

			n = e[x].costToPrecision(ss,1.2345678901234567890111)
			l('costToPrecision',   typeof n,n)
		}
	})


},10000)
`

**Comment by kroitor** [comment]
Those methods are designed to return string-based representations of numbers, that is because some exchanges will require numbers as strings for precision reasons...

Therefore `parseFloat` is not added *inside* those methods (may be excessive in some cases) and if you want to get floats – you just add `parseFloat` on the *outside* in userland:

```
n = e[x].amountToPrecision(ss,1.2345678901234567890111) 
console.log("amountToPrecision", typeof n,n)
```

↓

```
n = parseFloat (e[x].amountToPrecision(ss,1.2345678901234567890111))
console.log("amountToPrecision", typeof n,n)
```

Hope this answers your questions, let us know if not.
