### ISSUE TITLE
Exchange timeframes

### ISSUE THREAD

**Issue by aking7** [ccxt/ccxt#422]
Is there a reason `exchange.timeframes` are stored as a `dict` of `str`? It seems they would be more useful as `int` values for the timeframe in minutes. I can of course convert... just curious.

**Comment by kroitor** [comment]
Hi, @aking7 ! Yes, the reason for having string-based keys is because for higher timeframes like 1w, 1mo, 1y these numbers will be too large. But we will look into adding the possibility to put ints there as well, hopefully soon, after we resolve current pending issues. Let me know if it answers your question or not. Thx!

**Comment by aking7** [comment]
@kroitor The keys as strings make sense! I'm curious why the values are also stored as strings.

**Comment by kroitor** [comment]
@aking7 just because for the moment we found "1d", "1y" more readable than "86400" and "31536000". There's also some ambiguity on seconds + leap years, so to keep it simple, we thought it would be better to have readable string-based keys, not numeric strings.

**Comment by aking7** [comment]
@kroitor No, sorry I must not be clear. I'm good with the keys as "1d", "1w" and think they should be kept like that :) But if I call `exchange.timeframes['1d']` it would be nice to get an integer value (in minutes or seconds for example) to use for program logic elsewhere. Right now, this outputs something different for each exchange.

**Comment by kroitor** [comment]
@aking7 oh, so you're asking of values, not the keys. The values are there to map from common key abbreviations (1m, 5m, 30m, 1h, 12h, 1d, 1M, 1y) to values accepted by the exchange engine, so those are mappings for the API. The timeframe values are for internal use, not for external applications, because values are not unified (unique for each exchange, depending on which OHLCV timeframes are supported), whereas the keys are unified.

**Comment by kroitor** [comment]
We thought making a function to map from unified abbreviations to numbers of seconds, is not a big deal, therefore we didn't include it in the lib. But we can actually make it up here.

**Comment by aking7** [comment]
@kroitor Ah, I see! I was trying to piggyback off them for my own use ;) And yes, good point on the ambiguities for larger timeframes. It's probably best I find another solution.

**Comment by kroitor** [comment]
@aking7, most of the time:
1. you need to find a common subset of timeframes (keys) across your target exchanges
2. you can compute higher timeframes from lower timeframes
My 2 cents...
