### ISSUE TITLE
[Cryptopia] createOrder fails: `InsufficientFunds` when sufficient Funds are there.

### ISSUE THREAD

**Issue by saikatharryc** [ccxt/ccxt#4224]
Hi,
I'm facing issue while trying to place the createOrder .
Trying to Buy NEO from DOGE, i'm placing Buy Order For that, with the DOGE amount. and the amount i'm placing order is slightly less than the wallet balance. 
snippet i'm using:
```
data = await cryptipia.createOrder(curMar.symbol, 'limit', 'buy', amount, curMar.data.bid);
```
Verbose Output:
```

handleRestResponse:
 cryptopia GET https://www.cryptopia.co.nz/api/GetMarket/NEO_DOGE 200 OK 
Response:

Object {Date: "Sun, 25 Nov 2018 04:03:07 GMT", Content-Type: "application/json; charset=utf-8", Transfer-Encoding: "chunked", Connection: "close", Set-Cookie: "CryptopiaLang=en; expires=Mon, 25-Nov-2019 04:03:0…", …}


 {"Success":true,"Message":null,"Data":{"TradePairId":5459,"Label":"NEO/DOGE","AskPrice":3852.87722304,"BidPrice":3781.53360000,"Low":3800.00000000,"High":4162.70999788,"Volume":4.64480891,"LastPrice":3800.00000000,"BuyVolume":2584482.98026171,"SellVolume":91.72152414,"Change":-5.00,"Open":4000.00007755,"Close":3800.00000000,"BaseVolume":18545.76763426,"BuyBaseVolume":81809.92772851,"SellBaseVolume":12406083.18755659},"Error":null} 

fetch:
 cryptopia POST https://www.cryptopia.co.nz/api/GetTransactions 
Request:

Object {Content-Type: "application/json", Authorization: "amx 000d8e0b0854469b8346f587f8xxxa1:DTohabikXnKsr…"}


 {"type":"Deposit"} 

handleRestResponse:
 cryptopia POST https://www.cryptopia.co.nz/api/GetTransactions 200 OK 
Response:

Object {Date: "Sun, 25 Nov 2018 04:03:17 GMT", Content-Type: "application/json; charset=utf-8", Transfer-Encoding: "chunked", Connection: "close", Set-Cookie: "CryptopiaLang=en; expires=Mon, 25-Nov-2019 04:03:1…", …}

....,{"CurrencyId":4,"Symbol":"DOGE","Total":887.14481966,"Available":887.14481966,"Unconfirmed":0.00000000,"HeldForTrades":0.00000000,"PendingWithdraw":0.00000000,"Address":null,"Status":"OK","StatusMessage":null,"BaseAddress":null}, ....

fetch:
 cryptopia POST https://www.cryptopia.co.nz/api/SubmitTrade 
Request:
Object {Content-Type: "application/json", Authorization: "amx 000d8e0b0854469b8346f587f806fda1:3u9NLzzFWNS4t…"}

{"Market":"NEO_DOGE","Type":"Buy","Rate":3852.87722304,"Amount":885.93034062}
handleRestResponse:
 cryptopia POST https://www.cryptopia.co.nz/api/SubmitTrade 200 OK 
Response:

Object {Date: "Sun, 25 Nov 2018 04:03:33 GMT", Content-Type: "application/json; charset=utf-8", Transfer-Encoding: "chunked", Connection: "close", Set-Cookie: "CryptopiaLang=en; expires=Mon, 25-Nov-2019 04:03:3…", …}


 {"Success":false,"Error":"ERROR: Insufficient Funds.","Data":null} 

2018-11-25T04:03:46.800Z InsufficientFunds cryptopia ERROR: Insufficient Funds.

InsufficientFunds


```

In [docs](https://support.cryptopia.co.nz/csm?id=kb_article&sys_id=a75703dcdbb9130084ed147a3a9619bc) of cryptopia for `SubmitTrade `.

in the place of RATE and Amount i think we passing the wrong values,
they said:

Rate
The rate or price to **_pay for the coins_**, e.g. 0.00000034.

Amount
The amount of **_coins to buy_**, e.g. 123.00000000.

Direct From the cryptopia support:
![screenshot 2018-11-25 at 10 55 29 am](https://user-images.githubusercontent.com/15653282/48975871-beb88f00-f0a0-11e8-9fdb-ac1eff7e3c58.png)

**NOTE: I have tried to place order of ETH/DOGE , where i will buy DOGE Worked.**

- OS: OSX
- Programming Language version: Node.js 8.10
- CCXT version: ^1.17.533
- Exchange: Cryptopia
- Method: `createOrder`

**Comment by kroitor** [comment]
> ```
> {"Market":"NEO_DOGE","Type":"Buy","Rate":3852.87722304,"Amount":885.93034062}  //when wallet balance for DOGE is 887.***
> ```

The cost of your order is 3852.87 DOGE/NEO * 885.93 NEO = 3413373.12 DOGE
So you're trying to buy 885.93 NEO for the price of 3852.87 DOGE for one NEO (total cost is 3413373 DOGE).

Do you have 3413373.12 DOGE to buy 885.93 NEO on your balance? Unfortunately, you missed the most important piece of info that should answer the question.

**Comment by saikatharryc** [comment]
so, in thiss case how do i put the order for buying NEO with 885 DOGE?
i was trying like this 
```
data = await cryptipia.createOrder(curMar.symbol, 'limit', 'buy', amount, curMar.data.bid);
```
where amount is `885 DOGE`;

**Comment by kroitor** [comment]
> so, in thiss case how do i put the order for buying NEO with 885 DOGE?
> where amount is 885 DOGE;

You have to understand the terms and use them very precisely first, for that you will have to read the Manual )

- `symbol`: `NEO/DOGE`
- `base`: `NEO` (amounts)
- `quote`: `DOGE` (prices)
- `amount` = how much `NEO` you're going to buy or sell
- `price` = how much `DOGE` you're going to pay or get for each `NEO` you buy or sell
- `cost` = `amount` * `price`

> where amount is 885 DOGE;

As you can see from the above `amount` cannot be in `DOGE` – all amounts are in `NEO` only. So we have to use common terms in order to understand each other.

Now, having the above information, how much of `NEO` **amount** do you want to buy or sell for `DOGE` and what would be your `NEO/DOGE` **price** and what would be the total **cost** of your order in `DOGE`?

**Comment by saikatharryc** [comment]
okay, so in this case, i dont have exact  this informations.
but all i have is,
`DOGE` amount, 
`bid` or `ask` price for `NEO/DOGE` market.

goal is : convert `DOGE` to `NEO`.

NOTE:
we could try calculating according to the `bid` price, what will be the `NEO` amount for the amount of `DOGE`.
but i'm not sure the `fee` for the txn will be deduct from the wallet or the converted amount?

**Comment by kroitor** [comment]
> but all i have is,
> DOGE amount,

Nope... I'm telling you that you have to be precise with terms )) You can't have an amount in DOGE (because it's a quote currency). You can only have the amount in base currency (NEO). The quote currency is always for prices and costs and is never used to represent the amount (volume) of the order. In other words, you have to be precise mathematically, according to the definitions of terms (according to the Manual) that I've posted above.

So what you wanted to say is that you have some total cost in DOGE that you want to buy NEO for.

> we could try calculating according to the bid price, what will be the NEO amount for the amount of DOGE.

This is exactly what you need to do.

- I want to spend 885 DOGE of total order cost.
- My price is bid NEO/DOGE.
- The amount of NEO I am going to buy is
  - cost = amount * price
  - 885 DOGE = X * bid
  - X = 885 DOGE / bid 

Your amount will be `885 / bid` NEO, and your price will be `bid` DOGE/NEO  and your cost will be 885 DOGE. This way you will spend all of your 885 DOGE for some amount of NEO to buy. 

> but i'm not sure the fee for the txn will be deduct from the wallet or the converted amount?

The `fees` will be deducted from your balance in *quote* currency – that is, in DOGE. It means, you will pay a bit more of DOGE for the total cost + fee.

Let me know if that does not answer your question.
