### ISSUE TITLE
Add bequant.io exchange

### ISSUE THREAD

**Issue by hems** [ccxt/ccxt#4239]
bequant.io uses the same API as hitbtc so i believe it would make sense to add them to the list of exchanges!

https://api.bequant.io/

Thank You!

**Comment by dinamic** [comment]
The website is a total ripoff from hitbtc.
Even the tiniest of details are replicated, like the system health page.

Are you sure this is not a scam?

**Comment by kroitor** [comment]
> Are you sure this is not a scam?

That's an interesting question ) You never know ) But I can say that quite a lot of exchanges have quite a lot of similarities and even copies of parts of the infrastructure or even copies of the entire infrastructure – that's quite normal, because, if I imagine correctly, exchanges do sell their engines to 3rd parties.

**Comment by dinamic** [comment]
You seem to be right. It looks like [Multiexchange](https://multiexchange.com/) is the vendor of the engine for this one.

**Comment by hems** [comment]
i think they are basically the same company, so it's not a scam.

**Comment by dandare71UK** [comment]
@kroitor is there any update on this?

**Comment by mykolasmith** [comment]
@dandare71UK @kroitor I've opened a PR ^
