### ISSUE TITLE
How to add proxy that has authentication?

### ISSUE THREAD

**Issue by vachagan-balayan** [ccxt/ccxt#4259]
I found very simple example that only adds the proxy url but no way to define the user and pass required by the proxy server. 
How do we define that?
Also is it possible to change proxy of exchange instance (for example when we find out that we are about to hit ip rate limits...)? or do we just create an exchange instance from scratch?

**Comment by kroitor** [comment]
> I found very simple example that only adds the proxy url but no way to define the user and pass required by the proxy server.
> How do we define that?

Like so: 

- https://github.com/ccxt/ccxt/blob/master/examples/py/proxy-sync-python-requests-2-and-3.py#L33

> Also is it possible to change proxy of exchange instance (for example when we find out that we are about to hit ip rate limits...)?

Yes, it is possible, because the proxy settings are re-read upon each request: 

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L425

> or do we just create an exchange instance from scratch?

Nope, you don't really want to recreate the exchange instance too often.
