### ISSUE TITLE
Slow execution time on Binance

### ISSUE THREAD

**Issue by lampardlb** [ccxt/ccxt#4341]
- OS: Windows
- Programming Language version: python
- CCXT version: 1.18
- Exchange: Binance
- Method: fetchOrderBook, createMarketBuyOrder

My program goes through 3 steps to execute an order for a given amount of quote currency:
1. fetch the order book of the trade pair;
2. calculate how much coin can be bought with my quote currency amount;
3. execute market buy order to buy the coin

I've tested on BitMEX, Bittrex, HitBTC and Binance, with rate limits on all disabled (I'm not planning to execute it frequently so no worry here). The first 3 exchanges can finish all the steps in ~0.2-0.3 seconds, but Binance needs at least 0.5-0.6 seconds, sometimes ~1.0. Could anyone shed light on why Binance is slow, and how I can improve the speed please? Thank you.

**Comment by kroitor** [comment]
> Could anyone shed light on why Binance is slow, and how I can improve the speed please?

Depends on how you test it... Measuring that sequence might produce different results, depending on how exactly you measure it. Say, if you're not caching markets between test runs, then time can vary a lot depending on the exchange in question and the preloading that takes place upon your first call to a unified method.

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

I suggest that instead of 1+2+3 sequence you make it a 1+2+3+4 sequence:
1. load markets
2. fetch orderbook
3. calculate the amount
4. create the order

And then:
- measure each step in the 1+2+3+4 sequence separately from the others
- paste your testing code here (please, make it as short as you possibly can, surround it with triple backticks (\`\`\`) for readability)
- paste your measured results

**Comment by lampardlb** [comment]
Thanks Igor, I've done the tests using 24 USDT to buy BTC, and the results are below (I've pre-loaded the mkts, so the first steps are all 0):
Bittrex:
1st step elapsed time: 0.0
2nd step elapsed time: 0.018000125885009766
3rd step elapsed time: 0.0
4th step elapsed time: 0.17299985885620117

HitBTC:
1st step elapsed time: 0.0
2nd step elapsed time: 0.04800009727478027
3rd step elapsed time: 0.0
4th step elapsed time: 0.03099989891052246

Binance:
1st step elapsed time: 0.0
2nd step elapsed time: 0.25300002098083496
3rd step elapsed time: 0.0
4th step elapsed time: 0.26799988746643066

As you can see Binance is lagging quite a bit. The codes I used are:

pair = 'BTC/USDT'
USDT_amt = 24
for ex in [bittrex,hitbtc,binance]:
    print(ex.name+':')

    # 1st step: load market;
    st = time.time()
    ex.load_markets()
    print('1st step elapsed time: ' + str(time.time()-st))

    #2st step: fetch orderbook
    st = time.time()
    orderBook = ex.fetch_order_book(pair,limit=50)
    print('2nd step elapsed time: ' + str(time.time() - st))

    # 3rd step: calculate btc amount:
    st = time.time()
    avgPrice = calcAvgPrice(orderBook['asks'], pair, amount=USDT_amt)  # selfwocalculate avg price with given quote currency amount;
    amt_prec = ex.markets[pair]['precision']['amount']  # amount precision
    btc_amount = round(USDT_amt/avgPrice,amt_prec)
    print('3rd step elapsed time: ' + str(time.time() - st))

    # 4th step: execute order
    st = time.time()
    ex.create_limit_buy_order(pair,btc_amount,avgPrice)
    print('4th step elapsed time: ' + str(time.time() - st))

**Comment by lampardlb** [comment]
just to follow up and report  the ping results: 

ping www.bitmex.com: Average: 13 ms;
ping api.binance.com: Average: 3ms;
ping api.bittrex.com: Average: 2 ms;
ping api.hitbtc.com: Average: 14ms;

So it seems that the ping response time is not necessarily related with the execution time. Any thoughts why please?

**Comment by kroitor** [comment]
> So it seems that the ping response time is not necessarily related with the execution time. Any thoughts why please?

If that is the case, then, I'm afraid, the delay is caused by the backend itself – the exchange engine in this case. So, in general, it's pretty normal for a top exchange (which is usually under a very high load) to have delays of 1-5 seconds for order placement, and there's very little we can do to influence that time, because it's on the exchanges' side, obviously.

Let me know if that doesn't answer the question... well, I know, there's very little helpful info here, but still.

**Comment by lampardlb** [comment]
Yes this answers the question, thanks @kroitor !
