### ISSUE TITLE
Bitfinex fetchOpenOrders has value from response but can't get/assign that value to a variable

### ISSUE THREAD

**Issue by peterEycyeh** [ccxt/ccxt#4357]
- OS: MacOS Mojave (10.14.1)
- Programming Language version: Javascript, node 10.13.0
- CCXT version: 1.18.36
- Exchange: Bitfinex
- Method: fetchOpenOrders

I am running ccxt for Bitfinex on my local, thus I am using https://cors-anywhere.herokuapp.com/ as a proxy. 

Everything goes well, fetchTrades, createOrder to place an order for buy and sell, or cancelOrder.
However, when I tried to get open orders(using fetchOpenOrders).
```
orders = await exchange.fetchOpenOrders(symbol, nonce);
console.log("orders = ", orders );
```

I always get an empty array form the command of console.log, (orders =  []). 
If I turn verbose to true or use inspect from browser, I can see those order that I buy or sell from createOrder function.

```
await exchange.fetchOpenOrders(symbol, nonce) <= this has value responsed
```
But
```
orders = await exchange.fetchOpenOrders(symbol, nonce); <= the response can't be assign to 'orders' variable.
```

Sorry for if this question is not good enough. But I already stuck with this for few days. I still have no idea how to deal with it. Could you please let me know if you have any idea or a hint?
Thank you so much. 

```
Access-Control-Allow-Origin: "*"
Cache-Control: "max-age=0, private, must-revalidate"
Cf-Ray: "48bb0fbfbd5dc1e0-IAD"
Connection: "keep-alive"
Content-Encoding: "gzip"
Content-Type: "application/json; charset=utf-8"
Date: "Wed, 19 Dec 2018 15:56:50 GMT"
Etag: "W/"fa4a87580d859964b311e2977549c45b""
Expect-Ct: "max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct""
Server: "cloudflare"
Strict-Transport-Security: "max-age=31536000"
Transfer-Encoding: "chunked"
X-Content-Type-Options: "nosniff"
X-Final-Url: "https://api.bitfinex.com/v1/orders"
X-Frame-Options: "SAMEORIGIN, SAMEORIGIN"
X-Request-Id: "766dcb2d-7609-4exx-a6xx-340dxxxxxxxx"
X-Runtime: "0.015196"
X-Xss-Protection: "1; mode=block"
__proto__: Object
 
 [{"id":2034613xxxx"cid":2864987xxxx"cid_date":"2018-12-15","gid":null,"symbol":"mgousd","exchange":"bitfinex","price":"0.0000xxxx","avg_execution_price":"0.0","side":"buy","type":"exchange limit","timestamp":"1544860650.0","is_live":true,"is_cancelled":false,"is_hidden":false,"oco_order":null,"was_forced":false,"original_amount":"50.0","remaining_amount":"50.0","executed_amount":"0.0","src":"api"}] 
```

**Comment by kroitor** [comment]
> orders = await exchange.fetchOpenOrders(symbol, nonce);

Can you clarify on why you have the `nonce` there and what's the value in it?

**Comment by peterEycyeh** [comment]
Thank you for your quick response.
the nonce is timestamp, I was trying to use the parameters based on bitfinext.

I remove the nonce as a props after seeing your reply.
And the value can be assigned now!

Thank you so much!!!!

Ver 1 (not properly) =>
```
nonce = Date.now().toString();
payload = {
     request: "/v1/orders",
     nonce: nonce
};

orders = await exchange.fetchOpenOrders(symbol, nonce, payload);
```

Ver 2 (not properly) =>
```
nonce = Date.now().toString();

orders = await exchange.fetchOpenOrders(symbol, nonce);
```

Present Version (work!)=> 
```
orders = await exchange.fetchOpenOrders(symbol);
```

**Comment by kroitor** [comment]
> the nonce is timestamp, I was trying to use the parameters based on bitfinext.

The second argument to fetchOpenOrders is not the current timestamp (it shouldn't be the current timestamp)... It is the `since` argument to filter orders by opening time. Read more about it here: 

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#date-based-pagination

If you're passing the current timestamp as the second argument to `fetchOpenOrders`, if will only return all orders that were opened `since` the current timestamp, during the last second basically. There were no orders older than the current timestamp for obvious reasons, so, you're getting an empty array. And if you remove `nonce` from there – you get unfiltered results. So it worked all the time, you just have to pass proper values to `since` and work with the second argument of `fetchOpenOrders` according to the Manual. Let us know if that doesn't answer your questions.

**Comment by peterEycyeh** [comment]
That is really useful and solved my issue. 
Thank you so much for your help!
