### ISSUE TITLE
Binance: Unable to retrive hishtorical data for analysis

### ISSUE THREAD

**Issue by zero-direwolf** [ccxt/ccxt#4367]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows
- Programming Language version: Python
- CCXT version: 1.17.94
- Exchange: Binance
- Method: historical data retrival

```
import ccxt
import keys

api_key, secret_key = keys.keys()

exchange = ccxt.binance({
    'apiKey': api_key,
    'secret': secret_key,
    'enableRateLimit': True
})

if exchange.has['fetchOrders']:
    exchange.load_markets()
    since = exchange.milliseconds () - 86400000
    all_orders = []
    while since < exchange.milliseconds():
        symbol = 'BTC/USDT'
        limit = 20
        orders = exchange.fetch_orders(symbol, since, limit)
        
        if len(orders):
            since = orders[len(orders) -1]
            all_orders += orders
        else:
            break

print(orders)

```
no values are returned, unable to figure out where i am going wrong.

**Comment by kroitor** [comment]
@zero-direwolf what does it say without filters in verbose mode?

```Python
exchange.verbose = True
orders = exchange.fetch_orders(symbol)
print(orders)
```

**Comment by kroitor** [comment]
@zero-direwolf well, it says, there were no orders on that market for that account, so you might want to check your keys, it's easy to mix them up... are you sure that you have the keys for the account  used for trading on that market?

**Comment by zero-direwolf** [comment]
This is a test account, i was planning to load assets once, i had a MVP

that helped a bunch..thanks 

i am still new to this can you suggest way to pull historical data from binance ?? (say from 2018-01-01 -- 2018-12-01)

**Comment by kroitor** [comment]
> This is a test account, i was planning to load assets once, i had a MVP

Did you do the orders with it? Because you can't fetch the history of your orders if you have made no orders. `fetchOrders` is used to fetch YOUR existing orders. If you need some other history, then, please, read the Manual first in order to be able to use this library efficiently: 

- https://github.com/ccxt/ccxt/wiki/Manual

> i am still new to this can you suggest way to pull historical data from binance ?? (say from 2018-01-01 -- 2018-12-01)

There's at least a couple of dozens of types of historical data, so it really depends on which type of historical data you're talking about. Anyways, I suggest that you read the entire Manual from top to bottom, because it already has the answers, and everything you might need for a start – most of the methods are explained there.
