### ISSUE TITLE
instantiating an Exchange class for theocean throws exception

### ISSUE THREAD

**Issue by nimad** [ccxt/ccxt#4384]
- OS: Windows 10
- Programming Language version:Python 3.6 64 bit
- CCXT version: 1.18.69
- Exchange: theocean
- Method: instantiating an Exchange class

the following two lines of code throws this exception: ccxt.base.errors.NotSupported: Web3 functionality requires Python3 and web3 package installed: https://github.com/ethereum/web3.py 

exchangeClass = getattr(ccxt, 'theocean')
exchange = exchangeClass()

however, for most other exchanges, this code works fine. example:

exchangeClass = getattr(ccxt, 'binance')
exchange = exchangeClass()

**Comment by kroitor** [comment]
@nimad because The Ocean is a DEX (a distributed exchange) not a conventional CEX (not a centralized exchange) – it requires web3, as most of DEX infrastructure is currently built on top of web3 and 0x – so you should basically follow the guides that the exception is telling you, and install those packages if you want to use The Ocean – you will need them anyways. Let me know if this does not answer your issue.
