### ISSUE TITLE
HitBTC2 order not found

### ISSUE THREAD

**Issue by anik-jagtap** [ccxt/ccxt#4385]
- OS: Windows 10, Ubuntu 16.04
- Programming Language version: Javascript
- CCXT version: 1.11.147
- Exchange: HitBTC2
- Method: fetchOrder()
Hi,
 I am working on HitBTC api version 2. I am facing an issue. I am placing an order with createorder() method. It is returning me the response with some id and status as closed; immediately i am calling fetchorder() method for the returned order id from createorder() method. It is returning me hitbtc2 order not found error. But when i am making the same request seperately it is returning me the order. Can you please help me with this?

**Comment by kroitor** [comment]
Yep, this is a known issue with the HitBTC v2 API – basically, they don't have an endpoint to fetch an order – instead they have two endpoints:

1. one for fetching a "recent" order (if it is open at the moment or it was closed just a moment ago)
2. and one for fetching a "historical" order (if some time has passed since it has been closed)

By default `fetchOrder` is set to work with the "historical" endpoint (2).

We have added the unified implementation of the "recent" endpoint (1) and it is called `fetchOpenOrder`.

So, what's happening in your case:

1. You create the order and it is now a "recent" order.
2. You `fetchOrder` from "historical" endpoint to see if it's there – it's not there yet, because it is still a "recent" order – therefore you get OrderNotFound.
3. If you would call `fetchOpenOrder` from the "recent" endpoint – it would be there.
4. After some time passes, the order stops being "recent" and becomes "historical", so from there you can fetch it with `fetchOrder` as you would normally do...

The issue here comes from the design of the HitBTC v2 API itself – namely, from the differentiation between a "recent" and a "historical" order – this helps balance the load on their exchange engine. But is add an inconvenience on the user side. Because you don't know beforehand, which order it is at every particular moment, what you're left with is, basically, using the "brute-force method" – check `fetchOpenOrder` first and if it's `OrderNotFound` there – then it's in `fetchOrder`, most likely. That implies two calls instead of one for checking an order, if you don't know whether it's "recent" or not, before checking it.

@anik-jagtap does that answer your question?

**Comment by kroitor** [comment]
Closing this for now if you don't mind, feel free to reopen it if needed or just ask further questions.

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/2301
