### ISSUE TITLE
PHP CCXT Errors

### ISSUE THREAD

**Issue by MixMe** [ccxt/ccxt#4406]
```
zb GET http://api.zb.cn/data/v1/markets 502 <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

- CCXT version: 1.18.84

**Comment by MixMe** [comment]
```
ccxt\ExchangeNotAvailable
bcex GET https://www.bcex.top/Api_Market/getPriceList 404 <!doctype html>
```
on fetch_markets()

**Comment by MixMe** [comment]
```
ccxt\ExchangeNotAvailable

bitkk GET http://api.bitkk.com/data/v1/markets 502 <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

on fetch_markets()

**Comment by MixMe** [comment]
```
PHP Notice – yii\base\ErrorException
Undefined variable: details
```
in /app/vendor/ccxt/ccxt/php/Exchange.php at line 1228
in /app/vendor/ccxt/ccxt/php/Exchange.php at line 1012 – ccxt\Exchange::fetch('https://c-cex.com/t/pairs.json', 'GET', [], null)

"c-cex" on fetch_markets()

**Comment by MixMe** [comment]
```
ccxt\ExchangeNotAvailable
coingi GET https://coingi.com 503 
```

**Comment by kroitor** [comment]
> ccxt\ExchangeNotAvailable
> bcex GET https://www.bcex.top/Api_Market/getPriceList 404 <!doctype html>
> on fetch_markets()

Duplicate: 
- https://github.com/ccxt/ccxt/issues/4365

Duplicates: 
- https://github.com/ccxt/ccxt/issues/2487
- https://github.com/ccxt/ccxt/issues/3363

> ccxt\ExchangeNotAvailable
> coingi GET https://coingi.com 503 

They don't have a list of markets served from their API, so, we had a scraping code that scraped the markets from their website, but since their website has changed – the exchange effectively did break itself. We won't be adding web parsers for undocumented pages anymore for that reason.
