### ISSUE TITLE
Error-classes are not defined / unnecessary defined in some exchanges

### ISSUE THREAD

**Issue by Deathamns** [ccxt/ccxt#448]
Examples:
_1broker.js, bitfinex.js, bitfinex2.js, bithumb.js, bitlish.js, bitstamp.js, bitstamp1.js, btcchina.js, cex.js, coincheck.js, coinmate.js, coinspot.js, cryptopia.js, flowbtc.js, gatecoin.js, kuna.js, quadrigacx.js, xbtce.js

For instance, [`AuthenticationError`](https://github.com/ccxt/ccxt/blob/master/js/_1broker.js#L245) is thrown in `_1broker.js`, but its definition is [missing](https://github.com/ccxt/ccxt/blob/master/js/_1broker.js#L6), so when throwing an error of this type, it will throw a regular Error object "instead".

Also in many files there are error-classes defined, but never used.

**Comment by kroitor** [comment]
@Deathamns thanks for reporting! As you may know, this library is under heavy development. There may be bugs here and there, because unification isn't an easy process. We know of those issues and we are dealing with them *just in time*, so we are going to fix them all with your help. Some bugs may have been introduced by the recent source split into separate derived classes, for example... But new fixes are added daily as well. So, if you notice bugs like that, and you feel like you want to help us to fix it, your PRs are very welcome! (Make sure to read the CONTRIBUTING doc in the root of this repo if you want to give it a try). Thx again!

**Comment by kroitor** [comment]
We imported those imports so you can now import your imports importly (since version 1.9.345+)

![imported](https://user-images.githubusercontent.com/1294454/32330578-9cc6c672-bff1-11e7-9800-ce2233691eb4.jpg)

**Comment by Deathamns** [comment]
I wanted to send a pull request, but I couldn't decide what should I do. Only add the missing variables (since I saw that you usually included a few but didn't used them), add them all, or add only the ones that are used? So, I left the decision to you instead...

But, I see you left the variables that are actually used, so [here](https://github.com/ccxt/ccxt/pull/450) you go (you also missed bitfinex2).

These kind of issues (and many other types) could be easily detected with eslint. I see that the project has an `.eslintrc` file, however it's kind of empty. It would be helpful if someone could fill it with rules that needs to be followed for this project. It would help finding errors and following the coding style as well.
