### ISSUE TITLE
fetchMarkets() for coinbase returns false

### ISSUE THREAD

**Issue by ceaser1996** [ccxt/ccxt#4490]
Whenever I am trying to fetch markets using fetchMarkets() it's giving active is false . Sometimes it's giving true and sometimes it's giving false.
In old versions ccxt it's producing the correct data. Please fix the issue 
- OS:
- Programming Language version:PHP 7.2
- CCXT version:1.18.120
- Exchange:coinbase pro
- Method: public

**Comment by ceaser1996** [comment]
$accessible = $this->safe_value($market, 'accessible');
$active = ($market['status'] === 'online') && $accessible;
*this accessible is always return false .
Why?

**Comment by kroitor** [comment]
@ceaser1996 

> Why?

It's a bug, that was introduced here: #4440. I fixed it in 1.18.122. Let us know if you still have difficulties with after upgrading to most recent version.

**Comment by kroitor** [comment]
> too much of unstablity in code ?

Nope, just the usual open-source process of development. Just the right amount of instability in code ;))

> Is there any stable version available?

No, there isn't... This entire library is a work in progress, we add new features, bugfixes and patches every day. So, when someone finds a bug – we fix it and a new version is rolled out. Thus each new version will have less and less bugs. There's no such thing as "stable" and "dev" versions in our process, because exchanges add changes on the fly.

**Comment by ceaser1996** [comment]
Thanks a lot.

**Comment by ceaser1996** [comment]
Still it is returning all values as null

**Comment by kroitor** [comment]
@ceaser1996 the version 1.18.122 has not arrived yet, it will arrive in 5-10 minutes from now. Please retry **after** upgrading to 1.18.122. Will let you know once it's there.

**Comment by kroitor** [comment]
@ceaser1996 ok, 1.18.122 is available for downloading now, so if you upgrade and retry – it should work normally from there. Let us know if you still have difficulties with after upgrading.

**Comment by ceaser1996** [comment]
#4440. bug came again .

**Comment by kroitor** [comment]
@ceaser1996 do you mean, you have the same bug after upgrading to 1.18.122?

**Comment by ceaser1996** [comment]
yes

**Comment by ceaser1996** [comment]
$ticker = $this->publicGetProductsIdTicker ($request);
        $timestamp = $this->parse8601 ($ticker['time']); //line no 236


Undefined index: time {"exception":"[object] (ErrorException(code: 0): Undefined index: time at /var/www/html/cryptosig/vendor/ccxt/ccxt/php/gdax.php:236)

**Comment by ceaser1996** [comment]
is anybody there to help me out

**Comment by ceaser1996** [comment]
my every cron job is getting failed .

**Comment by kroitor** [comment]
> is anybody there to help me out

Yes, however, in order to help you, we need you to follow precisely the rules from here (literally to a word): 

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

No need to do this:

```PHP
$ticker = $this->publicGetProductsIdTicker ($request);
$timestamp = $this->parse8601 ($ticker['time']); //line no 236
```

The proper way to do this:

```PHP
$exchange = new \ccxt\gdax (array (
    'enableRateLimit' => true, // required by the Manual
));

try {

    $symbol = 'ETH/BTC';
    $result = $exchange->fetch_ticker ($symbol);

    var_dump ($result);

} catch (\ccxt\NetworkError $e) {
    echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
    echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}

?>
```

**Comment by ceaser1996** [comment]
I am not getting any proper way to fix it

**Comment by kroitor** [comment]
> I am not getting any proper way to fix it
> May I know any proper reason behind this?
> Is this can be fixed from your side as in .220 build of ccxt this got fixed

I suggest that we start with this simple example: https://github.com/ccxt/ccxt/blob/master/examples/php/gdax-fetch-ticker.php

Does it work for you? Anyways, copy the entire output of it and paste it here.

**Comment by ceaser1996** [comment]
```  if ($tried > 2) {
            \Log::warning("SAVEMARKETS - tried 3 times for exchange $exchangeId and market - " . $fetchedMarket['base']);
            return;
        }
        \Log::info("FetchedMarkets".json_encode($fetchedMarket));
        if (isset($fetchedMarket['active'])) {
            $active = ($fetchedMarket['active'] === true) ? config('constants.bittrex.active') : config('constants.bittrex.inactive');
        } else {
            $active = config('constants.bittrex.active');
        }

        $marketCurrency = ['symbol' => $fetchedMarket['base'], 'name' => ''];
        $baseCurrency = ['symbol' => $fetchedMarket['quote'], 'name' => ''];



            if ($market !== null) {
                $market->is_active = $active;
                $market->save();
                \Log::info("true".$active);
            }
            return;
        }

        if ($ticker === null) {
            try {
                $ticker = $exchange->fetchTicker($fetchedMarket['symbol']);
                if (empty($ticker)) {
                    return;
                }
            } catch (\ccxt\DDoSProtection $ex) {
                sleep(1);
                $tried++;
                rvar_dump($exchangeId, $exchange, $fetchedMarket, $tried, $ticker);
            } catch (\ccxt\RequestTimeout $ex) {
                sleep(1);
                $tried++;
                return self::marketJob($exchangeId, $exchange, $fetchedMarket, $tried, $ticker);
            }
        }
```

**Comment by kroitor** [comment]
You seem to be using the testing sandbox of coinbasepro/GDAX which is not guaranteed to work at all.

**Comment by ceaser1996** [comment]
by using sandbox I am just testing the functionality. It doesn't infer the updation of markets right ?

**Comment by kroitor** [comment]
> It doesn't infer the updation of markets right ?

Wrong: `not guaranteed to work at all.`

> What is the alternative way of doing the same as presently I am working on my dev server which I mainly use for testing and few days ago the code was working fine and even I was getting the proper output of data.

If you can paste a snippet of 5-20 lines making a complete program to reproduce the issue – then we will be able to debug it. Unfortunately, I can't even launch the snippet you posted above, because it's incomplete and it's too large (contains too much of code that is not relevant to the issue you've encountered). So, I need you to make it the smallest possible, but a complete program. Like the one I pasted here: https://github.com/ccxt/ccxt/blob/master/examples/php/coinbasepro-sandbox-fetch-ticker.php . This example shows how to fetch the ticker from coinbasepro sandbox. It works on my side with CCXT 1.18.122, does it work on your side as well? If not, we will need you to paste the output of it here.

**Comment by ceaser1996** [comment]
hey !!
I just did some debugging and I found there are only two pairs which are throwing " Undefined index: time" Error.

Below is my code:
```
$coinbasePro=new \ccxt\gdax;

$coinbasePro->fetch_ticker('MKR/USDC'); // Error: Undefined index: time
$coinbasePro->fetch_ticker('ZIL/USDC')); // Error: Undefined index: time
```
I found that these symbols have Undefined Index Time . Due to these symbols, it is causing the error.
Except for these two symbols all working fine.
