### ISSUE TITLE
Some Symbols Of Coinbase Are returning Undefined Time Index

### ISSUE THREAD

**Issue by ceaser1996** [ccxt/ccxt#4494]
hey !!
I just did some debugging and I found there are only two pairs which are throwing " Undefined index: time" Error.

Below is my code:
```
$coinbasePro=new \ccxt\gdax;

$coinbasePro->fetch_ticker('MKR/USDC'); // Error: Undefined index: time
$coinbasePro->fetch_ticker('ZIL/USDC')); // Error: Undefined index: time
```
I found that these symbols have Undefined Index Time . Due to these symbols, it is causing the error.
Except for these two symbols all working fine.
*Please do update me at your earliest.

- OS: Ubuntu 16.04
- Programming Language version: Php7.2
- CCXT version:1.18.125
- Exchange: Coinbase

**Comment by kroitor** [comment]
@ceaser1996 i've added this example (with a few modifications to it), so that if you launch it – it should tell you the cause:

- https://github.com/ccxt/ccxt/blob/master/examples/php/gdax-sandbox-fetch-ticker.php

Let us know if that example does not answer your questions. In short, they don't serve those two markets from their API. More about it here: 

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#market-structure

Related issue: #4490
