### ISSUE TITLE
OKEX how to get depth data

### ISSUE THREAD

**Issue by liuhuanshuo** [ccxt/ccxt#4498]
ATTENTION!!!

- OS: macos
- Programming Language version:python3.6
 I try to use:
`okex.fetchOrderBookr('BTC/USD', {'contract_type': 'this_week'})`
it says :'okex' object has no attribute 'fetchOrderBookr'

then i try to use:
`params = {
    'contract_type': 'next_week', # this_week, next_week, quarter
}
okex.fetch_ohlcv(futures_market['symbol'], timeframe, since, limit, params)
`

it got error :name 'futures_market' is not defined

why?

**Comment by kroitor** [comment]
> it says :'okex' object has no attribute 'fetchOrderBookr'

There's no such method called `fetchOrderBookr`. The actual method is `fetchOrderBook`, it's a typo in your code. Pay more attention to every character. More about it in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#order-book

See these examples:

- https://github.com/ccxt/ccxt/tree/master/examples/py

> it got error :name 'futures_market' is not defined
> why?

Because you don't have the variable `futures_market` properly defined in your code as the error says. It's again more a syntactic error in your code than an issue with CCXT. See the examples and the Manual on how to use it properly.

Hope that answers your questions.
