### ISSUE TITLE
question: calculateFee

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4506]
Regarding the JS version of calculateFee...

1. There appear to be two unused parameters (`type` & `params`), is that right (or is it a bug)?
2. The `cost` value in the returned object is always in the quote currency, correct?  
3. What is the behaviour if the trade fee (taker or maker) is undefined?

**Comment by kroitor** [comment]
> There appear to be two unused parameters (type & params), is that right (or is it a bug)?

Not a bug – those two are reserved as they might be required in order to determine the fee side correctly. 

>  The cost value in the returned object is always in the quote currency, correct?

Nope. Depending on exchanges' fee schedule It can be either of:
- always quote currency
- always base currency
- always the currency you get (depending on whether you're buying or selling)
- always the currency you give as a result of the trade
- custom

More about it here: https://github.com/ccxt/ccxt/issues/3261#issuecomment-401604350

> What is the behaviour if the trade fee (taker or maker) is undefined?

If taker and maker fee isn't defined and isn't served from the fetchMarkets endpoint or from at least some endpoint – we can't make it out of nothing, so, in that case those two fields will be missing (undefined) on the market and the behavior of calculateFee is therefore also undefined.

Let us know if that does not answer your questions.

**Comment by npomfret** [comment]
Thanks!

> Depending on exchanges' fee schedule It can be ...

So each exchange can override the method in order to provide exchange specific behaviour?  Or is it done declaratively?
