### ISSUE TITLE
Poloniex fetchMyTrades Bitmark symbol quote/base inversion

### ISSUE THREAD

**Issue by TotallyKyle** [ccxt/ccxt#4509]
- OS: Windows 
- Programming Language version: JS
- CCXT version: ccxt@1.18.133
- Exchange: Poloniex
- Method: fetchMyTrades

The symbol pair is normally quoted/base pairing for example EOS/BTC. However, Bitmark trades from poloniex show up as BTC/Bitmark which is the reverse pairing. I understand that Bitmark is spelled out fully due to conflicts with Bytom.

For example: 
```
{
    "timestamp": 1492261369000,
    "datetime": "2017-04-15T13:02:49.000Z",
    "symbol": "BTC/Bitmark",
    "id": "257012",
}
```

**Comment by TotallyKyle** [comment]
Also an issue with SDC, BLK, EMC2, SJCX, FLT, DAO, etc...

Possible fix is whenever BTC appears in the pairing, we fix it to base currency unless it is with a fiat currency?

**Comment by kroitor** [comment]
Polo doesn't serve Bitmark anymore:

- https://www.chepicap.com/en/news/3768/poloniex-to-delist-8-coins-on-september-25th.html

I don't see Bitmark here either:

- https://poloniex.com/public?command=returnCurrencies

> Possible fix is whenever BTC appears in the pairing, we fix it to base currency unless it is with a fiat currency?

Unfortunately, not, because in most cases we can't decide for the exchange which currency is base and which is quote. We could probably think of a workaround if you could post your verbose request/response for `fetchMyTrades` as described here: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ

Hope this answers your questions, let us know if not.
