### ISSUE TITLE
.fetchTrades problems with since argument

### ISSUE THREAD

**Issue by nikolasharing** [ccxt/ccxt#4513]
- OS: Windows
- Programming Language version: Python 3.7
- CCXT version: newest
- Exchange: kraken (but others too)
- Method: .fetchTrades

The .fetchTrades method seems to be unresponsive to changes in the "since" parameter value? This wasn't a problem yesterday morning.

`import ccxt

exchange = getattr (ccxt,'kraken') ()
print(exchange.fetchTrades('BTC/EUR',0,1))`

**Comment by kroitor** [comment]
Kraken never did support time-based pagination with `since`... Their API endpoint for public trades (`fetchTrades`) doesn't accept that parameter and ignores it. This has been so from the very beginning. Kraken will only support id-based pagination for public trades which you can use by passing the since param override to `fetchTrades`:

- https://www.kraken.com/en-us/help/api#get-recent-trades
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#trades-executions-transactions

```Python
from pprint import pprint
import ccxt
exchange = ccxt.kraken({'enableRateLimit':True})  # rate limiter is required by the Manual
params = {
    'since': last_trade_id,  # the id of the trade you want to fetch from, not a timestamp
}
pprint(exchange.fetch_trades('BTC/EUR', None, None, params))
```

Hope this answers your question.
