### ISSUE TITLE
since not working in fetchMyTrades() on Poloniex

### ISSUE THREAD

**Issue by robertwilliamallen** [ccxt/ccxt#4522]
- OS: macOS Mojave 10.14
- Programming Language version: Python 3
- CCXT version: 1.18.42
- Exchange: Poloniex
- Method: fetchMyTrades

Trade results are most recent and do not start from `since`. For example, I am passing `since=1485045230000` (2017-1-22 in milliseconds) with `limit=300` and the first entry in the returned trades `trades[0]` is from `2018-12-19`.

**Comment by kroitor** [comment]
If you look here: https://github.com/ccxt/ccxt/blob/master/python/ccxt/poloniex.py#L535 and browse the Poloniex docs, you will notice that Poloniex requires both the starting date and the end date, and in CCXT the end date is set to current timestamp. However, if you override the starting date, the ending date still remains the current timestamp. In that case Poloniex will look into the history itself, and if there's more than 1000 trades – it won't return your entire history, instead, it will only return most recents trades, So, Polo returns most recent trades starting from 2018-12-19 and you get the first 300 of those... 

If you could post your code and verbose output – we would be able to verify this. 

```Python
# ↓ this is what we expect to actually get from you instead of writing this here for you )
import ccxt
exchange = ccxt.poloniex({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
exchange.load_markets()
exchange.verbose = True
symbol = 'ETH/BTC'
since = 1485045230000
limit = 300
params = {}
exchange.fetch_my_trades(symbol, since, limit, params)
```

↑ We need to see your verbose output (without your keys).

In order to resolve the issue, if you want to traverse your Poloniex history, you should specify both the starting date and the ending date making it a narrow-enough period for Poloniex to tolerate your request.

```Python
symbol = 'ETH/BTC'
since = 1485045230000
limit = 300
params = {}
days = 10
params = {
    'end': int(since/1000) + 24 * 60 * 60 * days,  # you can only specify this in a params-override
}
exchange.fetch_my_trades(symbol, since, limit, params)
```

Standing by for a followup on this from you.

**Comment by robertwilliamallen** [comment]
Okay, I can confirm that using the 'end' param worked. Perhaps this would be something worth adding to the docs?

**Comment by kroitor** [comment]
@robertwilliamallen yep, will add some note and clarifications on that! Thx for the feedback!
