### ISSUE TITLE
Kraken darkpool

### ISSUE THREAD

**Issue by cod3gen** [ccxt/ccxt#4572]
On Kraken there is a "darkpool" feature which adds .d on some markets, I see there is support for this in CCXT, but would it not be more convenient that symbols are arranged as "ETH/XBT.d" instead of current "string(8) "ETHXBT.d""? I noticed this because my script is based on parsing through markets by splicing "/" which resulted in crash on kraken since there is no separation.

**Comment by kroitor** [comment]
> my script is based on parsing through markets by splicing "/" which resulted in crash on kraken since there is no separation

This is exactly the reason, why it is **highly discouraged** in the Manual for the user to try and parse those symbols. You should really treat them as atomic strings (unbreakable/unspliceable).

![screen-shot-2019-01-29-at-19 04 42](https://user-images.githubusercontent.com/1294454/51921673-e9082f00-23f8-11e9-88a3-8bf609613e88.jpg)

Examples of how a symbol might look like are also given in the Manual:

<img width="1059" alt="screen shot 2019-01-29 at 19 06 55" src="https://user-images.githubusercontent.com/1294454/51921752-1523b000-23f9-11e9-96cf-d489ed071d48.png">

- `'ETH/BTC'` is a symbol
- `'f.o0Obar/HelloWrold!'` is also a symbol
- `___$@#*&^(#()!` is a symbol as well )

Instead of trying to splice the symbol, you should use the `base`, `quote`, `baseId` and `quoteId` properties of the market (those contain the "spliced" parts you want already). 

For that you want to read how to use markets and how to access them by symbols and ids properly (as documented in the Manual ;)).

> would it not be more convenient that symbols are arranged as "ETH/XBT.d" instead of current "string(8) "ETHXBT.d""?

No, it makes no sense, because it doesn't work universally for all exchanges – for example: https://github.com/ccxt/ccxt/issues/3540#issuecomment-409579588

Hope that answers your question.
