### ISSUE TITLE
kraken - fetchTrades id missing but in last trade

### ISSUE THREAD

**Issue by stabilus** [ccxt/ccxt#4617]
- OS: Win 7 64
- Programming Language version: python 3.6
- CCXT version:  1.18.195
- Exchange: kraken
- Method: fetchTrades()

fetchTrades() returns list of trades. The id of all trades is None except for the last trade in the list which correctly contains the trade id.

Note that apparently the id value is already missing in info. I suspect that there is an error in parsing the response from Kraken.

exchange = ccxt.kraken()
print(exchange.fetchTrades('BTC/USD'))

excerpt of list received:
[ ..., , {'id': None, 'order': None, 'info': ['3365.00000', '0.75096575', 1549475287.0071, 'b', 'l', ''], 'timestamp': 1549475287007, 'datetime': '2019-02-06T17:48:07.007Z', 'symbol': 'BTC/USD', 'type': 'limit', 'side': 'buy', 'price': 3365.0, 'amount': 0.75096575, 'cost': 2526.99974875, 'fee': None}, {'id': None, 'order': None, 'info': ['3364.70000', '0.19000000', 1549475344.5196, 's', 'l', ''], 'timestamp': 1549475344519, 'datetime': '2019-02-06T17:49:04.519Z', 'symbol': 'BTC/USD', 'type': 'limit', 'side': 'sell', 'price': 3364.7, 'amount': 0.19, 'cost': 639.293, 'fee': None}, {'id': '1549475389577490913', 'order': None, 'info': ['3365.00000', '0.01109800', 1549475389.5775, 'b', 'm', '', '1549475389577490913'], 'timestamp': 1549475389577, 'datetime': '2019-02-06T17:49:49.577Z', 'symbol': 'BTC/USD', 'type': 'market', 'side': 'buy', 'price': 3365.0, 'amount': 0.011098, 'cost': 37.344770000000004, 'fee': None}]

**Comment by kroitor** [comment]
> The id of all trades is None except for the last trade in the list which correctly contains the trade id.

That's right. And that correctly corresponds to the Kraken docs.

> Note that apparently the id value is already missing in info. I suspect that there is an error in parsing the response from Kraken.

That isn't an error. That is actually to be designed that way. Kraken docs say that their trades endpoint will return the id of the last trade, so that you could use that for further filtering. 

- https://www.kraken.com/en-us/features/api#get-recent-trades 

You would put that id into your next request to filter new trades from the ones you've received already. The concepts of pagination are also partially explained here: 
- https://github.com/ccxt/ccxt/wiki/Manual#pagination

However, the unified API of CCXT returns an array in response to the user, so, that id is taken from the Kraken response and is put into the last trade.

Let us know if that doesn't answer the question.

**Comment by stabilus** [comment]
got it, thanks!
