### ISSUE TITLE
BigOne Precision

### ISSUE THREAD

**Issue by oleg619** [ccxt/ccxt#4677]
Hello.
Why do you think what limit calculate by function POW base 10 with precision?
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
> Why do you think what limit calculate by function POW base 10 with precision?

This is the smallest value you can get with that precision. The next smallest value within that precision is 0. Which is a bad amount for an order. So it has to be some atomic value greater than zero. And if the exchange doesn't specify a precise limit – then deriving it from precision is the closest we can get. 

The actual limit might be higher than the smallest precision value (in that case the user will get an exception that could be properly handled), but it cannot be lower than that.

If we missed a place where they specify their limits in their API – that's most likely because we are a work in progress, so, if you see an inconsistency, please let us know. Your contributions are also very appreciated: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Let us know if that does not answer the question. Thx!
