### ISSUE TITLE
Bitmex - Open order time

### ISSUE THREAD

**Issue by mattou78400** [ccxt/ccxt#4683]
Hi,

I am trying to pull the length of time a position has been running on bitmex.

Problem is, the openingTimestamp is wrong, and always is the start of the current hour.

Anyone figured out something like that? thanks a lot!

**Comment by hroff-1902** [comment]
Can you provide some bunch of code to reproduce the problem?

I'm also trying to use ccxt with same exchange, BitMEX; there are lots of more or less significant issues with it...

**Comment by mattou78400** [comment]
Just simply open a position on bitmex, and do the classic 
bitmex.private_get_order()

This will give you the detail of your open order, but impossible to get the actual opening time of the position. That's what I'm looking for

**Comment by hroff-1902** [comment]
Bitmex API explorer suggests "See the FIX Spec for explanations of these fields."
(see Implementation Notes in https://testnet.bitmex.com/api/explorer/#/Order)

The referenced "FIX Spec" (see https://www.onixs.biz/fix-dictionary/5.0.SP2/msgType_D_68.html) says: 

TransactTime | Y | Time this order request was initiated/released by the trader, trading system, or intermediary.

I guess that's the data you are looking for.

ccxt's privateGetOrder() (private_get_order()) returns exchange data without any modifications, as I understood, as any other private* or public* method...

**Comment by kroitor** [comment]
@hroff-1902 thanks for your help on this issue! )
@mattou78400 let us know if that doesn't answer the question )

**Comment by mattou78400** [comment]
Hi,

Thank you all for your help, unfortnuately, being a bit novice (even at python), I have no idea how to use the information given by hroff-1902

> TransactTime | Y | Time this order request was initiated/released by the trader, trading system, or intermediary.

How do I call that from python?

Thanks a lot!

**Comment by hroff-1902** [comment]
Umm, you told you are using private_get_order(). It returns response from the exchange. Something like this:
```
response = bitmex.private_get_order(params)
```
Structure of the response is described at the BitMEX API, see https://testnet.bitmex.com/api/explorer/#!/Order/Order_getOrders

So something like
`response[0]['transactTime']`
or
`response[0]['timestamp']`
will give you timestamp of the requested order.

The 'timestamp' field is returned by the fetch_order()/fetch_orders() methods in the ccxt's Unified API, so I can suggest you use it instead of private_get_order(). See https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints for details and read python/ccxt/bitmex.py in order to find out of how it's implemented.

**Comment by kroitor** [comment]
@mattou78400 please read this: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
I'd recommend to read the entire Manual from top to bottom – it has all the answers in it, and it will save you tons of time, trust me )

@hroff-1902 thx again for your help!

**Comment by mattou78400** [comment]
Hi all,

Thanks a lot for your help, unfortunately it doesn't help, but I think it's a "problem" on Bitmex's side. I don't think they make the opening time of a position available, and the opening time of past orders seems to have a few days lag, hence not suiting my case...

I'll find another way, meanwhile if anyone has other workarounds, I'm more than happy to hear them.

Thank you all!

**Comment by hroff-1902** [comment]
Wait a moment. If you are talking about position, that's another BitMEX API function, privateGetPosition(), not the privateGetOrder()...
See https://testnet.bitmex.com/api/explorer/#!/Position, it has the "openingTimestamp" field...

**Comment by mattou78400** [comment]
> @mattou78400 Wait a moment. If you are talking about position, that's another BitMEX API function, privateGetPosition(), not the privateGetOrder()...
> See https://testnet.bitmex.com/api/explorer/#!/Position, it has the "openingTimestamp" field...

Yes, but this "openingTimestamp" is actually the session's opening timestamp, hence it always displays the start of the current hour, not the timestamp the positions was opened at, unfortunately... :(

**Comment by hroff-1902** [comment]
> > @mattou78400 Wait a moment. If you are talking about position, that's another BitMEX API function, privateGetPosition(), not the privateGetOrder()...
> > See https://testnet.bitmex.com/api/explorer/#!/Position, it has the "openingTimestamp" field...
> 
> Yes, but this "openingTimestamp" is actually the session's opening timestamp, hence it always displays the start of the current hour, not the timestamp the positions was opened at, unfortunately... :(

Yeah, I see, I thought it's the position opening timestamp... So the only way is to iterate through previously completed, closed orders... And through partially open orders since when an order is still open partially, the position is also open...

By the way, there is an interesting case. Suppose you opened a long position for an instrument, say, for 100 contracts 20 minutes ago. Then, 10 minutes ago you placed a 'sell' order which completed immediately, for 200 contracts. The position is now -100 or 100 'short'. What one should say about the position opening time now -- 10 minutes (because one can treat it as the long position was closed 10 minutes ago and a new one, short position, was opened at the same time) or 20 minutes ago? Can be treated differentely by different exchanges, traders or library developers...

@kroitor This case btw is also for you to be taken into account during unification of the exchange position interface in the ccxt...

**Comment by kroitor** [comment]
@hroff-1902 noted! thx!

**Comment by mattou78400** [comment]
> Yeah, I see, I thought it's the position opening timestamp... So the only way is to iterate through previously completed, closed orders... And through partially open orders since when an order is still open partially, the position is also open...

I'll check this out... though to be honest, only the "filled" ordStatus seems relevant though there's either a few days lag, or as we discussed, no way of getting a porper timestamp.

Workarounds I'm working on:
1 - Have a csv file record whenever the open position changes
2 - Look for how long ago was the "opening price" reached

But I have to say, both look much more hacky than I'd like :D

Thanks a lot for your help, I'll post something if I find more :)

**Comment by hroff-1902** [comment]
You may look at the official bitmex res client, bitmex market maker (https://github.com/BitMEX/sample-market-maker). It implements only one strategy -- market making, but contains the whole set of functions to talk to Bitmex, including gathering data for orders, tickers, ohlcv, etc, closing the position at the end (if I added it by myself? do not remember...) and so long... I locally modified it so that I could insert custom strategies written with numpy, pandas and ta-lib there... Not published it yet, maybe some days... At least that bot is a good starting point, and it implements websocket (WS) interaction as well besides Rest API...
