### ISSUE TITLE
Problem running docker-compose for local tests (using current master branch)

### ISSUE THREAD

**Issue by hroff-1902** [ccxt/ccxt#4686]
Ubuntu 18.04 LTS.

Clean run of `docker-compose` after `docker system prune -a`.

See attachment (too long to paste):

[aaa.txt](https://github.com/ccxt/ccxt/files/2876764/aaa.txt)

**Comment by xpl** [comment]
@hroff-1902 From your log, it seems that the container image has been built just fine! Those errors when building the image are irrelevant:

```
byte-compiling build/bdist.linux-x86_64/egg/ccxt/async_support/jubi.py to jubi.pyc
  File "build/bdist.linux-x86_64/egg/ccxt/async_support/jubi.py", line 30
    async def fetch_markets(self, params={}):
            ^
SyntaxError: invalid syntax
```

Also, when building the container, it does not execute the tests, it only installs all the required dependencies. So after you get to the container's shell, you can execute the `npm run build` to build the sources, and then (for running the tests for various languages):

```
node run-tests --js
```
```
node run-tests --python2
```
```
node run-tests --python3
```

I also just changed the `run-tests` behavior a bit in f6de83d629e2bc0e478a9d93309983c0944e2749, so that it does not burn the CPU too hard — so please update.

**Comment by hroff-1902** [comment]
@xpl thanks, спасибо. 

I would never thought it'all right, so many errors in red...
(I've got an error with running `npm run build` in docker so decided the reason was in the failed docker-compose). Thanks, now I got the right sequence of actions I guess.
 
Documentation should be adjusted in some more details...

**Comment by xpl** [comment]
> I would never thought it'all right, so many errors in red...

It is seems that the `python setup.py install` command in our `Dockerfile` doesn't like the `async_support` folder (which is Py3) — that doesn't prevent the build from succeeding, but confuses people. Need to find a way to make the Py2 install ignore that folder...

**Comment by xpl** [comment]
@hroff-1902 Should be no errors now.

**Comment by hroff-1902** [comment]
@xpl Thanks, I'll repeat the actions on my next PR and verify.
