### ISSUE TITLE
advice on error handling (coinbasepro improvement)

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4740]
coinbasepro currently throws an `ExchangeError` when cancelling an already cancelled order.  I think it would be improved if it throw an `OrderNotFound` error (as I believe some other implementations do).  

@kroitor - do you have any advice, or do you have a good example on how to implement this properly?  The response has a 400 status code and a body with an error message:

```
fetch:
 coinbasepro DELETE https://api.pro.coinbase.com/orders/528725347 
Request:
 { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
  'CB-ACCESS-KEY': '403b4cd50cc52d8320bc711d26888bac',
  'CB-ACCESS-SIGN': 'vgpVFDBtWl9JXW72plnEZw4DiS3T+Um3n1nDsaS/tC4=',
  'CB-ACCESS-TIMESTAMP': '1551003406',
  'CB-ACCESS-PASSPHRASE': 'hlacrixe8ul',
  'Content-Type': 'application/json' } 
 undefined 

handleRestResponse:
 coinbasepro DELETE https://api.pro.coinbase.com/orders/528725347 400 Bad Request 
Response:
 { Date: 'Sun, 24 Feb 2019 10:16:46 GMT',
  'Content-Type': 'application/json; charset=utf-8',
  'Content-Length': '30',
  Connection: 'close',
  'Set-Cookie': '__cfduid=da2aa34ae78f5ee1eaef1fbdb02915d9d1551003406; expires=Mon, 24-Feb-20 10:16:46 GMT; path=/; domain=.pro.coinbase.com; HttpOnly',
  'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp',
  'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr',
  'Access-Control-Max-Age': '7200',
  'Cache-Control': 'no-store',
  Etag: 'W/"1e-jtBpYXwiagh6JcjFc50t32rmn/s"',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains',
  'X-Content-Type-Options': 'nosniff',
  'X-Dns-Prefetch-Control': 'off',
  'X-Download-Options': 'noopen',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Xss-Protection': '1; mode=block',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '4ae12db8fb9e6b9d-LHR' } 
 {"message":"Invalid order id"} 


```

**Comment by npomfret** [comment]
Ignore this.  Found it.

Question is though, what _should_ the exception be?  OrderNotFound or InvalidOrderId

**Comment by kroitor** [comment]
> Question is though, what _should_ the exception be? OrderNotFound or InvalidOrderId

We suggest to keep it semantically close to the exchange error message, so, if the exchange says "invalid order id", then we would throw an `InvalidOrder` exception.

**Comment by npomfret** [comment]
Hmm, ok - but that can lead to ccxt inconsistencies, no?

**Comment by kroitor** [comment]
> Hmm, ok - but that can lead to ccxt inconsistencies, no?

Well, not really, because we are talking of order canceling here. In general, when you're canceling an order and the cancelation fails, this could be due to one of the following reasons:

1. either there was no such order with the id you specified, in the first place (the order wasn't open or didn't exist) – in this case the exchange will throw `InvalidOrder` or `OrderNotFound`
2. or it was an existing order, and it has already been canceled or closed, in this case the exchange might also throw `InvalidOrder` or `OrderNotFound`. Some exchange may throw a message that allows to distinguish between the two types of exceptions, others just throw one single exception type for all errors of this kind.

Also, the `OrderNotFound` is a more specific subtype of `InvalidOrder`, that's why `OrderNotFound` is derived from `InvalidOrder`.

So, if you take the above and put into code:

```JavaScript
try {
    const response = await this.createOrder (...
} catch (e) {
    if (e instanceof ccxt.InvalidOrder) {
        // could not place the order, fall back to error handling
    }
}

try {
    const response = await this.fetchOrder (...
} catch (e) {
    if (e instance of ccxt.OrderNotFound) {
        // the order does not exist
    } else if (e instanceof ccxt.InvalidOrder) {
        // the order does not exist or some other error happened
    } else {
        // ...
    }
}

try {
    const response = await this.cancelOrder (...
} catch (e) {
    if (e instance of ccxt.OrderNotFound) {
        // the order does not exist or was already canceled
        // ...
    } else if (e instanceof ccxt.CancelPending) {
        // the order does exist and is being canceled already
    } else if (e instanceof ccxt.InvalidOrder) {
        // the order does not exist or was already canceled
        if (weHaveSeenThisOrderPreviously) {
            // already canceled most likely
        } else {
            // handle this
        }
    } else {
        // ...
    }
}
```

↑ How you chain those `ifs` and error handlers depends on the logic and design of your application.

Let me know if that does not answer your question.

**Comment by npomfret** [comment]
Understood.  Thanks
