### ISSUE TITLE
Which language is the most comprehensive for CCXT

### ISSUE THREAD

**Issue by smogili1** [ccxt/ccxt#4745]
Wondering which language is preferred right now ? I have some flexibility on which language I use (js /python preferred but others are also ok) and would like to pick one which is the most mature.

**Comment by xpl** [comment]
@smogili1 Both JS and Python 3 (with async) work equally fine. PHP is a bit behind, as it doesn't have the async support.

If you want to contribute to CCXT, then JS is preferred, because it is our base language at the moment (we take the JS code and convert it to Python automatically, so they are equal in the support level).

But if you're asking as a user, not a contributor, then choose whatever is more convenient to you. Both JS and Python are very mature languages with developed ecosystems and communities.

**Comment by smogili1** [comment]
@xpl thank you! Asking mainly as a user, although I intend to contribute back any fixes/improvements I make.

**Comment by kroitor** [comment]
@smogili1 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

↑ Let us know if that doesn't answer your question ) Your contributions are welcome, we will be happy so see pull requests from you! )
