### ISSUE TITLE
questions about order structure

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4795]
Regarding the order `status`, the docs say:

>     'status':     'open',         // 'open', 'closed', 'canceled'

If an order is partially filled and then cancelled, what should the status be?

Regarding the `cost`:

>     'cost':        0.076094524,   // 'filled' * 'price' (filling price used where available)

If the _filling price_ isn't available, should this field be left blank?  (I think it should)

**Comment by kroitor** [comment]
> If an order is partially filled and then cancelled, what should the status be?

- `status == 'canceled'`
- `filled > 0`
- `filled < amount`

> If the filling price isn't available, should this field be left blank? (I think it should)

The problem is 3/4 of exchanges do not actually return the filling price or assume filling price = limit price in their engines. So, we only fill it if
- the exchange provides the actual cost in the response, so we don't have to calculate it
- the exchange doesn't provide the actual cost from the API we use `filled * price` with the most accurate price available:
  - if the exchange specifies the filling price – we use that
  - otherwise we use the limit price from the exchange response

Let us know if that doesn't answer your questions.

**Comment by npomfret** [comment]
Thanks.

> ... otherwise we use the limit price from the exchange response 

Do you mean the limit price the original order was set at? If so this could result in an inaccurate figure, no?

**Comment by kroitor** [comment]
> Do you mean the limit price the original order was set at? 

Nope, when you query an order by id – you don't specify the price of the original order.
Say, you `fetchOrder (someId)`. You get an order response from the exchange.

It could look like

```JavaScript
    ...
    amount: 5,
    price: 2,
    cost: 10,  // ← this can be missing
    filling_price: 2, // ← this can be missing
    ...
```

↑ If the cost and the filling price are both missing, then the only thing we can take for the cost is `amount * price`. In most cases exchanges won't provide any further detail. Otherwise you just don't rely on the cost at all, and use `fetchMyTrades` or `fetchOrderTrades` to get the actual executed fills and filling prices/costs for your orders.

> If so this could result in an inaccurate figure, no?

Yes, however, the figure will be as accurate as you can get from that endpoint of that exchange.

**Comment by npomfret** [comment]
Ok. For what it's worth I think leaving it blank, rather than potentially providing an inaccurate figure, is best.

**Comment by kroitor** [comment]
> For what it's worth I think leaving it blank, rather than potentially providing an inaccurate figure, is best.

I totally agree on this, so, if you notice an lying cost somewhere, please do let us know.
