### ISSUE TITLE
Help with HuobiPro market buy trading limits: min amount and cost

### ISSUE THREAD

**Issue by syron0** [ccxt/ccxt#4799]
- Programming Language version: JS (React Native 0.57.8)
- CCXT version: 1.18.193
- Exchange: huobipro

Hi, I have a question regarding trading limits for HoubiPro: does ```limits.amount.min```, in this case, represent the minimum cost of the order, instead of the minimum amount of base currency?

The warning returned while creating an order without the price argument states that:

> [...] To switch off self warning exception and specify cost in the amount argument, set
> .options[createMarketBuyOrderRequiresPrice] = False.[...]

so it seems that if I don't set that flag, I have to specify the base currency amount, right?

However, I receive an ```invalid-amount``` error response even if the amount is greater than ```limits.amount.min```.

An example could be ADA/BTC, whose minimum amount is reported to be 0.1:
```huobipro.createOrder('ADA/BTC', 'market', 'buy', 191.03, 0.000011)```

I have a successful outcome only if the cost of the order exceeds what is reported in the minimum.

Thanks in advance for your time.
Please let me know if you need some more information.

**Comment by kroitor** [comment]
Hi!

> so it seems that if I don't set that flag, I have to specify the base currency amount, right?

Wrong )

First of, let's be very precise and exact with the terms that we use:

- `amount` is in the base currency
- `price` is in the quote currency
- `cost` = `price * amount`, in the quote currency

For market sell orders HuobiPro requires you to specify just the amount in base currency that you want to sell for a market price (for quote currency). Therefore for a market *sell* order you don't have to specify the price. However, for a market *buy* order Huobi requires you to specify the total of your order in quote currency (which is the same as cost), and, from here, we have two options:

1. warn you and ask you to specify the cost in quote currency – via the amount argument.
2. warn you and ask you to specify the amount *and* the price for market buy, so that the implementation could calculate cost = amount * price inside the method by itself.

↑ In both of the above cases the goal is calculate the total cost of a market sell, because that is what huobi pro requires to specify for market sells. If you think carefully of what is what and how these terms relate to each other – then, the rest of it should be clear.

So, for a market sell, you got two options:

1. specify the price (in quote currency), despite that it isn't really needed for a market order – just to calculate the cost
2. switch off the warning and specify the cost (in quote currency) you calculated yourself – pass it in via the amount argument

All of the above is due to the asymmetric base/quote nature of the market buy/sell with Huobi API.

Duplicates (all of the above has been explained here):

- https://github.com/ccxt/ccxt/issues/3460
- https://github.com/ccxt/ccxt/issues/3427
- https://github.com/ccxt/ccxt/issues/564#issuecomment-407197761

Let us know if that doesn't answer the question.

**Comment by syron0** [comment]
Thank you for your kind response.
I read the referenced issues before creating mine and read them again now, but maybe I'm still missing something.

> > so it seems that if I don't set that flag, I have to specify the base currency amount, right?

> Wrong

I'm so sorry for the ambiguity of the phrase above, it was meant to be "if I don't set that flag _to false_, I have to specify the base currency amount, right?".

So, given these conditions:
- .options[createMarketBuyOrderRequiresPrice] = true (as per default)
- Specifying amount (base currency) _and_ price

I should fall into this situation:

> 1. specify the price (in quote currency), despite that it isn't really needed for a market order – just to calculate the cost

and the mentioned trade:
```huobipro.createOrder('ADA/BTC', 'market', 'buy', 191.03, 0.000011)```
should be fulfilled, right?

However, I get the ```invalid-amount``` error response mentioned above.

This error lead me to think that ```limits.amount.min``` was actually referring to the minimum _cost_, given the fact that for a cost greater than that the order is fulfilled.

Could you please help me with this example?

**Comment by kroitor** [comment]
> should be fulfilled, right?

In short, yes. But it turns out, there's more to it.

Let's first add a few more clarifications in general:

1. Exchange APIs are not ideal, so, even if you do everything right, you might still get an error, if the issue is on the exchange side (that happens all the time even with the biggest exchanges).
2. Huobipro specifies different amounts for `market` and `limit` orders, and CCXT is mostly targeted to cover `limit` orders, because this is the type of orders that the majority of programmatic orders will use. When you use market orders, you give out control over the execution price - to the exchange engine, so the price is not guaranteed in case of market orders. So, the values you see in the unified fields in `limits.amount.min` – are for `limit` orders, not for `market` orders, so you can ignore them. CCXT isn't ideal either, it's a project in progress and we are constantly working on it to make it better and even more unified, but there's so many aspects to the crypto trading, that it's hard to cover everything at once. And, also, everything changes very quickly.

Taking the above into account, because of (2) we will need to work with huobipro market orders in an exchange-specific way, until this is unified in ccxt in a better and more cross-compatible way with other exchanges.

So, back to the question, you should first obtain the `market` order minimums and maximums, and then proceed from there. And I did an example that will fetch those limits for you and will check the arithmetic of your `cost = amount * price` equation against your values.

The example is here: 

https://github.com/ccxt/ccxt/blob/master/examples/js/huobipro-market-buy-sell-fetch-trading-limits.js

I suggest that you read through it very carefully to make sure that our understanding is aligned.

However, there's still a problem. 
When I launch it on my system, it shows that your values are correct.
Here are the limits for ADA/BTC fetched in that example:

```JavaScript
{                                  symbol: "adabtc",
               'buy-limit-must-less-than':  1.1,
           'sell-limit-must-greater-than':  0.9,
          'limit-order-must-greater-than':  0.1,
             'limit-order-must-less-than':  5000000,
     'market-buy-order-must-greater-than':  0.0001,
        'market-buy-order-must-less-than':  100,
    'market-sell-order-must-greater-than':  0.1,
       'market-sell-order-must-less-than':  500000,
   'limit-order-before-open-greater-than':  999999999,
      'limit-order-before-open-less-than':  0,
        'circuit-break-when-greater-than':  10000,
           'circuit-break-when-less-than':  10,
  'market-sell-order-rate-must-less-than':  0.1,
   'market-buy-order-rate-must-less-than':  0.1        }
```

If we remove the excessive fields, we're left with:

```JavaScript
{                                  symbol: "adabtc",
     'market-buy-order-must-greater-than':  0.0001,
        'market-buy-order-must-less-than':  100,
    'market-sell-order-must-greater-than':  0.1,
       'market-sell-order-must-less-than':  500000,
  'market-sell-order-rate-must-less-than':  0.1,
   'market-buy-order-rate-must-less-than':  0.1        }
```

Your equation:

```
amount = 191.03
price = 0.000011
cost = amount * price = 0.00210133

cost > market-buy-order-must-greater-than
0.00210133 > 0.0001

cost < market-buy-order-must-less-than
0.00210133 < 100
```

So, your cost is well within limits and your values seem to satisfy their requirements, however, their API still responds with an error. In that case, I suggest that you post your *verbose request/response* exactly as described here, please follow the guides as precisely as you possibly can, and use triple backticks for readability: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue (don't post your API keys, we don't need them) 

```JavaScript
await exchange.loadMarkets ()
exchange.verbose = true
const order = exchange.createOrder (...
```

We will check the request structure, and if it's legit, then this might be a case of (1), and then we'd ask you to reach out to the huobipro tech support on this matter, because if the error is on their side, there's obviously very little we can do about it in the lib, unless they fix it. But still, first things first, so, I suggest that you follow this from top to bottom carefully, and report back with your verbose output.

Looking forward to hearing from you.

**Comment by syron0** [comment]
Thank you a lot for the detailed answer.

This is the verbose output generated by the already mentioned ```createOrder``` call:

```
'fetch:'
, 'huobipro', 'POST', 'https://api.huobi.pro/v1/order/orders/place?AccessKeyId=XXXXXXXX-XXXXXXXX-XXXXXXXX-XXXXX&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2019-03-11T09%3A20%3A32&account-id=XXXXXXX&amount=0&symbol=adabtc&type=buy-market&Signature=qG2m0Fzn25gRjrDEDnbpDlE98d0r5TJpIBzGk%2F82S84%3D',
'Request:'
, { 'Content-Type': 'application/json' }
, '{"account-id":XXXXXXX,"amount":"0","symbol":"adabtc","type":"buy-market"}'
'handleRestResponse:'
, 'huobipro', 'POST', 'https://api.huobi.pro/v1/order/orders/place?AccessKeyId=XXXXXXXX-XXXXXXXX-XXXXXXXX-XXXXX&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2019-03-11T09%3A20%3A32&account-id=XXXXXXX&amount=0&symbol=adabtc&type=buy-market&Signature=qG2m0Fzn25gRjrDEDnbpDlE98d0r5TJpIBzGk%2F82S84%3D', 200, undefined,

'Response:',
{ 'Cf-Ray': '4b5c74010dcfbe61-MXP',
  Server: 'cloudflare',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  'X-Request-Id': 'ee0811d9affd4130728890db4eaa936d',
  'X-Application-Context': 'dawn-broker-pro:default,prd:8080',
  'Content-Type': 'application/json;charset=UTF-8',
  'Set-Cookie': '__cfduid=d1c4a34825653d669d936ae94d229a16f1552296033; expires=Tue, 10-Mar-20 09:20:33 GMT; path=/; domain=.api.huobi.pro; HttpOnly',
  Date: 'Mon, 11 Mar 2019 09:20:33 GMT'
},
'{"status":"error","err-code":"invalid-amount","err-msg":"Parameter `amount` is invalid.","data":null}'
```


Please note that I have replaced AccessKeyId and account-id with "X", hoping it's not a problem.

Reading the log, it seems that the requested amount is actually invalid: 0.

**Comment by kroitor** [comment]
Ok, so, indeed, here's what was happening:

Your amount is well within limits, as we've correctly stated above. However, there's one more detail, that is also covered in the Manual, that is the precision of the value that is being passed: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

If we take the ADA/BTC market for example, it looks like this:

```JavaScript
mbp:ccxt igorkroitor$ node examples/js/cli huobipro market ADA/BTC
huobipro.market (ADA/BTC)
{     limits: { amount: { min: 0.01, max: 100 },
                 price: { min: 1e-8, max: undefined },
                  cost: { min: 0, max: undefined }     },
   precision: { amount: 2, price: 8 }, // ←--------------------- not these values
   tierBased:    false,
  percentage:    true,
       taker:    0.002,
       maker:    0.002,
          id:   "adabtc",
      symbol:   "ADA/BTC",
        base:   "ADA",
       quote:   "BTC",
      baseId:   "ada",
     quoteId:   "btc",
      active:    true,
        info: {    'base-currency': "ada",
                  'quote-currency': "btc",
                 'price-precision':  8,
                'amount-precision':  2,
                'symbol-partition': "main",
                            symbol: "adabtc" }            }
mbp:ccxt igorkroitor$
```

It says `precision: { amount: 2, price: 8 }`, so the amount precision for the ADA base currency ADA is 2 decimals after the dot, and the price precision for the BTC quote currency is 8 decimals after the dot.

What previous implementation did was to take the amount you pass in and limit it to the amount precision. With 2 decimals after the dot, your perfectly-legal value of `0.00210133` gets cut down to `0.00` and that is simply `0`.

But in a market-buy order, the amount is specified in quote currency. And limiting it to 2 decimals is wrong, so there was a bug in the previous implementation and I've uploaded a fix for it that should handle the amount properly. It will now format it to the price precision instead of the amount precision and that will send your value to huobi properly.

So, if you `npm update ccxt` to version 1.18.357 (it will be available for downloading in 5-10 minutes) and retry with your code again – that should resolve the issue. We will be happy if you report back whether it helped or not. Thx!

**Comment by kroitor** [comment]
> Please note that I have replaced AccessKeyId and account-id with "X", hoping it's not a problem.

This isn't a problem at all, in fact, it's in your interest to keep your keys in secret and not show them to anyone, not even us nor anyone else.

**Comment by syron0** [comment]
Great, I can confirm that now it's solved and working correctly.
Thanks for your support!

**Comment by kroitor** [comment]
@syron0 thx for reporting and for the feedback! Let us know if you notice anything suspicious.
