### ISSUE TITLE
How many requests does levels in orderbook count as

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4827]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: All Exchanges
Node.js 11.9.0 installed
Method: exchange.fetchOrderBook

Hello!

I am not sure if I should ask this question here but I give it a try.
For example Binance has a rate limit of 1200 requests per minute.

If we look at the below code where we get 5 levels of the orderbook. I wonder if that counts as one request or 5 requests. Also if that counts different on different exchanges?
```javascript
const orderbook = await exchange.fetchOrderBook('ETH/BTC', 5)
```
Thank you!

**Comment by kroitor** [comment]
> If we look at the below code where we get 5 levels of the orderbook. I wonder if that counts as one request or 5 requests. 

In most cases it's one single request per unified method call. So, whatever `fetch*` method it is – it should not do more than one HTTP request per method call. This is the general rule of thumb throughout this library. So, to answer your question precisely: that's 1 request (not 5 requests).

However, there may be a few special cases, with `fetchMarkets` and a couple of other methods that are used to preload exchange settings and pairs – those can do two requests per call in cases, when it cannot be done otherwise (most often, it can be done with just one request).

> Also if that counts different on different exchanges?

Same thing. The limit parameter isn't related to the number of requests. You can download the orderbook with limit 5 or limit 10 – that should be one request anyway.

Hope this answers your question.

**Comment by jackpotcityco** [comment]
Then I understand. I was thinking of "fetchTickers()" for example that can be so many requests as there are symbols for binance for example. 

But that did answer my question. That was good news that in general a fetch* method counts as 1 request. 

Thank you for help!

**Comment by kroitor** [comment]
> Then I understand. I was thinking of "fetchTickers()" for example that can be so many requests as there are symbols for binance for example.

It will be one call. However, Binance takes it further. It says: that call still will cost you as if you did as many calls as many symbols they have. So, you still have to pay care and attention on what is called when. In other words, it's not always about the number of http-calls or http-requests sent. But it's more about the *"cost"* to process your request on the exchange side. If it's a heavy request (like a request for all tickers for all symbols at once) – the exchange won't like you fetching that very frequently at all. Hope this clarifies it a bit.

**Comment by kroitor** [comment]
In other words, you were initially asking about `fetchOrderBook`, but `fetchTickers` has its specifics, and the exchanges have their specifics as well, so it doesn't always boil down to something simple like the number of calls made (and we still limit that number to send as less requests as possible anyway, in 99% of cases it's not more than one request per call).
