### ISSUE TITLE
HitBTC fetch_ohlcv IndexError

### ISSUE THREAD

**Issue by tawe141** [ccxt/ccxt#4840]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python 3.6.4 (Anaconda)
- CCXT version: 1.18.368
- Exchange: HitBTC
- Method: fetch_ohlcv

Not sure what causes this bug. The same error appears for a variety of symbols and timeframes.

```
>>> e = ccxt.hitbtc()
>>> e.load_markets()  # prints a whole bunch of stuff
>>> e.fetch_ohlcv('BTC/USDC', timeframe='1h')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\USER\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1302, in fetch_ohlcv
    trades = self.fetch_trades(symbol, since, limit, params)
  File "C:\Users\USER\Anaconda3\lib\site-packages\ccxt\hitbtc.py", line 718, in fetch_trades
    return self.parse_trades(response['trades'], market, since, limit)
  File "C:\Users\USER\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1392, in parse_trades
    array = [self.parse_trade(trade, market) for trade in array]
  File "C:\Users\USER\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1392, in <listcomp>
    array = [self.parse_trade(trade, market) for trade in array]
  File "C:\Users\USER\Anaconda3\lib\site-packages\ccxt\hitbtc.py", line 640, in parse_trade
    return self.parse_public_trade(trade, market)
  File "C:\Users\USER\Anaconda3\lib\site-packages\ccxt\hitbtc.py", line 650, in parse_public_trade
    side = trade[4]
IndexError: list index out of range
```

**Comment by kroitor** [comment]
HitBTC v1 is deprecated, please use HitBTC v2 API instead, just change `e = ccxt.hitbtc()` to `e = ccxt.hitbtc2()` in your code. Let us know if that doesn't help.

**Comment by tawe141** [comment]
Should deprecated APIs be removed then? 

I also noticed some inconsistency where v2 APIs are sometimes not labelled as such. For instance, there is a bitstamp and bitstamp1, but also bitfinex and bitfinex2. In other cases, the v1 APIs are entirely removed. What's the decision process for naming these?

**Comment by kroitor** [comment]
> Should deprecated APIs be removed then?

It was kept there mostly for backward-compatibility. Deprecated and shutdown APIs are kept for a while (at least as long as the API servers are responding) before being completely removed.

> What's the decision process for naming these?

At this time, the reasoning behind those ids and numbers is the following: in most cases the id without a number is the *"current main version"*. So, `bitstamp` is preferred over `bitstamp1` for that reason. Same is true with `bitfinex` (stable, more or less complete) and `bitfinex2` (beta, not complete). `kucoin` and `kucoin2` are mapped to the same class for the same reason as well.

However, there are exceptions to this rule that are there mostly for historical reasons, and, also, because this lib is a living thing. One of such exceptions is the case of `hitbtc` and `hitbtc2` (the latter is the current main). You're absolutely right, though, we are cleaning this up along the way. We will drop v1 soon. 

Let us know if that doesn't answer the question.

Related:

- https://github.com/ccxt/ccxt/issues/4658

**Comment by tawe141** [comment]
Good to know, thanks! hitbtc2 works great.
