### ISSUE TITLE
Precision issue

### ISSUE THREAD

**Issue by 0xecute** [ccxt/ccxt#4853]
Hello,
I see some strange stuff happening in my trading system because of the amount_to_precision used in ccxt when placing an order.
Maybe I misunderstand how it works, but I have the following with Bitfinex echange for example:
print(bitfinex.amount_to_precision('LTC/USDT',2.2504))
2.2503
print(bitfinex.amount_to_precision('LTC/USDT',2.2503))
2.2503
print(bitfinex.amount_to_precision('LTC/USDT',2.2505))
2.2505

From what I understand, it is that the Decimal representation of 2.2504 is 2.25039999999999995594635038287378847599029541015625.
So when the round is applied, it cuts and become 2.2503.

This is a problem when I try to place an order to sell all my LTC for example, since I always have 0.0001 LTC on my account.

Can you help me on this one?
Thank you again for the great work!

0xecute

**Comment by kroitor** [comment]
Hi! What's your programming language and what's your CCXT version number?

**Comment by 0xecute** [comment]
Hi,

I use python 3 and I am using ccxt 1.17.199.
I can see it is not the last one. I just updated it and it works better.

Sorry for the inconvenience. You can close the issue.
And thanks for this great support 👍

**Comment by kroitor** [comment]
@0xecute yep, because we are a work in progress we usually add bugfixes on a regular basis, so, most often the solution is to simply update to the most recent version first. If that doesn't help, then, feel free to open it, however, make sure that you provide enough info next time: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. Let us know if you have any difficulties with it, will be happy to help! )
