### ISSUE TITLE
Liquid used balance is None, is there a way to get it?

### ISSUE THREAD

**Issue by justsaid** [ccxt/ccxt#4854]
https://github.com/ccxt/ccxt/blob/93fc14b7fd2fe8e75a32a918df4769737f91460e/python/ccxt/liquid.py#L280

**Comment by kroitor** [comment]
@justsaid can you post your **verbose** request/response precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue?

**Comment by justsaid** [comment]
I know that liquid does not provide more information, but maybe it is possible to fetch the used balance indirectly via the open orders ?

**Comment by kroitor** [comment]
@justsaid 

> but maybe it is possible to fetch the used balance indirectly via the open orders ?

Yes, of course, and ccxt gives you all the tools to do that. But it won't send two requests for you. 

Otherwise, we could also fetch all tickers and all trades and all your withdrawals and pending deposits – that makes too much to fetch at once, this isn't how libraries are designed to work. The library gives you the methods to do what you want, but it won't combine the methods into a working application for your needs – the developer has to do it in the app-level logic.

So, if you want to calculate your used balance from your open orders – then, please, fetch your open orders with a CCXT method for fetching open orders and calculate the used balance from there. You might think that the library could do the calculation for the user, but in fact, a generic library cannot decide if it's the right time to fetch your open orders – it's all too app-specific (depends on your particular usage case and your application tasks).

Let us know if that doesn't answer the question.

**Comment by justsaid** [comment]
No, The problem is that liquid does not provide any information about the used/reserved balance. We only can get it if we calculate it through the open orders! Would consider this approach ? Or is it too far fetched ?

**Comment by justsaid** [comment]
Ok, Thanks Kroitor! Make sense !

**Comment by kroitor** [comment]
> Would consider this approach ? Or is it too far fetched ?

Yep, I'd say, that's too far, for reasons i've tried to explain in my previous comment. Basically, each ccxt method is trying to be as atomic as possible. That implies no more than one http request per call. The user is free to combine and group those calls according to his specific needs. 

Feel free to ask if anything, will be happy to help.
