### ISSUE TITLE
Precision problem with partial order

### ISSUE THREAD

**Issue by 0xecute** [ccxt/ccxt#4863]
Hello,

I am using the following:
- OS: Linux
- Programming Language version: Python
- CCXT version: 1.18.385
- Exchange: Bitfinex
- Method: fetchOrder

When I place a limit order on bitfinex, for example ETCUSD which has a precision of 4 digits, for an amount of 9.3054, it works.
But then, if the order is hit partially and I fetch the order, the "filled" and "remaining" fields have the following values:
filled: 3.59975801
remaining: 5.70564199
So the precision is not the same anymore. If now I want to cancel the order and revert the order, I cannot because I will not be able to place a new revert order of 3.59975801 units.

Is it a ccxt precision problem? How can such a problem be managed?
Thank you in advance for your help!

0xecute

**Comment by kroitor** [comment]
Hi!

In order to help we need your **verbose request/response** otherwise we will be mostly guessing.

> But then, if the order is hit partially and I fetch the order, the "filled" and "remaining" fields have the following values:

I suggest that you read this very carefully:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

We need you to add `.verbose = True` before fetching the order:

```Python
exchange.load_markets()
exchange.verbose = True
exchange.fetch_order(...
```

↑ And post the output here.

**Comment by 0xecute** [comment]
Thank you for your fast reply.

Actually I don't think it is a ccxt issue because on the Bitfinex interface, I can see the details:
![Screenshot 2019-03-21 at 10 46 13](https://user-images.githubusercontent.com/15121936/54744192-9102d300-4bc6-11e9-90a1-842eda6b5865.png)


So the units that ccxt gives are correct. But I thought I am not the only one having this problem, so maybe I am missing something obvisous or it has a common solution.
In the example above, if I try to send the following order:
`bitfinex.createLimitBuyOrder('ETC/USD', 5.70564199, 4.9)` it will places a limit order of 5.7056, which is coherent with the precision but doesn't allow me to sell **all** my ETC.

I am sorry I am a bit lost about this precision issue, 

thank you again for any help.

**Comment by 0xecute** [comment]
Okay, I found more details. Actually, on the web interface of Bitfinex we can place an order of 5.70564199 and it works.
Apparently, it may be a problem of the way ccxt fetch or define the precision amount ( or maybe how I understood it :)
For example in bitfinex, calling:
`bitfinex.publicGetSymbolsDetails()` it will return for ETC/USDT:
`{'pair': 'etcusd', 'price_precision': 5, 'initial_margin': '30.0', 'minimum_margin': '15.0', 'maximum_order_size': '100000.0', 'minimum_order_size': '2.0', 'expiration': 'NA', 'margin': True}`
In the log:
`Request: GET https://api.bitfinex.com/v1/symbols_details {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None
`
I don't paste you the response because it is quite long, but we can see that it returns the same precision (5) for every symbols. Is it normal?


Thank you.

**Comment by kroitor** [comment]
> I don't paste you the response because it is quite long, but we can see that it returns the same precision (5) for every symbols. Is it normal?

No, because you should've posted just the last request and the last response. You should really follow the guides by that link **exactly** (literally to a word). But, anyways, no worries, I don't think it will help in this case.

> In the example above, if I try to send the following order:
> bitfinex.createLimitBuyOrder('ETC/USD', 5.70564199, 4.9) it will places a limit order of 5.7056, which is coherent with the precision but doesn't allow me to sell all my ETC.

To clarify, if the exchange reports those values – it would be incorrect for ccxt to cut them in `fetchOrder`. However, to be precise, the exchange will allow you to spend all your ETC, it just won't allow you to place an order with certain precision. There's two types of precision, that the exchange can implement:

- `DECIMAL_PLACES` – the number of digits after the decimal dot. If it equals 5, then you can't use a value of 0.123456.
- `SIGNIFICANT_DIGITS` – the number of non-zero digits. This is the type implemented with Bitfinex. If it equals 5, then you can't use a value of 0.123456 but you can use values 0.10000 and 0.023456.

Also, note, that there's `amount` precision and `price` precision, as explained in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Let me know if that does not help.
Feel free to reopen this or just ask if you have further questions.

**Comment by 0xecute** [comment]
Thank you for the help.
I understand the difference and your solution, but for ETC the minimum amount is 2 unit.
So I could send an order of 5.1 but then the order of 0.023456 is rejected.

Thank you again for your help.

**Comment by kroitor** [comment]
> I understand the difference and your solution, but for ETC the minimum amount is 2 unit.
> So I could send an order of 5.1 but then the order of 0.023456 is rejected.

Yeah, that's the effect of a different rule, the limits (along with the precision), so it turns out that you can't really spend everything to a penny. At least, we can't really overcome the exchange trading rules in the lib, for obvious reasons. But in most cases users can tolerate that and will have a "buffer". Not being able to go down to the absolute zero – can still be ok when the minimal amount is 2 or more.
