### ISSUE TITLE
Exchanges which fail to loadMarkets

### ISSUE THREAD

**Issue by ahmedbodi** [ccxt/ccxt#4884]
- OS: Ubuntu 18
- Programming Language version: PHP 7.3
- CCXT version: Latest
- Exchange: N/A
- Method: loadMarkets

Calling LoadMarkets on the following exchanges fails to load:

allcoin - Warning: Illegal string offset 'marketCoins'
bcex - GET https://www.bcex.top/Api_Market/getPriceList 404
buda - GET https://www.buda.com/api/v2/currencies 28 Operation timed out after 10001 milliseconds with 0 bytes received
btctradeim -  GET https://api.btctrade.im/coin/usc/allcoin?t=1553480255114 500 
ccex - GET https://c-cex.com/t/pairs.json 403 
coingi - GET https://coingi.com 200 not accessible from this location at the moment
coolcoin - fetchMarkets() for "usc" returned => "[]"
cryptopia - GET https://www.cryptopia.co.nz/api/GetCurrencies 403 
flowbtc - POST https://api.flowbtc.com:8405/ajax/v1/GetProductPairs 6 Could not resolve host: api.flowbtc.com
liqui - GET https://api.liqui.io/api/3/info 28 Operation timed out after 10001 milliseconds with 0 bytes received
yunbi - GET https://yunbi.com/api/v2/markets.json 28 Operation timed out after 825 milliseconds with 0 bytes received

**Comment by kroitor** [comment]
Duplicates:

> allcoin - Warning: Illegal string offset 'marketCoins'

They changed their API and the support for allcoin is currently broken:

- https://github.com/ccxt/ccxt/search?q=allcoin&type=Issues
- https://github.com/ccxt/ccxt/issues/2962
- https://github.com/ccxt/ccxt/issues/2702

> cryptopia - GET https://www.cryptopia.co.nz/api/GetCurrencies 403

Have shutdown the exchange due to a hack. They resumed the operation later but haven't completely restored it yet:

- https://github.com/ccxt/ccxt/search?q=cryptopia&type=Issues
- https://github.com/ccxt/ccxt/issues/4805
- https://github.com/ccxt/ccxt/issues/4584

> liqui - GET https://api.liqui.io/api/3/info 28 Operation timed out after 10001 milliseconds with 0 bytes received

Have shutdown the exchange:

- https://github.com/ccxt/ccxt/issues/4559
- https://github.com/ccxt/ccxt/search?q=liqui&type=Issues

> yunbi - GET https://yunbi.com/api/v2/markets.json 28 Operation timed out after 825 milliseconds with 0 bytes received

Have shutdown the exchange, we will remove it from the lib shortly.

- https://www.coindesk.com/yunbi-bitcoin-exchange-latest-close-china-crackdown

> flowbtc - POST https://api.flowbtc.com:8405/ajax/v1/GetProductPairs 6 Could not resolve host: api.flowbtc.com

They have changed their API and it is broken since then:

- https://github.com/ccxt/ccxt/search?q=flowbtc&type=Issues
- https://github.com/ccxt/ccxt/issues/3173

> bcex - GET https://www.bcex.top/Api_Market/getPriceList 404

Have have changed their API and it is broken since then:

- https://github.com/ccxt/ccxt/search?q=bcex&type=Issues
- https://github.com/ccxt/ccxt/issues/4365

The other exchanges from your list can be inaccessible due to connectivity issues, I suggest that we resolve each exchange in its own standalone issue, just for the separation of concerns. Feel free to ask, if you have more.
