### ISSUE TITLE
DX Exchange Implementation

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#4891]
Hello,

I'd like to implement the dx exchange for ccxt.
The exchange is not using HMAC, it uses an authentication token (sent as HTTP-Header), therefore it also needs a login method executed before the first request (and after timeout expired).
Also the method is provided as json parameter and not in the url.
https://apidocs.dx.exchange/#99e1780b-c222-4e60-a788-ad7e8f522529

If I create a pull request, will it be merged? (Because the exchange is quite different from any other exchange I have seen)
Is there any other exchange that uses similar mechanisms?

**Comment by kroitor** [comment]
Hello! 

Thanks for reaching out to us, good questions!

> The exchange is not using HMAC, it uses an authentication token (sent as HTTP-Header), therefore it also needs a login method executed before the first request (and after timeout expired).

Yes, it happens.

> If I create a pull request, will it be merged?

Yep. But we won't be able to certify it, unless they do something about their auth scheme.

> (Because the exchange is quite different from any other exchange I have seen)

It is different from most exchanges, but not really unique... There's more of them, like, `bitlish`, `btctradeua`... They have a `signIn` method for that matter as well. Most of them belong to smaller exchanges, though. In other words, the exchanges should not reinvent the wheel with their own authentication schemas anyway, because their first wheel will be square anyway. They should stick to an adequate public/secret key signing schema. [Huobi once tried](https://github.com/ccxt/ccxt/issues/3345) to add user-generated and uploaded elliptic-curve privateKeys, but very soon realized that was a bad idea (i guess, they didn't want to lose volumes due to negative feedback)...

But anyways, back to the subject, we could merge it, however, if we are doing it, it has to be done right. That means, we should throw proper hints at proper times at the user, so that the result is not confusing to use at least.

Here's a reduced example of how you could do that right with one of the exchange engines available commercially: https://gist.github.com/kroitor/075393ae77c8de3642d0d19c946a6b9e.

That is a lot more complicated example that involves `Authorization` token in HTTP headers (requires its own HMAC with its own `secret`) with some endpoints, and other endpoints require `publicKey` and `secret`. Therefore this example implementation has differentiated parts of the API, that are handled in the `sign()`. It isn't complete, doesn't have all the necessary methods of the unified API yet, but it demonstrates the approach with the non-standard authentication. You can use this as a template and you should rewrite and add **all** the relevant and missing parts to make it a complete implementation: 

Methods of interest there:

- `describe`
- `signIn`
- `sign`
- `handleErrors`

All the necessary procedures to calculate the encryption bits and pieces, including JWT, HMAC and other stuff – all of that is already in the CCXT base class.

Also, if you haven't already, make sure to read this entire doc: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Anyways, your contributions and PRs are welcome! Thanks for your involvement!
Let us know if you encounter any difficulties. Feel free to reopen this if needed or just ask further questions, if any, will be happy to help.

**Comment by brandsimon** [comment]
The transpiling works now for Python.

**Comment by brandsimon** [comment]
The transpiling works now for python. In PHP there is one problem left:
The exchange wants the params to be an object (Associative array). In PHP the functions has: `$params = array ()` as parameter. So if there is nothing in it, it will be sent as normal array in JSon.
So in PHP the exchange is throwing an error.

I can think of two solutions:
- Instead of `params = {}`, do `params = { '__associative_php_fix': true }` which works for the exchange.
- In sign, I check if params is an array and if it is empty and if so, I will set it to `{ '__associative_php_fix': true }`. (So it will only affect PHP).

I prefer solution 1, but I dont like it much. Is there a better way to do this?

**Comment by brandsimon** [comment]
I asked the same questions in my PR #4942

**Comment by kroitor** [comment]
@brandsimon replied there ) thank you!
