### ISSUE TITLE
Question about minimum amount in createOrder

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4914]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: Coinegg
Node.js 11.9.0 installed
Method: createOrder

Hello!

I am trying to createOrder on exchange coinegg for ETH/BTC with below code:
```javascript
(async () => {
    let exchange = new ccxt.coinegg(); // default id
    await exchange.loadMarkets();
    exchange.apiKey = "mypublicapikey";
    exchange.secret = "myprivateapikey";

    try {
        if (exchange.has['createOrder']) {

            const order = await exchange.createOrder("ETH/BTC", "limit", "buy", 0.01, 0.034);
            returnedvalue = JSON.stringify(order);
        }
    } catch (e) {

        if (e instanceof ccxt.NetworkError) {
            console.log(exchange.id + ' failed due to a network error:' + e.message);
        } else if (e instanceof ccxt.ExchangeError) {
            console.log(exchange.id + ' failed due to a exchange error:' + e.message);
        } else {
            console.log(exchange.id + ' failed with:' + e.message);
        }
    }
})();
```
The error I get when executing the code is:
```javascript
coinegg failed due to a exchange error: 
coinegg Pending order amount must be above 0.001 BTC
```

When looking at the JSON response for coinegg (coinegg.load_markets). This can be seen in the minimum limit:
**amount":{"min":1e-8 which is: (0.00000001)**

As seen I put 0.01 in the amount parameter which is larger than: 0.00000001 ?
Then the error message says that amount must be above 0.001 BTC. I am not sure if something is wrong or if I miss something about the amount parameter?

If I change the amount to: 0.003, then it works. But then I assume the below, but that is "cost" and not amount?
**0.03 * 0.034 = 0,00102 (greater than 0.001)**

```javascript
"ETH/BTC":{"limits":{"amount":{"min":1e-8,"max":100000000},
"price":{"min":1e-8,"max":100000000},"cost":{}},"precision":{"amount":8,"price":8},"taker":0.001,"maker":0.001,
"id":"ethbtc","symbol":"ETH/BTC","base":"ETH",
"quote":"BTC","baseId":"eth","quoteId":"btc","active":true,"info":["ETH","0.03529","0.03521911","0.03553505","0.035553",
"0.034155",12151,418.5931,2.26]}
```
Thank you!

**Comment by kroitor** [comment]
Hi!

> The error I get when executing the code is:

First of, when posting an issue, please ALWAYS include your **verbose request/response** as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. Otherwise we will ask it in our first response anyway. It isn't required for resolving this issue, however, it is still required in most cases (just the error message is not enough!). Otherwise it's hard to tell the reason immediately.

> Then the error message says that amount must be above 0.001 BTC. I am not sure if something is wrong or if I miss something about the amount parameter?

It is the exchange error message that is confusing you here... The rules and standardized terms in CCXT are:

- `amount` is always in base currency (`ETH` in this case)
- `price` is always in quote currency (`BTC` in this case)
- `cost` is always in quote currency (`BTC` in this case)

However, exchanges don't really follow any unified pattern in naming their terms, so they can call your cost in BTC – *"the amount"*, meaning that it is the total amount in BTC. 

Also, if you re-read their error message, it says *"amount in BTC"*. So, they mean total cost in that message:

> `coinegg Pending order amount must be above 0.001 BTC`

So, if that is the "amount in BTC" – they actually mean the total cost of your order in BTC.

However, they don't serve their cost minimums anywhere from their `loadMarkets`/`fetchMarkets` endpoints, so CCXT cannot tell you the cost limits for coinegg:

```
mbp:ccxt igorkroitor$ node examples/js/cli coinegg market ETH/BTC
coinegg.market (ETH/BTC)
{     limits: { amount: { min: 1e-8, max: 100000000 },
                 price: { min: 1e-8, max: 100000000 },
                  cost: { min: undefined, max: undefined } }, // ← the coinegg exchange does not provide it
   precision: { amount: 8, price: 8 },
   tierBased:    undefined,
  percentage:    undefined,
       taker:    0.001,
       maker:    0.001,
          id:   "ethbtc",
      symbol:   "ETH/BTC",
        base:   "ETH",
       quote:   "BTC",
      baseId:   "eth",
     quoteId:   "btc",
      active:    true,
        info: [ "ETH",
                "0.035501",
                "0.0352091",
                "0.03551586",
                "0.035553",
                "0.034155",
                 12192,
                 421.1936,
                 2.87         ]                               }
mbp:ccxt igorkroitor$
```

So, the only way to find out if your total cost is within their limits – is to try and place an order and catch the error message, then use the value from the error message as your minimal cost upon your second retry. Alternatively, you could just hardcode the minimal cost as 0.001 BTC, but I would not recommend that. I'd recommend you to make a function that will send a very small order at the beginning of your program, and will return the min cost for the life of your program (or you could even call it in regular intervals to keep your app logic updated).

Hope that answers the question, let me know if not.

**Comment by jackpotcityco** [comment]
> First of, when posting an issue, please ALWAYS include your verbose request/response as described here
Yes, that is true. I will do that next time ofcourse. Thank you.

> However, exchanges don't really follow any unified pattern in naming their terms, so they can call your cost in BTC – "the amount", meaning that it is the total amount in BTC.
I thought so also that it could have been that. I was not entirely sure if the error message was from ccxt or the exchange itself. But then I understand. They do not as you mentioned not provide the minimum cost in the JSON response.

It was a good idéa to for this kind of scenario create a function that tries to send a very small order to return the minimum amount to create an up-to-date database with minimum cost for orders to send.

Thank you for your help!
