### ISSUE TITLE
Is it possible to use a Proxy IP Address and Port on fetchTickers

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4928]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: All Exchanges
Node.js 11.9.0 installed
Method: fetchTicker()/fetchTickers()

Hello! 

I wonder if it is possible to use a proxy IP Address and Port number when calling the below methods: **fetchTicker() and fetchTickers()** ?
I have seen in the manual that there is a proxy in the exchange class but the example shows a string there.

Is it possible in any way to use an IP Address and Port?

**Example:
IP Address: 185.132.178.201	
Port: 8080**

_(Language Javascript)_
```javascript
let exchange = new ccxt.kraken();
exchange.proxy = ??? (Example from Manual: https://crossorigin.me/)
const tickers = await exchange.fetchTickers();
```
Thank you!

**Comment by kroitor** [comment]
Hi!

> Is it possible in any way to use an IP Address and Port?

Yes:

- https://github.com/ccxt/ccxt/issues/2480
- https://github.com/ccxt/ccxt/wiki/Install#javascript-proxies

**Comment by jackpotcityco** [comment]
Thank you!

So the below code should be able to work. I might have one question there:
```javascript
const ccxt = require ('ccxt')
    , HttpsProxyAgent = require ('https-proxy-agent')

const proxy = process.env.http_proxy || 'http://168.63.76.32:3128' // HTTP/HTTPS proxy to connect to
const agent = new HttpsProxyAgent (proxy)

const kraken = new ccxt.kraken ({ agent })
```
The question is for the below line. There is an "OR ||" where the first argument is: "process.env.http_proxy" I am not sure what that means?
At the same time, if I have this Proxy: "168.63.76.32:3128". Do I need to put the first argument there before the || ?
```javascript
const proxy = process.env.http_proxy || 'http://168.63.76.32:3128' // HTTP/HTTPS proxy to connect to
```

**Comment by kroitor** [comment]
> There is an "OR ||" where the first argument is: "process.env.http_proxy" I am not sure what that means?

It means: *take the first value before `||` and if it is `undefined` take the second value after `||`.

The first value is `process.env.http_proxy` – it is an environment variable that can be passed into your program by your shell. It sometimes helps to have the variables configurable from outside of the program, rather than hardcoding the value inside the program. That helps reconfigure the program without editing it – just by changing an environment variable. Google for `environment variables`, `shell env variables` and `node js env variables`. 

The second value is your proxy `'http://168.63.76.32:3128'`. If you're asking what the first value is, then, it is most likely `undefined` in your case, so you can simply ignore it and drop it from that line, simplifying it to:

```JavaScript
const ccxt = require ('ccxt')
    , HttpsProxyAgent = require ('https-proxy-agent')

const proxy = 'http://168.63.76.32:3128' // HTTP/HTTPS proxy to connect to
const agent = new HttpsProxyAgent (proxy)

const kraken = new ccxt.kraken ({ agent })
```

**Comment by jackpotcityco** [comment]
Thank you, then I understand the difference. I can just use the 'http://168.63.76.32:3128' proxy in this scenario then as the other parameter before OR || most likely is undefined in my case.

Thank you for your help!
