### ISSUE TITLE
module 'ccxt' has no attribute 'exchanges'

### ISSUE THREAD

**Issue by giladbi** [ccxt/ccxt#496]
hi
i am trying to install the package and than run `print(ccxt.exchanges)`
using python 3.5 and version installed is 1.10.24
i assume i am doing something wrong 
thanks

**Comment by kroitor** [comment]
@giladbi, hi! How do you install it?

**Comment by giladbi** [comment]
d.l. the whl file and run the install from the command prompt
and than:
`import ccxt
print(ccxt.exchanges) # print a list of all available exchange classes`

**Comment by kroitor** [comment]
@giladbi why don't you use pip install for that?

**Comment by giladbi** [comment]
i am new to programming and to python and pip didn't work for me so i used the cmd

**Comment by kroitor** [comment]
@giladbi if you want to actually start programming, you will have to give exact answers. It's very hard to help, if you don't answer precisely. 

So, for example, if you say *"pip didn't work for me"* – you should instead copy the command that you tried that didn't work, and the output that was printed... Otherwise we will inevitably ask for that and it will take much longer to resolve the issue if we ping-pong with question and answers in this manner. 

If you say *"I used cmd"*, then you should paste the entire sequence of alternative commands that you used... 

Also, most newcomers tend to ignore details, like, answering just one question of the two. We need all answers and we need them concrete. 

Unfortunately we can't really spend too much time teaching you the basics of programming. We can't help all newcoming programmers install their environments properly even if we really want to. There's usually a lot of info about that on the internet, so, if you're getting errors, you can google for them literally, programming skills are not necessary for that.
