### ISSUE TITLE
bitfinex2 'has': 'fetchMyTrades' shold be true

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#4971]
Hi,

I noticed that the bitfinex2 api (bitfinex v2) has the `has` property of `fetchMyTrades` set to false, but the method is implemented, so it should be true.

Or is the method still incomplete? It looks good from a quick check...

**Comment by kroitor** [comment]
> Or is the method still incomplete? It looks good from a quick check...

The documented pagination for v2 doesn't work – it will not react to `start` or `end` endpoint params and will always return the most recent trades (or no trades) without pagination, despite that the params are documented in the v2 docs. Bitfinex says that v2 is unstable. Therefore v2 `fetchMyTrades` has to be `false` until this is fixed in the API. If you think we should still enable it, let us know, last time when we tried to do so, users were more confused rather than happy.

- https://github.com/ccxt/ccxt/issues/2758

Let us know if that doesn't answer the question.

**Comment by firepol** [comment]
This answers the question, however a comment in the code would help me (or other people looking at it) understanding the issue, maybe you can add a comment and a link pointing to this issue? Just in case... thx
