### ISSUE TITLE
Getting canceled orders for Bittrex

### ISSUE THREAD

**Issue by romanbolshakov** [ccxt/ccxt#4974]
- OS: Ubuntu
- Programming Language version: javascript
- CCXT version: 1.18.345
- Exchange: Bittrex
- Method: fetchOrders

Hello. Please tell me how can I get my canceled orders? I try to do this for Bittrex. 
fetchOrders not supported yet. (I'm getting error: "Error: bittrex fetchOrders not supported yet") 
fetchOpenOrders and fetchClosedOrders doesnt contain cancled orders.
Any solutions?

Thnx ...

**Comment by kroitor** [comment]
> fetchOrders not supported yet. (I'm getting error: "Error: bittrex fetchOrders not supported yet")

That is by design, and that corresponds to the principles described in this section of the Manual: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties – not all exchanges have all the methods, but the exchanges have an indication of what is available with their API in the `has` property.

Bittrex doesn't have means for fetching canceled orders. In general, Bittrex does not differentiate canceled and closed orders. A canceled order is a closed order that has a positive `remaining` volume, as described in the order structure, here: https://github.com/ccxt/ccxt/wiki/Manual#order-structure.

I've added a conditional to Bittrex implementation that should help detect them in userland, so, if you update to version 1.18.459, it will show the closed orders with `remaining` > 0 as canceled. Let us know if that doesn't help.
