### ISSUE TITLE
exmo.me domain is unreachable

### ISSUE THREAD

**Issue by denarioresearch** [ccxt/ccxt#4975]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu
- Programming Language version: Node.js v11
- CCXT version: 1.18.459
- Exchange: exmo
- Method: loadMarkets

https://exmo.me/en/docs/fees and https://exmo.me/ctrl/feesAndLimits do not work because exmo.me is unreachable. Can we use https://exmo.com/en/docs/fees instead?

**Comment by xpl** [comment]
You can override the domain this way:

```javascript
new ccxt.exmo ({
    urls: {
        api: {
            web: 'https://exmo.com',
        },
        www: 'https://exmo.com',
    }
})
```

If that doesn't help, you can switch to hard-coded fees (those may be outdated though), that will suppress requests to the `/en/docs/fees` endpoint:

```javascript
new ccxt.exmo ({
    options: {
        useWebapiForFetchingFees: false
    }
})
```

We had to implement that `useWebapiForFetchingFees` flag because Exmo has recently started to ban programmatic requests to their WWW front-end, so switching domains didn't work. Maybe something has changed since then.

BTW, don't know why we currently have `useWebapiForFetchingFees: true` enabled by default, @kroitor ?

**Comment by denarioresearch** [comment]
thanks, I was not aware of requests ban. Switching to exmo.com did not help, but useWebapiForFetchingFees: false fixed problem. Now I need to check fees/limits accuracy.

**Comment by xpl** [comment]
@denarioresearch If you spot any inaccuracies please let us know, we will fix those in the library itself.

**Comment by kroitor** [comment]
Here's a similar dupe issue: https://github.com/ccxt/ccxt/issues/4950

@xpl

> BTW, don't know why we currently have useWebapiForFetchingFees: true enabled by default, @kroitor? UPD: I just set it to false in 650511d

Just in case they change their fees... But that doesn't make too much sense, probably.
