### ISSUE TITLE
request to rename fetch2 method

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4990]
I was digging around in the ccxt internals looks for a way to intercept all exchange requests.  I found what I think is the best point (for my requirements) and that is the `fetch2` method.  It seems to me that this guy is super important.  Could we perhaps rename it to something like `signAndSendRequest`?

**Comment by kroitor** [comment]
Yep! It was created upon detaching the signing from sending, but at that time we didn't come up with any more meaningful name for it, so it was always more like a temporary name meant to be changed later for a better one.

**Comment by ttodua** [comment]
if anyone has any need for this again, please re-raise the issue.

**Comment by trankhacvy** [comment]
Hey @npomfret How can you use `fetch2` to intercept the requests? I'm stuck on this.

**Comment by ttodua** [comment]
@trankhacvy do you mean something like:
```
// override instance's fetch2
const originalFetch2 = exch.fetch2;
exch.fetch2 = (...args) {
    console.log(args);
    return originalFetch2 (...args);
}
```

**Comment by trankhacvy** [comment]
@ttodua I'm using the method you mentioned, but it doesn't fully address my issue. I need to calculate the "weight" usage for each user. Binance provides a response header called 'X-MBX-USED-WEIGHT-(intervalNum)(intervalLetter)' that contains the current IP-based weight for all defined request rate limiters. However, I'm unable to access this header because the `fetch2` function doesn't return a Response object that would allow me to examine the headers.

**Comment by ttodua** [comment]
if you'd look in internals: https://github.com/ccxt/ccxt/blob/master/ts/src/base/Exchange.ts#L3586

you would have found out that it will eventually leads to `handleRestResponse` method. so you can override that method (exactly like my above given example, but instead of `fetch2`.
