### ISSUE TITLE
request: make nonce method async

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4994]
Hi

I'm in the process of putting a distributed ccxt instance in the cloud.  The problem I'm running into is that I'm getting invalid nonce errors (presumably because I'm reusing them in 2 quick successive api calls).

I want to replace the `nonce` call with one of my own (to a centralised nonce service that won't dish out duplicates).  But in order to do this the nonce method needs to be async.

@kroitor Would you accept a pr that changes:

    let nonce = this.nonce ();

to

    let nonce = await this.nonce ();

everywhere in the codebase?

**Comment by kroitor** [comment]
Hi!

> Would you accept a pr that changes:

In general, yes, however...

> I want to replace the nonce call with one of my own (to a centralised nonce service that won't dish out duplicates). But in order to do this the nonce method needs to be async.

... in order to do that right, we will have to make `sign` async as well, so it may be a little more involved.

I suggest that we move this discussion here: https://github.com/ccxt/ccxt/issues/3315 if you don't mind. Closing this for now as a duplicate, looking forward to proceeding in #3315.

**Comment by npomfret** [comment]
Thanks, I've figure out a way to do it without the change but it would be cleaner.

**Comment by kroitor** [comment]
@npomfret we don't want a change to break the old code, so let's think on how to make it backward-compatible, shouldn't be a problem, really.
