### ISSUE TITLE
Bitso: fetchOrder works but has.fetchOrder is set to false

### ISSUE THREAD

**Issue by franz-see** [ccxt/ccxt#5009]
- OS: macOS mojave OSX 10.14.4
- Programming Language version: node v10.15.1
- CCXT version: 1.18.481
- Exchange: bitso
- Method: fetchOrder

**Issue**
`bitos.has.fetchOrder` is set to `false` but it actually works as long as you provide both orderId and symbol. _Note: providing just the orderId fails._ 

**Test script**

_Note: I set the environment variables `BITSO_APIKEY` and `BITSO_SECRET` to make this script works_

```
'use strict';
const ccxt = require ('ccxt');

(async function () {
    try {
        console.log('ccxt version: ' + ccxt.version)
        const bitso1 = new ccxt.bitso ({id:'bitso1',apiKey:process.env.BITSO_APIKEY,secret:process.env.BITSO_SECRET})

        // load market first so that fetchOrder would work
        console.log('Loading markets')
        await bitso1.loadMarkets()

        console.log('Creating order')
        const created_order = await bitso1.createOrder('BTC/MXN', 'limit', 'sell', 0.000075, 100700)

        console.log('bitso.has.fetchOrder = ' + bitso1.has.fetchOrder)

        console.log('Fetching order')
        const fetched_order = await bitso1.fetchOrder(created_order.id, 'BTC/MXN')

        console.log('fetched_order = ' + JSON.stringify(fetched_order))

        console.log('Cancelling order')
        await bitso1.cancelOrder(created_order.id)
    } catch (error) {
        console.error(error)
    }
}) ();
```

**Output**

```
Loading markets
Creating order
bitso.has.fetchOrder = false
Fetching order
fetched_order = {"info":{"original_value":"7.55","unfilled_amount":"0.00007500","original_amount":"0.00007500","book":"btc_mxn","created_at":"2019-04-20T13:24:17+0000","updated_at":"2019-04-20T13:24:17+0000","price":"100700.00","side":"sell","type":"limit","oid":"ao5ehkA8qwWaQY0S","status":"open"},"id":"ao5ehkA8qwWaQY0S","timestamp":1555766657000,"datetime":"2019-04-20T13:24:17.000Z","symbol":"BTC/MXN","type":"limit","side":"sell","price":100700,"amount":0.000075,"remaining":0.000075,"filled":0,"status":"open"}
Cancelling order
```

**Comment by franz-see** [comment]
PR : https://github.com/ccxt/ccxt/pull/5010

**Comment by kroitor** [comment]
> Couldnt quite figure out how to write tests for it. Kindly advice and I can update the PR :)

We currently don't run private tests on Travis CI, because we do them locally, that is until we resolve the apikey storage/encryption issues on our side. In the meantime, you can check out the ad-hoc tests here: 

- https://github.com/ccxt/ccxt/tree/master/js/test
- https://github.com/ccxt/ccxt/tree/master/python/test
- https://github.com/ccxt/ccxt/tree/master/php/test

↑ Some of those are transpiled, the others are language-specific... So it's a bit more complicated. We currently don't have a set of tests for parsers of the endpoint response formats, but we do have a set of higher-level tests for unified structures.

We used to run private tests on Travis previously with a set of non-secret keypairs for testing, however, people reported on those too often ("your keys are in danger!") and other people screwed the nonce numbers by using the same testing keys for their purposes, so, we decided to remove private keys until we come up with a better solution for public testing of private endpoints with encrypted keys.

But anyways, thx so much for your participation, we are happy for all help! )
