### ISSUE TITLE
fetchOpenOrders - get orderID

### ISSUE THREAD

**Issue by tezeug** [ccxt/ccxt#5017]
- OS: Kubuntu 19.04
- Programming Language version: Python3.7
- CCXT version: 1.18.482
- Exchange: BitMEX
- Method: fetch_open_orders and orderID

Hello again.
I am sure this is not as much a CCXT problem as "Python's" but still I would like to ask you about that. I am trying to fetch the orderID of the currently opened orders but have this problem.
Have a look:

        trd = str(BitMEX.fetch_open_orders(Symbol1))
        trd1 = str(trd['id'][0])
        ord1 = BitMEX.fetch_order(id=trd1)

  File "bit.py", line 41, in check
    trd1 = str(trd['id'][0])
TypeError: string indices must be integers

I've searched over Google a bit but was not able to find a solution (I guess rather understand but it does not really matter now).

**Comment by kroitor** [comment]
It looks like you really need to practice Python first...

```Python
trd = str(BitMEX.fetch_open_orders(Symbol1))
trd1 = str(trd['id'])  # ←---------------------- deleted [0] from here
ord1 = BitMEX.fetch_order(id=trd1)
```

Hope this answers the question.

**Comment by tezeug** [comment]
Would you recommend me any good sources where to "professionally" start?

**Comment by kroitor** [comment]
@tezeug i'd suggest to check read the articles and watch video courses in the examples section here: https://github.com/ccxt/ccxt/tree/master/examples#see-also ) Also, browse the code examples here: https://github.com/ccxt/ccxt/tree/master/examples/py And read the Manual, here: https://github.com/ccxt/ccxt/wiki/Manual... If something is not clear there – google for the term, search for `python tutorials`, `python async`, `getting started with python`, and search on youtube as well. Unfortunately, I can't really teach all the basics of programming, because the issue format is not suitable for that... even though i'd want to help, there's just too many questions, hope for your understanding. There's better online resources for that. But I'd be happy to help your questions related to CCXT usage, if you have any.

**Comment by tezeug** [comment]
I need a little help with one more thing. I would like to make this condition:

if (BitMEX.fetch_open_orders() = None):
   ...

Just call some function when there are none opened orders but this does not work.

**Comment by kroitor** [comment]
@tezeug 

```Python

open_orders = BitMEX.fetch_open_orders()

if open_orders:
   # your code
```
or
```Python
open_orders = BitMEX.fetch_open_orders()

if len(open_orders) == 0:
    # your code
```
or
```Python
open_orders = BitMEX.fetch_open_orders()

if len(open_orders):
    # your code
```

\+ a million other ways, if you know Python. Which is beyond the scope of CCXT )
