### ISSUE TITLE
binance ohlcv 15m candles of 2019-03-12 missing from 02:00 until 08:00

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#5026]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Linux
- Programming Language version: Python 3.7
- CCXT version: 1.18.489
- Exchange: binance
- Method: fetch_ohlcv

Code snippet to reproduce:

```
since_datetime = datetime(2019, 3, 12)
since_timestamp = calendar.timegm(since_datetime.timetuple()) * 1000
candles = binance.fetch_ohlcv('BTC/USDT', '15m', since_timestamp, 500)
```

Result:

![image](https://user-images.githubusercontent.com/1702718/56697933-7a352c00-66f0-11e9-98d6-71ad642a2b4a.png)

Saved in a DB:

![image](https://user-images.githubusercontent.com/1702718/56697944-84efc100-66f0-11e9-8596-b6e694bfa2b8.png)

As you can see in the screenshot, 15m candles from 02:00 until 08:00 are missing, wtf?
Is it me or this is some weird bug affecting Mach 12th on binance? I tried another pair, e.g. NANO/BTC, all other days (even before March 12th, e.g. from March 1st until March 11 all good) are fine, but March 12th is missing those candles.

Ideas?

**Comment by kroitor** [comment]
> As you can see in the screenshot, 15m candles from 02:00 until 08:00 are missing, wtf?

They had a downtime due to a system upgrade. It was announced here:

- https://support.binance.com/hc/en-us/articles/360024825992-System-Upgrade-Notice

And this is documented in our Manual – some candles can be missing ) You're not guaranteed to get a continuous timeline. Every exchange will have a downtime at some point. That's just how it is. Sorry, if that contradicts your expectations, but, unfortunately, we can't really workaround this in the lib, for obvious reasons )) Let me know if that doesn't answer the question.

**Comment by firepol** [comment]
Thanks for the answer, now I can sleep in peace :D

I was quite puzzled because the data in tradingview shows up:

![image](https://user-images.githubusercontent.com/1702718/56698419-2a576480-66f2-11e9-8dc5-4b69f979e08d.png)

So if they had a downtime, how come TV doesn't show a "hole" in their charts? TV is faking it?
Anyway, if it was downtime I don't expect to get magic data. Really good to know.

Thanks again and cheers

**Comment by kroitor** [comment]
> how come TV doesn't show a "hole" in their charts? TV is faking it?

That's interesting, of course, however i don't know much about their inner workings... Have you tried asking them? )
