### ISSUE TITLE
Is there an easy way to generate a PNL graph?

### ISSUE THREAD

**Issue by Jens1989** [ccxt/ccxt#5037]
Programming Language version: Python 3.6.4
CCXT version: 1.18.437
Exchange: Binance

Hi,

I was wondering if there is an easy way to generate a PNL graph from the trade history? I've looked through the documentation and I can't find anything. It's possible I might have to create something myself but I wanted to double check in case I missed it.

thanks

**Comment by ttodua** [comment]
this issue seems too much old without any traction. closed for now, if anyone has any input, let us know.
just to add 2 words - ccxt aims to return the data what it is meant for, other than that, users can easily find out any external charting/graphing library, which will manipulate the data into desired visuals.
