### ISSUE TITLE
fetch_my_trades Error

### ISSUE THREAD

**Issue by tezeug** [ccxt/ccxt#5044]
OS: Kubuntu 19.04 64-bit
Programming Language version: Python 3.7
CCXT version: 1.18.494
Exchange: BitMEX
Method: fetch_my_trades(symbol = "BTC/USD", params = {"filter": {"open":True}})

I am trying to fetch currently opened trades / positions but get this error. It works with orders but not trades. Thanks

Traceback (most recent call last):
  File "FInBot.py", line 33, in <module>
    FT = BitMEX.fetch_my_trades(symbol = S1, params = {"filter": {"open":True, "side":"buy"}})
  File "/home/d9635776/.local/lib/python3.7/site-packages/ccxt/bitmex.py", line 348, in fetch_my_trades
    response = self.privateGetExecutionTradeHistory(request)
  File "/home/d9635776/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 404, in inner
    return entry(_self, **inner_kwargs)
  File "/home/d9635776/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 433, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/d9635776/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 429, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/d9635776/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 521, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/d9635776/.local/lib/python3.7/site-packages/ccxt/bitmex.py", line 917, in handle_errors
    raise BadRequest(feedback)
ccxt.base.errors.BadRequest: bitmex {"error":{"message":"filter columns are not valid","name":"HTTPError"}}

**Comment by tezeug** [comment]
I have also tried "ordStatus":"open" but it prints just [] although there is an open BUY position (trade).

**Comment by kroitor** [comment]
@tezeug 

First, you should understand the difference between the Unified API and the exchange-specific implicit API methods. It is explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints

>  It works with orders but not trades.

In general, you can't just use any names of params with any method of any exchange. Those params are exchange-specific, so you should only specify the params and values as documented in the docs for the exchange in question, as explained here:
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

For bitmex the corresponding docs are here:

- for positions (`privateGetPosition`): https://www.bitmex.com/api/explorer/#!/Position/Position_get (supports `filter`, `columns` and `count` params. the actual field in the filter is called `isOpen`)
- for trades (`fetch_my_trades` or `privateGetSettlement`): https://www.bitmex.com/api/explorer/#!/Settlement/Settlement_get (supports `symbol`, `filter`, `columns`, `count`, `start`, `reverse`, `startTime`, `endTime` params)

You're passing a parameter named `open` or `ordStatus` which is not supported by any of those endpoints. Therefore you're not getting the results. However, as you've noted here: https://github.com/ccxt/ccxt/issues/5036 – the `filter` parameter can be used to filter by side in some cases.

> I have also tried "ordStatus":"open" but it prints just [] although there is an open BUY position (trade).

Let's also clarify: an `open` position` is not a `trade`. A *trade* is a settled sell or buy, and each *position* may have many trades within itself, while still being open. So, the unified `fetch_my_trades` method won't give you a list of positions. In order to get it you need to call the corresponding `privateGetPosition` *implicit method* as described here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods, so to fetch a list of positions with bitmex:

```Python
import ccxt
exchange = ccxt.bitmex ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True
})
params = {
    # your filtering params here, if necessary
}
```

Also, this issue is a duplicate, because most of these answers are either documented in the Manual or have been answered here:

- https://github.com/ccxt/ccxt/issues/3596
- https://github.com/ccxt/ccxt/issues/2499
- https://github.com/ccxt/ccxt/search?q=private_get_position&type=Issues

But, anyways, sorry for the delays with my replies, sometimes, the quickest way to get an answer is to search for `bitmex positions` first and foremost ) Hope this clarifies it, let us know if not )

**Comment by tezeug** [comment]
I really thank you a lot for your time. I appreciate it because I know you definitely have a lot of work to do and I am happy that you also find a time to update CCXT. Have a good day 🙏😊!
