### ISSUE TITLE
Are API keys and secret credentials safe?

### ISSUE THREAD

**Issue by ibesora** [ccxt/ccxt#5050]
Hello, 
is there any guarantee that secret keys are not sent elsewhere? Can that be done?
Could someone merge changes to ccxt that take API keys and secrets and store somewhere on their cloud so they could have access to your account?

These library seems such a nice idea and work but taking into account the nature of the data (money exchanges) I'm not really sure how we, as developers, can be sure about giving our API secrets without thinking about it.

**Comment by kroitor** [comment]
Hi!

> is there any guarantee that secret keys are not sent elsewhere?

Yes, this is guaranteed in the following way: this project is open-source, so the developer can read the code and see what's happening with the secret key within the library – and from there any sufficiently-experienced developer can see that CCXT is absolutely honest and transparent. The keys are never sent anywhere, and this is the security policy that is implemented throughout this library. 

This library has been reviewed by a few thousands of developers, among them are very highly skilled coders and they haven't found anything suspicious. CCXT has 10k stars, more than 2k clones, more than 7 hundred dependent projects, etc – if there was an obvious hole, someone would shout about it. Moreover, the independent devs have helped build it out extensively themselves. This lib has more than 3 hundred people from all over the world involved in the development of it. The guarantee is provided by the common people based on the open nature of this project )

However, this library is licensed under MIT which states "no guarantee, use as is at your own risk". So, for most open-source projects, the guarantee you want should be provided to you by yourself first and foremost. In other words, don't install and run the code that you haven't checked for security personally, because other people may be lying to you. Even me. Even now.

> Can that be done?

Yes, if someone substitutes your CCXT installation with a hacked version of it – your keys may be stolen. But if that happens, it is not a failure of CCXT, but more a failure of your security administration. Any code can be hacked. Your operating system can be hacked in the same way. So, it's always possible, and the possibility depends on your own security policies more than on the CCXT codebase.

> Could someone merge changes to ccxt that take API keys and secrets and store somewhere on their cloud so they could have access to your account?

The right to merge is very restricted, only three devs from the core team have that permission, and three are the initial authors of the project. We review each and every PR for security. We don't do massive-merges blindly and we are very picky. So far, we haven't merged anything that would compromise the security, and we've managed to keep the reputation clean for more than 2 years. 

At some point we can try to add the cheating code that will take your keys and will send it to us. And then wait till you download the update. However, there's more than 700 independent people on Github (apart from the other places) who constantly watch each and every edit we make, so, if even if we try a trick like that – it won't go unnoticed. Doing so will immediately ruin everything we've been fighting for. In order to guarantee to completely protect from that – just become a watcher. So, ultimately, it's up to you how much trust or distrust you want to put into it. You can check each update for security to ensure that your security isn't compromised. And if you don't check bits of your software regularly – your security is already compromised.

Hope that answers the question ) Let us know if not)
