### ISSUE TITLE
HitBTC disable USDT->USD mapping?

### ISSUE THREAD

**Issue by tiagosiebler** [ccxt/ccxt#5078]
- Programming Language version: node 10x
- CCXT version: Latest
- Exchange: HitBTC
- Method: exchange.fetchBalance()

It seems ccxt is automatically converting the "currency" for my fetchBalances result, from USDT to USD. Can I disable this somehow? I've tried this in my exchange properties:
```
      commonCurrencies: { 
        USDT: 'USDT',
        USD: 'USD'
      }
```

Yet the balance result from the exchange still reports that my USDT balance is for the "USD" currency (which is invalid).

**Comment by kroitor** [comment]
If you're using `hitbtc` I'd suggest to switch to `hitbtc2` instead, also, make sure that your ccxt version is up to date.

Here's how you test it (there is no USDT → USD conversion by default there):

```JavaScript
const ccxt = require ('ccxt')
const exchange = ccxt.hitbtc ({ // or ccxt.hitbtc2
    enableRateLimit: true,
    apiKey: 'YOUR_API_KEY',
    secret': 'YOUR_SECRET',
})

;(async () => {
    console.log ('CCXT version:', ccxt.version)
    const balance = await exchange.fetchBalance ()
    console.log (balance)
}) ()
```

↑ You should see the following output:

```
{
    info: [ ... ], // raw exchange response as is
    ...,
    USDT: { free: 0, used: 0, total: 0 },
    ...,
    free: {
        ...,
        USDT: 0,
        ...,
    },
    used: {
        ...,
        USDT: 0,
        ...,
    },
    total: {
        ...,
        USDT: 0,
        ...,
    }
}
```

↑ No USDT → USD conversion here.

The balance structure is documented in the Manual here:
- https://github.com/ccxt/ccxt/wiki/Manual#balance-structure

There is, however, a USDT → USD conversion (the other way around), because HitBTC trades USDT and calls it USD as explained here: 

- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency

You can switch USDT → USD conversion off by doing the following:

```JavaScript
const ccxt = require ('ccxt')
const exchange = ccxt.hitbtc ({ // or ccxt.hitbtc2
    enableRateLimit: true,
    apiKey: 'YOUR_API_KEY',
    secret': 'YOUR_SECRET',
    'commonCurrencies': {
        'USD': 'USD',
    },
})
```

Let us know if that doesn't resolve it for you. Feel free to reopen it or just ask further questions, if any.

**Comment by tiagosiebler** [comment]
> There is, however, a USDT → USD conversion (the other way around), because HitBTC trades USDT and calls it USD as explained here:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency

Hi @kroitor , thanks for helping. This is actually my problem (with hitbtc2). The exchange itself doesn't use "USD" anywhere. "USDT" is specifically defined as "USDT", at least in the UI - is this different on the API level, or why is this automatically mapped to USD?

![Screenshot 2019-05-08 at 12 15 13](https://user-images.githubusercontent.com/14090872/57371625-1f3d1380-718b-11e9-970a-cfc19b1d4a9e.png)

**Comment by kroitor** [comment]
> The exchange itself doesn't use "USD" anywhere. "USDT" is specifically defined as "USDT", at least in the UI - is this different on the API level, or why is this automatically mapped to USD?

Yes, exactly. In their API, they designate that currency as "USD", you can verify that if you check the raw `info` field from their fetchBalance API response, it contains the following:

```
                    { currency_code: "USD", cash: "0", reserved: "0" },
```

↑ So, their API uses the "USD" code internally, therefore that mapping exists there.
