### ISSUE TITLE
connecting to a test environment

### ISSUE THREAD

**Issue by doepat** [ccxt/ccxt#5081]
hi, if i want to play around i want to make use of e.g. a test environment. with one exchange i found the possibility to enter a test environment. E.g. https://exchange.com:8000 

if i have a look at the example binance-test-order.py i could replace "binance" with "my exchange" but i doubt that i am hitting the test environment with the special port....how could i influence this?

thanks 
best regards

**Comment by kroitor** [comment]
Hi!

Sorry for the long delay with the answer!

You need to understand how testing environments work with exchanges. First of: there is no standard way to _"run in testing mode"_  – not every exchange has a testing environment at all. The exchanges that have it – all do it differently, so the testing functionality is exchange-specific and you need to consult the API docs for the exchange in question in order to understand how to test it.

In general, some exchanges will expose two types of testing:
- A sandbox base URL for testing – that is exposed in `this.urls['test']` and if the exchange has a sandbox, you can switch to that sandbox by doing something similar to the following:
```Python
exchange = ccxt.gdax ()
exchange.urls['api'] = exchange.urls['test']  # switch to the sandbox testing base URL
```
- Or in other cases, a special parameter for testing this or that method, for example, binance `createOrder` allows testing orders as described here: https://github.com/ccxt/ccxt/issues/2552 by [Overriding Unified API Params
](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params). In order to use it properly you should as well consult the API docs for the exchange in question.

Hope that answers the question.
