### ISSUE TITLE
Is the ordering of base/quote currencies normalized across exchanges?

### ISSUE THREAD

**Issue by davidonlaptop** [ccxt/ccxt#5099]
Say we have the symbol "BTC/USD" on HitBTC. Is it possible this market at another exchange is "USD/BTC" ?

If base/quote order is always the same for a currency pair, then is there a way to fetch that list from ccxt (eg. without connecting to an exchange)?

**Comment by kroitor** [comment]
> Say we have the symbol "BTC/USD" on HitBTC. Is it possible this market at another exchange is "USD/BTC" ?

Yes, some exchanges trade BTC for USD, others trade USD for BTC. 

Most of exchanges tend to have crypto on the base side and fiat or stablecoins on the quote side (BTC/USD, BTC/USDT, ETH/USD, LTC/USDT, ...), except the ETH/BTC, USDT/USD and a few other pairs, probably. However, there is no common standard across all exchanges. So, there may be an exchange with a BTC/ETH pair or a USD/LTC pair.

> If base/quote order is always the same for a currency pair, then is there a way to fetch that list from ccxt (eg. without connecting to an exchange)?

Nope, we don't recommend you to rely on prehardcoded lists, because every day tens of new pairs appear. Some pairs are delisted as well – that can happen quite frequently, on a daily basis. And even if the exchange does have some trading pair or trading symbol in general, that information is not enough to tell if the market is currently active, available for trading and so on. Some exchanges turn specific pairs on and off, so you have to get not just the listing of pairs, but all active statuses of each pair up to the moment – otherwise the info is quickly outdated. And you also want to check the currencies, because if you trade ETH/USDT and depositing/withdrawing ETH or USDT may be temporarily disabled due to maintenance or other reasons.

If the list of pairs of your interest is short and well-defined, and those pairs are popular – you can hardcode those, but in general – that is not recommended and will yield outdated information in 99% cases.

Hope that answers your question. Let us know if not.

**Comment by kroitor** [comment]
More about it here: https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

**Comment by davidonlaptop** [comment]
Thanks for the quick and detailed answer @kroitor !

> Yes, some exchanges trade BTC for USD, others trade USD for BTC.
Got it! That was not immediately obvious to me from the doc. Thanks

So one last question, if we can't rely on the markets to be stable but at the same time fetching the markets before every transaction could be costly... is there a recommended update frequency that you recommend, or that you are using for yourself?

**Comment by kroitor** [comment]
@davidonlaptop it depends on your strategy, but i'd recommend to [reload them](https://github.com/ccxt/ccxt/wiki/Manual#market-cache-force-reload) at least once in 12-24 hours.

**Comment by davidonlaptop** [comment]
ok cool!

That gives a good reference point,

Thanks for building this great library!
