### ISSUE TITLE
 Error with request for withdrawal kraken

### ISSUE THREAD

**Issue by lantedz** [ccxt/ccxt#5101]
- OS: Windows
- Programming Language version: Python
- CCXT version: Last
- Exchange: Kraken
- Method: Withdraw

I'm trying to make a withdrawal request, but I get an error, I can not understand what the problem is.

ccxt.base.errors.ExchangeError: kraken withdraw requires a 'key' parameter(withdrawal key name, as set up on your account)

exchange = ccxt.kraken({"apiKey": "kkkey,
                        "secret": "sssecret", })
code = "ETH"
amount = 0.01
address = "address"
tag = None
withdrawal = exchange.withdraw(code, amount, address, tag, {})

Traceback (most recent call last):
  File "C:/Users/Name/PycharmProjects/kraken/main.py", line 26, in <module>
    withdrawal = exchange.withdraw(code, amount, address, tag, {})
  File "C:\Users\Name\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ccxt\kraken.py", line 1266, in withdraw
    raise ExchangeError(self.id + " withdraw requires a 'key' parameter(withdrawal key name, as set up on your account)")
ccxt.base.errors.ExchangeError: kraken withdraw requires a 'key' parameter(withdrawal key name, as set up on your account)

**Comment by kroitor** [comment]
Kraken doesn't allow withdrawals to direct addresses, so, the address has to be predefined with their website, and when you create a withdrawal address it asks you for a name and an address:

![Screen-Shot-2019-05-11-at-17 55 26](https://user-images.githubusercontent.com/1294454/57571385-380d2980-7416-11e9-8e01-45da2d115f61.jpg)

The name entered there – is the `key` that the `ExchangeError` exception is warning you about. It is not related to your API keys. It just so happens, that the name of that parameter with their API is a bit confusing.

So, in order to withdraw with Kraken (and this is specific to Kraken), you need to pass an extra parameter in the last argument, like so:

```Python
exchange = ccxt.kraken({
    "apiKey": "kkkey,
    "secret": "sssecret",
    "enableRateLimit": True  # This is required by the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
code = "ETH"
amount = 0.01
address = "address"
tag = None
params = {
    'key': 'TheNameOfYourAddressAsDefinedOnTheirWebsite',
}
#                                             params go here ↓
withdrawal = exchange.withdraw(code, amount, address, tag, params)
```

Let us know if that doesn't answer the question.

See also: https://github.com/knowm/XChange/issues/1085

**Comment by guillaumepat** [comment]
This is terrible...
