### ISSUE TITLE
kraken {"error":["EAPI:Invalid signature"]}

### ISSUE THREAD

**Issue by xmurobi** [ccxt/ccxt#5128]
- OS:
MacOS 10.10.5

- Programming Language version:
Python 3.5.0

- CCXT version:
1.18.529

- Exchange:
Kraken

- Method:
fetch_balance()

exchange = ccxt.kraken({
    'apiKey': 'key',
    'secret': 'sec'
})
exchange.verbose = True
exchange.fetch_balance()

got 
ccxt.base.errors.ExchangeError: kraken {"error":["EAPI:Invalid signature"]}

**Comment by kroitor** [comment]
@xmurobi have you tried the troubleshooting sequence? Most often this is caused by reusing keys that have been used by another software (the other software will screw your nonce).

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Also, you have to enable the rate-limiting, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Let us know if that doesn't help.

**Comment by xmurobi** [comment]
@kroitor I had changed to another PC which use a clean windows 10 system, python 3.5.4 which only run the code to connect and fetchBalance from Kraken and got same error. Also, I use the ratelimit last and this time.

**Comment by kroitor** [comment]
@xmurobi the computer you try from doesn't make a difference, you should try with a fresh new keypair – have you tried to create a new keypair with kraken website and using that keypair with this code snippet:

```Python
exchange = ccxt.kraken({
    'apiKey': 'key',
    'secret': 'sec',
    'enableRateLimit': True,
})
exchange.fetch_balance()
```

?

**Comment by xmurobi** [comment]
@kroitor I know the reason. I had open the 2fa for this API key in Kraken security setting page. After I close the 2fa for this API key, everything works fine now.

**Comment by kroitor** [comment]
@xmurobi ok, glad you've figured it out, thx for reporting back – really appreciate that, i'm sure this will be helpful to others as well!
