### ISSUE TITLE
exmo trade parse 'injects' a fee

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5130]
`fetchMyTrades` in exmo injects a fee into the parsed trade based on the metadata of the class (the json response from the exchange doesn't include the fee).

Is this a sensible, or normal thing to do?  Feels like it could give invalid results, say if they change their fees, or the user has a different fee structure to that which is specified in ccxt.

**Comment by LiBin5255** [comment]
thanks you so much ,but I'm jsut a rookie ! so i'm kepping quiet right now ! but I believe in a short time .
I will definitely make my contribution !

**Comment by xpl** [comment]
> Is this a sensible, or normal thing to do?

We previously fetched their fees programmatically from their website, by parsing their web front-end output. But since then it got broken (those requests are now quickly getting banned), that forced us to switch to hard-coded fees, so...

> Feels like it could give invalid results, say if they change their fees, or the user has a different fee structure to that which is specified in ccxt

...yes, it can happen. But I suppose they don't have fees in their API output because they don't plan to change them anytime soon. So they kinda encourage their users to use hard-coded values.

**Comment by LiBin5255** [comment]
![insta](https://user-images.githubusercontent.com/50601015/57822908-2b972100-77c8-11e9-9136-ca08adf5c97b.jpg)
[install-options.txt](https://github.com/ccxt/ccxt/files/3185216/install-options.txt)
[package-versions.txt](https://github.com/ccxt/ccxt/files/3185218/package-versions.txt)
#HTML+CSS to be used in website building!
