### ISSUE TITLE
Supporting multiple fees in different currencies in trades

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5135]
I notice that itbit has the concept of a fee AND a rebate modelled separately in their API.  The code that deals with in in `parseTrade` looks like:

                if (feeCurrency === rebateCurrency) {
                    feeCost = this.sum (feeCost, rebatesApplied);
                    result['fee'] = {
                        'cost': feeCost,
                        'currency': feeCurrency,
                    };
                } else {
                    result['fees'] = [
                        {
                            'cost': feeCost,
                            'currency': feeCurrency,
                        },
                        {
                            'cost': rebatesApplied,
                            'currency': rebateCurrency,
                        },
                    ];
                }

... it creates a `fees` array instead of a `fee` object.  Is this a common model?

Or could we have a standard `fee`, which can be an array of objects or a single object?  Or always have `fees` as an array, typically an array of length one except in cases like that above?

**Comment by kroitor** [comment]
> Is this a common model?

Yes, so far. It is not documented yet, because it's still "in the works".
The current model is to have either `fee` or `fees`, the latter being an array.

> Or could we have a standard fee, which can be an array of objects or a single object? Or always have fees as an array, typically an array of length one except in cases like that above?

In general, a typecheck is harder than a key lookup, I think. And if we switch to an array – that might break the backward-compatibility... So, we need to consider it carefully... @xpl, @tankakatan what's your opinion on this?

**Comment by xpl** [comment]
> And if we switch to an array – that might break the backward-compatibility...

That will surely break all of the people's current code. But. I personally consider it a headache, having in some cases `fee` (object) and in some cases `fees` (array), because everywhere I need to consider fees, I currently need to write a coercion code that normalizes that to a general form (array):

```javascript
const fees = trade.fees || [trade.fee]
```

Leaving just `fees` alone would certainly be a right thing to do. What we can do is to perform a smooth transition, outputting both `fee` (in case of a single fee, for backward compatibility) *and* `fees` (always, for future code). Then remove any mentions of `fee` from the documentation, and explicitly announce that `fee` will be removed soon. Then finally remove `fee` some months later, raising the major version number.

**Comment by kroitor** [comment]
> What we can do is to perform a smooth transition

Yeah, I think it's the way to go. We should start adding `fees` everywhere.

**Comment by ttodua** [comment]
`fees` are being provided now in supported exchanges. closing this topic for now.
