### ISSUE TITLE
Documentation on the experimental rate limiter

### ISSUE THREAD

**Issue by davidonlaptop** [ccxt/ccxt#5152]
Hi @kroitor,

Is there documentation on the status of the experimental rate limiter algorithm?

More specifically:
- Is there some exchanges where setting `exchange.enableRateLimit = true` does not actually throttle anything (and should be considered unsafe)?
- Is it considered "experimental" because it uses safe default and could be optimized in some scenarios, or because the odds of getting banned are actually high?
- Some exchanges (such as Kraken) have different rate limit per operation type, does the current algorithm supports it?

**Comment by kroitor** [comment]
Hi, @davidonlaptop !

Please, see the details on the rate-limiter here: https://github.com/ccxt/ccxt/issues/1399#issuecomment-359233015

> Is there some exchanges where setting exchange.enableRateLimit = true does not actually throttle anything (and should be considered unsafe)?

No. It works in the same way for all exchanges. 

> Is it considered "experimental" because it uses safe default and could be optimized in some scenarios, or because the odds of getting banned are actually high?

It is experimental because the implementation is not finalized and may be changed in the future. Depends on the feedback we get. There actually two of them a naive rate-limiter (a less experimental) and a tokenBucket rate-limiter (a more experimental one).

> Some exchanges (such as Kraken) have different rate limit per operation type, does the current algorithm supports it?

The tokenBucket implementation does support variable call "costs", basically, you can think of "different rate limit per operation type" as if it was different cost per operation call. However, it is still in the works, and will require some hacking, if you want to use the existing `tokenBucket` implementation properly. That is, until we generalize it even further. Adding variable call costs is in the plans, and the `tokenBucket` was added as an intermediary step in that direction. After we finalize the it, we will add the necessary api mappings for endpoint-specific rate-limits.

Hope that answers the question, see the post linked above for more.

**Comment by davidonlaptop** [comment]
Wow! thanks for the super quick response!

I'll be looking at the link provided.
