### ISSUE TITLE
Check if withdraw is enabled for a specific API key?

### ISSUE THREAD

**Issue by kobej1** [ccxt/ccxt#5158]
Hello!

Is it possible to check if withdraw is enabled for a specific API key without actually withdrawing? I've read the manual but I couldn't find anything about this topic.  

Regards,
Kobe Janssens

**Comment by kroitor** [comment]
Hey! )

Unfortunately the exchanges very rarely provide that information beforehand, in general. Therefore this aspect is not completely unified yet. However, we are going to unify it as soon as possible by implementing a set of method for permissions. 

With the exchanges that do provide it, you can currently query that information in a non-unified exchange-specific way by using implicit API methods as described here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods.

Currently, the exchange-wide withdraw flags are unified in `this.currencies`, but the user-specific restrictions and key-specific permissions are not unified yet due to the above reasons. To be done asap.

Let us know if that doesn't answer the question.

**Comment by kroitor** [comment]
Also, see this related PR: https://github.com/ccxt/ccxt/pull/1424

**Comment by kobej1** [comment]
Thanks for your answer! 

I've tried some things and I came to the conclusion that when I'm withdrawing only 1 satoshi, I get another error message than when use an api key without withdrawing enabled. But is it possible to store the error message in a variable (I use Python3) so I can compare them?

**Comment by kroitor** [comment]
> But is it possible to store the error message in a variable (I use Python3) so I can compare them?

Yes, check out how that is done here: https://github.com/ccxt/ccxt/pull/1424/files#diff-dd6e086b520aaa8946e9b57edabf2db5R799. We will add something close to that to the codebase as soon as we can.

**Comment by faberkeping** [comment]
Hi! Any updates on which exchanges that are available with the `fetchPermissions`?
