### ISSUE TITLE
Problem with using fetch_trades() with the since argument

### ISSUE THREAD

**Issue by stevebdh** [ccxt/ccxt#5173]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
@stevebdh can you please follow the above guides precisely? We need the code snippet to reproduce it and both the verbose request and verbose response, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by stevebdh** [comment]
I have gone through the manual, and I have run lots of tests.  I am using Python 3.7.2, CCXT 1.18.359, and calling against the Binance exchange.  

The problem is with the fetch_trades() call.  I am supplying a 'since' parameter in milliseconds, representing the timestamp I want to start fetching from.  When I get back the array of trades, the earliest trade is in the future of my 'since' argument.  

While this is possible, I have then provided 'since' arguments that are 5 minutes, 10 minutes, and even 15 minutes in the past of what I really want, and then provided a limit of 25 trades.  In all those instances, I still get returned trades that start after the original 'since' argument provided (before I went to the past by x minutes).  

When I tried providing a 'since' value 1 hour before my desired time, I received an array of trades that started in the past of my desired time, but in the future of the supplied 'since' value.  Fortunately, this array did contain the trade I was originally looking for, but this is not a repeatable procedure.  I never know how far in the past to go to ultimately pick up the trade I want.  More importantly, I don't understand why the 'since' argument is not being handled properly.  By the way, the 'since' argument works fine with the fetch_ohlcv() calls.

Any guidance is appreciated.

**Comment by kroitor** [comment]
> but in the future of the supplied 'since' value.

That's correct, and that's what `since` means – you will get `limit` trades that happened after the milliseconds timestamp designated in `since`. In other words, date-based pagination works in ascending order with Binance.

**Comment by stevebdh** [comment]
Yes, but I am going into the past and I still get trades that occurred in the future of what I want.  If I go back far enough in time and make the call, then I get the trades I want.  This is inconsistent behavior that I don't understand.

**Comment by kroitor** [comment]
> Yes, but I am going into the past and I still get trades that occurred in the future of what I want. If I go back far enough in time and make the call, then I get the trades I want. This is inconsistent behavior that I don't understand.

Well, first of, if you [browse the docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#compressedaggregate-trades-list) for their trade endpoints, you'll immediately notice that Binance doesn't really support date-based pagination for public trades, and the only endpoint that supports the date-based pagination is the `aggTrades` endpoint. That is the endpoint we're using. 

The way it paginates the results is consistent if you think about it in terms of `since` + `limit`. And there's also a 1-hour range restriction that comes from Binance docs. This is actually consistent with how most of exchanges work with date-based pagination. And this is the default behavior of the exchange. They require both `startTime` and `endTime` to be in the range of one hour and their output will contain trades starting after `startTime` and before `endTime`, and if you apply _"max limit"_ to this, you will get up to max amount of trades after `startTime`. This just naturally follows from how the pagination works with this particular exchange and with many other exchanges.

You can [override those params](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params) and specify a narrow timerange as shown below:

```Python
import ccxt
symbol = 'ETH/BTC'
exchange = ccxt.binance({
    'enableRateLimit': True,  # as required by the Manual
})
params = {
    'startTime': '1558531200108',
    'endTime': '1558532200108',
}
trades = exchange.fetch_trades('ETH/BTC', None, None, params)
```

Let us know if that doesn't answer the question.

**Comment by stevebdh** [comment]
Here is the detail of what I am talking about:

I make a call to fetch_trades() with a 'since' value of 20 minutes (supplied in milliseconds) earlier than what I want.  The returned list of trades starts with a trade that occurs 3 minutes and 55 seconds after the time I wanted a trade for.  I would even accept a trade a little in the past of the time I wanted.

So, you might say that there just weren't any trades at or near the time I was interested in.  However, I ran the code again with a 'since' value of 1 hour earlier than what I wanted.  The returned list of trades now has trades that occurred prior to the time I want.  In fact, the returned list has a trade that occurs 1 minute and 56 seconds prior to the time I want.

So, the main question is why is the call returning trades that don't match the 'since' value?  I read your response, but if Binance doesn't support date-based pagination for public trade data, then why is it returning anything at all?  I will try your suggestion and see what happens.  Thanks.

**Comment by kroitor** [comment]
> So, the main question is why is the call returning trades that don't match the 'since' value?

Why do you think they should match that value exactly? People trade and public aggregated trades keep coming not on your specified `since`, but when they want to trade. That happens all the time, but it doesn't have to be a regular stream of 1 trade per millisecond or whatever. Trades happen in bulk, then there's a random delay, then they happen again (this is how matching works in general). So, your `since` filter will return the nearest trade after `since` up to max limit trades after that moment (not before).

> I read your response, but if Binance doesn't support date-based pagination for public trade data, then why is it returning anything at all?

I guess, you should forward this question to Binance, we just implement it the way it works and it is unified with other exchanges that implement date-based pagination (other exchanges accepting `since` work in the same way, mostly, with very few exceptions).

**Comment by kroitor** [comment]
@stevebdh alternatively, you can switch the `fetchTradesMethod` option to use a different implicit endpoint, for example, `publicGetTrades` instead of the default `publicGetAggTrades`. You will get just the most recent set of individual trades though, without pagination. Another alternative for Binance would be to use id-based pagination with `publicGetHistoricalTrades`.

**Comment by stevebdh** [comment]
Thanks for your response.  Just to be clear, I am not trying to get a specific trade based on a desired time.  I am trying to get a trade as close to the desired time as possible, but one that occurs prior to the desired time.  For what I am doing, I cannot use aggregates.  As stated, I need to get the specific trade that occurs as closely as possible, but earlier, to my desired time.

Since I need historical data, I cannot use the publicGetTrades call.  I guess what you are saying is that I should try either id-based pagination or the startTtime - endTime params method.  I will look into these ad see what happens.  Thanks again for the assistance.

**Comment by derekmahar** [comment]
> Thanks for your response. Just to be clear, I am not trying to get a specific trade based on a desired time. I am trying to get a trade as close to the desired time as possible, but one that occurs prior to the desired time. For what I am doing, I cannot use aggregates. As stated, I need to get the specific trade that occurs as closely as possible, but earlier, to my desired time.

I have the identical general use case, except I can use aggregate trades instead of individual trades and I also need to query older trades on exchanges other than Binance.  Given the timestamp of an ETH/BTC trade, I need the price of ETH/USD or BTC/USD as of (on or just before) this timestamp in order to as closely as possible approximate the fair market value in USD of the ETH/BTC trade.

**Comment by derekmahar** [comment]
> That's correct, and that's what `since` means – you will get `limit` trades that happened after the milliseconds timestamp designated in `since`. In other words, date-based pagination works in ascending order with Binance. Otherwise we would call that argument `before`. So, this is by design, and this is how pagination works in most cases where `since` is supported on the exchange side.

@kroitor, why doesn't method `fetch_trades` also support a `before` parameter to accommodate exchange APIs that can query trades by time range?

**Comment by derekmahar** [comment]
> > That's correct, and that's what `since` means – you will get `limit` trades that happened after the milliseconds timestamp designated in `since`. In other words, date-based pagination works in ascending order with Binance. Otherwise we would call that argument `before`. So, this is by design, and this is how pagination works in most cases where `since` is supported on the exchange side.
> 
> @kroitor, why doesn't method `fetch_trades` also support `before` (< desired time) or `until` (<= desired time) parameters to accommodate exchange APIs that can query trades by time range?

Nevermind.  According to the documentation for method [`binance.fetch_trades`](https://github.com/ccxt/ccxt/blob/f463e062319b10f6d3728b4a75977819145eb509/python/ccxt/binance.py#L3327), this method does accept an extra parameter [`params[until]`](https://github.com/ccxt/ccxt/blob/f463e062319b10f6d3728b4a75977819145eb509/python/ccxt/binance.py#L3347) that is valid "only used when `fetchTradesMethod` is `'publicGetAggTrades'`, `'fapiPublicGetAggTrades'`, or `'dapiPublicGetAggTrades'`".  I guess parameter `until` isn't common enough among exchanges to elevate it to "unified" status.
