### ISSUE TITLE
 When is the market support for Korea Exchange Upbit?

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#5251]
When is the market support for Korea Exchange Upbit?

**Comment by kroitor** [comment]
@bongkook we will add the support for market orders to Upbit very soon.

**Comment by bongkook** [comment]
thank you for the reply

**Comment by kroitor** [comment]
@bongkook thank you for the patience! 

Unfortunately, we can't really promise the exact dates due to reasons explained here: https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar. Hope for your understanding, we are doing as much as we can to maintain this project.

However, because you have been waiting for a long time, and because we'd like to have that functionality in the library, we've added it in CCXT version 1.18.650 or higher (will be available in 20 minutes or so). So, if you update your version of CCXT to the most recent version, `market` type orders should work with Upbit from there )

Also, note the following:

https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#market-buys

Let us know if you have any issues with it.

**Comment by bongkook** [comment]
Thank you for your thoughtfulness. ^^
I will try to use it immediately.

**Comment by bongkook** [comment]
https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#market-buys
↑↑↑↑The contents of this link may be incorrect.
The key word for this option is incorrect.
    createMarketBuyRequiresPrice [×]
    createMarketBuyOrderRequiresPrice [○]

**Comment by kroitor** [comment]
@bongkook thx for pointing that out, fixed it!
