### ISSUE TITLE
What is a dust trade?

### ISSUE THREAD

**Issue by nazariyv** [ccxt/ccxt#5269]

**Comment by kroitor** [comment]
Usually, small quantities of crypto and fiat funds are called "dust", because a user balance can contain many of them and they are all too small individually. A "dust trade" is a trade with an amount less than minimum amount accepted by the exchange for the currency in question. Many exchanges forbid dust trading. You can't force a dust trade. 

However, in some cases, due to the process of filling up an open order (see the explanation on [how orders are related to trades](https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades)) and also due to fees as well as [market precision and limits](https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits), many orders don't really get filled up entirely for the amount you've ordered. Practically always there remains some "microscopic" dust, naturally. Also, referral programs can generate "dust" amounts on your wallet. Some exchanges also provide means of converting all dust to a particular currency at once, if the user wants to get rid of all the dust using a mechanism allowed by the exchange.

For example, if the user had

```
ETH 0.123 // not dust
FOO 0.00000007 // dust
BAR 0.00000009 // dust
```

and wanted to convert the dust to ETH, the end result after the dust conversion would be something like:

```
ETH 0.123001 // not dust
FOO 0.0
BAR 0.0
```

↑ That would be an allowed set of dust trades.

Let us know if that doesn't answer the question.
