### ISSUE TITLE
Exchanges not returning response dictionary of requests

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#527]
Hi,

I trade with some exchanges and regularly, for some buy, sell ou tranfers requests, my order is placed but no response dictionary is returned, so I do not know if the order was really placed. Is there anything I can do about it, or it's a problem with the exchange's server that happens sometimes?

Thanks fou your support.

**Comment by kroitor** [comment]
@Felipe-Mangueira hi! Do you mean that you place those orders with ccxt? Or in general?

**Comment by Felipe-Mangueira** [comment]
Yes @kroitor, I place all those orders with ccxt.

**Comment by Felipe-Mangueira** [comment]
This happens recurrently with Kraken and sometimes with Mercado Bitcoin. With Bitfinex and others I have tested, it happened just a few times, but it happened anyway.

**Comment by kroitor** [comment]
@Felipe-Mangueira with Kraken it's a usual thing, it has been under huge load for past few months... They barely can handle it. In general, a request to create an order can fail, and in that case you should recover and check the open / closed orders and trades to find out whether it was accepted or not and whether it managed to close or not, while you were recovering. There's no other way to workaround this problem, unfortunately. We also see those timeouts all the time and we have to keep all state in the local memory in order to recover from http failures. It's just how exchanges work. Does this answer your question?

**Comment by Felipe-Mangueira** [comment]
Yes @kroitor, it does. I think I am taking the necessary actions to avoid this problem, unfortunately.
Thanks for your time again, and keep with your great work.

**Comment by kroitor** [comment]
@Felipe-Mangueira ok... you can also try increasing timeout for Kraken if you can tolerate that in your logic. We had to raise it up to 20 seconds, because Kraken takes 15 seconds just to open an order sometimes... Let us know if you have any other questions. Thx!

**Comment by Felipe-Mangueira** [comment]
I have already changed the timeout for Kraken, @kroitor , but not always the exchange returns a timeout error, and when it returns, it doesn't mean the order was not placed, and I have to check it out anyway.

Ok, no problem. I appreciate your tips, anyway.
