### ISSUE TITLE
Error in travis-ci

### ISSUE THREAD

**Issue by PolozovT** [ccxt/ccxt#5281]
};
        let result = await this.privatePostOrderNew (this.extend (order, params));
        return this.parseNewOrder (result);
    } (transpileDerivedExchangeClass @ transpile.js:614)

"Make sure your methods don't have empty lines!"

But when i do "npm run check-js-syntax" it's ok...why?

**Comment by kroitor** [comment]
> But when i do "npm run check-js-syntax" it's ok...why?

Because that particular command checks just the JS syntax, but it's not the full test, just a part of it. It validates JavaScript, but not the generated Python nor the generated PHP syntax, which may be broken if the guidelines from the CONTRIBUTING.md doc are not followed precisely. 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

Let us know if that doesn't answer it. Feel free to reopen this or just ask further questions if any,  will be happy to answer. Thx!
