### ISSUE TITLE
Add a list of non-working exchanges in the wiki?

### ISSUE THREAD

**Issue by ahmedbodi** [ccxt/ccxt#5285]
Might be nice to have? I'm willing to add in the ones i know arent currently working

**Comment by ahmedbodi** [comment]
if you give me access i'd be willing to start adding it to the wiki

**Comment by kroitor** [comment]
I'd suggest a "broken since" flag or some type of date or maybe a link to the breaking issue. In general, we don't edit exchange lists manually – those tables are generated by this script: https://github.com/ccxt/ccxt/blob/master/build/export-exchanges.js

Filling the info in the Manual.md by hand is hard to maintain in terms of future support (may be outdated quickly), so, we would collect that info and populate it with the exchange files in a unified format (we need to decide on it) – and that info would is used to generate those exchange tables with the same exporting script.

> if you give me access i'd be willing to start adding it to the wiki

You already have the access, this entire project is open-source, including the docs, and the docs are sourced from the wiki folder here: https://github.com/ccxt/ccxt/tree/master/wiki (those sources go to github wiki and to RTD and to other doc sites).

I'd suggest to first discuss how we would standardize that info within the exchanges, just to sync the effort )

In general, I would imagine a flag like `"broken": "2017-08-11T00:00:00Z"` or `"shutdown":"2017-08-11T00:00:00Z"`, or

```JavaScript
{
    status: 'ok', // 'shutdown', 'broken', 'maintenance', ...
    updated: "2017-08-11T00:00:00Z", 
    // other flags ?
}
```

let me know your thoughts )

**Comment by kroitor** [comment]
Alternatively, we could standardize the `fetchSystemStatus` or `fetchStatus` unified method to get the exchange info either from the exchange or from the hardcoded exchange properties, if the exchange in question does not offer a status endpoint (many of them do).

**Comment by ahmedbodi** [comment]
Sure, i knew the docs were auto-generated but not the wiki. If we can add something to the exchange classes that would be even better, would save me from having to manually remove them from my code. i could rely on those flags instead then

**Comment by ahmedbodi** [comment]
Status and updated are the two essential ones. With updated i could then use that to re-generate my api files, and can parse status to tell if i should just ignore it or not.

**Comment by kroitor** [comment]
Some exchanges also provide "ETA" (when the maintenance is expected to end), so, the unified structure that could be returned from `fetchStatus` (or hardcoded within the exchange properties) might look like:

```JavaScript
{
    status: 'ok', // 'shutdown', 'broken', 'maintenance', ...
    updated: "2017-08-11T00:00:00Z", 
    eta: "2018-08-11T00:00:00Z",  // when the status is expected to change, approximately
    // other flags ?
}
```

**Comment by ahmedbodi** [comment]
https://gist.github.com/ahmedbodi/5b47ae3502d69993009a898464c5cbd4 is the list i have so far from the previous work i did, do you know what other ones are faulty?

Definitely if some support ETA then we should add that too

**Comment by kroitor** [comment]
Your list is larger than mine )) The more I think of it, the more I tend to unifying it within `fetchStatus`:

```JavaScript
async fetchStatus (params = {}) {
    if (thisExchangeHasAnEndpointForStatus) {
        const response = await this.publicGetStatus (params)
        return this.parseStatus (response); // returns unified structure
    } else {
        return this.status; // returns hardcoded structure from describe()
    }
}
```

> Definitely if some support ETA then we should add that too

Which other flags do you think we may need within the exchange status property?

**Comment by ahmedbodi** [comment]
thats all i can think of tbh, unless you know of any others that exchange's return

**Comment by ahmedbodi** [comment]
We could start off by modifying the base class to have that method but returning ok for all of them, and then modify the known broken exchanges to return hardcoded broken

**Comment by ahmedbodi** [comment]
Then as we go through the exchanges we'd modify them to use the dedicated status enpoints

**Comment by kroitor** [comment]
@ahmedbodi ok, I suggest the following procedure: I will add an example to an exchange that has it and to an exchange that doesn't have it and will add the base property to store the status info, and will then post here, so that you could take that as an example for populating the rest of them. Does that sound ok to you?

**Comment by ahmedbodi** [comment]
sounds good to me, was just about to start adding it to the base exchange lol

**Comment by kroitor** [comment]
@ahmedbodi well, if you have the time – I don't mind at all, just wanted to avoid duplicate work ) I'll try to add the example case asap, hopefully today. However, if you want to give it a try in the meantime – your help is always welcome! ) Thx again )

**Comment by ahmedbodi** [comment]
Working on that in #5286 
What status would be put for exchange's who's api's have changed? error?

**Comment by kroitor** [comment]
> What status would be put for exchange's who's api's have changed? error?

Yeah, I'd put `'error'` there, and I would also add an `url`:

```JavaScript
{
    status: 'ok', // 'shutdown', 'error', 'maintenance', ...
    updated: "2017-08-11T00:00:00Z", // or milliseconds
    eta: "2018-08-11T00:00:00Z",  // when the status is expected to change, approximately

    // a link to an issue reporting the break or a link to exchange's blog post about it
    url: "https://github.com/ccxt/ccxt/issues/5285", 

    // other flags ?
}
```
