### ISSUE TITLE
consistency: set used to undefined for exchanges that do not have support for it

### ISSUE THREAD

**Issue by lead4good** [ccxt/ccxt#5292]
- [ ] find exchanges where used amount in balances is not supported but set to numerical 0 instead of undefined

**Comment by kroitor** [comment]
> the currency should be deleted

We don't "fix" the data, in fact, going back to https://github.com/ccxt/ccxt/pull/5290 it's the kraken fetchBalance that should be fixed in this case, because the `undefined` is the actual truth – the value is really undefined and this is documented in the Manual. We should not put zeroes where the value is undefined, instead we should only fill `free` or `total`, depending on what it is. Also, we should not delete the currencies, even if the corresponding balances are undefined.

> There should be a check when summing up for total, whether one or both of the values is undefined

There is such a check in `this.sum`, so, it will only sum them up if both are undefined. It may be missing in some cases, but we will fix for that.

Let us know if that doesn't answer the issue.

**Comment by lead4good** [comment]
No I'm fine with that behavior, we should keep it consistent though which is why I've updated the issue

**Comment by frosty00** [comment]
We should set it to `undefined` everywhere where it is not supported, and only to 0 if we recieve a response that says `used/blocked/frozen` with a zero value. Thanks for the heads up @lead4good will update the library shortly.

**Comment by kroitor** [comment]
This is now unified as of 1.18.935. Thx for your participation!
