### ISSUE TITLE
get huobipro market limit is wrong

### ISSUE THREAD

**Issue by rj03hou** [ccxt/ccxt#5298]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:centos
- Programming Language version:python3
- CCXT version:1.18.482
- Exchange:huobipro
- Method:loadMarkets

>>> markets=ex.loadMarkets()
>>> markets['CTXC/BTC']['limits']['amount']
{'min': 0.01, 'max': 100.0}

but when create order
ccxt.base.errors.InvalidOrder: huobipro {"status":"error","err-code":"order-limitorder-amount-min-error","err-msg":"limit order amount error, min: `0.1`","data":null}

try in the exchange web, show me the min is 0.1
maybe huobipro's api is wrong, or ccxt wrong

**Comment by frosty00** [comment]
You sir, need to update ccxt.

I'm seeing version `1.18.696` :P

**Comment by kroitor** [comment]
@rj03hou the comment by @frosty00 is correct – do you have the same issue with the most recent version? If you have the same issue after upgrading to the most recent version, then we will need you to copy-paste your **verbose request and response** (we need both parts) and your code to reproduce the issue here (without your keys, of course). Please follow these guides precisely on how to post verbose requests and responses:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
