### ISSUE TITLE
Poloniex getBalance() takes a long time

### ISSUE THREAD

**Issue by tandazhi** [ccxt/ccxt#531]
Hi, 

There are two many assets in Poloniex, so the getBalance() take a long time (about 3 seconds for me) to return. Is there any way to request just several assets (for example, just requesting BTC and BCH) balance? 

Thanks a lot!

**Comment by kroitor** [comment]
@tandazhi, hi!

Unfortunately, we don't control that. It's just how Poloniex works – it returns full balance info, and it does not allow to specify the currencies you're interested in. Actually, the problem is not the size of the response (even if you fetch all balances it is not big enough to add delays). It just takes that long from Poloniex for your request to be processed and we can't workaround it. We believe it's a universally fair for every Poloniex user. There may be some added lags due to your location. In that case we would recommend to host your application in the US, if you really want to target Poloniex. We also see these delays occasionally.

Does this answer your question?

**Comment by tandazhi** [comment]
Hi Kroitor,

Thanks for your quick answer.  I pinged the poloniex and the lag time is only about 200ms, I am wondering if to relocate the application in US, the lag time of fetchBalance() can be controlled within 1 second? Thanks for your suggestion.

Best Regards,

**Comment by kroitor** [comment]
@tandazhi the ping show you the round-trip latency... So, if you are talking to Poloniex ICMP with the ping tool, a ping-packet does not enable the whole Poloniex engine for balances, orders, or other private info of that sort. When you ping, you don't go through their authentication layer, you request does not go through their databases, etc... So with ping you're just scratching the surface. The real lag is coming from the Poloniex **trading** engine, not from **networking**. Their server is just slow to handle all incoming requests, if you send full-featured requests to the engine, not a basic networking ping-pong.

>  I am wondering if to relocate the application in US, the lag time of fetchBalance() can be controlled within 1 second?

The simplest AWS virtual host (VPS instance) costs approximately $0.001 per hour, that is less than one cent. So you can test it, and it's very affordable. The test will show if hosting in US makes any difference.

**Comment by kroitor** [comment]
In other words, `ping` may show 200ms, but the actual balance endpoint can still take 2-3 seconds to reply at the same time.

Let me know if I answered your question or not. Thx!

**Comment by tandazhi** [comment]
Hi Kroitor, 

Thanks a lot for your suggestion. I will test it to see what is the difference.
