### ISSUE TITLE
[therocktrading] txid and address incorrectly parsed for FIAT withdrawals 

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5331]
```
{
  "id": "12564223",
  "info": {
    "id": 12564223,
    "date": "2017-08-07T08:13:50.023Z",
    "note": "GB7IDL401573388",
    "type": "withdraw",
    "price": 4345.93,
    "fund_id": null,
    "currency": "EUR",
    "order_id": null,
    "trade_id": null,
    "transfer_detail": {
      "id": "EXECUTEDBUTUNCHECKED",
      "method": "wire_transfer",
      "recipient": "GB7IDL401573388",
      "confirmations": 0
    }
  },
  "txid": "EXECUTEDBUTUNCHECKED", <-- wrong
  "type": "withdrawal",
  "amount": 4345.93,
  "address": "GB7IDL401573388", <-- wrong
  "currency": "EUR",
  "datetime": "2017-08-07T08:13:50.023Z",
  "timestamp": 1502093630023
}
```

**Comment by kroitor** [comment]
>   "txid": "EXECUTEDBUTUNCHECKED", <-- wrong

↑ That's wrong indeed, however can you explain what's wrong with the following? ↓

>   "address": "GB7IDL401573388", <-- wrong

(in case of fiat we can't fill in anything else there)

**Comment by npomfret** [comment]
The thing that's in address is the IBAN for the transfer.  Doesn't belong in the address field IMO.

**Comment by npomfret** [comment]
@kroitor DSX has a similar problem:

```
{
  "id": "1555922",
  "fee": {
    "cost": 0,
    "currency": "USD"
  },
  "info": {
    "id": 1555922,
    "type": "Incoming",
    "amount": 7465,
    "status": 2,
    "address": "000-628242",
    "currency": "USD",
    "timestamp": 1521202192,
    "commission": 0
  },
  "type": "deposit",
  "amount": 7465,
  "status": "ok",
  "address": "000-628242", <-- wrong
  "currency": "USD",
  "datetime": "2018-03-16T12:09:52.000Z",
  "timestamp": 1521202192000
}
```

**Comment by kroitor** [comment]
@npomfret how do you suggest to workaround it?

**Comment by npomfret** [comment]
Is it appropriate to say this is a FIAT v's crypto problem.  FIAT transfers don't happen on chain so txid and address are inappropriate fields for them.

Is there a way to identify FIAT currencies?  If not, I guess we need that first.

**Comment by kroitor** [comment]
> Is there a way to identify FIAT currencies? If not, I guess we need that first.

To be honest, I would like to avoid remembering properties of tokens in the lib, because I believe the lib should be agnostic to token-specific things.

>  FIAT transfers don't happen on chain so txid and address are inappropriate fields for them.

If that identifies the recipient and the transaction – why not? I don't really see why a fiat transaction could not have an address and a txid.

**Comment by npomfret** [comment]
I my mind fiat transactions _might_ have a transaction id, but i thought the CCXT field `txid` was crypto/blockchain specific? 

They don't have an address though, they go to and from an _account_.  You could overload address with account information but I don't see why, I'd prefer to have a separate field (or fields).  Perhaps a `destination` object is what we need?  It could have a different shape (address, tag, account, bank name, customer name...) depending on the context.

In my project I do model fiat v's crypto currencies because its very important to me.  The stuff I need to do with fiat transactions is quite different to crypto transactions. Currently my solution is to just delete those fields for fiat transactions - I think it would be nice if ccxt handled it, but I understand your reticence.  It's no big deal, but I do think the  things I've pointed out here are misleading.

**Comment by kroitor** [comment]
> I my mind fiat transactions might have a transaction id, but i thought the CCXT field txid was crypto/blockchain specific?

Well, i would agree with you before you opened this issue, but now I'm in doubt ) This is the edge of our standard where it is less defined and we're basically defining it right now together. However, now, as I think of it more, I do believe that even with fiat transactions among banks, there is a transaction id involved, so, maybe filling up txif for fiat is not so bad idea in the light of what will follow next.

> They don't have an address though, they go to and from an account. 

I think of an `address` as an identifier of the account, and the more i think of it the more i tend to consider a bank account number to be equivalent to a crypto address – it identifies the recipient within the systems on the receiving side of a transfer or a transaction.

> You could overload address with account information but I don't see why, I'd prefer to have a separate field (or fields). Perhaps a destination object is what we need? It could have a different shape (address, tag, account, bank name, customer name...) depending on the context.

Yes, but what if you take this one step further. Suppose we have that `destination` field and suppose that for fiat transactions we define that it would contain the identifier of the transaction counterparty account within the receiving bank, as a string, and for crypto transactions we define that it contains the crypto address as a string. Then, suppose that we named that field `address` for historical reasons ) 

In general, your point on the `destination` variable structure (not a string) is of course a very valid point, so I do agree with it logically. Yet it does have its own drawbacks:

- it's not very backward-compatible (if there's a `destination`, why should there be an `address` outside of it for a certain type of transactions among crypto, fiat, pigeonmail and whatever else?.. why should there be any preference for a certain type of transactions above the other at all? – these are all questions that are related to a possible change of the format of the transaction structure)
- deep structures are sometimes less convenient for tabular views and rdbms

> In my project I do model fiat v's crypto currencies because its very important to me. The stuff I need to do with fiat transactions is quite different to crypto transactions. Currently my solution is to just delete those fields for fiat transactions - I think it would be nice if ccxt handled it, but I understand your reticence. It's no big deal, but I do think the things I've pointed out here are misleading.

I suggest that we look for other examples and types of transactions and transfers and generalize it all when we have a bit more info. I don't mind changing it, if it's the right thing to do, even at a cost of backward-incompatibility, but i wouldn't want to rush a quickfix, because it might have implications. Hope for your understanding. Let's do some more research with other exchanges. Your help is very much appreciated!

**Comment by npomfret** [comment]
> I do believe that even with fiat transactions among banks

I'm sure there is, but I've done 500 fiat deposits/withdrawals and so far I've not found any sort of id that has any use.

`I think of an address as an identifier of the account, and the more i think of it the more i tend to consider a bank account number to be equivalent to a crypto address – it identifies the recipient within the systems on the receiving side of a transfer or a transaction.`

I think I agree.  An address is globally unique, as is an IBAN is suppose.  Except in the case where there's an accompanying tag/memo or some other extra identifier?  I believe the Coinbasepro EOS address is just _coinbase_ or something like that.   

Regarding the general question of backward compatibility.  I've seen projects slow down enormously with an obsession over backward compatibility.  It's a nice thing to have, but in my mind we should be prioritising the future over the past.  

There are good and bad ways to make non-backward compatible changes.  At the most basic level you do have version numbers to indicate breaking changes.  People don't have to upgrade of course, and in extreme circumstances they can manage they're own fork.  But, in reality there are always nice tricks you can employ to make the transition more comfortable.  You can for example start with duplication of data within our structures.  You can deprecate (depending on the language I guess).  And when developers access deprecated stuff you can start logging warnings.  

I think using javascript classes over raw objects would empower us to push breaking changes forward.  I don't have a good grasp on how they cross compile though which is a significant hurdle.  Something like this might help with the current discussion

```
class Transaction {
    /**
     * @deprecated use destination instead
     */
    get address() {
        console.warn(`"address" property will be removed soon, please use "destination.address" instead`);
        return this.destination.address;
    }
   ...
```

I agree there's no reason to rush, this is a minor point.  I was looking at my data and saw some misleading stuff.  One of the many great design decisions in this project was to include the `info` element.  Having the original data is incredibly useful when debugging these issues.  It also allows you to re-parse the data should you disagree with the way it's done in ccxt (which is what I do in a few cases).
