### ISSUE TITLE
What are the conditions for internal reload of load_markets within the library?

### ISSUE THREAD

**Issue by IgorMBorushek** [ccxt/ccxt#5332]
OS: Windows 10
    Programming Language version: Python 3.6.3
    CCXT version: '1.18.458'
    Exchange: bittrex
    Method: all exchange methods that call load_markets internally

While testing performance on various exchange methods, I noticed that some calls are obviously hitting cached markets while some are reloading them. Clearly, load_markets is being reloaded internally within an exchange object but when going through the code, I couldn't figure out the exact conditions for internal reload? Is it set on a timer somewhere or do markets automatically reload when calling certain methods? Thanks in advance,

**Comment by kroitor** [comment]
> While testing performance on various exchange methods, I noticed that some calls are obviously hitting cached markets while some are reloading them.

We do not reload markets in the lib, we only load them once upon your first call to a any method of a unified API.

> Clearly, load_markets is being reloaded internally within an exchange object but when going through the code, I couldn't figure out the exact conditions for internal reload?

We don't do subsequent reloading and there is no logic in the lib nor timers that would control that. Reloading is put on the user (the user should call loadMarkets with a reload flag set to true in order to trigger a reload).

> Is it set on a timer somewhere or do markets automatically reload when calling certain methods? 

We only load them once per exchange instance lifetime. However, if you delete the exchange instance and re-create it somewhere else or later in your program – it will load the markets for each new instance of an exchange. So, if you see some markets being loaded and reloaded in your case – it is the exchange creation/deletion/recreation of the exchange instance that takes place in your code.

Let us know if that doesn't answer the question.

**Comment by kroitor** [comment]
This is how the library decides whether it needs to load and cache the markets or if they were already loaded and cached previously:

https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L692

```JavaScript
    async loadMarkets (reload = false, params = {}) {
        if (!reload && this.markets) {
            if (!this.markets_by_id) {
                return this.setMarkets (this.markets)
            }
            return this.markets
        }
        let currencies = undefined
        if (this.has.fetchCurrencies) {
            currencies = await this.fetchCurrencies ()
        }
        const markets = await this.fetchMarkets (params)
        return this.setMarkets (markets, currencies)
    }
```

If the `reload` flag is true or if `this.markets` have not been loaded and cached yet – then it loads them. So, if you see your application reloading them constantly, that might indicate a bug in class instance management (somewhere upon creating the instances or upon copying them around different parts of the system). However, this is beyond the scope of the lib.

Hope this helps, closing it for now.
