### ISSUE TITLE
KeyError: 'price' when calling calculate_fee with Gemini

### ISSUE THREAD

**Issue by razi-rais** [ccxt/ccxt#5339]
- OS: macOS Mojave (version 10.14.5)
- Programming Language version:  Python 3.7.3
- CCXT version: 1.18.758
- Exchange: Gemini
- Method: calculate_fee

I am trying to use ```calculate_fee```  method but getting ``` KeyError: 'price' ``` error.  When I browse through the section  [Precision and limits](https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits) in the manual it is not clear what I am doing wrong. Also, I can place the order itself on the exchange without any issues (last line that I have commented out). 

````
symbol = 'ETH/USD' 
order_type = 'StopLimit'  
side = 'sell'   
amount = 1.0
price = 500.0 
exchange.load_markets()

# Error -->  KeyError: 'price' 
print(exchange.calculate_fee(symbol, order_type, side, amount, price))  

# Works fine without issues.
#order = exchange.create_order(symbol, order_type, side, amount, price)

````
**Error:**
``` 
File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1566, in calculate_fee
    cost = float(self.cost_to_precision(symbol, amount * price))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1070, in cost_to_precision
    return self.decimal_to_precision(cost, ROUND, self.markets[symbol]['precision']['price'], self.precisionMode)
KeyError: 'price'
```

**Comment by kroitor** [comment]
The problem comes from the fact that Gemini does not serve the info about limits and precision anywhere from there API. The only way to add those limits programmatically – is to scrape them from their docs, here: https://docs.gemini.com/rest-api/#symbols-and-minimums. Or to wait until they add the missing info to their API. The `calculate_fee` relies on limits and precision, therefore it doesn't work with gemini. We hope to add the scraper for limits and precision info shortly.

**Comment by kroitor** [comment]
We have added a web-scraper that gets the limits and precision from Gemini docs, and this is the default now as of version 1.18.791+. So, the methods for calculating fees should work from there.

In order to switch back to the previous behavior:

```Python
gemini = ccxt.gemini({
    'options': {
        'fetchMarketsMethod': 'fetch_markets_from_api', // default is 'fetch_markets_from_web'
    },
})
```

Let us know if you have further difficulties with it.

**Comment by razi-rais** [comment]
After installing the build 1.18.791  getting error -- ```NotSupported: gemini the Gemini API doc HTML markup has changed, breaking the parser of order limits and precision info for Gemini markets```
```
File "/usr/local/lib/python3.7/site-packages/ccxt/gemini.py", line 178, in fetch_markets_from_web
 raise NotSupported(error)
ccxt.base.errors.NotSupported: gemini the Gemini API doc HTML markup has changed, breaking the parser of order limits and precision info for Gemini markets.
```

**Comment by kroitor** [comment]
@razi-rais hold on, will check for that and will get back to you shortly...

**Comment by kroitor** [comment]
Ok, reproduced it, found another bug in the python version, fixed it, and if you can update to version 1.18.794+ (will arrive in 15 minutes), it should work fine. I've tested it on my side and it works for me. We will be happy if you report back whether it work for you or not. Thx!

**Comment by razi-rais** [comment]
Working now. Thanks.

**Comment by kroitor** [comment]
@razi-rais thx for reporting! Appreciate that!
