### ISSUE TITLE
coinbasepro order['fee']['currency'] undefined/None/null

### ISSUE THREAD

**Issue by hroff-1902** [ccxt/ccxt#5343]
- Programming Language version: python
- CCXT version: 1.18.725
- Exchange: coinbasepro
- Method: fetch_order (parse_order)

The fee structure returned by fetch_order() (actually by parse_order()) for coinbasepro contains the 'currency' field equal to None. While the 'cost' field contains actual value for the fee (did not check, I assume this reviewing the codebase). I'm not sure if it shall definitely be quote currency for this exchange (may be the base currency or even a third currency), but at least this should indicate the currency in which the 'cost' is calculated, and not None.

**Comment by kroitor** [comment]
> I'm not sure if it shall definitely be quote currency for this exchange (may be the base currency or even a third currency)

We are not sure either. If it's in quote currency or in base currency – it's easy to fix though. Can you tell looking at your orders, what is it? Always quote? Always base?

> but at least this should indicate the currency in which the 'cost' is calculated, and not None.

In fact, throughout this library, when one field is present and the field next to it is undefined – that is not because we didn't want to define it, that means we could not find a defined value for it. In general, if the API does not return it – we do not invent it out of thin air. In some cases it could be guessed, but for coinbasepro we haven't guessed it yet. Your help investigating it is much appreciated. Check out this: 

- https://github.com/ccxt/ccxt/issues/4506
- https://github.com/ccxt/ccxt/issues/3261#issuecomment-401604350
