### ISSUE TITLE
fetch my open orders

### ISSUE THREAD

**Issue by mmilojevic** [ccxt/ccxt#5349]
Dear, 
This is more a question then issue, but I have read complete documentation and want to know how to retrieve MY open orders, not all but MY? Is it possible? You could set this question in FAQ also....

Because when order is made it cannot be tracked in some new call to API, but I should save the order ID to my DB while order is made (id is returned), is it right?

**Comment by kroitor** [comment]
> This is more a question then issue, but I have read complete documentation and want to know how to retrieve MY open orders, not all but MY? Is it possible? 

Yes, you should use the _private_ part of the unified API instead of the _public_ part. The private methods for fetching **your orders** (not all, but just yours) are:

- `fetchOrder`
- `fetchOrders`
- `fetchOpenOrders`
- `fetchClosedOrders`

More about that part of the API is here:

- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
- https://github.com/ccxt/ccxt/wiki/Manual#order-structure

> Because when order is made it cannot be tracked in some new call to API

Most of exchanges will offer at least one way to retrieve the information about your orders.

> but I should save the order ID to my DB while order is made (id is returned), is it right?

Yes, but in most cases you can retrieve the history of your orders and your current orders from the exchange.

Let us know if that doesn't answer the question )

**Comment by mmilojevic** [comment]
Thank you very much! It was so obvious, I just didn't tried it in practice :)
