### ISSUE TITLE
Format sub-account Binance request

### ISSUE THREAD

**Issue by calbertuk** [ccxt/ccxt#5359]
I'm looking into the Implicit API Methods of the manual but can't figure out how to call those sub-account functions for Binance.

I thought it would be:

`privateGetSubAccountList()
`

But that doesn't work. Tried a few different ones but no luck. Any chance you could steer me in the right direction?

Language: NodeJs
Exchange: Binance

**Comment by frosty00** [comment]
Hi there and thank you for using ccxt.

> I'm looking into the Implicit API Methods of the manual but can't figure out how to call those sub-account functions for Binance.

Implicit API methods are generated from the `exchange.api` property of the an exchange instance. 

Looking at the `.api` of a binance object this is what I see:

```
  wapi:
   { post: [ 'withdraw', 'sub-account/transfer' ],
     get:
      [ 'depositHistory',
        'withdrawHistory',
        'depositAddress',
        'accountStatus',
        'systemStatus',
        'apiTradingStatus',
        'userAssetDribbletLog',
        'tradeFee',
        'assetDetail',
        'sub-account/list',
        'sub-account/transfer/history',
        'sub-account/assets' ] },
```

Hence to generate the method that you want you need to join the parts of the endpoint you want. In this case I believe you are looking for `wapiGetSubAccountList`.

Note that here the `-` is removed since it would be an invalid method in javascript otherwise. Let me know if you have any more questions : )

**Comment by calbertuk** [comment]
That's all, thanks.
