### ISSUE TITLE
Add Beaxy Exchange 

### ISSUE THREAD

**Issue by evansmith-beaxy** [ccxt/ccxt#5378]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
Hi! We have an open post for Beaxy here: https://github.com/ccxt/ccxt/issues/5264. It's in progress. I'd close this as a duplicate for now.

**Comment by evansmith-beaxy** [comment]
Any ETA?
Thanks for getting back to me, really want to implement the Alpha price bot for $BXY in our community Discord server.

________________________________

**Comment by kroitor** [comment]
@evansmith-beaxy unfortunately, we can't give an estimate on when it will be done, we can't promise on the free work, due to reason explained in our FAQ: https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-thisa. Will keep you updated in #5264. Hope for your understanding.
