### ISSUE TITLE
[Bitmex] No method Error. I can't Fetch my current position.

### ISSUE THREAD

**Issue by DongwonTTuna** [ccxt/ccxt#5391]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows 10 pro
- Programming Language version: python 3.7
- CCXT version: 1.18.841
- Exchange: bitmex
- Method: can't use private_get_position()

![image](https://user-images.githubusercontent.com/38794795/60343519-20eac100-99ef-11e9-963d-890c31fcafa8.png)

**Comment by frosty00** [comment]
If you finish typing `bitmex.private_get_position` you will find that the method does indeed exist, it is only the intellij suggestions that are failing because the method is not defined anywhere in the code. We will have to do more research on how to get these to work.

https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by DongwonTTuna** [comment]
holy moly! It was problem of intellij...! Thank you.

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/5390
- https://github.com/ccxt/ccxt/issues/5352
