### ISSUE TITLE
Use ANTLR instead of own transpiling

### ISSUE THREAD

**Issue by gontadu** [ccxt/ccxt#5416]
Hi,

I am fairly new but after searching I'm unable to see why. Is it possible to apply ANTLR to the code transpiling area in CCXT i.e. JavaScript to Python/etc.? Maybe then we can leverage off those efforts?

**Comment by kroitor** [comment]
Hi!

The existing transpiler is regex-based, so, if we wanted to transpile a new JS clause to Python or PHP we would add a new regex and would then rebuild it within a few seconds. And it generates code which is very close to native Python/PHP code, so any person who wants to start learning CCXT from code –will be able to read it easily. The existing transpiler does it in a non-intrusive way – ideally you don't have to write new rules to be able to transpile the existing JavaScript code to Python or PHP.

With a generic external transpiler things become overcomplicated and adding a ton of new rules just to transpile the code and to get the same result – isn't something that we would need immediately. In other words, we would not use ANTLR just because it exists. There is another suggestion of an alternative tool for transpilation, called HAXE. However, we don't integrate with a package just because it exists and does something similar to what we do. An external generic transpiler would be an overkill for this project and introducing it implies too much overhead.

We only need to integrate new code only if:

- if it saves us a lot of time (which is not the case with an external transpiler – it would eat quite a lot of time to even get it configured properly)
- if it means progress for the project, in other words substituting one working tool for another working tool that produces the same result does not necessarily mean progress
- if it leads to less work in the future, not to more work in the future (for the devs and for the users)

Let us know if that does not answer your question. Thank you for your involvement!

**Comment by gontadu** [comment]
@kroitor I believe it does, and in my view a sensible practical reasoning. Thanks for taking the time out to answer :)
