### ISSUE TITLE
Kucoin trades and closed-orders are limited until 7 days after the "since"

### ISSUE THREAD

**Issue by AregShahbazian** [ccxt/ccxt#5443]
- OS: Ubuntu 18.04
- Programming Language version: JavaScript
- CCXT version: 1.18.880
- Exchange: Kucoin
- Method: `fetchMyTrades`, `fetchClosedOrders`

When the `since` parameter is given to the `fetchMyTrades` or `fetchClosedOrders` methods, an URL parameter called `startAt` is used to get data from the Kucoin API. I noticed from the returned objects that the data is limited until 7 days after the `startAt`. 

**To reproduce:**

- have a trade on any Kucoin market.
- call `fetchMyTrades` on that market, with `since=[trade.createdAt - (7 * 24 * 60 * 60 * 1000)]` (7 days before that trade). The trade will be in the response.
- call `fetchMyTrades` again, with `since=[trade.createdAt - (7 * 24 * 60 * 60 * 1000) - 1000]` (7 days plus 1 second before that trade). The trade is now missing.

**Suggestion for solution:** 

Maybe the easiest solution is to always send the [`endAt`](https://docs.kucoin.com/#list-orders) parameter with the current datetime, whenever the `startAt` is used.

**Comment by frosty00** [comment]
unfortunately the solution you suggested doesn't work.

```
 {"code":"400100","msg":"The duration between the start time and the end time should not exceed 7 days."} 
```

and for fetchMyTrades if the time difference is longer than a week you get

```
 {"code":"400100","msg":"validation.queryOrder.timeRangeInvalid"} 
```

so i'm not sure how to solve this. Any help would be appreciated.

**Comment by frosty00** [comment]
actually nvm i found a solution for the trades, using `/api/v1/limit/fills` not sure about the orders however.

**Comment by kroitor** [comment]
@AregShahbazian 

> I noticed from the returned objects that the data is limited until 7 days after the startAt.

It is documented in the Manual, that exchanges will never return all data from the chosen starting point up to the current date – there will always be a limit of trades or a limit on a timerange that you can query. So, we always query a range of `since + 7 days from since`. Switching to always query `now - 7 days before now` is incorrect, because that would break the logic of date-time pagination. 

I would suggest to close this at this point, unless @frosty00 has a solution. `GET /api/v1/limit/fills` is a no-go, because it is limited to 1000 most recent trades, can't specify `since` with it.

I'd suggest this pseudocode solution in userland:

```
t = one year ago
while (t < now) {
    timestamp = t;
    trades = fetch_trades (timestamp)
    if (trades) {
        timestamp = trades[-1]['timestamp']
    } else {
        t += one week
    }
}
```

Let us know if that helps.

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/4949

**Comment by kroitor** [comment]
We are going to add a new option that changes this behavior: https://github.com/ccxt/ccxt/pull/5448

```Python
import ccxt
exchange = ccxt.kucoin({
    'options': {
        // ← default, also: 
        'fetchMyTradesMethod': 'private_get_fills', // 'private_get_limit_fills', 'private_get_hist_orders'
    }
})
```
