### ISSUE TITLE
How to trade with all available balance ?

### ISSUE THREAD

**Issue by frodoe7** [ccxt/ccxt#5464]
This is more a question than issue

I manually fetch the user available balance then make some complicated calculations to calculate the amount to buy or sell

these calculations include fetching all available balance , converting to another coin , calculating the fees ratio , deducting from the amount to buy or sell and so on ..

however my calculations is not very accurate , 
the final amount result is above or less than the expected by very small amount

for example , I have .004 BTC and would like to buy ETH
now I need to calculate the .004 BTC in ETH and also remove the fees , which sometimes (.2%) , let's assume the amount should be 0.15 ETH

sometimes my result is .151 > then it fires error : insufficient balance
sometimes my result is .149 > then it goes well but it keeps a tiny amount in my BTC balance , and I don't need this behavior

my issue with this last parameter (amount)

`exchange.createOrder(market , 'market' , side , amount)`

any way to tell the exchange , that I'd like to trade with all my available balance ?

**Comment by frosty00** [comment]
Hi @frodoe7,

I do not think you need to take the fees into consideration, as the exchange will do that for you and give you an amount after taking fees. So here you want to buy 0.15 ETH.

`exchange.create_order ('ETH/BTC', 'limit', 'buy', 0.15, 0.0267)`

where 0.004 / 0.0267 = 0.15

ETHamount / ETHBTCprice = BTCamount

a cool way to think about markets is as a fraction. so ETH/BTC is literally ETH over BTC (or ETH per BTC).

If you do these calculations you should be able to sell most of your crypto. These is no flag for most exchanges "sell everything", however I agree it would be nice. And if an exchange supports such an option you would be able to do it using https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by kroitor** [comment]
> And if an exchange supports such an option you would be able to do it using https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Or, alternatively, https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

@frodoe7 

> however my calculations is not very accurate ,
> the final amount result is above or less than the expected by very small amount

In general, because of [limits and precision](https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits), you won't be able to spend everything to a cent, some dust will always remain there, unless you're lucky enough to have amounts large enough to avoid the rounding entirely. 
Let us know if that does not answer the question.

**Comment by mr-asad92** [comment]
> 
> 
> Hi @frodoe7,
> 
> I do not think you need to take the fees into consideration, as the exchange will do that for you and give you an amount after taking fees. So here you want to buy 0.15 ETH.
> 
> `exchange.create_order ('ETH/BTC', 'limit', 'buy', 0.15, 0.0267)`
> 
> where 0.004 / 0.0267 = 0.15
> 
> ETHamount / ETHBTCprice = BTCamount
> 
> a cool way to think about markets is as a fraction. so ETH/BTC is literally ETH over BTC (or ETH per BTC).
> 
> If you do these calculations you should be able to sell most of your crypto. These is no flag for most exchanges "sell everything", however I agree it would be nice. And if an exchange supports such an option you would be able to do it using https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Hi, I'm having the exact same issue. Whenever i calculate some amount to buy, it sometimes gives me error that i dont have enough balance for requested operation. I think this is because I calculated the amount on a price which was increased at the time of order execution. I'm executing market orders and i cant use limit orders because I need it to be closed immediately. Any suggestions how I can handle this?

Thanks.

**Comment by kroitor** [comment]
Hi @mr-asad92 

> I'm executing market orders and i cant use limit orders because I need it to be closed immediately. Any suggestions how I can handle this?

Do you take the fees and the fee side (base/quote) into account when you calculate the values for your market orders? In any case, there may be price slippage, since orders are not processed immediately. Even if you calculate everything right, you might still hit a limit.

Some exchanges, however, support the _"timeInForce"_ option which basically allows you to control the lifetime of your **limit** orders. The most common values for `timeInForce` are:

- `GTC` = good till canceled (this is the default in many cases)
- `IOC` = immediate or cancel (you might want to look into this one)
- `FOK` = fill or kill...

So, I'd suggest to look into those options, depending on the exchange in question. 

Another way to approach this is to introduce a "buffer" into your strategy, so that you trade 90%, 99%, 99.9999%  (whatever works for you), not 100%...

**Comment by kroitor** [comment]
Just a quick update: we have added the support for total cost for market orders with Binance here: https://github.com/ccxt/ccxt/issues/6391#issuecomment-576247330

**Comment by Hovooo** [comment]
> > Hi @frodoe7,
> > I do not think you need to take the fees into consideration, as the exchange will do that for you and give you an amount after taking fees. So here you want to buy 0.15 ETH.
> > `exchange.create_order ('ETH/BTC', 'limit', 'buy', 0.15, 0.0267)`
> > where 0.004 / 0.0267 = 0.15
> > ETHamount / ETHBTCprice = BTCamount
> > a cool way to think about markets is as a fraction. so ETH/BTC is literally ETH over BTC (or ETH per BTC).
> > If you do these calculations you should be able to sell most of your crypto. These is no flag for most exchanges "sell everything", however I agree it would be nice. And if an exchange supports such an option you would be able to do it using https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
> 
> Hi, I'm having the exact same issue. Whenever i calculate some amount to buy, it sometimes gives me error that i dont have enough balance for requested operation. I think this is because I calculated the amount on a price which was increased at the time of order execution. I'm executing market orders and i cant use limit orders because I need it to be closed immediately. Any suggestions how I can handle this?
> 
> Thanks.

Hey! 
I've done it the way you suggested and there is a very unexpected behaviour.
In case of making market order for MATIC/USDT it works absolutely fine. I give the amount of 1 usdt and get corresponding amount of MATIC on the other end. 
But in case of doing absolutely the same with AVAX/USDT almost all my balance is being used to buy AVAX, nevertheless I specify amount equal to 1 USDT. 
Any ideas why is I happening and how can I fix it?
