### ISSUE TITLE
Request timeout for fetchbalance

### ISSUE THREAD

**Issue by KhalilMohammad** [ccxt/ccxt#5486]
- OS: Windows 10
- Programming Language version: NodeJs
- CCXT version: 1.18.916
- Exchange: okex3
- Method: fetchBalance

Most other methods are working.
I tried Proxy VPN but it is not working. #5279

**Comment by kroitor** [comment]
@KhalilMohammad what's your version of Node? Can you paste a minimal snippet of code to reproduce it?

**Comment by KhalilMohammad** [comment]
NodeJs Version: v11.9.0

I just tried again, same code it is now working.



```Javascript

  const ccxt = require("ccxt");
  const log = require("ololog").configure({ locate: false });

  require("ansicolor").nice;
  try {
    const exchange = new ccxt.okex3({
      apiKey: apiKey, // standard
      secret: secret,
      password: password // Set password if api requires
    });
    const balance = await exchange.fetchBalance();
    //callback(null, balance);
  } catch (e) {
    if (e instanceof ccxt.DDoSProtection || e.message.includes("ECONNRESET")) {
      log.bright.yellow("[DDoS Protection] " + e.message);
    } else if (e instanceof ccxt.RequestTimeout) {
		// Previously each time request was coming here
      log.bright.yellow("[Request Timeout] " + e.message);
    } else if (e instanceof ccxt.AuthenticationError) {
      log.bright.yellow("[Authentication Error] " + e.message);
    } else if (e instanceof ccxt.ExchangeNotAvailable) {
      log.bright.yellow("[Exchange Not Available Error] " + e.message);
    } else if (e instanceof ccxt.ExchangeError) {
      log.bright.yellow("[Exchange Error] " + e.message);
    } else if (e instanceof ccxt.NetworkError) {
      log.bright.yellow("[Network Error] " + e.message);
    }
    //callback(e);
  }

**Comment by kroitor** [comment]
> I just tried again, same code it is now working.

It was a temporary RequestTimeout then. In general, you should expect connectivity errors and `ExchangeNotAvailable`, `RequestTimeout`, `NetworkError` and other exceptions occasionally. Unfortunately, the connectivity is not globally-ideal all the time. So, catching a NetworkError or a RequestTimeout occasionally due to network congestion or due to any other net errors is pretty much normal. 

More about errors and their meaning here: 

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Let us know if that doesn't answer the question.

**Comment by KhalilMohammad** [comment]
Thank you for your quick response.
