### ISSUE TITLE
How to get all Price Tickers for all Exchanges

### ISSUE THREAD

**Issue by Modrx** [ccxt/ccxt#5490]
Hi,

I would like to get the Price Tickers for all exchanges using PHP, how can I do that?

Yobit, CoinMarketCap, and other exchanges are not providing all the Price Tickers, some are limited to 100.

What's the best way to get all the Price Tickers without checking each and every exchange if it's providing all the Price Tickers or not.

I can get the exchange list and process all exchanges no problem but I am getting errors similar to the following, while some exchanges are simply providing 100 items without any errors (ex: CoinMarketCap):

yobit has 8264 markets exceeding max URL length for this endpoint (512 characters), please, specify a list of $symbols of interest in the first argument to fetch

Thank you!

**Comment by kroitor** [comment]
Hi!

> I would like to get the Price Tickers for all exchanges using PHP, how can I do that?

Which particular price tickers for all exchanges do you want? Because a price ticker is tied to a market symbol, some exchanges may have a completely different set of tickers and symbols than other exchanges. Also, the exchanges will not allow you to fetch all data in one call – you gotta be ready to traverse it, depending on your needs. This is the limitation on the exchanges' side, as explained in the Manual here: 

- https://github.com/ccxt/ccxt/wiki/Manual#pagination

The workaround may depend on the specifics of an underlying exchange.

In general to fetch all tickers, you would call [`fetchTickers`](https://github.com/ccxt/ccxt/wiki/Manual#all-at-once) on the exchange instance, if the exchanges in question has that in the [exchange metadata](https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata).

You might have to override some params for `fetchTickers` as described here:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

> yobit has 8264 markets exceeding max URL length for this endpoint (512 characters), please, specify a list of $symbols of interest in the first argument to fetch

That error says that you should specify a list of symbols to yobit `fetchTickers`, and it will try to load all 8264 tickers by default, which is way more than the max URL length, so you need to limit the tickers you fetch by specifying a lower number of symbols (instead of the default "all symbols").

See [`cli.php`](https://github.com/ccxt/ccxt/blob/master/examples/php/cli.php) for example:

```
mbp:ccxt igorkroitor$ php -f examples/php/cli.php yobit fetch_tickers '["ETH/BTC","BTC/USD"]'
Array
(
    [ETH/BTC] => Array
        (
            [symbol] => ETH/BTC
            [timestamp] => 1562727339000
            [datetime] => 2019-07-10T02:55:39.000Z
            [high] => 0.02552146
            [low] => 0.02386818
            [bid] => 0.02404446
            [bidVolume] =>
            [ask] => 0.02409635
            [askVolume] =>
            [vwap] =>
            [open] =>
            [close] => 0.02404446
            [last] => 0.02404446
            [previousClose] =>
            [change] =>
            [percentage] =>
            [average] => 0.02469482
            [baseVolume] => 38022.36254164
            [quoteVolume] => 947.91717815
            [info] => Array
                (
                    [high] => 0.02552146
                    [low] => 0.02386818
                    [avg] => 0.02469482
                    [vol] => 947.91717815
                    [vol_cur] => 38022.36254164
                    [last] => 0.02404446
                    [buy] => 0.02404446
                    [sell] => 0.02409635
                    [updated] => 1562727339
                )

        )

    [BTC/USD] => Array
        (
            [symbol] => BTC/USD
            [timestamp] => 1562727329000
            [datetime] => 2019-07-10T02:55:29.000Z
            [high] => 13200.00000003
            [low] => 12206.0005
            [bid] => 13052.35669077
            [bidVolume] =>
            [ask] => 13150
            [askVolume] =>
            [vwap] =>
            [open] =>
            [close] => 13052.35669034
            [last] => 13052.35669034
            [previousClose] =>
            [change] =>
            [percentage] =>
            [average] => 12703.00025001
            [baseVolume] => 47.16509871
            [quoteVolume] => 597158.5063962
            [info] => Array
                (
                    [high] => 13200.00000003
                    [low] => 12206.0005
                    [avg] => 12703.00025001
                    [vol] => 597158.5063962
                    [vol_cur] => 47.16509871
                    [last] => 13052.35669034
                    [buy] => 13052.35669077
                    [sell] => 13150
                    [updated] => 1562727329
                )

        )

)
```

Let us know if the above does not answer the question.

Dupe: https://github.com/ccxt/ccxt/issues/5441

**Comment by Modrx** [comment]
Can you please provide me the PHP code to get all (2264) CoinMarketCap Price Tickers when using the following code, instead of 100:

$exchange = new \ccxt\coinmarketcap (array (
    'apiKey' => 'YOUR_API_KEY', // ?------------ replace with your keys
    'secret' => 'YOUR_SECRET',
//    'verbose' => true,
));

if ($exchange->has['fetchTickers']) {
//var_dump ($exchange->fetch_tickers ()); // all tickers indexed by their symbols
}

Thank you!

**Comment by kroitor** [comment]
> Can you please provide me the PHP code to get all (2264) CoinMarketCap Price Tickers when using the following code, instead of 100:

It is not possible with the free CoinMarketCap v1 API that is integrated in CCXT, unfortunately, CMC will limit the results at 100 tickers. However, we are going to add suport for their new paid API which does allow to fetch all tickers at once, and as soon as we have it integrated – we will post the example here. Pardon for the inconvenience, but this is really against the will of the exchanges – they will very rarely tolerate fetching too many data too often and will try to limit the output at all costs.

Will do our best to provide asap a solution for using CMC with CCXT specifically. Feel free to ask if you have further questions.

**Comment by Modrx** [comment]
Hi,

Can you please provide me the PHP code to get all Price Tickers for the exchanges that do offer all tickers.

I am getting the following error:

_1btcxe API does not allow to fetch all tickers at once with a single call to fetch_tickers

Code:
$exchange = new \ccxt\coinmarketcap (array (
'apiKey' => 'YOUR_API_KEY',
'secret' => 'YOUR_SECRET',
'verbose' => true,
));

if ($exchange->has['fetchTickers']) {
var_dump ($exchange->fetch_tickers ()); // all tickers indexed by their symbols
}

Thank you!
