### ISSUE TITLE
Bitfinex order history limit

### ISSUE THREAD

**Issue by FlickerBean** [ccxt/ccxt#5500]
- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.18.923
- Exchange: Bitfinex and Bitfinex2
- Method: fetchClosedOrders

Bitfinex has a parameter 'limit' (https://docs.bitfinex.com/reference#rest-auth-orders-history) which doesn't work when passing under params. This code only returns 93 orders... (there are def more than 93 orders on the exchange).

```
            $closedOrders = $exchange->fetchClosedOrders($market, null, 500, ['limit' => 500]);
```

Bitfinex2 crashes out with:

```
privatePostOrdersHist method not found, try underscore_notation instead of camelCase for the method being called.
```

**Comment by kroitor** [comment]
@FlickerBean can you please post your verbose request/response for the v1 call?

```PHP
$exchange->load_markets();
$exchange->verbose = true;
$closedOrders = $exchange->fetchClosedOrders($market, null, 500, ['limit' => 500]);
```

?

**Comment by FlickerBean** [comment]
Bitfinex2 not supporting fetchClosedOrders yet is fair enough. Do you think overriding its parent classes method to make this more apparent, may be a good idea?

Apologies for not posting the output I should know better by now :blush:

https://pastebin.com/dQ8pC5WS

**Comment by kroitor** [comment]
> Bitfinex2 not supporting fetchClosedOrders yet is fair enough. Do you think overriding its parent classes method to make this more apparent, may be a good idea?

Yes, of course! Thanks for that! We will add an override that will throw a `NotSupported` exception with a meaningful description asap.

> Apologies for not posting the output I should know better by now 😊
> https://pastebin.com/dQ8pC5WS

Ok, now, in the output, we immediately see that `limit` is 

```
    [3] => {"nonce":"xxxxxxxxxxxxx","request":"\/v1\/orders\/hist?limit=500","limit":500}
)

Response:
Array
(
    [0] => POST
    [1] => https://api.bitfinex.com/v1/orders/hist?limit=500
```

So, the exchange has received the `limit=500` request from you, and it replied with 100 orders exactly.
The exchange replied with just 100 orders because they have a max limit on the exchange which we cannot workaround on our side for obvious reasons. Their limits are documented in their docs: https://docs.bitfinex.com/reference#rest-auth-active-orders

![Screen-Shot-2019-07-12-at-11 03 17](https://user-images.githubusercontent.com/1294454/61112594-dd835e80-a494-11e9-8bb2-d84732e05509.jpg)

Note that the history is limited in time and I suspect that 100 is the max number of elements you can get in one request. You can test that by requesting 99 and 101 orders. 

That limitation is documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#pagination

However, you've also applied filtering by symbol by specifying the `$market` along with the limit, so, in this specific case, I'm guessing, you're filtering IOTA orders, and therefore `fetchClosedOrders` returns 93 of IOTA orders and filters out the other 5 XRP orders and 2 LTC orders which are not IOTA. That's a behavior documented in the Manual, the way it's supposed to behave based on your arguments.

Case solved? )

**Comment by FlickerBean** [comment]
Ahhh... that all makes sense... I thought 100 was the default due to their v2 documentation using the simiular UI but in v2 they put the default not the max there. See here: https://docs.bitfinex.com/v2/reference#orders-history

If I could contribute via php i'd be happy to implement `Bitfinex2::fetchClosedOrders` which supports up to 500.
Where can I get more information on how to contribute via php, is this possible or are contributions to exchanges only allowed via Javascript due to the transpiling?

I have read https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md before. But it doesn't make everything 100% clear.

**Comment by kroitor** [comment]
@FlickerBean thx! We appreciate all PRs and contributions!

> Where can I get more information on how to contribute via php

Here: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

> is this possible or are contributions to exchanges only allowed via Javascript due to the transpiling?

Well, technically, we accept JavaScript only, however, if you open the JavaScript fetchClosedOrders and the PHP fetchClosedOrders and compare them, you will immediate notice 0 differences:

<img width="1136" alt="Screen Shot 2019-07-12 at 11 38 57" src="https://user-images.githubusercontent.com/1294454/61114742-a9f70300-a499-11e9-996f-5307574f7922.png">

↑ That code is literally the same line-to-line. That is because the code is designed to be portable. So, if you don't feel confident with JavaScript, but you can code in PHP – you could still implement the proper method in JS just by copy-pasting the existing code.

When writing the new code we stick to these rules:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

> I have read https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md before. But it doesn't make everything 100% clear.

Let us know if you have specific questions, will be happy to answer )

**Comment by FlickerBean** [comment]
> Well, technically, we accept JavaScript only, however, if you open the JavaScript fetchClosedOrders and the PHP fetchClosedOrders and compare them, you will immediately notice 0 differences

This is exactly what I was looking for.

I'm comfortable enough with Javascript. If I get a spare few hours i'll look deeper into it all :)

Thanks for all your help.
