### ISSUE TITLE
HitBTC createOrder amountToPrecision

### ISSUE THREAD

**Issue by romanbolshakov** [ccxt/ccxt#5574]
- OS: ubuntu 
- Programming Language version: node.js 9.8
- CCXT version: 1.18.965
- Exchange: HitBTC
- Method: createOrder

Hi. For market HitBTC: BAT\BTC I want to BUY some amount of BAT for 0.00001 BTC. Try to place following order:

exchange=HitBTC
symbol=BAT/BTC
type=market
side=buy
amount=0.00001

Error: ```Quantity not a valid number```

Can I place BUY order with amount in quote currency?

**Comment by frosty00** [comment]
Hi @romanbolshakov,

Typically when you use create order the `amount` param is in the `base` currency. You can roughly calculate how much `quote` currency that would be equivalent to by using the formula `quote = base * price`. Will add some edits to the manual.

**Comment by romanbolshakov** [comment]
Hi @frosty00. Thank you for fast reply )... Is it rule or recomendation (for base and quote amount while create the oreder). In some cases it is not easy to calculate the amount in ```base``` currency via ```quote``` currency (need to know orderbook stack with available amounts and it can change very quickly).

**Comment by frosty00** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

Well I thought it would be a rule to always use the base order, but it seems that ccxt is not even unified in that regard yet. It seems to vary from exchange to exchange, and we cannot easily convert without losing precision due to floating point loss of precision. I think hitbtc and around 90% and most of the good exchanges use the base currency.

**Comment by romanbolshakov** [comment]
Ok, clear. Thank you.
