### ISSUE TITLE
question: how to get balance from HitBTC

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5596]
HitBTC has the concept of a 'Main Account' per currency, and a 'Trading account' per currency. The current call to `fetchBalance` only looks at your 'trading' account balance, and so it doesn't return the full picture.  

Is this intentional?  What's the technique for getting the balance of the 'Main Account'?

**Comment by npomfret** [comment]
Ok, answer is to passing in a paramter: `{type: 'trading'}`, or `{type: 'account'}`. Perhaps we could consider if making 2 api calls within the hitbtc2 implementation and adding the result together might be a better approach?

**Comment by kroitor** [comment]
Hey @npomfret ! Sorry for the delays with the answer. Looks like you've figured it out...

> Perhaps we could consider if making 2 api calls within the hitbtc2 implementation and adding the result together might be a better approach?

To be honest, I don't think that sending two requests is a good solution, because the number and the nature of the requests is app-specific, in some cases we want to get the trading balance only, in other cases we want the account balance only, in other cases we want both. Changing this functionality and the corresponding formats in a backward-compatible way would be very hard. By default CCXT will show the trading account, that is, the account used for spot trades. Let me know if that does not answer it.

**Comment by npomfret** [comment]
Perhaps just a comment in the code is in order?  The only way to know at the moment is reading the code.

**Comment by kroitor** [comment]
@npomfret sure, will add more clarifications to it shortly!

**Comment by tredondo** [comment]
@kroitor where can we find the clarifications?

https://github.com/ccxt/ccxt/wiki/Manual#account-balance doesn't say anything special about HitBTC.

https://github.com/ccxt/ccxt/wiki/Exchange-Markets doesn't link to any exchange-specific CCXT information, or must the user look at the API documentation provided by the exchange?

**Comment by kroitor** [comment]
@tredondo that param is not documented in CCXT yet, but we give links to the exchanges' API docs for the exchange-specifics. Those are generalized here (we just don't list out every single param for each exchange):

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

Yes, we know that not everything is unified yet, but we are working on this aspect as well, hope to make it better soon!
Thx for your feedback, we really appreciate it!
