### ISSUE TITLE
Dont duplicate python async exchanges

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#5629]
I think it is possible to not duplicate the async exchanges in python, something like this (pseudo code):
```
import not_async_binance
import AsyncBaseExchange

class Binance(AsyncBaseExchange, not_async_binance):
    pass
```
The AsyncBaseExchange should provide definitions for every entry point with async and it can call with super the not_async_binance methods.
This would result in less code, smaller commits. See #5442 
I just want to discuss this and would implement it later if it would get merged.

**Comment by brandsimon** [comment]
We could also remove comments in php/python builds. If someone wants to change code, he would do this in JS anyway. Any thoughts on this?

**Comment by kroitor** [comment]
> and it can call with super the not_async_binance methods.

I don't think you can substitute the logic that is happening behind

```Python
result = await this.somethingAsync()  # respects async
```

↑ not equal to ↓

```Python
result = this.somethingNotAsync ()  # breaks async
```

Because of the above we can't really avoid a conflict of async vs non-async syntax. If it was that easy, there would be no difference between Python 2.7 and Python 3.7 in that regard, yet the two Pythons are incompatible )

> We could also remove comments in php/python builds.

Yep, we could. However, we would lose readability == would make it harder for people to get on board (most devs would want to read the underlying code at some point).

**Comment by brandsimon** [comment]
@kroitor 
I think those are equal in python3. If not, please elaborate, I havnt done much work with it.
```
import asyncio
import time


async def func(x):
    print("func: going to sleep")
    time.sleep(3)
    print("func: return result")
    return x * 2


async def print_result(coroutine):
    print("func: print_result started")
    print(await coroutine)
    print("func: print_result ended")


async def main():
    result = func(4)
    await print_result(result)


asyncio.run(main())
```
results to:
```
func: print_result started
func: going to sleep
func: return result
8
func: print_result ended
```

**Comment by kroitor** [comment]
@brandsimon see the difference between `asyncio.sleep()` and `time.sleep()`. Try thinking this way: why would there be an async version of sleep, when there's a sync version of sleep is available. That is because a blocking call will block all other asynchronous jobs. You can see that id you launch two async routines simultanously, and make one call `time.sleep` while another is doing a call to `requests` – they won't run in parallel and will block each other (if you sleep long enough). Then switch to `async.sleep` + `aiohttp` and you will see that they don't block each other. In other words, a blocking call will always block the execution of asynchronous calls.

More about it here: 

- https://stackoverflow.com/questions/2625493/asynchronous-vs-non-blocking

Let me know if that does not answer the question.

**Comment by kroitor** [comment]
@brandsimon a more direct explanation:

```Python
# -*- coding: utf-8 -*-

import asyncio
import time


async def work_sync(i):

    print(i, 'started')
    time.sleep(5)
    print(i, 'done')

async def work_async(i):

    print(i, 'started')
    await asyncio.sleep(5)
    print(i, 'done')

async def main_sync(loop):
    print('running sync test')
    tasks = set()
    for i in range(0,3):
        tasks.add(loop.create_task(work_sync(i)))
    await asyncio.wait(tasks)

async def main_async(loop):
    print('running async test')
    tasks = set()
    for i in range(0,3):
        tasks.add(loop.create_task(work_async(i)))
    await asyncio.wait(tasks)


loop = asyncio.get_event_loop()
loop.run_until_complete(main_sync(loop))
loop.run_until_complete(main_async(loop))
```

```
mbp:ccxt igorkroitor$ python3 examples/py/concurrency.py
running sync test
0 started
0 done
1 started
1 done
2 started
2 done
running async test
0 started
1 started
2 started
0 done
1 done
2 done
mbp:ccxt igorkroitor$
```

**Comment by brandsimon** [comment]
@kroitor 
Thank you for the explanation, now I understand what you mean. The problem is not the main entry point, but the call to the exchange. Got it, thank you!

**Comment by kroitor** [comment]
> The problem is not the main entry point, but the call to the exchange.

Yep, exactly, it's because of those bottom-layer calls which require everything to the top to be `async` as well. I could not find good words to say it as short as you did )
