### ISSUE TITLE
why does hitbtc use the clientOrderId field instead of the id field for orders?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5674]
Both parseTrade and parseOrder implementations in Hitbtc use the `clientOrderId` as the order id field.  This seems inconsistent with the other implementations which I think all use the exchange provided id.  The client supplied id is important, and could be represented on its own, but it feels wrong to use it in place of the id field.  

I think the rest api uses the client order id in cancelOrder calls, perhaps this is why?

**Comment by kroitor** [comment]
> I think the rest api uses the client order id in cancelOrder calls, perhaps this is why?

Exactly. The reason is that HitBTC accepts clientOrderId for practically all endpoints, but not the original exchange id.

- https://api.hitbtc.com/#orders-history
- https://api.hitbtc.com/#get-active-order-by-clientorderid
- https://api.hitbtc.com/#cancel-order-by-clientorderid

vs

- https://api.hitbtc.com/#trades-by-order

We could make that fieldname overrideable with options, if you think it's worth it.

**Comment by npomfret** [comment]
I think some comments directly in the code would be helpful (on the surface it does look like a mistake).

In this case though I think the decision is probably the right one, although not what I would have done if implementing from scratch I guess.  As the exchange provides a clientOrderId (if you do not supply one) it can be relied on. 

The `trades-by-order` does complicate things.  I would have added a clientOrderId to the ccxt order model.  I imagine other exchanges support this as it's a very useful feature...  And added a base method `cancelOrderByClientOrderId` perhaps.
