### ISSUE TITLE
Add an OHLCV base method for getting next/previous timeframe date

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#5683]
## Proposal
Since exchange has multiple static helper methods, like `Exchange.parse_timeframe()`, would you see it usefull to have a similar method which returns the date of the previous / next candle?

Basically passing in timeframe and date (defaults to utcnow()?) - which then returns the date of the next candle.

### Purpose

I think this can be usefull in "fetch_ohlcv()" loops, where you can wait for the next candle (it does not make sense to run this every few seconds if the next candle only comes in 20 minutes).

### Interface Example

``` python
# probably replace datestring with epoch in ms to be aligned with all other methods - but that's very odd-looking for demonstration purposes
assert Exchange.timeframe_to_prev_date('10m', '2019-08-12 13:22:08') == '2019-08-12 13:20:00'
assert Exchange.timeframe_to_prev_date('30m', '2019-08-12 13:22:08') == '2019-08-12 13:00:00'

assert Exchange.timeframe_to_next_date('5m', '2019-08-12 13:22:08') == '2019-08-12 13:25:00'
assert Exchange.timeframe_to_next_date('30m', '2019-08-12 13:22:08') == '2019-08-12 13:30:00'

```

I'm willing to work on adding this if there is interrest in adding this - but i'll probably need some help / guidance if this will be transpiled from js or not (since it's in the base class, i assume it's not?).

Feel free to close this if you think this should be done on the client side, and not be part of ccxt.

**Comment by kroitor** [comment]
Hi @xmatthias !

Thx for the proposal!

> Since exchange has multiple static helper methods, like Exchange.parse_timeframe(), would you see it usefull to have a similar method which returns the date of the previous / next candle?

It may be useful, however, we need to do it in agreement with the rest of the interface of the lib, which operates and expects integer timestamps in milliseconds. CCXT already does offer methods for converting from/to iso8601 datestrings: https://github.com/ccxt/ccxt/wiki/Manual#working-with-datetimes-and-timestamps

So, the code snippet you posted above would rather look like:

```Python
assert Exchange.timeframe_to_prev_date('10m', Exchange.parse8601('2019-08-12 13:22:08')) == Exchange.parse8601 ('2019-08-12 13:20:00')
```

Also, it may be easier to vary the argument values than function names across all languages, so we could also do it like so:

```Python
assert Exchange.round_timeframe('10m', ROUND_DOWN, Exchange.parse8601('2019-08-12 13:22:08')) == Exchange.parse8601 ('2019-08-12 13:20:00')
assert Exchange.round_timeframe('10m', ROUND_UP, Exchange.parse8601('2019-08-12 13:22:08')) == Exchange.parse8601 ('2019-08-12 13:30:00')
```

> I'm willing to work on adding this if there is interrest in adding this - but i'll probably need some help / guidance if this will be transpiled from js or not (since it's in the base class, i assume it's not?).

That is correct, because basecode is language-specific and is not transpiled, we have to implement it in all three languages.

> I think this can be usefull in "fetch_ohlcv()" loops, where you can wait for the next candle (it does not make sense to run this every few seconds if the next candle only comes in 20 minutes).

Can you post an example of such a loop? )

**Comment by xmatthias** [comment]
As mentioned in the code comment, i'm aware that it should be timestamps in ms :+1: 

> probably replace datestring with epoch in ms to be aligned with all other methods - but that's very odd-looking for demonstration purposes



I like your `round_timeframe` naming - this seems logical to me (and i know i'm bad at naming things anyway).

### Loop example:

It's for now a quick and dirty inline example - but i hope it illustrates the purpose i imagine for this.

``` python
from ccxt import Exchange, binance
from time import sleep

ROUND_DOWN = 'down'
ROUND_UP = 'up'
def round_timeframe(timeframe, direction, date):
    timeframe = Exchange.parse_timeframe(timeframe) * 1000
    # Get offset based on timerame in milliseconds
    offset = date % timeframe
    if direction == 'up':
        return date - offset + timeframe
    else:
        return date - offset
    
ex = binance()
pair='ETH/BTC'
timeframe = '5m'

candles = []
while True:
    
    if not candles or  candles[-1][0] >= round_timeframe(timeframe, ROUND_UP, Exchange.milliseconds()):
        print("polling")
        candles = ex.fetch_ohlcv(pair, timeframe)
        print(len(candles))
    else:
        print('sleeping')
        sleep(1)
```

**Comment by kroitor** [comment]
> It's for now a quick and dirty inline example - but i hope it illustrates the purpose i imagine for this.

Yep, it does illustrate the idea in an abstract form. However, I tend to think more practically, I mean, i'd rather take a realistic loop, i mean not the idea of how it could look like, but the actual code of how it should look like in reality. 

So, I suggest that we break it down a bit in order to clarify my point. 

The snippet above does traverse OHLCV for Binance, but it's not guaranteed to work with any other exchange, or with a unified API in general, because it assumes that fetchOHLCV will return the most recent candles if you omit `since` and `limit`. However, this is not true and it is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination

If you don't specify pagination arguments `since` and `limit` and you don't apply any of the pagination techniques described, then the result of `fetchOHLCV (symbol, timeframe)` will return an arbitrary set of candles, which will be exchange-specific (it will correspond to what the exchange returns by default without pagination params). 

Many exchanges return most recent candles, however, there are exchange that return candles starting from the beginning of the trade (for that specific symbol). For those exchanges calling `fetchOHLCV (symbol, timeframe)` in a loop will always return the same set of candles. And if you constantly get the same candles the above loop breaks down or loops infinitely (does not traverse the history)...

In order to fix the root cause of the issue, you will want to introduce `since` (which is a timestamp in milliseconds) and `limit` to your query: `fetchOHLCV (symbol, timeframe, since, limit)`. Or, if the exchange uses a page-based or id-based pagination, then you will want to define `params` as well: `fetchOHLCV (symbol, timeframe, since, limit, params)`.

And in that case your pseudocode loop becomes:

```Python

while True:
    
    if not candles or  candles[-1][0] >= round_timeframe(timeframe, ROUND_UP, Exchange.milliseconds()):
        print("polling")
        # ------------------------------------------------------------
        # need to introduce `since` and `limit` somewhere here
        # ------------------------------------------------------------
        candles = ex.fetch_ohlcv(pair, timeframe, since, limit, params)
        # Do some cool stuff with the candles ... -> business logic
    else:
        print('sleeping')
        sleep(1)
```

However, this is not the end of the story. Because you introduce `since`, the above logic should be reconsidered to actually increment since + offset to traverse over history. And the `since` value of your next query should be taken from the last candle from the previous query... 

And if you think about the ways of doing it, a unified interface to pagination in pseudocode it would look like:

```Python
if exchange.pagination === 'date-based':
    # loop over since + offset with a limit
    exchange.fetch_xxx (symbol, { since, limit })
elif exchange.pagination === 'id-based':
    # loop over ids
    exchange.fetch_xxx (symbol, { id })
elif exchange.pagination === 'page-based':
    # loop over pages
    exchange.fetch_xxx (symbol, { page: 1 })
elif exchange.pagination === 'offset-based':
    # loop using offset shifting
    exchange.fetch_xxx (symbol, { offset: 200 })  
else:
   ...
```

The hardest part here is making a complete unified interface that would wrap all of the above in a convenient set of methods. For example, we'd want to add a unified exchange property that would indicate the type of pagination used by this or that endpoint of this or that exchange, however, we need to add several significant changes to the underlying basecode, and this is not a very easy task, but we are making steady progress towards that.

**Comment by xmatthias** [comment]
Backing off from the exchange (as shown in the above example script) is **one** usecase, but definitely not the only one (detecting half-closed candles would be another usecase).

Adding since / limit is not a probem, (as you've shown above).

About pagination:
I think you're deviating from the purpose of this issue.
This about adding a helper-function to detect previous / next candle based on date (.

It's not about fixing pagination problems.
ccxt does not do a very good job unifying that in my eyes, especially with the id-based approach, which is different per exchange (`fetch_trades()` requires `params={"since": from_id}` for kraken, and `params={"fromId": from_id}` for binance).

I need to look up the correct `params` element in the exchange API to be able to correctly paginate - ccxt does not help with this (a attribute showing "paginate_attr" would be helpful here...).
However, this is a seperate issue i  have more thoughts about - is there an existing issue where this is discussed in detail?.


Your script is helpful, however none of the python example scripts implement pagination as you show / propose above (while using the since argument), all i've looked at simply instantiate one specific exchange (binance, kraken or gdax) and loop over that (most using the since attribute, some don't specify that at all - so would be subject to get "odd" results if only the exchange is changed).

My sample-script was meant to be added as a sample to an eventual PR - but i don't think correctly paginating should be the purpose of that script (none of the others do that, either).

**Comment by kroitor** [comment]
@xmatthias 

> This about adding a helper-function to detect previous / next candle based on date (.

I don't mind adding such a helper method, to be honest, so, if you feel like you want to give it a try – we welcome all PRs and contributions ) No problems with that )
