### ISSUE TITLE
Fix isJsonEncodedObject

### ISSUE THREAD

**Issue by f4bsch** [ccxt/ccxt#5721]
Some exchanges (started to?) send JSON response without proper content-type header and with leading whitespace. `isJsonEncodedObject`fails here.

This is a possible fix with `trimLeft()`:

```
    isJsonEncodedObject (object) {
        if ((typeof object === 'string') && (object.length >= 2)) {
            object = object.trimLeft ();
            return (object[0] === '{') || (object[0] === '[')
        } else {
            return false;
        }
    }
```

**Comment by kroitor** [comment]
@f4bsch

> Some exchanges (started to?) send JSON response without proper content-type header and with leading whitespace.

Which particular exchanges?

What's your version of CCXT?

**Comment by f4bsch** [comment]
`We intentionally avoid trimming all strings in this case.`
Why? `    []` is a valid JSON string.

I couldn't think of any case where the `trimLeft()` breaks the current behavior. 

For example [btcbox](https://www.btcbox.co.jp/api/v1/orders?coin=ltc).

**Comment by f4bsch** [comment]
@frosty00 Please read my issue properly. Its about JSON detection, prior to parsing.

**Comment by kroitor** [comment]
> For example btcbox.

This is exactly the reason I asked about which particular exchange and which particular version of CCXT you have... Because we detected this issue 2 days ago and fixed it here:

- https://github.com/ccxt/ccxt/commit/9c95b21d74ecdd1596206bc1e90fe02f50584244#diff-1d7455fc7a166caba5268b86312d88d6

So, if you update to version 1.18.1079, this should be fixed. Let us know if that does not help.

**Comment by f4bsch** [comment]
I missed the btcbox specific fix, thanks for pointing that out.

Still, I think there is a bug in `isJsonEncodedObject` because `isJsonEncodedObject("   []")` returns false.
