### ISSUE TITLE
Optimization of BitMex fetch_balance() method

### ISSUE THREAD

**Issue by qwasko1212** [ccxt/ccxt#5737]
I am trying to optimize number of requests sent to bitmex. 
When i call method fetch_balance(), it calls await self.load_markets() inside, what is absolutely inapropriate for me, since i need to use fetch_balance() frequently. self.load_markets() uses public API which are limited per IP address with 30 requests. Is it possible to get rid of self.load_markets() inside fetch_balance() in your library by default, or i have to do it by myself? Method fetch_balance() returns same result without self.load_markets().

- OS: Linux
- Programming Language version: Python 3.5
- CCXT version: 1.18.1093
- Exchange: BitMex
- Method: fetch_balance()

**Comment by kroitor** [comment]
```Python
import ccxt
exchange = ccxt.bitmex({
    'enableRateLimit': True,
})
exchange.load_markets()   # load them once
for i in range(0,5):
    print(exchange.fetch_balance())  # won't call load_markets
```

A call to a unified method will trigger `loadMarkets()` once and will cache the markets further. It will not trigger loadMarkets, unless you destroy and recreate the exchange instance. So, in order to avoid it being triggered by fetchBalance – you just need to load them manually once or load them from a file or whatever other storage of presaved markets you have.

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#market-cache-force-reload

> Method fetch_balance() returns same result without self.load_markets().

It will not work without knowing the symbol←→id mappings that are loaded with markets. 

Let us know if the above does not answer the question.
