### ISSUE TITLE
Kraken fetch_balance doesn't show free and used balance

### ISSUE THREAD

**Issue by AurelReb** [ccxt/ccxt#5818]
- OS: Ubuntu 16.04
- Programming Language version: Python 3.6
- CCXT version: 1.18.1146
- Exchange: Kraken
- Method: fetch_balance

Hi, kraken.fetch_balance() returns only total balance. I know kraken doesn't return the free and the used balance, but they have another rest API for this case: TradeBalance

Could kraken fetch_balance method include this to get the free and the used balance in addition to the total balance?

Thank you very much

**Comment by kroitor** [comment]
> Hi, kraken.fetch_balance() returns only total balance.

Right: 

- https://github.com/ccxt/ccxt/issues/5776
- https://github.com/ccxt/ccxt/issues/5587
- https://github.com/ccxt/ccxt/issues/5292

> I know kraken doesn't return the free and the used balance, but they have another rest API for this case: TradeBalance

It is for margin trading, not for spot trading and it requires a quote currency argument (not for all currencies).

> Could kraken fetch_balance method include this to get the free and the used balance in addition to the total balance?

Unfortunately, nope, because those are not interchangeable.

Let us know if the above does not answer the question.

**Comment by AurelReb** [comment]
Thank you for the quick reply!
Sorry to don't search enough for other duplicated issues.

So I will use the total balance and contact Kraken to see if they can change their API.
