### ISSUE TITLE
[EAPI:Invalid nonce] with Kraken

### ISSUE THREAD

**Issue by Droppix** [ccxt/ccxt#5846]
### Overview
Unable to fetch a fetchBalance() with ccxt.kraken

### Details
OS: darwin (MacOS v10.14.6)
Programming Language version: Node.js LTS (v10.5.3)
CCXT version: v1.18.1175
Exchange: Kraken
Method: .fetchBalance()

### Error output
(node:44036) UnhandledPromiseRejectionWarning: InvalidNonce: kraken {"error":["EAPI:Invalid nonce"]}

### Suggestion:
Replace this : **nonce () { return this.milliseconds ();}**
by : **nonce () {return new Date() * 1000;}**

**Comment by kroitor** [comment]
@Droppix is this a new key or a key that has already been used with a different application?

**Comment by kroitor** [comment]
@Droppix Have you tried anything from the troubleshooting sequence from the Manual?

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by kroitor** [comment]
Duplicates:

- https://github.com/ccxt/ccxt/issues/5110
- https://github.com/ccxt/ccxt/issues/253
- https://github.com/ccxt/ccxt/search?q=kraken+invalid+nonce&type=Issues

**Comment by Droppix** [comment]
My key/secret was created a few days ago and works well with the official API.

1/ With verbose = true
Object {Cf-Ray: "519c7a7e1b77a8b5-CDG", Connection: "close", Content-Encoding: "gzip", Content-Type: "application/json; charset=utf-8", Date: "Sat, 21 Sep 2019 13:45:15 GMT", …}
Exchange.js:626
19:

 {"error":["EAPI:Invalid nonce"]} 

2/ If I replace nonce () { return this.milliseconds ();} by nonce () {return new Date() * 1000;}, it's works.

**Comment by kroitor** [comment]
> My key/secret was created a few days ago and works well with the official API.

@Droppix you cannot interchange software with the same API key, since the official API uses nonces in microseconds, while the CCXT's default is milliseconds. Therefore if you create a new key and don't use it with another code, but use it with CCXT – it will work. Otherwise, your nonce gets screwed too high by the "official API" and then it's not usable with milliseconds. It works with CCXT if you redefine your nonce to microseconds, but you should not really do that, unless it's necessary. And it's not necessary, if you don't mix keys/software.

**Comment by Droppix** [comment]
ok, I understand! 
Thanks
