### ISSUE TITLE
kukoin not fetching amount for all accounts

### ISSUE THREAD

**Issue by obsidianart** [ccxt/ccxt#5849]
- OS: React native
- Programming Language version: js
- CCXT version: 1.18.1176
- Exchange: kukoin
- Method:fetchBalance

I got a few users asking why they can't see their kukoin balance, after some research this is due to kukoin type specified in the balance

```
    async fetchBalance (params = {}) {
        await this.loadMarkets ();
        const request = {
            'type': 'trade',
        };
```

Removing 'type': 'trade' returns also type:main, is there any reason not to include it in the balance?

**Comment by kroitor** [comment]
By default CCXT will show the trading account, that is, the account used for spot trades. The logic behind the unified balance structure is such that `total['BTC'] = free['BTC'] + used['BTC']`. If we add more than one account into this (margin account + spot account + some other type of account) – the logic breaks down, since the sub-account values have to be indexed by account types. Therefore we will return the trading balance by default and will allow the users to redefine the request params, as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Let us know if that does not answer it.
