### ISSUE TITLE
Transaction Details [GET/api/spot/v3/fills?] madness

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5912]
Does anyone understand how to get my fills from the okex3 api?  When i get the trades for an order there's a weird mix of buys and sells in there.  Some have fees, some don't.  I can see from the comments in the code that it's a ledger-style response.  But I can't seem to pair them up in a sensible way.

Here's an example for a maker sell order:
```
[
  {
    "created_at": "2019-10-03T15:01:22.000Z",
    "exec_type": "M",
    "fee": "-0.00000035",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7377679066",
    "liquidity": "M",
    "order_id": "3628171542291456",
    "price": "0.0068",
    "product_id": "XMR-BTC",
    "side": "buy",
    "size": "0.00034151",
    "timestamp": "2019-10-03T15:01:22.000Z"
  },
  {
    "created_at": "2019-10-03T15:01:22.000Z",
    "exec_type": "M",
    "fee": "-0.00000081",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7377679065",
    "liquidity": "M",
    "order_id": "3628171542291456",
    "price": "0.0068",
    "product_id": "XMR-BTC",
    "side": "buy",
    "size": "0.00080115",
    "timestamp": "2019-10-03T15:01:22.000Z"
  },
  {
    "created_at": "2019-10-03T15:01:22.000Z",
    "exec_type": "M",
    "fee": "-0.00000062",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7377679064",
    "liquidity": "M",
    "order_id": "3628171542291456",
    "price": "0.0068",
    "product_id": "XMR-BTC",
    "side": "buy",
    "size": "0.00061841",
    "timestamp": "2019-10-03T15:01:22.000Z"
  },
  {
    "created_at": "2019-10-03T15:01:22.000Z",
    "exec_type": "M",
    "fee": "0",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7377679063",
    "liquidity": "M",
    "order_id": "3628171542291456",
    "price": "0.0068",
    "product_id": "XMR-BTC",
    "side": "sell",
    "size": "0.050223",
    "timestamp": "2019-10-03T15:01:22.000Z"
  },
  {
    "created_at": "2019-10-03T15:01:22.000Z",
    "exec_type": "M",
    "fee": "0",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7377679062",
    "liquidity": "M",
    "order_id": "3628171542291456",
    "price": "0.0068",
    "product_id": "XMR-BTC",
    "side": "sell",
    "size": "0.117817",
    "timestamp": "2019-10-03T15:01:22.000Z"
  },
  {
    "created_at": "2019-10-03T15:01:22.000Z",
    "exec_type": "M",
    "fee": "0",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7377679061",
    "liquidity": "M",
    "order_id": "3628171542291456",
    "price": "0.0068",
    "product_id": "XMR-BTC",
    "side": "sell",
    "size": "0.090943",
    "timestamp": "2019-10-03T15:01:22.000Z"
  },
  {
    "created_at": "2019-10-03T15:01:17.000Z",
    "exec_type": "M",
    "fee": "-0.00002643",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7377678247",
    "liquidity": "M",
    "order_id": "3628171542291456",
    "price": "0.0068",
    "product_id": "XMR-BTC",
    "side": "buy",
    "size": "0.0264257",
    "timestamp": "2019-10-03T15:01:17.000Z"
  },
  {
    "created_at": "2019-10-03T15:01:17.000Z",
    "exec_type": "M",
    "fee": "0",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7377678246",
    "liquidity": "M",
    "order_id": "3628171542291456",
    "price": "0.0068",
    "product_id": "XMR-BTC",
    "side": "sell",
    "size": "3.886133",
    "timestamp": "2019-10-03T15:01:17.000Z"
  }
]
```
... and a taker sell order:

```
[
  {
    "created_at": "2019-10-03T08:46:33.000Z",
    "exec_type": "T",
    "fee": "-0.00000051",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7374219830",
    "liquidity": "T",
    "order_id": "3627836574017536",
    "price": "0.0067",
    "product_id": "XMR-BTC",
    "side": "buy",
    "size": "0.000335",
    "timestamp": "2019-10-03T08:46:33.000Z"
  },
  {
    "created_at": "2019-10-03T08:46:33.000Z",
    "exec_type": "T",
    "fee": "0",
    "instrument_id": "XMR-BTC",
    "ledger_id": "7374219829",
    "liquidity": "T",
    "order_id": "3627836574017536",
    "price": "0.0067",
    "product_id": "XMR-BTC",
    "side": "sell",
    "size": "0.05",
    "timestamp": "2019-10-03T08:46:33.000Z"
  }
] 
```

**Comment by kroitor** [comment]
@npomfret yes, it's very inconvenient, but with okex (either 1 or 3) you have to remember the order history to match orders against fills and calculate the fees properly. Also, we've noticed missing fills/missing orders in their API, and there may be gaps in the date-based pagination (like, they will only serve 3-day history), so, it cannot be used reliably to deduce the entire history, you may want to save the balance deltas in order to match them with fills over time. Unfortunately, this is not something that we can work around on our side, as this issue is fully dependent on the exchange API itself. Let us know if you have specific questions on this matter, we will be happy to help (where we can).

**Comment by kroitor** [comment]
@npomfret 

In the second case you see two "fills", but those are not really fills in common sense, those are OKEX's ledger records, and you have at least two records for both sides of the trade – you give some currency, thus a sell, and you receive some currency, thus a buy. The currency you gave is not charged any fee. The currency you received – is charged with the fee (so, in this trade you've paid the fee from the currency you've received). OKEX calls those records "buy" and "sell", but in fact they should be treated "given"/"received" – it will make a lot more sense.

Therefore in OKEX terms each record corresponds to one of the two sides of the trade, as seen from your perspective. This is easy to see from your second example, since it has only one actual fill that is represented by a pair of "given/received" records in the OKEX ledger.

The first example is logically identical, the only difference is that each actual fill will generate two ledger records, therefore in the first example you see more than one pair of "buy-sells".

Hope that answers your question, let me know if not.
