### ISSUE TITLE
[request] fix bitbay fees

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5917]
I can't find an ([unauthenticated](https://docs.bitbay.net/v1.0.1-en/reference#fee-and-market-configuration))  API call unfortunately... https://bitbay.net/en/fees

**Comment by lead4good** [comment]
@kroitor in the documentation the market structure does not include any fees. This is necessary for this issue to be fixed however since we have different markets with different fee structures. I could supply an (undocumented) fix similar to #6685, listing the fees as `taker` and `maker` in the market structure.

**Comment by kroitor** [comment]
> I could supply an (undocumented) fix similar to #6685, listing the fees as `taker` and `maker` in the market structure.

Yes, thank you!

> @kroitor in the documentation the market structure does not include any fees. This is necessary for this issue to be fixed however since we have different markets with different fee structures. 

Right, the only reason why `taker` and `maker` are not mentioned in the Manual yet – is because we didn't have them unified for all exchanges. However, saving them to `taker` and `maker` is the correct way to handle market-specific fees and we will document those fields in the Manual shortly. So, `market['taker']` and `market['maker']` are going to be unified across all exchanges in the same way (this process is covered by 50% or more at this time).
