### ISSUE TITLE
Please update fetch_balance details of Liquid Exchange

### ISSUE THREAD

**Issue by JosephWN** [ccxt/ccxt#6001]
- OS: Ubuntu 18.04
- Programming Language version: Python 3.6
- CCXT version: 1.18.1279
- Exchange: Liquid
- Method: fetch_balance by CCXT API

Refer to the API document of Liquid (https://developers.liquid.com/#get-an-account-details), in section of "Get an Account Details" and "Get Reserved Balance Details". 

The balance details of Liquid Exchange now supports "free balance", "used balance" and "total balance". The current CCXT fetch_balance function can only get "total balance" information, please update CCXT fetch_balance function.

Thanks a lot! ^_^

**Comment by kroitor** [comment]
> The current CCXT fetch_balance function can only get "total balance" information, please update CCXT fetch_balance function.

The existing fetch_balance function will issue a single HTTP request per call, so it uses this endpoint to fetch all balances: https://developers.liquid.com/#get-all-account-balances. Unfortunately, that endpoint only serves a single `balance` value. So there's no way to fetch all detailed balances at once, unfortunately. We cannot issue multiple HTTP requests per call, since it will take an eternity to fetch all balances one by one, and this is against the design of the lib.

Let us know if that does not answer this issue.

**Comment by JosephWN** [comment]
I see, thanks for your quick response!

Send from Outlook<https://aka.ms/qtex0l> for iOS.
________________________________
发件人: Igor Kroitor <notifications@github.com>
发送时间: Saturday, October 19, 2019 3:29:57 PM
收件人: ccxt/ccxt <ccxt@noreply.github.com>
抄送: JosephWN <weinquant@outlook.com>; Author <author@noreply.github.com>
主题: Re: [ccxt/ccxt] Please update fetch_balance details of Liquid Exchange (#6001)


Closed #6001<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fccxt%2Fccxt%2Fissues%2F6001&data=02%7C01%7C%7C135f415ee3ee4606734a08d7546624c2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637070669989325328&sdata=yh9%2BSQCORn06ks7zRW2C3nW6IZKfNFgpRN1i3sZXQI8%3D&reserved=0>.

―
