### ISSUE TITLE
it is not possible to withdraw usdt with tron network on binance

### ISSUE THREAD

**Issue by blue73** [ccxt/ccxt#6017]
- OS: MacOS
- Programming Language version: js with node 12.10.0
- CCXT version: 1.18.1315
- Exchange: binance
- Method: withdraw

i'm trying to withdraw usdt with tron network from binance to poloniex:
const info = await exchangeBinance.withdraw('USDT', 10, 'TZXXXXXXXXX5aUBy3MZics92earBD6y9bn', null, {})

(I've changed nine letters to X)

I'm getting this error:
ExchangeError: binance {"msg":"Address verification failed","success":false}

I've doublechecked the address.

On the web frontend it works. I get this info when I fetch the withdrawals:

{
      info: {
        amount: 82.76588378,
        transactionFee: 0,
        address: 'TZXXXXXXXXX5aUBy3MZics92earBD6y9bn',
        addressTag: null,
        txId: 'X',
        id: 'X',
        asset: 'USDT',
        applyTime: 1571821825000,
        status: 6
      },
      id: 'X',
      txid: 'X',
      timestamp: 1571821825000,
      datetime: '2019-10-23T09:10:25.000Z',
      address: 'TZXXXXXXXXX5aUBy3MZics92earBD6y9bn',
      tag: undefined,
      type: 'withdrawal',
      amount: 82.76588378,
      currency: 'USDT',
      status: 'ok',
      updated: undefined,
      fee: undefined
    }

**Comment by kroitor** [comment]
@blue73 from this doc:

- https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#withdraw

↑ it looks like you have to provide the `network` argument in order to specify the actual withdrawal network, since Binance allows withdrawing USDT to Omni addresses, ERC20 addresses and other networks.

You can pass that in the last argument to the `withdraw()` call as described in the Manual, here:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```JavaScript
const params = {
    'network': 'YOUR_NETWORK_HERE',
}
const info = await exchangeBinance.withdraw('USDT', 10, 'TZXXXXXXXXX5aUBy3MZics92earBD6y9bn', null, params)
```

Let us know if the above does not answer the question.

**Comment by blue73** [comment]
It works!
Thx!

Igor Kroitor <notifications@github.com> schrieb am Mi., 23. Okt. 2019,
14:29:
