### ISSUE TITLE
Passing keys to cli.py from keys.json

### ISSUE THREAD

**Issue by interzonez** [ccxt/ccxt#6032]
I've hunted for an answer. Using cli.py

How to pass keys from keys.json or keys.local.json to cli.py ? My below attempt failed. 

`    "bitforex":      { "skip": true },
    "bithumb":       { "skip": true },
    "bitmex":       {"apiKey": '****', "secret": '****'},
    "bitibu":        { "skip": true },
    "bitkk":         { "skip": true },
`

- OS: Ubuntu 18
- Programming Language version: python
- CCXT version: latest
- Exchange: Bitmex
- Method: keys

**Comment by kroitor** [comment]
@interzonez your attempt is almost correct, the contents of the file should be:

```JavaScript
{
    "bitmex": {"apiKey": "****", "secret": "****"},
}
```

↑ Use double quotes (`"`) instead of single quotes (`'`) everywhere throughout the JSON file. 

The two files work like this:

- if `keys.local.json` is present, then `cli.py` will load the keys from there
- if `keys.local.json` is missing, `cli.py` will try to load the keys from `keys.json`, if it's present

Let us know if that does not answer the question.

**Comment by interzonez** [comment]
Many thanks, works.
What's the difference between using `keys.local.json` and `keys.json`  ?

**Comment by kroitor** [comment]
> What's the difference between using keys.local.json and keys.json ?

`keys.json` is used for shared keys that may be used on our Travis CI for private testing, so it is a part of the repo, and `keys.local.json` is your local override, that is not a part of the repo. I'd recommend to use `keys.local.json` for your personal keys and private testing.
