### ISSUE TITLE
[question] rate limit error type?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6057]
Is the `DDoSProtection` network error the one to use if a _rate limit exceeded_ type error is encountered?

**Comment by kroitor** [comment]
In most cases we throw DDoSProtection, since the rate limit itself is for protecting from abuse. We can subclass a specific type of DDoSProtection and call it RateLimitExceeded or something like that if that will help handle the exceptions better in userland. Do you need a more specific class of errors for these exceptions?

**Comment by npomfret** [comment]
> We can subclass a specific type of DDoSProtection and call it RateLimitExceeded if that will help 

That sounds like a good idea.
