### ISSUE TITLE
Pandas Memory Error when building database of Historical Data

### ISSUE THREAD

**Issue by topchatz** [ccxt/ccxt#6058]
- OS: Windows 8
- Programming Language version: Python 3.6.1
- CCXT version: 1.18.1093
- Exchange: Binance
- Method: Fetch_OHLCV

Hi guys, I have a bit of a strange one.

I have a script I run every now and again that gets a bunch of historical data for every symbol on Binance. Up until yesterday it worked absolutely no problems, however yesterday no matter what I tried my laptop would basically grind to a halt. So I then tried it on my windows machine and I at least get an error, which is simply 'Memory Error' after iterating through the first first 20 or so coins. I have now gone back to basics and am just trying to run the simple script below, and I still get this memory error.

```
import ccxt
import pandas as pd
import datetime as dt

binance = ccxt.binance()

prices = pd.DataFrame()

for i in binance.load_markets():
    if i[-3:] == 'BTC':
        if binance.market(i)['active'] == True:
            df = pd.DataFrame(binance.fetch_ohlcv(i, '1h', limit=1000))
            df.columns = ['Date', 'o', 'h', 'l', i, 'v']
            df['Date'] = [dt.datetime.fromtimestamp(x/1000) for x in df['Date']]
            if prices.empty:
                prices = df[['Date', i]]
            else:
                prices = prices.merge(df[['Date', i]], on='Date', how='left')
prices.set_index('Date', inplace=True)
print(prices)
```

I have no idea why this suddenly won't work for me, and it appears to be nothing to do with my machine as I have tried the same thing on two different computers, one windows one mac. I don't imagine it does make a difference but I am from London and we just changed our clocks on Sunday, seems a bit coincidental?

Any suggestions/help would be really appreciated

**Comment by topchatz** [comment]
I don't know if this helps at all, but I have been playing around. So I've run that script many times now and it crashes on the 22nd coin. Which when listed alphabetically is BNB/BTC. However, it's nothing to do with BNB/BTC because when I remove it from the alphabetical list I was looping through, it just crashes on the one after BNB.

One thing I have found though is pd.concat instead of pd.merge causes no memory errors which I thought was interesting. I've always used pd.merge mind you and never had any problems whatsoever. I'd still rather use merge though as so many of Binances coins now are recently listed, when I go back further in time than the original 1000 limit using pd.concat causes problems as I can't 'merge on' the Date, as it were.

Hope this helps in some way,

cheers

**Comment by kroitor** [comment]
@topchatz first of, you're not using the rate-limiter despite that it is required to rate limit your requests, as explained in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit, so it should be

```Python
binance = ccxt.binance({'enableRateLimit': True})
```

On your question itself, unfortunately, it is beyond the scope of this lib. I'm almost sure that this issue has nothing to do with CCXT, but related to the way you handle the data with pandas. However, there's a better place for support on pandas, you might want to ask this question here (this is what I would suggest):

- https://github.com/pandas-dev/pandas/
- https://github.com/pandas-dev/pandas/issues
- https://github.com/pandas-dev/pandas/search?q=memory+error+merge&type=Issues
- https://github.com/pandas-dev/pandas/search?q=memory+error+merge&unscoped_q=memory+error+merge

↑ Pandas has its own GitHub, you should really try it ;) From my experience most of the memory errors with pandas come from running very costly operations on dataframes just to do a very simple thing that can be done easier (like, joins or merges of lengthy unindexed dataframes, for example). So, you would want to research and google more on what is the actual memcost and the inner workings of the pd operations you want to use in your code. 

> I don't imagine it does make a difference but I am from London and we just changed our clocks on Sunday, seems a bit coincidental?

Most likely, it has nothing to do with your PC, your location or your system clocks ) The most likely cause of your issue is the way you use `.columns` with `.merge`.

> One thing I have found though is pd.concat instead of pd.merge causes no memory errors which I thought was interesting.

This is a strong indication that you're doing `.merge` the way it should not be done (and maybe you don't have to `.merge` at all).

-------------------------------

Here's a snippet of code to demonstrate that this issue is not related to CCXT, loading more than 22 OHLCV series without using pandas at all and without running into a memory error:

```Python
import ccxt
from pprint import pprint

exchange = ccxt.binance({
    'enableRateLimit': True,
})

markets = exchange.load_markets()

series = {}
i = 1
for symbol, market in exchange.load_markets().items():
    if (market['quote'] == 'BTC') and market['active']:
        print('---------------------------------------------------------------')
        print(i, 'loading OHLCV series for', symbol)
        ohlcv = exchange.fetch_ohlcv(symbol, '1h', limit=1000)
        series[symbol] = ohlcv
        pprint(ohlcv)
        print(i, ' ↑ OHLCV series for', symbol)
        i += 1

# do whatever is needed with the series here

print('Done.')

```

Also, i find this line of your code very confusing:

```Python
df.columns = ['Date', 'o', 'h', 'l', i, 'v']  # why this list has symbol i in place of 'c' here?
```

> I'd still rather use merge though as so many of Binances coins now are recently listed, when I go back further in time than the original 1000 limit using pd.concat causes problems as I can't 'merge on' the Date, as it were.

I'd recommend to address this question to the pandas community – you will definitely get help on this specific issue a lot faster there.

Hope it helps. Closing this for now, if you don't mind. Feel free to ask further questions if you don't get any luck with the pandas GitHub or stackoverflow.

**Comment by topchatz** [comment]
Hi Mate, 

Thanks very much for your input. Apologies for not using the Rate Limit I'll use this in future. 

I agree it does appear to be due to using merge, which is really odd as I've never encountered this problem using merge before while building databases with CCXT. I think I will just have to rewrite everything and use concat some how.

Many thanks
