### ISSUE TITLE
Coinbase client has incorrect hard-coded markets

### ISSUE THREAD

**Issue by evan-coygo** [ccxt/ccxt#6066]
- OS: Linux Mint
- Programming Language version: JS
- CCXT version: 1.18.1358
- Exchange: Coinbase
- Method: loadMarkets

There is currently a hard-coded list of markets. This is incorrect, Coinbase has added a lot of new coins/tokens since this list was created. Ideally it should be dynamically created.

https://github.com/ccxt/ccxt/blob/master/js/coinbase.js#L145
```js
 'markets': {
                'BTC/USD': { 'id': 'btc-usd', 'symbol': 'BTC/USD', 'base': 'BTC', 'quote': 'USD' },
                'LTC/USD': { 'id': 'ltc-usd', 'symbol': 'LTC/USD', 'base': 'LTC', 'quote': 'USD' },
                'ETH/USD': { 'id': 'eth-usd', 'symbol': 'ETH/USD', 'base': 'ETH', 'quote': 'USD' },
                'BCH/USD': { 'id': 'bch-usd', 'symbol': 'BCH/USD', 'base': 'BCH', 'quote': 'USD' },
                'BTC/EUR': { 'id': 'btc-eur', 'symbol': 'BTC/EUR', 'base': 'BTC', 'quote': 'EUR' },
                'LTC/EUR': { 'id': 'ltc-eur', 'symbol': 'LTC/EUR', 'base': 'LTC', 'quote': 'EUR' },
                'ETH/EUR': { 'id': 'eth-eur', 'symbol': 'ETH/EUR', 'base': 'ETH', 'quote': 'EUR' },
                'BCH/EUR': { 'id': 'bch-eur', 'symbol': 'BCH/EUR', 'base': 'BCH', 'quote': 'EUR' },
                'BTC/GBP': { 'id': 'btc-gbp', 'symbol': 'BTC/GBP', 'base': 'BTC', 'quote': 'GBP' },
                'LTC/GBP': { 'id': 'ltc-gbp', 'symbol': 'LTC/GBP', 'base': 'LTC', 'quote': 'GBP' },
                'ETH/GBP': { 'id': 'eth-gbp', 'symbol': 'ETH/GBP', 'base': 'ETH', 'quote': 'GBP' },
                'BCH/GBP': { 'id': 'bch-gbp', 'symbol': 'BCH/GBP', 'base': 'BCH', 'quote': 'GBP' },
            },
```

**Comment by kroitor** [comment]
> Ideally it should be dynamically created.

Yes, and the problem is that the Coinbase API does not serve a full list of supported pairs, just the currencies. We can't create those pairs from currencies, because they have 169 currencies and they don't give an indication which currencies are base or quote, so, if we pair all-to-all currencies, that means 169² = 28561 markets, and not all of those pairs will work.

@evan-coygo plz share if you find a way to load or create those markets for Coinbase dynamically. We are looking for a solution as well.

Let me know if that does not answer the question.

**Comment by dblue** [comment]
@kroitor--

I don't think it is **28,561** markets. Instead, I think Coinbase trades 18 cryptocoins in 169 currencies in **3,042** markets. 

```publicGetCurrencies``` returns 169 fiat currencies and ```publicGetExchangeRates['data']['currency']``` returns 187 currencies (18 crypto and 169 fiat). The [pricing page](https://www.coinbase.com/price) lists 17 cryptos that can be traded; the 18th crypto is BSV but I think the page is slightly outdated because I can access a BSV-USD market.

So, the ```base``` is a crypto currency and ```quote``` is a fiat currency. Coinbase does not appear to trade cryptos for cryptos; that's reserved for Coinbase Pro.

```
> coinbase.publicGetPricesSymbolBuy({'symbol' => 'BSV-USD'})
=> {"data"=>{"base"=>"BSV", "currency"=>"USD", "amount"=>"134.75"}}

> coinbase.publicGetPricesSymbolBuy({'symbol' => 'BTC-USD'})
=> {"data"=>{"base"=>"BTC", "currency"=>"USD", "amount"=>"9233.95"}}

> coinbase.publicGetPricesSymbolBuy({'symbol' => 'BSV-BTC'})
RestClient::NotFound: 404 Not Found

> coinbase.publicGetPricesSymbolBuy({'symbol' => 'BTC-ETH'})
RestClient::NotFound: 404 Not Found
```
(Forgive the appearance of the code... I'm hacking away at the Ruby fork.)

**Comment by kroitor** [comment]
@dblue thx so much for the info! Will add this to the implementation shortly.

**Comment by kroitor** [comment]
Plz update to version 1.18.1360 and let us know if you have any issues with it. Thank you! )
