### ISSUE TITLE
Question on Poloniex's spot trading fees

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#6073]
- OS: Any
- Programming Language version: Any
- CCXT version: 1.18.362
- Exchange: Poloniex
- Method: -

Poloniex is charging 0 trading fees until the end of the year, and CCXT files have been changed accordingly.
Nevertheless, Poloniex has a private endpoint (used in CCXT's fetchTradingFees()) that returns the current fees for the user accessing it. fetchTradingFees() works correctly, and returns the trading fees for the tier the user is on. It currently returns 0% for both maker and taker, without having to modify the static fees in CCXT.

I'm just wondering if the modification of the static fees should indeed be done. After all the fees have no meaning if there is no authenticated user to make a trade.

**Comment by kroitor** [comment]
> I'm just wondering if the modification of the static fees should indeed be done.

Tbh, we would rather remove all those hardcoded magic numbers from the lib. This is something we are going to address soon, hopefully. But for now, we have to maintain them up to date for less confusion, since `fetchTradingFees()` isn't fully documented in the Manual yet.

> After all the fees have no meaning if there is no authenticated user to make a trade.

Totally agree with you on this!

Let me know if the above does not answer the question. Thx!
