### ISSUE TITLE
Poloniex fetch_ohlcv not working

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#6076]
- OS: linux
- Programming Language version: python
- CCXT version: 1.19.2
- Exchange: poloniex
- Method:fetch_ohlcv

using the regular `fetch_ohlcv()` method does not work.

```
import ccxt
ct = ccxt.poloniex()
lm= ct.load_markets()
# ct.verbose = True
# Does not work
# ct.fetch_ohlcv('BTS/BTC', timeframe="15m", limit=500)
#
ct.fetch_ohlcv('BTS/BTC', timeframe="5m", limit=1000, params={'start': 1572645000, 'end': 1572701499})
```

When using this without "since" - there is one single line with an empty ohlcv array
```
[[0, 0.0, 0.0, 0.0, 0.0, 0.0]]
```

Not proving the `limit` argument - which is optional according to the documentation results in 
`{"error":"Data requested is too large. Please specify a longer period or a shorter date range, or use resolution=auto to automatically calculate the shortest supported period for your date range."}`

Debugging the above call (with limit=500):
the call `https://poloniex.com/public?command=returnChartData&currencyPair=BTC_BTS&period=900&start=0&end=450000 ` seems odd as well - end seems "way too low" - as the working example uses epoch (in seconds) ...

**Comment by kroitor** [comment]
Hi!

First of, Poloniex ohlcv endpoint requires the `start` argument in seconds. If you specify `since` in milliseconds – CCXT will take that and will put that into `start` in seconds. If you omit `since`, ccxt will default to 0, meaning "the beginning of time", 1 Jan 1970. If you specify a limit, but don't specify the `since` argument, the range will be `[ 0 ; 0 + 1000_limit * 5m_timeframe ] = [ 0, 450000 ]`. 

Now, BTS/BTC was not traded on Polo back then, so when you select that datetime range, you get an empty response, which Polo serves as a single candle with zeroed values.

If you specify both `since` and `limit` – then the range is: `[ since; since + limit*timeframe ]`. If you specify both the `since` and the `limit` via the args (not via `params` overrides), then it should work:

```Python
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> e = ccxt.poloniex()
>>> candles = e.fetch_ohlcv('BTS/BTC', '5m', 1572645000000, 1000)
>>> len(candles)
204
```

We will add some changes shortly, to it to make this more intuitive and to make it work with the overrides properly.

**Comment by xmatthias** [comment]
using epoch (or unixtimestamp) 0 as start is odd for any cryptocurrency exchange - since None of these will have existed in 1970 ... (not even in the head of people, most likely).

Thanks for fixing @kroitor :+1:

**Comment by kroitor** [comment]
> using epoch (or unixtimestamp) 0 as start is odd for any cryptocurrency exchange

Polo used to serve the entire history range from start to current moment previously, so a range of [ 0; now ] resulted in all candles for a symbol/timeframe. This wasn't scalable, however, so they had to switch to a limited mode and they now require a range of values, therefore [ 0; now ] would not work anymore. So, we fixed this in 1.19.3.

@xmatthias thx for reporting, appreciate it!

**Comment by sdroy101** [comment]
So if we wish to withdraw past 1 year OHLCV data of 5m interval, we can't do it in poloniex. Because it's restricted ("Please specify a longer period or a shorter date range, or use resolution=auto to automatically calculate the shortest supported period for your date range."). Is there any other way?

**Comment by kroitor** [comment]
@sdroy101 that specific message is not about the 1-year limitation, though, it says that your range is too long, and in that case the end date should be supplied for it in the params overrides, or the limit should be supplied via args, as described in the Manual on pagination:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination

However, even if you supply the proper arguments, Poloniex will not allow to query beyond 1 year in the past (the error message will be different in that case). There's no way to workaround that, at least, we don't know about it.

**Comment by sdroy101** [comment]
@kroitor actually I've just started exploring ccxt and my problem might sound trivial. Actually I want to fetch '5m' data of last 1-year and 6 months ohlcv of BTC/USDT from poloniex using ccxt. I tried setting the 'since' and 'limit' accordingly but It showed the above error. can you please specify the necessary changes in this code?

import ccxt
ct = ccxt.poloniex()
candles = ct.fetch_ohlcv('BTC/USDT', '5m', 1580515200000,params={'end': 1593561600})

**Comment by kroitor** [comment]
@sdroy101 you will have to do that in a loop, plz, read the Manual on pagination:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination

----------------------------------

See this example:

- https://github.com/ccxt/ccxt/tree/master/examples/py/poloniex-fetch-ohlcv-with-pagination.py

```Python
# -*- coding: utf-8 -*-
import ccxt

exchange = ccxt.poloniex({'enableRateLimit': True})
exchange.load_markets()

# Poloniex will only serve one year of data into the past

symbol = 'BTC/USDT'
timeframe = '5m'
since = exchange.parse8601('2019-01-01T00:00:00Z')
previous_length = 0
all_candles = []
limit = 1000
duration = exchange.parse_timeframe(timeframe) * 1000
now = exchange.milliseconds()

while since < now:
    try:
        print('---------------------------------------------------------------')
        print('Fetching ohlcvs since', exchange.iso8601(since))
        candles = exchange.fetch_ohlcv(symbol, timeframe, since, limit)
        print('Fetched', len(candles), 'candles')
        print('From', exchange.iso8601(candles[0][0]), 'to', exchange.iso8601(candles[-1][0]))
        since = candles[-1][0] + duration
        all_candles += candles
        total_length = len(all_candles)
        print('Fetched', total_length, 'candles in total')
    except ccxt.NetworkError as e:
        print(e)  # retry on next iteration
    except ccxt.ExchangeError as e:
        print(e)
        break

print('Fetched', len(all_candles), 'candles since', exchange.iso8601(all_candles[0][0]), 'till', exchange.iso8601(all_candles[-1][0]))
```

**Comment by kroitor** [comment]
@sdroy101 i'd highly recommend to read the entire Manual carefully from top to bottom at least once, it will save your time, really.
