### ISSUE TITLE
exchange.fees trading fee_loaded info not found

### ISSUE THREAD

**Issue by Rajeshinu** [ccxt/ccxt#6099]
Hi ,

in exchange.fees fee_loaded = False ..?
i want to know what is "fee_loaded" in the exchange.fees
what it means for true and false
fee_loaded = false and fee_loaded = true
not able to find the proper document for this fee_loaded details

**Comment by kroitor** [comment]
Hi @Rajeshinu !

It looks like your version of CCXT is outdated. We don't have `fee_loaded` anywhere in the current master branch version 1.19.18. I highly recommend to update your version frequently.

Those flags were used previously to designate whether those fees were loaded from the exchange or were taken from the hardcoded info in the exchange file. However, we don't use those flags anymore. In order to load those fees, you would call `fetchTradingFees` where available (see [exchange metadata](https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata) for that).

Let us know if that does not answer the question.
