### ISSUE TITLE
Coinmarketcap historical data

### ISSUE THREAD

**Issue by aki** [ccxt/ccxt#6115]
Whether to consider add coinmarketcap historical data?
api doc =  https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyListingsHistorical
api url = 
https://web-api.coinmarketcap.com/v1/cryptocurrency/quotes/historical?convert=USD,BTC&format=chart_crypto_details&id=1&interval=1d&time_end=2019-01-01&time_start=2013-04-28

**Comment by kroitor** [comment]
We don't have the plans to add that now, since we don't support CMC's commercial API. The CMC version integrated with CCXT is the old version that was free (and it still works). However, CoinMarketCap has launched a new pricing model with a paid API access, and the endpoint in question is a part of their paid plans. Let us know if that does not answer the question.
