### ISSUE TITLE
okex3 has markets that don't appear to be on the exchange

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6137]
`fetchOpenOrders` for LTC/USD say results in an error: `{"code":30032,"message":"The currency pair does not exist"}`.  A quick look at the website shows the error is correct, this market doesn't exist.  Do we know why it's there, or if it's possible to filter them out?

```
"LTC/USD": {
"limits": {
"amount": {},
"price": {
"min": 0.001
},
"cost": {}
},
"precision": {
"price": 3
},
"taker": 0.0015,
"maker": 0.001,
"id": "LTC-USD-191227",
"symbol": "LTC/USD",
"base": "LTC",
"quote": "USD",
"baseId": "LTC",
"quoteId": "USD",
"info": {
"instrument_id": "LTC-USD-191227",
"underlying_index": "LTC",
"quote_currency": "USD",
"tick_size": "0.001",
"contract_val": "10",
"listing": "2019-09-13",
"delivery": "2019-12-27",
"trade_increment": "1",
"alias": "quarter",
"underlying": "LTC-USD",
"base_currency": "LTC",
"settlement_currency": "LTC",
"is_inverse": "true",
"contract_val_currency": "USD"
},
"type": "spot",
"spot": true,
"futures": false,
"swap": false,
"active": true
}
```

**Comment by kroitor** [comment]
@npomfret do you have the okex3 file up to date? Because OKEX has changed the way the futures markets are defined, and in your case it looks like you still have the old version, which does not handle their new format. Therefore the futures markets override spot markets on your side, and that leads to a further breakdown with markets later...

Related: 
- #6116
- https://github.com/ccxt/ccxt/pull/6069

Does that help?

**Comment by kroitor** [comment]
@npomfret let me know if the above does not answer the question )
