### ISSUE TITLE
allcoin: fee schedule

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#614]
This is one of few remained exchanges that still don't have a fee schedule attached to its markets and I have a hard time figuring out what should it be.

What I read on their website is:

> Transaction Fee - Buy: 0% Sell: 0.2%

Is it really buy/sell instead of maker/taker? Or it's a bad translation?

Did you place orders on it? I remember that you've done a thorough exploration of how different exchanges calculate their fees - was this exchange on your list then?

**Comment by kroitor** [comment]
Hi!

We're not trading with allcoin ourselves, it was added due to this request: https://github.com/ccxt/ccxt/issues/317

We did very basic tests of it, but not the fill test. I can't really answer the question. But they also say they're a *"free trading platform"*, whatever it means, so this may actually be the case. I suggest, let's investigate )

**Comment by mkutny** [comment]
Ok, thanks, just asked in that thread.
