### ISSUE TITLE
Bitfinex oddities

### ISSUE THREAD

**Issue by kvz** [ccxt/ccxt#618]
Hi, 

When running fetchTickers (no arguments or anything special) I get:

```
Nov 17 15:55:41 cryptal bash[24378]: Tickfetcher: TypeError: Cannot use 'in' operator to search for 'BTCUSD' in undefined
Nov 17 15:55:41 cryptal bash[24378]:     at bitfinex.fetchTickers (/srv/cryptal/releases/20171117154557Z/node_modules/ccxt/js/bitfinex.js:202:24)
Nov 17 15:55:41 cryptal bash[24378]:     at <anonymous>
Nov 17 15:55:41 cryptal bash[24378]:     at process._tickCallback (internal/process/next_tick.js:188:7)
```

It also appears that for the ticks I do receive, quoteVolume is missing.

Any ideas?

**Comment by kroitor** [comment]
Hi, @kvz !

Thx, will fix it in 5 minutes, hold on!

**Comment by kvz** [comment]
Thanks @kroitor! 

Will this also fix

>It also appears that for the ticks I do receive, quoteVolume is missing.

?

**Comment by kroitor** [comment]
@kvz 

> It also appears that for the ticks I do receive, quoteVolume is missing.

Use `baseVolume` instead of `quoteVolume`,  for tickers, Bitfinex v1 and v2 only report 24h traded volumes in base currency. They return no values for quote currencies and volumes. So you should do rate conversions on your own. We can't workaround it for now, unfortunately, due to the limitations of their API.

**Comment by kvz** [comment]
:+1:
