### ISSUE TITLE
Blockchain transation data available?

### ISSUE THREAD

**Issue by yohplala** [ccxt/ccxt#6210]
Hello,
I have not foud any information on this.
Please, is it existing or plan to add in CCXT the ability to get blockchain transaction data to/from exchanges being managed by CCXT?
More exactly, a query about this data:
BLOCKCHAIN TRANSACTION DATA / BINANCE EXCHANGE / BTC
would indicate me through a time serie the last X BTC deposits to Binance, and last X BTC withdrawals from Binance.

Please, can this feature be supported by CCXT?
It can be somehow compare to the service provided by https://whale-alert.io/ API, but restricted to supported exchange addresses and for main crypto (BTC, ETH, LTC, XRP, BCH coming to my mind)

I thank you in advance for your feedback.
Have a good evening, bests,
Pierre

**Comment by kroitor** [comment]
> More exactly, a query about this data:
> BLOCKCHAIN TRANSACTION DATA / BINANCE EXCHANGE / BTC
> would indicate me through a time serie the last X BTC deposits to Binance, and last X BTC withdrawals from Binance.
> Please, can this feature be supported by CCXT?

This is already in CCXT: 

- https://github.com/ccxt/ccxt/wiki/Manual#funding-your-account
- https://github.com/ccxt/ccxt/wiki/Manual#transactions
- https://github.com/ccxt/ccxt/wiki/Manual#deposits
- https://github.com/ccxt/ccxt/wiki/Manual#withdrawals
- https://github.com/ccxt/ccxt/wiki/Manual#all-transactions

See also: 

- https://github.com/ccxt/ccxt/wiki/Manual#ledger

Let us know if the above does not answer the question.

**Comment by yohplala** [comment]
Hello Igor,
I am possibly a newbie on the topic.
I feel the links you direct me to are about deposit or withdrawals for a given user account.
My question however deals with all the accounts of an exchange.
For instance, (my examples may be inadequate), I can tell ETH adresses for IDEX or HOTBIT:
IDEX: https://etherscan.io/address/0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208
HOTBIT: https://etherscan.io/address/0x274f3c32c90517975e29dfc209a23f315c1e5fc7
From these, in etherscan, you have the list of all transactions to and from these exchanges.

So I would like to know if it is plan to have in CCXT a query function, attached to an exchange (and not an account) to retrieve the last X transactions in a given crypto: BTC, ETH, XRP...

I am sorry if this is already existing, I feel from what I read that the information you sent me is about withdrawal or deposit for a given account.

I thank you in advance for your feedback.
Bests,
Pierre

**Comment by kroitor** [comment]
> I feel the links you direct me to are about deposits or withdrawals for a given user account.

That's right – the exchange will never disclose a full list of user addresses, because that breaks privacy, confidentiality and security. Yes, you can fetch some of those transactions from blockchain explorers for the addresses that you know as belonging to the exchanges and especially, decentralized exchanges like IDEX, however, you can't really know much about the finances transferred with conventional crypto exchanges. Even if you do obtain some set of that information – it will be very hard to tell if your set is complete or not just from looking at the transaction data alone.

As of integrating aggregators and blockchain explorers in ccxt:

- https://github.com/ccxt/ccxt/issues/1976#issuecomment-366935558

Currently we don't have the support for traversing blockchains, although, we do support web3 (for ETH-based chains). We are going to detach the data aggregators into their own subspace inside ccxt, as blocktrail, blockchain.info and others are not exchanges in common sense, those are just data aggregators (intermediaries).

**Comment by yohplala** [comment]
Thanks a lot Igor for your reply.

> however, you can't really know much about the finances transferred with conventional crypto exchanges. Even if you do obtain some set of that information – it will be very hard to tell if your set is complete or not just from looking at the transaction data alone.

Here is an example of results https://whale-alert.io/ is boasting on the 1st page of their website:
> 21:46:21 8,700 XRP (1,953 USD) transferred from binance to unknown wallet
21:46:52 2.4 ETH (360 USD) transferred from unknown wallet to kraken
21:46:52 2.2 ETH (337 USD) transferred from bibox to okex
21:46:32 747 XRP (168 USD) transferred from hitbtc to unknown wallet
21:46:39 10.4 ETH (1,574 USD) transferred from hitbtc to unknown wallet
21:47:04 6 MKR (3,271 USD) transferred from bitfinex to bitfinex

So, would you say their information is incomplete and there might be other transactions to or from these exchanges? Or do you think they have come up with an alternative solution to setup their blockchain tracker that makes it possible to have a "complete" view?

I feel I am quite of a newbie on this topic, which is why I dare to ask if the 1st information you answered me is to be taken for real, or if after a 2nd thought, it seems to you, that yes, maybe there could be some way to have a "complete" vision of blockchain transactions to and from the exchanges.

Thanks again already for your first answers.
Have a good evening,
Bests,

**Comment by kroitor** [comment]
> So, would you say their information is incomplete and there might be other transactions to or from these exchanges?

Nope, what I'm saying is that their information is as complete as their database of exchanges and their wallet addresses. In other words, whale-alert.io will most likely have a much more complete set of info than a custom solution, because they track every transaction on production scale. However, their solution is not entirely free. If you're looking for comprehensive and free existing tools for tracking – i'm not sure if such free tools exist.

You need to understand how whale-alert.io works. There's no such thing as a _"transaction to or from an exchange"_. There are transactions _to/from addresses_ though. Thus, if you receive and process all blockchain transactions (running all the btc and eth node software), then you can match those addresses to a database like this:

```
{
    'address1': 'gemini',
    'address2': 'binance',
}
```

However, that database of addresses has to be collected first, and then properly maintained and kept up to date either by hand or automatically, because the exchanges can introduce new addresses, tokens, blockchains not supported by the tracker, and, also new exchanges appear all the time. So, logically, whale-alert.io may serve a very close approximation, but their data may also be incomplete. You may want to address the question on how they match these addresses and how complete the info is to their tech support. 

To my understanding, there's no such system that is 100% flawless.

**Comment by yohplala** [comment]
Thanks a lot Igor, I think this is crystal clear to me! Thanks again!
Have a good evening,
Bests,

**Comment by yohplala** [comment]
Hi Igor,
I have written directly to Whale Alert, and here is their answer. Inline with your own comments. Thanks again:

> Some of the addresses are provided or confirmed by exchanges that we are in contact with. Others are determined by a number of heuristics that our system uses to determine ownership. We can't guarantee that we have all addresses for any particular exchanges. Also, for many addresses we can't say with 100% certainty that they are tagged correctly. The reason for this is that most of the time detecting who the owner is of an address is complex and based on finding "clues" within the blockchain. We are working hard to have this reflected in the data our api returns: the API will return for each tagged address a probability score that reflects the certainty of ownership. Also, much better heuristics to find these clues are added in order to return better results.
