### ISSUE TITLE
'master' has been diverged

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#625]
Hi, git noticed that we diverged after 1.10.148 and I'm unable to merge.

30+ commits are missing from upstream.

Is it known and I should just reset or it's something unexpected?

**Comment by xpl** [comment]
We had to revert some commits yesterday, while trying to figure out a mysterious issue with GitHub showing a wrong username under commits made by our Travis CI deploy script.

It turned out it was not related to our recent changes at all, and was a GitHub issue actually (someone managed to link travis@travis-ci.org email with their GitHub account...). Since then, it has been resolved successfully.

**Comment by mkutny** [comment]
> We had to revert some commits yesterday, while trying to figure out a mysterious issue with GitHub showing a wrong username under commits made by our Travis CI deploy script.

I noticed that too. Actually, I thought that you've got a new team member )

Ok, clear now, will reset.
