### ISSUE TITLE
[suggestion] add fetchMyFees method

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6270]
I'm implementing this for a number of exchanges in my project.  The current signature is 

    async fetchMyFees(symbol, params = {})

@kroitor Would you consider adding this to the ccxt API?

**Comment by kroitor** [comment]
> @kroitor Would you consider adding this to the ccxt API?

It is somewhat more complicated, i'm afraid...

We already have `fetchFundingFee`, `fetchFundingFees`, `fetchTradingFee`, `fetchTradingFees`, and also `fetchTradingLimits`, `fetchFundingLi...` in some cases... And the fetchFees should kinda aggregate all that. 

The design problem becomes evident when you factor in the differences between the exchanges, some of them have standalone endpoints for withdrawal fees and trading fees (and limits), others serve this information along with the markets and currencies, in some cases that info is public, in other cases it's personalized and depends on various rebate and 30d-volume programs... And we also have to include the loadMarkets/loadCurrencies/fetchMarkets/fetchCurrencies logic into this...

Naming issues are also very important in that regard, and, i'm not sure if fetchMyFees is a good name, because it does not specify which particular fees it will fetch. If it is going to fetch all possible personal fees, it will be quite hard to implement in a unified way for the above reasons. Let me know your thoughts...

**Comment by kroitor** [comment]
Here, if you want to break your head completely )) all about fees:

- https://github.com/ccxt/ccxt/issues/40#issuecomment-510695854
- https://github.com/ccxt/ccxt/pull/1669
- https://github.com/ccxt/ccxt/pull/1793
- https://github.com/ccxt/ccxt/pull/1814

**Comment by npomfret** [comment]
Sorry, yes - I actually wanted `fetchMyTradingFees`!  This is what I've been making

**Comment by kroitor** [comment]
@npomfret that basically corresponds to fetchTradingFees, because in most cases that's a private request anyway...

**Comment by kroitor** [comment]
@npomfret or do you want to differentiate between tier-based personalized fees and common fees?

**Comment by npomfret** [comment]
> that basically corresponds to fetchTradingFees, because in most cases that's a private request anyway...

Ah! I did not know that.  I assumed it would be `fetchMy...` to distinguish it from default fees.

**Comment by npomfret** [comment]
Yes, I wanted an API call that does not return common fees.  It only returns _my_ fees (with my discounts)

**Comment by kroitor** [comment]
@npomfret then we might want to split fetchTradingFees / fetchMyTradingFees (both private calls, mostly) for the exchanges that differentiate them, then add `fetchMyTradingFees` = emulated to the base class and make a base method like

```
async function fetchMyTradingFees (...) {
    if (this.has['fetchTradingFees']) {
        return this.fetchTradingFees()
    }
}
```

> Sorry, I wasn't being clear at all.

No worries at all ) Don't hesitate if anything.

**Comment by npomfret** [comment]
Right.  So the default would be `fetchMyTradingFees = emulated` if there is no specific method `fetchMyTradingFees ` but there is a `fetchTradingFees` method.

**Comment by npomfret** [comment]
Ok, maybe I'll do a coinbasepro implementation PR and you can comment on that.

**Comment by kroitor** [comment]
@npomfret if it will be easier for you – we can skip the emulation bit for now and just add the derived fetchMyTradingFees methods where available

**Comment by npomfret** [comment]
ok, and the return value?  Something like this?

```
return {
    maker: 0.001,
    taker: 0.002,
    info: stuff
}
```

**Comment by kroitor** [comment]
@npomfret on a second thought, maybe we should just assume that `fetchTradingFees` always returns your private fees, and public fees would be either served with the markets or another public endpoint loaded in `fetchMarkets` or scraped from a web page... What do you think? We don't want to overcomplicate the interface, since it will introduce some ambiguity on which particular method to call – fetchTradingFees or fetchMyTradingFees... To be honest, I need to review the existing implementations again to answer firmly, if you could hold on with it for a day, i will get back to you on this.

On the return values, it depends on the arguments, this is currently not very well unified:

```JavaScript
{
    maker: 0.001,
    taker: 0.002,
    info: stuff
}
```

for fetch...Fee and fetch...Fees, however, for a multiple (Fees) we should probably refactor it like so:

```JavaScript
{
    'ETH/BTC': {
        maker: 0.001,
        taker: 0.002,
        info: stuff
    }, ...
}
```

We could probably draw some not-very-straight parallels here:

```
cancelOrder (id) → fetchTradingFee (symbol)
cancelOrders (ids = undefined) → fetchTradingFees (symbols = undefined)
cancelAllOrders (symbol = undefined) → fetchAllTradingFees (symbols = undefined) ???
```

What I'm trying to say is that we have to think of a robust and flexible design that will handle all variations of apis...

**Comment by npomfret** [comment]
Happy to hold off.  It needs to be clear of course that there is a difference between your fees and the default fees.  That's why I like `fetchMy...` style method names.
