### ISSUE TITLE
Storing OHLCV data retrieved with CCXT?

### ISSUE THREAD

**Issue by yohplala** [ccxt/ccxt#6277]
Hello ccxt team,
I have a look in already existing OHLCV-related questions in CCXT Github, and I have not been able to identify a similar question.
I would like to retrieve OHLCV data from a given exchange using CCXT.
Now let say I want to keep data, and append it with what has been retrieved using CCXT.
Does CCXT allow "that"?

The "that" most notably refere to:
- does CCXT provide and "append_OHLCV" function? (that would trim already recorded data and only append newest data)
- does CCXT provide any compressed format for storing? (in case data gets huge)
- does CCXT provide any data structure to keep track of some metadata related to the OHLCV, such as exchange from where it has been retrieved, timeframe of OHLCV data (other?) so that when appending, some basic checks can be run and that data from two different exchanges or with different timeframe are not mixed-up?

- in addition, I woudl be also interested in some "extra" features, such as:
 - check holes: check if some data is missing for some timestamp
 - transform to larger timeframe (for instance 5m to 15m - I know a script example has already been provided in a previous issue for that)
 - shift timeframe: shift UTC time, for instance UTC+1 to UTC+2 (ony applicable if the shift is a multiple of the timeframe)

I anticipate that this is not provided by CCXT, nor this being in the scope of CCXT.
In this latter case, please, would you know any existing python library to do that, which would be a kind of extra layer over panda, and providing these extra functions focused on OHLCV data?

I have spotted the pystore library devised for storing time serie data, but which doesn't provide specific functions for handling OHLCV data (metadata to keep track of the exchange, timeframe_shift, and so on...)
https://github.com/ranaroussi/pystore

I feel this falls is in-between what can provide CCXT and pystore.

I thank you for any help you can bring,
Have a good day,
Bests,
Pierre

**Comment by kroitor** [comment]
@yohplala hi!

> I would like to retrieve OHLCV data from a given exchange using CCXT.

CCXT allows that )

> Now let say I want to keep data, and append it with what has been retrieved using CCXT. Does CCXT allow "that"?

In general, nope, because we think that storing the data is beyond the scope of this lib (at least, at this time). Because the variety of storage mechanisms is so vast, we don't give a preference to any specific storage type. Therefore CCXT returns native language types, and serializing them for storage is the responsibility of the user. However, CCXT has some helper methods that may used together with any type of storage. So, CCXT is storage-agnostic, and your anticipation is mostly correct in that regard.

> does CCXT provide and "append_OHLCV" function? (that would trim already recorded data and only append newest data)

No, because _how you append and trim_ depends on _how you store_.

> does CCXT provide any compressed format for storing? (in case data gets huge)

Nope, because compression is addressed by database engines and/or compression engines.

> does CCXT provide any data structure to keep track of some metadata related to the OHLCV, such as exchange from where it has been retrieved, timeframe of OHLCV data (other?) so that when appending, some basic checks can be run and that data from two different exchanges or with different timeframe are not mixed-up?

The exchange and all its properties as such: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties. You can "remember" that along with the actual OHLCV data in your database. It's usually a no-issue to have a +1 table or a +1 document type in your schema, regardless of which particular database you use.

> check holes: check if some data is missing for some timestamp

No, the philosophy of CCXT is to serve you the data from the exchanges as close to its original as possible, "as is", it will not judge if this or that data is complete, but it will return everything it gets. So, the patching of the holes is usually done with aggregation methods from pandas or other similar tools (it's a one-liner, basically, if you know pandas well).

> transform to larger timeframe (for instance 5m to 15m - I know a script example has already been provided in a previous issue for that)

Apart from the mentioned script we don't have the plans to add this functionality to CCXT in the nearest future, but we may add this in 2020.

> shift timeframe: shift UTC time, for instance UTC+1 to UTC+2 (ony applicable if the shift is a multiple of the timeframe)

```Python
# wrap this in a function if needed
timeframe = '5m'
symbol = 'ETH/BTC'
ohlcv = exchange.fetch_ohlcv(symbol, timeframe)
 period = exchange.parse_timeframe(timeframe) * 1000
shift = -5  * period # -5 periods for example
shifted =[([o[0] + shift] + o[1:]) for o in ohlcv]
```

> I anticipate that this is not provided by CCXT, nor this being in the scope of CCXT.
In this latter case, please, would you know any existing python library to do that, which would be a kind of extra layer over panda, and providing these extra functions focused on OHLCV data?

Many of the features from your request are actually provided by pandas itself, however, you really need to know it well to use it efficiently.

As far as I know there is no such solution that makes everything easy out of the box – in many cases you have to add the gluing code in between the components to make them work together.

**Comment by fonzmeister** [comment]
What do you want to achieve? Do you want to get historical data example from a year back until now? This is not hard to achieve, I have done this myself multiple times using this library for backtesting purposes. 


Or do you want to fetch the current candles and append future candles to you data every X minutes?
THis is also not that hard, but might require a different approach. You probably should store the data you fetch in a database or a CSV file
