### ISSUE TITLE
Integration requirements

### ISSUE THREAD

**Issue by alesito85** [ccxt/ccxt#6287]
I would like to know if all methods that are listed in https://github.com/ccxt/ccxt/wiki/Requirements are mandatory for implementation. The reason behind the question is that I don't see all methods integrated in all exchanges.

For example Bitfinex has integrated fetchFundingFees but not fetchFundingLimits. I also couldn't find an explanation of what each method should contain. This is not a problem if I can find an example and test it but I couldn't even find an example of fetchFundingLimits.

**Comment by kroitor** [comment]
> I would like to know if all methods that are listed in https://github.com/ccxt/ccxt/wiki/Requirements are mandatory for implementation.

It depends on the structure of the underlying exchange API. Not all of those methods are mandatory, but most of the info returned from those methods – is mandatory. In many cases, the exchanges return trading limits (min/max order size/price) along with the markets from fetchMarkets, so you only need a standalone `fetchTradingLimits` method if the underlying exchange has separate endpoints for market pairs and corresponding limits. For the above reason very few exchanges actually have fetchTradingLimits. 

> I also couldn't find an explanation of what each method should contain.

Due to the rare nature of `fetchTradingLimits` it's not documented yet, but in general it should return the `limits` subdictionary from `fetchMarkets()`, indexed by symbol, like so:

```JavaScript
{ 
    'ETH/BTC': {
        'info': limits,
        'limits': {
            'amount': { 'min': 1.2345, 'max': undefined },
            'price': { 'min': 5.4321, 'max': undefined },
            'cost': { 'min': 5.4321, 'max': undefined },
        },
    },
    'BTC/USDT': {
        ...
    },
    ...
}
```

You can find examples in the code:

- https://github.com/ccxt/ccxt/search?q=fetchTradingLimits&unscoped_q=fetchTradingLimits
- https://github.com/ccxt/ccxt/blob/master/js/huobipro.js#L177
- https://github.com/ccxt/ccxt/blob/master/js/huobipro.js#L233
- https://github.com/ccxt/ccxt/blob/master/js/bcex.js#L228
- ...

> For example Bitfinex has integrated fetchFundingFees but not fetchFundingLimits.

The Bitfinex exchange serves funding fees from a standalone endpoint: https://docs.bitfinex.com/v1/reference#rest-auth-fees, while funding limits are served from `fetchMarkets()`: https://docs.bitfinex.com/v1/reference#rest-public-symbol-details

Let us know if the above does not answer the question.

**Comment by alesito85** [comment]
Thanks for the explanation. It does help. However i was asking for funding, not trading limits.

**Comment by kroitor** [comment]
> However i was asking for funding, not trading limits.

Yep, pardon, basically, for funding limits it's the same story as with trading limits, and the general logical structure is as follows:

- trading: symbols, markets, fetchMarkets, fetchTradingLimits, fetchTradingFees
- funding: codes, currencies, fetchCurrencies, fetchFundingLimits, fetchFundingFees

So, in most cases withdrawal fees and limits are served from the `fetchCurrencies` endpoint. Also, jfyi, no exchange currently has a standalone implemented `fetchFundingLimits` at all (most of them will either miss that info entirely or will serve it from a currencies-endpoint), so that particular method is not in the examples yet.
