### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by jdimstrnate** [ccxt/ccxt#629]
Any query I make to any exchange does not return in JSON., return is wrapped around screen instead.
The manual describes JSON being returned untouched.  Shouldnt the information be presented in a cleaner way as it is shown in the manual?

Returned JSON Objects
All public and private API methods return raw decoded JSON objects in response from the exchanges, as is, **untouched**. The unified API returns JSON-decoded objects in a common format and structured uniformly across all exchanges.

==============================================================
Ex: 

>>> import asyncio
>>> import ccxt.async as ccxt
>>> async def print_poloniex_ethbtc_ticker():
...     poloniex = ccxt.poloniex()
...     print(await poloniex.fetch_ticker('ETH/BTC'))
... 
>>> asyncio.get_event_loop().run_until_complete(print_poloniex_ethbtc_ticker())
{'vwap': None, 'timestamp': 1511076542136, 'last': 0.04773992, 'percentage': None, 'first': None, 'info': {'percentChange': '0.10483499', 'baseVolume': '5166.58019286', 'high24hr': '0.04859050', 'highestBid': '0.04767038', 'isFrozen': '0', 'id': 148, 'low24hr': '0.04249711', 'lowestAsk': '0.04773992', 'quoteVolume': '115503.38042345', 'last': '0.04773992'}, 'close': None, 'ask': 0.04773992, 'quoteVolume': 5166.58019286, 'baseVolume': 115503.38042345, 'change': 0.10483499, 'low': 0.04249711, 'average': None, 'open': None, 'symbol': 'ETH/BTC', 'bid': 0.04767038, 'high': 0.0485905, 'datetime': '2017-11-19T07:29:02.136Z'}
>>> 
>>> 
==============================================================

**Comment by kroitor** [comment]
> Any query I make to any exchange does not return in JSON., return is wrapped around screen instead.

That's how Python prints JSON in the terminal. 

> The manual describes JSON being returned untouched. 

Exactly, public and private APIs return JSON untouched (the `info` substructure), whereas unified APIs also parse it and add additional fields. CCXT does not do any screen "wrapping" your terminal and Python does. The examples in the manual are preformatted by hand for readability, whereas in code those structures are returned as is.

> Shouldnt the information be presented in a cleaner way as it is shown in the manual?

CCXT does not present that info to you. You present that info to yourself from CCXT. So it's up to you how you want it formatted in your environment/terminal. If you see it formatted not the way you want it when you output it, and you think it should be output differently, it means you're misunderstanding how the output formatting works in programming languages and in your terminal. 

CCXT does not reformat it. Use pprint if you want "each key on a separate line".

```Python
import asyncio
import ccxt.async as ccxt
from pprint import pprint
poloniex = ccxt.poloniex()
pprint(asyncio.get_event_loop().run_until_complete(poloniex.fetch_ticker('ETH/BTC')))
```

In fact, this has absolutely nothing to do with CCXT, compare:

1. 
   
        ```Python
        print({'ask': 0.04549986,
            'average': None,
            'baseVolume': 167015.6085475,
            'bid': 0.04548301,
            'change': 0.04679197,
            'close': None,
            'datetime': '2017-11-19T17:38:39.730Z',
            'first': None,
            'high': 0.0485905,
            'info': {'baseVolume': '7658.05449808',
                    'high24hr': '0.04859050',
                    'highestBid': '0.04548301',
                    'id': 148,
                    'isFrozen': '0',
                    'last': '0.04549986',
                    'low24hr': '0.04300092',
                    'lowestAsk': '0.04549986',
                    'percentChange': '0.04679197',
                    'quoteVolume': '167015.60854750'},
            'last': 0.04549986,
            'low': 0.04300092,
            'open': None,
            'percentage': None,
            'quoteVolume': 7658.05449808,
            'symbol': 'ETH/BTC',
            'timestamp': 1511113119073,
            'vwap': None})
    ```

↑ this **does not involve CCXT** and it "reformats" your output. For it to fit your screen, because your terminal can't scroll to the right, man.

2. 

    ```Python
        from pprint import pprint
        print({'ask': 0.04549986,
            'average': None,
            'baseVolume': 167015.6085475,
            'bid': 0.04548301,
            'change': 0.04679197,
            'close': None,
            'datetime': '2017-11-19T17:38:39.730Z',
            'first': None,
            'high': 0.0485905,
            'info': {'baseVolume': '7658.05449808',
                    'high24hr': '0.04859050',
                    'highestBid': '0.04548301',
                    'id': 148,
                    'isFrozen': '0',
                    'last': '0.04549986',
                    'low24hr': '0.04300092',
                    'lowestAsk': '0.04549986',
                    'percentChange': '0.04679197',
                    'quoteVolume': '167015.60854750'},
            'last': 0.04549986,
            'low': 0.04300092,
            'open': None,
            'percentage': None,
            'quoteVolume': 7658.05449808,
            'symbol': 'ETH/BTC',
            'timestamp': 1511113119073,
            'vwap': None})
    ```

↑ This example uses `pprint` to pretty-print your output, **no CCXT involved, again**.
