### ISSUE TITLE
Coinbasepro fetchTrades not correctly passing 'since' parameter?

### ISSUE THREAD

**Issue by nlwhd** [ccxt/ccxt#6303]
- OS: PureOS
- Programming Language version: Python2.7
- CCXT version: 1.20.81
- Exchange: Coinbasepro
- Method: fetch_trades

It seems that the 'since' parameter is not being passed to the coinbasepro exchange.  When using any since value, the most recent trades are returned.

Is this the same behavior as the recently closed issue with the Kraken fetch_trades since parameter?  or is this a CCXT version issue on my part?

Kraken fetch_trades is working as expected in my script.

```
import ccxt

coinbasepro = ccxt.coinbasepro()
t_start=1546300800000

data = coinbasepro.fetch_trades('BTC/USD', since=t_start, limit=100)
```

**Comment by kroitor** [comment]
@nlwhd coinbasepro does not support that argument: https://docs.pro.coinbase.com/#get-trades. We'd love to add the support for `since`, however, the exchange endpoint does not accept that param, so the only time we can filter by `since` – is on the client side. This is common to many exchanges – they will only return just the most recent set of public trades (like, 100, 500 or 1000 max). Hope that answers your question. Let us know if not.

**Comment by ManuelSchneid3r** [comment]
Why dont you just support fetch_trades_by_id and fetch_trades_by_timestamp? which we can check via the `has` member?
