### ISSUE TITLE
get the current opened position Order side ( short or long ). binance py

### ISSUE THREAD

**Issue by medozero** [ccxt/ccxt#6314]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: WINDOWS 10
- Programming Language version: py 3.7
- CCXT version:1.20
- Exchange:binance
- Method:

i tried to compare the current price with the previous price and compare that to my PNL and previous PNL for the ticks . but that was not accurate . may be i am missing something in the comparing function . but in the main time is there any way to get the current Order side for the opened position ( long or short ) using ccxt . i check the getBalance() and that was not there 

Thanks

**Comment by kroitor** [comment]
> but in the main time is there any way to get the current Order side for the opened position ( long or short ) using ccxt

In general, no, because this is not how positional trading works in general. A single position may be a result of a series of multiple buy and sell orders, so your `position = 0 + buy - sell` in an abstract form. Thus, there's no single order side that can be associated with an entire position. Hope that answers your question. Let us know if now.

**Comment by medozero** [comment]
Ok thanks i got it . but most of the time i am opening only one position . but you may close this as i  will think of something .
