### ISSUE TITLE
Getting fills on Poloniex

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#6319]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.21.15
- Exchange: Poloniex
- Method: returnOrderStatus

Hi. I'm trying to get fills (or even just closed orders) from orders that were created *outside* of CCXT.  I use fetchOpenOrders() to get the orders and then later I want to use fetchOrder, but get that 'not open' error. I've googled around to find a solution but I can't find one.

I've tried their native returnOrderStatus but it doesn't exist, as well as privatePostReturnOrderStatus, and fetchOrderTrades.

Suggestions?

**Comment by kroitor** [comment]
Hey)

> I'm trying to get fills (or even just closed orders) from orders that were created outside of CCXT. I use fetchOpenOrders() to get the orders and then later I want to use fetchOrder, but get that 'not open' error. I've googled around to find a solution but I can't find one.

See the explanation for that here:

- https://github.com/ccxt/ccxt/issues/6227#issuecomment-562545825

> I've tried their native returnOrderStatus but it doesn't exist, as well as privatePostReturnOrderStatus, and fetchOrderTrades.

You need `fetchMyTrades`, as explained in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#personal-trades-1

There is no way to restore the "old order history" with poloniex, since that information is archived by the exchange API immediately after generating the fills for those orders (upon filling them up and closing them). So, in order to restore your history, you want to `fetchMyTrades` and check the `order` id field inside those trades.

Hope that answers the question. Let us know if not.

**Comment by npomfret** [comment]
For Poloniex, it might be a good idea to keep your own record of any orders placed.  Actually, you might find that's a good idea in general.

**Comment by kroitor** [comment]
Totally agree with @npomfret on the above comment – storing your history is always good.
