### ISSUE TITLE
How to know if crypto can be deposited / withdraw-ed from exchange?

### ISSUE THREAD

**Issue by mmilojevic** [ccxt/ccxt#6323]
I was looking at `fetch_markets` method but the information that crypto can be deposited or withdrawed is not contained there. How can we know  if crypto can be deposited / withdraw-ed from exchange?

**Comment by kroitor** [comment]
You need `fetchCurrencies, plz see the answer here: https://github.com/ccxt/ccxt/issues/1087

**Comment by mmilojevic** [comment]
Thank you very much! Was searching for this question but didn't caught it :)
Just one more question,  active will be false if only deposit can't be made or only withdraw can't be made or both can't be made? And it is true when deposit and withdraw can be made?

**Comment by kroitor** [comment]
> Just one more question, active will be false if only deposit can't be made or only withdraw can't be made or both can't be made? And it is true when deposit and withdraw can be made?

Yes, that is correct, if the currency is not withdrawable and/or cannot be deposited – the `active` flag is set to false. However, you may want to pay attention to the data you get from the exchange in question, since this really depends on the underlying exchange API and not all exchanges provide that info from their APIs. Hope that helps.

**Comment by mmilojevic** [comment]
Got it! Kroitor you are king!
