### ISSUE TITLE
Release tags cleaned?

### ISSUE THREAD

**Issue by devsi** [ccxt/ccxt#6334]
Hi @kroitor,

Just curious, did you purge a bunch of version tags from the repo recently? We specifically locked in to a version and the last build took down our staging app as it can no longer be found!

No worries, we can just update it, but wondering why you decided to purge?

Thanks :)

**Comment by kroitor** [comment]
> No worries, we can just update it, but wondering why you decided to purge?

Yep, we have to purge them occasionally, see: https://github.com/ccxt/ccxt/blob/master/build/cleanup-old-tags.js – otherwise package managers like Packagist start to break down when serving our page with thousands of tags and releases, unfortunately. Those version numbers are still kept in the corresponding commit messages, but the tags themselves have to be purged from time to time. We keep 3 most recent minor versions with detailed tags, all older versions will be purged at some point, keeping each first minor tag (1.9.1, 1.10.1, 1.11.1, 1.12.1, ... , 18.1, . 1.19.1, ...). Hope that answers the question.
