### ISSUE TITLE
https Keep alive with cors proxy in browser version

### ISSUE THREAD

**Issue by joyser** [ccxt/ccxt#6339]
Hi, I'm using js ccxt with React and currently using the proxy parameter to get around the CORs issue:

`this.ccxt = new ccxt['okex3'](
            {proxy:'http://192.168.0.248:8080/',
            apiKey: this.apiKey,
            secret: this.secret,
            password: this.passPhrase,
          }
        );`

I want to implement a keepAlive so  I don't need to do a SSL/TPL handshake for every request made to the exchange, which is causing a larger than desired round trip time.

I've tried to implement the solution posted here: [#4628](https://github.com/ccxt/ccxt/issues/4628), by adding a httpAgent, but it doesn't seem to fix the issue. I'm thinking maybe it's not possible to use keepAlive in conjunction with CORs proxy? Or using the proxy parameter overrides the agent option all together?
Or possibly this is something I need to implement within the cors proxy I'm using from the manual?

Thanks.

**Comment by kroitor** [comment]
@joyser hi!

> I want to implement a keepAlive so I don't need to do a SSL/TPL handshake for every request made to the exchange, which is causing a larger than desired round trip time.

We already have keepAlive enabled with Node, as of version 1.21.10, see these related issues:

- https://github.com/ccxt/ccxt/issues/5815
- https://github.com/ccxt/ccxt/pull/6302

> I'm thinking maybe it's not possible to use keepAlive in conjunction with CORs proxy? 

I'm practically sure it is caused by the CORS proxy, since most of them can't keep alive two connections: a _you-to-cors_ connection and a _cors-to-your-destination_ connection.

> Or using the proxy parameter overrides the agent option all together?

Nope.

> Or possibly this is something I need to implement within the cors proxy I'm using from the manual?

Yep. However, it's a bit beyond the scope of this lib. See keepAlive details here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Let me know if that does not answer the question.

**Comment by joyser** [comment]
Makes sense! I think I'll have to move ccxt to a node server and set up a custom sort of proxy which will forward the requests from React -> node -> ccxt -> exchange.  Thanks!
