### ISSUE TITLE
Binance Margin Trading not able to Cancel Order

### ISSUE THREAD

**Issue by baeriswyld** [ccxt/ccxt#6345]
- OS: Ubuntu 19.04
- Programming Language version: Python
- CCXT version:  1.20.48
- Exchange: Binance
- Method: sapiPostMarginOrder

Hi! 
Huge fan here! We've been using CCXT for a while now. Would be great to have a chat at some point! 

Quick question and probably an easy solution to it.

I am unable to cancel margin orders using your implicit method.

I do the following to cancel a trade:

`params = {"symbol": 'ETHBTC',
                      "orderId": int(10)}`
`ccxt.sapiPostMarginOrder( params)`

Order 10 exists. The return message is:
`binance {"code":-1102,"msg":"Mandatory parameter 'quantity|side|type' was not sent, was empty/null, or malformed."}`

What am I missing?

Best,
Daniel

**Comment by kroitor** [comment]
Hi! )

> What am I missing?

The `sapiPostMarginOrder` is for placing orders (not for canceling them). If you want to cancel it, you need a different endpoint (a different implicit method) called `sapiDeleteMarginOrder`.

Let me know if that does not answer the question.

**Comment by baeriswyld** [comment]
Thank you Sir ! 

In the binance api margin docs 
https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md
cancelling an order is supposed to be at this address:
**Margin account cancel order (TRADE)
Delete /sapi/v1/margin/order**

I thought that your implicit method follows the folder string.

**Comment by kroitor** [comment]
@baeriswyld the rules for implicit method names are here:

- https://github.com/ccxt/ccxt/wiki/Manual#api-method-naming-conventions

Let us know if you have further issues or questions.

**Comment by Princeton007** [comment]
Hello @kroitor 
I'm trying to post a new margin order on binance: 

CCXT version: 1.24.28

```Python
order = exchange.sapiPostMarginOrder(symbol, side, type, amount, limit_price, stop_price, timeInForce)
``` 
And get the following error: 
TypeError: inner() takes from 1 to 2 positional arguments but 8 were given

Any idea what goes wrong?

**Comment by kroitor** [comment]
> Any idea what goes wrong?

Yep, it's explained in the error message that you've posted ) You're confusing the unified API methods with the implicit API methods. 

You're trying to call an implicit method as if it is a unified method and the difference is explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints
  - https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
    - https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
  - https://github.com/ccxt/ccxt/wiki/Manual#unified-api

↑ We always recommend to read the entire Manual from top to bottom at least once – it will save you a lot of time, really.

1. There's no such unified method as `sapiPostMarginOrder` – it's an implicit API method, a mapping to one of the exchange's endpoints.
2. As shown in the Manual it only accepts one argument – `params`, which is a dictionary of exchange-specific params for this request. The params for it are not unified (exchange-specific), and you should look them in Binance API docs for that call.
3. The correct code to call that implicit method would look like:

```Python
order = exchange.sapiPostMarginOrder({
    # see which params are required for the order
    # the auth params will be handled for you (not required here)
    # specify just the order params for
    # https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md#margin-account-new-order-trade
})
```

P.S. We are going to unify margin trading soon, this is one of our priorities for the nearest future, so that you could also call it in a way that would be unified with the other exchanges. So it will become easier from the user perspective. But at this point you have to strictly follow the documentation.

**Comment by Princeton007** [comment]
@kroitor Thanks, and actually I was in the meantime coming to the same conclusion (and now that I should and will read the documentation twice!) 
YES! It works! (after a few iterations, though) :-) 
And I'm looking forward to the unified method 
Stay safe!
