### ISSUE TITLE
Question about binance.fapiPrivateGetPositionRisk

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#6355]
Hi, 

If I use this: 
`await binance.fapiPrivateGetPositionRisk ( {  symbol : 'BTCUSDT'  } )
`I get info from all positions, not only BTCUSDT like I am asking for, after this I need to find the BTCUSDT position with a for loop . 

Can you make it to show the BTCUSDT position only , because I am writing the `symbol : 'BTCUSDT' `in the brackets..

Regards

**Comment by kroitor** [comment]
Hi!

> Can you make it to show the BTCUSDT position only

Unfortunately, it's a bit more complicated. In general, we have two families of methods:
- the Unified API
- the exchange-specific implicit API

Both parts and the difference between them – are described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints

The main difference between the two is: with the Unified API you can filter by unified symbols in a cross-compatible way, because the purpose of the Unified API is to make all exchanges' APIs look the same (unify them). With the implicit API you can't use unified args, and you have to account for exchange specifics. At this point, the Unified API does unify balances, orderbooks, tickers, ohlcv candles, trades, orders, deposits, withdrawals, ledger entries and much more. However, it does not unify the positional trading (it's a work in progress, and we are going to unify that aspect as well). Thus you have to use implicit APIs for positional trading – and if that is the case – we don't intercept
the params sent to the exchange or return types coming back from the exchange – what you send is what you get. 

If you look carefully at the arguments of `fapiPrivateGetPositionRisk` in Binance API docs:

- https://binance-docs.github.io/apidocs/futures/en/#position-information-user_data

You will immediately notice, that it does not support a `symbol` param and will always return the entire set of your positions, regardless of the `symbol` you send.

So, instead of this: 

- `await binance.fapiPrivateGetPositionRisk ( { symbol : 'BTCUSDT' } )` 

you should probably do this:

- `await binance.fapiPrivateGetPositionRisk ()`

... and, yes, if you're using the implicit API – then you will have to filter the result on your own (it's not processed by CCXT – you get it directly from the exchange itself).

Hope that answers the question.

**Comment by kroitor** [comment]
P.S. more about it here: https://github.com/ccxt/ccxt/issues/4834

**Comment by Gennttii** [comment]
Hi , 
Yea I know its implicit, but because it asks a symbol as parameter, maybe u can only add the loop in the function in ccxt to show  the data for the given symbol only, just a suggestion..

The symbol parameter has no use in this case for now..!

**Comment by kroitor** [comment]
> maybe u can only add the loop in the function in ccxt to show the data for the given symbol only
> The symbol parameter has no use in this case for now..!

Exactly, and this is what I'm trying to explain – CCXT does not intercept implicit methods (at all), so it does not know about the arguments and the return types of each particular explicit method – that is done by Unified methods, but positional trading is not unified yet, therefore you have to use implicit methods (and some custom code) until we unify this aspect. Unfortunately, we can't intercept the symbol for one specific implicit method for Binance in particular, leaving 100500 other implicit methods of all other exchanges as is (this is against the design of the unification). Therefore, if we unify that method and name it like `fetchPositions (symbol, ...` – we do that for all exchanges, not just one. But, again, this is a work in progress and we don't have positional trading unified yet.

**Comment by kroitor** [comment]
@Gennttii 

> Yea I know its implicit, but because it asks a symbol as parameter

Just to clarify, if you look into binance's docs and in the code of ccxt – it does not ask for a symbol parameter, the list of parameters accepted by that method is here:

- https://binance-docs.github.io/apidocs/futures/en/#position-information-user_data
