### ISSUE TITLE
About Binance futures leverage type ( cross , isolated )

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#6357]
Hi,

Lately binance has changed the Futures leverage, it was only leverage , now its added type of `cross` and `isolated`

I am changing the leverage with this :
`await binance.fapiPrivatePostLeverage({symbol: 'BTCUSDT', leverage: 100}) `,  but now how can I change the leverage type to cross or isolated? 

Regards

**Comment by kroitor** [comment]
Hi!

You would do that just with any other [implicit method](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods):

- https://binance-docs.github.io/apidocs/futures/en/#change-margin-type-trade

↑ From here you can carry that you need:

```JavaScript
await exchange.fapiPrivatePostMarginType ({
    symbol: 'BTCUSDT',
    marginType: 'ISOLATED', // or 'CROSSED'
})
```

Let us know if that does not answer the question.

**Comment by Gennttii** [comment]
Hi

I am getting this:  `exchange.fapiPrivatePostMarginType is not a function` !

**Comment by kroitor** [comment]
@Gennttii yep, because Binance has introduced these changes just recently, so, this is "fresh", and you have to update your CCXT version (we've added it when Binance added it, a week ago). So, if you don't have this function – that means that your CCXT version is older than a few days. That's one of the reasons why we recommend to update the lib frequently, since the exchanges evolve and add new functionality very quickly, every day. Let us know if you have issues with the most recent version of CCXT.

**Comment by Gennttii** [comment]
Still getting errors after update, I am using Futures testnet, will try it in real Futures later.. Thanks

**Comment by kroitor** [comment]
> Still getting errors after update, I am using Futures testnet, will try it in real Futures later.. Thanks

Yep, also, if you could post the errors and your initialization code without your keys (showing how you switch to the testnet) – that would help resolve the issue quicker.
