### ISSUE TITLE
while loops not being properly transpiled

### ISSUE THREAD

**Issue by abhishekr700** [ccxt/ccxt#6372]
Environment: Docker supplied with repo

```js
while (true) {
            const request = {
                'symbol': tradingSymbol,
                'page': page,
                'since': since,
            };
            // console.log(request);
            const resp = await this.private1PostListExecutedOrders (this.extend (request, params));
            // console.log("resp: ",resp.data);
            if (resp.data.length === 0) {
                // console.log ("All trades fetched");
                break;
            }
            page = page + 1;
            allTrades = allTrades.concat (resp.data);
            // console.log("int alltrades:", allTra÷des);
        }
```

Transpiled python
```python
while(true) {
            request = {
                'symbol': tradingSymbol,
                'page': page,
                'since': since,
            }
            # console.log(request)
            resp = self.private1PostListExecutedOrders(self.extend(request, params))
            # console.log("resp: ",resp.data)
            if len(resp.data) == 0:
                # print("All trades fetched")
                break
            page = page + 1
            allTrades = allTrades.concat(resp.data)
            # console.log("int alltrades:", allTra÷des)
```

You can see curly braces are being transferred as it is.

**Comment by kroitor** [comment]
@abhishekr700 while (true) is not allowed in derived exchange classes, we cannot emulate aggregated pages by issuing multiple sequential requests since that breaks rate-limit management if the user is trying to race those requests in parallel. Therefore we don't transpile the `while (true)` clause, only limited for loops are allowed. Let us know if that does not answer the question.

**Comment by abhishekr700** [comment]
@kroitor I'm unable to get a while loop run, without a while(true) also. Are while loops completely blocked ?

**Comment by kroitor** [comment]
@abhishekr700 yes, in general we don't use them in derived classes and only use c-style `for` loops over integers. Another important rule across unified derived methods is that we cannot really do sequential requests without breaking rate-limiting. So, it is always assumed that the user might issue one or many asynchronous calls. Therefore the general rule is one HTTP request per unified call.

**Comment by abhishekr700** [comment]
@kroitor  I'm trying to implement fetchMyTrades and here the exchange gives results in a paginated way. Thus, I have to make multiple requests changing page numbers. What should be done in this case ?

**Comment by kroitor** [comment]
@abhishekr700 in these cases we add the proper support for `since` and `limit` arguments and the page-based pagination is supported by default via params, as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#pagenumber-based-cursor-pagination

The user should specify the page he wants. If the user did not specify the page number via params, then:

- if the exchange requires it – return the first page received from the exchange
- if the exchange does not require it – return the default page received from the exchange

The body of fetchMyTrades would look close to:

1. If the exchange does not require `page` (this must be verified by testing – sending no `page` at all first):

```JavaScript
    // ...
    const request = {
        'symbol': tradingSymbol,
        'since': since,
        // we don't send `page` if it is not required
    };
    // if the user specifies `page` in params – it will be added ↓ to the request here ↓
    const response = await this.private1PostListExecutedOrders (this.extend (request, params));
    const data = this.safeValue (response, 'data', []);
    return this.parseTrades (data, ...
```

2. If the exchange requires `page`:

```JavaScript
    const request = {
        'symbol': tradingSymbol,
        'page': 1, // whatever is the default
        'since': since,
    };
    // if the user specifies `page` in params – it will be added ↓ to the request here ↓
    const response = await this.private1PostListExecutedOrders (this.extend (request, params));
    const data = this.safeValue (response, 'data', []);
    return this.parseTrades (data, ...
```
