### ISSUE TITLE
create a margin order

### ISSUE THREAD

**Issue by zobi000** [ccxt/ccxt#6398]
Hello,

I have problem to create a margin order on binance.

`
import ccxt.binance as binance

b= binance({'apiKey': publicKey, 'secret': privateKey, 'options': {'adjustForTimeDifference': True}, })

b.sapi_post_margin_order({'symbol': 'BTC/USDT', 'side': 'buy','type':'market','quantity':1,'recvWindow':60000})
 `
I have this error :

 uring handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\rauber\PycharmProjects\script\venv\lib\site-packages\ccxt\base\exchange.py", line 439, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\rauber\PycharmProjects\script\venv\lib\site-packages\ccxt\binance.py", line 1674, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\rauber\PycharmProjects\script\venv\lib\site-packages\ccxt\base\exchange.py", line 458, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\rauber\PycharmProjects\script\venv\lib\site-packages\ccxt\base\exchange.py", line 564, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\rauber\PycharmProjects\script\venv\lib\site-packages\ccxt\binance.py", line 1668, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "C:\Users\rauber\PycharmProjects\script\venv\lib\site-packages\ccxt\base\exchange.py", line 476, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}

I can import my balance, loan or borrow but i can't create a new order. Do you know how create a margin order in binance?

**Comment by kroitor** [comment]
You have errors in your code.

First of, you're not using the rate-limiter, despite that it is required, as documented in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Secondly, since you're using implicit API methods to place the order – your params should match the documentation of the exchange:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Also, you seem to be confusing unified symbols with exchange-specific market ids. Unified symbols are used with the Unified API. While exchange-specific implicit APIs require an exchange-specific market id instead of a unified symbol. This is also explained in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

If you want to see binance's symbols and market ids – see this example:

- https://github.com/ccxt/ccxt/blob/master/examples/py/symbols.py

In your request, you have a wrong set of parameter names and their formats:

- https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md#margin-account-new-order-trade

You have the following errors:

- you're using a unified symbol `BTC/USDT` instead of an exchange-specific id `BTCUSDT` with an implicit API method
- you're using lowercase `side` which must be uppercase according to Binance's docs
- you're using lowercase `type` which must also be in uppercase
- the `quantity` must be a decimal string

So, to correct your errors, you should edit the code:

```Python
import ccxt.binance as binance

exchange = binance({
    'apiKey': publicKey,
    'secret': privateKey,
    'options': {'adjustForTimeDifference': True},
    'enableRateLimit': True,  # ←----------------------- ADD THIS
})

b.sapi_post_margin_order({
    'symbol': 'BTCUSDT',  # ←------- market id instead of a unified symbol here
    'side': 'BUY',  # ←------- UPPERCASE
    'type':'MARKET',  # ←------- UPPERCASE
    'quantity':'1',  # ←--------------- MUST BE A DECIMAL STRING
    'recvWindow':60000,  # optional
})
```

↑ All of that is explained in the Manual. In general, to work with this library efficiently we recommend to read the entire Manual from top to bottom at least once – it will save you a ton of time. Most of these questions are answered there. There's also a troubleshooting section as well as. Don't hesitate if you have further questions after that (make sure to read the [CONTRIBUTING](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) guidelines and the [FAQ](https://github.com/ccxt/ccxt/wiki/FAQ) on code formatting and readability).

**Comment by zobi000** [comment]
thank you for you help. This is work now.

**Comment by TokarM** [comment]
I'm trying to send a regular limit sell order on binanceus and keep getting the following error: 

AuthenticationError: binanceus {"code":-1022,"msg":"Signature for this request is not valid."}

I tried everything mentioned above and it is still doesn't work. However, the market order executes properly

This is working as expected:
await taking_exchange.createMarketBuyOrder('ADA/USD', 6, params);

But this one is not:
await exchange.createLimitSellOrder(coin.symbol, amount, price, params);

I also tried createOrder and it doesn't work as well:

await exchange.createOrder('ADA/USD', 'LIMIT', 'SELL', 6, 2.5, { "timeInForce": "GTC"});

await exchange.createOrder('ADA/USD', 'LIMIT', 'SELL', '6', 2.5, { "timeInForce": "GTC"});

await exchange.createOrder('ADA/USD', 'LIMIT', 'SELL', 6, 2.5);

await exchange.createOrder('ADA/USD', 'LIMIT', 'SELL', '6', '2.5', { "timeInForce": "GTC"});

none of this os working.
