### ISSUE TITLE
Get Min and Max Order size for each Symbol Pair on each exchange

### ISSUE THREAD

**Issue by Tunafleur** [ccxt/ccxt#640]
Is there a unified method for example getting the minimum order size for a pair like ETH/BTC on each exchange?
I have seen on some exchanges there is information stated when calling fetch_markets() but would be nice to have this unified since some exchanges have this information in it and some not, but the names also vary a lot.

Thanks guys!

**Comment by kroitor** [comment]
> Is there a unified method for example getting the minimum order size for a pair like ETH/BTC on each exchange?

There is no method such method because order size limits and precision are saved in the market structure, like so (just an example demonstrating how we are going to unify that metainfo):

```
{
                'id': id,
                'symbol': symbol,
                'base': base,
                'quote': quote,
                'darkpool': darkpool,
                'info': market,
                'altname': market['altname'],
                'maker': maker,
                'taker': parseFloat (market['fees'][0][1]) / 100,
                'lot': lot,
                'active': true,
                'precision': {
                    'amount': market['lot_decimals'],
                    'price': market['pair_decimals'],
                },
                'limits': {
                    'amount': {
                        'min': lot,
                        'max': Math.pow (10, precision['amount']),
                    },
                    'price': {
                        'min': Math.pow (10, -precision['price']),
                        'max': undefined,
                    },
                    'cost': {
                        'min': 0,
                        'max': undefined,
                    },
                },
            }
}
```

Many of those fields are not documented yet, because this is a work in progress. Some of them may be missing here and there. Let us know if you find those. We are adding improvements regularly. 

Apart from the above, there's also a family of functions for converting floats to specific precision by symbol:

```
amountToPrecision (symbol, value)
priceToPrecision (symbol, value)
costToPrecision (symbol, value)
feeToPrecision (symbol, value)
```

Those may be implemented with truncation or rounding depending on the rules of each particular exchange. More about it here:

- https://github.com/ccxt/ccxt/issues/393
- https://github.com/ccxt/ccxt/issues/522

We will be happy if you contribute parsing code and help us add those fields where missing. Feel free to submit a PR if you want to give it a try. We are thankful for all contributions. Just make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Let me know if the above answers your question or not. Thx!

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#markets

**Comment by kroitor** [comment]
I would close this for now, we are in the process of unifying currencies as well as markets and symbols, feel free to continue here if you still have any questions on this. Thx!

**Comment by Tunafleur** [comment]
https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- these minimum trade sizes are not in the library as far as i saw

**Comment by kroitor** [comment]
@Tunafleur that's right, they don't have an endpoint for that, so we currently have to hardcode those values in userland. Do you suggest hardcoding them in the library itself? Being hardcoded, those values might require some updates later... Alternatively, we can solve that by scraping, probably...

**Comment by Tunafleur** [comment]
@kroitor yes i see the problem, we should contact the exchanges and ask them to deliver the mindest trade sizes for each market via the API but in the meantime i would do a quick & dirty solution and hardcode the values which are known
