### ISSUE TITLE
FTX: Get historical data

### ISSUE THREAD

**Issue by mkang1234** [ccxt/ccxt#6403]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.21.83
- Exchange: FTX
- Method: fetch_ohlcv 

I'm trying to get 6 months of historical 1 minute data using ohlcv method.  I have specified "since" parameter to 6 months back but it appears to only return 1500 entries which is only past 2 days.  How do I obtain historical data back several months or longer?  Thank you

**Comment by kroitor** [comment]
@mkang1234 which symbol is it? Can you post the code to reproduce it or your verbose request/response or at least something?

**Comment by kroitor** [comment]
@mkang1234 actually, nevermind, I've reproduced it on my side. In general with FTX (as with many other exchanges) you are limited to 1500 candles (the limit differs from exchange to exchange), and with lower timeframes (`1m`/`5m`, etc) you can't get history that is too old because of that limitation. So, if you want 6 months back, you need `4h` or `1d`.

This is documented in the Manual here: 

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

![Screen-Shot-2020-01-23-at-22 23 55](https://user-images.githubusercontent.com/1294454/73016595-36ae5080-3e2f-11ea-9f48-e744d5503b97.jpg)

> **There's a limit on how far back in time your requests can go.** Most of exchanges will not allow to query detailed candlestick history (like those for 1-minute and 5-minute timeframes) too far in the past. They usually keep a reasonable amount of most recent candles, like 1000 last candles for any timeframe is more than enough for most of needs. You can work around that limitation by continuously fetching (aka *REST polling*) latest OHLCVs and storing them in a CSV file or in a database.

Hope that answers your question, let me know if not.

**Comment by mkang1234** [comment]
Thank you. That answered my question.
