### ISSUE TITLE
How to withdraw from Buda exchange?

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#6407]
Reading Buda doc (https://api.buda.com/#nuevo-retiro) I see that we need to submit an auth parameter in the post, which depends on the api keys. But I dont understand how to use the ccxt `withdraw` function. I used:

```
let buda = new ccxt.buda({<api_keys_conf>});
let withdraw_response = await buda .withdraw('BTC', 0.01, <deposit_address>, {});
```
and I get the error:
```
ExchangeError: buda Validation Failed
```
I think we can pass an extra param in the params parameter, but I dont know which one.
So I tried to read how buda withdraw is implemented in buda.js, and I found the following code:
```
    async withdraw (code, amount, address, tag = undefined, params = {}) {
        this.checkAddress (address);
        await this.loadMarkets ();
        const currency = this.currency (code);
        const request = {
            'currency': currency['id'],
            'amount': amount,
            'withdrawal_data': {
                'target_address': address,
            },
        };
        const response = await this.privatePostCurrenciesCurrencyWithdrawals (this.extend (request, params));
        const withdrawal = this.safeValue (response, 'withdrawal');
        return this.parseTransaction (withdrawal);
    }
```
I dont understand where is privatePostCurrenciesCurrencyWithdrawals and if it implementes the required auth.

(Should I submit questions using github issues or is there a better way to do it. Just let me now. Thanks!)

**Comment by kroitor** [comment]
If you compare your code with the `withdraw` function:

```JavaScript
await buda.withdraw('BTC',    0.01,   <deposit_address>,         {}                                     );
       //                              ↓          ↓                 ↓                           ↓
       async withdraw (code, amount,       address,             tag = undefined, params = {}) {
```

You're passing {} as the `tag` argument, which you shouldn't really do in general. However, this is just a sidenote, not the cause of your issue since that argument is not supported in Buda implementation at this moment. 

In order to understand the true cause, we need to check your verbose request/response, please paste it (without your keys) here, as explained in the [guidelines](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) and in the [Troubleshooting](https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting) section.

Questions to you (it would be great if you could post your answers to these along with the verbose output):

1. Do your constructor params contain anything else except the credentials? [Rate limiter enabled](https://github.com/ccxt/ccxt/wiki/Manual#rate-limit)? Any other options?
2. Does it work with `fetchBalance()` with the same credentials?
3. Does it work with `createOrder()` with the same credentials?

> I dont understand where is privatePostCurrenciesCurrencyWithdrawals and if it implementes the required auth.

That is explained in the Manual (we recommend to read it thoroughly from top to bottom at least once):

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods

> Should I submit questions using github issues

Yep, however, make sure to provide as much info as you can, that can help resolve it quicker.

> is there a better way to do it

Nope )

**Comment by kroitor** [comment]
@fedecaccia also, upon creating your API keypair with Buda website, have you checked the checkbox that enables the permission to withdraw?

![Screen-Shot-2020-01-24-at-07 09 16](https://user-images.githubusercontent.com/1294454/73044001-c2989a80-3e78-11ea-8cbf-1addd2be0c08.jpg)

**Comment by fedecaccia** [comment]
Thanks for your quick response @kroitor . Indeed the error was setting {} as tag, an nothing in the params. I fix the code and now Im using:
```
let buda = new ccxt.buda({<api_keys_conf>});
let withdraw_response = await buda .withdraw('BTC', 0.01, <deposit_address>, null, {amount_includes_fee: true, simulate: false});
```
and now withdraw was submited.


Thanks for the link explanation about this "magic functions".

Regarding a "better way to ask", I was just asking so I don't fill up issues with questions, soI don't disrupt your work.

Thank you very much for all the help!
