### ISSUE TITLE
Cannot insert datetime from Huobi trades to sql database

### ISSUE THREAD

**Issue by oab-do** [ccxt/ccxt#6414]
- OS: Windows 10  (64-bit)
- Programming Language version: Python 2.7.15. 
- CCXT version: 1.21.92 
- Exchange: huobipro
- Method: fetch_trades()

datetime in huobipro trades is `2020-01-27T02:46:55.850Z`

I tried directly inserting it into the db table:
`cursor.execute("INSERT INTO huobipro_trades_table (date_time) VALUES %s", huobipro_trades)`

It returned the error `TypeError: not all arguments converted during string formatting`

Then I tried converting it to string:
```
for d in huobiproTrades:
    date_time = d['datetime']
    date_time = datetime.datetime.strptime(date_time, '%Y-%m-%d %H:%M:%S.%f')
    date_time = date_time.strftime("%m/%d/%Y")
    insert_str = "INSERT INTO huobipro_trades_table VALUES (" + str(date_time) + "),(" + str(d[1]) + ");"
    c.execute(insert_str)
```

But it also gave me:
`ValueError: time data '2020-01-27T02:46:55.850Z' does not match format '%Y-%m-%d %H:%M:%S.%f'`

**Comment by kroitor** [comment]
First, please read the Manual on the formats of all the fields in a trade structure: https://github.com/ccxt/ccxt/wiki/Manual#trade-structure.

To fix your snippet, you should follow really carefully what the error tells you:

> `ValueError: time data '2020-01-27T02:46:55.850Z' does not match format '%Y-%m-%d %H:%M:%S.%f'`

Your computer tells you that the value in `d['datetime']` does not match your format specification:

```
d['datetime'] = 2020-01-27T02:46:55.850Z
your format   =   %Y-%m-%d %H:%M:%S.%f
                                      ↑ missing Z here in your format
                          ↑ missing T here in your format
```

So, the first part of the fix is to make it match:

```Python
for d in huobiproTrades:
    date_time = d['datetime']
    # ---------------------------------------------------- HERE ↓
    date_time = datetime.datetime.strptime(date_time, '%Y-%m-%dT%H:%M:%S.%fZ')
    # this will produce the correct date_time without a ValueError in the above line
```

The second part is for you to make sure that your SQL query agrees with SQL language and the table format.

I cannot provide more help on the following code (and it doesn't look right to me) without a lot more info from you on the structure of that SQL table, and the task you are trying to solve in general:

```Python
    # THIS DOES NOT LOOK RIGHT TO ME
    
    date_time = date_time.strftime("%m/%d/%Y")
    insert_str = "INSERT INTO huobipro_trades_table VALUES (" + str(date_time) + "),(" + str(d[1]) + ");"
    c.execute(insert_str)
```

I would recommend to print out the `insert_str` before executing it, so that you could read it and check that it is correct for your use case. 

In general, your question is not about CCXT, but more about using sql with python, which we don't consult on, therefore you might want to forward your sql-related questions on websites like https://stackoverflow.com. If I get more involved into this particular problem – i will be actually doing your work for you, so from here I would leave it up to you to resolve and fix it.
