### ISSUE TITLE
Digifinex will steal your funds and not tell you why

### ISSUE THREAD

**Issue by cryptoAcc0unt** [ccxt/ccxt#6424]
Myself and many others have had our accounts frozen on Digifinex recently (10 days now). It seems everyone who was frozen was doing arbitrage. They claim they don't even have to give a reason and seem to just be ignoring us now; they are banning everyone who asks about disabled accounts from their telegram channels. Exchanges have shown themselves to be responsive to the threat of being delisted from CCXT and losing many API traders, for this reason and to protect other traders from the same fate, I think CCXT should delist Digifinex like it did CoinTiger. The crypto community needs to come together to put pressure on scammy exchanges or they will just keep taking advantage of us. 
![digifinexBS](https://user-images.githubusercontent.com/60350652/73263822-6a76d680-419f-11ea-8790-d46323019269.jpg)

**Comment by kroitor** [comment]
> I think CCXT should delist Digifinex

We cannot do this based solely on the info from your single report. We understand how locking funds might feel, and the CCXT Dev Team is on the users' side in any such case, but your account is new on GitHub and this is your first message ever, so we hope for your understanding as well. This issue needs more details and objective information. The more reports with details – the better chances you have for a positive resolution.

> The crypto community needs to come together to put pressure on scammy exchanges or they will just keep taking advantage of us.

Totally agree with you on this.

Let's keep this issue open for a discussion.

**Comment by npomfret** [comment]
@cryptoAcc0unt  I'm sorry to hear that, and I feel the same way about livecoin, but I think it would not be the right thing to do to remove them from ccxt.  

Your best bet is to try to shame them on reddit / twitter / LinkedIn or whatever social media you can think of.  Contact anyone on social media who mentions them to warn them.  Stick to the facts though, and of course never reveal any account details.  

Contact law enforcement in your jurisdiction if you feel they have defrauded you (just because something in the the terms and conditions doesn't make it legal).  I found with livecoin that they have removed all possible contact details from their site, I couldn't sue them if I wanted to.  There are no names of staff, and no addresses of their offices.  It's effectively a shell corporation who have very cleverly hidden their true identity or any possibly way to find it.  You might find that Digifinex have followed the same pattern.

I know it's not helpful, but the lesson to learn is that you need to do some due diligence on the exchange before trading with them.

**Comment by silert** [comment]
Hello, I successfully traded on Digifinex for a long time and my account also was frozen 10 days ago with all funds. Many people complains about frozen accounts in their official telegram chat (DigiFinexEN). I'm not asking to remove this exchange from ccxt, but please be careful with arbitrage trading on Digifinex.

**Comment by npomfret** [comment]
Contact them directly via LinkedIn ...

<img width="839" alt="Screenshot 2020-01-28 at 14 44 56" src="https://user-images.githubusercontent.com/5489469/73274146-f824e700-41dc-11ea-8e8a-10eb7e94a2f3.png">

**Comment by oliverdigifinex** [comment]
I'm a  staff member of Digifinex, can you tell me the specific situation including your UID and what happend, let me see what I can do for you，telegram：@oliverdigifinex emal：oliver_xing@digifinex.com

**Comment by oscaroyk** [comment]
Digifinex has always put the first priority to enhance our security so as to protect user fund. We are very concern about the issue @cryptoAcc0unt had mentioned, i hope you can provide more information for our further investigation and clarify if there is any misunderstanding. Apart from above Oliver's email, please also send to support@digifinex.com with your UID and details. Thank You.

**Comment by oliverdigifinex** [comment]
A client’s account be hacked and It resulted in huge loss of this client and  inappropriate profit of several other accounts（about 10）.We have to locked these account. After investigation and negotiation Some accountss agreed to roll back the abnormal transaction will be unblocked today.

**Comment by oscaroyk** [comment]
Thanks @oliverdigifinex for the clarifying the issue. @kroitor customer already contacted with us and solved the problem. As mentioned, DigiFinex is always strive our best toward to the customer services and network security.

If users has encountered issue on DigiFinex, please don't hesitate to contact our support at support@digifinex.com

**Comment by kroitor** [comment]
Thank you @oliverdigifinex @oscaroyk!

@cryptoAcc0unt can you confirm whether this issue is resolved now on your side?

**Comment by cryptoAcc0unt** [comment]
Thanks @oliverdigifinex, @oscaroyk, I have access to my account again. The lack of clear communication from Digifinex is troubling (just yesterday online CS was telling me it would be 1-3 weeks), but I am thankful that they eventually figured it out. @kroitor thanks for keeping the issue open, it seems that exchanges feel some pressure to act when they get called out publicly here.
