### ISSUE TITLE
huobipro 'private_post_margin_orders_id_repay' wrong implementation?

### ISSUE THREAD

**Issue by stringyao** [ccxt/ccxt#6440]
Exchange huobipro has its specific and implicit api 

```
POST /v1/margin/orders/{order-id}/repay
```

which is used to repay the loan for the margin account. This api takes two parameters, 'order-id' and 'amount', and the parameter 'order-id' (the id for the loan one applied before) should be written in the url path as shown in the api. 

However, the implicit method used by ccxt.huobipro is as follows:

```
ccxt.huobipro.private_post_margin_orders_id_repay()
```

which does not seem to work as the api implies. 

I'm wondering is there any way to make this work? I tried to feed the above method with params such as

```
repay_request = {
  "order-id": "5980103",
  "amount": "1.0"
}

repay_response = huobipro.private_post_margin_orders_id_repay(repay_request)
```
and 

```
repay_request = {
  "amount": "1.0"
}

repay_response = huobipro.private_post_margin_orders_id_repay(repay_request)
```
Yet neither of the two fulfilled the purpose.

**Comment by kroitor** [comment]
> This api takes two parameters, 'order-id' and 'amount', and the parameter 'order-id' (the id for the loan one applied before) should be written in the url path as shown in the api.

That's right, according to Huobi docs, that endpoint needs `order-id` and `amount`.
The `amount` value gets sent in the POST body, therefore the name of that argument matters. However, the `order-id` argument is not sent in the request, it is included in the request URL, as you've noted precisely. Therefore when you submit a loan id, it will substitute that argument in the URL and the request ends up looking like this:

```JavaScript
//                        ↓ the order-id goes here in the URL
POST /v1/margin/orders/123456/repay
{
    'amount': "123.45", // the amount goes here in the body
}
```

From the above you can see that the name of the `amount` is sent in the body, while the name of `order-id` is not sent anywhere (it's replaced with the actual id).

If you look at Huobi API endpoint definitions from CCXT, that endpoint is defined as:

- https://github.com/ccxt/ccxt/blob/master/js/huobipro.js#L122

```JavaScript 
'margin/orders/{id}/repay', // 归还借贷 ←------------------- HERE
```

In that URL, the `order-id` parameter is actually called just `id`. And since its name does not matter on the exchange side, it will be substituted for whatever `id` you submit in `params` (not for `order-id`).

For that reason the name of that method according to [naming conventions](https://github.com/ccxt/ccxt/wiki/Manual#api-method-naming-conventions) is 

- `private_post_margin_orders_id_repay` 

instead of 

- `private_post_margin_orders_order_id_repay`

Therefore, the correct code is:

```Python
repay_request = {
  "id": "5980103",  # ←----------- "id" here
  "amount": "1.0"
}

repay_response = huobipro.private_post_margin_id_repay(repay_request)
```

Let us know if that does not answer the question.

**Comment by kroitor** [comment]
P.S. We may change that argument name to `order-id` in the future to align that naming with Huobi's docs for less confusion.

**Comment by stringyao** [comment]
Thank you very much for your quick and detailed reply. Changing 'order-id' to 'id' solved my problem.
