### ISSUE TITLE
Question: Deduct exchange currency id from symbol

### ISSUE THREAD

**Issue by jgordor** [ccxt/ccxt#647]
Hi,

I need from a normalized currency (from symbol), get the exchange currency Id (to be able to understand some exchanges responses, example (bitstamp):

Market-sell fetchOrder response (ETH/BTC symbol):

```javascript
{
        status: 'Finished',
        id: 111111111111,
        transactions: [{
          fee: '0.00001',
          price: '0.04433001',
          datetime: '2017-11-22 15:43:02.017688',
          btc: '0.0013299003000000',
          tid: 222222222,
          eth: '0.03000000',
          type: 2
        }]
      }
```

ccxt provided info (mapped pairs/symbols):
```javascript
bitstamp.markets
....
  'ETH/BTC':
   { limits: undefined,
     precision: undefined,
     id: 'ethbtc',
     symbol: 'ETH/BTC',
     base: 'ETH',
     quote: 'BTC' }
...
```

From the symbol base/quote I can't deduct the real base/quote name used on the exchange side (some does not have "/" separator, sometimes lowercase, ..).

Do you know how I can get this info normalized on all the exchanges?

**Comment by kroitor** [comment]
@jgordor do you need currency id or market id?

**Comment by jgordor** [comment]
@kroitor the currency id

**Comment by kroitor** [comment]
@jgordor currently, you will have to hardcode those, because separate currencies are not completely unified yet. We're working on this, see here:
- https://github.com/ccxt/ccxt/pull/553
- https://github.com/ccxt/ccxt/pull/473

We will update you on the progress, in the meantime, I'd close this issue if you don't mind. Feel free to reopen it if necessary or ask questions, if you have any. We hope to deliver currency unification soon.

**Comment by jgordor** [comment]
Thanks!!
