### ISSUE TITLE
Indodax: No market symbol USDT/IDR (RVN/IDR)

### ISSUE THREAD

**Issue by alinaKava** [ccxt/ccxt#6476]
Get error: "ExchangeError: No market symbol USDT/IDR". The same with symbol RVN/IDR.

- OS:
- Programming Language version: Python
- CCXT version: 1.22.40
- Exchange: Indodax
- Method: fetchTrades

**Comment by kroitor** [comment]
Hi! Are you sure you have the most recent version?

It works with [cli.js](https://github.com/ccxt/ccxt/blob/master/examples/js/cli.js):

- https://gist.github.com/kroitor/3f5ab19a736d8dd4f0f773da01b82e89

And [cli.py](https://github.com/ccxt/ccxt/blob/master/examples/py/cli.py):

- https://gist.github.com/kroitor/b51134bf38ecb29214a7d04300169aaf

Also, both symbols are listed out in the indodax implementation:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/indodax.py#L113
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/indodax.py#L119

Make sure you have CCXT up to date. Let us know if that does not resolve the issue. Feel free to reopen it if needed or just ask further questions if any. In order to provide more detailed help on this, we need your verbose request/response sequence and the code to reproduce it:

```Python
import ccxt
exchange = ccxt.indodax ({'enableRateLimit': True, 'verbose': True})
print('CCXT version:', ccxt.__version__)
print(exchange.fetch_trades('USDT/IDR'))
```
