### ISSUE TITLE
A way to identify market types (stable coin markets, leverage token markets) ?

### ISSUE THREAD

**Issue by gaugau3000** [ccxt/ccxt#6481]
Hi,

If i take exemple of binance in spot markets we can a kind see 3 types like :
- Classic : BTC/USDT
- Stable USDC/USDT
- Leverage token : ETHBEAR/USDT

Such classification seem not to be provide by binance API (so cannot appear in market structure result) i don't know for other exchanges.

Do you know if there is a way to handle this ?

Many tks have a nice day.

**Comment by kroitor** [comment]
> Do you know if there is a way to handle this ?

To be honest, it's not entirely clear which classification you mean, since you haven't defined the  criteria for the classification. There's no direct link between BTC/USDT and USDC/USDT, the only commonality here is the quote currency USDT, and that's it.

Let me know if that does not answer the question. Feel free to reopen this, or just ask further questions if any.

**Comment by gaugau3000** [comment]
Hi,

I have not the rights to re-open this issues but i will try to explain better.

I would like to be able to filter markets depending on reference currency type of coin.

I can classify coin in three categories : stable coins (USDT, USDC...) , classic crypto (BTC, ETH) and leverage token (ETHBEAR, EOSBBULL)... Maybe you can define more maybe the categories are irrelevant no matter.

Does exchanges or external api (i don't know if cctx have dependencies with non crypto exchanges api) provide a kind of this type of classification.

The idea is not to hardcode markets you want to trade and say of example i trade only stable coins market or only leverage token...

Many tks.

**Comment by kroitor** [comment]
> I can classify coin in three categories : stable coins (USDT, USDC...) , classic crypto (BTC, ETH) and leverage token (ETHBEAR, EOSBBULL)... Maybe you can define more maybe the categories are irrelevant no matter.

Your idea is more clear now, thanks for explaining it, however, not too many exchanges provide that info from their APIs. You could also classify them differently, like most of the exchanges do: Omni (USDT, ...), Ethereum (ETH, USDT ERC20, USDC, ...), Bitcoin and forks (BTC, BCH, ...). ETH can also be classified as a Bitcoin fork )

You can check all the info from the exchanges yourself if you clone this repo, run `npm install` in it and then try the various [examples](https://github.com/ccxt/ccxt/tree/master/examples). You can launch them from your command line, don't even have to code anything:

- https://gist.github.com/kroitor/4482755810755efccc15f235062111ce
- https://gist.github.com/kroitor/9744b8d6da525a5a6adc4011c682d99a
- https://gist.github.com/kroitor/82c4c07573676647a94a2e0bd646d71b
- https://gist.github.com/kroitor/14c3ae542b5cf9ad9c75c04573904f03
- https://gist.github.com/kroitor/56f8e9f1cdffec08fcc015a51a664afe
- https://gist.github.com/kroitor/81c0e27fa49647f2ac26a33b2cf49bfc
- https://gist.github.com/kroitor/2a685493e940d588f042cbe364528f09

↑ You can experiment with all the flags, methods, variables and params as explained in the Manual: https://github.com/ccxt/ccxt/wiki/Manual

In CCXT we currently have a `type` property on the market to distinguish spot/futures markets. However this aspect is not fully unified yet. We will look into other classifications as soon as we can. In the meantime, we would suggest to store the list of token codes and market pairs of your interest in a config, since many of them are very new, and they appear and disappear daily.

Hope that answers your question. Let us know if you have more )

**Comment by catafeidi** [comment]
Hi,

That's a DOM and there are some of the important elements such as: 'isSpotTradingAllowed', 'isMarginTradingAllowed'.
Both of them are under the object 'info'.

You can access them by following calls:

**exchange.load_markets()**  ----> to initialize all the coin pairs
**exchange.markets['DOTUP/USDT']['info']['isSpotTradingAllowed']**        ->>>> to read the element isSpotTradingAllowed

The return of above pair will be false because DOTUP/USDT pair is only on leverage market.

Please find attached the entire structure of markets where you can filter based on elements/nodes.
[ccxt market structure.txt](https://github.com/ccxt/ccxt/files/7602443/ccxt.market.structure.txt)

**Comment by gaugau3000** [comment]
To categorize  coins, coingecko provide a way:

[swagger doc](https://www.coingecko.com/fr/api/documentation)

then

https://api.coingecko.com/api/v3/coins/categories/list

and 

(example with stable coins : &category=stablecoins)

https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&category=stablecoins&order=market_cap_desc&per_page=1000&sparkline=false&locale=en

Not sure if ccxt use or want to use coingecko (extra http dependencies)  be it can be added in marketInfos associated to a symbol.

**Comment by alsaffar01** [comment]
Any update here on the suggestion of @gaugau3000 ?
I mean, there is a flag that indicates whether the currency is legal tender or not, but there is none that indicates whether it is a stable currency or not, I think its direly missing from the `info` of a currency.

gecko is good, but you will have to worry about the mapping from ccxt terminology to gecko.
