### ISSUE TITLE
orderBook for pair 'BTC/USDT' at OKEX3

### ISSUE THREAD

**Issue by claudio-br** [ccxt/ccxt#6484]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by claudio-br** [comment]
I can't to obtain the orderBook for the pair BTC/USDT at okex, i'm using okex3 API. The message is obtained: 
 okex3 {"code":30032,"message":"The currency pair does not exist"}

I am using the code bellow:

;(async ( ) => {
exchange =  new ccxt.okex3 ()
let  orderBook = await exchange.fetchOrderBook('BTC/USDT', 3)
console.log (orderBook)
}) ( )

If i change the pair to 'BTC/USDK' its work correctly. 

{ bids:
   [ [ 10246.4, 2.15 ], [ 10243.4, 1.1 ], [ 10242.1, 0.28786 ] ],
  asks: [ [ 10251.9, 3.7 ], [ 10254.2, 0.026 ], [ 10255.3, 0.002 ] ],
  timestamp: 1581621878438,
  datetime: '2020-02-13T19:24:38.438Z',
  nonce: undefined }

best regards, 

Claudio

**Comment by kroitor** [comment]
1. Which version of CCXT do you have?
2. This should work with the most recent version:

```JavaScript
const ccxt = require ('ccxt')
;(async () => {
    const exchange = new ccxt.okex3 ({
        enableRateLimit: true, // required by the Manual
    })
    console.log (await exchange.fetchOrderBook('BTC/USDT'))
}) ()
```
↑ This is a complete program that shows that OKEX3 has BTC/USDT and it works with fetchOrderBook. If you copypaste this to your node, you should see this: https://gist.github.com/kroitor/617bd6215b1c9f29f5ec614c2134176d

If that short snippet works and not your code – then we need to see a complete code to reproduce the issue (as there might be a bug somewhere else).

3. Please, use [github markdown](https://guides.github.com/features/mastering-markdown/)  for readability when pasting code and output.

4. In order to help, we need your verbose request/response and the full code to reproduce it as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by claudio-br** [comment]
Thanks Koitor. 
I was using  an old version. 
Best regards
