### ISSUE TITLE
having trouble with futures api

### ISSUE THREAD

**Issue by doongzzi** [ccxt/ccxt#6496]
when i transfer funds between spot<->futures wallet with the function below, it returns "{total:0}" which doesn't fit with the returns i expected. where can i find the right example for transfering between wallets

transfer = await sbinance.sapi_get_futures_transfer({
    asset: "USDT",
    amount: 10,
    type: 1,
    startTime: +new Date()
  });

**Comment by kroitor** [comment]
1. You're using a wrong endpoint. `sapi_get_futures_transfer` is for getting the history of transfers, and if you have no transfers it will return `{'total': 0}`. The correct endpoint for posting a transfer is `sapi_post_futures_transfer` (`POST`, not `GET`)

2. Binance docs say that `amount` must be a decimal string, `'10'` (with quotes), instead of `10`.

3. `startTime` is not supported for the `sapi_post_futures_transfer`, since it only makes sense in the `GET` context...

Therefore your code should be:

```JavaScript
const transfer = await exchange.sapi_post_futures_transfer({
    'asset': 'USDT',
    'amount': '10',
    'type': 1,
})
```

Does that answer your question?

**Comment by doongzzi** [comment]
love you 3000. 
have one more question though, is there any way to get spot trade orderbook when i made the defaultType as 'future' ? Is defining another ordinary ccxt.binance() the only way to get them?

**Comment by kroitor** [comment]
> Is defining another ordinary ccxt.binance() the only way to get them?

Yes, unfortunately, they're not interchangeable atm (futures markets are not interchangeable with spot markets yet), but we will look into adding better unification to that aspect: https://github.com/ccxt/ccxt/issues/6376

Let us know if anything. Feel free to reopen this or just ask if you have more questions.

**Comment by q15197721923** [comment]
Excuse me, is this method exclusive to CCXT Pro?

**Comment by kroitor** [comment]
@q15197721923 no, you can use it with the free version of CCXT.

**Comment by q15197721923** [comment]
thank you very much

**Comment by q15197721923** [comment]
I'm sorry to ask again why I don't have this method. Is there any operation that needs to be done?

**Comment by kroitor** [comment]
@q15197721923 this is answered in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods

You should have it in the most recent version of CCXT. Let us know if the above does not help.

**Comment by q15197721923** [comment]
Oh! Thank you. I'll do it right now. Thank you so much
