### ISSUE TITLE
fetchMyTrades on Huobipro / can't get my history

### ISSUE THREAD

**Issue by NansSimpson** [ccxt/ccxt#6512]
Hello, I'm trying to `fetchMyTrades` on Huobi exchange but it would only show the past few days. 
I'm using the `since` parameter like this: 
`since=huobi.parse8601('2018-01-01T00:00:00Z')`
`myTrades=huobi.fetchMyTrades (symbol = 'ADA/BTC', since = since, limit = None, params = {})`
But I get this error:
`ExchangeError: huobipro {"status":"error","err-code":"invalid-start-date","err-msg":"The start date of query contains illegal values.","data":null}`
How can I fetch my trades history? Have you found another method?
Thanks a lot.

**Comment by kroitor** [comment]
Hi! Can you post your verbose output for the above request?

```Python
exchange.load_markets()
exchange.verbose = True
exchange.fetch_my_trades(symbol, since, limit=None, params)
```

↑ Please, post your output here.

**Comment by NansSimpson** [comment]
Here is the response
![image](https://user-images.githubusercontent.com/24104411/75015323-9cbae180-5488-11ea-8d90-a90ec0eeb193.png)

**Comment by NansSimpson** [comment]
My request:
`huobi.load_markets()`
`since = huobi.parse8601('2018-01-01T00:00:00Z')`
`huobi.verbose = True`
`huobi.fetch_my_trades(symbol=None, since=since, limit=None)`

The response:
![image](https://user-images.githubusercontent.com/24104411/75015538-19e65680-5489-11ea-89e7-cabba96db538.png)

**Comment by kroitor** [comment]
@NansSimpson for some reason you're ignoring the [FAQ](https://github.com/ccxt/ccxt/wiki/FAQ). 

You haven't posted the request part, which was the key, just the response... And you have posted text as an image – please don't do that, otherwise nobody will be able to find it using the search later. Always post text as text using [github markdown](https://guides.github.com/features/mastering-markdown/). 

We need to see both the verbose request and the response, not just the response. You can strip your credentials from it if you want, but we need both parts to resolve this. Do not cut off the beginning or the ending of it, though.

Most likely, the problem is related to this: https://github.com/ccxt/ccxt/blob/master/python/ccxt/huobipro.py#L488. In other words, this is a limitation on the exchange side that does not allow you to fetch history older than 120 days. And even if you fit in the allowed range, you should also specify the end-date within 2 days from the start-date, i think.

Also, they have updated their docs, and now they say, it's 61 days, not 120... So they've tightened their limits:

- https://huobiapi.github.io/docs/spot/v1/en/#search-match-results

Does this work:

```Python
huobi.load_markets()
since = huobi.parse8601('2020-01-01T00:00:00Z')  # a date within 61 days from today
params = {
    'end-date': huobi.ymd(huobi.parse8601('2020-01-03T00:00:00Z'))  # +2 days allowed range
}
huobi.verbose = True
huobi.fetch_my_trades(symbol=None, since=since, limit=None, params)
```

?

**Comment by NansSimpson** [comment]
I'm sorry I'm not very familiar with posting issues and Github.
Yes, it does work with only +1 day range. This is kind of annoying, I guess I'll have to fetch my trades everyday to record my whole history.
Thanks a lot for your help!

**Comment by kroitor** [comment]
@NansSimpson yep, unfortunately, this is a limitation that we cannot workaround in the lib, because it's coming from the exchange itself. Let us know if you have further questions.
