### ISSUE TITLE
error loading ccxt in javascript rhino shell

### ISSUE THREAD

**Issue by rmcxm** [ccxt/ccxt#6554]
I am trying to load ccxt in rhino javascript shell. it is giving me this error:
**starting the shell:** 
`java -cp rhino1.7.12/lib/rhino-1.7.12.jar:. org.mozilla.javascript.tools.shell.Main`
**loading ccxt:**
`js> load('node_modules/r.js')`
`js>  var ccxt = require(['ccxt/ccxt.js'])`
`js: "ccxt/ccxt.js", line 171: SyntaxError: invalid object initializer`
`js: module.exports = Object.assign ({ version, Exchange, exchanges: Object.keys (exchanges) }, exchanges, functions, errors)`
`js: .........................................^`
`js: "ccxt/ccxt.js", line 1: Compilation produced 1 syntax errors. at node_modules/r.js:2466`

meanwhile i tried in node js server;
there it perfectly loads and prints everything.

i am working on a java project where rhino js shell is used instead of node server.

- OS: fedora 30
- Programming Language version: javascript / rhinojs
- CCXT version: '1.22.86'
- Exchange: 
- Method:

**Comment by kroitor** [comment]
@rmcxm i'll do my best to install rhino and investigate, thank you for reporting!

**Comment by kroitor** [comment]
@rmcxm we've uploaded a possible workaround for it, it would be great if you could test it against the most recent version of CCXT and report back. Thank you!

**Comment by kroitor** [comment]
@frosty00 Actually, that fix probably won't help (( But thx for trying anyways.

The cause of the problem is that rhino does not support ES6. So you have to transpile it from ES6 to ES5 to use it in rhino.

@rmcxm It's not easy to tell the instructions on how to do that, since it heavily depends on the structure of your package, i think. In general you have to tell the transpiler which files to transpile to ES5 and also which files to exclude from the transpilation or include in the process, depending on your target platforms, etc, etc. So, it may be a Babel config of two lines + a few helper plugins or a longer config file...

- https://medium.com/@SunnyB/how-to-convert-es6-into-es5-using-babel-1b533d31a169

You may also want to to check other tutorials on ES6 ←→ ES5 on google. Unfortunately, this is a little bit beyond of the scope of this lib at this time, so you have to do your research.

Also, some insights may be found here:

- https://github.com/ccxt/ccxt/search?q=babel&type=Issues
- https://github.com/ccxt/ccxt/search?q=webpack&type=Issues
- https://github.com/ccxt/ccxt/search?q=react&type=Issues
- https://github.com/ccxt/ccxt/search?q=browserify&type=Issues

It would be great if you report back whether you have a followup on this issue or not.

**Comment by rmcxm** [comment]
When I transpiled whole module (each file one by one), it gives me error - " module is undefined " because in rhino, they are expecting 'define' method for exporting module. So I have to replace module.exports in each file by 'define' which I am having no idea how to do. So I am looking to use websockets in java or something else (I need to use only ohlcv api).

**Comment by kroitor** [comment]
@rmcxm https://github.com/knowm/XChange

**Comment by rmcxm** [comment]
thanks I don't have to rewrite now.

**Comment by rmcxm** [comment]
no binance futures support in this ?

**Comment by kroitor** [comment]
@rmcxm we hope to add the support for native Java and other compiled languages in CCXT soon after migrating to TypeScript, but yeah, for now it would be easier for you to use an alternative. Another alternative solution to your problems – is having a REST http gate to your backend – then you don't have to tie them up and they can be loosely coupled. So you have nodejs ES6 behind a https server with a REST api that forwards calls from HTTP to CCXT to Exchanges and back. This way you're more language agnostic.

**Comment by kroitor** [comment]
> no binance futures support in this ?

I'm not sure, since I don't maintain that package. But CCXT does support Binance futures.

**Comment by rmcxm** [comment]
since it is an android app that i am working on, i am unaware of running a node server (heard of liquidcore but not much) in an app, so i will give it a pass until ccxt comes with java support. i will try forking Xchange for now. thanks for showing me right path!
