### ISSUE TITLE
Okcoin.fetch_tickers always ends with an exception.

### ISSUE THREAD

**Issue by alexander-irbis** [ccxt/ccxt#6562]
- OS: MacOS
- Programming Language version: Python 3.7.5
- CCXT version: 1.23.49 (seen before at least on 1.23.35)
- Exchange: okcoin
- Method: fetch_tickers

Call to `okcoin.fetch_tickers()` ends with an exception: 
```
ExchangeError('okcoinusd{"error_code":1}')
```

**Comment by kroitor** [comment]
@alexander-irbis the okcoinusd is deprecated, since it migrated to v3, and the version implemented in CCXT is v1. We will eventually move it to v3, see more details here: https://github.com/ccxt/ccxt/pull/6563

Let me know if that does not answer the question. Closing this for now if you don't mind. Feel free to reopen it or just ask if you have more question.

**Comment by alexander-irbis** [comment]
Did I understand correctly that okex3 should be used instead of okcoin? Are these not different exchanges?

**Comment by brandsimon** [comment]
@alexander-irbis 
The implementations of the API are the same, so CCXT changed to the new v3 API.
