### ISSUE TITLE
Can we support sending batch coins for calling fetch_ohlcv

### ISSUE THREAD

**Issue by lfzCarlosC** [ccxt/ccxt#6578]
Hello,
Just found out that full scanning all coins in exchange will call `fetch_ohlcv ` one time for each coins, totally making massive times of calls for scanning all coins and cost a lot of time because for each call the client needs to hold for a while. Can we do sth to send a batch of coins for calling so that the number of calls can be reduced and save a lot of time? My app now is suffering with this issue when full scanning coins.

- OS: linux
- Programming Language version:
- CCXT version: latest
- Exchange:
- Method:

**Comment by kroitor** [comment]
> Can we do sth to send a batch of coins for calling so that the number of calls can be reduced and save a lot of time?

In most cases – we cannot, because the exchange endpoint only accepts a single OHLCV symbol, we can't send many symbols even if we wanted to. However, the general way to address this – is to have more than once computer, working in parallel and each gathering it's own subset of OHLCVs. This is usually done in an AWS cloud. In other words, you should apply some parallelization to your architecture to optimize it for your use case.

Let me know if that doesn't answer the question.
