### ISSUE TITLE
The limit method in CCXT pro and offload cached streaming data

### ISSUE THREAD

**Issue by icytrader** [ccxt/ccxt#6579]
Hi,

```
// throttling mode
const limit = 5 // optional
// await is optional, alternatively you can launch it in bg without await
await exchange.watchOrderBook (symbol, limit)
while (true) {
    // your reaction takes place here
    // you arrive here every 100 ms regardless of whether there was an update or not
    // in throttling mode offloading the orderbook with .limit () is required
    console.log (exchange.orderbooks[symbol].limit (limit))
    await sleep (100) // every 100 ms
}

```

In the manual of CCXT pro there is an example for throttling mode where we get the cached orderbook infomation with a limit() method. I tested it out and I know that without the limit method you will only get a static orderbook on the console if you do:

```
    console.log (exchange.orderbooks[symbol])

```

1) Could you help me understand what trick the limit method is doing here besides slicing the orderbook? I checked out the limit method definition on the source code OrderBookSide.js but I can't explain.  I only have some Python experience and new to JS. Thank you very mcuh.

2) For other streamed data like ticker and orders, how can I offload the most recent snapshot from cache?

- OS: Windows
- Programming Language version: Node.JS
- CCXT version: CCXT Pro
- Exchange: Binance
- Method: WatchOrderBook

**Comment by frosty00** [comment]
if you don't run `await exchange.watchOrderBook` then the limit method is not run. Since messages are arriving all the time even when you are not `awaiting` for them the orderBook deltas are indexed by their price's in a hashmap. This is faster than inserting the bids/asks into the list will take at least `O(n)` time, possibly more depending on the implementation.

The limit method converts these indexes into an ordered orderBook with bids and asks arranged in order.

> For other streamed data like ticker and orders, how can I offload the most recent snapshot from cache?

You can use `exchange.tickers[symbol]`, and `exchange.orders[symbol]` however the underlying data structures are still undergoing heavy development.

**Comment by kroitor** [comment]
@icytrader Hi!

> 1. Could you help me understand what trick the limit method is doing here besides slicing the orderbook? I checked out the limit method definition on the source code OrderBookSide.js but I can't explain. I only have some Python experience and new to JS. Thank you very mcuh.

Basically, it does the slicing of the output result and also does the limiting in case of limited order books. Suppose you have an order book that is limited by a certain number of bids and asks, say, the exchange only sends top 150 bids and top 150 asks. Then, if a new bid delta with a new price is received, after inserting it into the orderbook there should remain 150 bids, not 151. The exchange will only update the topmost 150 orders, and will not send deltas for orders below 150. Thus, the 151th order is quickly outdated and not updated anymore – it must be removed from an orderbook with a limit of 150. Now suppose that the underlying exchange can also index the orders by order id instead of by price. You can't just do a basic array slicing on a dictionary indexed by order ids. The limiting, sorting and slicing has to be done based on the price. So, in general, the `limit()` method is used not only for slicing, but also for proper sorting, depending on the type of orderbook in question.

> For other streamed data like ticker and orders, how can I offload the most recent snapshot from cache?

Most of other incremental structures supported so far – are plain lists or dicts, so you don't have to offload them with a special method – can just use them as is. The orderbooks is a very special case, though, therefore it requires a limiting method to work properly. We might introduce some offloading methods for other structures, but so far the orderbook is the only type of incremental structure that requires offloading with a call to the `limit` method.

Let us know if that does not answer your questions )
