### ISSUE TITLE
Bittrex fetch_ohlcv for restricted markets with API v2 

### ISSUE THREAD

**Issue by TheSkynet1337** [ccxt/ccxt#6584]
- OS: Ubuntu 18.04.4
- Programming Language version: Python
- CCXT version: 1.23.30(persists with newest version)
- Exchange: Bittrex
- Method: fetch_ohlcv

fetch_ohlcv for Bittrex uses self.v2GetMarketGetTicks to grab ohlcv data for a symbol/market.
Creating an API call similiar to this
 https://bittrex.com/api/v2.0/pub/market/GetTicks?marketName=BTC-CTC&tickInterval=fiveMin 
however since this is a restricted market on Bittrex the call simply returns {"success":false,"message":"RESTRICTED_MARKET","result":null,"explanation":null}.
This results in an exception being thrown by fetch_ohlcv.

I would propose changing the v2 call in the Bittrex exchange file from
 'v2': 'https://{hostname}/api/v2.0/pub' to 'v2': 'https://global.{hostname}/api/v2.0/pub'. 
This results in a call like this 
https://global.bittrex.com/api/v2.0/pub/market/GetTicks?marketName=BTC-CTC&tickInterval=fiveMin
 which returns valid data.
This would also need to be done in the async variant of the file.

**Comment by kroitor** [comment]
> I would propose changing the v2 call in the Bittrex exchange file from
'v2': 'https://{hostname}/api/v2.0/pub' to 'v2': 'https://global.{hostname}/api/v2.0/pub'.

Hi! We don't really need to change the code since it supports user-configured hostnames and you can change the hostname in your exchange constructor args, like so:

```Python
import ccxt
exchange = ccxt.bittrex({'hostname':'global.bittrex.com'})
```

↑ This will use the Bittrex's "global" API host for all calls.

Let us know if that does not answer the question.
