### ISSUE TITLE
FTX fetchOpenOrders does not contain all orders

### ISSUE THREAD

**Issue by fonzmeister** [ccxt/ccxt#6586]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: 
- Programming Language version:
- CCXT version: 1.23.76
- Exchange: ftx
- Method: fetchOpenOrders

FTX has a different api endpoint for triggerOrders (e.g. stops). Thus the fetchOpenOrders method only fetches open limit orders.

I think it is better to fetch both api endpoints and merge the results, since that is the behaviour on other exchanges

**Comment by kroitor** [comment]
> I think it is better to fetch both api endpoints and merge the results, since that is the behaviour on other exchanges

It is not, in fact there's a strict rule in CCXT that says _"one HTTP request per unified method call"_, and `fetchOpenOrders` is a unified call. It will only break that rule in very few cases where it is makes a lot let sense to do otherwise. However, for `fetchOpenOrders` we can't break that rule, because that will effectively break the rate-limiting for the users who don't need triggerOrders. So, instead of sending two requests we will just add an option that will allow you to choose which orders to fetch (and fetch twice in userland if needed).

**Comment by fonzmeister** [comment]
Thanks for the explanation. That makes way more sense indeed.

**Comment by kroitor** [comment]
@fonzmeister please see this issue for a solution on fetching trigger orders from FTX (until we unify this aspect completely):

- https://github.com/ccxt/ccxt/issues/6669#issuecomment-603767175

**Comment by fonzmeister** [comment]
thanks,  I have similar problems with bybit btw.

**Comment by kroitor** [comment]
@fonzmeister 

> I have similar problems with bybit btw.
what do you mean? 

Bybit implementation does support fetching stop orders with [params overrides](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params):

```Python
order = exchange.fetch_order(None, None, {
    'stop_order_id': 'YOUR_STOP_ORDER_ID_HERE'
})
```

```Python
orders = exchange.fetch_orders(None, None, {
    'stop_order_status': 'Active', // 'Untriggered', 'Triggered', 'Cancelled', 'Rejected', 'Deactivated'
})
```

Let me know if that does not help.
