### ISSUE TITLE
Strange slippage with an order PHP/Binance

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#6615]
- OS: Ubuntu
- Programming Language version: PHP 7.2
- Exchange: binance

@kroitor - Hi, I don’t see you reading this message first as always :) 

My question is - does ccxt cache something at home I began to notice a very strange error when working with Binance a couple of days ago... 

**I want to say right away that this error cannot be received the first time; it falls 1:800**

Generally what magic happens: 
I place 2 orders using SAPI on margin account. 

out of 800 orders are placed normally (there are no delays) the algorithm of actions is

1. place an order №1
2. place an order №2
3. get order №1
4. get order №2

99% fulfills as it should... 1% - at step 3 or 4 I get an error from the binance 

> {"code":-2013,"msg":"Order does not exist."}

but at the same time the order in step 1 or 2 **is actually placed on the exchange!!!**

At first, I thought that this was happening because binance just didn’t have time to process my order, and I decided to add a cut in 3 seconds since I place a pending order and the speed of operations is not critical for me. But this error was repeated, and I thought I would make a delay after 2 steps 10 seconds - but this error didn’t go anywhere, the binance still says that he never had such an order, although the order is actually placed. 

Interestingly, here I already began to suspect that the problem is not on the exchange side, in 10 seconds any queue for placing orders will be processed even with a heavy load ...

if you create a new instance of the class and get a "nonexistent" one on it id then everything will be fine, the order data will be returned and no error will occur.

hmm I'm thinking ... it looks like some kind of strange bug ... 

I even find it difficult to say what is the reason because it is rather difficult to reproduce, but it spoils life - can you tell what could be the problem?

**Comment by StasToken** [comment]
I wrote earlier about something like that, but they fixed the error there
https://github.com/ccxt/ccxt/issues/6196

**Comment by kroitor** [comment]
Hi @StasToken !

> I want to say right away that this error cannot be received the first time; it falls 1:800

Can you make a short snippet of the actual code to reproduce the problem though? I mean, can you post the code to create the order and fetch it 800 times? Because this:

> 1. place an order №1
> 2. place an order №2
> 3. get order №1
> 4. get order №2

Does not really tell me anything, it depends on how you do that specifically (which methods are involved, which particular sequence of calls is executed, etc), not on what you're trying to do in general.

A few counter questions to you:

> although the order is actually placed.

1. Do you see that order in your history of orders with Binance? Do you see the id of that order? Can you fetch it now by the id?

2. Can you define the timeframe – when you first started seeing this behavior and whether you still see it now?

3. We obviously need all of the info from here (log it and dump it to a file) – verbose output, version numbers and the code itself of course:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

> I even find it difficult to say what is the reason because it is rather difficult to reproduce, but it spoils life - can you tell what could be the problem?

At this time without the above info from you it's hard to pinpoint the cause, but we've seen this earlier and it may actually be caused by the exchange engine itself. In order to tell the right answer, we need the above info from you.

**Comment by kroitor** [comment]
@StasToken can you plz paste the code to reproduce it?

**Comment by StasToken** [comment]
@kroitor - hi - sorry for the long answer, with this epidemic COVID-19 all plans went awry
I am busy with urgent tasks, and I don’t know when they will end, I will close this question for now, how will I have time I will make an example that can be reproduced and open the question.
Take care of yourself!

**Comment by kroitor** [comment]
@StasToken thx, you too! Hope to see you soon!
