### ISSUE TITLE
Binance Futeres incorrect errors instances

### ISSUE THREAD

**Issue by qmzik** [ccxt/ccxt#6699]
- OS: Windows 10
- Programming Language version: python 3.7
- CCXT version: 1.25.32

```
binance.fapiPrivateGetBalance()
```

```
it raises DdoSProtection error with the following text: binance temporary banned: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: 83.167.27.42"}
```

It is after I opened futures account, this should be Authentification error, not the DdoSProtection

Before I opened a futures account, it raises `Request Timeout` error, but should be `ExchangeNotAvailable` error

**Comment by kroitor** [comment]
Do you have the rate-limiting enabled?

**Comment by qmzik** [comment]
Yes

**Comment by kroitor** [comment]
Can you show the code to reproduce it (including the exchange instantiation), but without your keys?

**Comment by kroitor** [comment]
@qmzik that error can only be raised if you have been already authenticated successfully with this exchange instance, meaning that this keypair has worked on a program run, and then received a failure response from Binance later on the same run with the same keys. Which is often what you get when you don't rate limit the requests according to their weights.

**Comment by kroitor** [comment]
@qmzik let us know if this does not help or does not answer the question: https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1936

**Comment by qmzik** [comment]
My code without keys

client = ccxt.binance({'enableRateLimit': True, 'rateLimit': 250}
client.fapiPrivateGetBalance()

**Comment by qmzik** [comment]
I could not exceed the limit with one request and what about Request Timeout error before opening futures account?

**Comment by kroitor** [comment]
@qmzik that code works on my side (if that is a complete code snippet):

```Python
import ccxt
client = ccxt.binance({'enableRateLimit': True, 'rateLimit': 250}, 'apiKey': 'MY_KEY', 'secret': 'MY_SECRET'})
print(client.fapiPrivateGetBalance())
```

Please see the link posted above for the explanation of `{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: 83.167.27.42"}`. You can technically get the `DDoSProtection` on that error only if you have already authenticated successfully with that keypair at least once during that same program run. So, if you restart that code it should throw an `AuthenticationError`, unless there's some private request in between the exchange instantiation and your call to `client.fapiPrivateGetBalance()`. You can check which calls are being sent in verbose mode:

```Python
client = ccxt.binance({'enableRateLimit': True, 'rateLimit': 250, verbose: True})
client.fapiPrivateGetBalance()
```

Let me know if that still does not help.

> and what about Request Timeout error before opening futures account?

If it really was a `RequestTimeout` it could be thrown correctly (if the http response did not arrive in a default timeout of `10000` ms, which can also be adjusted). But it's hard to tell what it was, because we can't measure the timeout in the past at this point. It's hard to reproduce because we can't close the futures accounts to try reopening them.

**Comment by qmzik** [comment]
@kroitor 
Few steps to get Request Timeout error:
1. Create a new account on binance
2. Create API keys

Try to get fapiPrivateGetBalance and you will get a Request Timeout error, but it shouldn't be/ It is really hard to handle

3. Open Futures account, but not check the `Enable Futures` in API keys setting.

And then try it again, you will get DdoSProtection error, but it should be Permission error

**Comment by kroitor** [comment]
@qmzik i'll try to reproduce the above on my side and will get back to you with a followup on this, thx.

**Comment by qmzik** [comment]
Actually the description of DDoSProtection error is correct `"Invalid API-key, IP, or permissions for action`, but why it is a DDoS error? You have Authentification error in your errors file, it is more obvious

**Comment by kroitor** [comment]
@qmzik 

> Actually the description of DDoSProtection error is correct "Invalid API-key, IP, or permissions for action, but why is it a DDoS error? You have Authentification error in your errors file, it is more obvious

It is explained why it is `DDoSProtection` here:
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1936 (read that comment in the code for an explanation)

In most cases CCXT will throw `AuthenticationError` on that error, as you can see here:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L324

However, if you have already authenticated successfully with that api keypair – and you're sending further requests too fast – binance will ban you for a short perios of 10 minutes to an hour, and it will raise that error. Because your keypair is fine – it *cannot possibly be an `AuthenticationError` if you had it working with other private requests*. In that case CCXT will throw `DDoSProtection`, because that is the true cause of the confusing error that you're getting from Binance (because your keys are fine actually).

However, if you restart your code while being banned, CCXT should throw `AuthenticationError` since it did not see you successfully authenticating during a new run. If this is not what you are seeing and it still throws DDoSProtection on your first attempt to call a private method, it means Binance indicated a  HTTP 429 return code (too many requests). If you could post your full verbose output [as required here](https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help) it would easier to tell the exact cause. Can you please paste it?

**Comment by qmzik** [comment]
Error in `verbose: True`
```
'_Feature' object is not callable
```

**Comment by kroitor** [comment]
@qmzik jsut add the single quotes around it, since it's a dictionary key...

```
client = ccxt.binance({'enableRateLimit': True, 'rateLimit': 250, 'verbose': True})
client.fapiPrivateGetBalance()
```

**Comment by qmzik** [comment]
```
import ccxt

client = ccxt.binance({'enableRateLimit': True, 'rateLimit': 250, 'verbose': True})
client.fapiPrivateGetBalance()
```

Output:
```
'_Feature' object is not callable
```

**Comment by kroitor** [comment]
@qmzik that last one is a minor issue with the verbose print_function, i'll fix it shortly and will proceed to debugging this issue.

**Comment by qmzik** [comment]
@kroitor I solved the problem, thank you for the quick response!

**Comment by kroitor** [comment]
@qmzik thx for reporting back!

**Comment by pavan344** [comment]
I am also having same issue. I tried creating new API keys still same error on every new run
I have traded before using this account using bot. Now I have 3 bots each making request at interval of 3 minutes
My complete verbose response

Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': 'MYAPIKEY', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=1626281675073&recvWindow=5000&symbol=BTCUSDT&type=MARKET&side=BUY&newClientOrderId=x-R4BD3S82d65dfe7caea873003ee437&newOrderRespType=FULL&quantity=0.001992&signature=20de5a72736614af0fac44f4aeb3fe4f1501df39481a3bcad9dc8378c5b42f34

Response: POST https://api.binance.com/api/v3/order 401 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '70', 'Connection': 'keep-alive', 'Date': 'Wed, 14 Jul 2021 16:54:35 GMT', 'Server': 'nginx', 'x-mbx-uuid': 'e6a957ab-6edc-4ec6-849c-7ec0f8c73412', 'x-mbx-used-weight': '23', 'x-mbx-used-weight-1m': '23', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 f7ee847c2bd335d62c54ba4fa1347687.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'BOM52-C1', 'X-Amz-Cf-Id': 'REZIOw1aQbvkjQ34AtdwPmHFtbmXfawrPCC1XBmxaOn3zQtRV87fgw=='} {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
DDoSProtection binance temporary banned: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

**Comment by kroitor** [comment]
@pavan344 have you enabled the trading permissions on the key? Does it have IP whitelisting?

**Comment by pavan344** [comment]
@kroitor Never mind it was a permission issue. Thanks for all the support and have a great day!!
