### ISSUE TITLE
Kraken HTTP error 403 in load_markets

### ISSUE THREAD

**Issue by carloconnor** [ccxt/ccxt#6700]
Hi,

I have an issue that started happening this morning. When calling load_markets on Kraken, the call to zendeskGet205893708WhatIsTheMinimumOrderSize in fetch_min_order_amounts started giving a HTTP 403 forbidden error. It returns an HTML page asking to fill a CAPTCHA.

The code to reproduce:
x = ccxt.kraken({'enableRateLimit': True, "timeout": 10000})
x.load_markets()

The error:
Traceback (most recent call last):
  File "C:\...\site-packages\ccxt\base\exchange.py", line 566, in fetch
    response.raise_for_status()
  File "C:\...\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

I won't post the rest of the error because it's the complete HTML code for the page asking to fill a CAPTCHA.

I could reproduce this with the latest ccxt version (1.25.39) on 3 different machines.

Thanks!

**Comment by kroitor** [comment]
@carloconnor before it started happening – did you have the rateLimiting enabled? Because in your code to reproduce, it is missing...

**Comment by carloconnor** [comment]
Yes, sorry I didn't include it in the repro code, but my production code (that started failing this morning) creates the ccxt instance with the following params:
{'enableRateLimit': True, "timeout": 10000}

**Comment by kroitor** [comment]
@carloconnor i assume, your 3 different machines are in different subnets? It may be a Cloudflare protection issue. Does it work for you with a CORS proxy?

```Python
x = ccxt.kraken({
    'enableRateLimit': True, "timeout": 10000,
    'proxy': 'https://cors-anywhere.herokuapp.com/',  # last slash is critical
})
x.load_markets()
```

**Comment by carloconnor** [comment]
@kroitor Yes, the machines are in different subnets. One is home, one is work and one is a cloud machine.

I tried with the code you sent me and it gives me the same error.

I shoud also mention that all 3 machines run on Windows.

**Comment by Sebastiaan240** [comment]
I also have this issue since this morning. The problem is only with Kraken, not with other exchanges. It happens with all requests. Even on a machine that normally doesn't run any scripts with Kraken has the same problem, so it's not rate limits. The problem happens both on Ubuntu and on Windows.

My suspicion is that Kraken changed something changed something today and that this happens with all CCXT users now. It makes sense because the request that fails is the one that requests a regular web page and not the API.

For example, I tried this code:

import ccxt
kraken = ccxt.kraken()
kraken.verbose = True
kraken.fetch_order_book('BTC/USD')

The verbose shows it makes 2 succesful requests:

Request: GET https://api.kraken.com/0/public/Assets {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.kraken.com/0/public/Assets 200    [Very long response]

Request: GET https://api.kraken.com/0/public/AssetPairs {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.kraken.com/0/public/AssetPairs 200    [Very long response]

Response: GET https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- 403 {'Date': 'Mon, 30 Mar 2020 12:58:17 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'CF-Chl-Bypass': '1', 'Set-Cookie': '__cfduid=d234b95249a3592885c0fc4da4f3982361585573097; expires=Wed, 29-Apr-20 12:58:17 GMT; path=/; domain=.support.kraken.com; HttpOnly; SameSite=Lax', 'Cache-Control': 'no-cache', 'X-Frame-Options': 'SAMEORIGIN', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '57c20055ecf19f1b-AMS', 'Content-Encoding': 'gzip'} <!DOCTYPE html>
<html lang="en">

Followed by a huge error showing a RECAPTCHA page in multiple languages.

**Comment by kroitor** [comment]
@carloconnor yep, I can confirm – getting it too now. The problem is – Kraken API will not return the order limits from the API, and the only page we could scrape that info from – was that zendesk page. Of course, Kraken does not guarentee that page to work forever, because it's not a part of the API. But at the same time, there's no other way to fetch order limits programmatically. Today the zendesk page seems to be causing trouble, being half unresponsive, half blocked by that captcha... 

We are searching for a workaround at this point, probably will make this endpoint call optional, with limits temporarily undefined...

**Comment by kroitor** [comment]
Please update to CCXT 1.25.40 in 15 minutes. That endpoint is now disabled by default. If you want to reenable it, use this:

```Python
x = ccxt.kraken({
    'enableRateLimit': True
    'options': {
        'fetchMinOrderAmounts': True,
    }
})
x.load_markets()
```

Note, however, that min limits are now arbitrary and you should take care of them on your side until Kraken fixes this in some way.

**Comment by carloconnor** [comment]
@kroitor Thanks a lot for such a fast response and fix!

**Comment by kroitor** [comment]
@carloconnor no problem, thx for your feedback! Actually, this isn't really a fix, just a workaround... Found another zendesk page for limits here: https://support.kraken.com/hc/en-us/articles/360001389366-Price-and-volume-decimal-precision... But it's the same zendesk, doesn't really work. And they still have no API endpoint for that info... Which makes the life of a trader harder.

**Comment by carloconnor** [comment]
FYI I was about to deploy the changes in my last prod environment and it started working on its own again. It seems like whatever Kraken had changed this morning that made the request to their support page fail is now changed back to its previous state (and the page can be loaded again from code). Not sure if you want to do something with that but I thought I'd let you know.

**Comment by kroitor** [comment]
@carloconnor thx! Will keep an eye on it and will restore it if it's stable...

**Comment by iiiclaw** [comment]
It seems to be working again without the workaround

**Comment by kroitor** [comment]
Kraken's official answer: 

> we are aware of the recent issue that CCXT experienced when a security change to our support pages prevented the minimum order sizes from being retrieved via our support pages. Our REST API developers are in the process of adding the minimum order sizes to the REST API AssetPairs endpoint, which would make the minimum order sizes available more efficiently (and more reliably). We do not yet have an expected availability date for this update, but I will keep track of the progress, and let you know when more information is available.

**Comment by carloconnor** [comment]
That's good news, thanks for the follow-up!
I started having the issue again this morning so for now I've simply set the option manually to avoid loading the minimum order sizes.

**Comment by kroitor** [comment]
> I started having the issue again this morning so for now I've simply set the option manually to avoid loading the minimum order sizes.

Yep, you're not alone: https://github.com/ccxt/ccxt/issues/6795
Min limits are broken again for everyone...

To other people who may encounter this issue: In the meantime, you can workaround it, by setting `fetchMinOrderAmounts` option to `false`. 

```Python
exchange = ccxt.kraken({
    'enableRateLimit': True,
    'options': {  # ←--------------------- inside 'options' subkey
        'fetchMinOrderAmounts': False,  # ←---------- set to False 
    }
})
```

That way you will effectively lose the information about the minimal limits, but the other functionality will keep working.
