### ISSUE TITLE
Duplicate code in parseTicker/parseOrder

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#6713]
In the exchange specific `parseTicker`/`parseOrder` is a lot of duplicate code, because they calculate entires of the unified order structure, which is not provided by the original exchange response.
(for `parseTicker` e.g. change, percentage, for `parseOrder` e.g. average)

Does it enhance the code quality, if we move all of these quirks to a method in the base exchange class, so the exchange specific classes only save in the unified structure, what is provided by the exchange and then call e.g. `return this.calculateParsedOrderProperties({ ... })`

I think, it would reduce copy/pasted quirks and enhance code quality, because one exchanges profits from enhancements made for another exchange.
My concern is, that this single function would get to heavy and not maintainable.
e.g. one exchange has provided `last` and `previous` to calculate `change` and `percentage`, another exchange has provided `previous` and `percentage` to calculate `change` and `last` (probably unrealistic), but my point is, when to check for which property could be a problem and after calculating one property, we would need to check again, if we can calculate another.

Any thoughts on this?

**Comment by kroitor** [comment]
> Does it enhance the code quality, if we move all of these quirks to a method in the base exchange class, so the exchange specific classes only save in the unified structure, what is provided by the exchange and then call e.g. return this.calculateParsedOrderProperties({ ... })

To my mind – yes, of course it does. The less duplication, the fewer points of failure, the better in general... However, it has to be done carefully, i mean upon a massive change we can run into unexpected issues here and there, so it is better if we approach it step by step, say, `parseTicker` first, `parseTrade` second, then `parseOrder`, and so on... one exchange at a time with heavy testing.

> I think, it would reduce copy/pasted quirks and enhance code quality, because one exchanges profits from enhancements made for another exchange.

I agree with that. We are already working on the `safeSymbol` method that is also designed to reduce duplication, since in many cases market recognition is a) reusable across methods b) reusable across exchanges.

> My concern is, that this single function would get to heavy and not maintainable.
e.g. one exchange has provided last and previous to calculate change and percentage, another exchange has provided previous and percentage to calculate change and last (probably unrealistic), but my point is, when to check for which property could be a problem and after calculating one property, we would need to check again, if we can calculate another.

Yeah, we have the same concerns as well. There is a risk of overengineering it. However, again, to my mind it depends on how we approach the task. If we move from lower levels upwards, through the architecture – we should end up with a good design naturally. Suppose you were to design a big method that is trying to account for all possible variations of defined and undefined values to deduce as many of them as possible from a given dataset. You would most likely have some other lower-layer base calls inside that method. For example, calculating simple cost from amount and price is a utilitarian function that could be reused in various methods. Also, calculating, say, `amount`, `remaining` and `filled` for the order can be wrapped in a standalone lower-layer method. We could try and start from there... 

Also, there may be an alternative less intrusive way to solve this. We currently have `this.sum` which is _"safe"_, meaning that it can sum up `undefined/None/null` values. If we also had _"safe"_ `this.subtract`, `this.multiply`, `this.divide` we would have less duplication as well.
