### ISSUE TITLE
kuna: aggregated orderbook & design issue

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#674]
While testing ccxt on kuna I noticed that kuna returns orderbook on a per-order basis while other exchanges that I know aggregate orderbooks by price-level.

I implemented an aggregator to bring kuna's orderbook in sync with others but while submitting a PR noticed that you also have `fetchL2OrderBook` method which is nowhere used.

With this method in mind, I'm a bit uncertain about unification.

As I see it the idea was to provide a user with a choice of getting aggregated OB with `fetchL2OrderBook` (that what most exchanges return) or detailed OB with `fetchOrderBook` (on that exchanges that support it).

The issue is that `fetchOrderBook` in its current form *usually* returns aggregated data, not detailed data. It's not `ccxt` fault, it just exchanges that aggregate data for us.

`fetchOrderBook` became kinda of default method for all exchanges while if we were to stick to the initial design we would need to provide it only for some of them (like we do with `fetchTickers`).

Now getting back to the issue.

My client code depends on aggregated data and in order to handle kuna I would need to switch it to `fetchL2OrderBook`. At the same time, if I switch to it then it would aggregate orderbooks for other exchanges (despite they are already aggregated) bringing unnecessary overhead.

I see two approaches of how to make it more elegant:
- if you don't aware of any exchanges that provide detailed orderbooks I will make `fetchOrderBook`to  return aggregated data for kuna
- if there are exchanges that return detailed orderbooks I would implement new `fetchDetailedOrderBook` for them (and for kuna) and rework `fetchOrderBook` to return aggregated data

**Comment by kroitor** [comment]
First of, thanks for opening this! And for the very detailed feedback!

> you also have fetchL2OrderBook method

Yep, this is covered briefly here: https://github.com/ccxt/ccxt/wiki/Manual#order-book--market-depth (in the end of the paragraph).

> which is nowhere used

Who said that ? ;) You mean, anywhere inside the library )

> aware of any exchanges that provide detailed orderbooks

I know some of them do return detailed orderbooks (non-aggregated) per user request, but at the same time I know all of them encourage users not to use L3 orderbooks, because those requests are much slower in general (on exchanges' side). For example, GDAX accepts a level of depth, and can return an orderbook containing order ids, a few other exchanges also allow that. I'd say approx 10-15% of all exchanges have that functionality, the rest of them return L2.

> I see two approaches of how to make it more elegant

Both of your suggested approaches are very good, I'm having a little difficulty deciding on which one is better... I think, it would be ideal if we meet the following requirements:
- Have a default behaviour that is consistent. I think having fetchOrderBook return the exchanges' default is very fine.
- Be backward compatible, again this is covered by current fetchOrderBook.
- Be able to specify precisely L2 or L3 (your requirement is very reasonable, this is why we had to add the fetchL2OrderBook in the first place, our own needs are the same).

So, from here, this whole enhancement move can be done in a few small steps:
- add fetchL3OrderBook
- make fetchOrderBook call fetchL2OrderBook by default
- make fetchL2OrderBook from fetchL3OrderBook only if there's no way to access any orderbook other than L3

Now, a showstopper: some exchanges can return non-aggregated orders in L2 aggregated orderbooks (price duplicates appear in their output), so we decided to aggregate on client side anyway, not relying on the exchange. Don't know if it makes any sense to you, but we've seen all sorts of shit within many exchanges, and we don't trust their madskillz at all. 

So, maybe we should enhance our tests first to determine the exact capabilities and inconsistencies of output orderbooks for all exchanges to collect the stats and decide based on that? If your goal aside from having the required level of aggregation is to minimize the load, we will have to determine which of all exchanges are consistent and trustworthy, and which of them aren't consistent and still require re-parsing and re-aggregation of their output. Also, a significant addon to this: we never had a performance issue on our side, because most of the time those are still faster than HTTP reaction/roundtrip times. So, maybe, you're trying to optimize prematurely, if you haven't run into a bottleneck anywhere in your code yet. 

Let me know what you think of the above?

**Comment by mkutny** [comment]
@kroitor, thanks for this elaborative (as usual) answer!

I swear I read the Manual not a single time but apparently missed the L1/L2/L3 explanation.

Now I've got the big picture and almost ready to move ahead.

I will do a `fetchL3` for kuna but still not sure what LoD should its `fetchOrderBook` return.

> Have a default behaviour that is consistent. I think having fetchOrderBook return the exchanges' default is very fine.

As I've got from your explanation 10%-15% of exchanges *can* return L3 per user request but this implies that they don't do it by default, right? If this is true then kuna will be the only one standing out and everyone would consider `fetchOrderBook` to be de-facto standard for fetching L2.


> Make fetchOrderBook call fetchL2OrderBook by default.

And this statement makes me think that you too want `fetchOrderBook` to return L2?


> Actually, in terms of method call chains, I'm not sure which way is better: should fetchL2OrderBook call fetchOrderBook or vice versa... This is still an open question.

Basically, as I see it all boils down to what you want `ccxt` users to expect from `fetchOrderBook`. 

Until now I was expecting it to return L2 by default. But at the same time from what I read from other parts of your answer it might be interpreted as you expect users to use `fetchL2/L3` while reserving `fetchOrderBook` for internal use (like you do with `parseOrderBook`, for example). What's the case?


>  Also, one more significant point: we never had a performance issue on our side, because most of the time those conversions are still faster than HTTP reaction/roundtrip times. So, maybe, you're trying to optimize prematurely, if you haven't run into a bottleneck anywhere in your code yet.

Well, I didn't do any profiling but I bet that HTTP roundtrip times are eating up all the benefits. At the same time:
- you're going to switch to WS, so roundtrip times will shorten
- you told me just a few days ago that you're rewriting your `map` calls because plain iterations are faster...
- I have a bad sleep when I know there is an extra unnecessary loop in the code, really )

But basically, we can put the performance issues aside for now. I agree that they are not really important at the moment.

**Comment by kroitor** [comment]
> I will do a fetchL3 for kuna but still not sure what LoD should its fetchOrderBook return.

I think, it should return the default for Kuna, so, that is L3. So, yes, please go ahead and implement this whatever way you need it for Kuna, because, guess what, you are the user ) So, it's up to you to decide ) If I were to solve this question, I'd ask yourself ) I have less experience with that particular exchange than you do, obviously.

> Until now I was expecting it to return L2 by default. But at the same time from what I read from other parts of your answer it might be interpreted as you expect users to use fetchL2/L3 while reserving fetchOrderBook for internal use (like you do with parseOrderBook, for example). What's the case?

Practically, it's always the same endpoint, so, yes, I believe, we should have assign fetchOrderBook to be an *internal* method for fetching an order book of arbitrary depth, and then have fetchL2OrderBook / fetchL3OrderBook for the userland (those two will call fetchOrderBook internally). I will also edit the Manual to prioritize L2/L3 methods.

> Until now I was expecting it to return L2 by default. But at the same time from what I read from other parts of your answer it might be interpreted as you expect users to use fetchL2/L3 while reserving fetchOrderBook for internal use (like you do with parseOrderBook, for example). What's the case?

Initially, we also thought of returning L2 by default... but now it seems that we better have fetchOrderBook return exchanges' default (L2 for most of them, L3 for Kuna), and have the two methods (L2/L3) for precise control, if the user needs to specify that.

Let me know if I can help with anything and feel free to ask if you still have some remaining questions. Thanks!

**Comment by kroitor** [comment]
Reference: https://github.com/ccxt/ccxt/pull/676

**Comment by mkutny** [comment]
I'm still a bit uncomfortable with the base class' `fetchL2OrderBook` working on a child's `fetchOrderBook` unconditionally (because the former one never knows what LoD the latter one returns)... But that's ok for now.

**Comment by mkutny** [comment]
Thanks!

**Comment by kroitor** [comment]
> because the former one never knows what LoD the latter one returns

Yeah, but, at the same time, we can override fetchL2OrderBook per-exchange, right? Having that option should do the job for now and if we encounter a specific case, we can rework it further... Or do you suggest to change the base fetchL2OrderBook somehow? If you do mean that we need to edit it, then, why not, let's do it.

**Comment by mkutny** [comment]
I just feel that the current implementation does not follow the new design and at the same time I can't come up with any meaningful proposal of how to address this.

But, as you mentioned it does its job for now so I guess I'll leave it as is.

**Comment by kroitor** [comment]
> current implementation does not follow the new design

Mm... why not? It does re-aggregate and re-sort them, so, I believe it returns L2 whatever the input, doesn't it? I may be missing something, can you please elaborate on this a little more?

**Comment by mkutny** [comment]
> It does re-aggregate and re-sort them, so, I believe, it returns L2 whatever the input, doesn't it?

Yeah, it does work, that's why I think we can leave it as is.

I'll elaborate on it as you asked but mind that what will follow is just my subjective opinion (or rather a preference) on how it might have been done differently. And when I say differently it neither means that it's "the right way" to do nor that the current way is a "wrong way" to do.

The implementation we basically ended up with could be summarised as:
```
// base class: provides default method
fetchL2() {
  let unknownLevel = fetchOB();
  let l2 = aggregate(unknownLevel);
  return l2;
}

// exchange class: provides fetchOB and might provide fetchL2()
// if an exchange implementation knows that it can fetch L2 directly from the exchange then it overrides default fetchL2()
```

At the same time, if we implemented this design from scratch it might look somewhat different:
```
// base class: provides helper method
elevateL3toL2(orderbook) {
  return aggregate(orderbook);
}

// an ordinary exchange class
fetchL2() {
 // fetch from an exchange
}

// kuna, or any implementation that receives a 'dirty' orderbook and wants to clean it up
fetchL2() {
  return elevateL3toL2(fetchL3());
}
```

The difference is that in the latter case a particular exchange implementation is explicitly responsible to know what it receives from an exchange while in the former (somewhat relaxed) case an exchange implementation might just do not care and this will lead to a slight performance penalty in case it happened to receive L2.

P.S. I need to excuse for the delays with my answers, I've got an occasional access to my comp this weekend.

**Comment by kroitor** [comment]
@mkutny that penalty could be addressed if fetchL2OrderBook did not re-aggregate the orderbook, when a special flag is set in method arguments or even exchange-wide. We can add a flag to exchange base class, something like `skipL2AggregationWarningDangerAllOfThat = false` (by default). You would set it to true in your case for a slight performance gain if you are sure your exchanges behave well or if you are fine risking some orderbook inconsistencies for speed (like those mentioned above). A `flag` solution also seems to be an easy way out of this dilemma, doesn't it?
