### ISSUE TITLE
How to specify before time in params 

### ISSUE THREAD

**Issue by crossx4real** [ccxt/ccxt#6775]
- OS: Win 10
- Programming Language version: node js
- CCXT version: 1.19.74

i'm trying to zero-in on a particular trade that may have happen in a specific time frame. using the fetchTrades (symbol, since = undefined, limit = 50, params = {})

how would you configure params if you wanted to specific a before time?

for since: i'm using exchange.milliseconds() but i want to narrow the result as much as possible

**Comment by kroitor** [comment]
> how would you configure params if you wanted to specific a before time?

The "before" argument is not unified since very few exchanges actually support precise date ranges for public trades. So, if you want to specify an override for it, you should first look it up in the exchanges' endpoint description in the API docs for the exchange in question, and then use params overrides as explained in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```JavaScript
params = {
    // your params here, if the exchange supports them
}
fetchTrades (symbol, since, limit, params)
```

Let us know if the above does not answer the question. Feel free to reopen it or just ask further questions, if any.
