### ISSUE TITLE
How to fetch selling price and not ask price

### ISSUE THREAD

**Issue by lRninG9977** [ccxt/ccxt#6814]
How can I fetch the selling price of a cryptocurrency?
If I fetch the price of BTC/EUR market I get the "ask price".. What about the selling price?
On Binance, my balance is calculated as "btc_balance*selling_price", how can I fetch the selling price to calculate my effective balance in EUR?
Thanks!
![Cattura](https://user-images.githubusercontent.com/63800198/79500750-3fc54d00-802d-11ea-9a73-0cf2c9b9aec4.PNG)

**Comment by kroitor** [comment]
> How can I fetch the selling price of a cryptocurrency?

First of, there's no such simple thing as a universal _"selling price"_. The price you have depends on how much you're buying or selling, because of the market depth.

You want to understand how trading with financial markets works, since your question is not related to CCXT or Binance at all. This is more related to your understanding of what is a _bid_, an _ask_, the _market depth_ and how they affect the _orderbook_ that defines the market value of your assets, and how that is related to buying or selling.

- https://www.google.com/search?q=orderbook+tutorial
- https://www.investopedia.com/terms/o/order-book.asp
- https://www.thebalance.com/trading-definitions-of-bid-ask-and-last-market-prices-1031026
- https://support.kraken.com/hc/en-us/articles/115000364388-Trading-glossary

In short:
- bid = the price that someone is willing to give you for your BTC (when you sell BTC)
- ask = the price that someone is willing to get from you for their BTC (when you buy BTC)

The orderbook consists of multiple levels of bids and asks, sorted by best prices in both directions. So, if you want to calculate the value of your BTC in EUR with Binance's BTC/EUR market, then the algorithm is rather simple:

1. Check the first bid from the orderbook.
2. Check the volume of the bid.
3. If the volume of the bid covers your remaining assets in BTC entirely – multiply your BTC assets by the first bid price (aka _"market price"_) then proceed to step 7.
4. If the volume of the first bid does not cover your remaining assets in BTC entirely – multiply bid price by bid volume and remember the intermediary total.
5. Subtract the bid volume from your BTC assets.
6. Check the next bid and repeat the process from steps 2-5.
7. Sum the intermediary totals from steps 3-4 – the result is your value of BTC in EUR.

↑ The above algorithm is using the market depth to calculate the best value of EUR that you can get for your BTC with Binance.

Let me know if the above does not answer the question.

**Comment by lRninG9977** [comment]
Omg, such a perfect answer: precise, simple, exhaustive... Thank you so much, I will try to implement this tomorrow.
Have a nice evening!

**Comment by kroitor** [comment]
@lRninG9977 what's your programming language?

**Comment by lRninG9977** [comment]
It's Python, I'm trying to implement my own portfolio for my cryptocurrencies and trades... :)

**Comment by kroitor** [comment]
@lRninG9977 

```Python
import ccxt

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # as required and explained in the Manual
})

balance = exchange.fetch_balance()

your_balance = balance['total']['BTC']
remaining_balance = your_balance
orderbook = exchange.fetch_order_book('BTC/EUR')
cost = 0

for bid in orderbook['bids']:
    if remaining_balance < bid[1]:
        cost += bid[0] * remaining_balance
        break
    else:
        cost += bid[0] * bid[1]
    remaining_balance = max(0, remaining_balance - bid[1])


print('Your', your_balance, 'BTC is worth', cost, 'EUR')
```

**Comment by lRninG9977** [comment]
Thank you very much!!!
I will donate something to the BTC wallet :)
On Binance I see the exact same value but with 2€ of difference... If I use `cost-2` the balance is the same. Is this normal, due to market fluctuation? I'm refreshing both balances at the same time.

**Comment by kroitor** [comment]
> On Binance I see the exact same value but with 2€ of difference... If I use cost-2 the balance is the same. Is this normal, due to market fluctuation? I'm refreshing both balances at the same time.

Nope, that depends on how Binance website calculates your worth. In general the exchanges don't calculate the precise value of your assets. Instead they give you a rough estimate. They just multiply your BTC value by the first bid price and stop there. That gives the rough market value of your assets in EUR, but it is not precise.

So, a simpler calculation will most likely yield the same result as Binance:

```
import ccxt
import sys


exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # as required and explained in the Manual
})


balance = exchange.fetch_balance()
orderbook = exchange.fetch_order_book('BTC/EUR')
total = orderbook['bids'][0] * balance['total']['BTC']
print('Your', balance['total']['BTC'], 'BTC is worth', total, 'EUR')
```

Yet, again, the above is not precise, it's a rough estimate. So, if you try to actually get that EUR for BTC – you will get less EUR eventually.

Apart from that, I think, neither Binance nor my calculation above accounts for the fees. Because when you sell BTC for EUR – you won't get your EUR value – you will get value-fee. That should be also factored in.

**Comment by kroitor** [comment]
P.S. And, yes, the prices on Binance actually fluctuate a lot, so, launching any of these script multiple times will yield slightly fluctuating totals.

**Comment by lRninG9977** [comment]
Everything clear. Don't know how to thank you for your kindness and your time :)
The second script gives me almost the same value as the first one, maybe because the balance is low (300€)? I used this as total = orderbook['bids'][0]**[0]** * balance['total']['BTC']

**Comment by kroitor** [comment]
> maybe because the balance is low

No, if the difference is very-very small, that is because Binance calculated your worth at a different time (a fraction of a second earlier or a fraction of a second later).

If your difference is exactly equal to 0.1% of your total – that is due to fees.

**Comment by lRninG9977** [comment]
Ah ok I understand. Thank you so much again!!!

**Comment by kroitor** [comment]
@lRninG9977 no problem )

Also, note that the correct sign should be fixed above (`<=` instead of `<`):

```
    if remaining_balance < bid[1]:
```
↓
```
    if remaining_balance <= bid[1]:
```

**Comment by lRninG9977** [comment]
Nice. I fix it :)
