### ISSUE TITLE
Open positions Cache purge

### ISSUE THREAD

**Issue by jimmi19** [ccxt/ccxt#6828]
Hello,

When i cancel all open positions in bitmex and then call the `exchange.private_get_position` it still maintains the previous position. I have checked visually on bitmex and the position was closed correctly. Is the position cached? if so is there a purge function like for orders?.

Thank you in advance

**Comment by kroitor** [comment]
> it still maintains the previous position

I think, your synthetic position is simply a cumulative result of all your orders. 

Placing an order means "entering a position", placing an opposite order means "exiting/closing a position". The position starts existing since you've signed up with the exchange and it continues to "exist" after you "close" it. It is still there, with a status that shows how deep you're into it. 

Put even more simply: if the sum of your orders yields "0" – then you're not in position. If it yields a value different than 0 – then you're in either a long or a short position. You should devise your current status from the position's fields, which show you whether you're in it or not, and by how much.

> Is the position cached? 

I don't think so.

> if so is there a purge function like for orders?.

Nope, not for BitMEX.

Let me know if I'm missing something or if the above does not answer the question.

**Comment by jimmi19** [comment]
Hmm ok thanks I think I understand. Tomorrow I'm going to take a deeper look into the open positions fields and I will get back to you with what I find. But thanks for the rapid response really appreciate it.

**Comment by kroitor** [comment]
@jimmi19 sure, let us know if you encounter any difficulties. Closing it for now, if you don't mind. Feel free to reopen it or just ask further questions if any.
