### ISSUE TITLE
Timestamp for request outside recvWindow - it's back

### ISSUE THREAD

**Issue by lRninG9977** [ccxt/ccxt#6832]
Hi. 
I just read all previous posts about this issue, but still cannot solve it...
4-5 days ago everything was working well.
I did not change my code... Maybe Binance's problem?
When I run `exchange.fetch_balance()`
```
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
```

**Comment by kroitor** [comment]
Hi!

What exactly have you tried, what's your OS, programming language version, ccxt version?

We will always ask for your code to reproduce it and your verbose request/response:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by lRninG9977** [comment]
You right. Here some info:
I tried printing: 
`Exchange UTC time: 1587562576360 2020-04-22T13:36:16.360Z
Your UTC time: 1587562568117 2020-04-22T13:36:08.117Z`
As you suggested in another post.
I'm on Windows 10 - Python 3

The code is `balance = exchange.fetch_balance()`
generating this error:
`ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}`

**Comment by kroitor** [comment]
> I tried printing:
> Exchange UTC time: 1587562576360 2020-04-22T13:36:16.360Z
> Your UTC time: 1587562568117 2020-04-22T13:36:08.117Z

From here you can see that your time difference with binance is more than 5 seconds. Whereas the default value for recvWindow in 5 seconds (5000 milliseconds). This is the cause of the error response from Binance.

You can mitigate it in two ways:

- Either configure your Windows system to synchronize the system clock every 10 minutes. Just enabling time sync in Windows does not fix it, because Windows will only synchronize the time once every 24 hours or so, which is not enough. So you need to really-synchronize the time, as explained here: 
  - https://github.com/ccxt/ccxt/issues/850
  - https://github.com/ccxt/ccxt/issues?q=recvWindow
- Or enable the adjustment for time difference using CCXT, as shown in the duplicate issues:
  - https://github.com/ccxt/ccxt/issues/936#issuecomment-425247573

```Python
exchange = ccxt.binance({
    'options': {
        'adjustForTimeDifference': True,
    },
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
```

Let us know if that does not help.

P.S. For the future, please, use [github markdown](https://guides.github.com/features/mastering-markdown/) for readability when pasting code or text. Don't confuse triple backticks (&#096;&#096;&#096;) with a single backtick (&#096;). Wrap your code or text with triple backticks as shown below (this is also shown in any issue template upon opening it – you should really follow what's written in the template):

&#096;&#096;&#096;Python
YOUR_CODE_HERE
&#096;&#096;&#096;

&#096;&#096;&#096;
YOUR OUTPUT HERE
&#096;&#096;&#096;

**Comment by lRninG9977** [comment]
Ok, I solved using the `adjustForTimeDifference`. Thank you so much for your help.
Yes, you are right, in future I will follow the template.
Thanks again!

**Comment by yemenpoint** [comment]
try this 
```
       const exchange = new ccxt.pro.mexc({
            'apiKey': "",
            'secret': "",
            "milliseconds": () => new Date().getTime() - 2000,
        });
```
this works for me 
this issue closed but this is another solution
