### ISSUE TITLE
Unchecked null array values causing errors when an order has no associated trades

### ISSUE THREAD

**Issue by ron7684** [ccxt/ccxt#6835]
It looks like there is an issue with Kraken in `parse_order()`

The `order` dict does not contain a key for `'trades'` if there are no trades which causes `safe_value()` to set `rawTrades = None` in kraken.py line 1042. This is then passed to `parse_trades()` which calls `to_array(None)` to set `array = None`. Finally, in exchange.py line 1607, using this `None` value causes `[self.extend(self.parse_trade(trade, market), params) for trade in array]` to raise a TypeError.

I've hacked a fix in by having `to_array()` return an empty list on null input but I'm not sure if this is a valid solution for the whole project.

**Comment by kroitor** [comment]
Hi @ron7684 ! First of, thx for reporting this bug! 

> I've hacked a fix in by having to_array() return an empty list on null input but I'm not sure if this is a valid solution for the whole project.

Unfortunately, not, since an empty array means "no trades fur sure", whereas an undefined/None/null value for trades means "we don't know if there were trades or not in this case". The latter is the correct behavior for Kraken parseOrder. Thus returning an empty array there will change the semantics.

I've uploaded a fix to it (the new build 1.26.76 will arrive in 15 minutes), so it will not crash and will return no value for trades when missing in the response. Had to close your PR #6836 for that reason. In any case, we really appreciate your help and feedback, and we will be happy to see more PRs from you in the future. Thx again!
