### ISSUE TITLE
binance.fapiPrivateGetIncome gives empty array

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#6852]
Hi, I can't get data with this endpoint: `binance.fapiPrivateGetIncome( )`, it shows empty array..
`await binance.fapiPrivateGetIncome ( {  symbol : 'BTCUSDT'     } ) `

Nodejs, latest update

**Comment by kroitor** [comment]
Hi! Can you plz show your verbose request/response?

**Comment by Gennttii** [comment]
`

fetch:
 binance GET https://testnet.binancefuture.com/fapi/v1/income?timestamp=1587897961045&recvWindow=5000&symbol=BTCUSDT&limit=10&signature=88ffe7679518f35c0c21c419fffeca7b93b513c17f1e753944280159478c5a55
Request:
 { 'X-MBX-APIKEY':
   '0fa3f792d2859487616ea404e62a06b0c5935ae6d78d3d022c8d495fdea593d8' }
 undefined

handleRestResponse:
 binance GET https://testnet.binancefuture.com/fapi/v1/income?timestamp=1587897961045&recvWindow=5000&symbol=BTCUSDT&limit=10&signature=88ffe7679518f35c0c21c419fffeca7b93b513c17f1e753944280159478c5a55 200 OK
Response:
 { 'Access-Control-Allow-Credentials': 'true',
  'Access-Control-Allow-Headers': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  Connection: 'keep-alive',
  'Content-Length': '2',
  'Content-Type': 'application/json',
  Date: 'Sun, 26 Apr 2020 10:46:01 GMT',
  Server: 'Bengine',
  Via:
   '1.1 b71ecd1018f21aabbfe290f634d31212.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'rEam2WoZu9JiNQIKYy90EB_LmvtdFhSINGfwv1_y0r3ar1Duv4Yrhw==',
  'X-Amz-Cf-Pop': 'SOF50-C1',
  'X-Cache': 'Miss from cloudfront',
  'X-Mbx-Used-Weight-1m': '20',
  'X-Response-Time': '26ms' }
 []

[]`

**Comment by kroitor** [comment]
@Gennttii Basically, what you get is the direct response from the exchange as is. This, if you get an empty result, it literally means "your futures API income response is empty". That could be due to no trades with the futures account with that specific symbol, or for other reasons. I'd recommend to reach out to Binance for an explanation of what it means.

**Comment by Gennttii** [comment]
Yes I have many many trades and I trade with this symbol only `'BTCUSDT' ,` I can get my trades with other endpoints like `fapiPrivateGetUserTrades,`, but I need to get all fees paid. Fees, commission , funding, do I get all these with `fapiPrivateGetIncome ()`? And forgot to tell this is testnet.

**Comment by kroitor** [comment]
> Fees, commission , funding, do I get all these with fapiPrivateGetIncome ()?

You should be able to get those from the unified [`fetchMyTrades` method](https://github.com/ccxt/ccxt/wiki/Manual#personal-trades-1) when used with the `defaultType: 'future'` options. 

> And forgot to tell this is testnet.

I'd still recommend to reach out to Binance tech support on this – it may be related to the thresholds of the testnet itself. Obviously, we can't "make up" that data, because you're talking to the exchange directly. Let us know if that does not help. Feel free to reopen it if needed or just ask further questions if any.
