### ISSUE TITLE
how to rewrite fetchOHLCV  or   add private method to ccxt

### ISSUE THREAD

**Issue by homily** [ccxt/ccxt#6871]
Hi Kroitor
Thanks for creating this wonderful python module.
I'm extensively using this module for my algos.

Now I have some problems ，it have been bothering me

when i use ccxt.okex.fetchOHLCV in future，it just return 300 items

so ，I wrote a method to get it in a loop ,get more just change "limit".

```
def fetchOHLCV(Symbol,Time,From=None,Limit=None):
    exchange=ccxt.okex({'hostname':'okex.me'})  #how to use'self.fetchOHLCV()'
    row= (300 if (Symbol[-6:].isdigit()==True) else 200)

    if (Limit==None or Limit<=row):
        data_raw= exchange.fetchOHLCV(Symbol,Time,From,Limit)

    else:
        m=1
        h=60
        d=24*60
        w=7*24*60
        x=int(Time[:-1])*eval(Time[-1]) 
        
        frequency=(Limit+row-1)//row 
        data_raw=[]
        for i in range(frequency, 0, -1):
            start = exchange.iso8601(int(time.time()-x*60*row*i)*1000)
            end   = exchange.iso8601(int(time.time()-x*60*row*(i-1))*1000)
            data  = exchange.fetchOHLCV(Symbol, Time, None, None, {'start': start, 'end': end})
            data_raw = data_raw+data

        if (Limit%row!=0):
            data_raw=data_raw[-Limit:]
            
    return(data_raw)      
```

But every time I use it, I need to re-reference it, and most importantly,
 I ca n’t write it to an internal method

it'must use 'exchange=ccxt.okex({'hostname':'okex.me'})' in it
if i change different exchange it will be wrong

so how can i get  Class attribute or private attribute 
To judge different exchanges

so,i want try it  @staticmethod or classmethod  to rewrite fetchOHLCV method
```
okex=ccxt.okex()
okex.fetchOHLCV=fetchOHLCV
```
but i can't use self.fetchOHLCV in my method

final
i want to create 'plus.py' and create  some def 
it can  rewrite fetchOHLCV  in different exchange 
when i use new file,  just  import ccxt and import plus.py 
it well be funy

wow，  my python and english is not very good ，
can you help me？

**Comment by homily** [comment]
**hi，kroitor  ！
I have an idea**

### first   new one   'okex_plus.py'

```

import time


def fetchOHLCV_more(self,Symbol,Time,From=None,Limit=None):
    row= (300 if (Symbol[-6:].isdigit()==True) else 200)
    if (Limit==None or Limit<=row):
        data_raw= self.fetch_ohlcv(Symbol,Time,From,Limit)
    else:
        m=1
        h=60
        d=24*60
        w=7*24*60
        x=int(Time[:-1])*eval(Time[-1]) 
        
        frequency=(Limit+row-1)//row 
        data_raw=[]
        for i in range(frequency, 0, -1):
            start = self.iso8601(int(time.time()-x*60*row*i)*1000)
            end   = self.iso8601(int(time.time()-x*60*row*(i-1))*1000)
            data  = self.fetch_ohlcv(Symbol, Time, None, None, {'start': start, 'end': end})
            data_raw = data_raw+data
        if (Limit%row!=0):
            data_raw=data_raw[-Limit:]
            #RAW= RAW.tail(Limit).reset_index(drop=True) 
    return(data_raw)       

```

### in my   program   i  use it.

```
import ccxt
from okex_plus import *
import pandas as pd
import types

okex=ccxt.okex({'hostname':'okex.me'})
okex.fetchOHLCV = types.MethodType(fetchOHLCV_more, okex) #use MethodType update fetchOHLCV
data = okex.fetchOHLCV('BTC-USD-200626','15m',Limit=600)

M15=pd.DataFrame(data)
M15.columns = ['time','open','high','low','close','volume']
M15["datetime"] = pd.to_datetime(M15['time'],unit='ms').dt.tz_localize('UTC').dt.tz_convert('Asia/Shanghai')
print(M15)
```

now it used   types.methodtype  rewrite the fuction fetchOHLCV
i can get 600 ohlcv items

because  in  'okex,py'   the  self.loadmarket（） is instantiation func
so @classmethod can't use to instantiation func  ^_^。

**Comment by kroitor** [comment]
Hi @homily!

First of, your question is not about CCXT at all. Your question is more about how to use Python to write a well-structured Python program. Which is not related to CCXT. You can find much better resources online for learning Python.

Google or search on Youtube for tutorials on how to use Python, in particular:

- OOP basics
- classes and inheritance
- method overrides
- structuring the call flow
- architectural considerations
- functional programming vs OOP programming

Unfortunately, we cannot consult you on how to use Python, since CCXT assumes that you know well enough the programming language that you are using, to be able to write the programs how you want.

> every time I use it, I need to re-reference it

No. You don't need to recreate the exchange reference on every call.

> it'must use 'exchange=ccxt.okex({'hostname':'okex.me'})' in it

No. That depends on how you structure your program. In general, it does not have to instantiate the exchange inside it.

> if i change different exchange it will be wrong

This is why you don't want to instantiate your exchanges in every call. Pass the exchange instance to the function instead.

> so how can i get Class attribute or private attribute

Read Python's manual on basic built-in methods like getattr, setattr: https://docs.python.org/3/library/functions.html

> To judge different exchanges

You don't need that. All you need – is to learn the OOP in Python or a functional approach in Python to make it right.
Also, every exchange has an id that you can use to distinguish one from another (this is also documented in the CCXT Manual and it is recommended to read it from top to bottom at least once)

-------------------------------------------------------------------------------

I've uploaded an example that shows something similar to what you want:

- 

I would highly recommend to make sure that you understand everything there (that will require investing some of your time into your OOP skills and programming aspects listed out above). The example shows how to fetch all available okex ohlcvs using the inheritance. Note that OKEX will not serve more than a few hundred candles for each timeframe.

```Python
# -*- coding: utf-8 -*-

import ccxt
from ccxt.base.exchange import Exchange


# An example of OOP / class inheritance in Python

class ohlcv(Exchange):
    def fetch_all_ohlcvs(self, symbol, timeframe, max_retries=3):
        print('Loading', self.id, 'markets...')
        self.load_markets()
        print('Loaded', self.id, 'markets.')
        limit = 100
        earliest_timestamp = self.milliseconds()
        timeframe_duration_in_seconds = self.parse_timeframe(timeframe)
        timeframe_duration_in_ms = timeframe_duration_in_seconds * 1000
        timedelta = limit * timeframe_duration_in_ms
        ohlcv_dictionary = {}
        ohlcv_list = []
        i = 0
        done = False
        while True:
            # this printout is here for explanation purposes
            print('===========================================================')
            print('Iteration', i)
            fetch_since = earliest_timestamp - timedelta
            print('Fetching', self.id, symbol, timeframe, 'candles from', self.iso8601(fetch_since), 'to', self.iso8601(earliest_timestamp))
            num_retries = 0
            try:
                num_retries += 1
                ohlcv = self.fetch_ohlcv(symbol, timeframe, fetch_since, limit)
                if (len(ohlcv)):
                    earliest_timestamp = ohlcv[0][0] - timeframe_duration_in_ms
                    print('Fetched', len(ohlcv), self.id, symbol, timeframe, 'candles from', self.iso8601(ohlcv[0][0]), 'to', self.iso8601(ohlcv[-1][0]))
                else:
                    print('Fetched', len(ohlcv), self.id, symbol, timeframe, 'candles')
                    done = True
            except Exception:
                if num_retries > max_retries:
                    raise
                else:
                    continue
            i += 1
            ohlcv_dictionary = self.extend(ohlcv_dictionary, self.indexBy(ohlcv, 0))
            ohlcv_list = self.sort_by(ohlcv_dictionary.values(), 0)
            if len(ohlcv_list):
                print('Stored', len(ohlcv_list), self.id, symbol, timeframe, 'candles from', self.iso8601(ohlcv_list[0][0]), 'to', self.iso8601(ohlcv_list[-1][0]))
            if done:
                break
        return ohlcv_list


# Another example of OOP / class inheritance.
# This time my_okex class is inherited from two other classes
# both ohlcv and ccxt.okex, and has the methods from both classes.
# This is just an example, it is not necessary do it this way.
# You can combine classes and methods using Python's OOP how you like.

class my_okex(ohlcv, ccxt.okex):
    pass


# instantiate your class and call the inherited method

exchange = my_okex({
    # 'hostname': 'okex.me',  # if you're in mainland China
    'enableRateLimit': True,  # as required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

symbol = 'BTC/USDT'
timeframe = '1m'
ohlcvs = exchange.fetch_all_ohlcvs(symbol, timeframe)
print('Done.')

```

Let us know if that does not help, or does not answer your question.
Feel free to reopen it or just ask further questions, if any.

**Comment by homily** [comment]
hi,   very thanks.
Thank you very much for your professional answers
I will study your manual carefully
