### ISSUE TITLE
Why a Binance futures order timestamp/datetime is None?

### ISSUE THREAD

**Issue by heckad** [ccxt/ccxt#6877]
If I open order on binace future and try to get datetime I get the None. Seems on binacne future datetime need extract from `updateTime` response field.

**Comment by kroitor** [comment]
@heckad can you plz post your verbose request+response for that call?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
exchange.load_markets()
exchange.verbose = True
orders = exchange.fetch_open_orders(...
```

↑ Please, paste the verbose request and response of fetch_open_orders, after loading the markets.

**Comment by heckad** [comment]
Response after call open order
```
{
  'orderId': 2126185933,
  'symbol': 'BTCUSDT',
  'status': 'NEW',
  'clientOrderId': 'D37Qvs0capylB2s2uYtSGD',
  'price': '7100',
  'avgPrice': '0.00000',
  'origQty': '1',
  'executedQty': '0',
  'cumQty': '0',
  'cumQuote': '0',
  'timeInForce': 'GTC',
  'type': 'LIMIT',
  'reduceOnly': False,
  'closePosition': False,
  'side': 'BUY',
  'positionSide': 'BOTH',
  'stopPrice': '0',
  'workingType': 'CONTRACT_PRICE',
  'origType': 'LIMIT',
  'updateTime': 1588445012524
}
```
Ccxt result after process response 
```
{
  'info': {
    'orderId': 2126185933,
    'symbol': 'BTCUSDT',
    'status': 'NEW',
    'clientOrderId': 'D37Qvs0capylB2s2uYtSGD',
    'price': '7100',
    'avgPrice': '0.00000',
    'origQty': '1',
    'executedQty': '0',
    'cumQty': '0',
    'cumQuote': '0',
    'timeInForce': 'GTC',
    'type': 'LIMIT',
    'reduceOnly': False,
    'closePosition': False,
    'side': 'BUY',
    'positionSide': 'BOTH',
    'stopPrice': '0',
    'workingType': 'CONTRACT_PRICE',
    'origType': 'LIMIT',
    'updateTime': 1588445012524
  },
  'id': '2126185933',
  'clientOrderId': 'D37Qvs0capylB2s2uYtSGD',
  'timestamp': None,
  'datetime': None,
  'lastTradeTimestamp': None,
  'symbol': 'BTC/USDT',
  'type': 'limit',
  'side': 'buy',
  'price': 7100.0,
  'amount': 1.0,
  'cost': 0.0,
  'average': None,
  'filled': 0.0,
  'remaining': 1.0,
  'status': 'open',
  'fee': None,
  'trades': None
}
```

**Comment by kroitor** [comment]
@heckad in CCXT the order has two related fields, `timestamp` and `lastTradeTimestamp`. 

Binance futures API does not provide any of those values since they are not relevant to futures trading in general. The `timestamp` has to remain fixed in time, because it is the time of opening the order, so we cannot set it to `updateTime`. The value of `updateTime` will change when the order will be updated, which breaks unification. 

Therefore Binance futures API does not define the opening timestamp of the order, thus it is set to a `None/undefined` value. If we set `timestamp` = `updateTime`, then if the order is updated to a user it will looks like the order "jumped" over time, which it is not supposed to do. The opening timestamp should remain fixed in time, obviously.

Does that answer your question?

**Comment by kroitor** [comment]
Closing this for now if you don't mind. Let us know if we are missing something. Feel free to reopen this issue or just ask further questions if you have more. We will be happy to reply as soon as we can. Thx for your feedback!
