### ISSUE TITLE
FTX: add fetchClosedOrders

### ISSUE THREAD

**Issue by tradercgt** [ccxt/ccxt#6881]
Currently for the exchange FTX the method `fetchClosedOrders` is not implemented. Why not implement it in a similar way like the [binance implementation](https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1335)?

```
    async fetchClosedOrders (symbol = undefined, since = undefined, limit = undefined, params = {}) {
        const orders = await this.fetchOrders (symbol, since, limit, params);
        return this.filterBy (orders, 'status', 'closed');
    }

```
The closed order status is supported by the FTX API: [https://docs.ftx.com/?javascript#orders](https://docs.ftx.com/?javascript#orders)

**Comment by kroitor** [comment]
> Why not implement it in a similar way like the binance implementation?

Because FTX does not have an endpoint for fetching closed orders only.
However, it has a method for fetching all orders, open+closed+... – `fetchOrders` ← use this instead. See the [`has` metainfo](https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata) to see which methods are available. Let us know if that does not answer the question.

**Comment by tradercgt** [comment]
that's correct, but doesn't answer my question. Why don't you implement/emulate it like you did with binance?

**Comment by kroitor** [comment]
@tradercgt such an emulation breaks the pagination, unfortunately. We tend to avoid emulating the missing methods in general. You can do the filtering by status on the user side in 2 lines:

- https://github.com/ccxt/ccxt/issues/6301#issuecomment-568212041

```JavaScript
        const orders = await exchange.fetchOrders (symbol, since, limit, params);
        return exchange.filterByArray (orders, 'status', [ 'closed', 'canceled' ], false);
```

We had to add it for binance specifically, because the users insisted on it. Though, we're not too happy about it and may remove it in the future, if Binance does not add a corresponding endpoint. I can't find the exact issue quickly, but it was added by a user request. In general we tend to avoid the `emulated` methods where the underlying exchange does not have a true endpoint. Let me know if that still does not answer the question.

**Comment by tradercgt** [comment]
I understand better now! Thank you for the explanation!
