### ISSUE TITLE
Margin Binance: "code":-1003,"msg":"Too many requests; current request has limited:

### ISSUE THREAD

**Issue by baeriswyld** [ccxt/ccxt#6905]
- OS: Linux
- Programming Language version: Python
- CCXT version: ccxt==1.20.48

Hello ! 

Hope all well.

I place loan orders on Binance margin.
```
provider = ccxt.binance ....
msg = await provider.sapiPostMarginLoan(params={"asset": "XRP", "amount": 20})```
```
 I use my own rate limiter which works perfectly fine for orders.
However, I randomly get the error message -1003 , as below.
```
binance 429  {"code":-1003,"msg":"Too many requests; current request has limited."
```
Any idea what I do wrong ?

Thanks !!

**Comment by kroitor** [comment]
> Any idea what I do wrong ?
> I use my own rate limiter which works perfectly fine for orders.

If you're using your own rate-limiter, then you want to make sure that your request rates satisfy the "weight" requirements for binance endpoints (different endpoints have different weights).

See Binance docs for details: https://binance-docs.github.io/apidocs/

Also:

- https://binance-docs.github.io/apidocs/spot/en/#change-log

![Screen-Shot-2020-05-07-at-20 33 14](https://user-images.githubusercontent.com/1294454/81326243-36feee80-90a2-11ea-8412-811e84a29a0e.jpg)

If you're 100% sure, that your request rate satisfies all the rules from Binance docs – then you might want to report it to Binance tech support, since there were recent changes to that specific part of the API and it may be a bug.

**Comment by baeriswyld** [comment]
Ha ! That's it. They keep changing things...
I m violating the request limit of 1 every 2 second !

Thank you ! and sorry, you are not the Binance support...
