### ISSUE TITLE
Bug or expect behavior? 

### ISSUE THREAD

**Issue by heckad** [ccxt/ccxt#6911]
https://github.com/ccxt/ccxt/blob/6a3dba2b2519f318f69567ec2cad26c4b7677507/js/binance.js#L516
Why you use ` -1 * Math.log10 (precision['amount'])` and what you want achive?

**Comment by kroitor** [comment]
That looks like a bug to me. It should be set `undefined` there. This is just an outdated line of code, Binance has added the MIN_NOTIONAL filter, which overrides the min cost a few lines below here: https://github.com/ccxt/ccxt/blob/6a3dba2b2519f318f69567ec2cad26c4b7677507/js/binance.js#L553

That, however, is not applied to futures, because MIN_NOTIONAL is not applicable to futures. I will clean it up shortly.

**Comment by heckad** [comment]
What does `cost` mean?

**Comment by kroitor** [comment]
@heckad usually, `cost` aka _"notional"_ means `amount` * `price` or the total cost of the order or a trade _in quote currency_. 

For trades: cost = amount * price 
For orders: cost = filled * price, the actual filling price and the actual filled value is used which may be different from the ordered price, depending on the type of the order. 

It is documented here: https://github.com/ccxt/ccxt/wiki/Manual#order-structure
