### ISSUE TITLE
New Exchange: MorCrypto

### ISSUE THREAD

**Issue by ChimeAmakiri** [ccxt/ccxt#6925]
https://morcrypto-exchange.com/apidocument MorCrypto Exchange, is a crypto currency exchange from Africa/Nigeria registered as MorCrypto Ltd in Nigeria RC.1660409 we aim to contributei in driving the adaptation of crypto in Africa as this will bring a great opportunity for Africa and the Blockchain, we have successfully built our exchange and we will be honored to list on CCXT/GitHub

**Comment by ChimeAmakiri** [comment]
Thanks for the fast responds, we see that you have added the new exchange label to our request, does this mean that our exchange is now listed on the CCXT library? or there anything else we should do?

**Comment by kroitor** [comment]
> does this mean that our exchange is now listed on the CCXT library?

Nope, all requests for adding new exchanges receive that label. It means, that this issue will be open until someone implements the exchange as described in our contributing guidelines and it passes the public and private testing. If nobody submits a workable implementation – we will do that as soon as we can. However, we cannot give an ETA on the free work as explained in our FAQ, because we have 80+ exchanges in the backlog. If you want the CCXT Dev Team to prioritize and do the integration work quickly, please reach out to us at info@ccxt.trade.

**Comment by ChimeAmakiri** [comment]
we have sent a message to  info@ccxt.trade from our email admin@morcex.com, is there any payment for this or it's a free listing?

**Comment by ChimeAmakiri** [comment]
Because we want the CCXT Dev Team to prioritize and do the integration work quickly

**Comment by kroitor** [comment]
>  is there any payment for this or it's a free listing?

We don't charge for the listing itself, however, there's no such thing as "just listing in CCXT". The exchange API has to be implemented first according to the CCXT contributing guidelines in order to be merged and listed. However, we cannot guarantee the ETA on the free work for obvious reasons. So, there's no payment if you can wait. If you want us to prioritize the work on the implementation with a guaranteed delivery datetime – we can charge for the work. I suggest to move this discussion to email.

**Comment by ChimeAmakiri** [comment]
ok, i will send an email now

**Comment by ChimeAmakiri** [comment]
I just sent you an email to your gmail please check

**Comment by kroitor** [comment]
Exchange certificates have expired:

<img width="1678" alt="Screenshot 2021-11-12 at 22 30 27" src="https://user-images.githubusercontent.com/1294454/141524215-cb3fa1e3-af24-411e-9d8e-b73c0528075b.png">
