### ISSUE TITLE
Poloniex fetchOHLCV empty ohlcv candle with since=0

### ISSUE THREAD

**Issue by ManuelSchneid3r** [ccxt/ccxt#6928]
```python
>>> import os
>>> import ccxt
>>> ccxt.__version__
'1.27.51'
>>> os.uname()
posix.uname_result(sysname='Darwin', nodename='xenon.fritz.box', release='19.4.0', version='Darwin Kernel Version 19.4
.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64', machine='x86_64')
>>> ccxt.poloniex().fetchOHLCV('BTC/USDT', timeframe='5m', limit=1000, since=0)
[[0, 0.0, 0.0, 0.0, 0.0, 0.0]]
>>>
```

I guess this should return some nice OLHCV data.

**Comment by kroitor** [comment]
In short, if you send `since=0`, Poloniex will return an array with one empty candle.
If you send `since=1`, Poloniex will return an empty array.
That is because Poloniex did not exist back then in 1970.
The exchange could return an error for such queries, but in this case it is the responsibility of the user. You might want to change your input values.

That call translates to this URL:

- https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&period=300&start=0&end=300000

```Python
import ccxt
exchange = ccxt.poloniex({
    'enableRateLimit': True,
    'verbose': True,
})

exchange.fetchOHLCV('BTC/USDT', timeframe='5m', limit=1000, since=0)
```

I have this output in JS and Python:

```JavaScript
fetch:
 poloniex GET https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&period=300&start=0&end=300000
Request:
 {}
 undefined

handleRestResponse:
 poloniex GET https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&period=300&start=0&end=300000 200 OK
Response:
 {
  'Access-Control-Allow-Methods': 'GET',
  'Access-Control-Allow-Origin': '*',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '591e11410852dfeb-FRA',
  'Cf-Request-Id': '02a6a91ca20000dfeb50106200000001',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Mon, 11 May 2020 18:47:15 GMT',
  'Expect-Ct': 'max-age=604800, ' +
    'report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=d5282986b7a52767c228273a024e72c4b1589222835; ' +
    'expires=Wed, 10-Jun-20 18:47:15 GMT; path=/; ' +
    'domain=.poloniex.com; HttpOnly; SameSite=Lax; ' +
    'Secure',
  'Transfer-Encoding': 'chunked'
}
 [{"date":0,"high":0,"low":0,"open":0,"close":0,"volume":0,"quoteVolume":0,"weightedAverage":0}]
```

↑ What you see is what you get directy from the exchange as requested by you. It is the data returned from the exchange, so, if you think it should be different – you can send your output to the exchange tech support. To me it does not look strange, though, very few exchanges will accept a `since` value of `0`. In most cases they will require `since` greater than the timestamp when the exchange was launched, or the timestamp when the currency birth, or the timestamp of adding the specified symbol on the exchange side.

Let us know if the above does not resolve this issue.
