### ISSUE TITLE
How do I know the number of BUY trade and the number of SELL trade in each candle

### ISSUE THREAD

**Issue by nabilharir** [ccxt/ccxt#6966]

**Comment by kroitor** [comment]
In general, the exchanges will not serve the number of trades in OHLCV candles. Please, see the Manual for which structures include what: https://github.com/ccxt/ccxt/wiki/Manual. We recommend to read it at least once from top to bottom – it will save you a ton of time, really. Let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. If you want to find out the number of trades – you will have to get public trades continuously with fetchTrades (CCXT) or watchTrades (CCXT Pro), count buys and sells, and store those results in the history on the user side.

**Comment by nabilharir** [comment]
> In general, the exchanges will not serve the number of trades in OHLCV candles. Please, see the Manual for which structures include what: https://github.com/ccxt/ccxt/wiki/Manual. We recommend to read it at least once from top to bottom – it will save you a ton of time, really. Let us know if that does not answer your question.

I need a python code for calculate number of BUY trade and SELL trade

**Comment by kroitor** [comment]
> I need a python code for calculate number of BUY trade and SELL trade

Ok, but you will have to write it. You have to know Python in order to be able to work with this lib efficiently. After reading the Manual and having the base Python skills it shouldn't be a problem to write the snippet of code that does what you want. Yet we can't write all the code for everyone –thousands of users are using this lib and it is physically impossible to write the code for everyone, hope for your understanding. CCXT provides you with the building instruments and you can use those to get the data that you want. We will be able to help if you run into a specific problem related to the CCXT usage or with some specific snippet of your code, there's no shortcuts.
