### ISSUE TITLE
[dsx] fetch orders broken

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6983]
I'm getting `dsx fetchOrders not supported`, but it is.

**Comment by kroitor** [comment]
> but it is.

Nope, I don't think it is. If you look into the actual response – both DSX and HitBTC will return closed orders from "active" orders endpoint for some while. And then those orders will be moved to inactive orders (the status does not change). So it does not have a true fetchOrders endpoint for historical reasons. It will also return partially filled orders from their historical endpoint. In other words, their "active" exchange-specific state has nothing to do with the "open/closed" unified status, really. Both exchanges have `fetchOpenOrders` and `fetchClosedOrders`. But neither of them has `fetchOrders` for all orders, regardless of the "active" state and regardless of the "open/closed" status. Does that answer your question? Let me know, if I'm missing something.

**Comment by npomfret** [comment]
I see, thanks.

**Comment by kroitor** [comment]
Also, because of that "active/inactive" design both exchanges have fetchOrder (for "historical" orders which may be open/closed/canceled) and fetchOpenOrder (for querying an "active" order, which can also be open/closed/canceled). We think of renaming fetchOrder → fetchClosedOrder to match the API a little bit closer.
