### ISSUE TITLE
How to get Huobi bid/ask price with watchTicker?

### ISSUE THREAD

**Issue by Corfucinas** [ccxt/ccxt#7033]
Language: Python

Hi @kroitor 
I have decided to purchase ccxpro!

Two things that I have noticed initially:
-The repository cannot be installed using Poetry (pip works fine), it has an exit code 1.
-Huobi `watch_ticker` is not returning the "ask" or "bid", which is a bummer since I bought CCXTPRO for that reason 🤣 .
I can use `watch_order_book`, but it will take me a lot of refactoring to do..

Is it possible to add `"ask"/"bid"` to Huobipro?

**Comment by kroitor** [comment]
Hi @Corfucinas !

> -The repository cannot be installed using Poetry (pip works fine), it has an exit code 1.

We haven't tested it with 3rd-party package managers, but will do our best to get there.

> -Huobi watch_ticker is not returning the "ask" or "bid", which is a bummer since I bought CCXTPRO for that reason 🤣 .
> Is it possible to add "ask"/"bid" to Huobipro?

Unfortunately, not, because Huobi Pro does not provide that information via the WS ticker, here's how a ticker update from Huobi looks like:

```
2020-05-28T13:19:20.960Z onMessage {
  ch: 'market.btcusdt.detail',
  ts: 1590671960809,
  tick: {
    id: 215837272868,
    low: 9053.9,
    high: 9450.01,
    open: 9160.36,
    close: 9399.88,
    vol: 373216777.90379894,
    amount: 40485.241497971125,
    version: 215837272868,
    count: 457796
  }
}
```

↑ No bid/ask there to derive that data from. So, the only way to track current market prices is to use the orderbook feed. Or fallback to `fetchTicker` over REST.

In general, not all exchanges will consider bid/ask a part of the ticker, most often the ticker is limited to the 24 OHLCV + last public trade price. The ticker itself is just a second-order statistical 24-hour calculation (derived data) from the first-order realtime data based on the orderbook+trades. You can derive the ticker info from the source data on the user side.

Let me know if the above does not answer your questions question.

**Comment by Corfucinas** [comment]
Thanks for the prompt reply. I'll continue exploring the library. (I'll work around Huobi, you have some, they take some...one day a single websocket will provide us everything we need for quant!)

**Comment by kroitor** [comment]
@Corfucinas thanks! Feel free to reopen it if needed, or just ask further questions if any. Thank you for using CCXT Pro.
