### ISSUE TITLE
how i get average buy price?

### ISSUE THREAD

**Issue by jins81c** [ccxt/ccxt#7036]
Programming Language version: python
CCXT version: newest
Exchange: BITHUMB
Method: balance (bal = exchange.fetch_balance() )

i want get average buy price. 
upbit, bitmex => it have in balance
but bithumb it's not have...

plz help me.

**Comment by kroitor** [comment]
Hi!

First of all, have you read the Manual?

- https://github.com/ccxt/ccxt/wiki

**Comment by jins81c** [comment]
> Hi!
> 
> First of all, have you read the Manual?
> 
> * https://github.com/ccxt/ccxt/wiki
sorry. i read it. it's difficult

I am new to development.

Upbeat, Bitmax is complete.
We are inquiring because Bithumb cannot be resolved.

If you know how to fix it, please let me know.
thank you

**Comment by kroitor** [comment]
> I am new to development.

If you're new to development, my advice is to always read the Manual first. If you want to enter software development – do not ever skip reading the documentation.

I suggest to read the Manual at least once from top to bottom very carefully first, because it explains how to get various types of prices. 

The `fetch_balance()` call has nothing to do with the prices, it is for fetching the current balance. 
The `fetch_orderbook` call is related to getting the current prices from the orderbook. 
The `fetch_trades` call allows you to get the most recent publicly filled prices. You need to understand the difference between different types of prices.
The `fetch_my_trades` and `fetch_orders` allow you to get the buying prices of your personal trades and orders.

From your question it is not entirely clear which specific price you want.

In general algotrading with CCXT requires certain skills in both programming and trading. The Manual explains how to use CCXT and introduces very specific terms related to algotrading, and you seem to be confusing those terms in your question. 

The Manual also has links to examples and a lot of useful information. The only thing that is required and inevitable – you will have to read it in order to be able to work with this library efficiently.

Unfortunately, we can't write the code for everyone, because that is not possible physically. Moreover, most of that code is already written and explained in the docs and in the examples.

Let us know if you get stuck in the process. Closing this issue for now, feel free to reopen it or just ask further questions, if any.

**Comment by jins81c** [comment]
> > 저는 개발이 처음입니다.
> 
> 개발에 익숙하지 않다면 항상 조언을 먼저 읽는 것이 좋습니다. 소프트웨어 개발을 시작하려는 경우 – 설명서를 읽는 것을 건너 뛰지 마십시오.
> 
> 다양한 유형의 가격을 얻는 방법을 설명하기 때문에 매뉴얼을 맨 처음부터 맨 아래까지 한 번 이상 매우 신중하게 읽는 것이 좋습니다.
> 
> `fetch_balance()`호출이 가격과는 아무 상관이없는, 현재의 균형을 가져 오는입니다. 호출은 수주 잔고에서 현재의 가격을 받고 관련이 있습니다. 전화는 가장 최근에 공개적으로 가득 차 가격을 얻을 수 있습니다. 다른 유형의 가격의 차이점을 이해해야합니다. 하고는 귀하의 개인 거래 및 주문의 구매 가격을 얻을 수 있습니다.
> `fetch_orderbook`
> `fetch_trades`
> `fetch_my_trades``fetch_orders`
> 
> 귀하의 질문에서 원하는 특정 가격이 명확하지 않습니다.
> 
> 일반적으로 CCXT를 이용한 알고 트래 딩은 프로그래밍과 거래에 특정 기술이 필요합니다. 이 매뉴얼은 CCXT 사용 방법을 설명하고 알고 트래 딩과 관련된 매우 구체적인 용어를 소개합니다.
> 
> 매뉴얼에는 예제와 많은 유용한 정보에 대한 링크가 있습니다. 필요하고 불가피한 유일한 것 –이 라이브러리를 효율적으로 사용하려면이를 읽어야합니다.
> 
> 불행히도 모든 사람을 위해 코드를 작성할 수는 없습니다. 물리적으로는 불가능하기 때문입니다. 또한 해당 코드의 대부분은 이미 문서와 예제에서 작성 및 설명되었습니다.
> 
> 당신이 과정에 갇혀 있는지 알려주십시오. 지금이 문제를 해결하려면 언제든지 다시 열거 나 추가 질문이있는 경우 언제든지 문의하십시오.

thank you.
ex)
1. i buy bitcoin => 9500$ cnt1
2. i buy bitcoin => 10000$ cnt1

=> "my" average buy price => 9750$ cnt 2

I usually brought the balance and there was an average price there ( upbit, bitmex)
but bitthumb is not

ex) bitmex
bit.private_get_position() => ['avgEntryPrice']
ex) upbit
exchange.fetch_balance()  => ['avg_buy_price']

bitthumb
1.get_position() is not (https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/bithumb.py)
2.fetch_balance() not have avg_buy_price

I don't know where to find 

thank you

**Comment by kroitor** [comment]
@jins81c a simple formula like (a + b) / 2 will not work for a general case.

Suppose that you buy, then sell, then buy again, and again, and then sell again. Then the simple formula will not work with spot orders this way (for Bithumb).

So, the average buying price (aka average entry price) is only applicable to margin/contract trading positions. At this time bithumb.pro's contract trading is not implemented in CCXT yet, only bithumb.com spot trading is available. We are going to add bithumb.pro as soon as we can.

In the meantime, if you want to get the average buying price from bithumb.com – you can call `fetch_my_trades`, filter the trades by the `side` (buy/sell) and then aggregate and divide them by the sum of their volumes.

**Comment by APIScorcher** [comment]
I want to add to this, so for bitmex I was able to get the average entry price by using exchange.private_get_position()
but now it seems sometimes the function returns the avgEntryPrice and sometimes it does not want to return it.
Sometimes its there and sometimes it isn't there.

I use another method to get set cross margin and in its response, avgEntryPrice is available. What other methods can get me the avgEntryPrice for bitmex?
