### ISSUE TITLE
Support for Bittrex Credits in API v3

### ISSUE THREAD

**Issue by otschek** [ccxt/ccxt#7100]
Is it possible to add the function to use the Bittrex Credits mentioned in the Bittrex API Reference?

[https://bittrex.github.io/api/v3#/definitions/NewOrder](https://bittrex.github.io/api/v3#/definitions/NewOrder)

**useAwards:** boolean
_option to use Bittrex credits for the order (optional)_

Example:
```
{
  "marketSymbol": "string",
  "direction": "string",
  "type": "string",
  "quantity": "number (double)",
  "ceiling": "number (double)",
  "limit": "number (double)",
  "timeInForce": "string",
  "clientOrderId": "string (uuid)",
  "useAwards": "boolean"
}
```

**Comment by kroitor** [comment]
CCXT already supports all possible params by design, as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

You can specify any of the desired values in `params`-overrides.

We highly recommend to read the Manual very carefully from top to bottom at least once – it will save you a ton of time, really.

```Python
params = {
    'useAwards': 'true',
}
order = exchange.create_order(symbol, type, side, amount, price, params)
```

Let us know if that does not answer your question.

**Comment by otschek** [comment]
It works perfect.

Thank you very much for the fast answer.
