### ISSUE TITLE
Binance fapiPrivateGetPositionRisk RequestTimeout

### ISSUE THREAD

**Issue by eugjr** [ccxt/ccxt#7101]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux
- Programming Language version: Python 3.6
- CCXT version: 1.29.75

I'm running a simple bot on a Amazon VPS, and I'm getting some errors that make the bot stop. The last one says Request Timeout for Binance futures api when fetching user positionrisk. Here is the part of the code that have this line. It runs fine for some hours and then got stopped with the outputed error below:
```
corretora = ccxt.binance({
        'apiKey': 'x',  # edit for your keys
        'secret': 'x',
        'enableRateLimit': True,
        'options': { 'defaultType': 'future' },
    })
posicao = corretora.fapiPrivateGetPositionRisk()
positionAmt = (posicao[0]['positionAmt'])
   
print('Posição atual :', positionAmt,'BTC')	
```
##The algo then uses positionAmt var to place and cancel entry orders, account is running only BTC/USDT trades``

```
File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, i
n request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, i
n send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py", line 529, i
n send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='fapi.binance.com', port=443): R
ead timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "btc_v2.py", line 34, in <module>
    posicao = corretora.fapiPrivateGetPositionRisk()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 452,
in inner
    return entry(_self, **inner_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/binance.py", line 1987, in re
quest
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 471,
in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body
'])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 571,
in fetch
    raise RequestTimeout(method + ' ' + url)
ccxt.base.errors.RequestTimeout: GET https://fapi.binance.com/fapi/v1/positionRisk?timesta
mp=1591850594955&recvWindow=5000&signature=aea773e4919a5bac1b6d165bc5d22fb79be0b1cfadd12a486234baeb7e16cfea
```
Unfortunatelly I cant't get the begining of the error, as the tmux terminal on vps doesn't allow me to navigate trought the past displayed texts.

Is this error related to the new v2 binance futures api call for positionRisk as stated on their changelog or is something realated to my code? The bot runs fine for couple of hours (made some trades), and then get some errors like this one, or Gateway error, etc.
The python script of the bot is running in a while() loop to get updated prices, cancel open orders and placing new ones.

https://binance-docs.github.io/apidocs/futures/en/#change-log
``` 2020-06-04

New endpoints of version 2 of fapi, having better performance than the v1 endpoints:
GET /fapi/v2/account
GET /fapi/v2/balance
2020-06-02

New endpoint GET /fapi/v2/positionRisk in version 2 of fapi:
User can choose to send specific "symbol".
All symbols in the market can be returned.
Different responses for "One-way" or "Hedge" position mode.
Better performance than the v1 endpoint. ```

**Comment by kroitor** [comment]
Hi!

First of all, the lib really requires you to follow the guidelines very precisely, including the troubleshooting guidelines.

This is very important to make stable and quality user programs. Be as precise as you possible can when following the guidelines (do not miss anything).

At this time your report raises more questions:

> I'm running a simple bot on a Amazon VPS, and I'm getting some errors that make the bot stop.

The Manual says that you should always add the error handling, by wrapping the code with try/except clauses. Do you have that?

Apart from that the same Manual says how to troubleshoot an issue – which specific steps have you tried? https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

- Does it work for you if you run it locally or from a different location?
- Is it repeatable (always working first for 2 hours, then crashes)
- Do you run multiple parallel executions of the same script?
- How do you launch the script?
- Are you sure you don't have stale processes running in the background?

```
corretora = ccxt.binance({
        'apiKey': 'x',  # edit for your keys
        'secret': 'x',
        'enableRateLimit': True,
        'options': { 'defaultType': 'future' },
    })
posicao = corretora.fapiPrivateGetPositionRisk()
positionAmt = (posicao[0]['positionAmt'])
   
print('Posição atual :', positionAmt,'BTC')
```

> It runs fine for some hours and then got stopped with the outputed error below:

↑ This code does not run for 2 hours. It only does one request and exits immediately.

Therefore it is very hard to tell the exact specific reason of your error, since you're not showing the part that is running for 2 hours..

If you can paste a short **BUT COMPLETE** snippet to reproduce it – we will be able to help you.
Unfortunately, without seeing the complete code it's hard to tell the cause of your issue.
Please make it as short as possible, remove all irrelevant parts from it. Keeping removing parts and pieces until you're left with the shortest code that is short enough to fit on a page, but still causes a crash after 2 hours of running.

You may also find the problem yourself in the process of reducing your code to a reproducible case.

When pasting the code and output, please always follow the guidelines literally to a word:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

↑ It says, we need the code to reproduce it + your verbose request/response sequence. The error stacktrace is not enough. 

To get the debug output which is required to solve the issue, you want to add `'verbose': True` to your exchange config, alongside the `'enableRateLimit': True`.

> Unfortunatelly I cant't get the begining of the error, as the tmux terminal on vps doesn't allow me to navigate trought the past displayed texts.

This one is a question on how to use tmux, but it's not related to CCXT, really.
In tmux you can enter the scroll-mode (press `ctrl+b` then press the `[` key – in the scrollmode you can see the output that went out of the screen, by scrolling with your keypad keys `↑` and `↓`. You can exit the scrollmode by pressing `q`.

- https://www.google.com/search?q=tmux+scroll

Apart from any Linux shell allows you to redirect the output to a file and collect everything there.
Redirecting the output to a file is a common unix thing, and using CCXT requires certain basic skills to operate your shell:

```
python3 your-script.py > log.txt
```

↑ This way you don't even have to scroll – all the output from your script will be written to a text log file. It's not about CCXT, but more about your basic skills of working with Linux – you need to have them to operate efficiently. I'd recommend to read some _"`bash` tutorials"_ (google those).

We need the code + the log, otherwise we will be guessing on what is happening around the code, that you haven't pasted here.

> Is this error related to the new v2 binance futures api call for positionRisk as stated on their changelog or is something realated to my code? 

If you provide the above info – we would be able to identify and locate the error rather quickly. We do not need your keys, so please don't paste those.

A RequestTimeout exception is normal (can happen from time to time and can be mitigated with a simple try/except error handling + retry in most cases), as explained, for example here: https://github.com/ccxt/ccxt/issues/7099#issuecomment-642580736

**Comment by eugjr** [comment]
Thanks for the answer, I'll implement log function for the script and do more tests and back with more info.

**Comment by kroitor** [comment]
@eugjr let us know if you still have this issue, feel free to reopen it or just ask further questions if any.
