### ISSUE TITLE
Get FTX Futures Stats via public API (MOVE Contract)

### ISSUE THREAD

**Issue by ianpetrarca** [ccxt/ccxt#7115]
- OS: Windows 10 
- Programming Language version: Node v11.14.0
- CCXT version: 1.29.97

Hi I am looking to get back the stats for MOVE contract futures on FTX (Strike Price, Open Interest, etc). I'm getting an error when trying to retrieve that via publicGetFuturesFutureNameStats().

FTX Futures Stats: https://docs.ftx.com/#get-future-stats

```
async function publicRequest() {
    let ftx = new ccxt.ftx ()  
    let move = await ftx.publicGetFuturesFutureNameStats("BTC-MOVE-0613");
    console.log(move)
}

publicRequest()
```

**Comment by kroitor** [comment]
Hi!

First of, the implicit methods accept an object `{'future_name': 'BTC-MOVE-0613'}`, not a string `'BTC-MOVE-0613'`.

Secondly, you should always `enableRateLimit` as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Third, you shouldn't create a new instance for each new request, make sure to reuse the existing exchange instance, otherwise you will break the rate limits.

Fourth, when you get an error, always follow the Manual and the FAQ literally to a word:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Especially, this:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

The correct call looks like this:

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.ftx ({
    'enableRateLimit': true,
})

(async () => {
    const response = await exchange. publicGetFuturesFutureNameStats ({
        'future_name': 'BTC-MOVE-0613',
    })
    console.log (response)
}) ()
```

Let us know if the above does not answer your question.

**Comment by ianpetrarca** [comment]
Thank you so much! This worked for me.
