### ISSUE TITLE
Binance delivery future API needed 

### ISSUE THREAD

**Issue by icytrader** [ccxt/ccxt#7117]
https://binance-docs.github.io/apidocs/delivery/en/#change-log

Hi, their dapi endpoint and delievry future contracts have been released for some days, can we support it in ccxt and ccxt.pro?

thanks

**Comment by kroitor** [comment]
Thanks! We are going to add it as soon as possible.

Whoever is the designer of their API should've just had a single set of endpoints instead of introducing fapi/exchangeInfo, dapi/exchangeInfo, and spot/exchangeInfo. If they served those definitions from a single universal endpoint for all markets of all types, that would make integrations A LOT easier. Introducing whole new API sections that are almost mirroring the other sections is a pain to maintain and support on the user side.

**Comment by hhagelbe** [comment]
Hi @kroitor,

Is there any expected delivery date for this?

Thanks

**Comment by gokerg** [comment]
Hi @kroitor,

Is there any expected delivery date for this?

Thanks

**Comment by frosty00** [comment]
@gokerg 

We will get to it as soon as possible. We cannot guarantee any dates. See here for more details -
https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar

**Comment by dbaynard** [comment]
Hello

I'm seeking to add this functionality in the coming days, unless somebody else is already working on it.

(Also since this issue was opened they've changed the name of their apis… they're still at `fapi` and `dapi` but now they're USDT-margined and coin-margined…)
