### ISSUE TITLE
FTX ccxt (fetch_closed_orders) show not supported yet

### ISSUE THREAD

**Issue by SENSEmudley** [ccxt/ccxt#7123]
when I try to fetch closed orders it will show

"fetch_closed_orders() is not supported yet"

how can I fix this sir ?
many thanks

**Comment by kroitor** [comment]
@SENSEmudley we will add the implementation for FTX's order history asap.

**Comment by kroitor** [comment]
@SENSEmudley FTX has `fetchOrders` (not `fetchClosedOrders`) because the exchange API does not have an endpoint for closed orders, it returns all orders instead.

- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

Let us know if that does not answer your question. Feel free to reopen it or just ask further questions if any.
