### ISSUE TITLE
HitBTC Extra Transaction Types

### ISSUE THREAD

**Issue by eabrouwer3** [ccxt/ccxt#7205]
My problem comes with a discrepancy between what I actually got back from the HitBTC API. The CCXT API docs say that we should only get 'deposit' and 'transaction' back from the API. It seems the code here is to blame, because we aren't managing the two extra types:

```python
def parse_transaction_type(self, type):
    types = {
        'payin': 'deposit',
        'payout': 'withdrawal',
        'withdraw': 'withdrawal',
    }
    return self.safe_string(types, type, type)
```

I'm happy to submit a PR, either to the docs, or to the code to handle those other cases. I just don't know which one we actually want, so I wanted to open up a ticket first.

- OS: Ubuntu 20.04
- Programming Language version: Python 3.7
- CCXT version: 1.30.51

```python
def limit_offset_get(method):
    results = list()
    offset = 0
    while True:
        params = {'offset': offset}
        result = method(limit=1000, params=params)
        if len(result):
            results += result
            offset += 1000
        else:
            break
    return results

client = getattr(ccxt, 'hitbtc')({
    'enableRateLimit': True,
    'apiKey': '<apiKey>',
    'secret': '<secret>'
})
txns = limit_offset_get(client.fetch_transactions)
print(set(map(lambda tx: tx['type'], txns)))
```

What I got:
```python
{'deposit', 'exchangeToBank', 'withdrawal', 'bankToExchange'}
```
What I expected:
```python
{'deposit', 'withdrawal'}
```

**Comment by kroitor** [comment]
Hello, please see these related discussions: 

- https://github.com/ccxt/ccxt/pull/5919
- https://github.com/ccxt/ccxt/issues/406

In short, `exchangeToBank` and `bankToExchange` are not deposits nor withdrawals. Those are just internal transfers from one HitBTC account to another (main account to trading account and back).

Changing those to `deposit` and `withdrawal` would me a mistake, since deposits and withdrawals are for blockchain-transactions only.

Instead, we should implement a `fetchLedger` method to handle that specific aspect of HitBTC properly in a unified manner.
Removing them from the output would also be a mistake, since that will break the pagination.

In the meantime you can just `fetchTransactions` and filter out everything that is not a `deposit` or `withdrawal`.

Due to the above I'd close the PR https://github.com/ccxt/ccxt/pull/7207 for now, until we have a better unification mechanism for it.

Feel free to reopen this issue or just ask further questions if any.
