### ISSUE TITLE
Binance Future position side

### ISSUE THREAD

**Issue by Chetchaiyan** [ccxt/ccxt#7215]
Dear Sir,

I understand that the question is related to binance api more than ccxt but I don't know where I can seek an help so I drop question here wish you might help me for my issue.

My Environment is 
- Python 3.7.x 
- ccxt 1.30.57
- exchange binance future

What I try to do is, I try to get position information back from binance. However, I can't get side of current position.

Please consider the following response
1. Long Position
```
[{'entryPrice': '9088.33000',
'initialMargin': '3.63693',
'isolated': False,
'leverage': '5',
'maintMargin': '0.07274',
'maxNotional': '50000000',
'openOrderInitialMargin': '0.00000',
'positionInitialMargin': '3.63693',
'positionSide': 'BOTH',
'symbol': 'BTCUSDT',
'unrealizedProfit': '0.00798308'}],
```
2. Short Position
```
[{'entryPrice': '9088.49000',
'initialMargin': '3.63658',
'isolated': False,
'leverage': '5',
'maintMargin': '0.07273',
'maxNotional': '50000000',
'openOrderInitialMargin': '0.00000',
'positionInitialMargin': '3.63658',
'positionSide': 'BOTH',
'symbol': 'BTCUSDT',
'unrealizedProfit': '-0.00592273'}],
```

That's all I get from fetch_balance(). for me it look almost the same no way to know which one is long or short.

I don't use Hedge Mode (which I know that it will return positionSide as LONG or SHORT) because of I would like to make sure that only one-side apply at anytimes. 

Please help me to solve this problem.

Best Regards, 
Chet Chetchaiyan

**Comment by kroitor** [comment]
Hi! 

This question has been answered here:

- https://github.com/ccxt/ccxt/issues/7195#issuecomment-650705896

You want to make sure that you have the understanding of a few key concepts, namely:

1. what is a position
2. what `'positionSide': 'LONG'`, `'positionSide': 'SHORT'` and `'positionSide': 'BOTH'` means

----------

1. Your position with a trading symbol is nothing more than just a cumulative result of all your trades with that symbol. Make sure that this is clear to you. Suppose we're talking about the BTC/USDT perpetual swap symbol, as you've shown above. When you don't have an open position with BTC/USDT, that is essentially the same thing as having a position of size 0 (neutral position). 

----------

2. Now, suppose you buy 50 BTC/USDT swaps. That makes your BTC/USDT position +50 (or, in other words, it is now a LONG position as you would say). Then you sell -30 BTC/USDT swaps. That shrinks the size of your BTC/USDT position down to 20 swaps (the sum of all your trades). It is still on the LONG side, since you have +20 swaps remaining in total. Then, suppose, you sell -60 more BTC/USDT swaps. That makes your position +20 - 60 = -40. Now it has changed the side, because you've sold more than you've bought in total. That means that your position is now SHORT. Thus, the position side is defined by the cumulative size of the sum of your trades. Binance does not show that position as LONG or SHORT. Instead, Binance shows the position side as BOTH (which you can see in your output). That BOTH term means that your position switches sides depending on the sum of trades you make. It's always the same position, but it changes the side depending on how you trade. This is just how Binance's perpetual swap positions work. 

BOTH – is the default side of your position, if you don't specify the exact position side yourself.

Next, if you want to make sure that your position is always one-sided, precisely LONG or SHORT (not BOTH), then you have to specify [a param override](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params) for `createOrder` upon placing your order (when making trades). Thus, if you place an BTC/USDT with positionSide LONG or positionSide SHORT – you will force the position to be either LONG or SHORT (not BOTH).

So, assuming that you're starting with a neutral position of size 0, then in that case, if you buy +50 swaps with positionSide LONG – your position will be LONG. If you sell -20 swaps later, your position will remain +30 LONG.

How to specify the side of your position upon placing an order is explained here:

- https://github.com/ccxt/ccxt/issues/7195#issuecomment-650705896

I hope the above answers your question. Let us know if not.

**Comment by Chetchaiyan** [comment]
Dear Kroitor,

Thank you for your time and effort for answering my question.

I might misunderstanding between the word "one-side" thank you for your explanation. With I want is I would like to make sure that only one position exist in my portfolio either long or short is fine, but not 1 LONG and 1 SHORT positions (Hedge Mode) 

Then, I would like to increase or decrease that position. without knowing the side I can't issue correct command (buy/sell). Let consider this scenario
1. Reduce the position 
    pseudocode : check current position detail if long order sell, if short order buy 
2. Increase the position
    pseudocode : check current position detail if long order buy, if short order sell 
Reduce or Increase might be more than current position to swap the side. Without information about current side, I can' issue buy or sell command.

Thank you Again
Chet Chetchaiyan

**Comment by kroitor** [comment]
> With I want is I would like to make sure that only one position exist in my portfolio either long or short is fine, but not 1 LONG and 1 SHORT positions (Hedge Mode)

You have to be extremely precise with the terms, because _"either long or short"_ means "BOTH" by default.

You can do what you want in many different ways, so it's not entirely clear which specific situation you mean. 

Binance has the following controls:

- `CROSS`(default)  and `ISOLATED` margin modes
- `Hedge Mode` and `One-way mode` (default) 

You can control those things with [implicit API methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) from CCXT as described in the Manual.

You can combine those controls to achieve the functionality you want.

So, if you want just one position (LONG or SHORT), you might want to switch to Hedge Mode + CROSS Margin.
Or you can also do that in One-way mode with ISOLATED margin. It really depends on how you want to build your algorithm, and to do that correctly you will have to figure out and understand the exact meaning of each of those terms. You also have to understand that order side is not the same thing as positionSide.

If you're doing this in Hedge Mode, you can have one position with positionSide LONG or positionSide SHORT.

Then:

> 1. Reduce the position
>    pseudocode : check current position detail if long order sell, if short order buy

a. check your positions (if you have it open, you will see one position)
b. if positionSide is LONG, you place an order with side='sell' and positionSide='LONG'.
c. if positionSide is SHORT, you place an order with side='buy' and positionSide='SHORT'.
d. do not open other positions if you want just one position at a time.

> 2. Increase the position
>    pseudocode : check current position detail if long order buy, if short order sell
>    Reduce or Increase might be more than current position to swap the side. Without information about current side, I can' issue buy or sell command.

a. check your positions (if you have it open, you will see one position)
b. if positionSide is LONG, you place an order with side='buy' and positionSide='LONG'.
c. if positionSide is SHORT, you place an order with side='sell' and positionSide='SHORT'.
d. do not open other positions if you want just one position at a time.

Also, instead of looking into your positions, you can also check the history of your orders and figure out your positionSide from there.

I'd suggest two things:

1. read the entire CCXT Manual from top to bottom very carefully: https://github.com/ccxt/ccxt/wiki/Manual
2. read the entire Binance API doc on perpetual swaps very carefully: https://binance-docs.github.io/apidocs/futures/en/#account-trades-endpoints

Hope it helps.

**Comment by david87-aa** [comment]
yo ....

i hade a same question ... and this is my answer :
( i know what mean Both just i dont need for my project .. i have to know what happend ;) )

        apikey = "XyZ"
        secretapi = "XyZsecret"
        mysymbol = ""
           
        client = Client(apikulcsom, secretapikulcsom)

        futurepositioninfo = client.futures_position_information()          

        for n in range(len(futurepositioninfo)):  
            if float(futurepositioninfo[n]["entryPrice"])  > 0: 
                mysymbol = futurepositioninfo[n]["symbol"]

        lasttransaktion = client.futures_account_trades(symbol = mysymbol)
        
        myside = pd.DataFrame(lasttransaktion)["side"][0]
        
so i check all position , and if had entryprice i check my trade hystory with this symbol and there you have side 

GiHi

**Comment by yurifontoura** [comment]
> yo ....
> 
> i had same question with my project ... and this is my answer : ( i know what mean Both just i dont need for my project .. i have to know what happend buy or sell long or short ;) )
> 
> ```
>     apikey = "XyZ"
>     secretapi = "XyZsecret"
>     mysymbol = ""
>        
>     client = Client(apikey, secretapi)
> 
>     futurepositioninfo = client.futures_position_information()          
> 
>     for n in range(len(futurepositioninfo)):  
>         if float(futurepositioninfo[n]["entryPrice"])  > 0: 
>             mysymbol = futurepositioninfo[n]["symbol"]
> 
>     lasttransaktion = client.futures_account_trades(symbol = mysymbol)
>     
>     myside = pd.DataFrame(lasttransaktion)["side"][0]
> ```
> 
> so i check all position , and if had entryprice i check my trade hystory with this symbol and there you have side
> 
> GiHi

It is a welcome implement. Anyway, it fails if last trade is partial take profit, for example.

To avoid that, we can consider handle the `entryPrice` and ang get last trade `side `, that has the same price. 
Still not excellent, but is an option.

**Comment by abadrangui** [comment]
Hi everyone I found a fun workaround.

Check the 'positionAmt'  value. If this number is _positive_ this position is "BUY" and if it's _negative_ it's "SELL".

Works for me <3
