### ISSUE TITLE
How to place leveraged orders?

### ISSUE THREAD

**Issue by TusharDcs** [ccxt/ccxt#7249]
Hi Team,

how can i place order with leverage in any exchange? is every exchange provide leverage trading or not? and please understand my example.

assume : 
My USD balance is $100
I want to place order 15% of my balance means (15% of $100) $15 with 8x leverage with STOP LOSS 2%.
how can i place this kinds or order using ccxt with exchanges(binance,cex,kraken,bitmax,bittrix,gimini,bitfinex,coinbasepro)

I hope you getting my concern. 
please explain me solution by using same example.

Thanks
Tushar

**Comment by theantiqa** [comment]
Can you give me quick reply due to this my project gonna be hold.

Thanks

**Comment by kroitor** [comment]
@theantiqa @TusharDcs 

> My USD balance is $100
> I want to place order 15% of my balance means (15% of $100) $15 with 8x leverage with STOP LOSS 2%.

You want to use `fetchBalance()` method and then multiply the corresponding value by 0.15 on your side to get 15% of it. The usage of `fetchBalance()` is explained in the Manual.

- https://github.com/ccxt/ccxt/wiki

> how can i place this kinds or order using ccxt with exchanges(binance,cex,kraken,bitmax,bittrix,gimini,bitfinex,coinbasepro)

This is not completely unified, however, you can still do this with CCXT using either the `createOrder` method or with implicit API methods – all of that is also documented in the Manual.

See the examples on how to place various orders. In order to help a bit more precisely we need you to read the entire Manual from top to bottom, we can't really write out all the code in the world for everyone, so, you have to be more specific with the questions. First and foremost, we need to know your programming language, and we also need to know what you have tried already after reading the Manual. We can help if you have a specific piece of code as explained here (make sure to follow all docs precisely (literally to a word) – that will speed up the answer:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
Placing leveraged orders with Kraken: https://github.com/ccxt/ccxt/issues/6438#issuecomment-580731935

**Comment by kroitor** [comment]
Placing leveraged orders with Binance:

- https://github.com/ccxt/ccxt/issues/6978
- https://github.com/ccxt/ccxt/issues/6969
- https://github.com/ccxt/ccxt/issues/6357
- https://github.com/ccxt/ccxt/issues/7217

**Comment by bashman** [comment]
In binance futures. Similar for others. 

```
async def async_setleverage(exchange_id, symbol, leverage, apikey, apisecret, proxy):
    exchange_id = exchange_id
    exchange_class = getattr(ccxt, exchange_id)
    exchange = exchange_class(
        {
            'aiohttp_proxy': proxy, #optional proxy set to None if not proxy need. 
            'apiKey':  apikey,
            'secret': apisecret,
            'enableRateLimit': True,
            'options': {
                # 'defaultType': 'spot',
                'defaultType': 'future',
            },
        }
    )
    #exchange.verbose = True
    setleverage = await exchange.fapiPrivate_post_leverage({'symbol': symbol, 'leverage': leverage})
    await exchange.close()
    return setleverage
```

**Comment by kroitor** [comment]
@bashman thank you!

@TusharDcs let us know if the above info does not answer your question. Feel free to reopen this issue or just ask further questions, if any.

**Comment by ligarius** [comment]
Work for me in bitmex
symbol = 'BTC/USD'
type = 'market'
side = 'buy'
amount = monto_trade
leverage = 50
bitmex.private_post_position_leverage({"symbol": "XBTUSD", "leverage": str(leverage)})
posicion = bitmex.create_order(symbol, type, side, amount)
