### ISSUE TITLE
CORS errors only on few methods

### ISSUE THREAD

**Issue by f-malet** [ccxt/ccxt#7255]
I try to do something easy but i have an error that i don't understand : when I call fetchBalance() (or fetchMyTrades) methods I have this error : 

Access to fetch at 'https://api.binance.com/api/v3/account?timestamp=1594500611242&recvWindow=5000&signature=XXXXXXXX' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field x-mbx-apikey is not allowed by Access-Control-Allow-Headers in preflight response.

Some others methods works like loadMarkets() but these which concerned user seems to be not working.

- OS: Linux
- Programming Language version: Angular
- CCXT version: 1.30.82

```
this.binance = new ccxt.binance({
      apiKey: 'XXXXXXXXXX',
      secret: 'YYYYYYYYY'
      timeout: 30000,
      enableRateLimit: true,
    });

console.log(this.binance.has['fetchMyTrades']); // return true
console.log (this.binance.requiredCredentials); // prints required credentials
this.binance.checkRequiredCredentials(); // not throw AuthenticationError
this.binance.verbose = true;
this.binance.fetchBalance().then( balance => {
      console.log('fetchBalance', balance);
});
```

**Comment by kroitor** [comment]
If you're doing it from a browser (with Angular), you have to do this via a CORS proxy. You might want to run your own CORS proxy or use one of the public CORS proxies. Otherwise the browser will block it. If you do this with Node.js you won't have this issue, so it's related to browsers only (you have to read more about CORS and how it works)

- https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin
- https://stackoverflow.com/questions/32500073/request-header-field-access-control-allow-headers-is-not-allowed-by-itself-in-pr
- https://www.google.com/search?q=Request+header+field+is+not+allowed+by+Access-Control-Allow-Headers+in+preflight+response

For example: 

```JavaScript
this.binance = new ccxt.binance({
      apiKey: 'XXXXXXXXXX',
      secret: 'YYYYYYYYY'
      timeout: 30000,
      enableRateLimit: true,
      proxy: '', 
      proxy: 'https://cors-anywhere.herokuapp.com/',  // ←---------------- using a public CORS proxy
      origin: 'f-malet-binance-client',  // ←-------- any string here, required by the public CORS proxy
});

console.log(this.binance.has['fetchMyTrades']); // return true
console.log (this.binance.requiredCredentials); // prints required credentials
this.binance.checkRequiredCredentials(); // not throw AuthenticationError
this.binance.verbose = true;
this.binance.fetchBalance().then( balance => {
      console.log('fetchBalance', balance);
});
```

Let us know if the above does not answer your question.

**Comment by f-malet** [comment]
Thanks a lot it's working. I made my own proxy with node and cors-anywhere

It's ok for the dev but if I would like to developp my angular app, I'll need to keep this personnal proxy ?

**Comment by kroitor** [comment]
> It's ok for the dev but if I would like to developp my angular app, I'll need to keep this personnal proxy ?

Yes, because Binance's API won't work otherwise, since they don't declare the Access-Control-Allow-Origin header which would allow you to use the Binance's API from a browser under your own domain. Basically, this is caused by the browser-based security rules. You might really want to read on Access Control and CORS if you want a deeper understanding on the subject.
