### ISSUE TITLE
How to fetch price of underlying indexes at OKEx?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7264]
Hello,

I would like to use the method `futures_get_instruments_instrument_id_index` to fetch price of BTC/USDT underlying index at OKEx but what is the proper way of using exchange specific method?

https://www.okex.com/docs/en/#futures-index_information

Thank you,

```
import ccxt
ok = ccxt.okex()
ok.secret = ''
ok.apiKey = ''
ok.password = ''
ok.futuresGetInstrumentsInstrumentIdIndex('BTC/USDT')
```

`AttributeError: 'str' object has no attribute 'items'
`

**Comment by kroitor** [comment]
1. Always enable the rate-limiter! https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
2. For that reason always read the entire Manual very carefully! (https://github.com/ccxt/ccxt/wiki/)
3. The implicit methods require a dictionary of params, not a string! That is also documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
4. Your instrument_id should be equal to the instrument_id `BTC-USDT` corresponding to `BTC/USDT` unified symbol. The difference is also explained in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
5. Also, you can't get an index for `BTC/USDT`, because it's a spot market that does not have an index. You should use an id of a futures market, for example, at this time: `BTC-USDT-200717`, `BTC-USDT-200724`, `BTC-USDT-200925` or `BTC-USDT-201225`, this is documented here: https://www.okex.com/docs/en/#futures-index_information

```Python
import ccxt
from pprint import pprint

exchange = ccxt.okex()
exchange.apiKey = 'YOUR_API_KEY'
exchange.secret = 'YOUR_API_SECRET'
exchange.password = 'YOUR_PASSWORD'

exchange.enableRateLimit = True  # ←--------- required!

exchange.load_markets()
symbol = 'BTC-USDT-200717'
market = exchange.market(symbol)
params = {
    'instrument_id': market['id'], # ←------------------ market id here instead of a symbol
}

response = exchange.futuresGetInstrumentsInstrumentIdIndex(params)
pprint(response)
```

Let us know if the above does not answer your question.
