### ISSUE TITLE
Is there a way to get an smaller CCXT object in PHP?

### ISSUE THREAD

**Issue by frankhubrepo** [ccxt/ccxt#7294]
I'm currently creating php CCXT objects in this manner:

```
$exchange = '\\ccxt\\' . $id;
   $exchange_class = new $exchange (array (
    'timeout' => 30000,
));
```

However, I only need to access the $exchange_class->fetch_ticker() method.

The issue is that i need to perform this operation several times in the script, but the exchange_class object is too massive, causing the script to crash. Is there a way to get an smaller object with less properties (perhaps only the fetch_ticker method)?

I already tried adding the 'has' array to the class instantiation and setting everything else to false, but the result is the same.

**Comment by kroitor** [comment]
> The issue is that i need to perform this operation several times in the script, but the exchange_class object is too massive, causing the script to crash.

In general, instantiating all exchange classes should not cause a crash.
Can you post a minimal, but complete snippet in PHP (10-20 lines) to reproduce the crash? (We need something to work with and we don't want to imagine the code – ideally, we should be able to copy-paste and run it).
Also, please, paste your PHP version, your CCXT version and the error stacktrace, as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by frankhubrepo** [comment]
Thank you for replying. This is the code:

```
$codes=['BTC'=>'Bitcoin to USD',
//      ...
// this is an array of 20 currencies, all to USD
        ];

foreach ($codes as $clave => $code) {

$exchanges = ['binance','huobipro', 'okex3', 'bitfinex', 'kraken'];

foreach ($exchanges as $id) {
    $exchange = '\\ccxt\\' . $id;
   
   $exchange = new $exchange (array (
    'timeout' => 30000,
));
   
   try {

    $symbols = [ $clave.'/USDT' ];
    
    var_dump($symbols);

// 	foreach($symbols as $symbol){
//     $result = $exchange->fetch_ticker ($symbol);
		
// 	$bid = $result['bid'];
	
// 	$bidlist = $bid;
//     $sql = "INSERT INTO crypto_prices (currency,exchange, avg_price, query_time)
// 		VALUES ( '".$clave."','".$id."','".$bidlist."',CURRENT_TIMESTAMP)";

// 		if ($conn->query($sql) === TRUE) {
// 			echo "Success";
// 		} else {
// 			echo "Error: " . $sql . "<br>" . $conn->error;
// 		}

// 	}
} catch (\ccxt\NetworkError $e) {
    //echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
    echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}
}
}
```

**Comment by kroitor** [comment]
@frankhubrepo let's clarify, do you understand:

1. how the above code works?
2. how to configure your web-server? (if you're using a web-server to invoke the above PHP script)

Also, have you read the CCXT Manual? Probably not, because in your code you're missing some critical pieces explained in the Manual. I would highly recommend you to read the Manual from top to bottom very carefully, that is actually required in order to work with this library efficiently.

> I'm not sure what is the CCXT version as this is an old project I took over, but I think it's at least 2 years old.

That, in particular, is documented in the Manual (so, if you read and follow it carefully, you should be aware of how to get the CCXT version):

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

The problem is that your question is not really related to using the CCXT, but more like a question on how to code your task to solve it correctly. In other words, it's more about the proper code design to solve your task, and it's less about CCXT itself or the usage of CCXT.

No offense, but the code you've posted above has a very poor architecture (I would call it noob code), as if the author does not understand resource utilization principles. So, on the outside loop, it walks over 20 `$codes` and for each of the `$codes` it creates 5 `$exchanges` in the inside loop. That is making 20 * 5 = 100 exchanges. Moreover, when it's done in the internal loop, it drops the exchange and then recreates it again for the next of $codes. That is not how you're supposed to use the exchange instances. Instead you should have the exchange-instances **pre-created and reused** upon walking over the 20 `$codes`. That will ensure that you only have 5 exchange instances, instead of 100.

So you should switch places of the inner loop ←→ outer loop.

> I can't tell you the exact error stack trace because I just get a "this site can't be reached. website unexpectedly closed the connection"

Do you understand what that error means and why it happens? If you google it, you'll probably find the answer, namely, it happens when your script has an error that is not handled properly.

Do you know how to use your webserver and configure logging in the webserver and in PHP in order to find the cause of the error?

↑ If your answer to the above questions is "no" – that is the real cause of your trouble. Also, you don't have to even use a webserver to invoke a PHP program. Because it can do the job without a webserver in pure PHP. However, you have to be skilled and confident with the PHP principles to properly design the code. The CCXT library assumes that you know very well first and foremost the programming aspects of the language you're using. If you're not confident in that, you may need to spend more time with that. Because a skilled PHP developer has to answer "yes" to all of the above questions.

So, without knowing anything about your task and your program structure (the pieces you haven't posted), I would suggest to rewrite it like so at the very least:

```PHP
<?php

// apparently, you have some other code here...

$exchange_ids = array('binance','huobipro', 'okex3', 'bitfinex', 'kraken');
$exchanges = array();

foreach ($exchange_ids as $id) {
    $exchange = '\\ccxt\\' . $id;
    $exchanges[$id] = new $exchange(array(
        'enableRateLimit' => true, // required by the Manual
    ));
}

$codes = array(
    'BTC' => 'Bitcoin to USD',
    // this is an array of 20 currencies, all to USD
);

foreach ($codes as $clave => $code) {
    foreach ($exchanges as $id => $exchange) {
        try {
            $symbol = $clave . '/USDT';
            var_dump($symbol);
            $result = $exchange->fetch_ticker ($symbol);
            $bid = $result['bid'];
            $sql = "INSERT INTO crypto_prices (currency,exchange, avg_price, query_time) " .
                " VALUES ( '".$clave."','".$id."','".$bid."',CURRENT_TIMESTAMP)";
            if ($conn->query($sql) === TRUE) {
                echo "Success";
            } else {
                echo "Error: " . $sql . "<br>" . $conn->error;
            }
        } catch (\ccxt\NetworkError $e) {
            //echo '[Network Error] ' . $e->getMessage () . "\n";
        } catch (\ccxt\ExchangeError $e) {
            echo '[Exchange Error] ' . $e->getMessage () . "\n";
        } catch (Exception $e) {
            echo '[Error] ' . $e->getMessage () . "\n";
        }
    }
}

// apparently, you have some other code here...

?>
```

I would also highly recommend to update your CCXT version, because just by seeing `okex3` in the code I can tell that this is really a very old version of CCXT. The `okex3` (v3) has replaced the okex v1 and in CCXT it was renamed to `okex` long ago. So, if you're still using the `okex3` label, that indicates a very old version number, prior to renaming. I really recommend to:

1. update your version of CCXT
2. change `okex3` to `okex` in your code after updating it

I hope the above answers your questions. Feel free to reopen it or just ask further questions if any. However, please, note that we can't teach everyone about the basics of PHP – that is physically impossible, even if we wanted to, hope for your understanding. We would be happy to answer CCXT-specific questions, though.
