### ISSUE TITLE
[bitfinex2] possible metadata issue with amount formatting on USDT/USD

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7310]
const exchangeId = 'bitfinex2';
        const exchange = new ccxt[exchangeId]();
        await exchange.loadMarkets();

        console.log(ccxt.version);
        console.log(exchange.amountToPrecision('USDT/USD', 104.1982751584727))

```
> 1.31.43
> 104.1982751584727
```

The order than comes back for the exchange from`createLimitOrder` :

```
{
        "info": [47776174708, null, 1595236461460, "tUSTUSD", 1595236461460, 1595236461460, -104.19827516, -104.19827516, "EXCHANGE LIMIT", null, null, null, 0, "ACTIVE", null, null, 1.0018, 0, 0, 0, null, null, null, 0, null, null, null, null, "API>BFX", null, null, null],
        "id": "47776174708",
        "clientOrderId": "1595236461460",
        "timestamp": 1595236461460,
        "datetime": "2020-07-20T09:14:21.460Z",
        "symbol": "USDT/USD",
        "type": "limit",
        "side": "sell",
        "price": 1.0018,
        "amount": 104.19827516, <--- different to what was passed in
        "cost": 0,
        "average": 0,
        "filled": 0,
        "remaining": 104.19827516,
        "status": "open"
}
```

**Comment by kroitor** [comment]
@npomfret i think, we'll add an option for controlling the amountToPrecision behavior, thx for the feedback!

**Comment by kroitor** [comment]
@npomfret actually, after looking more carefully into the `info` – that's the value returned from the exchange itself. CCXT does not cut it down upon parsing or upon submitting the order:

```
> const ccxt = require ('./ccxt')
undefined
> const exchange = new ccxt.bitfinex2({'enableRateLimit': true})
undefined
> exchange.loadMarkets ()
Promise { <pending> }
> exchange.numberToString (104.1982751584727)
'104.1982751584727'
```

So, apparently Bitfinex2 truncates it down to precision on the exchange side upon submitting the order. You may want to ask them about it, but they will most likely say that this is according to the market precision settings. If our assumption is correct and it truncates it on the exchange side – there's practically nothing we can do about it on the user side.

Let me know if that does not answer the question. Feel free to reopen it or just ask further questions if any.

**Comment by npomfret** [comment]
Oh right - so we think the exchange precision settings are wrong?

**Comment by kroitor** [comment]
@npomfret i don't think it's wrong, but they are cutting the values down to their precision on the exchange side. In CCXT we did `numberToString` instead of `amountToPrecision`, that is for historical reasons, since at that time `bitfinex2` was a beta, and they didn't have a documented way of retrieving the precisions. We're using the v1 to fetch that info since then. I'll take a look into it and will probably switch it to `amountToPrecision`.

**Comment by npomfret** [comment]
Ah, sorry - I should have explained.  I use both v1 and v2 in my app, and I call `amountToPrecision` before sending any values to ccxt (so that ccxt doesn't change anything that I pass in).  

In this case, the exchange is changing the amount on their side.  And the reason that's happening is because ccxt's `amountToPrecision` function isn't formatting the amount to the precision that the exchange requires (I've tried with _bitfinex_ and _bitfinex2_).

It looks like the exchange is formatting my amount to 8 decimal places after I place the order.

ccxt's has the following:

bitfinex:  `precision: { price: 5, amount: undefined },` -> `amountToPrecision` results in _104.1982751584727_
bitfinex2: `precision: { price: 5, amount: 5 }` -> `amountToPrecision` results in _104.1982751584727_

The above number gets formatted the same for both which is weird, right?  What am I doing wrong here?

**Comment by kroitor** [comment]
@npomfret yep, I understood, and I will try to add a workaround asap. The problem is that Bitfinex did not define the amount precision in their API docs: https://docs.bitfinex.com/docs#price-precision – only price formatting is mentioned there, assuming that the amount is not altered. I am investigating and will fix it soon, hopefully.

**Comment by npomfret** [comment]
Ah I see, so the bitfinex2 value for amount precision is just wrong, it should be undefined?

**Comment by kroitor** [comment]
@npomfret nope, if they cut it down to 8 decimals, it probably has to be defined as `8`. We might have to either hardcode it or fetch it from somewhere. I am looking into it and will get back to you as soon as I can. Thx!

**Comment by npomfret** [comment]
Why is the value of `5` being ignored in bitfinex2?  Is that just a bug?

**Comment by kroitor** [comment]
@npomfret nope, it's not a bug, it's just because they apply the SIGNIFICANT_DIGITS rounding mode to prices, and not to amounts. This is why we had to add an override for `amountToPrecision` in bitfinex.js (inherited from there in bitfinex2.js):

- https://github.com/ccxt/ccxt/blob/master/js/bitfinex.js#L537

**Comment by kroitor** [comment]
@npomfret i've opened a ticket with Bitfinex API support in order to confirm the undocumented rounding of amounts to 8 decimals. Will report back to you as soon as they reply. If our assumptions are correct, we will either obtain this setting from the API somehow, or will hardcode 8 decimals and will reimplement the `amountToPrecision` for it.

**Comment by kroitor** [comment]
```
Hello IgorKroitor

Thanks for getting in touch, I can confirm that 8 significant figures is the maximum for the amount fields for all pairs. I've asked our team to add this to the documentation to prevent any further future confusion, thank you for pointing this out.

If you have any other issues or questions, please let us know.

Kind regards,
Bitfinex.com
support@bitfinex.com
```

@npomfret going to hardcode that shortly.
