### ISSUE TITLE
Kucoin fetch order book

### ISSUE THREAD

**Issue by mapapuche** [ccxt/ccxt#7366]
Hello,

i am looking to migrate my code to this new plugin who look like amazing. 

But i have some trouble, maybe i use it badly ?

I init kucoin class like this:
`exchange_class = getattr(ccxt, 'kucoin')`

I want to do : `kucoin_order_book = kucoin.fetch_order_book('PIVX')`

But i go this error : `ccxt.base.errors.BadSymbol: kucoin does not have market symbol PIVX`

Kucoin has PIVX on his plateform :/ I tried to add BTC-PIVX or BTCPIVX but it's not working too :(

**Comment by kroitor** [comment]
Hi! To use CCXT efficiently, I'd highly recommend to read the entire Manual from top to bottom, because your question is answered there, so it will save your time, really:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

```Python
import ccxt
exchange = ccxt.kucoin({
     'enableRateLimit': True,  # as required by the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
exchange.load_markets()
for symbol in exchange.markets:
    market = exchange.markets[symbol]
    print('Market id'; market['id'], 'symbol', market['symbol'])
```

**Comment by frosty00** [comment]
`PIVX` is not a symbol, it is a currency code. To fetch the orderbook of `PIVX/BTC` you would have to do 

```
kucoin.fetch_order_book('PIVX/BTC') 
```

or

```
kucoin.fetch_order_book('PIVX/USDT') 
```

**Comment by mapapuche** [comment]
Thank you. Indeed i'll take some time to read it first
