### ISSUE TITLE
explicit conversion of cost/price/fee/amountToPrecision

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#742]
Hey,

as it touches base class I'd rather ask first and than PR (if you agree).

Of the four `*ToPrecision` functions, the latter returns `number` while the first three return `string`.

I believe that in userland we (users) primarily work with numbers, not strings and in most cases, JS silently coerces types for us so it goes unnoticed.

Although, that coercion is not universal. I'm not able to find my open order in an orderbook if I do it in the following manner:
```
openOrder.price === orderBookEntry[0];
```
I guess that there exist other types of cases when this implicit coercion breaks (maybe silently) userland code.

In general, I would strongly prefer that the primary type for financial figures be `number`, not `string`.

How do you feel about that?

**Comment by kroitor** [comment]
Hi! 

> Of the four *ToPrecision functions, the latter returns number while the first three return string.

The reason for that is because floats don't save the precision at all. Basically, it boils down to the arbitrary precision support, related to this issue: #522 . 

> In general, I would strongly prefer that the primary type for financial figures be number, not string.
> How do you feel about that?

Turns out in JS you either have precision control with strings, or no precision control with floats. So the way to fix this is to have a single `toPrecision (numberOrDecimalFloatString, decimalDigits, typeOfTruncationOrRounding)` with support for arbitrary precision math on strings like "0.00000000000000031243 x 13213248329473298479234.3"... 

Switching to arbitrary precision isn't too difficult, actually, we can do a bunch of base-wrapper-methods and integrate any lightweight existing lib to do the job for us. So it's a matter of choice of the lib in question, I believe, we will have to start the migration sooner or later anyway... )

Or, would you suggest another alternative?

**Comment by mkutny** [comment]
I think that we speak about two different things.

1. Arbitrary precision math itself.

As `floats` don't save precision all implementations have an internal representation (container) for floats. For example, `ccxt` uses `strings` and it might happen that some libs also use `string` but others may employ whatever container they found useful.

I'm a supporter of switching to a lightweight lib also `ccxt` tiny math functions do their job fairly well too.

2. Userland.

Once libs finish their arbitrary precision math they return the result and this result (IMHO) should be `number`, not internal container object, so in userland, we can do something like `(bid+ask)/2`.

Because `ccxt` **happen** to store math objects in `strings` JS automatically (and silently for the users) coerces those math objects to `numbers` so `(bid+ask)/2` just works. And as it "just works" I believe that the vast majority of users even are not aware that they receive `strings`, not `numbers`.

But in some cases, this implicit conversion does not happen and it breaks userland code.

If instead of
```
return parseFloat (price).toFixed (this.markets[symbol].precision.price)
```
we do
```
return parseFloat(parseFloat (price).toFixed (this.markets[symbol].precision.price))
```
that would not ruine `ccxt` math but would help avoid implicit coercion bugs.

**Comment by kroitor** [comment]
> that would not ruine ccxt math but would help avoid implicit coercion bugs.

If we do that right away inside those methods, that would break precision-formatting for exchange APIs, because the same functions are used for building the request, as expected by their engine and precision filters.

> Once libs finish their arbitrary precision math they return the result and this result (IMHO) should be number, not internal container object, so in userland, we can do something like (bid+ask)/2.

We believe this should be a mix of the two (optional):

A. User wants more flexibility over precision: he switches to floats for convenience / coersion, losing a few satoshis on `small volume x fee` multiplication with floats. Most of the time the error goes unnoticeable on both the exchange and in userland.

B. User wants more precision over flexibility: he switched to string representations ensuring the exact values, but having to use the methods for arbitrary precision provided by ccxt, or some 3rd-party lib. We highly recommend you to consider this option in favor of coersion-convenience. I **really do mean** it )

So, I completely agree to everything you said, but at the same time we have to be very careful not to run into problems. Maybe we should add more methods or generalize it differently as a quickfix-measure... Or we may actually do the proper generic implementation to solve this (and related issues) once and for all.

**Comment by mkutny** [comment]
Hmm... It might happen that I simply don't understand something but I really do not see "**OR**" in between "flexibility" and "precision".

I agree with that we use `strings` for calculations. At the same time, I don't see any problems with returning `numbers` after the math is done. I don't say there are no problems, I just don't see them.

Just an excerpt of your poloniex code:
```
        let cost = parseFloat (this.costToPrecision (symbol, amount * rate));
        if (side == 'sell') {
            cost *= price;
        } else {
            key = 'base';
        }
        return {
            'type': takerOrMaker,
            'currency': market[key],
            'rate': rate,
            'cost': parseFloat (this.feeToPrecision (symbol, cost)),
        };
```

Here you don't rely on coercion and do the explicit conversion yourself. I guess you need numbers too!

> A. User wants more flexibility over precision: he switches to floats for convenience / coersion, losing a few satoshis on `small volume x fee` multiplication with floats. 

I feel there may be indeed rounding errors here, maybe you have an example too when `*ToPrecision` helps to avoid it returning a `string` rather than a `number`?

**Comment by kroitor** [comment]
> At the same time, I don't see any problems with returning numbers after the math is done. I don't say there are no problems, I just don't see them.

If you want to compare prices, a strict comparison of floats might yield a miss, if they aren't aligned in terms of significant digits. In other words, you can't compare floats at all, have to use the EPSILON: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON for that. Also, if you do rounding on floats, you will be fine, but if you try truncation, that's where you will run into all sorts of problems with floats. We have to use strings for that. So, apparently, even in userland it's always better to have arbitrary precision to avoid problems. However, we would better keep this optional (floats or arbitrary precision at user's discretion).

> Here you don't rely on coercion and do the explicit conversion yourself. I guess you need numbers too!

This is the "output" function, the result of it goes to the outside world, but, hey, I'm not proud of those lines at all! %)) I believe they should be rewritten. The actual problem is the other place, in the `createOrder()`.

> I feel there may be indeed rounding errors here, maybe you have an example too when *ToPrecision helps to avoid it returning a string rather than a number?

Yes, if we think of it in terms of `createOrder` it becomes obvious. In other methods it does not make any difference (luckily for now).

**Comment by mkutny** [comment]
> Yes, if we think of it in terms of createOrder it becomes obvious.

So if we look at `createOrder` Is there any difference (in terms of results) between:
```
let response = await this[method] (this.extend ({
    'rate': this.priceToPrecision (symbol, price),
```
and 
```
let response = await this[method] (this.extend ({
    'rate': parseFloat(this.priceToPrecision (symbol, price)),
```
?

I mean, does really `parseFloat` loose information?

**Comment by kroitor** [comment]
@mkutny it does not loose info, but it yields an improperly formatted string. The float itself does not loose the precision (within 64 bits), but the float formatting goes wild. So, changing that line would break it, because the value would not pass through precision-filters on the exchange side. Many exchanges are very sensitive to this. Therefore strings are returned to ensure exact formatting. Apart from that, no problems with floats.

**Comment by mkutny** [comment]
Just note, that on the very next line you proceed with:
```
    'amount': this.amountToPrecision (symbol, amount),
```

`amountToPrecision` returns `numbers`, not `strings`.

It looks not consistent when some methods return `numbers` and some `strings` but well... I'll learn to somehow keep up with it )

Thanks for your time anyway )

**Comment by kroitor** [comment]
The above may actually be a bug, not a feature. We don't have it fully "settled" yet, therefore we are open to all proposals. Thx for your feedback as well!
