### ISSUE TITLE
itBit: PAXG/USD price missing

### ISSUE THREAD

**Issue by tansawit** [ccxt/ccxt#7458]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: macOS 10.15.4
- Programming Language version: Python 3.8.4
- CCXT version: 1.33.4

I was trying to get the latest price of the PAXG token from itBit, which is available through its REST endpoint (https://api.itbit.com/v1/markets/PAXGUSD/ticker). However, when I query it using ccxt, I get the error "itBit does not have market symbol PAXG/USD". And when I query the list of markets available for itBit, I seem to get a rather small list, as shown below.

```
#!/usr/bin/env python3
import ccxt
import sys


def main(exchange, base_symbol, quote_symbol):
    return getattr(ccxt, exchange)().fetchTicker(base_symbol + "/" + quote_symbol)["last"]


if __name__ == "__main__":
    try:
        print(main(*sys.argv[1:]))
    except Exception as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)


```

```
$ python3 p main.py itbit PAXG USD
itbit does not have market symbol PAXG/USD
```

**Comment by kroitor** [comment]
Hi!

The problem is that itBit API does not have an endpoint for obtaining all market pairs programmatically. Therefore we have to either update that list manually or scrape it somehow, as explained here: https://github.com/ccxt/ccxt/issues/4970#issuecomment-481966564

I've added those missing pairs to it and you should be able to use PAXG/USD in CCXT version 1.33.5+, the new build will arrive in 15 minutes. Let us know if that does not help.
