### ISSUE TITLE
Pulling trade data for 20coins from Poloniex  simultaneously 

### ISSUE THREAD

**Issue by sdroy101** [ccxt/ccxt#7466]
Is it possible to fetch trades for next Xmins for 20coins simultaneously without any lag?

**Comment by kroitor** [comment]
> without any lag?

That requirement is a little vague )
Some lag is always there, since the communication is not instantaneous.
CCXT is a RESTful library, so it is using the HTTPS REST APIs, that involves a request and a response, meaning at least some roundtrip time to fetch the data. And you have to obey the exchange rules and stay within request rate limits, otherwise they will ban you.

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://docs.poloniex.com/#http-api

> Please note that there is a default limit of 6 calls per second. If you require more than this, please consider optimizing your application using the websocket-based push API, the "moveOrder" command, or the "all" parameter where appropriate.
>
> Making more than 6 calls per second to the API, or repeatedly and needlessly fetching excessive amounts of data, can result in rate limit. Please be careful.
>
> If your account's volume is over $5 million in 30 day volume, you may be eligible for an API rate limit increase. Please email api-support@poloniex.com.

![Screen-Shot-2020-08-15-at-00 18 39](https://user-images.githubusercontent.com/1294454/90294031-2246a980-de8e-11ea-9b1a-66cbaf383141.jpg)

With CCXT Pro + WebSockets you can lower the roundtrip-times by half due to how sockets work in general:

- https://ccxt.pro/

You can't completely eliminate the lag, in other words, so, you have to be a bit more specific )
Closing this for now. Feel free to reopen it or just ask further questions if any.

**Comment by sdroy101** [comment]
Actually, if multiprocessing is used, one can fetch 20 coins simultaneously but that would be too much load on the system. However, without multiprocessing, how can someone fetch data even for 6 coins simultaneously?
