### ISSUE TITLE
ccxt Binance sapiGetMarginOrder: "A mandatory parameter was not sent, was empty/null, or malformed."

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#7475]
ccxt version : 1.33.4
programming language: python 3.7

I try to retrieve isolated margin orders in Binance with the

`exchange.sapiGetMarginOrder({'symbol': 'BNBBTC', 'timestamp': exchange.milliseconds()})`

According to https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md#margin-account-new-order-trade, only symbol and timestamp are requiered.

However, I get the error:
`BadRequest: binance {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."} `

Perhaps, there is a solution, but fetchmytrades do not show them.

Thank you!

**Comment by kroitor** [comment]
@nikky78 the link from your message is pointing to the POST endpoint https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md#margin-account-new-order-trade

And the `sapiGetMarginOrder` corresponds to a different GET endpoint: https://binance-docs.github.io/apidocs/spot/en/#query-margin-account-39-s-order-user_data

I think you confused the GET endpoint with the POST endpoint in this case.

As you can see in the above docs, the `sapiGetMarginOrder` requires either an `orderId` or a `origClientOrderId`

I would highly recommend you to use the unified CCXT API (`createOrder`, `fetchOrder`, `fetchOpenOrders`, etc...) instead of exchange-specific implicit methods, for that I'd advise to read the Manual from top to bottom very carefully – it will really save your time.

Let us know if that does not answer your question.
