### ISSUE TITLE
CancelAllOrders and CancelAllOrdersByPair

### ISSUE THREAD

**Issue by dexter369** [ccxt/ccxt#748]
Do you plan to implement "CancelAllOrders" and "CancelAllOrdersByPair" as I cannot find it at:
https://user-images.githubusercontent.com/1294454/32969545-9a3e0f30-cbf6-11e7-8c71-2ef54d4b889f.png

**Comment by kroitor** [comment]
@dexter369 yes, we actually want to unify all functionality (btw those methods are implemented as custom methods for all exchanges because ccxt implements all endpoints out of the box, so you can use the exchange's custom API (`console.log(exchangeInstance)` or `print(dir(exchange_instance))` to see the full list of available methods with the exchange in question. So you can cancel them all with a custom method, and we will unify it in `cancelAllOrders (symbol = undefined, ...)` soon. Your contributions on this will also be appreciated a lot! Hope this answers your question. Let us know if we can help with anything else for now.

**Comment by dexter369** [comment]
ok thanks, was not aware of the custom method implementations.

**Comment by kroitor** [comment]
Yep, they should work, just consult the docs of the exchange (param names are exchange-specific, this is what "custom" means). We will let you know you when we have those methods unified, in the meantime, if you don't mind, i'd close this issue for now. Feel free to reopen it if needed or just ask questions, if any. Thx!
