### ISSUE TITLE
Please provide valid nonce in Request Nonce (x) is not bigger than last nonce (x)

### ISSUE THREAD

**Issue by asafravid** [ccxt/ccxt#7503]
OS: Windows
Programming Language: Python
- CCXT version - I don't know

What I do is call the following function over and over. I don't know what is the nonce that I should increase

> def connect_to_bit2c(plot, api, balances):
>     # from variable id
>     exchange_id = 'bit2c'
>     exchange_class = getattr(ccxt, exchange_id)
>     exchange = exchange_class({
>             'apiKey'         : api["key"].upper(),
>             'secret'         : api["secret"],
>             'timeout'        : 30000,
>             'enableRateLimit': True,
>     })
>     print('[connect_to_bit2c] Fetching Balances...\n=======================================')
>     balances['data'] = exchange.fetch_balance()
>     print('[connect_to_bit2c] Balances: {}'.format(balances))
>     labels = []

This is the error returned by fetch_balance()
[connect_to_bit2c] Balances: {'data': {'info': {'error': 'Please provide valid nonce in Request Nonce (1598218490) is not bigger than last nonce (1598218490).'}, 'BCH': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'BSV': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'BTC': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'BTG': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'ETC': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'ETH': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'GRIN': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'LTC': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'NIS': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'free': {'BCH': 0.0, 'BSV': 0.0, 'BTC': 0.0, 'BTG': 0.0, 'ETC': 0.0, 'ETH': 0.0, 'GRIN': 0.0, 'LTC': 0.0, 'NIS': 0.0}, 'used': {'BCH': 0.0, 'BSV': 0.0, 'BTC': 0.0, 'BTG': 0.0, 'ETC': 0.0, 'ETH': 0.0, 'GRIN': 0.0, 'LTC': 0.0, 'NIS': 0.0}, 'total': {'BCH': 0.0, 'BSV': 0.0, 'BTC': 0.0, 'BTG': 0.0, 'ETC': 0.0, 'ETH': 0.0, 'GRIN': 0.0, 'LTC': 0.0, 'NIS': 0.0}}}

MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by asafravid** [comment]
Additional Information:
When the interval between calls to `exchange.fetch_balance()` is ~1 minute - I see that the nonce issue doesn't appear
So a follow-up question is - what is the minimal interval "allowed"?

**Comment by kroitor** [comment]
> What I do is call the following function over and over. I don't know what is the nonce that I should increase

There is a problem in your function. It does not respect the rate limits, as explained in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit. Instead of reusing the same exchange instance, you are dropping the old instance and creating a new instance upon every call. Since the rate limiter is a property of the exchange instance, re-creating the instance effectively creates another rate-limiter. The two exchange instances have separate rate limiters.

What happens is:

1. you run that function the first time, it works
2. you run that function the second time, and since the newly created exchange instance does not know about the old exchange instance, the second call happens immediately (without a rate-limiting delay)
3. you keep calling that function over and over and it fails over and over, because you are resetting the rate limiting over and over

What should happen is:
1. you create the exchange instance first
2. then you start calling your function over and over again reusing the exchange instance

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

def fetch_balances(exchange, balances):
    print('[fetch_balances] Fetching Balances...\n=======================================')
    balances['data'] = exchange.fetch_balance()
    print('[fetch_balances] Balances: {}'.format(balances))

# from variable id
exchange_id = 'bit2c'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey' : api["key"].upper(),
    'secret' : api["secret"],
    'timeout' : 30000,
    'enableRateLimit': True,
})

exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes

balances = {}
while True:
    try:
        # reuse the same exchange instance here
        fetch_balances(exchange, balances)
    except Exception as e:
        print(e)
        break
```

Let us know if the above does not help.

---------------

I would highly recommend to update your CCXT to version 1.33.49, i've uploaded some edits for better error handling.

---------------

For the future, please, always follow the guidelines very precisely: 

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. 

Always paste your source code here using [GitHub markdown](https://guides.github.com/features/mastering-markdown/) for readability and padding, surround your code and/or output with triple backticks (&#096;&#096;&#096;), like shown below:

&#096;&#096;&#096;Python
put your code here – something we can copypaste and launch
don't paste one line of code, paste your full short complete code snippet to reproduce it
it has to be short but complete including exchange instantiation, but without your keys of course
&#096;&#096;&#096;

&#096;&#096;&#096;
your output here
&#096;&#096;&#096;
