### ISSUE TITLE
Getting binance historical data of all coins 

### ISSUE THREAD

**Issue by oren0e** [ccxt/ccxt#7543]
Hi,
I apologize if the answer is written in the docs somewhere, I couldn't find it.
Basically what I want is to get historical data like price, market cap, volume and other available variables (like age of the coin) for all the coins in binance without needing to specify the names in a list. I also want to be able to specify the currency in which these prices are listed (same for all the coins is ok), how can I achieve that?
I am aware that I will run into rate limits, so I just wanted to check if this is the way to enable the rate limiter for binance:
```python
exchange = ccxt.binance({
    'enableRateLimit': True,
})
```

Python version: 3.7
OS: Linux Ubuntu 18.04

**Comment by kroitor** [comment]
Hi!

> Basically what I want is to get historical data like price, market cap, volume and other available variables (like age of the coin) for all the coins in binance without needing to specify the names in a list. I also want to be able to specify the currency in which these prices are listed (same for all the coins is ok), how can I achieve that?

First and foremost we recommend to read the CCXT Manual:

- https://github.com/ccxt/ccxt/wiki/Manual

You want to make sure that you understand various types of data and their relations.
Basically, CCXT implements the exchanges that have the endpoints for:

- getting a list of currencies
- getting a list of all currency pairs
- getting the public trade history for a currency pair
- getting the orderbook for a currency pair

↑ That is the primary data, that is used to calculate and derive all other data, like:

- 24h tickers
- OHLCV stats

↑ CCXT also implement the above, that is the intermediary data used to calculate and derive the other end-data, like market cap, volume, etc...

In other words, you would use CCXT to get your primary and intermediary data in order to calculate your end-data yourself. You can use a number of libs for tech analysis and other purposes. CCXT is mostly used to interact with the exchanges directly.

> I am aware that I will run into rate limits, so I just wanted to check if this is the way to enable the rate limiter for binance:

Yes, that is the correct way to enable it.

Let us know if the above does not answer your question. Feel free to reopen it or just ask further questions if any.
