### ISSUE TITLE
what is the issue , kindly help me

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#7572]
I am using bybit testnet account for trading when I do some trading problematically,  It is showing this transaction via a notification on the portal but it is not showing our orders in the position bar or active order bar. what is the issue,
kindly help me.

Thanks in advance!

**Comment by kroitor** [comment]
I'd suggest to forward this question to Bybit's tech support, since we don't maintain or control the Bybit's testnet website. You can create and fetch your Bybit testnet orders with CCXT using the unified API as documented in the CCXT Manual, but we're not responsible for the working of the Bybit's website.
