### ISSUE TITLE
Binance requests limit

### ISSUE THREAD

**Issue by 4nzor** [ccxt/ccxt#7581]
Hi! I need to get the entire history for all tickers, but the limitation makes this process very long (about 8 minutes) for the user, are there any ways to solve this problem without using a proxy?

```
async def get_trades(exchange_, symbol):
    trades = await exchange_.fetch_my_trades(symbol)
    return trades
```
```

async def main():
    exchange = async_ccxt.binance({
        ...
    })
    tickers = await exchange.load_markets()
    tasks = [get_trades(exchange, symbol) for symbol in tickers]
    all_trades = await asyncio.gather(*tasks)
    await exchange.close()
    return all_trades
```
```
loop = asyncio.new_event_loop()
loop.run_until_complete(main())
```

**Comment by kroitor** [comment]
> but the limitation makes this process very long (about 8 minutes) for the user, are there any ways to solve this problem without using a proxy?

Nope, the exchanges impose a rate limit on you, so if you violate it, they will ban you:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://binance-docs.github.io/apidocs/spot/en/#limits

You either split your requests to different machines and synchronize the nonce between them (scale your infrastructure to include multiple machines/IPs), or you schedule the fetches and update the trades in your db for your user in the background, so that you always have a db of most recent trades of the user, or you reduce the number of symbols, or use proxies, or some other kind of load-balancing.

Hope that answers your question. Let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by kroitor** [comment]
@4nzor p.s. you can tweak the rate limiter as described in the CCXT Manual.
