### ISSUE TITLE
Bitmex overload

### ISSUE THREAD

**Issue by bitog** [ccxt/ccxt#7586]
Hi,

I searched issues and found the following snippet to handle bitmex's overload:

```
done = False
while not done:
   try:
       order = exchange.private_post_order_bulk({'orders': orders})
       done = True
   except ccxt.BaseError as e:
       print(e)
       pass
```

I was wondering, if there is an exception that **only** triggers for overload? This one is pretty vague and also triggers if there is no margin balance, and I am sure a lot more. In that case it keeps retrying even though its an exception that needs a break.

Thank you!

**Comment by kroitor** [comment]
@bitog hi!

> I was wondering, if there is an exception that **only** triggers for overload? This one is pretty vague and also triggers if there is no margin balance, and I am sure a lot more. In that case it keeps retrying even though its an exception that needs a break.

Yes: https://github.com/ccxt/ccxt/wiki/Manual#error-handling
Instead of `ccxt.BaseError` you need `ccxt.RateLimitExceeded`, `ccxt.DDoSProtection`, or `ccxt.ExchangeNotAvailable`.

I'd recommend to read the entire Manual from top to bottom, it will save you a ton of time.
Let us know if the above does not answer your question.
