### ISSUE TITLE
how to use bitfinex2 fetch_trades params

### ISSUE THREAD

**Issue by pro-respirator** [ccxt/ccxt#760]
I'm trying to get the last n trades on bitfinex markets, using fetch_trades but it seems that the since/limit parameters are not implemented like on fetch_ohlcv. 
`    

    def fetch_trades(self, symbol, since=None, limit=None, params={}):

        market = self.market(symbol)

        response = self.publicGetTradesSymbolHist(self.extend({

            'symbol': market['id'],

        }, params))

        return self.parse_trades(response, market)

`
Is there a way to use the params argument to pass request items to the api directly? I tried passing a dictionary {'limit_trades': 1000} as params as per the [bitfinex api](https://docs.bitfinex.com/v1/reference#rest-public-trades), but it didn't work.

Sorry if this is a dumb question, I'm new to rest apis

**Comment by kroitor** [comment]
> but it didn't work

Please, be a little more specific next time )

1. You almost did it right, but the `limit_trades` is the v1 parameter, and with v2 the correct parameter name is `limit`:

- https://docs.bitfinex.com/v1/reference#rest-public-trades ← `limit_trades`
- https://docs.bitfinex.com/v2/reference#rest-public-trades ← `limit`

This code does work in your current version:

```Python
import ccxt
bitfinex2 = ccxt.bitfinex2()
trades10 = bitfinex2.fetch_trades('ETH/BTC', None, None, {'limit': 10})
trades100 = bitfinex2.fetch_trades('ETH/BTC', None, None, {'limit': 100})
trades1000 = bitfinex2.fetch_trades('ETH/BTC', None, None, {'limit': 1000})
print(len(trades10), len(trades100), len(trades1000))
```

↑ the above code will print `(10, 100, 1000)`

2. If you update ccxt to version 1.10.297, both `since` and `limit` params will work with fetchTrades as they do with fetchOHLCV.

Let us know if you have any other difficulties with it. 

Thanks!

**Comment by pro-respirator** [comment]
Thanks for the help
