### ISSUE TITLE
Is there a possibility to know the listing datetime of Binance markets?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7614]
Hello,

I was wondering what is the most elegant way to fetch new Binance markets programmatically. My problem is that Binance doesn't return the listing date and time of markets so when I try the `fetchOHLCV` method from 2019-01-01 it answers with no data for markets recently added. 

Any idea how I could avoid this issue or found the listing datetime?

This is how I use the method:

```
client.fetchOHLCV(self.symbol,
                                                 timeframe='1h',
                                                 since=desired_timestamp,
                                                 limit=None
                                                 )
```

Thank you,

**Comment by kroitor** [comment]
> Any idea how I could avoid this issue or found the listing datetime?

Unfortunately, Binance does not specify that info, but you can try fetching historical trades (ohlcv candles are generated from trades), or run a retry-loop to shift your `since` argument over time (or shift exchange-specific pagination arguments) catching the error every time until you start getting the results – that would be your launch date. Also, you can move over time forwards and backwards, and even perform a binary search to try and pin down the launch datetime of a specific pair.

See this related issue: https://github.com/ccxt/ccxt/issues/2740
