### ISSUE TITLE
When will there be support for push-based events?

### ISSUE THREAD

**Issue by ronreiter** [ccxt/ccxt#762]
There are many exchanges that provide push support via websockets or other mechanisms. I don't see there's a framework for that yet but I have seen mentions of supporting this in the documentation.

I would be happy to contribute code if there was a way.

**Comment by kroitor** [comment]
Hi!

See the answer here: https://github.com/ccxt/ccxt/issues/745

We hope to deliver WS support very soon, hopefully, this year. Sorry, but your issue is a duplicate, I'd close it for now, if you don't mind.

> I would be happy to contribute code if there was a way.

Your contributions are welcome! More about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
