### ISSUE TITLE
CCXT in Browser with Snowpack / Parcel.js

### ISSUE THREAD

**Issue by psytron** [ccxt/ccxt#7632]
Trying to use CCXT in Browser by compiling with Snowpack. Seems to output correctly but get error in dependencies. 
- OS: Mac OS Catalina, Chrome Latest 
- Programming Language version: JavaScript ES6
- CCXT version: 1.34.54

```javascript
import  ccxt  from '/web_modules/ccxt.js'
import * as ccxt from '/web_modules/ccxt.js' 
// both throw same error:
```

```
ccxt.js:29101 Uncaught TypeError: Cannot read property 'utils' of undefined
    at ccxt.js:29101 
( var utils$2 = elliptic_1.utils;  elliptic_1 is undefined )
```

How can we use CCXT in browser using ES6 import syntax ?
Snowpack is usually excellent for this.

**Comment by kroitor** [comment]
@psytron you probably want to use the browser bundle, instead of the Node.js module:

- https://github.com/ccxt/ccxt/blob/master/dist/ccxt.browser.js

However, there are certain drawbacks when using it from a browser, like CORS issues...

- https://github.com/ccxt/ccxt/wiki/Install#javascript-for-use-with-the-script-tag
- https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin
- https://github.com/ccxt/ccxt/issues/3193

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. you may also want to minimize it and make it compact. Also, you may want to make your own bundle and only include the exchanges you want to minimize the file size.
