### ISSUE TITLE
Rate limits per API function

### ISSUE THREAD

**Issue by rdbr** [ccxt/ccxt#778]
Rate limiting generally works fine, but some heavy functions like `fetchBalance` and `fetchTickers` have a different rate limit on some exchanges than regular lighter functions. For example, Poloniex doesn't allow multiple `fetchBalance` calls in a row, within the normal rate limit. It would be nice to have a configurable rate limit per API function per exchange on top of the normal `rateLimit`.

**Comment by kroitor** [comment]
@rdbr we already support that mostly (still not documented, however), please read this: https://github.com/ccxt/ccxt/issues/736. We implement a *Token Bucket* rate limiter with support for call cost, bursts, etc, but it is in experimental state currently. For now it will require you to override some methods for controlling the call costs, because that aspect is not completely unified yet. We will be happy if you contribute on that. I'm closing this as a duplicate, if you don't mind.

**Comment by rdbr** [comment]
I have seen #736, but the problem is not solved by defining the `cost` of the function. It would require a Token Bucket per API function, on top of the normal Token Bucket, because after a heavy function, other functions can still be called, only the same heavy function must be delayed.

It could be solved in the application level by using new throttle objects, but than the `throttle` constructor should be available to applications directly.

**Comment by kroitor** [comment]
>  It would require a Token Bucket per API function, on top of the normal Token Bucket, because after a heavy function, other functions can still be called, only the same heavy function must be delayed.

It wouldn't really require multiple token buckets, because a single token bucket can easily handle that behaviour. This can be done by tweaking the logic of current implementation of `throttle()`. It has a queue, and heavy requests from the queue can be skipped while lighter requests may be allowed if the bucket has enough space for that. But you're right, we will have to expose the `throttle` for the user to be able to redefine it.
