### ISSUE TITLE
How to filter all the spot markets? 

### ISSUE THREAD

**Issue by Cinux-Chosan** [ccxt/ccxt#7821]
I found that markets in some exchange may have `spot: true` but some may not! Is there a common way to filter all the spot markets in every exchange?

**Comment by frosty00** [comment]
there is no common way to filter out all the spot markets, this aspect has not been fully unified yet. But we are looking to do add support to distinguish between:

* spot markets
* spot with margin
* futures markets with an expiry
* futures with no expiry and perpetual interest

**Comment by kroitor** [comment]
@Cinux-Chosan In most cases, you can assume that either the `type` and `spot` indicate whether this is a spot market or not, and in cases where both `type` and `spot` are missing, you can assume that it is a spot market. However, since this lib is a work progress, there may be some quirks. Let us know if you find inconsistencies, and we will fix those as soon as we can. After the unification of all markets is complete, there will be proper values in the `type` field everywhere. 

Let us know if that does not answer your question.
