### ISSUE TITLE
When shall I reload market with loadmarkets() ?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7882]
Hi,

I created dedicated [Celery tasks](https://docs.celeryproject.org/en/stable/) to open new orders, update and cancel existing order because it's easy to manage queues and also retransmission in case of network failure, timeout, etc. 

The problem is that arguments of a Celery task need to be serialized which mean only string can be passed as argument (no Python objects). In other words exchange instance can't be passed as an argument when I call a task to open a new order, to update or to cancel existing orders.

For this reason I need to **recreate** a new exchange instance every time I call a task, and I trade on several market types (spot, future). I understand that loadMarket() create a list of available markets for an exchange, but could you please tell me if I need to call the loadMarkets() after the instance is created in the specific cases:

- create an order on Binance (future & spot) with `create_order(**args)` 
- fetch all orders on Binance (future & spot) on a specific symbol with `fetch_orders(symbol, since)`
- cancel an order on Binance (future & spot)  by it's orderId with `fetch_order(id=orderid ...)`

The idea is to minimize the number of calls to an exchange and fasten orders execution.

Thank you,

**Comment by kroitor** [comment]
Hi!

- If you call `create_order()`, `fetch_orders()`, `fetch_order()` on a fresh exchange instance – `load_markets()` is called in the background. The library will load those markets on your first call to any unified method, if you haven't loaded them yet. 

- If you call `load_markets()` more than once – it will not reload the markets, unless you specify a force-reload boolean flag `load_markets(True)`.

That is documented in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

The general approach to solving your problem is to initialize one global instance of Binance beforehand, load the markets on that instance, and then pass the values of several serializeable exchange properties to your Celery tasks. Then, inside each task, you would create another instance of Binance, but instead of loading the markets or calling `create_order` (which would also load the markets), you copy the values of those serializeable properties onto the _"child-instance"_ of Binance. This way you would load the markets on the global instance just once and would then share the loaded info with your Celery tasks.

Check this example:

- https://github.com/ccxt/ccxt/blob/master/examples/js/shared-load-markets.js

It is in JS, but in Python it would be very similar. The main thing is that it contains the list of properties that you have to copy from one exchange instance to another in order to avoid loading the markets multiple times.

In Python it would look like:

```Python
import ccxt

# preload markets once

config = {'enableRateLimit': True}
global_exchange = ccxt.binance(config)
global_exchange.load_markets()

# copy markets and currencies
config.ids = global_exchange.ids
config.markets = global_exchange.markets
config.markets_by_id = global_exchange.markets_by_id
config.marketsById = global_exchange.marketsById
config.currencies = global_exchange.currencies
config.currencies_by_id = global_exchange.currencies_by_id
config.baseCurrencies = global_exchange.baseCurrencies
config.quoteCurrencies = global_exchange.quoteCurrencies
config.symbols = global_exchange.symbols

# later inside a task...

def task(config):
    local_exchange = ccxt.binance(config)
    # no need to load_markets here....
```

Calling `load_markets()` is equivalent to setting those properties manually.

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

Let us know if that does not answer your question.

**Comment by Kinzowa** [comment]
Many thanks for the explanation Igor. If I understand well it's possible to give a config object (Python dictionary) at the creation of the instance so that no loadMarkets() call is executed. Unfortunnatly I'm afraid Celery tasks can't access global variables so the solution proposed should not work, however it should be possible to pass a Python dictionary as config object in the task argument.

**Comment by kroitor** [comment]
> however it should be possible to pass a Python dictionary as config object in the task argument.

Yep, that's exactly what is shown in the python snippet above. You can pass a property of a "global" object to your task, and then inside your task you can assign the passed value to the "local" object. Of course, it has nothing to do with global variable accessibility, i just made up those terms to explain what I mean.
