### ISSUE TITLE
[Bittrex v3] FetchTicker() return empty values for some properties

### ISSUE THREAD

**Issue by karimhossenbux** [ccxt/ccxt#7893]
- OS: any
- Programming Language version: NodeJS
- CCXT version: 1.34.89 && 1.37.4

`fetchTicker()` on version 1.34.89: `last` value is missing.

`fetchTicker()` on version 1.37.4: `high`, `low`, `volume` are missing.

I believe it's related to #7673, noticed a change of endpoint there.

Question is if we need both set of values, how can we do?

Thank you for helping!

**Comment by kroitor** [comment]
Since Bittrex has upgraded their API to v3, there's no way to fetch all that info in one call anymore (as they used to have in v1). Therefore, you have to fetch that info in two separate calls.

If you version is lower than 1.37.6, you can do that using the `exchange.options` property:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

```JavaScript

// fetchTicker -------------------------------------------------------------------------------

// default
exchange.options.fetchTicker.method = 'publicGetMarketsMarketSymbolTicker'
console.log (await exchange.fetchTicker (symbol))

// optional
exchange.options.fetchTicker.method = 'publicGetMarketsMarketSymbolSummary'
console.log (await exchange.fetchTicker (symbol))

// fetchTickers ------------------------------------------------------------------------------

// default
exchange.options.fetchTickers.method = 'publicGetMarketsTickers'
console.log (await exchange.fetchTickers ())

// optional
exchange.options.fetchTickers.method = 'publicGetMarketsSummaries'
console.log (await exchange.fetchTickers ())
```

-------------------------------------------

If you upgrade to CCXT version 1.37.6+ (the new build will arrive in 20 minutes), you can also do the following with unified params overrides:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```JavaScript

// fetchTicker -------------------------------------------------------------------------------

// default
console.log (await exchange.fetchTicker (symbol, { method: 'publicGetMarketsMarketSymbolTicker' }))

// optional
console.log (await exchange.fetchTicker (symbol, { method: 'publicGetMarketsMarketSymbolSummary' }))

// fetchTickers ------------------------------------------------------------------------------

const symbols = undefined // all symbols

// default
console.log (await exchange.fetchTickers (symbols, { method: 'publicGetMarketsTickers' }))

// optional
console.log (await exchange.fetchTickers (symbols, { method: 'publicGetMarketsSummaries' }))
```

Let us know if that does not help. Feel free to reopen this issue or just ask further questions if any.

**Comment by karimhossenbux** [comment]
Wow, that was really fast! I'll test that asap.

Thank you very much @kroitor, keep up the great work you are doing on issues 🙌
Cheers!

**Comment by Pascal66** [comment]
Can I ask if there's a way to merge both functions to have a ticker with all information ?
