### ISSUE TITLE
[binance] BadSymbol error

### ISSUE THREAD

**Issue by Guayab0** [ccxt/ccxt#7906]
Hello, i tried to buy a coin today on binance but it gave me the error "BadSymbol: binance does not have market symbol X". I've read on some other posts that you have to manually update the new symbols. If thats the case, is there any way i can do it myself? Perhaps on a file which contains all the symbols that the program uses and i can just add whatever is missing? Thanks.

**Comment by kroitor** [comment]
Hi!

> I've read on some other posts that you have to manually update the new symbols.

It does not mean that you have to insert each symbol manually, those other posts mean triggering the mechanism for reloading all symbols with `loadMarkets()` + `reload` flag.

> If thats the case, is there any way i can do it myself? 

You can add them by hand, by this is not how this library works. In order to work with this lib efficiently, I would highly recommend to read the entire Manual from top to bottom at least once, that will really save a lot of your time, since it answers most of questions and operates with specific terms.

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- ...

> Perhaps on a file which contains all the symbols that the program uses and i can just add whatever is missing?

This is not how unified symbols are managed across this lib, please, check the links above in order to understand how that is done. Also, see the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples

> i tried to buy a coin today on binance but it gave me the error "BadSymbol: binance does not have market symbol X".

In case of any problem, you have to follow through several steps, precisely in order to provide the info so that we could help you:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help ← we need most of this info in order to resolve this issue quickly

**Comment by Guayab0** [comment]
I tried to give a look to the links you said but i dont understand almost anything, i get the idea but dont how to actually execute it, really sorry for taking up your time on this.
I used the code posted below and it gave me "BadSymbol: binance does not have market symbol YOYO/BTC" as i mentioned it to you before. I also tried YOYO_BTC and YOYOBTC
I found the command "print (exchange.load_markets ())" on the manual and when i put it in the console it gave an insanely big list of symbols. I don't know if thats got to do with anything or not, i found YOYO but not YOYO/BTC.
Using Python 3.8 on Spyder.

```
# -*- coding: utf-8 -*-

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


exchange = ccxt.binance({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
})

symbol = 'YOYO/BTC'
type = 'market'  # or 'market'
side = 'buy'  # or 'buy'
amount = 0
price = None  # or None

# extra params and overrides if needed
params = {
    'quoteOrderQty': 0.6.,  # binance-specific
}

order = exchange.create_order(symbol, type, side, amount, price, params)

print(order)
```

**Comment by kroitor** [comment]
@Guayab0 the set of markets is given to you by the underlying exchange API, you can't add or invent new markets out of thin air, you can only trade the markets that are supported by this or that exchange. If you want to see a list of all symbols supported by Binance like so:

```Python
# -*- coding: utf-8 -*-

import ccxt
from pprint import pprint

exchange = ccxt.binance({
    'enableRateLimit': True,
})

markets = exchange.load_markets()
pprint(exchange.symbols)
```

↑ From there you can see that Binance's YOYO/BTC is called YOYOW/BTC, because it the Waves-version of it.

So, you have to change your code slightly:

```Python
import ccxt


print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
})

exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes if necessary

symbol = 'YOYO/BTC'
type = 'market'  # or 'market'
side = 'buy'  # or 'buy'
amount = 0
price = None  # or None

# extra params and overrides if needed
params = {
    'quoteOrderQty': 0.6.,  # ←------------ are you sure about spending 0.6BTC to buy YOYO?
}

order = exchange.create_order(symbol, type, side, amount, price, params)

print(order)
```

Let us know if the above does not answer your question.
