### ISSUE TITLE
Market Buy Order based on cost.

### ISSUE THREAD

**Issue by homerbong** [ccxt/ccxt#7926]
- OS: Linux 5.4.28-gentoo x86_64
- Programming Language version: typescript 3.8.3
- CCXT version: 1.36.95
- Exchange:  Binance, Huobi Pro, Hitbtc, Binance

I know this issue has been already addressed several but after reading the manual section related to this issue I still have some doubts about it.
My problem is that I want to convert all of my quoted currency in the base currency at market price. 
E.G. I have 80 USDT and I want them to convert them to BTC by placing a buy market order on BTC/USDT
Until now I've bee using the `createOrder` passing both the amount and the price to the function. 
After reading the manual I've seen that there is also the `createMarketOrder` and `createMarketBuyOrder` functions.
First I've verified that all of the exchanges mentioned above have such implementation:

```
this.exchanges.huobipro.ccxt.has['createMarketOrder']
true
this.exchanges.binance.ccxt.has['createMarketOrder']
true
this.exchanges.hitbtc.ccxt.has['createMarketOrder']
true
this.exchanges.okex.ccxt.has['createMarketOrder']
true
```
Then I've seen that some of the exchanges actually manage the buy orders based on the quoted currency and not on the base currency as usual. So I've verified how the above exchanges are initializing the `createMarketBuyOrderRequiresPrice` option by default.
```
this.exchanges.okex.ccxt.options['createMarketBuyOrderRequiresPrice']
true
this.exchanges.binance.ccxt.options['createMarketBuyOrderRequiresPrice']
undefined
this.exchanges.hitbtc.ccxt.options['createMarketBuyOrderRequiresPrice']
undefined
this.exchanges.huobipro.ccxt.options['createMarketBuyOrderRequiresPrice']
true
```
What I wanted to know is if the initialization of such parameter can give some indication whether the exchange supports such a behavior or not since in the future I want to include other exchange, not just the 4 I've been mentioning. In such a manner I could try to handle the market buy order differently according to the exchange.

Any other suggestions you could give in order to try to convert all of my currencies to a single one, in particular to BTC at market price, which is actually my final objective, but with market buy orders seems to be more complicated than with sell.
Thank you very much and let me know if anything is not clear enough.

**Comment by kroitor** [comment]
> What I wanted to know is if the initialization of such parameter can give some indication whether the exchange supports such a behavior or not since in the future I want to include other exchange, not just the 4 I've been mentioning.

Technically, there's a difference between the requirement for an amount in quote currency, and the support for an amount in quote currency. The `createMarketBuyOrderRequiresPrice` option indicates if the exchange requires the amount in quote currency. But not all exchanges that support quote amounts actually require that. For example, Binance supports both and doesn't require either. So, that flag can be used to determine which exchanges will definitely want a quote currency, but nothing more. Most of that aspect is already unified in CCXT. The support for the amount in quote currency across the exchanges that have it – is not unified yet, since this lib is a work in progress. In some exchanges we support the `cost` param override along with exchange-specific param-overrides. 

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1656
- https://github.com/ccxt/ccxt/blob/master/js/bitvavo.js#L786
-...

At this time, until we unify the "support" aspect you will have to look into the code and maybe make a few custom wrappers for some exchanges.

Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions if any.
