### ISSUE TITLE
[bitfinex1] request

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7942]
see https://docs.bitfinex.com/docs/rest-reading-the-api-documentation#query-parameters

bitfinex1 has POST endpoints that have additional query parameters.  For example: `limit=120&sort-1&end=TIMESTAMP`.  Without these you can't for example, get your most recent transactions by default because the default sort order appears to be ascending.

**Comment by kroitor** [comment]
To clarify, is this about bitfinex1 or bitfinex2? Just asking, because the link points to the v2 doc.

**Comment by npomfret** [comment]
Sorry, I strayed from one set of docs to the other without realising.

Ok, so my question is - does anyone know how to get transfers in most-recent-first order?

**Comment by kroitor** [comment]
@npomfret if you need all of them sorted – fetch them all with pagination and sort them locally afterwards?
You can also use the `start` (since) + `end` pagination (bitfinex2.fetchTransactions) to scroll pages backwards, if you just need a subset of most recent transfers. Let me know if that doesn't answer the question. Feel free to reopen it if needed or just ask further questions.

**Comment by npomfret** [comment]
ah - i think it's the limit param filter stuff out.  sorry
