### ISSUE TITLE
conversions using BASE currency and QUOTE currency

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7944]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: python Python 2.7.17
- CCXT version: 1.34.38

REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
N/A

REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
N/A

Hi,

On the internet, there are many web sites that allow one to convert a USD Currency to a BTC Currency

For BTC/USD,    BTC = base currency while USD is the quote currency

What I am looking to be able to do is to enter a USD value as Input and then get the conversion to BTC or ETH or XRP or anything I choose as an output.

Where can I find this?

TIA

**Comment by kroitor** [comment]
You have to understand how the exchange trading works to do that, as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-and-trades-are-related

> What I am looking to be able to do is to enter a USD value as Input and then get the conversion to BTC or ETH or XRP or anything I choose as an output.

You have to get a conversion price from the exchanges of your interest and then divide your USD value by the price. But you will have to specify which price you want to use exactly for your conversion, because there's a dozen of different types of prices, all of them could be used for conversions, depending on the purpose of the calculation:

- market price
- orderbook depth price
- last traded price
- open price
- close price
- high price
- low price
- volume-weighed average price
- ...

Here's a snippet that shows how to calculate what you want using the market price. Usage: 

```shell
python usdconvert.py exchange symbol amount
# for example
# python usdconvert.py binance BTC/USDT 1000  # to convert 1000 USDT to BTC
```

```Python
import ccxt
import sys


try:

    exchange_id = sys.argv[1]
    symbol = sys.argv[2]
    quote_amount = float(sys.argv[3])

    exchange = getattr(ccxt, exchange_id)({'enableRateLimit': True})

    markets = exchange.load_markets()
    market = exchange.market(symbol)

    ticker = exchange.fetch_ticker(symbol)

    market_price = ticker['ask']

    base_amount = quote_amount / market_price

    base_amount = exchange.amount_to_precision(symbol, base_amount)
    quote_amount = exchange.price_to_precision(symbol, quote_amount)
    print('You can buy', base_amount, market['base'], 'for your', quote_amount, market['quote'])

except Exception as e:

    print(type(e).__name__ , str(e))
    print('Usage: python', sys.argv[0], 'exchange', 'symbol', 'amount')
```

Let us know if the above does not answer your question.

P.S. Also, note, that CCXT is Python3-only since January 2020.
