### ISSUE TITLE
How do I create a trailing limit order on the bybit API?

### ISSUE THREAD

**Issue by efz00** [ccxt/ccxt#7967]
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: 1.37

Alright so I'm attempting to make trailing limit orders on Bybit. I was successful in doing this on Bitmex like so:
```
exchange.create_order(symbol = 'BTC/USD', type = 'stop', side = 'buy', amount = 1, params = {
        'ordType': 'Stop',
        'pegPriceType': 'TrailingStopPeg',
        'pegOffsetValue': 0.5 # distance in USD
        })
```

```
What are the required params for the bybit api, it's very confusing. Thanks in advance for your help.
```

**Comment by kroitor** [comment]
As far as I know, at this time Bybit API does not have a documented way of placing pegged trailing stop orders unless you have an open position already. The only meaningful mention of it in their API docs is this entry in the changelog:

<img width="669" alt="Screen Shot 2020-11-12 at 23 21 14" src="https://user-images.githubusercontent.com/1294454/98992101-cd263c80-253d-11eb-9190-ad944b9105cf.png">

> 2020-02-26
> REST API
> Remove trailing_stop field from paramters of place order endpoint. Currently, this field is useless.

So, in order to place a trailing stop with Bybit you must first open a regular position with `create_order` and then set a trailing stop on it with implicit API methods as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
markets = exchange.load_markets()
symbol = 'BTC/USD'

# order = exchange.create_order(...)

# exchange.verbose = True  # uncomment for debugging

market = exchange.market(symbol)
response = exchange.openapi_post_position_trading_stop({
    'symbol': market['id'],
    # 'take_profit': 0,  # Cannot be less than 0, 0 means cancel TP
    # 'stop_loss': 0,  # Cannot be less than 0, 0 means cancel SL
    'trailing_stop': 12.34,  # Cannot be less than 0, 0 means cancel TS
    # 'tp_trigger_by': 'LastPrice',  # take profit trigger price type，default: LastPrice
    # 'sl_trigger_by': 'LastPrice',  # take profit trigger price type，default: LastPrice
    'new_trailing_active':12.34,  # Trailing stop trigger price. Trailing stops are triggered only when the price reaches the specified price. Trailing stops are triggered immediately by default.
})


```

↑ original comments preserved as in the Bybit API docs... 

Change the above for your values and try running it.
Let us know if that does not help. Feel free to reopen this issue or just ask further questions if any.
