### ISSUE TITLE
How to define not readonly keys?

### ISSUE THREAD

**Issue by 4nzor** [ccxt/ccxt#7972]
Can I somehow determine whether apiKey and secret are not readonly, (i.e they can be used to trade )?

```python 
exchange_client = exchange_class({
            'apiKey': ex_wrap.credentials.api_key,
            'secret': ex_wrap.credentials.api_secret,
            'enableRateLimit': True,
            'verbose': False,

            'options': {
                'defaultType': self.ex_subtype,
            }
        })

exchange_client.is_support_trading() # for example like this 
```

**Comment by kroitor** [comment]
There is no general unified way of doing that check of the keys yet, since very few exchanges actually return the necessary info from the API itself. However, you can still try to run a bunch of custom tests to check for specific permissions, say, place a limit order at a price that won't fill, etc. Also, check this PR: https://github.com/ccxt/ccxt/pull/1424
Let us know if the above does not answer your question.
