### ISSUE TITLE
HuobiPro fetch_ohlc does not use since argument and only returns latest data

### ISSUE THREAD

**Issue by degloff** [ccxt/ccxt#7981]
CCXT for HuobiPro does not return properly OHLC 

Check this:

https://github.com/ccxt/ccxt/blob/97874a8562026087c836a269246ce27665113497/python/ccxt/async_support/huobipro.py#L728

No reference is made to since. It always returns the latest num data elements.

ccxt version: 1.37.51

**Comment by kroitor** [comment]
This Huobi API endpoint does not have any params that would allow to specify a timerange: https://huobiapi.github.io/docs/spot/v1/en/#get-klines-candles

**Comment by degloff** [comment]
Oh, yes I just check it too, so bad. Need to use the websocket interface to get historical data

https://huobiapi.github.io/docs/spot/v1/en/#get-klines-candles

"This API doesn't support customized period, refer to Websocket K line API to get the emurated period value."

**Comment by kroitor** [comment]
As you can see, CCXT already applies the since+limit filtering on the client side a few lines below, as for the server-side filtering – i'm afraid we can't do much about it until the exchange adds the support for OHLCV pagination to the API. Let us know if we are missing something or if the above does not answer your question. Feel free to reopen this issue or just ask further questions if any.

**Comment by degloff** [comment]
What about using emulated version of the REST call using the websocket interface?

**Comment by kroitor** [comment]
@degloff emulation will work, however, CCXT is REST-only. [CCXT Pro](https://ccxt.pro) = CCXT + WS. However, at this time historical queries on OHLCV are not supported in CCXT Pro yet. We will add it asap.

**Comment by degloff** [comment]
@kroitor hm, Karaken is also wrong. seems the inteface of kraken allows a since but the implemention in CCXT is wrong.

https://www.kraken.com/features/api#get-ohlc-data

**Comment by kroitor** [comment]
@degloff this is answered here:

- https://github.com/ccxt/ccxt/issues/4136#issuecomment-437136014

Also, documented here:

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

Kraken will return candles within (now - X candles; now) at most, and it will apply the `since` argument to that range. It won't allow you to get far back into the history. I think, for Kraken the limit is at 720 or 1440 candles into the past, depending on your timeframe.

**Comment by kroitor** [comment]
@degloff in other words, there is almost always a reason why it works how it works, and most often the limitation is not on our side. Let me know if that does not answer your question.

**Comment by kroitor** [comment]
@degloff for Kraken the fallback solution is to paginate over public trades with `fetchTrades` to build the OHLCV history from ticks: https://github.com/ccxt/ccxt/blob/97874a8562026087c836a269246ce27665113497/python/ccxt/base/exchange.py#L1617

**Comment by degloff** [comment]
@kroitor oh good idea I try that out. And test a few more :). Thanks for the reply
