### ISSUE TITLE
many orders created problem

### ISSUE THREAD

**Issue by ref-dat** [ccxt/ccxt#7982]
hi guys, i'm building a bot for buying and selling orders in Binance automatically, and i add one rule for taking orders using CCXT library:

i did for buying:

if budget> float(markets[p12]['bidQty']):
fail = True
break

and for selling

if budget > float(markets[p21]['askQty']):
fail = True
break

what i want from this is that if i have an amount of 1000 USDT for example, then bot must take only from order that is more than my amount in bid and ask panel.

problem is that Binance always taking more than one order(two orders or more) instead of just taking one as i want

so, is anyone have an idea about how to do this?

**Comment by kroitor** [comment]
Hi!

First of all, do you understand how orders are matched in the orderbook?

- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-and-trades-are-related

In order to be able to help you, we need a complete short snippet of code, something we could copy, launch and test, without your keys. Please, paste the code to reproduce it in this issue using GitHub markdown for readability, including the exchange instantiation code and the CCXT calls. We also need your verbose-mode request/response output as well as your version numbers, and other details as described in the FAQ: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
Depending on your traded symbol, comparing the budget in USDT to the bidQty or to the askQty is not always something you want, because you can't put a comparison sign between values in quote currency (USDT) and values in base currency (bidQty/askQty) directly. The difference between base, quote, and other terms is also explained in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids. In general, I would highly recommend to read the entire Manual from top to bottom, it has a lot of useful info and it will definitely save your time.

**Comment by ref-dat** [comment]
Thank you very much for your helpful information bro.
