### ISSUE TITLE
Do all exchanges include fee in the amount?

### ISSUE THREAD

**Issue by mak1986** [ccxt/ccxt#8003]
Say that I place a buy order with  1 TRX for 0.25 USD and lets say that the maker fee is 0.02% = 0.0002 

The scenarios I can think of is:

1. You receive 0.9998 TRX which is 1-0.0002
2. You receive 1 TRX but you pay 0.25*1.0002 = 0.25005
3. I'm wrong and it should be calculated otherwise.

What is the correct behaviour or does it differ between exchanges?

Another quick question Is there a way to prevent an order to be created if its going to be charge as taker fee?

**Comment by kroitor** [comment]
> The scenarios I can think of is:
> 
> 1. You receive 0.9998 TRX which is 1-0.0002
> 2. You receive 1 TRX but you pay 0.25*1.0002 = 0.25005
> 3. I'm wrong and it should be calculated otherwise.
> 
> What is the correct behaviour or does it differ between exchanges?

It's a bit more involved, but not that hard: in general, when you place an order to buy 1 TRX for 0.25 USD, the fee is applied upon the settlement of the trade. So, the calculation goes as follows:

1. The cost of your trade is 1 TRX x 0.25 USD = $0.25 USD
2. Since you're buying you will get 1 TRX, so your TRX balance will increase by 1
3. You will give 0.25 USD, so your USD balance will decrease by 0.25
4. The fee will be applied to the fee side, and that depends on the exchange in question, there can be 5 different scenarios:
    - the exchange always deduces the fee from your balance in the base currency (TRX), regardless of the side of your trade
    - the exchange always deduces the fee from your balance in the quote currency (USD), regardless of the side of your trade
    - the exchange always deduces the fee from your balance in the currency you get (TRX or USD), depending on the side of your trade
    - the exchange always deduces the fee from your balance in the currency you give (TRX or USD), depending on the side of your trade
    - the exchange always deduces the fee from your balance in a 3rd currency (like fees in BNB on Binance BTC/USDT)

The indication of the fee side is exchange-specific and is not fully unified yet, but you can use the `calculateFee` method in order to predict the fees to a certain extent, though this lib is a work in progress, so you have to check those results manually until we finish the unification of that aspect.

> Another quick question Is there a way to prevent an order to be created if its going to be charge as taker fee?

Yes, use the params-overrides to specify a post-only flag for the exchange in question:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-params

The post-only feature, is currently also exchange-specific, you have to look up if the exchange supports it in their API docs and specify a proper flag in your `createOrder` params, depending on the exchange in question. Basically, post-only means _"the order should not be placed if it would be matched immediately, so the order has to live on the orderbook for at least some time, making it a maker order by definition"_.

Let us know if that does not answer your question.

**Comment by mak1986** [comment]
@kroitor  Thank you for this detailed explanation.
