### ISSUE TITLE
Trying to fetch market data ()/deribit

### ISSUE THREAD

**Issue by MilicaMedic** [ccxt/ccxt#8039]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: macOS High Sierra v. 10.13.6
- Programming Language version: Python 3.7.3
- CCXT version: ccxt==1.28.13
- Exchange: deribbit
- Method: get_book_summary_by_instrument

Hi,
I'm trying to use the method :
```
response = drbt.get_book_summary_by_instrument({'instrument_id':'BTC-27NOV20-8000-C'})
```
I'm getting an error:
```
AttributeError: 'deribit' object has no attribute 'get_book_summary_by_instrument'
```
I'm getting the same error without passing the instrument_id as a parameter:
```
response = drbt.get_book_summary_by_instrument('BTC-27NOV20-8000-C')
```
Is there some method to get market data from deribit, as 'get_historical_volatility', 'get_book_summary_by_instrument', 'get_order_book', 'get_trade_volumes', etc. 

THanks,
Milica

**Comment by kroitor** [comment]
@MilicaMedic hi!

You can print all supported methods as documented in the Manual on the implicit API methods:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.deribit({'enableRateLimit': True})
pprint(dir(exchange))
```

You will find these methods:

```
[
...
'publicGetGetBookSummaryByInstrument',
...
'publicGetGetOrderBook',
...
'publicGetGetTradeVolumes',
...
...
...
'public_get_get_book_summary_by_instrument',
...
'public_get_get_order_book',
...
'public_get_get_trade_volumes',
]
```

Just from their names it is obvious what exactly they do. You can see the corresponding endpoints here:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/deribit.py#L125

In order to use those methods, you should supply a single dictionary of params as you do in the first line of code you've posted above.

- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
- https://docs.deribit.com/#public-get_book_summary_by_instrument

Also, instead of using the non-unified implicit `public_get_get_order_book` i'd recommend to use the unified `fetchOrderBook()/fetch_order_book()`. In general it is recommend that you prefer the unified CCXT API over the implicit CCXT endpoints:

- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#unified-api
- https://github.com/ccxt/ccxt/wiki/Manual#order-book

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.deribit({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging

symbol = 'BTC-27NOV20-8000-C'
market = exchange.market (symbol)
pprint(market)

print ('--------------------------------------------------')

book_summary = exchange.public_get_get_book_summary_by_instrument ({
    'instrument_name': market['id'],
})
pprint (book_summary)

print ('--------------------------------------------------')

orderbook = exchange.fetch_order_book(symbol)
pprint (orderbook)

print ('--------------------------------------------------')

trade_volumes = exchange.public_get_get_trade_volumes ({
    'extended': True,  # optional
})
pprint(trade_volumes)

```

I'd highly recommend to read the entire Manual from top to bottom – it will save your time. Let us know if the above does not answer your question. Feel free to reopen this issue or just further questions if any.

**Comment by MilicaMedic** [comment]
Thanks for the help!
