### ISSUE TITLE
HitBTC & HitBTC2 fetchTrades

### ISSUE THREAD

**Issue by professorkolik** [ccxt/ccxt#807]
Hi @kroitor ,

I'm very appreciated for your/team work!

I'm trying to fetchTrades for HitBTC, and seems it not work on step loadMarkets, I'm trying to figure out by myself, but seems it's takes too long time

CCXT v.1.10.337

Here is the possible code
```
const ccxt = require('ccxt');
const hitbtc = new ccxt.hitbtc2({verbose: true});

var response = await hitbtc.fetchTrades('BTCUSD').catch(function (error) {
   console.log(error);
});
```

Didn't reject on any exception.

Verbose 
```
hitbtc2 GET https://api.hitbtc.com/api/2/public/symbol 
Request:
 {} undefined
```

May be you can give some advise!
Thank you

**Comment by kroitor** [comment]
@professorkolik hi! 

You're using an exchange-specific **market id** (`BTCUSD`), instead of using a cross-exchange compatible **symbol** (`BTC/USD`):

The difference is explained here (I highly recommend to read the entire Manual):
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

- https://github.com/ccxt/ccxt/blob/master/examples/js
- https://github.com/ccxt/ccxt/blob/master/examples/js/arbitrage-pairs.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/symbols.js

I'd close this issue as a duplicate if you don't mind. Let us know if you have any other questions. Thx!

**Comment by professorkolik** [comment]
Thank you for your quick response @kroitor.

But actually I tried different formats of symbols. The result is the same

**Comment by kroitor** [comment]
@professorkolik have you tried any of the above examples?

**Comment by kroitor** [comment]
@professorkolik try

```
node node_modules/ccxt/examples/js/tickers bitfinex BTC/USD
```

**Comment by professorkolik** [comment]
I tried formats 'BTCUSD', 'BTC/USD', 'BTC/USDT'

This line
```
node node_modules/ccxt/examples/js/tickers bitfinex BTC/USD
```

returning correct response

**Comment by professorkolik** [comment]
@kroitor 

I'm sorry, the issue was in my DB, thank you for your time
