### ISSUE TITLE
Okex swap create_order

### ISSUE THREAD

**Issue by stdt99** [ccxt/ccxt#8136]
- OS:  win10
- Programming Language version: python 3.7.3
- CCXT version: 1.39.48

Try this #7415
If contract price 1-9$ it works fine, if price 0.378 recieve "Open order quantity exceeds limit"
Sorry Im noob)

**Comment by kroitor** [comment]
@stdt99 catch the errors in try-except and handle them right, also make sure that your orders pass the limits as described in the Manual. In general, we highly recommend to read the Manual from top to bottom – it will save you a ton of time since most of these questions are already answered there.

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Let us know if that does not help.

**Comment by stdt99** [comment]
okex {"error_message":"Open order quantity exceeds limit","result":"true","error_code":"35039","client_oid":"","order_id":"-1"}

**Comment by kroitor** [comment]
@stdt99 do you have a question on that error message?

**Comment by stdt99** [comment]
Polno..
