### ISSUE TITLE
A few doubts when creating orders

### ISSUE THREAD

**Issue by rubobaquero** [ccxt/ccxt#815]
I have to deal with a lot of exchanges. When I am going to make an order, is impossible to me to know a few (important) things without actually testing them manually and reading each exchange docs:

- How can i check if the exchange allows market orders?
- How can i know the minimum amounts of trading for each exchange?
- How can i know if i should put the price per coin or the total price when making an order? For example, if i want to buy 200 XRP at 0.00001676 each one, i don't know if i should pass 0.00001676 or 0.003352 as price argument.

Thanks in advance kroitor!

**Comment by kroitor** [comment]
Unfortunately, for now most answer to your questions are negative, however, as you know, we are working very hard to deliver most of listed features, because we need them for our own needs as well... So, it's a work in progress (under development).

> How can i check if the exchange allows market orders?

Currently, an exchange will throw an exception if you submit a market order where it is not allowed, yet it still requires to try the submission first. A solution to that would be to add a flag to each exchange that would clearly designate whether an exchange has support for market orders or not.

> How can i know the minimum amounts of trading for each exchange?

We have started the work on this and for some exchanges we have defined `exchange.market['BTC/USD']['limits']` and `exchange.market['BTC/USD']['precision']`, if you look at those structures, you'll see how to use it. However, those structures are not yet defined for all exchanges, because this is still a work in progress (most of is done in a very small team of 2-3 people with the help of the community). Let us know if you find undefined limits and precision, or, it would be even better, if you could submit a PR (see how those things are defined, where present already).

> How can i know if i should put the price per coin or the total price when making an order? For example, if i want to buy 200 XRP at 0.00001676 each one, i don't know if i should pass 0.00001676 or 0.003352 as price argument.

In 99% of cases the amount of the order is in **base** currency (before the slash in a *symbol*). However, you're right, there's no flag that would tell that explicitly. We would add it sooner or later, or, once again, your PRs and contributions on that are welcome as well.

I know, the above may not be a very helpful answer... Let me know if I can help with anything else.

**Comment by rubobaquero** [comment]
Thanks for your answer Kroitor. I have been programming for five days and it is a little bit frustrating to have to check everything related with orders for each exchange that i use. 

But ... more frustrating is to see constant timeouts with exchanges like kraken that make my arbitrage system completely useless. 

I think that doing near-real-time arbitraging with REST APIs is impossible. I suppose that doing it with websockets would be much better. Could you tell us your experience?

Once again, thanks in advance for your great work!!

**Comment by kroitor** [comment]
> I think that doing near-real-time arbitraging with REST APIs is impossible. I suppose that doing it with websockets would be much better. Could you tell us your experience?

When it's down, it's usually down completely ) WS can improve it under normal loads, and can behave "weird" when it is under high loads. Kraken does not have WS, btw... In general, you can't go with REST only or WS only, have to mix the two in 99% of practical cases.

**Comment by kroitor** [comment]
@rubobaquero i'd close this issue for now, if you don't mind. Feel free to reopen it if need or just continue to ask questions, if any. I'll be happy to help. Thx!
