### ISSUE TITLE
[binance] -2011 error handling

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#8179]
We currently have `'-2011': OrderNotFound` in binance.  This error happens when you use an orderId in a cancel operation, but that ID is not in the binance database yet.  Basically, it appears that the Rest API talks to a database that lags behind slightly, so the order is legitimate, but it's just not in the db yet.  Is OrderNotFound the correct thing to use?

**Comment by kroitor** [comment]
@npomfret 
> Is OrderNotFound the correct thing to use?

Yes, I think so. It literally tells the truth – the order is not found (yet).

The problem is that we can't distinguish the -2011 code when the order is not in the db but will be there eventually, from when the order will never be there.

Let me know if that does not answer the question.

**Comment by npomfret** [comment]
ok, thanks
