### ISSUE TITLE
kraken.fetch_ohlcv problem with limit arg

### ISSUE THREAD

**Issue by luisparravicini** [ccxt/ccxt#8184]
- OS: ubuntu 20.10
- Programming Language version: python 3.8.6
- CCXT version: 1.39.61

When using `fetch_ohlcv` with only `symbol` and `limit`, the returned data by ccxt is the oldest data returned by kraken and not the newest.

```python
import ccxt
exch = ccxt.kraken()
exch.verbose = True
exch.fetch_ohlcv('BTC/USD', limit=10)
```
The request made to kraken is:
```
Request: GET https://api.kraken.com/0/public/OHLC?pair=XXBTZUSD&interval=1 {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None
```

The problem seems to be that [kraken api](https://www.kraken.com/features/api) does not support a `limit` parameter in it's api, so (if you dont supply `since`) it returns data from now to the last 12 hours, and ccxt's kraken code calls [exchange.parse_ohlcvs](https://github.com/ccxt/ccxt/blob/c1506843e4a59909b333bf36c467630b886da6b8/python/ccxt/base/exchange.py#L1455) with all the data returned. This is where the limit is enforced and the items returned are from the beginning (the items from 12 hours back) and not the end (the newest).

Maybe this is the expected behaviour? I would expect to get the latest data and not from 12 hours before.

Exchanges which support a `limit` in their apis doesn't have this problem, like binance:

```python
import ccxt
exch = ccxt.binance()
exch.verbose = True
exch.fetch_ohlcv('BTC/USDC', limit=10)
```

I think the simplest solution is to apply the limit in [kraken.py](https://github.com/ccxt/ccxt/blob/master/python/ccxt/kraken.py) but maybe there are more exchanges without a `limit` in their apis and this same beahviour affecting kraken is present in others. In that case maybe the solution is to modify exchange.py

**Comment by kroitor** [comment]
> Maybe this is the expected behaviour?

If you don't specify `since` – you will get the default set of candles as returned from the exchange.  The default is exchange-specific. Then, if you supply `limit` it will return the first 10 of those default candles. 

This is how date-based pagination works and it is covered in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

So, if you want specific candles, i'd recommend to specify the starting timestamp (`since`).

Alternatively, you can filter them in the userland:

```
candles = exchange.fetch_ohlcv('BTC/USDC')
candles = candles[-10:]
```

Also, check these duplicate issues for more info:

- https://github.com/ccxt/ccxt/issues?q=is%3Aissue+kraken+ohlcv+720

Let us know if that does not answer your question.
