### ISSUE TITLE
CCXT use all available balance?

### ISSUE THREAD

**Issue by claritytechno** [ccxt/ccxt#8210]
Hi guys
Is there a parameter that allows you to signal ccxt to use full balance of that particular crypto? I can use fetch_partialbalance to get say just my BTC balance, but is there a way to convert to a variable and use this is replace of the numeric input required to create an order through ccxt?
Cheers

**Comment by kroitor** [comment]
Hi!

In general, the exchanges will require you to specify the exact amount upon placing an order via the API.
You can't tell the exchange to use all your balance whatever it is.
But you can tell the exchange to use all your balance which is an exact value.

First and foremost, you have to understand the difference between base and quote currencies:

- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

Some exchanges (not all of them) will allow you to specify "the amount to spend for the order in quote currency".
So, the general approach is to do it in steps:

1. `fetch_balance()` to get the exact value of your current balance
2. specify the cost to `create_order()` in quote currency taken from the current balance with respect to the trading fees

You can do steps 1 and 2 with CCXT, however, you will have to use params overrides or exchange-specific order types to get what you want. In other words, it will depend on the exchange in question, since this aspect is not fully unified yet.

Hope that answers your question. Let us know if not. Feel free to reopen this issue or just ask further questions if any.
