### ISSUE TITLE
FTX "cancel_all_orders" error

### ISSUE THREAD

**Issue by rylos** [ccxt/ccxt#8247]
- OS: Ubuntu 20.04
- Programming Language version: Python 3.8
- CCXT version: 1.40.30

When using cancel_allorders on FTX for example with this method:
```
exchange.cancel_all_orders(symbol='BTC/USD')
```

It's raising an error message from FTX with this content:
```
ccxt.base.errors.ExchangeError: ftx {"error":"Must cancel either limit orders or conditional orders","success":false}
```

Best Regards
Marco Ziliani

**Comment by kroitor** [comment]
Right, FTX requires an order type, I've pushed a fix that will default to standard limit orders. So, if you upgrade to version 1.40.34 in ~20 minutes when the new build arrives your code should work as is. If you want to cancel conditional orders, use it like so:

```
exchange.cancel_all_orders(symbol, {'conditionalOrdersOnly':True})
```

Let us know if you have issues with it after upgrading your version. We will be happy if you report back whether the issue is resolved or not. Thx!
