### ISSUE TITLE
Get date exchange added symbol?

### ISSUE THREAD

**Issue by TensorTom** [ccxt/ccxt#8315]
I'm looking for a property to know how far back of OHLCV data I can request for a given symbol. Is there one?

**Comment by kroitor** [comment]
This specific limitation is not fully unified across the exchanges yet, but we are looking to add it within the `features` interface, as is in this issue: #6772 ← I'd suggest to move the discussion there to keep related things together. We don't have an ETA yet, since this is a work in progress, so we will just starting these properties one by one to all exchanges soon.
