### ISSUE TITLE
Binance Futures  - BTC/USDT & ETH/USDP perpetual are not comming out from load_markets()

### ISSUE THREAD

**Issue by cheerfuljinakim** [ccxt/ccxt#8398]
Hi, thank you all for great contribution to ccxt library. 
I've used this library from last Dec. 2020 and had no problem for binance future BTC/USDT ETH/USDT trading. 

From couple of hour ago, however, the symbol 'BTC/USDT' and 'ETH/USDT' in future market do not get/post perpetual contract information but connect to the 'BTCUSDT_210326' and 'ETHUSDT_210326'

```python
ex1 = ccxt.binance({
    'apiKey': APIKeyBn,
    'secret': SecretKeyBn,
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
        'adjustForTimeDifference': True, 
    },})

ex1.load_markets()
ex1.market_id('ETH/USDT')
```
The result of the code above is 'ETHUSDT_210326'
It was totally fine until yesterday, and I have not changed any code. 

Is there any way that I could connect to the ETH/USDT perpetual in binance future?
Thank you

**Comment by kroitor** [comment]
@cheerfuljinakim hi! Have you upgraded your CCXT to the most recent version 1.41.61+? This issue has been addressed and fixed already. You have to keep your software up to date, since the underlying APIs can change. This is step 1 in the documented troubleshooting sequence:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Duplicates:

- https://github.com/ccxt/ccxt/issues/8387
- https://github.com/ccxt/ccxt/issues/8386

Let us know if that does not help.

**Comment by cheerfuljinakim** [comment]
Oops... I miss the issues. Sorry for your inconvenience. Thank you very much
