### ISSUE TITLE
Binance price is aways 0 in future demo account after open a buy position

### ISSUE THREAD

**Issue by dpalmeira** [ccxt/ccxt#8436]
Hi, I'm doing a full bot who supports download and store data, backtesting, trading strategies, live with demo and real accounts with Binance crypto currencies.

Current versions:
backtrader 1.9.76.123: 
bt-ccxt-store: 1.0 - https://github.com/Dave-Vallance/bt-ccxt-store
ccxt: ccxt-1.41.71

Well, the problem comes with 'future' DEMO account in live mode. (https://testnet.binancefuture.com/en/futures/BTCUSDT)

Basically after open an order (eg- BUY), it's executed well, and I can see it in the Binance UI perfectly, but the JSON returned by CCXT always says, price: 0 at order level (inner json obj), but at 'info' top level in the json it seems to be ok, and it's a problem for the rest of my code. Look at this:

JSON returned after open a position:
at: https://github.com/Dave-Vallance/bt-ccxt-store/blob/master/ccxtbt/ccxtbroker.py (line 195)
`
# Get the order
ccxt_order = self.store.fetch_order(oID, o_order.data.p.dataname)
`

`{'info': {'orderId': 2631050336, 'symbol': 'BTCUSDT', 'status': 'FILLED', 'clientOrderId': 'x-xcKtGhcu7bxfgec32d18a7db31cfr', **'price': '0'**, 'avgPrice': '47135.03000', 'origQty': '0.212', 'executedQty': '0.212', 'cumQuote': '9992.62636', 'timeInForce': 'GTC', 'type': 'MARKET', 'reduceOnly': False, 'closePosition': False, 'side': 'BUY', 'positionSide': 'BOTH', 'stopPrice': '0', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'MARKET', 'time': 1612897507401, 'updateTime': 1612897516496}, 'id': '2631050342', 'clientOrderId': 'x-xcKtGhcu7b33c32d68a18a7db31cf5', 'timestamp': 1612897507401, 'datetime': '2021-02-09T19:05:07.401Z', 'lastTradeTimestamp': None, 'symbol': 'BTC/USDT', 'type': 'market', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', **'price': 47135.03**, 'stopPrice': 0.0, 'amount': 0.212, 'cost': 9992.62636, 'average': 47135.03, 'filled': 0.212, 'remaining': 0.0, 'status': 'closed', 'fee': None, 'trades': None}
`

Maybe some broker mapping problem for binance?
here is my mapping:

`            broker_mapping = {
                'order_types': {
                    back_trader.Order.Market: 'market',
                    back_trader.Order.Limit: 'limit',
                    back_trader.Order.Stop: 'stop-loss',
                    back_trader.Order.StopLimit: 'stop limit'
                },
                'mappings': {
                    'closed_order': {
                        'key': 'status',
                        'value': 'closed'
                    },
                    'canceled_order': {
                        'key': 'status',
                        'value': 'canceled'
                    }
                }
            }
`

I'm trying to debug both Libraries, ccxtbt and ccxt to understand what is happening. Maybe you can help me, or confirm if ccxt json is correct with price 0 at inner json level?

Any idea how what else to check?

Thank you!

**Comment by kroitor** [comment]
Hi!

> Any idea how what else to check?

I would recommend checking the Manual, it is already covered there. Namely, when you get any response from CCXT, the data structures will contain a so called `info` substructure, which contains the answer from the exchange is is, untouched.  That substructure will always contain exchange-specific data that will differ from exchange to exchange and will include some peculiarities like the one you've noted. Everything else around `info` – is the unified information that is processed by CCXT from the `info` substructure.

This is covered, for example, here:

- https://github.com/ccxt/ccxt/wiki/Manual#order-structure

In general, the market orders don't require a price at all. The `price` is usually a property of limit orders. So, you can't preset the price on a market order. Also a single market order can be filled with multiple trades for differing prices (https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades). From the above it follows, that a market order cannot possibly have a single price, until they're filled. When a market order is filled, it obtain the price, that is the actual filling market price. If there was more than one filling trade – then the price is the volume-weighed average of prices of the trades (no single price, except the average filling price).

Consequently, a market order may not always have a price, but will probably have the `average` field in that case. The price most of the exchanges show you for your market orders – is the average filling price. The average price is usually roughly equal to the order `cost` over the order `filled` amount.

Beginner traders are not used to this and believe that a market order always has a single price. Some users have asked us a number of times about this, which is why the Manual recommends searching for duplicates:

- https://github.com/ccxt/ccxt/issues/3721#issuecomment-415978839
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

If you look at the `price` outside of `info` – that's the unified price from CCXT. Initially it was undefined for market orders. But the lack of a price confused too many users, despite that it's a pretty common thing in a basic trading model. Therefore we decided to do the "fix" that other exchanges do – just put the average price into `price`... which is why the `price` and `average` you get from CCXT is slightly different from what the API returns – that is done for the convenience of the users and for less confusion:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L1533

Let us know if the above does not answer your question.

**Comment by dpalmeira** [comment]
Wuauuu it's an incredible answer! very illustrative and useful.
After read it, I think it should be a problem in the ccxtbt wrapper lib, because in my strategy inside Backtrader, I always recaive self.position.price with a 0, and order.executed.price, order.executed.value, order.executed.comm, all with 0 value also after open a position at notify_order method with a order.status in [order.Completed]:.

So, I think or it's related with ccxtbt lib which implements the ccxtbroker, ccxtstore and ccxtfeed for backtrader, and use CCXT behind to connect the real broker.

Well, I will investigate/debug and read more. And if I finally I get the point, I will back with the answer to help others.

Thank you so much, and great work!

**Comment by kiskoapeles** [comment]
> Well, I will investigate/debug and read more. And if I finally I get the point, I will back with the answer to help others.

Hi, were you able to find an answer?
