### ISSUE TITLE
fetch_ohlcv's behaviour might have changed in the last CCXT version 

### ISSUE THREAD

**Issue by aldomora** [ccxt/ccxt#8454]
Hello, first of all, great job! I've been using CCXT for years and this is the first time I have an issue. 

I just upgraded to the last version today, and part of my Python codes suddenly stopped working. 

I found that the culprit was 

exchange = ccxt.binance()
ohlcvs = exchange.fetch_ohlcv("BTC/USDT", "1h", 1483228800000, limit=1000)

who is now returning an empty list and it used to return data. That timestamp corresponds to  01/01/2017.  It still works though when I use more recent dates. Any ideas on how to solve this issue without downgrading my ccxt version? Thanks in advance!

**Comment by aldomora** [comment]
I just randomly chose an earlier CCXT version (from early this year) and it works, so something must have happened in between. 

Cheers

**Comment by kroitor** [comment]
@aldomora hi!

Binance has changed their limits, you cannot fetch the candles if your window range is larger that 1 week, check this related issue:

- https://github.com/ccxt/ccxt/issues/8399

If you want to fetch the candles from the start of time, you should do this:

```
ohlcvs = exchange.fetch_ohlcv("BTC/USDT", "1h", 0, limit=1000)
```

If you specify a `since` timestamp other than 0, you will only have a range of one week from there. And there were no trades on Binance back in January 2017 (corresponds to your timestamp).

Let us know if the above does not answer your question,

**Comment by milkymeda** [comment]
@kroitor,

Test case:
```
$binance = new \ccxt\binance();
$res = $binance->fetch_ohlcv('BTC/USDT', '1m', 1518049620000, 1000);
var_dump($res);
```
Result:

```
array:1 [
  0 => array:6 [
    0 => 1518049680000
    1 => 7790.0
    2 => 7794.91
    3 => 7783.81
    4 => 7784.02
    5 => 8.153564
  ]
```
If I wanted to fetch 1m candles older than 1518049620000 the code can't do it because of the endTime being too narrow as 1518079619999 and the exchange has no candles between 1518049620000 to 1518079619999.

The endTime is only a couple of hours later. It's not always possible to get one week range from the code below at vendor/ccxt/ccxt/php/binance.php:1913:

`$endTime = $this->sum($since, $limit * $duration * 1000 - 1);`

It's dependent on the timeframe duration rather than exchange range limits. It can work well at larger timeframes but a 1-minute timeframe is too low for that. If the exchange has no candles from that range -as it does in the example- it can't go any further fetching candles.

That line may be changed to the below for specifying the exact 1 week period or some other change can be made accordingly.

`$endTime = $this->sum($since, 604800 * 1000 - 1);`

Side note: I don't think Binance has a 1-week range limit because when I manually remove the endTime, it works just fine and I can get 1000 candles starting from 1518049680000. But maybe some other exchange has that limit, so endTime specification makes sense for those cases. But like I said, I couldn't confirm on Binance and could not find any official statement.

**Comment by kroitor** [comment]
@milkymeda looks like something has changed on the exchange side with that behaviour. It didn't work before without the endTime... Tested on my side and it works without it now.

**Comment by AndrewBarba** [comment]
@kroitor This "fix" appears to be break dapi. The others are working correctly after removing endTime
