### ISSUE TITLE
When does actually the watch_ticker function refresh?

### ISSUE THREAD

**Issue by unaiasegi** [ccxt/ccxt#8467]
Dear contributor,

I have gone through the ccxt documentation and the answer to the following question is not clear to me. When the following code line (python) is executed:
order_book = await exchange.watch_order_book(symbol)
every time the order book for that symbol is updated the function will return the whole new order book. However, if we type the following code line:
ticker = await exchange.watch_ticker(symbol)
What does actually need to change in the market data so that something is returned in that function?

Thank you very much in advance,

Unai

**Comment by kroitor** [comment]
Hi!

In general, WS is more about real-time. 
You have two types of data:

1. real-time fills + real-time orderbooks – this is the first-order data that is used to calculate everything else
2. second-order data (tickers and ohlcvs) that is calculated from first-order data

Changes on first-order data (1) are delivered as soon as the exchange can.

It takes time for the exchange to calculate the statistical second-order data, but you can also calculate it on your own. How frequently to deliver the changes on second-order data (2) – depends on the exchange. Some exchanges will update you in regular intervals (like once or a few times every second), others will update the ticker more frequently. Some exchanges will send you delayed second-order data since it is not considered _"important"_ for a real-time trading operation.

You should not rely on tickers or OHLCVs if you wish to stay as close to real-time as possible.

Let us know if that does not answer your question.

**Comment by unaiasegi** [comment]
It does, thank you very much.

Unai
