### ISSUE TITLE
insufficient funds issue with bittrex

### ISSUE THREAD

**Issue by kingofclubstroy** [ccxt/ccxt#847]
Is it a bug report, a question or feature request? <sup>*(choose one)*</sup>

- [ ] bug report
- [x] question
- [ ] feature request

- Operating System: 
- Language +version: python 2.7
- CCXT version:
- Exchange: BITTREX
- Method: createLimitBuyOrder(), createLimitBuyOrder()

### Description

I keep receiving an insufficient funds error when attempting to buy on bittrex, i have looked into and followed what you showed in issue #393, and it seems to have worked for buying and selling on binance,
but not for bittrex. I am wondering if you could point me in the right direction

Here is what i have been doing:

```Python     
precisePrice = bittrexApi.priceToPrecision(market, rate)

if side == "buy":
         #buying so amount is in mainCoin or quote, convert to base
          amount = float(amount / precisePrice)

preciseAmount = bittrexApi.amountToPrecision(market, amount)

bittrexApi.createLimitBuyOrder(market, preciseAmount, preciseRate)
```

Do i need to subtract transaction fees?
Input quote amount instead of base?
Do quote to base conversion with unprecise rate?

Any tips would help, thanks!

**Comment by kroitor** [comment]
> Do i need to subtract transaction fees?

Yes you need to subtract if you want to spend all of your balance. Otherwise you need to have balance sufficient to pay for the order itself + fees.

> Input quote amount instead of base?

No.

> Do quote to base conversion with unprecise rate?

No.

> Any tips would help, thanks!

First of all, you have to understand how fees are applied... Are you familiar with a concept of *maker* and *taker*?

**Comment by kingofclubstroy** [comment]
i have seen fees be different if it maker or taker, but i dont know how i would determine if my order is one of the other, and thanks for your help!

**Comment by kingofclubstroy** [comment]
If i were to make an order at a price of (bid + ask /2) would i be a maker? And if i made an order that was at the price that was being asked for and was instantly taken, that would be a taker correct?

**Comment by kroitor** [comment]
> i have seen fees be different if it maker or taker, but i dont know how i would determine if my order is one of the other, and thanks for your help!

This is explained here: 

- https://github.com/ccxt/ccxt/issues/336#issuecomment-338380765
- https://github.com/ccxt/ccxt/issues/694#issuecomment-348145042

> If i were to make an order at a price of (bid + ask /2) would i be a maker? And if i made an order that was at the price that was being asked for and was instantly taken, that would be a taker correct?

The point is, you're not guaranteed that your order will arrive as a maker or a taker, because the of the price slippage (to put it simply, the price changes while your order is in flight towards the exchange). So, the only way to know about it, is to check if the order was filled immediately or not. If it wasn't filled immediately – it is now definitely a maker (present in the order book). It it was closed immediately, then you should check the price, it might be either of the two:
- a taker, if the price you got was a better price for you than you asked for – your taker order took some other (better) maker off the order book
- a maker if the price you got, was the price you asked for – your maker limit order was just filled by another taker quickly.

**Comment by kroitor** [comment]
So, from there you should be able to call `calculateFee()`, to get your predicted fee and then compare it to the actual price and fee that you got from the exchange. However, that method is still experimental, we are working on this particular aspect very intensively. Let me know if I answered your questions or not.

**Comment by kroitor** [comment]
I'd close this for now, if you don't mind, let us know if you still have some doubts on this. We'll be happy to help. Feel free to reopen it if needed, or just ask questions, I'll respond asap.

**Comment by FlickerBean** [comment]
I have a question following on from this so I thought I'd comment here rather than open a new issue.

I'm suffering from the same issue as op. And while it makes sense if the fee's vary, from maker to taker, from what I can tell fee's are always 0.25% on Bittrex. So why does the maker/taker issue even come in to play?

Would someone mind taking the time out to explain for me please?

Thanks

**Comment by FlickerBean** [comment]
Thanks for the response @kroitor.

Just to be clear in order to successfully make an order I need to ensure I have .25% of the value of the order available in quote currency?

So if I want to sell 100XXX coin at a rate of 1 XXX to 1 BTC. I need to ensure my account has at least 0.25btc available with which to pay the fee's?

This is something I wasn't aware of, so thanks very much for enlightening me.

Strangely even if I ensure I have 100x the required amount of btc available I still often get INSUFFICIENT_FUNDS errors from the btrx api. Is this a known issue with BTRX (they seem to have quite a few of them!).
