### ISSUE TITLE
Asyncio and watch_order_book

### ISSUE THREAD

**Issue by unaiasegi** [ccxt/ccxt#8476]
Dear contributor,

This is a conceptual question that maybe is out of your scope. If you think so, please feel free to close this issue automatically.

The situation is the following: by using asyncio gather, we are awaiting watch_order_book(market) for more than 40 markets and we are updating a dictionary with the real time date. Then, we use this dictionary for different things.

We do not understand clearly what happens in the following situation:
 - If the thread y processing an update (blocking code) for a given market, what happens with the updates that arrive simultaneously? Are they queued or just discarded?
 -  Can the blocking code be interrupted by an update from another market?
 -  If a queue is created, does it have a maximum length?
 -  What do you think is the best way to proceed in this situation not to lose any update?
 
Thank you very much for you effort.

**Comment by frosty00** [comment]
Hi @unaiasegi,

There is no threads in the code, just asyncio. Our code should be able to handle more than 40 markets without any problems. We do not drop any updates and they will be applied to the orderbook even if you do not `await` for it. If your processing code is too slow you might miss some notifications of market changes since you were not `await`ing when there was a new update and were doing other stuff.

> What do you think is the best way to proceed in this situation not to lose any update?

Make sure that the code after:

```
await exchange.watch_order_book()
<THE CODE HERE>
```

does not do any `time.sleep` or heavy processing code or any `awaits` after this code if you do not want to miss any notifications from orderbook updates.

**Comment by kroitor** [comment]
Hi @unaiasegi !

> We do not understand clearly what happens in the following situation:

> If the thread y processing an update (blocking code) for a given market, what happens with the updates that arrive simultaneously? Are they queued or just discarded?

They're queued and processed by the underlying networking code.

> Can the blocking code be interrupted by an update from another market?

Nope.

> If a queue is created, does it have a maximum length?

Yes check exchange.options['tradesLimit'], exchange.options['ohlcvLimit'], etc: https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#incremental-data-structures

> What do you think is the best way to proceed in this situation not to lose any update?

Check the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/py

Let us know if that does not answer your questions.
