### ISSUE TITLE
Bitfinex v2: fetchOrder TypeError: this.privatePostOrderStatus is not a function

### ISSUE THREAD

**Issue by deman4ik** [ccxt/ccxt#8546]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Mac OS
- Programming Language version: node v14.15.1
- CCXT version: 1.42.54

```
const exchange = new ccxt.bitfinex2({
  apiKey: "",
  secret: ""
});
const order = await exchange.createOrder(
      "XRP/USD",
      "limit",
      "buy",
      8,
      0.3,
      { type: "LIMIT" }
    );
const check = await exchange.fetchOrder(order.id, "XRP/USD");
```

```
TypeError: this.privatePostOrderStatus is not a function
    at bitfinex2.fetchOrder (/node_modules/ccxt/js/bitfinex.js:959:37)
```

**Comment by kroitor** [comment]
@deman4ik bitfinex2 is not fully implemented yet, in particular, it is inherited from bitfinex v1, but it does not have a fetchOrder method.

```
const exchange = new ccxt.bitfinex2()
console.log (exchange.has['fetchOrder'])
```

Since the method is inherited, the call is mapped to the underlying v1 call. In general, you have to check the `has` substructure as described in the Manual before calling the unified methods to make sure they're available: https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata. We will add an override to throw a proper exception from bitfinex2's fetchOrder.

**Comment by deman4ik** [comment]
My bad with `has`. Switching back to v1. Thank you
