### ISSUE TITLE
New exchange: Bit-Z

### ISSUE THREAD

**Issue by wtksyjpy** [ccxt/ccxt#860]
Hi author:

Could you please help add below exchange?
https://www.bit-z.com/api.html
Thank you for all your help!

**Comment by Deathamns** [comment]
Started working on it.

**Comment by kroitor** [comment]
@Deathamns respect!

**Comment by johnnyk85** [comment]
@Deathamns any updates?

**Comment by Deathamns** [comment]
@johnnyk85 See the referenced pull request.

**Comment by kroitor** [comment]
Merged in #1126, however still in experimental state and needs private API testing. 
We would be happy if you could help us test it extensively.
Available in ccxt since version 1.10.1011
Thank you!

**Comment by andrey-crypto** [comment]
does anyone understand what is 'nonce' here: https://www.bit-z.com/api.html ?

**Comment by kroitor** [comment]
@andrey-crypto a nonce is a constantly-increasing number. It isn't necessarily equal to current timestamp). So, with bit-z you have to send both the timestamp and the nonce.

**Comment by andrey-crypto** [comment]
@kroitor Thanks Igor! Can I also ask you what is 'sign'? Is it not secret key? Or how can it be found?

**Comment by kroitor** [comment]
@andrey-crypto it's explained right there on the page you've linked above, search for "How to sign" there. It is not your secret key, the secret key remains on your side and does not get sent, instead a unique signature is calculated based on nonce, apiKey and secret and the signed request can be sent safely after that. More about general authentication here:
- https://github.com/ccxt/ccxt/wiki/Manual#authentication

**Comment by Pmant** [comment]
fetchBalance throws an error and the API does not seem to support it. Still .has returns true for fetchBalance:
```
{ CORS: false,
  publicAPI: true,
  privateAPI: true,
  cancelOrder: true,
  cancelOrders: false,
  createDepositAddress: false,
  createOrder: true,
  deposit: false,
  fetchBalance: true,
  fetchBidsAsks: false,
  fetchClosedOrders: false,
  fetchCurrencies: false,
  fetchDepositAddress: false,
  fetchFundingFees: false,
  fetchL2OrderBook: true,
  fetchMarkets: true,
  fetchMyTrades: false,
  fetchOHLCV: true,
  fetchOpenOrders: true,
  fetchOrder: false,
  fetchOrderBook: true,
  fetchOrderBooks: false,
  fetchOrders: false,
  fetchTicker: true,
  fetchTickers: true,
  fetchTrades: true,
  withdraw: false }
```

**Comment by zn8ae** [comment]
Hi, I've tried to use bit-z's api to make orders but it triggers error as such:

The required parameter cannot be empty.

I think their updates might require some new parameters. Please kindly check. Thanks!

**Comment by kroitor** [comment]
@zn8ae can you please post your **verbose request/response** here ? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by zn8ae** [comment]
Sure thing!

In fact, I believe all the fetch_balance(), fetch_orders(), create_order() don't work now for bit-z because the required parameter missing issue. 

This is the request and response with fetch_balance (I changed the api_key and sign for safety):

Request: POST https://www.bit-z.com/api_v1/balances {'Content-type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} api_key=1c1dad8a12a1asdasf377e25f84&nonce=100001&timestamp=1530206233&sign=5ad8ca76dad2334974a9addab

Response: POST https://www.bit-z.com/api_v1/balances 200 {'Date': 'Thu, 28 Jun 2018 17:17:14 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'Set-Cookie': '__cfduid=deda3dd54995basdsasada482baad52ab6221530206234; expires=Fri, 28-Jun-19 17:17:14 GMT; path=/; domain=.bit-z.pro; HttpOnly, LANG=en; expires=Fri, 29-Jun-2018 17:17:15 GMT; Max-Age=86400; path=/', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4321ce443e7391d6-EWR', 'Content-Encoding': 'gzip'} {"code":100,"msg":"The required parameter cannot be empty","data":null}

And actually, create_market_buy_order gives an exception that is not server error:

If I use create_order to perform this one, it will trigger the required parameter empty as above again!

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-aca080a1530a> in <module>()
----> 1 bitz.create_market_sell_order('ETH/USDT', 0.1)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py in create_market_sell_order(self, symbol, amount, params)
   1315 
   1316     def create_market_sell_order(self, symbol, amount, params={}):
-> 1317         return self.create_order(symbol, 'market', 'sell', amount, None, params)
   1318 
   1319     def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/bitz.py in create_order(self, symbol, type, side, amount, price, params)
    337             'coin': market['id'],
    338             'type': orderType,
--> 339             'price': self.price_to_precision(symbol, price),
    340             'number': self.amount_to_string(symbol, amount),
    341             'tradepwd': self.password,

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py in price_to_precision(self, symbol, price)
    850 
    851     def price_to_precision(self, symbol, price):
--> 852         return ('{:.' + str(self.markets[symbol]['precision']['price']) + 'f}').format(float(price))
    853 
    854     def amount_to_precision(self, symbol, amount):

TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by kroitor** [comment]
@zn8ae what's your version of CCXT ?

**Comment by zn8ae** [comment]
1.14.169. Is it the older version?

**Comment by zn8ae** [comment]
Oops I'm afraid it is. I shall upgrade my ccxt then... Thanks so much!
