### ISSUE TITLE
Unnecessary Rate Limit Throwing Exceptions (PHP & Python)

### ISSUE THREAD

**Issue by TomAshley303** [ccxt/ccxt#863]
There's some rate limiting code in this library that throws exceptions even if I limit my loop to 1 call every second. The GDAX API supports many calls per second. I have tested this with a different gdax library and it lets me make these calls ever .25 seconds and even faster I think. Would like to go as fast as GDAX will allow.

- OS: Ubuntu 16.04
- Language: PHP (Same thing happens with PY)
- CCXT version: 1.10.390
- Exchange: GDAX
- Method: Ticker

```
$gdax = new \ccxt\gdax();

//var_dump ($gdax->fetch_trades ('BTC/USD'));

//var_dump($gdax->fetch_ticker('ETH/USD'));

while(1){
    echo $gdax->fetch_ticker('ETH/USD')['info']['price'];
    sleep(1);
}
```

```
Fatal error:  Uncaught ccxt\DDoSProtection: gdax GET https://api.gdax.com/products/ETH-USD/ticker 429 not accessible from this location at the moment in /home/user/www/madax/includes/ccxt/php/base/Exchange.php:609
Stack trace:
#0 /home/user/www/madax/includes/ccxt/php/base/Exchange.php(783): ccxt\Exchange->raise_error('DDoSProtection', 'https://api.gda...', 'GET', 429, 'not accessible ...')
#1 /home/user/www/madax/includes/ccxt/php/base/Exchange.php(630): ccxt\Exchange->fetch('https://api.gda...', 'GET', Array, NULL)
#2 /home/user/www/madax/includes/ccxt/php/gdax.php(530): ccxt\Exchange->fetch2('products/{id}/t...', 'public', 'GET', Array, NULL, NULL)
#3 [internal function]: ccxt\gdax->request('products/{id}/t...', 'public', 'GET', Array)
#4 /home/user/www/madax/includes/ccxt/php/base/Exchange.php(573): call_user_func(Array, 'products/{id}/t...', 'public', 'GET', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#6 /home/user/www/madax/includes/ccxt/php/base/Exchange.php(1387): call_user in /home/user/www/madax/includes/ccxt/php/base/Exchange.php on line 609

```

**Comment by kroitor** [comment]
Hi! It's not the library throwing the exception, it's the GDAX returning the code, that tells you that you are hitting the rate limit, because you are making too many ticker-requests in a loop. They will not allow fetching tickers over REST once per second.

Explained here:
https://github.com/ccxt/ccxt/issues/794

I'd close this for now as a duplicate, if you don't mind. The linked issue contains testing scripts for tickers vs orderbooks, if you want to verify this. Let us know if we can help with anything else or if you still have questions.
