### ISSUE TITLE
What is the latest version of ccxtpro ?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#8664]
Hi Kroitor,

I'm running ccxtpro 1.0.1 and I would like to know if it's the latest version. What is the best way to check this ?

This is what the upgrade command returns : 
```
> python -m pip install ccxtpro --upgrade
Requirement already satisfied: ccxtpro in /home/abc/python/envdev/lib/python3.6/site-packages (1.0.1)

```

The reason I want to check is that I get an error whith :

```
ccxtpro.poloniex({'enableRateLimit': True})
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-2a06c4112629> in <module>
----> 1 ccxtpro.poloniex({'enableRateLimit': True})

AttributeError: module 'ccxtpro' has no attribute 'poloniex'
```

Thank you

**Comment by kroitor** [comment]
Hi! 

No, you should not install it from `pip`, since CCXT Pro is not available on the public package registry.
You should instead install it from GitHub, after getting the license at https://ccxt.pro, please, read this install guide: https://github.com/ccxt/ccxt/wiki/ccxt.pro.install

The latest version of CCXT Pro is 0.6.9.
The version you get from `pip` is a stub (uploaded by us on purpose), that has no functionality in it.

Let us know if that does not answer your question.

**Comment by Kinzowa** [comment]
Thanks igor, I reinstalled again from Github and it works :  

`python -m pip install git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python`
