### ISSUE TITLE
getTrades inconsistent timestamps

### ISSUE THREAD

**Issue by Sicria** [ccxt/ccxt#881]
The inconsistencies between exchanges with the ``getTrades`` method is really confusing.

Poloniex requires the ``since`` in int form which it then does ``request['start'] = parseInt (since / 1000);`` on it.

Bitfinex does not even pass through the ``since`` to the request so you've got to pass it through as an extra param of ``timestamp``.

These are the two that I've looked at but I'm concerned that others will have similar quirks which may causes issues and force people to have to put case statements in for each exchange.

Are these on the road map to fix or am I maybe just using this package incorrectly?

**Comment by kroitor** [comment]
> Are these on the road map to fix or am I maybe just using this package incorrectly?

You are using them correctly (for now), and these are on the roadmap, we hope to fix them all asap. As you may know, this library is under active development. We will be thankful for your contributions and PRs. More on that here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

The intended design is to support `since` and `limit` params throughout the library, and avoid using custom extra `params` at all. This particular aspect has not been fully unified yet, it's a [work in progress](https://github.com/ccxt/ccxt/issues/470).

Let me know if this answers your question or not.

**Comment by Sicria** [comment]
Thank you that answers my questions perfectly.
