### ISSUE TITLE
Support for the unofficial Bittrex API v2.0

### ISSUE THREAD

**Issue by ASfSDlS61TLT6eoP3Qb7** [ccxt/ccxt#890]
The Bittrex API is not official yet, but can be gathered using Chrome Developer Tools on Bittrex Website. 

The link to the unofficial API Reference:
https://github.com/thebotguys/golang-bittrex-api/wiki/Bittrex-API-Reference-(Unofficial)

It could be nice to have the Bittrex API v2.0 implemented in the ccxt library. Though, it's quite risky, since the endpoints, actions can be changed. But I don't expect that and that it would be a big problem.

**Comment by kroitor** [comment]
We already have it.

**Comment by ASfSDlS61TLT6eoP3Qb7** [comment]
Allright, that's great. I must misunderstood it due the version in:
https://github.com/ccxt/ccxt/blob/ba0b1fa8ce8c1133d7ea7de1e5a1b89e0cfbc10c/js/bittrex.js#L17

And I think the documentation needs an update as well, right?

![image](https://user-images.githubusercontent.com/14862123/34163273-9d3e7096-e4d6-11e7-9e60-6d6d1ec5501d.png)

**Comment by kroitor** [comment]
I must misunderstood it due the version in:

Bittrex v1.1 is the official version, and their v2.0 covers just a small public part of the API... So you can't really do a lot with v2.0 only... It has to be 1.1+2.0 anyway. Moreover, v1.1 is still the dominant part of it.

> And I think the documentation needs an update as well, right?

Well, first of, the docs are generated from js files, so the version would be populated from bittrex.js, therefore no need to edit the doc by hand. An edit to bittrex.js would be enough. However, we think we should keep v1.1 because their v2.0 is not ready for migration yet (missing endpoints, docs, etc). I guess, this is what *unofficial API* means.
