### ISSUE TITLE
Amount in exchange.options['createMarketBuyOrderRequiresPrice']

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8928]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.47.3
Exchange: All Exchanges
Method: Amount in `exchange.options['createMarketBuyOrderRequiresPrice']`

Hello!

To be sure of this. I wonder about the: `exchange.options['createMarketBuyOrderRequiresPrice']`

The manual says this: https://ccxt.readthedocs.io/en/latest/manual.html
_With market buys some exchanges require the total cost of the order in the quote currency!_

Running the below shows either: `undefined` or `true` for `exchange.options['createMarketBuyOrderRequiresPrice']`.
```
(async () => {
    const allexchanges = ccxt.exchanges.filter((id) => !['coinmarketcap'].includes(id))
        .map(async (id) => {

            const Exchange = ccxt[id];
            const exchange = new Exchange({enableRateLimit: true, 'verbose': true, 'timeout': 10000 }); 
            console.log(exchange.options['createMarketBuyOrderRequiresPrice'] + "___" + id);
        });
    await Promise.all(allexchanges);
})();
```
**Question:** _('verbose': true doesn't show any information)_
For the **amount**: Is it true that only the exchanges that shows `TRUE` requires the _total cost of the order in the quote currency_ and the `undefined` does use the base currency as the amount?
**(I would put the `exchange.options['createMarketBuyOrderRequiresPrice'] = false` to calculate this manually)**

Thank you!

**Comment by ttodua** [comment]
Late reply, but i'll add:
- `exchange.options['createMarketBuyOrderRequiresPrice']` is not meant to override by you or set to false/true. It's the declaratory parameter for exchange, meaning that **you have to** input price when creating market order. It's not that you wish to override that or etcetera. It just says that exchange "requires" price, and if you override or don't provide it with price, then your order will not succeed through exchange api, because "market order requires price".

Let us know if you have any issues.
