### ISSUE TITLE
bitstamp createOrder type limit throws "under 5$ Order" exception

### ISSUE THREAD

**Issue by jompro** [ccxt/ccxt#893]
createLimitBuyOrder is also broken on bitstamp.

- exchange.createOrder ('BTC/USD', 'limit', 'buy', '0.001', '20.00') -> doesn't work
- exchange.createOrder ('BTC/USD', 'market', 'buy', '0.001') -> works fine

i don't know how to fix it myself, sorry.

**Comment by kroitor** [comment]
Let's see... you're buying BTC 0.001 for a price of $20 per BTC, that is:

`$20 * 0.001 = $0.020` 

which is obviously less that $5. 

Your BTC/USD order should be worth more than $5 in total.

> i don't know how to fix it myself, sorry.

One solution I would propose is to not submit orders that are too small, because most exchange will forbid *dust trade* (orders of very tiny amount)?

**Comment by jompro** [comment]
oh, i totally misunderstood this function.
thanks a lot.
