### ISSUE TITLE
Getting different data with bitfinex.fetch_ohlcv

### ISSUE THREAD

**Issue by gambitov** [ccxt/ccxt#9055]
Dear developer, I am using bitfinex.fetch_ohlcv but data is differente with market.

```
`import configparser
import ccxt
import mplfinance as mpf
# Reading Configs
config = configparser.ConfigParser()
config.read(r"config.ini")

#Load apikey and secret for Binance
apiKey = config['Bitfinex']['apiKey']
secret = config['Bitfinex']['secret']

# Create client for Bitfinex
exchange_id = 'bitfinex'
exchange_class = getattr(ccxt, exchange_id)
bitfinex = exchange_class({
    'options': {
        'adjustForTimeDifference': True,  # ←---- resolves the timestamp
    },
    'apiKey': apiKey,
    'secret': secret,
    'timeout': 30000,
    'enableRateLimit': True,
})

symbol = 'BTC/USD'
time_frame = '1h'
candle = bitfinex.fetch_ohlcv(symbol, time_frame)
df = pd.DataFrame(candle,columns=['Date','Open','High','Low','Close','Volume'])
df['Date'] = df['Date'].apply(lambda date: pd.Timestamp(time.ctime(date/1000.)))
df.set_index('Date',inplace=True)
mpf.plot(df, type='candle', style='yahoo')
`
```

I am getting this data for candle

[[1364774400000, 93.25, 100.0, 93.03, 93.1, 345.58388931], 
[1364778000000, 93.37999, 93.48797, 93.1, 93.1, 45.24333505], 
[1364781600000, 93.17, 94.0, 93.10999, 93.74, 466.3114199999999], 
[1364785200000, 93.8, 93.8, 92.49999, 92.70002, 96.31618]]

But BTC/USD is at about 50k

Help me please.

**Comment by kroitor** [comment]
@gambitov you're getting the prices from the beginning of their trade since 2013.

```Python
~/ccxt/python $ python3
Python 3.8.2 (default, Dec 21 2020, 15:06:03)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.bitfinex()
>>> exchange.iso8601 (1364778000000)
'2013-04-01T01:00:00.000Z'
```

If you want proper candles, you have to pass the `since` timestamp in milliseconds to `fetch_ohlcv` and check the timestamps in the response, as explained in the Manual:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts
- https://github.com/ccxt/ccxt/wiki/Manual#pagination

Please, read the entire Manual from top to bottom at least one, it has the answers to most frequent questions and it will really save your time.

Let us know if the above does not answer your question. Feel free to reopen this issue or just ask further questions if any.

**Comment by gambitov** [comment]
Dear @kroitor, you are the best, thank you so much. Have a nice day.
