### ISSUE TITLE
No (obvious) forum?

### ISSUE THREAD

**Issue by gitcnd** [ccxt/ccxt#9099]
The Doc https://github.com/ccxt/ccxt/wiki "Troubleshooting" section doesn't mention any support options or community links whatsoever.  Google didn't turn up anything obvious either.

Is there a forum or support option that exists?

If not, can one please be set up?  It's going to remove a huge burden from the devs when knowledgeable users can help one-another...

**Comment by kroitor** [comment]
> doesn't mention any support options or community links whatsoever. Google didn't turn up anything obvious either.

We use the GitHub's issue tracker as a forum, since it is directly integrated with the repository and also allows links to the code.
In short, you've made a new post the forum, and this is my comment on your post.
Any user can post here on any issue, regardless of whether it is open or not – it's the same as with a forum.

Apart from GitHub issues we also have a discord chat here: [![Discord](https://img.shields.io/discord/690203284119617602?logo=discord&logoColor=white)](https://discord.gg/dhzSKYU)

Also: https://github.com/ccxt/ccxt#social

Let us know if that does not answer your question.
Feel free to reopen this or just ask further questions if any.
