### ISSUE TITLE
Can exchange.createOrder(...) return an empty response string

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#9173]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.47.3
Exchange: All Exchanges
Method: binance.createOrder()

Hello!

The ccxt is great. Just a wonderful creation! 

I have a question about when we create an order using: `exchange.createOrder(...)`.
```
async function _createOrder() {

    var exchange = new ccxt.binance(); const params = {};
    const response = await exchange.createOrder("BTC/USDT", "limit", "buy", 0.01, 56200, params);

    console.log(response);
}
```
We receive a **response** with a format that look like this when everything works:
```
{
	id: '60s8asdfsafask3453lk345lj3l',
        symbol: 'BTC/USDT',
        amount: '0.01',
        etc...
}
```
I am in the process of implementing scenarios of what could happen which leads me to this question. I have tried the code above perheps 20 times while implementing code.

What I wonder is if there is a scenario where we **Do Not** get a response from: `exchange.createOrder` with any information about what has happened. 

1. For example can response be completely empty with No information at all like an EMPTY string?
2. For example let us assume that the internet connection goes down 1 millisecond after the: `exchange.createOrder` has been executed and the internet connection works again after 1 hour. What happens here in the response?
3. Perheps I am looking for all other possible responses which can come out from this except a successful response?

I beleive question 1. is one which I wonder about much.
I am not sure if I have described the question well enough, but perheps the idéa of what I wonder about can be seen.

Thank you!

**Comment by kroitor** [comment]
> For example can response be completely empty with No information at all like an EMPTY string?

No. If you find such a scenario – please, send us a message.

> For example let us assume that the internet connection goes down 1 millisecond after the: exchange.createOrder has been executed and the internet connection works again after 1 hour. What happens here in the response?

Instead of getting a response, an exception gets thrown and you catch it and handle just as you would do with any regular application in JavaScript. The error handling is documented here: https://github.com/ccxt/ccxt/wiki/Manual#error-handling, also, see how that is done in the examples: https://github.com/ccxt/ccxt/tree/master/examples
Perheps I am looking for all other possible responses which can come out from this except a successful response?

> Perheps I am looking for all other possible responses which can come out from this except a successful response?

It is an object that should look like this: https://github.com/ccxt/ccxt/wiki/Manual#order-structure. In case of an error you get an exception that you can control.

Hope that answers your questions, let us know if not.

**Comment by jackpotcityco** [comment]
Then I understand. That helped alot.
I will look at all errors in the link you posted and implement code for different errors that could occur there.

Thank you!
