### ISSUE TITLE
Fetch_tickers returns nothing when requesting futures on OKEX 

### ISSUE THREAD

**Issue by tomaszrydzewski** [ccxt/ccxt#9196]
OS: Win 10
Programming Language version: Python 3.7.4
CCXT version: 1.50.8
```

import ccxt
exchange = ccxt.okex({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
})

exchange.load_markets()
exchange.fetch_tickers(['TRX-USDT-210521'])
```

```
{}
```

**Comment by kroitor** [comment]
@tomaszrydzewski we're migrating to OKEX v5 now, it will arrive within a couple of days. This issue will be resolved in the new build. Thx for your feedback!

**Comment by tomaszrydzewski** [comment]
Great, thanks for letting me know.

**Comment by pygabr** [comment]
Hi, it actually happens as well with:
CCXT 1.50.11
and exchange deribit:

```
import ccxt
d=ccxt.deribit()
d.load_markets()
d.fetchTickers('ETH-PERPETUAL')
{}
```


Curiously (for me), BTC seems to work differently:
`d.fetchTickers('BTC-PERPETUAL')
`
{'BTC-PERPETUAL': {'symbol': 'BTC-PERPETUAL', 'timestamp': 1621462252166, 'datetime': '2021-05-19T22:10:52.166Z', 'high': 43591.5, 'low': 28508.5, 'bid': 39248.5, 'bidVolume': None, 'ask': 39249.0, 'askVolume': None, 'vwap': None, 'open': None, 'close': 39254.5, 'last': 39254.5, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': 127130.67, 'info': {'volume_usd': '4744817899.99', 'volume': '127130.67', 'quote_currency': 'USD', 'price_change': '-8.5616', 'open_interest': '436781250', 'mid_price': '39248.75', 'mark_price': '39248.19', 'low': '28508.5', 'last': '39254.5', 'instrument_name': 'BTC-PERPETUAL', 'high': '43591.5', 'funding_8h': '-0.0012247', 'estimated_delivery_price': '39279.27', 'current_funding': '-0.00029126', 'creation_timestamp': '1621462252166', 'bid_price': '39248.5', 'base_currency': 'BTC', 'ask_price': '39249.0'}}}


on the other hand, fetchTicker seems to work fine (both for BTC and ETH), eg:
`d.fetchTicker('ETH-PERPETUAL')
`
{'symbol': 'ETH-PERPETUAL', 'timestamp': 1621462670438, 'datetime': '2021-05-19T22:17:50.438Z', 'high': 3445.5, 'low': 1805.05, 'bid': 2657.5, 'bidVolume': 1.0, 'ask': 2658.65, 'askVolume': 1500.0, 'vwap': None, 'open': None, 'close': 2657.5, 'last': 2657.5, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': 1024390.941414, 'info': {'timestamp': '1621462670438', 'stats': {'volume_usd': '2722099205.0', 'volume': '1024390.941414', 'price_change': '-21.8251', 'low': '1805.05', 'high': '3445.5'}, 'state': 'open', 'settlement_price': '2986.97', 'open_interest': '252684796', 'min_price': '2621.75', 'max_price': '2701.6', 'mark_price': '2660.67', 'last_price': '2657.5', 'instrument_name': 'ETH-PERPETUAL', 'index_price': '2665.49', 'funding_8h': '-0.000771', 'estimated_delivery_price': '2665.49', 'current_funding': '-0.001308', 'best_bid_price': '2657.5', 'best_bid_amount': '1.0', 'best_ask_price': '2658.65', 'best_ask_amount': '1500.0'}}

The problem seems to be (on deribit) with any ETH ticker when using fetchTickers()
Regards

**Comment by kroitor** [comment]
@pygabr Deribit is very specific in that aspect, you have to specify a currency code in the options for ETH perpetuals: 

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/deribit.py#L327
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/deribit.py#L727

Apart from that `fetch_tickers` accepts a list of symbols (you should not specify just one string in the first argument), while `fetch_ticker` accepts just one symbol.

BTC works for you, since it's Deribit's default.

```Python
import ccxt
d=ccxt.deribit({'options':{'fetchTickers':'ETH', 'fetchTicker': 'ETH'}})
d.load_markets()
d.fetch_tickers(['ETH-PERPETUAL'])
d.fetch_ticker('ETH-PERPETUAL')
```
Let us know if that does not answer your question.

**Comment by pygabr** [comment]
Hi, it does, in part (I had missed the 'default ticker' mechanism).
However, and apologies for not having said it immediately, it didn't (and doesn't) work with lists either. Eg:

`d.fetchTickers(['ETH-PERPETUAL', 'ETH-28MAY21'])
`
{}
and:

`d.fetchTickers(['ETH-PERPETUAL', 'BTC-28MAY21'])`
{'BTC-28MAY21': {'symbol': 'BTC-28MAY21', 'timestamp': 1621491013598, 'datetime': '2021-05-20T06:10:13.598Z', 'high': 40615.5, 'low': 28532.0, 'bid': 39588.0, 'bidVolume': None, 'ask': 39644.0, 'askVolume': None, 'vwap': None, 'open': None, 'close': 39603.5, 'last': 39603.5, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': 4113.14, 'info': {'volume_usd': '149600000.0', 'volume': '4113.14', 'quote_currency': 'USD', 'price_change': '-0.2293', 'open_interest': '179825470', 'mid_price': '39616.0', 'mark_price': '39600.88', 'low': '28532.0', 'last': '39603.5', 'instrument_name': 'BTC-28MAY21', 'high': '40615.5', 'estimated_delivery_price': '39601.07', 'creation_timestamp': '1621491013598', 'bid_price': '39588.0', 'base_currency': 'BTC', 'ask_price': '39644.0'}}}

Any idea?

**Comment by kroitor** [comment]
@pygabr have you noticed how the options i added for the exchange initialization [here](https://github.com/ccxt/ccxt/issues/9196#issuecomment-844543572)? Can you paste your full code?

**Comment by pygabr** [comment]
Sorry, no I hadn't seen your comment, maybe the page wasn't properly refreshed.
It works indeed with this:

```
>>> import ccxt
>>> d1=ccxt.deribit()
>>> d2=ccxt.deribit({'options':{'code':'ETH'}})
>>> dd=d1.load_markets()
>>> dd=d2.load_markets()
>>> d2.fetchTickers(['ETH-PERPETUAL'])
{'ETH-PERPETUAL': {'symbol': 'ETH-PERPETUAL', 'timestamp': 1621511161845, 'datetime': '2021-05-20T11:46:01.845Z', 'high': 2936.1, 'low': 1805.05, 'bid': 2745.15, 'bidVolume': None, 'ask': 2745.2, 'askVolume': None, 'vwap': None, 'open': None, 'close': 2745.0, 'last': 2745.0, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': 1050324.13, 'info': {'volume_usd': '2625925014.0', 'volume': '1050324.13', 'quote_currency': 'USD', 'price_change': '3.4895', 'open_interest': '272972575', 'mid_price': '2745.18', 'mark_price': '2743.81', 'low': '1805.05', 'last': '2745.0', 'instrument_name': 'ETH-PERPETUAL', 'high': '2936.1', 'funding_8h': '0.000114', 'estimated_delivery_price': '2741.32', 'current_funding': '0.000408', 'creation_timestamp': '1621511161845', 'bid_price': '2745.15', 'base_currency': 'ETH', 'ask_price': '2745.2'}}}

```

I wonder however if there's a way to get both BTC and ETH tickers without needing two exchange instances (d1 and d2)... as far as I understand it's either BTC (by default) or ETH (by adding the 'code' option), but not both of them. Not a huge problem, but slightly weird.
Thank you very much 
Regards

**Comment by kroitor** [comment]
> I wonder however if there's a way to get both BTC and ETH tickers without needing two exchange instances (d1 and d2)... as far as I understand it's either BTC (by default) or ETH (by adding the 'code' option), but not both of them. Not a huge problem, but slightly weird.

Deribit's own API requires a currency code for fetchTickers: 

- https://docs.deribit.com/#public-get_book_summary_by_currency
- https://docs.deribit.com/#public-get_book_summary_by_instrument

**Comment by soyoeml** [comment]
info = okex.fetch_ticker ([ 'BTC-USDT-210924','BTC/USDT' ])

only returns BTC/USDT, futures are missing.

**Comment by kroitor** [comment]
@soyoeml you cannot send an array of symbols to `fetch_ticker`, it accepts just one symbol.

**Comment by soyoeml** [comment]
typo error. Should be fetch_tikers. It returns BTC/USD only.
> @soyoeml you cannot send an array of symbols to `fetch_ticker`, it accepts just one symbol.

**Comment by kroitor** [comment]
@soyoeml okex5's fetchTickers allows to fetch one instrument type only, you can't fetch multiple instruments of different types. All tickers should either be spot tickers, or futures tickers, or swap tickers, or options-tickers, and not spot+futures. By default it will fetch the spot tickers.

You should specify the `defaultType` exchange option or the `type` parameter override to it:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/okex5.py#L944

Hope that answers your question.

**Comment by ttodua** [comment]
@kroitor's above answer had clarified issue and there was no follow-ups. This issue is closed now, if you experience any issue with CCXT, let us know,
