### ISSUE TITLE
How to import ccxt with vite.js

### ISSUE THREAD

**Issue by mattiaz9** [ccxt/ccxt#9199]
I'm trying to use ccxt with vitejs but I'm having troubles importing the module.

I tried:
```
import * as ccxt from "ccxt/dist/ccxt.browser"
console.log(ccxt.binance)
```

and:
```
import { binance } from "ccxt/dist/ccxt.browser"
console.log(binance)
```

In both cases `binance` is `undefined`.

Has anyone managed to import ccxt using vitejs?

**Comment by ttodua** [comment]
Similar question was asked before [here](https://github.com/ccxt/ccxt/issues/8677). If that doesn't answer the issue, let us know.

**Comment by jazoom** [comment]
`import ccxt from 'ccxt';`
`import { binance } from 'ccxt-esm';` <-- this should really be how it's done in the main package so we only import the code we need

Both of the above seem to compile in SvelteKit (uses Vite). But they still don't work.

```
    const binanceApi = new binance({
      apiKey: getApiKey(),
      secret: getSecretKey(),
    });
    console.log(binanceApi.id);
```

I get this error every time:
`Uncaught (in promise) ReferenceError: Buffer is not defined`

Perhaps this library is relying upon Webpack polyfilling `Buffer` for the browser, which as far as I can tell, it does by default? It seems Vite (sensibly IMHO) does not do this.

**Comment by jazoom** [comment]
I can get the above commands to work if I do the following:

1. `yarn add '@esbuild-plugins/node-globals-polyfill'`

3. Add this to Vite config file (which for SvelteKit is `svelte.config.js`):
`import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';`

4. Add this to Vite config (which for SvelteKit is the `vite` field in `svelte.config.js`):
```
      optimizeDeps: {
        esbuildOptions: {
          define: {
            global: 'globalThis'
          },
          plugins: [
            NodeGlobalsPolyfillPlugin({
              buffer: true
            })
          ]
        }
      }
```

My gut tells me this should be unnecessary and if `ccxt` requires `Buffer` then it should include it as a dependency rather than relying on this external polyfill behaviour.

Credit to this answer: https://stackoverflow.com/a/70719923

**Comment by ttodua** [comment]
@frosty00 @kroitor please, if you have some clues, post a reply here.

**Comment by sc0Vu** [comment]
Is this esm issue? Because ccxd was common's module, using the `import` might break the functionality. The example was use `require('ccxt')` and import as module.

**Comment by silvercondor** [comment]
> 

confirmed this works with vite react. 

agree that if ccxt requires buffer then it should include as dependency instead of requiring polyfill

**Comment by ttodua** [comment]
if anyone have any related issues, let us know
