### ISSUE TITLE
New Exchange : trbinance

### ISSUE THREAD

**Issue by NeutK** [ccxt/ccxt#9289]
https://www.trbinance.com/en/

**Comment by frosty00** [comment]
https://www.binance.com/tr same thing?

**Comment by kroitor** [comment]
> https://www.binance.com/tr same thing?

I think, binance.com/tr is just a Turkish switch for Binance, while trbinance.com is a Binance franchise exchange in Turkey.

**Comment by NeutK** [comment]
Pairs are same with binance.com ( same Orderbooks, trade history etc. ). But, trbinance.com has different API. So you can't control trbinance with binance API.

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/8122

**Comment by kroitor** [comment]
@NeutK  we are working on the Binance TR integration right now, however, we have an issue with testing it, since we're not citizens of Turkey. If you could help us get the API keys for testing (we don't really need your balance) – that would help speed it up. If you wish to assist, please, contact info@ccxt.trade. Thank you!
