### ISSUE TITLE
Is connection dropped on 'ping-pong keepalive missing on time' error?

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#9334]
Periodically for FTX, Binance/Futures error `Connection to [stream_name] timed out due to a ping-pong keepalive missing on time` occurred when `watchTicker` method is running. Is connection closed after that error and I need to resubscribe for all symbols?

- OS: DEBIAN (Docker)
- Programming Language version: NodeJS
- CCXT version: Pro version: 0.6.81

**Comment by kroitor** [comment]
The same connection is shared across all subscriptions, and most often if one of them times out, all of that become unresponsive, and the entire connection with all its subscriptions must be re-established. We also have plans on adding a better connection manager that will restore your subscriptions automatically and will allow subscribing to many symbols at once. Let us know if the above does not answer your question. If that happens too frequently, please, let us know, we will investigate further.

**Comment by yfenggoldentree** [comment]
Hi @kroitor, curious if there's an update to the aforementioned connection manager?

**Comment by nileio** [comment]
@kroitor I see this issue is closed.. can you clarify please ? is there an update on this issue ? this is a major problem.. I moved from a different lib and was struck by this issue on many exchanges including Binance! 
definitely support restoring subscriptions in case of disconnect, providing easier expose of the WSclient so people can listen on `disconnects`, handling of ping-pong (ping-pong should be optional though recommended but Binance for example does not drop the connection if it does not recieve a pong)..
allowing multiple subscriptions at once is nice to have but I can't find a way to resolve this ping-pong issue..
