### ISSUE TITLE
Pagination not working as expected with FTX exchange

### ISSUE THREAD

**Issue by springrider** [ccxt/ccxt#9343]
- OS: MacOS
- Programming Language version: Python
- CCXT version: 1.50.89

I tried to get all of the trade I have made, using the method, "exchange.fetchMyTrades()", which basically called "/fills" api as below:(start time is "2020-06-01", and end time is "2020-06-09")

 GET https://ftx.com/api/fills?market=DOGE-PERP&limit=2&start_time=1590969600&end_time=1623236704

the expected behaviour is that it returns the earliest records first, is that right?  so I could use:
since = orders[len(orders) - 1]['timestamp']
to continue to fetch more. but it continues to return the result of "2020-06-09", and while the loop goes on it just returns same result everytime....
it is really confusing,  I tried the ftx api directly and the result is the same, so not sure if this has something to do with the exchange. 

here is the code I am using, copied from the manual. 
```
def getAllTrades():
  exchange = ftx
  since = exchange.milliseconds () - 86400000*3  # -1 day from now
  since = exchange.parse8601 ('2020-06-01T00:00:00Z')
  # alternatively, fetch from a certain starting datetime
  # since = exchange.parse8601('2018-01-01T00:00:00Z')
  all_orders = []
  while since < exchange.milliseconds ():
      print("since:", since)
      limit = 2  # change for your limit
      orders = exchange.fetchMyTrades(symbol, since, limit)
      if len(orders):
          since = orders[len(orders) - 1]['timestamp']
          all_orders += orders
      else:
          break

  return all_orders
```

**Comment by kroitor** [comment]
> the expected behaviour is that it returns the earliest records first, is that right?

No, the arrays of trades/orders/ohlcvs/deposits/withdrawals will be returned sorted chronologically. The earliest record will be the first in the array, the latest record will be the last.

**Comment by springrider** [comment]
> > the expected behaviour is that it returns the earliest records first, is that right?
> 
> No, the arrays of trades/orders/ohlcvs/deposits/withdrawals will be returned sorted chronologically. The earliest record will be the first in the array, the latest record will be the last.

thanks, that's exactly what I am asking,   I set "since=2020-06-01 && limit =2", and it returns records of 2020-06-09.  shouldn't it returns record from 2020-06-01, 2020-06-02, 2020-06-03, and 2020-06-09 was the last?

if it returns 2020-06-09, then it seems no way to set since to return records before 2020-06-09.

**Comment by springrider** [comment]
I have records from 2020-06-07 and 2020-06-08.   so if I only query 2 records since 2020-06-01, it definitely shouldn't return the one from 2020-06-09?

**Comment by springrider** [comment]
this code:
```
def getAllTrades():
  exchange = ftx
  #since = exchange.milliseconds () - 86400000*3  # -1 day from now
  since = exchange.parse8601 ('2020-06-01T00:00:00Z')
  all_orders = []
  while since < exchange.milliseconds ():
      print("since:", since)
      limit = 2  # change for your limit
      orders = exchange.fetchMyTrades(symbol, since, limit)
      print(len(orders))

      for order in orders:
        print("orderid:", order['id'], order['info']['time'])
      if len(orders):
          since = orders[len(orders) - 1]['timestamp']
          all_orders += orders
      else:
          break

  return all_orders
```

returns:

```
since: 1590969600000
2
orderid: 2554708600 2021-06-09T02:57:12.656888+00:00
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820
1
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820
1
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820
1
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820
1
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820
1
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820
1
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820
```
first it returns 2 records, and then only one, and the same one again and again. 

if I change the limit to 20 or even more, it would output like this:

```
since: 1590969600000
20
orderid: 2554459203 2021-06-09T02:35:28.925396+00:00
orderid: 2554459275 2021-06-09T02:35:29.377867+00:00
orderid: 2554483999 2021-06-09T02:39:29.621028+00:00
orderid: 2554489489 2021-06-09T02:40:15.296590+00:00
orderid: 2554503921 2021-06-09T02:41:54.386314+00:00
orderid: 2554503949 2021-06-09T02:41:55.113608+00:00
orderid: 2554505709 2021-06-09T02:42:18.609721+00:00
orderid: 2554505729 2021-06-09T02:42:18.721653+00:00
orderid: 2554517373 2021-06-09T02:44:28.809473+00:00
orderid: 2554619638 2021-06-09T02:49:33.216307+00:00
orderid: 2554640982 2021-06-09T02:51:03.052306+00:00
orderid: 2554645554 2021-06-09T02:51:27.467284+00:00
orderid: 2554662190 2021-06-09T02:52:53.011432+00:00
orderid: 2554686170 2021-06-09T02:54:42.999931+00:00
orderid: 2554688922 2021-06-09T02:55:06.061139+00:00
orderid: 2554698324 2021-06-09T02:56:14.991188+00:00
orderid: 2554705390 2021-06-09T02:56:51.437715+00:00
orderid: 2554708524 2021-06-09T02:57:11.819640+00:00
orderid: 2554708600 2021-06-09T02:57:12.656888+00:00
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820
1
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820
1
orderid: 2554711710 2021-06-09T02:57:33.820820+00:00
since: 1623207453820 
```

as you can see there are actually many records, just not sure how to fetch them all.  I copied the code from the manual, not sure if it is the right way to use it.

**Comment by kroitor** [comment]
@springrider first and foremost, are you trying to fetch all your personal orders or all your personal trades?

**Comment by springrider** [comment]
> @springrider first and foremost, are you trying to fetch all your personal orders or all your personal trades?

all my personal trades. sorry for the bad variable name, didn't change it after copied from the example...

**Comment by kroitor** [comment]
@springrider let us know if this example does not answer your question:

- https://github.com/ccxt/ccxt/blob/master/examples/py/ftx-fetch-all-my-trades.py

```Python
import ccxt  # noqa: E402


# make sure your version is 1.51+
print('CCXT Version:', ccxt.__version__)

exchange = ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})


markets = exchange.load_markets ()

# exchange.verbose = True  # uncomment for debugging

all_trades = []
symbol = None
since = None
limit = 200
end_time = exchange.milliseconds()

while True:
    print('------------------------------------------------------------------')
    params = {
        'end_time': int(end_time / 1000),
    }
    trades = exchange.fetch_my_trades(symbol, since, limit, params)
    if len(trades):
        first_trade = trades[0]
        last_trade = trades[len(trades) - 1]
        end_time = first_trade['timestamp']
        all_trades = trades + all_trades
        print('Fetched', len(trades), 'trades from', first_trade['datetime'], 'till', last_trade['datetime'])
    else:
        print('Done')
        break


print('Fetched', len(all_trades), 'trades')
for i in range(0, len(all_trades)):
    trade = all_trades[i]
    print(i, trade['id'], trade['datetime'], trade['amount'])
```

**Comment by springrider** [comment]
Thanks a lot, this dose answer my question,  I did some search and not found this example code, my bad...

**Comment by jacobthetechy** [comment]
I came across this issue recently as well, but I think there is a bigger issue with the pagination strategy does not seem unified across fetching functions. 

I'm using python3.8.2 and ccxt-1.52.29, and I'm connection to FTXUS instead.

Take this snippet for example. 

```python
withdrawls = [(i['id'], i['timestamp']) for i in exchange.fetch_withdrawals()]

# returns
[('39700', 1615349957737),
('42357', 1615694459775),
('71435', 1619237781176),
('71824', 1619282299669),
('89925', 1620426111372),
('95335', 1620679194550),
('97970', 1620781966366),
('126146', 1622651773534),
('126338', 1622661788564),
('126349', 1622662315865),
('137434', 1623641692471),
('139166', 1623796898463)]
```

As expected, adding `limit=4` returns the last 4 withdraws.

```python
withdrawls = [(i['id'], i['timestamp']) for i in exchange.fetch_withdrawals(limit=4)]

# returns
[('126338', 1622661788564),
('126349', 1622662315865),
('137434', 1623641692471),
('139166', 1623796898463)]
```

Again as expected, adding `since=1615349957737` (the first withdraw) returns 4 withdraws since that date going forward in time.

```python
withdrawls = [(i['id'], i['timestamp']) for i in exchange.fetch_withdrawals(limit=4, since=1615349957737)]

# returns
[('39700', 1615349957737),
('42357', 1615694459775),
('71435', 1619237781176),
('71824', 1619282299669),]
```
When using `fetch_my_trades()` this is not the case.

```python
trades = [(i['id'], i['timestamp']) for i in exchange.fetch_my_trades()]

# returns
[('1318456', 1613877495598), 
('1318635', 1613878357516), 
('1329210', 1613939466053), 
('1329542', 1613940244273), 
('1352172', 1614004622606), 
('1426760', 1614179986020),
...
('10339246', 1621680371355),
('10510210', 1621788779640), 
('10591216', 1621841794352),
('11498023', 1622651426749), 
('11498159', 1622651552748), 
('12326808', 1623374226139)]

trades = [(i['id'], i['timestamp']) for i in exchange.fetch_my_trades(limit=4)]

# returns as expected
[('10591216', 1621841794352),
('11498023', 1622651426749), 
('11498159', 1622651552748), 
('12326808', 1623374226139)]

trades = [(i['id'], i['timestamp']) for i in exchange.fetch_my_trades(limit=4, since=1613877495598)]  # since first trade

# returns not expected
[('10591216', 1621841794352),
('11498023', 1622651426749), 
('11498159', 1622651552748), 
('12326808', 1623374226139)]

# Expecting the first 4 trades since 1613877495598
[('1318456', 1613877495598), 
('1318635', 1613878357516), 
('1329210', 1613939466053), 
('1329542', 1613940244273)]
```

In the example code given by @kroitor pagination is going back in time while the pagination I was using was going forward in time, starting with as far as possible and working my way to present day. This is also seen here in the [docs](https://ccxt.readthedocs.io/en/latest/manual.html#date-based-pagination). My reasoning with going forward in time was it needed to work with any exchange, and using the `end_time` parameter would be specific to FTX/FTXUS.

My gut feeling is that it has to with FTX/FTXUS and not ccxt but saw this issue here and wanted to get feedback as to the behavior @springrider and I were seeing.

Thanks for taking the time to look into this.

**Comment by kroitor** [comment]
@jacobthetechy FTX aligns the resulting range for your personal trades to end_time. The end_time is set to current timestamp by default. That explains the the results you see with FTX's fetch_my_trades. There's no easy way around it. We would be interested to know, what would you suggest? We are working on a better unification for the pagination schemas, so that the user would know if the page is aligned to a "since" timestamp or to a "before" timestamp.

**Comment by jacobthetechy** [comment]
@kroitor Thanks for the speedy reply! I've been trying to play with this [example](https://github.com/ftexchange/ftx/blob/master/rest/client.py) from FTX.US [docs](https://docs.ftx.us/?python#pagination) by using the `start_time` parameter, and it looks to have no effect on the expected outcome. So I will submit an issue with FTX to see what they say about it.

I fully recognize how difficult this could be, and I have only worked with 4 exchanges, so my opinion is limited in that regard.

Would having data be aligned to a `since` timestamp be something to add to the Certification program? From a quick look at the requirements, there is already the idea of a required structure for incoming data.

There is also the idea that ccxt has for the user to check if a function is available through `exchange.has['function']`. Possibly adding a flag there to indicate what pagination strategy to use would be helpful? Tho, this has the problem of introducing more issues. For FTX it would require knowing to use the `end_time` parameter for that to work, while other exchanges would have a different parameter names.

**Comment by kroitor** [comment]
> Possibly adding a flag there to indicate what pagination strategy to use would be helpful? 

Yep, that's exactly what I meant under the extra unified "metainfo" above.

**Comment by jacobthetechy** [comment]
So I found what the issue is! 

ccxt needs to remove the limit parameter from the request URL. FTX/FTXUS must be parsing backwards internally, but hitting the limit set before getting to the `start_time`. Because ccxt is using `limit` to manually slice the returned values, the fix below should not have any issues.

Here is a quick fix for until it can be pushed to master

```python
import ccxt


class ftx(ccxt.ftx):
    def fetch_my_trades(self, symbol=None, since=None, limit=None, params={}):
        self.load_markets()
        market, marketId = self.get_market_params(symbol, 'market', params)
        request = {}
        if marketId is not None:
            request['market'] = marketId
        # Having this in the request URL cause FTX to ignore the start_time 
        # parameter and returns the most recent trades from the end_time 
        # to the limit specified
        # if limit is not None:
        #     request['limit'] = limit
        if since is not None:
            request['start_time'] = int(since / 1000)
            request['end_time'] = self.seconds()
        response = self.privateGetFills(self.extend(request, params))
        trades = self.safe_value(response, 'result', [])
        return self.parse_trades(trades, market, since, limit)
```
Here are the results from the change

```python
trades = [(i['id'], i['timestamp']) for i in exchange.fetch_my_trades()]

# returns
[('1318456', 1613877495598), 
('1318635', 1613878357516), 
('1329210', 1613939466053), 
('1329542', 1613940244273), 
('1352172', 1614004622606), 
('1426760', 1614179986020),
...
('10339246', 1621680371355),
('10510210', 1621788779640), 
('10591216', 1621841794352),
('11498023', 1622651426749), 
('11498159', 1622651552748), 
('12326808', 1623374226139)]

trades = [(i['id'], i['timestamp']) for i in exchange.fetch_my_trades(limit=4)]

# returns as expected
[('10591216', 1621841794352),
('11498023', 1622651426749), 
('11498159', 1622651552748), 
('12326808', 1623374226139)]

trades = [(i['id'], i['timestamp']) for i in exchange.fetch_my_trades(limit=4, since=1613877495598)]  # since first trade

# returns as expected
[('1318456', 1613877495598), 
('1318635', 1613878357516), 
('1329210', 1613939466053), 
('1329542', 1613940244273)]

```

Here is the process I followed that lead me to see what the issue was.

I was in the process of submitting an issue with FTX and was using this [example](https://github.com/ftexchange/ftx/blob/master/rest/client.py) they provide to better write out for my explanation for the issue we were having.

I then modified [this](https://github.com/ftexchange/ftx/blob/master/rest/client.py#L148) function to allow adding parameters

```python
    def get_fills(self, **kwargs) -> List[dict]:
        return self._get(f'fills', kwargs)
```

Going through these test made me realize that adding the limit parameter to the URL is what was causing the issues we were seeing.

```python
from ciso8601 import parse_datetime
from operator import itemgetter

f = FtxClient('YOUR_KEY', 'YOUR_SECRET')

def parse_data(data):
    # Adding timestamp to match ccxt to make easier to compare
    for i in data:
        i['timestamp'] = parse_datetime(i['time']).timestamp()
    
    # sorting by timestamp and printing
    for i in sorted(data, key=itemgetter('timestamp')):
        print(f"{i['id']}, {i['timestamp']}")


parse_data(f.get_fills())

# return all trade data
1318456, 1613877495.598703
1318635, 1613878357.516783
1329210, 1613939466.053169
1329542, 1613940244.273037
1352172, 1614004622.606824
1426760, 1614179986.020709
...
10339246, 1621680371.355843
10510210, 1621788779.640863
10591216, 1621841794.352599
11498023, 1622651426.749859
11498159, 1622651552.74806
12326808, 1623374226.139195

# time is in secs not ms
parse_data(f.get_fills(start_time=1614997422))

# returns
1589503, 1614997422.033616
1720551, 1615723482.138025
2451346, 1618149003.243224
6156984, 1619917240.930174
10339246, 1621680371.355843
10510210, 1621788779.640863
10591216, 1621841794.352599
11498023, 1622651426.749859
11498159, 1622651552.74806
12326808, 1623374226.139195

parse_data(f.get_fills(start_time=1614997422, end_time=1622651426))

# return data as expected
1589503, 1614997422.033616
1720551, 1615723482.138025
2451346, 1618149003.243224
6156984, 1619917240.930174
10339246, 1621680371.355843
10510210, 1621788779.640863
10591216, 1621841794.352599

parse_data(f.get_fills(start_time=1614997422, limit=4))

# returns data not expected!
10591216, 1621841794.352599
11498023, 1622651426.749859
11498159, 1622651552.74806
12326808, 1623374226.139195

parse_data(f.get_fills(limit=4, end_time=1622651426.749859))

# returns as expected
10339246, 1621680371.355843
10510210, 1621788779.640863
10591216, 1621841794.352599
11498023, 1622651426.749859
```

**Comment by kroitor** [comment]
> Here is a quick fix for until it can be pushed to master

From your explanation it follows that you should not send the `limit` argument to fetchMyTrades, then it will not be populated in the call. We will not remove it from the master, cause it's under a conditional – if `limit` is specified, it will not be sent. So the user already has the control over it in the current version of the lib.

**Comment by jacobthetechy** [comment]
> From your explanation it follows that you should not send the limit argument to fetchMyTrades

No it is still useful. In fact it is passed through `parse_trades()` -> `filter_by_symbol_since_limit()` -> `filter_by_value_since_limit()` where the results are then "limited" 

```python
...
if limit is not None:
            array = array[-limit:] if tail else array[:limit]
...
```

If I'm reading the code correctly, it doesn't make sense to me to send `limit` to the API to then do that same later. 

Also in the API docs for both [FTX](https://docs.ftx.com/) and [FTXUS](https://docs.ftx.us/) I could not find any reference to add `limit` to the URL parameters. So by including it in the request URL, it is introducing unexpected behavior by making the results align to the `end_time`.

I appreciate hearing your thoughts.

**Comment by kroitor** [comment]
> No it is still useful. In fact it is passed through `parse_trades()` -> `filter_by_symbol_since_limit()` -> `filter_by_value_since_limit()` where the results are then "limited"

Then, if you omit the `limit` argument, you should filter those trades on your side: `trades = trades[:limit]`.
In general, the design of the lib is such that when the exchange supports a certain argument, it is either sent to the exchange if the user specified it, or not sent to the exchange, if it's not required and the user has not specified it. That aligns with the other exchanges (we're not an FTX-specific lib, since we have other exchanges as well, those have to be accounted for, and the majority is generalized). The counter-argument to removing that parameter from the query is that other users might not want the extra traffic at all. So a proper solution to it would be adding the support for the counting direction on the exchange side in the API.

> If I'm reading the code correctly, it doesn't make sense to me to send `limit` to the API to then do that same later.

It does make sense, since not all exchanges will support the `limit` parameter at all, and if the user has specified it, the resulting list should be limited anyway.

**Comment by jacobthetechy** [comment]
I really appreciate you taking the time to respond. Any chance to learn from great developers is a good day in my book!

I guess my failing was with testing pagination with the `limit` parameter. Being new to the crypto world, I don't have enough activity to need pagination (for now), but needed a way to test it. 

I do have some question for you if you don't mind answering.

> In general, the design of the lib is such that when the exchange supports a certain argument, it is either sent to the exchange if the user specified it, or not sent to the exchange, if it's not required and the user has not specified it.

With this specific case for FTX the `limit` parameter in the request URL does not seem to be documented based on my research. Why include it with the request instead of leaving it to the user to add it `params`? Especially if it creates behavior that is different to other endpoints on the API. 

> We are working on a better unification for the pagination schemas, so that the user would know if the page is aligned to a "since" timestamp or to a "before" timestamp, as well as other metainfo about the exchange specifics

I understand the way I was using it was improper in the context of pagination. In this specific case with FTX you would need to specify the pagination strategy with each endpoint and with each combination of function parameters used since the behavior changes.

> > If I'm reading the code correctly, it doesn't make sense to me to send limit to the API to then do that same later.

> It does make sense, since not all exchanges will support the limit parameter at all, and if the user has specified it, the resulting list should be limited anyway.

Correct. For instance, `kraken.fetch_my_trades()` does not add the limit parameter to the URL but is trimmed later by the base `Exchange.filter_by_value_since_limit()`. My proposed change would be the same. Take out the limit in the URL and allow the base class method to handle the trimming. This would make the behavior act the same across endpoints, and the user still has the ability to add the limit parameter back into the request by way of `ftx.fetch_my_trades(params={"limit": True})`.

> The counter-argument to removing that parameter from the query is that other users might not want the extra traffic at all.

Regardless of anything of my thoughts, this is the best counterpoint made. And this specifically should be made aware with FTX since this changes the expected behavior depending on endpoint and is not documented. I will make sure to add this in my new issue made with them.

Hope this all make sense, and again thank you for your time.

**Comment by kroitor** [comment]
> With this specific case for FTX the `limit` parameter in the request URL does not seem to be documented based on my research. Why include it with the request instead of leaving it to the user to add it `params`? Especially if it creates behavior that is different to other endpoints on the API.

Actually, hold on a sec, from what we see in the history, it was added that way back in 2019: https://github.com/ccxt/ccxt/commit/2b949f8974a510e6042b4edc49affd3a5e163a49#diff-02a94d5a3c4522c71285b8365221364890b611b2a8ed14cefca312bbb113152b Tbh, it's quite hard to restore the logic behind it, i guess, it's there for historical reasons. I don't see it documented in the FTX API docs anywhere, so maybe we should indeed remove it from the query. Thanks for pointing it out!

> Regardless of anything of my thoughts, this is the best counterpoint made. And this specifically should be made aware with FTX since this changes the expected behavior depending on endpoint and is not documented. I will make sure to add this in my new issue made with them.

Please, let us know if you have any progress on that. Thx again!

**Comment by kroitor** [comment]
@mssikf check the answers here: 

- https://github.com/ccxt/ccxt/search?q=ftx+Only+have+permissions+for+subaccount&type=issues

```
exchange = ccxt.ftx({
    'apiKey': main_account_api_key,
    'secret': main_account_secret,
    'headers': {
        'FTX-SUBACCOUNT': 'YOUR_SUBACCOUNT_HERE'
    }
})
```
