### ISSUE TITLE
Ccxt exchange request speed drops 10 times in version 1.50.74

### ISSUE THREAD

**Issue by squirrelsquare** [ccxt/ccxt#9357]
- OS: Mac and Windows
- Programming Language version: Node
- CCXT version: 1.50.74

Hi, Kroitor! 

Thank you a lot for your hard work and excellent framework.

After update ccxt version 1.46.47 to 1.50.74 exchange request speed drops 10 times on all exchanges.

For example on Binance function fetchOrderBook speed drops from 50 milliseconds to 500 milliseconds. Also speed became same on local and low latency server, so it looks like some delay added in new ccxt version.

Do you have any idea how to fix it? Thank you in advance.

**Comment by kroitor** [comment]
This edit was added at the time when Binance changed their API rate limits. As documented in the Manual, it's up to you to tweak it for your needs or to disable the built-in rate limiter entirely and make your own. By default it's a sub-optimal average. In other words, this change was actually initiated by Binance itself (due to high loads on their systems). Let us know if that does not answer your question.

- https://www.binance.com/en/support/announcement/f3d75a44fc7b4610b080b9c3499ed075
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Feel free to reopen this question or just ask further questions if any.
