### ISSUE TITLE
Documentation not clear on Canceling Orders

### ISSUE THREAD

**Issue by tuloski** [ccxt/ccxt#9429]
In the documentation of Canceling Orders it is not clear what is returned by exchange.cancelOrder.
It seems that sometimes it's only a string with the id and sometimes the complete Order structure object. Are there other cases? Is this exchange dependant? Is it only missing some implementations in some exchanges?

**Comment by carlosmiei** [comment]
Hello @tuloski,
Unfortunately, there is no standard response from the exchange when canceling an order. Every exchange has its own way of doing it (some return the created order, some return only a success status, etc) so yes, it is exchange dependant. When the exchange returns with the created order, we return it parsed, otherwise, we just forward the exchange response.

**Comment by kroitor** [comment]
Just to add to this issue and to clarify:

We have 3 unified methods for canceling orders:

1. `cancelOrder` for canceling a single order by id, must return an order structure. If it's not unified in some exchanges or does not return a unified order structure – that has to be fixed in the lib and that is a work that still has to be done, @tuloski @carlosmiei let me know if you can find or fix any occurrences of those.
2. `cancelOrders` for canceling multiple orders by multiple ids. It currently returns exchange-specific responses everywhere, since it's quite hard to unify. It should probably return a dict of canceled and non-canceled ids.
3. `cancelAllOrders` for canceling multiple orders with or without a symbol. It currently also returns exchange-specific response everywhere for the same reason.

(1) Should already be mostly unified.
(2) + (3) is still a question on how to better unify those, we are gathering exchange response samples for an overview later.
