### ISSUE TITLE
Has a library security audit ever been done? 

### ISSUE THREAD

**Issue by skeller88** [ccxt/ccxt#943]
I'm really impressed by this library. What a great resource! I'd love to use it. I'm digging into the code. 

Has any security audit been done of this library recently, or are there people using this library in public production systems who can vouch for the security of it? One component of an audit is a [source code analysis tool](https://www.owasp.org/index.php/Source_Code_Analysis_Tools). Another is pen testing. [Open source software is a significant attack vector for hackers](https://www.csoonline.com/article/3157377/application-development/report-attacks-based-on-open-source-vulnerabilities-will-rise-20-percent-this-year.html). A common problem with OSS is that everyone else assumes that everyone else will do an appropriate security review, and so no one does. I'm not saying that's happening with this library, but I'm curious if that discussion has taken place amongst the contributors. 

Unfortunately, this library is a juicy target because it's probably being used to trade millions of dollars of currencies at this point. If an attacker inserts malicious code that transfers money to whatever btc address they want, for example, that'd be bad. 

If an audit hasn't been done, I'd like to potentially help. I searched for "ccxt" in a few vulnerability databases and didn't find anything:

- [NVD](https://nvd.nist.gov/vuln/search/results?adv_search=false&form_type=basic&results_type=overview&search_type=all&query=ccxt)
- [CVE details](https://www.cvedetails.com/google-search-results.php?q=ccxt)
- [Rapid7](https://www.rapid7.com/db/search?utf8=%E2%9C%93&q=ccxt&t=a)
- [VulDB](https://vuldb.com/?search)
- [Exploit database](https://www.exploit-db.com/search/?action=search&q=ccxt&g-recaptcha-response=03AMPJSYW7oNmVFLZMdq99ZPza_4zo4RRiK7u-snUo46x2LZy6fy0E6PNv1yl44B8_bsF8x5DIQZP7SRcWoXtVUlgtZtd7lbAGsRDapCjYA61PIvCGhLSRHRmszW_UbXBRu0eFQAWnJWtMeQIq5nGYq19IKq5HRwOOfjIfVWseGslRD4AS-AA_fCCOihcj244PqfxlW4OW1CJmQAs5dYcp8UmbXbWK8cllXzn7uIEbXpXoBXBtHBNtsdLfGDKAYrs0diyHCVT1_ErkZi6ZmKEIB2tsuh35V6aI93W4PnE3NBpPshoYCg93dnGf5XHJbN2VnPvabweguSSnwLaT_nMyAcIBYy_lffp8yoQG4XaerrYjbSp0lJ-9VP-n2_VeHofqiF5LIa831E8Y)

**Comment by snowboardinsteve** [comment]
Personally, I read every line of the code before including it in my trading system, and deleted the code for exchanges I am not using. I also repeat that process for updating the library.

I didn't find anything malicious, or any obvious security issues (in the Python version) however I am not an expert.

Good idea. Maybe Kroitor can do an ICO-funded professional review :D

**Comment by kroitor** [comment]
> A common problem with OSS is that everyone else assumes that everyone else will do an appropriate security review, and so no one does. 

I am not assuming this, and, I guess, @snowboardinsteve does not assume that too. So, I can't agree that everyone assumes a proper review from someone else – I never trust anyone else for reviewing my security. I'd recommend you to stop assuming that and and start checking your sources anyway. This would solve the problem for you ;) And if you are concerned about the security of other people, then, please, help us spread this word ) Everybody should stop trusting the code blindly.

> I'm not saying that's happening with this library, but I'm curious if that discussion has taken place amongst the contributors.

The discussion is going on right now, right here )

> If an audit hasn't been done, I'd like to potentially help. I searched for "cctx" in a few vulnerability databases and didn't find anything:

Don't know if this is intentional, but you made a typo that is a security flaw. The library is called **ccxt**, not cctx ;) My advice on security: pay attention to each symbol literally )

**Comment by skeller88** [comment]
>  Everybody should stop trusting the code blindly.
I personally am not trusting this code yet. That's why I brought up this issue. My hope is that this issue will prompt a useful discussion and an impromptu crowdsourced security audit :). 

> Don't know if this is intentional, but you made a typo that is a security flaw.

Oops on that typo! Thanks for correcting. Ironically, I searched for "ccxt" in the databases.

**Comment by kroitor** [comment]
> My hope is that this issue will prompt a useful discussion and an impromptu crowdsourced security audit :)

I'm all for it! Would love to take part in this, happy to assist with actions and answers, if someone decides to dive into it.

> Are there areas of the code base that are particularly open to attack that I can focus on?

If I knew about them, I would be fixing them right now instead of writing this answer ) 
The single source of security is the implementation of the `sign()` method for each particular exchange. This is done in exact correspondence to their own rules for generating secure numbers.  So, I guess, the library is as strong as is the SSL+HMAC256/512+nonce.

More about it here:
- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#api-keys-setup
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce

Let me know if you have specific questions on that, I'll be happy to explain.

**Comment by thijstriemstra** [comment]
@kroitor would be really good if you can use pgp to sign your git commits.

**Comment by kroitor** [comment]
@thijstriemstra I will add a signature, thx!

**Comment by BohdanTkachenko** [comment]
I want to add that to be 100% sure that you can use this library you should not only check source code of this library, but also check all dependencies and basically the whole dependency tree. Attackers may add some malicious code to some small library in dependency tree and package manager will just fetch it because it can be just patch version change. So my point is that somebody can hack into this library even if you 100% sure that code of this library is safe.

**Comment by BohdanTkachenko** [comment]
In addition, code in GitHub can be not the same as code in NPM, so basically you should install library with all dependencies somewhere in an isolated environment and check source code of actual installed dependency tree and only after that you can be sure that only this exact snapshot with all dependencies is secure.

**Comment by kroitor** [comment]
@BohdanTkachenko true! Thanks for bringing this up!

**Comment by skeller88** [comment]
@snowboardinsteve that's a great idea. How do you keep the repo updated...do you maintain a separate repo fork and after applying the changes, delete the folders you don't use? 

@kroitor How many admins are there for this repo? Are only admins allowed to approve PRs? I ask because the fewer people allowed to approve PRs, the more secure the repo should be. Within reason.

**Comment by kroitor** [comment]
@skeller88 

> @kroitor How many admins are there for this repo? 

3 admins.

> Are only admins allowed to approve PRs? 

Yes.

> I ask because the fewer people allowed to approve PRs, the more secure the repo should be. Within reason.

If you take a look here: https://github.com/ccxt/ccxt/pulls?q=is%3Apr+is%3Aclosed it should be obvious, I approved and merged most of pull requests myself )

**Comment by thijstriemstra** [comment]
@kroitor see https://help.github.com/articles/signing-commits-using-gpg/ ;)

**Comment by kroitor** [comment]
@thijstriemstra yep, thx, i've read it immediately after your previous comment, will set it up shortly.
