### ISSUE TITLE
Add KuCoin fetch_orders() support.

### ISSUE THREAD

**Issue by vandenberghinc** [ccxt/ccxt#9564]
Could you add fetch_orders() support for exchange KuCoin.

Exception:
    ccxt.base.errors.NotSupported: fetch_orders() is not supported yet

**Comment by kroitor** [comment]
> Could you add fetch_orders() support for exchange KuCoin.
> 
> Exception:
> ccxt.base.errors.NotSupported: fetch_orders() is not supported yet

No we cannot add KuCoin fetchOrders, because KuCoin's API endpoint for orders needs a status and can either return just the open orders or just the closed orders. It cannot return both open + closed. Therefore in CCXT KuCoin does not have fetchOrders, but it has fetchOpenOrders and fetchClosedOrders, depending on which orders you need (this is documented in CCXT's Manual: https://github.com/ccxt/ccxt/wiki/Manual#querying-orders) . In other words, CCXT already supports KuCoin's API to its extent, and we cannot work around the API limitation on the exchange side. Hope that answers your question.

**Comment by vandenberghinc** [comment]
Okay thanks for the info!
