### ISSUE TITLE
Bitfinex - fetch_my_trades()

### ISSUE THREAD

**Issue by JamesKBowler** [ccxt/ccxt#9569]
- OS: Ubuntu 20.4
- Programming Language version: python 3.7
- CCXT version: 1.52.94

```python
symbol = 'BTC/USD'
day = 24 * 60 * 60 * 1000
start_time = exchange.parse8601 ('2021-02-25T22:27:44.000')
now = exchange.milliseconds ()
all_trades = []

while start_time < now:

    print('------------------------------------------------------------------')
    print('Fetching trades from', exchange.iso8601(start_time))
    end_time = start_time + day

    trades = exchange.fetch_my_trades(
        symbol=symbol, 
        since=start_time, 
        limit=None, 
        params={
            'endTime': end_time
        }
    )
    if len(trades):
        last_trade = trades[-1]
        start_time = last_trade['timestamp'] + 1
        all_trades += trades
    else:
        start_time = end_time

print('Fetched', len(all_trades), 'trades')
for i in range(0, len(all_trades)):
    trade = all_trades[i]
    print (i, trade['id'], trade['datetime'], trade['amount'])
```

When using `fetch_my_trades()` on either `bitfinex` and `bitfinex2`, the `since` date has no effect and responses return only the last 50 trades for `bitfinex` and 25 for `bitfinex2` api's.

Any help appreciated

Thanks

**Comment by carlosmiei** [comment]
@JamesKBowler  I believe that's because you're not passing a limit to the fetch_my_trade method. In those cases, the default limit will be used, so if the number of trades within the range you've defined with the since parameter is bigger than the limit itself the response will be capped at the limit value. Just bear in mind that these limits may not be high as well. During my tests, I was able to retrieve 999 trades in a single request from the public API, but that limit can vary depending on the endpoint.
(cc @kroitor )

**Comment by ttodua** [comment]
Above answer by @carlosmiei was correct. I'll mark the issue as closed. Let us know if you experience any issue with CCXT.
