### ISSUE TITLE
Retry methods

### ISSUE THREAD

**Issue by leoplct** [ccxt/ccxt#961]
Retry methods by default

- OS: Unix
- Programming Language: JS
- CCXT version:
- Exchange: Bittrex, Gdax, Okcoinusd, bitfinex
- Method:

Quite often the methods stop working because of server issues (eg. timeouts, downtime etc..), so I have to retry the request. I can implement this using "async.retry" but it became quite messy, so would be great to have it by default to all methods..

**Comment by kroitor** [comment]
Thanks for the proposal! We are going to add this feature, hopefully soon.

**Comment by osnwt** [comment]
Let me also remind that would be good to have some control over rate limiting when retrying depending on the retry reason.

As I wrote, if we receive, say, "Nonce must be greater than..." message from Poloniex after few sequential requests (received by the exchange out of order due to TCP delays), there is no sense waiting for backoff, we should repeat the request ASAP and in 99% it will be successful.
So I analize the failed request result and depending on the issue either:
- retry immediately; or
- retry with backoff; or
- return fatal error without retrying.

It may be a hook to install own strategy or select a default one.

A max number of retry attempts, logging function for every try, backoff action for different issues should be configurable where possible.

**Comment by JamesMcGuigan** [comment]
This issue is especially true at times of heavy server load, such as during bubbles and crashes, which may include cloudfare DDOS warnings and I have found it may take 5-10 retires in a try/catch loop before finally getting a successful response

**Comment by mkutny** [comment]
> Quite often the methods stop working because of server issues (eg. timeouts, downtime etc..), so I have to retry the request. I can implement this using "async.retry" but it became quite messy, so would be great to have it by default to all methods.

Having that enabled for all methods might be dangerous. Consider your `await createOrder()` is hanging for a while (it might be hours) because ccxt makes retries internally. Market conditions may change. You probably will not want it.


> Let me also remind that would be good to have some control over rate limiting when retrying depending on the retry reason.

And this one is a good idea!

**Comment by kroitor** [comment]
> Market conditions may change.

This is a very significant argument against a retry on mission-critical calls. Very true.

**Comment by fredfortier** [comment]
A retry feature may be useful, but I find it much more important to have the right kind of error messages (e.g. the distinction between `ExchangeError` and `NetworkError` is critical). This gives me the ability to categorize errors and deciding when to retry. I much prefer this to automated retries.

**Comment by phips28** [comment]
Is there a functionality to retry api requests once after a request timeout?

**Comment by kroitor** [comment]
@phips28 

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

```Python
num_retries = 3
current_try = 0
while current_try < num_retries:
    try:
        response = await exchange.fetch...
        break
     catch RequestTimeout as e:
        current_try += 1 
```

**Comment by phips28** [comment]
Is there no built in wrapper for this? this would result in a lot of code duplicates with the retry code.
We have multiple exchanges and fetching trades, withdrawals/deposits and so on.. would be a lot of copy paste.
Can I somehow monkey-patch the request? 🙈

**Comment by ttodua** [comment]
Retry mechanism has been merged recently. see https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#retry-mechanism
