### ISSUE TITLE
bybit, bimex, bitmart, coinone api isn't working in react (binance, coinbase is working) [CORS]

### ISSUE THREAD

**Issue by givinkwon** [ccxt/ccxt#9853]
![image](https://user-images.githubusercontent.com/22470975/130343790-20724a75-e0cf-422a-a74b-91f21945e4d1.png)

import ccxt from "ccxt"

let bybit = new ccxt.bybit({    
  'enableRateLimit': true,  // required by the Manual
})
let bitmart = new ccxt.bitmart()
let bitmex = new ccxt.bitmex()

console.log(bitmart.loadMarkets(), bitmex.loadMarkets(), coinone.loadMarkets(), ftx.loadMarkets(), bybit.fetchMarkets())

i guess this is CORS Problem.

what should i do to solve this problem?

**Comment by carlosmiei** [comment]
@ttodua I haven't looked into the details, but if this is a CORS problem unfortunately there's nothing we can do about it since the CORS policy is set by the server

**Comment by ttodua** [comment]
@carlosmiei yes, sorry, i had incorrectly assigned to you (i thought it was some ESM related issue) and then immediately re-assigned once I realized it wasnt that. about CORS, I will write you some details in discord channel, as we have some step-forward to add simple CORS proxy support,, so that will be solved for all exchanges.

**Comment by ttodua** [comment]
closing this issue. solving CORS problem in browsers is easier for users, if they run CORS redirection snippet on their local device, see `sample-local-proxy-with-cors` script in https://github.com/ccxt/ccxt/blob/master/examples
