### ISSUE TITLE
Buy USD with CCXT

### ISSUE THREAD

**Issue by soumyadeeproy12** [ccxt/ccxt#9862]
Hello, 

I just wanted to know if there's anyway with CCXT where I can buy USD using debit card/ACH payment depositing and put the amount in wallet for trade in future, say in Binance?

Please label this as question

**Comment by kroitor** [comment]
Hi! No, CCXT does not have any specific functionality to cover your deposits, since that is beyond the scope of the lib. CCXT lets you do everything the exchange allows you to do, call any endpoint with any set of params, as you like, but CCXT cannot talk to the banks and other structures required in the depositing process. CCXT is about cryptocurrency exchanges, mostly. Hope that answers your question.
