### ISSUE TITLE
Phemex how close position

### ISSUE THREAD

**Issue by nik4152** [ccxt/ccxt#9962]
In Phemex market I create order
exchange.create_order()
and then don't know how close order\position?

exchange.cancel_order() cancel only Take Profit and Stop Loss order how general order cancel Limit\Market

**Comment by carlosmiei** [comment]
Hello @nik4152 
When dealing with contracts trading, we have two different concepts: canceling a pending contract order and closing an ongoing contract order.

We can cancel a pending contract order by using the regular cancelOrder method (first example snippet below). However, orders from the type of 'market' are very difficult to cancel, since they're filled at the next available price. Limit/stop-price orders may stand for a long time depending on price movement, so it's much more likely to be successful doing it. 

Regarding contract orders already filled, there is no direct way of canceling them. In these cases, we just issue the same order but in the opposite direction, nullifying our initial exposure (second example).

```Python
import ccxt  # noqa: E402

exchange = ccxt.phemex({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'apiKey': 'apiKey',
    'secret': 'secret',
    'options': {
        'defaultType': 'swap',
    },
})

exchange.set_sandbox_mode(True)  # uncomment to use the testnet sandbox

amount = 10
symbol = 'BTC/USD;USD'

# Opening and Canceling a pending contract order (unrealistic price)
order = exchange.create_order(symbol, 'limit', 'buy', amount, '20000') # order id: 1b947cb7-c2a2-4181-a405-441913b0ebda

exchange.cancel_order(order['id'], symbol)

# Opening and exiting a filled contract position by issuing the exact same order but in the opposite direction

# Opening a long position
order = exchange.create_order(symbol, 'market', 'buy', amount)

# closing the previous position by issuing the exact same order but in the opposite direction
# with reduceOnly option to prevent an unwanted exposure increase
orderClose = exchange.create_order(symbol, 'market', 'sell', amount, None, {'reduceOnly': True})
```
