### ISSUE TITLE
Question: API key and subprocesses

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#9989]
Hi, 

A general question. If we want to use different subprocesses for different market in the same account in the same exchange. would it be better to use a single API Key or create an API key for each process?

thanks,

**Comment by Matoran** [comment]
It won't work for most of the exchanges for handling correctly the rate limit. One or multiples keys have the same problem as the rate limit is by user and not by API Key (for most exchanges).

If you want multiple subprocesses you will need handling rate limit between them manually.

**Comment by kroitor** [comment]
@pickmone as @Matoran noted, you might run into rate-limiter problems attempting to access different APIs with the same keys simultaneously in parallel. Therefore, to handle it properly you will either need to manage the rate limits across your subprocesses, or use one API keypair per subprocess so that they don't conflict. The rate limiter is described here:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Hope that answers your question, let us know if not.

**Comment by pickmone** [comment]
yes, thank you for the insights.
